### ISSUE TITLE
No knife or rolling pin in the gateway beach

### ISSUE THREAD

**Issue by lilahnovi** [tgstation/tgstation#78695]
Reporting client version: 514.1589

## Round ID:
[215750](https://scrubby.melonmesa.com/round/215750)

## Reproduction:

I went through the gateway I *believe* on lava station? (The station that is built into the asteroid) and ended up on a beach.
![image](https://github.com/tgstation/tgstation/assets/124811534/34d7eafa-e0ba-4045-892d-6df0f7d8ecd9)
While on the beach, I went to the little bar, and decided to start cooking. 
However, the space is missing major cooking items like knives and a rolling pin. So despite having lots of ingredients, I couldn't actually make much.
May be prudent to put a utensil vendor into this space, or a closet filled with knives, rolling pins, pots, pans, bowls, etc.

**Comment by BlueMemesauce** [comment]
Presumably fixed #78568

**Comment by SyncIt21** [comment]
@Sealed101 ^
