### ISSUE TITLE
Codex Cicatrix Transmutation not working

### ISSUE THREAD

**Issue by BHat0451** [tgstation/tgstation#78739]
## Round ID:
[215933](https://scrubby.melonmesa.com/round/215933)

## Testmerges:
#78217 
#78406 

## Reproduction:
With the balance changes introduced in #77939 the Codex Cicatrix was changed into a roundstart knowledge for Heretics. I attempted to transmute the Codex using several combinations of the listed potential ingredients, including library books and bibles, as well as monkey hide and leather (both of which should be interchangeable for the recipe) and a fountain pen. No matter the combination of book, hide and pen, the Codex refused to be transmuted whatsoever, failing to display balloon messages or provide any sort of feedback as to why the ritual failed.

To replicate, grab a book, a unique pen, a hide, and a transmutation rune. Attempt to transmute a Codex Cicatrix using said ingredients. Fail to receive any feedback as to why the transmutation failed.

**Comment by carlarctg** [comment]
It works with dead mobs in place of the wrapping ingredient. I neglected to test with stack ingredients as that clearly already works (clueless)

**Comment by Absolucy** [comment]
seems to have been an error in the code's logic, fixed it downstream here: https://github.com/Monkestation/Monkestation2.0/pull/881
