### ISSUE TITLE
Meson vision shows people behind walls indirectly, in some situations.

### ISSUE THREAD

**Issue by SingeStheos** [tgstation/tgstation#78737]
## Reproduction:

Using meson vision as a borg (or in any case, but i dont have confirmation this works as a non-borg) allows you to see people removing items from containers, as well as between pockets. It may even extend to locker items, but I am not sure. I was in MetaStation in the Justice room and I was able to see someone remove items from their backpack and put them back in. This may be xray and gives an unfair advantage.

**Comment by private-tristan** [comment]
old bug  #39799

**Comment by SingeStheos** [comment]
Well then.
