### ISSUE TITLE
The GMM lets you commit embezzlement.

### ISSUE THREAD

**Issue by lizardqueenlexi** [tgstation/tgstation#78731]
## Round ID:

No specific round. Tested on a local server running current tg master.

## Reproduction:

**REQUIRES THE FIX IN #78729 TO REPRODUCE.** Otherwise you can't use the market at all.

1. Be a member of cargo.
2. Build a materials market.
3. Select any mineral to order with your private account. This can be as cheap as a 1 cr sheet of iron.
4. Switch to using the cargo budget before the order is shipped.
5. Select as many minerals as you want. Observe the cargo budget draining.
6. Call the supply shuttle.
7. Retrieve the crate. Note that it is a private crate with your name on it.
8. Open the crate with your ID. Make off with potentially tens of thousands of credits worth of minerals that no one else can even access!

I did not specifically test if this works the other way around (draining someone's personal account for a cargo department order), but I assume it would work the same way.

**Comment by carlarctg** [comment]
feature
