### ISSUE TITLE
icebox escape pods are ass

### ISSUE THREAD

**Issue by Admiral-Gigaton** [tgstation/tgstation#78735]
Reporting client version: 514.1589

## Round ID:
[215918](https://scrubby.melonmesa.com/round/215918)

## Testmerges:
- [Pipe gas visuals](https://www.github.com/tgstation/tgstation/pull/78217)
- [adds boxes of bandages, and bandages to go in them](https://www.github.com/tgstation/tgstation/pull/78406)

## Reproduction: nukies go delta, escape, land inside greentext box room, see second pod fall next to us, be afraid, then a third land on top of you, killing the entire pod you were in. all pods seemed to have landed inside the same place and everyone got giga gibbed.

![image](https://github.com/tgstation/tgstation/assets/130595499/b7e32b44-9c9b-4e08-857c-d262d2146956)

**Comment by BlueMemesauce** [comment]
I think heretic blade shatter has the same problem. it teleported me to that room and i was stuck in gbj
