### ISSUE TITLE
Railing Ending Dirs Misaligned

### ISSUE THREAD

**Issue by unit0016** [tgstation/tgstation#78741]
## Round ID:
N/A, Noticed On Webmap

## Testmerges:
N/A

## Reproduction:
#78598 introduced new railing sprites. Neat!
However. 
The railing endings are misaligned on every already-placed instance.
![image](https://github.com/tgstation/tgstation/assets/50649185/a0cfb737-ddc3-4004-8380-8e5640e6bc22)

**Comment by ArcaneMusic** [comment]
Looks like the two rail endings in this photo need to be swapped specifically

It's an easy enough fix, but it's worth cross referencing against the existing mapped railings to make sure it's consistent as opposed to mapping new ones in to confirm they all link (hahaha oops...)
