### ISSUE TITLE
Clown Planet Biodome's last door is broken

### ISSUE THREAD

**Issue by Richie9999** [tgstation/tgstation#78784]
Reporting client version: 514.1589

## Round ID:
[216084](https://scrubby.melonmesa.com/round/216084)

## Testmerges:
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)

## Reproduction:
Arrive in lavaland_biodome_clown_planet.dmm map ruin. Survive slippery floor puzzle. Reach final door. Open final door. Enter through final door and slip right into the disposal chute. Try again and repeat until madness is achieved or you acquire a tool that lets you just break the puzzle. 

It could be that something has been deliberately changed with the final door and the slip there that I'm unaware of, but from observations of bitrunners running the lavaland_biodome_clown_planet.dmm based map that is normally seen on lavaland, I have yet to see them come up with a solution for the last door that doesn't involve throwing one of the other bitrunners over the threshhold of the door. Otherwise, if you go through that last door, you will slip right into the disposals opposite the door and back to the start. 

Normally I mine so when I encounter that ruin I just cheese the last door with miner loot. After discussion with other players some talk of just disassembling the walls of the final room. However, bitrunners encountering this map are somewhat limited in ways they can solve the problem. 

Back when I was a newer miner, before using lavaland loot to cheese the door's slip (heiro club mainly) I remember the last door would slip you towards the disposal chute before you got kicked off to the side either landing on one of the glass tables flanking the chute or stuck between the chute, the table and the trophy case. You might get hurt a bit getting out of that spot, but it was still doable solo.

I could be wrong, but it seems to me that the last door is bugged given that, without someone else, or extra tools (things that a bitrunner or even miner cannot always rely upon having) a solo player cannot fully solve the ruin's puzzle, despite getting through all of the slippery floors.

**Comment by Profakos** [comment]
The door is not bugged, it is fully intended to work like this on lavaland. However, this is still an issue, and the domain version of the ruin should be edited indeed.

**Comment by Richie9999** [comment]
So, to be perfectly clear. The last room in intended to be functionally unlootable unless you introduce foreign elements to it on lavaland?

**Comment by Maurukas** [comment]
I do not really want a lavaland ruin to be dependent on cheesing it with gear, or using multiple players. If we're going to automatically recycle all lavaland ruins for bitmining, this is even more important.

**Comment by Profakos** [comment]
> So, to be perfectly clear. The last room in intended to be functionally unlootable unless you introduce foreign elements (heiro club, telecubes, no slips-not sure if those'd work-, maybe the fancy boots or just breaking down the wall) to it on lavaland? Or for literal years have I and many others just been bumbling in there through the door and looting the place without those due to a bug

Its a mean ruin. And the easiest way to cheese it is to have a second person throw you diagonally.

**Comment by gueba14** [comment]
Just so people understand, i do not blive that the map has a problem, it's intended to make people think outside the box.
I'm gonna say how this is suposed to be completed:

Spoilers

You are suposed to brake the tables in the room with the lamp and then make a table frame in front of the final door, then drag the frame in the door space, finish the table and you can climb over it with out sliping letting you loot the inside.

**Comment by Richie9999** [comment]
In all my time on the TG servers this is literally the very first time I've heard of that being the planned solution for the puzzle. I have never seen anyone so much as attempt it that way.

**Comment by Maurukas** [comment]
> You are suposed to brake the tables in the room with the lamp and then make a table frame in front of the final door, then drag the frame in the door space, finish the table and you can climb over it with out sliping letting you loot the inside.

This doesn't seem to work. It's not possible to drag a table frame into a tile with an airlock on it, it just causes the airlock to cycle. This may have been possible into the past, but it does not currently seem to be without destroying the airlock.

**Comment by gueba14** [comment]
> > You are suposed to brake the tables in the room with the lamp and then make a table frame in front of the final door, then drag the frame in the door space, finish the table and you can climb over it with out sliping letting you loot the inside.
> 
> This doesn't seem to work. It's not possible to drag a table frame into a tile with an airlock on it, it just causes the airlock to cycle. This may have been possible into the past, but it does not currently seem to be without destroying the airlock.

You dont click in the door tile, you click on the wall to the left of the door
