### ISSUE TITLE
Heretics lose living heart when bitrunning

### ISSUE THREAD

**Issue by SGSDHSD-Enterprise** [tgstation/tgstation#78780]
found on this downstream https://github.com/fulpstation/fulpstation
## Reproduction: 

1. be a heretic with your living heart
2. run a bitrunning domain
3. load yourself in
4. leave via any means
5. notice you no longer have a living heart

**Comment by jlsnow301** [comment]
I do not see bitrunning there. Is there a branch?

**Comment by necromanceranne** [comment]
Check out round 216012

I was a bitrunner heretic. Had this same issue.

**Comment by Momo8289** [comment]
> I do not see bitrunning there. Is there a branch?

Would be this one: https://github.com/Momo8289/fulpstation/tree/sept-tgu-real-100
Sounds like it's reproduceable on tg though
