### ISSUE TITLE
"I Was a Teenage Anarchist" achievment doesn't work

### ISSUE THREAD

**Issue by Samag5** [tgstation/tgstation#78791]
## Reproduction:

Try to get crushed or gibbed by a vending machine and see that you won't getting achievment. On the specified round I was crushed and gibbed at the end of the round and it didn't work.

**Comment by Samag5** [comment]
> did you hit the vending machine to tip it over? i think thats what you have to do

Yeah, that's exactly what I've done. I tried hitting it at low hp to get killed, rolled even gib, tried to hit and stay alive, and still I've got nothing.

**Comment by Time-Green** [comment]
The vending machine needs to kill you

**Comment by Time-Green** [comment]
And yeah uhhh gibbing doesn't work because you don't really die, you just become not
If you want to get it, I suggest setting up a conveyor / disposal chute contraption, it's the only way I've found that is consistent

**Comment by Samag5** [comment]
> And yeah uhhh gibbing doesn't work because you don't really die, you just become not If you want to get it, I suggest setting up a conveyor / disposal chute contraption, it's the only way I've found that is consistent

That's weird, but okay, I'll try it.

**Comment by Samag5** [comment]
> The vending machine needs to kill you

I tought about it while I was looking at code, but people in game said that they got it without getting killed by vending machine.

**Comment by Time-Green** [comment]
> > The vending machine needs to kill you
> 
> I tought about it while I was looking at code, but people in game said that they got it without getting killed by vending machine.

https://github.com/tgstation/tgstation/blob/e41730f6e455c3ece1cd52e3b67aa6c1d11cd953/code/modules/vending/_vending.dm#L864-L865

Looks like it really shouldn’t, but I’ll admit I’m not sure how so many people have the achievement (maybe it got changed or there’s a chance vendor crush kills? I can’t really check properly right now)
