### ISSUE TITLE
Spiderlings get stuck in Sticky Webs (the traps not normal webs)

### ISSUE THREAD

**Issue by SethLafuente** [tgstation/tgstation#78802]
## Reproduction:
Be a young spider or spiderling and try to walk above sticky webs YOU CANT this is a really bad thing and I know not why it happens
![image](https://github.com/tgstation/tgstation/assets/84478872/d2597220-2422-4a2f-b0ac-4c032c7db41e)
This is the code in spiderwebs.dm

**Comment by AtomTheProphet** [comment]
Wait, wasn't this intentional?
