### ISSUE TITLE
Clown Cake & Monkey's Delight cannot be made.

### ISSUE THREAD

**Issue by ophaq** [tgstation/tgstation#78805]
## Reproduction:

For the clown cake, the issue is that it is not listed at all in the recipe list, even when you read the recipe book for cakes. It isn't in the recipe book, but it exists in the wiki.

For the Monkey's Delight, there is an issue where it does not properly mix. When you mix salt in with the rest of the ingredients, it creates salt water. This in turn makes the pot eject the rest of the contents of the soup when it reaches the required temperature. The recipe requires 25u of water and 5u of salt reagent, salt water reagent is instead made and thus you cannot create the soup.

**Comment by Profakos** [comment]
There really should be some kind of soup unit test...

**Comment by carlarctg** [comment]
My bad, missed that recipe when making my PR. Will fix tomorrow, ping me otherwise

**Comment by carlarctg** [comment]
> ## Round ID: This is in any round issue.
> ## Reproduction:
> 
> For the clown cake, the issue is that it is not listed at all in the recipe list, even when you read the recipe book for cakes. It isn't in the recipe book, but it exists in the wiki.
> 
> For the Monkey's Delight, there is an issue where it does not properly mix. When you mix salt in with the rest of the ingredients, it creates salt water. This in turn makes the pot eject the rest of the contents of the soup when it reaches the required temperature. The recipe requires 25u of water and 5u of salt reagent, salt water reagent is instead made and thus you cannot create the soup.

![image](https://github.com/tgstation/tgstation/assets/53100513/3c4306cf-8e86-4e81-8c46-45262366fd3e)

You may wish to update the wiki with this information.
