### ISSUE TITLE
Gondola Bitrunner Issues

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#78804]
Reporting client version: 514.1589

## Round ID:
[216142](https://scrubby.melonmesa.com/round/216142)

## Testmerges:
- [Logging fixes and catches](https://www.github.com/tgstation/tgstation/pull/78788)

## Reproduction:
Load in the gondola bitrunner mission
Turn into a gondola
Realize you've pushed the cache into a location you can no longer remove it from
Turn on and off the simulation to reset
Go into your original pod, become a gondola in space
Suicide
Go to the next pod over and enter it
Turn into a gondola again
Be unable to push the crate at all, even after repeating the process with the third pod
Suffer

![image](https://github.com/tgstation/tgstation/assets/66640614/fc4fb87e-8c87-47f6-97cf-f0188bd52d70)

+ bonus mapping weirdness
![image](https://github.com/tgstation/tgstation/assets/66640614/fbf047c9-0f34-433b-a5fa-a55c7cd585d9)

**Comment by jlsnow301** [comment]
i didn't see this was made after it was reported to me in discord. this was fixed in #78818
