### ISSUE TITLE
Cryo cells don't connect to pipenet on mapload

### ISSUE THREAD

**Issue by lessthnthree** [tgstation/tgstation#78830]
Since https://github.com/tgstation/tgstation/pull/78273 the medical cryo cells mapped in don't connect to the pipenet on mapload.

You have to rotate the cell before it will connect to pipes.

https://github.com/tgstation/tgstation/assets/83487515/e5fde05f-3dd0-4acf-9692-5dc5ad46a00f

## Reproduction:

Load any map with cryo cells

**Comment by FlufflesTheDog** [comment]
Tram specific I believe, since it's the only cryotubes that connect any direction that isn't down

The top cryo tube actually seems to auto-connect to the waste line directly under it, despite the visual connector being on the side.

**Comment by lessthnthree** [comment]
Northstar cryo also faces E/W.

**Comment by lessthnthree** [comment]
The init for the cryo_cell has
```
internal_connector = new(loc, src, dir, CELL_VOLUME * 0.5)
```
for the gas connector in Initialize(), but it seems the gas connector is always direction 2/south, regardless of what dir the cryo_cell is
