### ISSUE TITLE
NtOS error/TGUI unusable

### ISSUE THREAD

**Issue by SinfulBliss** [tgstation/tgstation#78859]
Round ID: [216296](https://scrubby.melonmesa.com/round/216296)

Testmerges: Unsure

Reproduction: Open PDA, door panel, or something that uses TGUI and see this error:
https://i.imgur.com/HjBuVcn.png

Happened for 3 rounds in a row, multiple people in the rounds so not just me. Admin enabling CDN fixed it temporarily for a round.

**Comment by SyncIt21** [comment]
Duplicate #53997.

Some issues will live on forever
