### ISSUE TITLE
Hand Selection does not appear when swapping hands

### ISSUE THREAD

**Issue by Eronymun** [tgstation/tgstation#78869]
Reporting client version: 515.1614

## Round ID:
[216331](https://scrubby.melonmesa.com/round/216331)

## Testmerges:
- [Fixes modified MA overlays potentially causing duplicate overlays](https://www.github.com/tgstation/tgstation/pull/78719)

## Reproduction:

It's probably part of this test merge. If you press X to swap hands then the overlay for the hands act as if you have 4 hands instead of 2 (you need to press x4 times to complete a whole cycle of swapping between all your hands).

**Comment by SethLafuente** [comment]
![mNZZJze](https://github.com/tgstation/tgstation/assets/84478872/6b91900b-780d-4731-9285-d5d59c6615fc)
No longer a bug as shown here for a little while now
