### ISSUE TITLE
NtOS error/TGUI bug

### ISSUE THREAD

**Issue by SinfulBliss** [tgstation/tgstation#78860]
Round ID: [216296](https://scrubby.melonmesa.com/round/216296)

Testmerges: Unsure

Reproduction: Open PDA, door panel, or something that uses TGUI and see this error:
https://i.imgur.com/HjBuVcn.png

Happened 3 rounds in a row, multiple people in the rounds so not just me. Admin enabling CDN fixed it temporarily for a round.

**Comment by Sealed101** [comment]
one issue is enough
