### ISSUE TITLE
Announcements are Smaller than Standard Text

### ISSUE THREAD

**Issue by wulfenbach-jpg** [tgstation/tgstation#78875]
## Testmerges: 
- tgstation/tgstation/pull/77307

## Reproduction:
1. Receive announcement.
2. **PRIORITY ANNOUNCEMENT/CENTRAL COMMAND UPDATE** text is actually smaller than normal text.
![image](https://github.com/tgstation/tgstation/assets/53832839/99da33b1-a7f4-4f43-9b3f-9b448d197db1)
![dreamseeker_08-14-48](https://github.com/tgstation/tgstation/assets/53832839/0e6c8cc4-ac81-4484-ad07-a8ae5d494c68)

**Comment by distributivgesetz** [comment]
how do i manage to fuck this stuff up so badly
