### ISSUE TITLE
Ephedrine does not block bots stuns battons

### ISSUE THREAD

**Issue by gueba14** [tgstation/tgstation#78895]
## Round ID:
[216403](https://scrubby.melonmesa.com/round/216403)

## Reproduction:
Have ephedrine in you
Get stunned battoned by a sec bot
Fall down stunned

**Comment by timothymtorres** [comment]
Epi is not supposed to make you immune to stuns.

**Comment by gueba14** [comment]
Isnt it suposed to make you inmune to stun battons?

**Comment by gueba14** [comment]
> Isnt it suposed to make you inmune to stun battons?

And aren't sec bots suposed to stun you with the stun batton the are built with?

**Comment by GPeckman** [comment]
The Beepsky stun is not mechanically the same as a normal stunbaton. A normal stunbaton inflicts 60 stamina damage and causes a knockdown after a few seconds. Ephedrine makes you immune to the delayed knockdown, that's it. Beepsky just instantly applies a 10 second paralyze, no stamina damage involved. Ephedrine is not meant to block paralysis, and beepsky's stun is not meant to be equivalent to a normal stun baton.

If you would like to be immune to beepsky, bath salts will do the trick.

**Comment by gueba14** [comment]
> The Beepsky stun is not mechanically the same as a normal stunbaton. A normal stunbaton inflicts 60 stamina damage and causes a knockdown after a few seconds. Ephedrine makes you immune to the delayed knockdown, that's it. Beepsky just instantly applies a 10 second paralyze, no stamina damage involved. Ephedrine is not meant to block paralysis, and beepsky's stun is not meant to be equivalent to a normal stun baton.
> 
> If you would like to be immune to beepsky, bath salts will do the trick.

I didn't know that, still feels a bit iffy that a bot that is constructed with a stn batton does not stun batton you but paralize you, but i think i understand why
