### ISSUE TITLE
Chem is boogered real bad

### ISSUE THREAD

**Issue by Toparai** [tgstation/tgstation#78906]
## Reproduction: Attempt to make phenol, attempt to delete 30 units of chems in a beaker with 30 units of phenol, 30 units of acetone and 30 of diethylamine

 Chem is broken in various ways. Firstly - reactions often leave 0 of a reagent, sometimes give .99 of a reagent when they shouldn't. Often (like the example above) the deletion of chems isn't distributed right. I have gotten 10/25/25 12/24/24 and 15/22.5/22.5 of that example on different occasions. There have also been problems with using buffers - they don't work if the beaker is full. The first 2 of these have been confirmed by another player, so it's almost definitely not client-side.
![Screenshot 2023-10-10 200430](https://github.com/tgstation/tgstation/assets/82719198/ac691199-dd23-4ff0-9ab1-7fefc947c3cf)
![Screenshot 2023-10-10 200512](https://github.com/tgstation/tgstation/assets/82719198/125fc45a-7c83-40c5-9be6-79e51f4aee67)
Next image after removing 30 units
![Screenshot 2023-10-10 200535](https://github.com/tgstation/tgstation/assets/82719198/2027ef34-7795-456d-9f9b-165b77fa6362)

**Comment by Sealed101** [comment]
continuation of #78890 which was also mentioned in the issue's comments
