### ISSUE TITLE
You can deepfry a modsuit into oblivion

### ISSUE THREAD

**Issue by zxaber** [tgstation/tgstation#78928]
## Testmerges:
#78524

## Reproduction:
- Handcraft modsuit, add no modules
- Deepfry
- Open deepfried modsuit with screwdriver
- Add Storage Module
- Add slice of bread to modsuit storage window
- Open modsuit's storage
- Click on bread while holding modsuit
- Modsuit is added to bread, which exists inside modsuit
![image](https://github.com/tgstation/tgstation/assets/37497534/9f0f6414-e7a3-4aeb-bac5-82d6ec9d381c)

Even still, the suit storage works, which means that you have a modsuit-sized storage that exists inside itself. Though, you can't re-open the storage window if you close it.

If you leave the modsuit bread inside the modsuit, it'll exist with your mob as the loc. If you are gibbed, it gets deleted.

**Comment by GPeckman** [comment]
I wonder if you can do similar things with backpacks?

**Comment by BlueMemesauce** [comment]
> I wonder if you can do similar things with backpacks?

You can't add things with storage to the deepfryer. This bug is bypassing that since the storage module is only being added after the frying. I think there's two ways to solve this, either you can't fry modsuits or you can't add new modules to fried modsuits
