### ISSUE TITLE
The AI can view cameras inside Bitrunning Virtual Areas

### ISSUE THREAD

**Issue by BurgerLUA** [tgstation/tgstation#78936]
Coderbase is on Bubberstation (A downstream of a downstream of a downstream).

https://github.com/Bubberstation/Bubberstation

## Reproduction:

1. Jump to a random unknown on camera because you're an AI powergamer.
2. Oh it's an unknown bitrunner in the syndicate ship.
3. Oh god it's a virtual area.
4. Oh god I can shock and bolt doors.
5. Oh god what have I done.

**Comment by rageguy505** [comment]
It's just the AI also playing video games with the bitrunners

**Comment by nikothedude** [comment]
I'd argue this should be canomized as feature,.I mean the ai is the electronic operator of the station right

**Comment by BurgerLUA** [comment]
I had that thought too. It would be a funny feature if the AI could help out bitrunners, however that may defocus the AI's core responsibilities of killing lizards and using vox to read woody's got wood.

**Comment by jlsnow301** [comment]
> I'd argue this should be canomized as feature,.I mean the ai is the electronic operator of the station right 

Ok
