### ISSUE TITLE
Chemical factories still appear to be broken

### ISSUE THREAD

**Issue by MidoriWroth** [tgstation/tgstation#78945]
## Round ID: N/A

Chemical factories still appear to be broken, even after the PR that was supposed to fix them merged.

![4Ihs7C6](https://github.com/tgstation/tgstation/assets/18170896/0ce4876e-b914-4227-88ad-7313c313d00b)
This reaction chamber is supposed to fill to that amount provided, but seems to just stop right before it's supposed to with the water and locks up, and even overfills with the hydrogen.

![KIbtQWI](https://github.com/tgstation/tgstation/assets/18170896/161410dc-27ba-4ff1-90a5-4d86219d82fd)
This chemical press is set to 50 units, but then stops at 49.9998 units and locks up.

These are just some examples but it happens to quite a few things with factories.

**Comment by SyncIt21** [comment]
This is expected because look at what I specifically said in the previous PR

> Also, it's fine if we don't get exact amount of each reagent when transferring and we end up with some incorrect math, there is no such performance criteria to be achieved, this is much better than having missing reagents altogether & less code to debug overall so it's a win.

Now the solution is pretty simple just round the result before displaying it to chat but I did not want to do that incase people wanted to see exact amounts.

Floating point math is not perfect you have been lied too I just merely exposed it by rounding it to 4 decimal places and not 2 before displaying but if people only want to see whole numbers then sure I'll do that

**Comment by SyncIt21** [comment]
Luckily this code is specific to reaction chamber and not reagents as a whole. I'll see what I can do

**Comment by MidoriWroth** [comment]
it wouldnt be a problem if the whole system didnt still lock up because of it

**Comment by SyncIt21** [comment]
> it wouldnt be a problem if the whole system didnt still lock up because of it

Yeah I still don't understand why that happens.  For now you can just use a plunger on everything to restore it till I figure out what's happening

**Comment by SyncIt21** [comment]
> Luckily this code is specific to reaction chamber

I was wrong this is related to reaction chamber & plumbing as a whole. Hopefully it should be fixed by the above PR now
