### ISSUE TITLE
Dragons won't eat or break walls

### ISSUE THREAD

**Issue by tiger8255** [tgstation/tgstation#78953]
Reporting client version: 514.1589

## Round ID:
[216558](https://scrubby.melonmesa.com/round/216558)

## Testmerges:
- [Invisibility refactor](https://www.github.com/tgstation/tgstation/pull/78908)

## Reproduction:

Got the midround dragon roll in round 216558. I couldn't break down walls, clicking them just did nothing. Additionally, I was entirely unable to eat corpses. Clicking on them just attacked them.
Rifts, firebreathing, gust, and regular attacks all worked fine.

**Comment by san7890** [comment]
Space Dragons, per the code, aren't meant to break down the walls:

![image](https://github.com/tgstation/tgstation/assets/34697715/7806a9b7-b89f-48e0-ad50-88cfa622c374)

They need at least `ENVIRONMENT_SMASH_WALLS`, which they explicitly lack. However them not eating corpses is rather weird, should be looked into.

**Comment by san7890** [comment]
Oh wait they can break through walls through some flakey code. uhhh i'm just gonna rewrite this
