### ISSUE TITLE
Laser carbines are a tad too strong vs spider webs

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#78989]
Reporting client version: 514.1589

## Round ID:
[216646](https://scrubby.melonmesa.com/round/216646)

## Testmerges:
- [Tram v6/Transport Subsystem](https://www.github.com/tgstation/tgstation/pull/78230)

## Reproduction:
Step 1: Locate your nearest spider nest that likely took several minutes to build
Step 2: Equip the carbine and hold left click
Step 3: Watch as the entire nest is destroyed by a SINGLE CARBINE

I think it might be wise to lower this thing's object damage or something cause holy shit it just melts through webs like butter and that is probably unintended

**Comment by Jacquerel** [comment]
I believe that lasers don't _have_ a separate projectile damage from their regular damage
Carbine lasers do 10 damage, webs have 15 health.
They take 1.25x damage from burn damage, but would be destroyed by two shots anyway.

**Comment by GPeckman** [comment]
Its only marginally better at it than a normal laser gun. A normal laser takes one shot to destroy webs and has 16 shots in a full cell, so 16 destroyed webs before it needs charging. The carbine takes 2 shots to destroy webs and has 40 shots in a cell, so it can destroy 20 webs before needing a recharge.
