### ISSUE TITLE
SCREAM FOR ME DOESN'T WORK, WOUND REFACTOR BROKE IT

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#79017]
## Reproduction:

SCREAM FOR ME DOESNTW ORK!!! YOU HIT A DUDE WITH IT AND THEY SCREAM BUT DONT GET ANY WOUDNS

**Comment by nikothedude** [comment]
im sorry please stop yelling :(

**Comment by carlarctg** [comment]
> im sorry please stop yelling :(

YOU RUINED MY WIZ ROUND ONE MILLION YEARS DUNGEON
