### ISSUE TITLE
mooks act as solid walls

### ISSUE THREAD

**Issue by LePiromano** [tgstation/tgstation#79032]
the mooks at the mook village in lavaland act as completely solid walls, you can't crawl under them or push them. they even act like solid walls when dead and can't be gibbed.
![image](https://github.com/tgstation/tgstation/assets/55637865/0f99429d-9f2b-46da-aaf4-bf9cf461e4fd)
(this is a death trap)

**Comment by san7890** [comment]
@Ben10Omintrix didn't you or jacq make an element to make them passable on death?

**Comment by san7890** [comment]
this was allegedly fixed
