### ISSUE TITLE
Weakened virus plasma recepie acts weird and broken

### ISSUE THREAD

**Issue by HalfPunch** [tgstation/tgstation#79058]
Reporting client version: 514.1589

## Round ID:
[216871](https://scrubby.melonmesa.com/round/216871)

## Testmerges:
- [Logging fixes and catches](https://www.github.com/tgstation/tgstation/pull/78788)

By mixing Virus plasma and Synaptizine in 1:1 ration you get unexpected results that vary from quanities of reagents. 
## Reproduction:
1 case:
Take 5 u of virus plasma and mix them with 5 units of Synaptizine -> You get 0.53 units of Synaptizine -> Why?
2 case: 
Take 1u of each and mix -> Get Nothing -> What?
3 case:
Take 1u of virus rations, 1u of plasma and Synaptizine and mix them -> you get 1u of virus rations and nothing else.
4 case:
Take 5 units like in 1 case - > add 1 unit of Synaptizine in 5 units of virus plasma -> get 2u of Weakened virus plasma and 4u of virus plasma -> FINALY.
Repeat until 2u of virus plasma left.
Add 1u of synaptizine -> get...
![image](https://github.com/tgstation/tgstation/assets/91390177/67816582-034e-4693-a79e-24f8c99397cf)
![image](https://github.com/tgstation/tgstation/assets/91390177/4feccabe-bd8f-49f3-9886-7190cffc5e64)

**Comment by SyncIt21** [comment]
> Take 5 u of virus plasma and mix them with 5 units of Synaptizine -> You get 0.53 units of Synaptizine -> Why?

https://github.com/tgstation/tgstation/assets/110812394/d22029b9-2f0d-4869-a480-9ecbc6e8e98d

Works for me locally

**Comment by HalfPunch** [comment]
Strange, you can actually go try it on Campbell. Maybe testmerge bug. Maybe just a local Campbell issue. Or it got fixed in latest patches that didn't merged yet

**Comment by SyncIt21** [comment]
It's best to go report this issue on campbell.  Maybe it's specifically a downstream issue
