### ISSUE TITLE
Chemical factories are still broken... Somewhat

### ISSUE THREAD

**Issue by MidoriWroth** [tgstation/tgstation#79051]
Chemical factories appear to be fixed for the most part thanks to #78947 , but not the presses. Presses still lock up specifically when set to 50 unit bottle outputs, as can be seen here: 
![QggilbX](https://github.com/tgstation/tgstation/assets/18170896/bbd878d1-99b9-4cb9-a32d-359758e920d1)

I'm not sure entirely what happens on the code end, but it will produce one 50 unit bottle at first, and then refuse to do so again regardless with whatever you do to change it around and such.

@SyncIt21 All yours pal!

**Comment by SyncIt21** [comment]
(...Smashes keyboard on the wall and starts contemplating life)

**Comment by SyncIt21** [comment]
I'm unable to reproduce this locally.  Created the setup to create Seiver and had the pill factory run for a solid 15 minutes. The only time it stopped producing is when the apc ran out of power. Is that what happened?

**Comment by SyncIt21** [comment]
Above PR should fix it. Shit happens
