### ISSUE TITLE
Virusology is broken completely

### ISSUE THREAD

**Issue by HalfPunch** [tgstation/tgstation#79060]
Reporting client version: 514.1589

## Round ID:
[216871](https://scrubby.melonmesa.com/round/216871)

## Testmerges:
- [Logging fixes and catches](https://www.github.com/tgstation/tgstation/pull/78788)

## Reproduction:
Go get the roundstart Flu virus.
![image](https://github.com/tgstation/tgstation/assets/91390177/3baed2d0-df9e-4f13-a9ae-63db62313369)
Take the syringe and ingect yourself with Flu.
Why am i taking toxin damage?
Why i am not sick?
Oh so you want to say that every time i take infected blood it will just turn into toxin? Really?
Go play Orion trail you Viros!
P.S. Of course it works not only on Flu virus. I tested it twise on Flu and my own virus, both don't work

**Comment by Time-Green** [comment]
You love to see it: virology removing itself

**Comment by HalfPunch** [comment]
Ok, you can actually make a working virus. But no matter how much stealth it have none of the scanners will detect it

**Comment by SyncIt21** [comment]
This is a long shit but #78657 refactored how diseases & stuff inflict damage on mobs. @vinylspiders thoughts?

**Comment by ATH1909** [comment]
there's a non-advanced flu disease (https://github.com/tgstation/tgstation/blob/master/code/datums/diseases/flu.dm) and an advanced flu disease (https://github.com/tgstation/tgstation/blob/master/code/datums/diseases/advance/presets.dm); maybe something is somehow confusing them?

**Comment by FlufflesTheDog** [comment]
Injecting blood that isn't a compatible type will turn it into toxin (the reagent, which deals toxin damage), though that isn't relevant to the application of a disease

Is there any chance you had cybernetic organs, including from the tin man or prosthetic organ quirks? Those can protect against various means of transmission.
