### ISSUE TITLE
Mapping issue with Pubby disposals system in medbay

### ISSUE THREAD

**Issue by Papersmiles** [tgstation/tgstation#79078]
## Round ID:

https://github.com/fulpstation/fulpstation

## Reproduction:

 On pubby, the disposals system in medbay doesn't connect the medbay area with the techfab to the rest of the tubes, resulting in trash going right out the tube under the door and breaking a tile [pic](https://imgur.com/a/OMDCITi)

**Comment by Jolly-66** [comment]
Pubby isn't a map on /tg/station, not in rotation at least.

**Comment by rageguy505** [comment]
this isnt a problem on the pubby in the map depot

**Comment by san7890** [comment]
brotha report this one on the fulpstation repository
