### ISSUE TITLE
Medical cryo cell is transferring far too much cryoxadone

### ISSUE THREAD

**Issue by lessthnthree** [tgstation/tgstation#79083]
Putting someone in the cryo tube is consuming almost the entire beaker of cryox, and transferring insane amounts to their body.

![image](https://github.com/tgstation/tgstation/assets/83487515/ac1eb781-c4d7-419c-87f9-80e9de6e00a6)

## Reproduction:

Put someone in the cryo cell, turn on.

**Comment by SyncIt21** [comment]
Question, was this reported on Campbell?

**Comment by lessthnthree** [comment]
> Question, was this reported on Campbell?

No, I've seen it on Manuel and Sybil.

```
beaker.reagents.trans_to(occupant, (CRYO_TX_QTY / (efficiency * CRYO_MULTIPLY_FACTOR)) * seconds_per_tick, efficiency * CRYO_MULTIPLY_FACTOR, methods = VAPOR) // Transfer reagents.
```
CRYO_TX_QTY is 0.5.
It's now transferring 0.5 per tick instead of the expected 0.04, so I think something changed in how the multiplier is applied.

**Comment by SyncIt21** [comment]
Yup i found the problem. One sec
