### ISSUE TITLE
Docker error trying to set up the TTS server

### ISSUE THREAD

**Issue by cattoman1** [tgstation/tgstation#79094]
im trying to make my own server but when im trying to setup the TTS server which is not been modified in anyway i run cmd and insert
_docker compose up -d_ but then i get the error  `failed to solve: process "conda run -n intel /bin/bash -c pip install Flask &&\tpip install waitress &&\tpip install llvmlite --ignore-installed &&\tpip install torch torchaudio --extra-index-url https://download.pytorch.org/whl/cu118 &&\tpip install pydub &&\tpip install TTS &&\tpip cache purge" did not complete successfully: exit code: 1` im on docker version : 4.24.2 and i have conda and python installed can someone help me here

**Comment by Sadboysuss** [comment]
closing in favor of https://github.com/tgstation/tgstation/issues/86677
