### ISSUE TITLE
Gorillas have long attack delay

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#79092]
## Reproduction:

Player controlled tot' gorilla has 4~ seconds attack delay on mobs. Normal attack delay on objects.

**Comment by Jacquerel** [comment]
Can't reproduce, gorillas spawned locally have the normal mob attack period of 2 seconds.

**Comment by SyncIt21** [comment]
Could have been time dilation on the server

**Comment by antropod** [comment]
I do confirm that attacking a mob feels weird and has a delay between hits.

How to reproduce:
spawn as geneticics
give yourself a traitor
go to role restricted, buy serrum
transform into gorilla
---
attack a window
attack a monkey
compare attack speeds
attacking a monkey has a delay of like 3 seconds between attacks, also it is impossible to land a hit if monkey is moving

**Comment by Dorsisdwarf** [comment]
Fixed by #79238
