### ISSUE TITLE
Buying materials off the GMM without enough credits causes horrible consequences.

### ISSUE THREAD

**Issue by ArcaneMusic** [tgstation/tgstation#79115]
## Round ID:
Missing the round number but this would have occured on 10/18/23, and have confirmed locally.

## Testmerges:
N/A

## Reproduction:

Spawn in a Galactic Mineral Market.
Place an order for 500 units of any one thing. Remove credits from your ID so that you can't afford it if necessary.
Send the shuttle.

Congratuations, you have now entered a nebulous new area as follows.

The GMM prevents a single user from being able to place more than 10 stacks worth of materials in a single order. If that's the case, it will tell them they need to finish the order to buy more. However, a consequence of #78836:

> New Qol: now money will be deducted from cargo budget/your account only after the order is confirmed in the cargo request console & after shuttle is called and arrives with your packages

As these are custom orders in the same vein as mining point custom orders, cargo cannot cancel these orders, locking the user out of the GMM until they can finish their order.

An ideal fix would be for GMM orders to be cancellable, yes, but also for you to be prevented from adding more to an order that you don't reasonably have the funds in that account to afford. (Unless your paying from the cargo account, because that's not tragic, that's funny)

**Comment by isotope436** [comment]
actually iv talked to the original creator of the GMM about that pr and how that one change has completely fucked the GMM and remember him mentioning a rework or removal and honestly thats what needs to happen no one was complaining about the fact the GMM could eat up all the funds and this fix just makes using it annoying and actually causes more problems.
