### ISSUE TITLE
Mansus gate dodge minigame is impossible to survive

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#79113]
Reporting client version: 514.1589

## Round ID:
[217084](https://scrubby.melonmesa.com/round/217084)

## Reproduction:
It seems that when people are sacrificed they're sent to one of the gates. Only to stay in crit and die to the hands before they can even react

**Comment by MrMelbert** [comment]
maybe `heal_and_revive` is busted. 

related?: This revive call uses the old args which is wrong (it should be `revive(NONE, 10)`. 

https://github.com/tgstation/tgstation/blob/47f10ca86071a14ea962d918827b75790eb4737b/code/modules/mob/living/living.dm#L837

**Comment by Jacquerel** [comment]
I have found part of what might be the real problem: The bonfires in two of the five heretic domains have stopped lighting themselves, meaning that people spawn in complete darkness and likely do not realise that the minigame has begun.

**Comment by DaydreamIQ** [comment]
> I have found part of what might be the real problem: The bonfires in two of the five heretic domains have stopped lighting themselves, meaning that people spawn in complete darkness and likely do not realise that the minigame has begun. This seems to be because when they initialize the air in that area has not yet initialized, so they fail to ignite.

I finally got a chance to observe someone in auto observe mode during their sacrifice and it seems that they just stay in crit for the entire duration. I think it's unlikely that the cause Is solely visual

**Comment by Jacquerel** [comment]
The other cause is that someone refactored the "heal you per tick" buff wrong and now unless you have no legs it actually damages you
