### ISSUE TITLE
Ricochet ammo will still hit you even if ricohet_shoots_firer is set to TRUE for (possibly) hitscan projectiles

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#79122]
## Reproduction:
Here, I fired at a wall across from me to the east. The result was shooting myself.
![image](https://github.com/tgstation/tgstation/assets/40847847/6daa12d7-8af1-4e99-a4c6-03cef8fa6eca)

This is potentially just a marksman ammo issue due to it using hitscan. Even if you set the ricochet to not shoot the firer, it will still hit the firer regardless.

This leads to such wonderful situations like shooting yourself with your own bullet if you miss firing in a cardinal direction, or in a very tight room.

**Comment by SmArtKar** [comment]
This flag just ensures that it won't autoaim at the firer, random ricochets are still possible

**Comment by MrMelbert** [comment]
Why did I even self assign this
