### ISSUE TITLE
Gradients are not applied properly to Huge Afros

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#79125]
Reporting client version: 514.1589

## Round ID:
[217138](https://scrubby.melonmesa.com/round/217138)

## Reproduction:
New hairstyle, Huge Afro, does not have gradients applied in the right place, resulting in a vertical split gradient coering half of your face in a droopy, melted mess
![Screenshot 2023-10-20 102320](https://github.com/tgstation/tgstation/assets/88996803/73936892-87eb-4caf-81e5-8412c388b20c)

**Comment by HalfPunch** [comment]
Oh no, it's so messy. I like it

**Comment by OuroborusReporter** [comment]
> Oh no, it's so messy. I like it

It's fully unplayable is what it is, now my Miror B bitrunning cosplay is incomplete!
