### ISSUE TITLE
Knock heretics autowin against nukies

### ISSUE THREAD

**Issue by Annihilit** [tgstation/tgstation#79126]

**Comment by mc-oofert** [comment]
mf just use a nullrod

**Comment by the-orange-cow** [comment]
In order to beat the nukies, they would have to pretty much forfeit their own victory.

**Comment by Jacquerel** [comment]
Maybe we can do something about it but any heretic who would do this is extremely cringe tbh.

**Comment by JupiterJaeden** [comment]
The real issue here is indefinite jaunts which just straight up shouldn’t be a thing.

**Comment by mc-oofert** [comment]
> The real issue here is indefinite jaunts which just straight up shouldn’t be a thing.

untrue and biased opinion

**Comment by Annihilit** [comment]
> Maybe we can do something about it but any heretic who would do this is extremely cringe tbh.

I opened this because it literally happened on Manuel lowpop. I was solo nukie and the acting cap was a knock heretic.

**Comment by mc-oofert** [comment]
> > Maybe we can do something about it but any heretic who would do this is extremely cringe tbh.
> 
> I opened this because it literally happened on Manuel lowpop. I was solo nukie and the acting cap was a knock heretic.

shouldve hit them with literally any holy item that you couldve possibly stole from chapel with arsenal or botany if they grew holymelons

**Comment by Annihilit** [comment]
> > > Maybe we can do something about it but any heretic who would do this is extremely cringe tbh.
> > 
> > 
> > I opened this because it literally happened on Manuel lowpop. I was solo nukie and the acting cap was a knock heretic.
> 
> shouldve hit them with literally any holy item that you couldve possibly stole from chapel with arsenal or botany if they grew holymelons

Thats an extremely unreasonable expectation on a lone op of all things. Either the jaunt needs to be changed or nukies need an affordable null rod

**Comment by xzero314** [comment]
> > Maybe we can do something about it but any heretic who would do this is extremely cringe tbh.
> 
> 
> 
> I opened this because it literally happened on Manuel lowpop. I was solo nukie and the acting cap was a knock heretic. 

Hi I was the heretic. I was actually the chaplain that had just late joined. (Which means I had the null rod haha) I had killed cap though and took the disk and their id. Was honestly as confused as you were.
