### ISSUE TITLE
Caseless ammunition does not properly clear from boltaction guns

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#79128]
## Reproduction:

The only example of this is the harpoon gun. Currently, it is a bolt action. However, if you pull back the bolt after firing, it does not properly rack the bolt and is stuck in a closed position. This requires you to cycle it twice to clear it.

**Comment by TJatPBnJ** [comment]
Oops, it actually IS caused by caseless ammunition, the bolt only opens when there is no bullet chambered. (I didn't realize the new bolt-action rifle was caseless) Although, in the case of bolt actions which aren't caseless, the bolt will still magically open if there's nothing chambered.
