### ISSUE TITLE
You cannot examine anyone beyond being directly next to them.

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#79142]
## Reproduction:
Try and examine someone from further than one tile. You just can't.

Not much more to this one.

**Comment by MrMelbert** [comment]
Cannot reproduce on local master.

If this was on live please include round ID, it's possible `examine` runtime error'd

**Comment by necromanceranne** [comment]
It was indeed on live. I'll get the ID of one of the rounds in a bit.

**Comment by necromanceranne** [comment]
Right, so it works on live currently, so I can give you this round Id and know it is relevant.

https://statbus.space/rounds/217266

**Comment by MrMelbert** [comment]
I believe this is related to #78857

**Comment by necromanceranne** [comment]
Oof makes sense given the proximity nonsense.

**Comment by SyncIt21** [comment]
This still an bug? The test merge was closed a while back

**Comment by MrMelbert** [comment]
Certainly not
