### ISSUE TITLE
Some crafting recipes seem to not work.

### ISSUE THREAD

**Issue by dalmationer** [tgstation/tgstation#79159]
## Round ID :217237

During today's round, I tried to craft a rootdough in the kitchen, but despite having all the ingredients, it seemed I was unable to craft it. Similarly, one of the scientists tried to craft me a motorised wheelchair, and it didn't seem to work either. The crafting menu stayed greyed out as if not all ingredients were present.

## Reproduction:

Attempt to craft an item using the crafting menu.

**Comment by iprice** [comment]
Plus one.  Seems like heavily broken across the board. Stood on a stack of 5 paper, 50 wood, 5 iron, zero items craftable (with there being items using just one of those things, so all sorts of materials broken)
