### ISSUE TITLE
Black out drunk doesn't appear properly in deadchat

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#79163]
Reporting client version: 514.1589

## Round ID:
[217251](https://scrubby.melonmesa.com/round/217251)

## Testmerges:
- [Makes lighting objects objects again](https://www.github.com/tgstation/tgstation/pull/78857)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/62606051/20550ba0-941f-4b01-abba-b682e74904b1)
No name or orbit button is attached to it, it'll just come up with "Is blacking out" sometimes

**Comment by SyncIt21** [comment]
You just made an issue about this. #79138

**Comment by Sealed101** [comment]
dupe as stated above, got fixed (hopefully)
