### ISSUE TITLE
Oh god, have you know you actually can become invisible if you have seethrough ability???

### ISSUE THREAD

**Issue by Voudez** [tgstation/tgstation#79161]
Reporting client version: 514.1589

## Round ID:
[217249](https://scrubby.melonmesa.com/round/217249) (if it matter in general)

## Reproduction:
In theory:

1. Turn yourself into any mob with "Toggle seethrough" ability

2. Spam that ability (~5-10 times)

3. Toggle ability once more (to a the state where mob becomes completely invisible)

After that, if everything done correctly, it makes your mob invisible not only for yourself! (but hit box remains the same)
which means it gives some advantage..?
For example:
1. Become Space Dragon

2. Spam ability real quick

3. Toggle ability once more to the state where mob becomes completely invisible

Current example bad (but more common) because dragon's face and claws still visible which gives indicator that hes there!

**Comment by jlsnow301** [comment]
Confirmed this locally, just spam the ability and go invisible. You also get stuck invisible/transparent
