### ISSUE TITLE
Wackniess with the vorpal scythe 

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#79165]
Reporting client version: 514.1589

## Round ID:
[217255](https://scrubby.melonmesa.com/round/217255)

## Testmerges:
- [Makes lighting objects objects again](https://www.github.com/tgstation/tgstation/pull/78857)

## Reproduction:
So for some reason if I'm holding something in the hand my scythe is attached to, then try to move said item to another hand. Dropping it will set off the vorpal scythe's unsated effect despite it not being deployed

**Comment by DaydreamIQ** [comment]
Actually it seemed to just constantly keep activating the unsated effect regardless so I really have no idea what the cause is

**Comment by necromanceranne** [comment]
Can't seem to replicate it. Was there another chaplain that round?

**Comment by DaydreamIQ** [comment]
Roundstart chaplain. No other chaplains were in the round
