### ISSUE TITLE
Auto juicing plant trait consumes ethanol

### ISSUE THREAD

**Issue by the-orange-cow** [tgstation/tgstation#79166]
Round ID: [217258](https://scrubby.melonmesa.com/round/217258)
BYOND Version: 515.1610
Server revision compiled on: 
Master commit: [3068e1d79bcf7b0b3fa0e250e3bc1c0b53f8ad8c](https://www.github.com/tgstation/tgstation/commit/3068e1d79bcf7b0b3fa0e250e3bc1c0b53f8ad8c)
The following pull requests are currently test merged:
[#78705: 'Spider Infestation Balance Rebalance Expansion Part 2' by SethLafuente at commit bd050d975d](https://www.github.com/tgstation/tgstation/pull/78705)
[#79105: 'Adds a subtle ghost poll' by jlsnow301 at commit b953edee8c](https://www.github.com/tgstation/tgstation/pull/79105)

Local commit: 55e371db6efc252ec9ed92da131624207a38534a
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

The auto juicing trait is supposed to take nutriment and vitamin and convert it to a juice based off the plant it is a trait of.  For some reason, it is also consuming ethanol inside the plant and turning it into juice.  This seems inconsistent with the traits description and core functionality.

There is a good chance this is affecting more than just ethanol, but I haven't exhaustively checked every reagent.

To reproduce:

1. Grow a pineapple, then graft the pineapple
2. Take the graft, and put it on something with ethanol, such as Polypore mushroom (large mushrooms from lavaland).
3. Harvest plant, and notice how the ethanol has been consumed.

**Comment by dalmationer** [comment]
I've observed that this seems to be the case with any 'edible' reagent.

**Comment by the-orange-cow** [comment]
> I've observed that this seems to be the case with any 'edible' reagent.

Yeah, I believe it used to only affect nutriment and vitamin, which makes sense because those are the two 'base' foodstuff reagents.

**Comment by MTandi** [comment]
As of foodening, it converts all subtypes of `reagent/consumable` mainly because I wanted to make the sugar a part of the juice. Since ethanol is a subtype of it, it becomes a part of the juice too.

**Comment by MTandi** [comment]
This is now also true for fermenting btw.

**Comment by Yttriums** [comment]
@MTandi goofy ass behavior, should not work this way

**Comment by ArcaneMusic** [comment]
From `code\modules\hydroponics\grown.dm` line ~120:

```
for(var/datum/reagent/reagent in reagents.reagent_list)
		if(!istype(reagent, /datum/reagent/consumable))
			continue
```

As stated above, it looks like /obj/item/food/grown/ferment() seems to only convert reagent/consumables like fruit juices, and ethanol shares a subtype. juice does similar as well due to a convert_reagent call on /datum/reagent/consumable. Looks like we can safely call this not a bug then for the time being.
