### ISSUE TITLE
Thermal Pistols don't hurt on point blanks, cryo pistol just seems to do nothing

### ISSUE THREAD

**Issue by Nova-Hero** [tgstation/tgstation#79167]
Reporting client version: 514.1589

## Round ID:
[217267](https://scrubby.melonmesa.com/round/217267)

## Testmerges:
- [Spider Infestation Balance Rebalance Expansion Part 2](https://www.github.com/tgstation/tgstation/pull/78705)
- [Adds a subtle ghost poll](https://www.github.com/tgstation/tgstation/pull/79105)

## Reproduction:
1) Get a thermal and cryo pistol.
2) Fire at someone multiple times with an inferno pistol. For me, it did do damage at first and made me feel like an idiot.
3) Fire at someone with a cryo pistol. This should just do nothing.
4) If those do not work, try point-blanking a target with combat mode off. It should look like it hit them while actually doing no damage.
5) Repeat with thermal and cryo pistols and it should do nothing outright.

## Notes:
First observed on previous sybil round by attempting to shoot a monkey with either pistols, doing no damage. After, I had someone shoot me with a cryo pistol and took no damage.

**Comment by necromanceranne** [comment]
Most likely broken by https://github.com/tgstation/tgstation/pull/79024

Could also be an incorrect return somewhere!
