### ISSUE TITLE
Can't enter netpods as paraplegic

### ISSUE THREAD

**Issue by Justice12354** [tgstation/tgstation#79164]
Reporting client version: 514.1589

## Round ID:
[217238](https://scrubby.melonmesa.com/round/217238)

## Testmerges:
- [Logging fixes and catches](https://www.github.com/tgstation/tgstation/pull/78788)

## Reproduction:
While paraplegic, you cannot get into pods.
Doing so while in your wheelchair will trigger the opening animation.
Doing so while on the floor will do absolutely nothing. Other people can put you in the pod though.

Trying to get into a pod while on the floor without being paraplegic works.

**Comment by jlsnow301** [comment]
Are you talking about netpods

**Comment by dalmationer** [comment]
Related to #78901 
You are able to enter the blue auto-generating pods, but it APPEARS you don't-- it just takes your wheelchair then spits you out at the other side.

**Comment by Justice12354** [comment]
> Are you talking about netpods

Yes. Sorry for not specifying

**Comment by Justice12354** [comment]
> Related to #78901 You are able to enter the blue auto-generating pods, but it APPEARS you don't-- it just takes your wheelchair then spits you out at the other side.

In this case, you don't leave the wheelchair to begin with
