### ISSUE TITLE
Deep-frying Epinephrine Medipens for Grinding

### ISSUE THREAD

**Issue by NoeSilent2** [tgstation/tgstation#79178]
## Reproduction:

Take any medipen and try to grind it using a mortar and pestle or an all-in-one grinder. Note that you are **unable** to grind it. This step is not necessary for reproduction, but for understanding the issue.

Place the medipen into a deep fryer and take it out.

Attempt to grind the deep fried medipen using a mortar and pestle or an all-in-one grinder. Note that you are now **able** to grind it and get all the reagents out.

## Why This is an Issue:

Whether or not a medipen has been dipped in hot oil or not should not determine whether or not you are physically able to grind it, and creates an absurd roundabout solution to getting reagents out of medipens.

**Comment by JupiterJaeden** [comment]
feature

**Comment by HalfPunch** [comment]
Definetly a feature. 
I demand only one thing.
Make it unable to inject once it deepfried? something like "some components of pen are stuck in oil". So people would have to eat it to use
