### ISSUE TITLE
Slimepeople can get wounds

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#79174]
## Reproduction:

I got bleeding wound as a slimeman (what can makes copies of himself). Slimepeople always was immune to wounds and I didn't find any PR what changed it.

**Comment by Jacquerel** [comment]
https://github.com/tgstation/tgstation/pull/77813
Slime people can receive slashing wounds but do not bleed from them.

**Comment by SethLafuente** [comment]
Im not sure why this wasn't closed earlier it seems like a non issue and for wounds to be intended for dismemberment so Im going out on a **LIMB** here and close it

**Comment by SethLafuente** [comment]
this one might be more fitting
