### ISSUE TITLE
Shuttle turrets are invisible to all but observers

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#79181]
## Reproduction:

This is true of any turret that isn't spawned inside of a cover. Those turrets are straight up invisible. The responsible code assumes that the turret is in a cover. It has no consideration for turrets without a cover, inheriting the invisibility of the parent.

Almost certainly caused by https://github.com/tgstation/tgstation/pull/78908

**Comment by Isratosh** [comment]
This affects the nuclear operative infiltrator and base turrets, pirate shuttle turrets, emergency shuttle turrets on the Lance, the engineer special traitor item constructible turret, and even the AI satellite and upload turrets that do indeed have a cover (the turrets are still invisible after popping out of the cover).

**Comment by necromanceranne** [comment]
As it's his refactor @ninjanomnom you may wish to be made aware of this ongoing issue.
