### ISSUE TITLE
pAI/Positronic notifications that were previously silent now have a ghost ping and a REALLY big header

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#79195]
Reporting client version: 514.1589

## Round ID:
217310

## Testmerges:
- [Makes lighting objects objects again](https://www.github.com/tgstation/tgstation/pull/78857)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/62606051/03a8e2a1-c7f9-4e1e-a825-e8e57ba9440d)
I never minded them popping up before since it was a small text that didn't blare an alert in your ears every time it was used but with the recent change ghosts get a ping every time its pressed. Not sure if the subtle ghost poll pr will fix this or not since its merged but not updated on Manuel right now so disregard this if it does I suppose?

Edit: This also got rid of the old positronic sound and replaced it with the default ping which makes it super annoying to distingish

**Comment by jlsnow301** [comment]
not the new subtle ghost poll but #79139
