### ISSUE TITLE
using the power of THE NET to mostly-safely humanify ape escape helmet'd monkeys

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#79190]
1. strap an ape escape helmet to a monkey. if the helmet is removed from their head or they change species, they will be ghosted (this is intended functionality), so don't do that yet.
2. put a linked quantum spin inverter inside of a backpack and have the monkey wear it.
3. have the monkey enter THE NET using a bitrunning pod
4. activate the other quantum spin inverter. this will cause the monkey's body to leave the bitrunning pod without ending their bitrunning session.
5. use a genetics console to humanify the monkey. this will trigger the ape escape helmet's recoil effect, but because the monkey's client is not in their body, they will not be ghosted. There is still around a 7.5% chance of an additional negative side effect happening that could harm their body, though (e.g. gibbing or gorillification).
6. have the monkey leave THE NET and reenter their body.
7. they'll return to their body, but be left in this weird state where they can move around and talk, but can't use their hands.
8. have them enter a different bitrunning pod and then disconnect again.
9. the monkey is now a perfectly normal human with access to their hands and such.
10. the first pod you put the monkey in is now in this weird state where it thinks it's occupied but actually isn't. you can't crowbar it open, and deconstructing it will produce a machine frame and parts as normal, but won't destroy it. sadly, deconstructing it again will not produce more machine frames/parts.

I wish I had pictures for this, but they didn't save properly.

**Comment by ATH1909** [comment]
update: apparently this might cause Very Bad Things to happen to the server. uh, don't do it.

**Comment by necromanceranne** [comment]
@jlsnow301 may want to check this out

**Comment by DaxDupont** [comment]
How do people even come up with this shit
