### ISSUE TITLE
Syndicate Assault bitrunning job can't be completed without destroying transit tube

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#79201]
Reporting client version: 514.1589

## Round ID:
[217325](https://scrubby.melonmesa.com/round/217325)

## Testmerges:
- [Makes lighting objects objects again](https://www.github.com/tgstation/tgstation/pull/78857)

## Reproduction:
The transit tube in the Syndicate Assault bitrunning domain blocks the door into the safehouse. This isn't an issue ormally, because the tube is meant to take you to the equipment storage room, but if you manage to get the cache and try to take it back there to claim it, you have to destroy the tube entrance to get the crate through, because you can't send a crate through the tubes.

![Screenshot 2023-10-22 223703](https://github.com/tgstation/tgstation/assets/88996803/6afe8855-cde8-4022-8a2e-c87815e986aa)

**Comment by jlsnow301** [comment]
> you can't send a crate through the tubes

![dreamseeker_nggA5uNbin](https://github.com/tgstation/tgstation/assets/42397676/c8dbdb00-cb43-41f1-bdfe-a1040b8094fe)

**Comment by OuroborusReporter** [comment]
> > you can't send a crate through the tubes
> 
> ![dreamseeker_nggA5uNbin](https://user-images.githubusercontent.com/42397676/277303211-c8dbdb00-cb43-41f1-bdfe-a1040b8094fe.gif) [ ![dreamseeker_nggA5uNbin](https://user-images.githubusercontent.com/42397676/277303211-c8dbdb00-cb43-41f1-bdfe-a1040b8094fe.gif) ](https://user-images.githubusercontent.com/42397676/277303211-c8dbdb00-cb43-41f1-bdfe-a1040b8094fe.gif) [ ](https://user-images.githubusercontent.com/42397676/277303211-c8dbdb00-cb43-41f1-bdfe-a1040b8094fe.gif)

My old nemesis strikes again: Not being able to tell the left and right sides of the tube apart

**Comment by jlsnow301** [comment]
I'll give you that- they're a little confusing. Closing this as not bitrunning related (you're welcome to open an issue saying the transit tubes aren't obvious)
