### ISSUE TITLE
Infected Domain bitrunning sim loses air and cannot be completed unless you SPEEDRUN

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#79202]
Reporting client version: 514.1589

## Round ID:
[217325](https://scrubby.melonmesa.com/round/217325)

## Testmerges:
- [Makes lighting objects objects again](https://www.github.com/tgstation/tgstation/pull/78857)

## Reproduction:
The Infected Domain sim loses air over time, possibly due to having no walls, instead only being walled with tears in reality. This sim also starts you without a backpack, and with no internals as a result

**Comment by jlsnow301** [comment]
@Rhials

**Comment by Rhials** [comment]
Argh, I used lavaland chasms instead of default chasms, so the air is probably getting replaced with planetary atmos.
