### ISSUE TITLE
Paraplegic bitrunners can't get into the pod

### ISSUE THREAD

**Issue by Noobetski** [tgstation/tgstation#79211]
## Testmerges:
#78705: 'Spider Infestation Balance Rebalance Expansion Part 2' by SethLafuente at commit bd050d975d

## Reproduction:
1. Choose paraplegic quirk in loadout
2. Spawn in as bitrunner
3. Understand that you can't close the pod while you're on the floor and you can't enter the pod while you're buckled to wheelchair.

**Comment by jlsnow301** [comment]
duplicate #79164
