### ISSUE TITLE
mod shield gennerators are capped to a range of 3.75 and a charge of 70 no matter how many machines you add

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#79218]
## Round ID:
[217361](https://scrubby.melonmesa.com/round/217361)

## Reproduction:
![Screenshot (656)](https://github.com/tgstation/tgstation/assets/61211748/e91d5abc-3f47-4671-8f23-1f3ecec5e024)
build modular shield generators with more than 3 relays and many wells and see that no matter how many you add you cannot go over 70 charge or 3.75 range

**Comment by moocowswag** [comment]
you see the little red and green lights on them?

the red light is on and the green light is off

that means those machines are not linked to the main generator

you link machines together with a multi tool after changing their orientation to match.
