### ISSUE TITLE
Androids can be medipenned, but do not metabolise the results, leading to bad mood traps on overdosing

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#79223]
Reporting client version: 514.1589

## Round ID:
[217374](https://scrubby.melonmesa.com/round/217374)

## Reproduction:

Like the title, while hypospray's and piercing syringes wont work on an android, an epipen or other types of medipen will, will insert their reagents into the android, who will not metabolise them from blood, but still acquires the overdose bad mood.

**Comment by Xackii** [comment]
[https://github.com/tgstation/tgstation/pull/79234](url)
