### ISSUE TITLE
Plasmaman bitrunner with claustrophobia dies from permanent choking upon exiting domain

### ISSUE THREAD

**Issue by timothymtorres** [tgstation/tgstation#79226]
Reporting client version: 514.1589

## Round ID:
[217380](https://scrubby.melonmesa.com/round/217380)

## Testmerges:
- [Spider Infestation Balance Rebalance Expansion Part 2](https://www.github.com/tgstation/tgstation/pull/78705)

## Reproduction:

1. Spawn as plasmaman with claustrophobia quirk
2. Enter bitrunner domain for several minutes while putting on internals and exploring
3. Get bored and exit domain
4. Plasmaman internals are disconnected and start choking
5. Reconnect plasmaman internals but it doesn't stop the choking
6. Die a slow and unavoidable death

**Comment by MrMelbert** [comment]
user error

**Comment by deathrobotpunch** [comment]
error 404 HOW2BREATHE.exe is not found
