### ISSUE TITLE
GMM poorly tuned, easy to make Bicycle money through buying low and selling high.

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#79247]
## Reproduction:
Miming or buying from GMM and selling when prices are high makes it too easy to generate absurd amounts of credits. Its simply too easy to make money on longer rounds, doubly on mineral-rich IceBox. Partially a problem with the bug that doesnt actually inventory sheets on GMM, but just having sufficient minerals from mining allows you to make far more money than cargo should have on a given round. A smart player on high-pop could conceviably make a million credits in an hour long round, which is a definite problem.

**Comment by YakumoChen** [comment]
As an addition, some aspects of GMM don't make sense, like restocking. I've seen the GMM restock minerals when the prices are very low, instead of high, which makes it easy to buy them cheaply (ignoring the outstanding bug) 

Prices don't seem to naturally crash at low stock, and the actual availability of sheets doesn't seem to hinge on price.

**Comment by YakumoChen** [comment]
You can rapidly inflate your money with something as low value as silver. It crashes at 25 credits and is plentiful. With 500 sheets (10 stacks) you can go from 12.5k credits to 67k credits (after the 20 sale cut)

Having several players using their own account (taking half cargoes cut with wraps and bar codes) to but stacks just has a multiplier on how fast you can rack up stacks.

**Comment by Jacquerel** [comment]
Among a couple of other issues, the market is bugged right now due to the concept of limited not simply not actually working, there's a cap to how many minerals any arbitrary number of people would be able to buy which simply isn't applying at the moment.

**Comment by YakumoChen** [comment]
> Among a couple of other issues, the market is bugged right now due to the concept of limited not simply not actually working, there's a cap to how many minerals any arbitrary number of people would be able to buy which simply isn't applying at the moment.

The market is still going to be very easy to play even after that's fixed, just in part due to very large profit margins. 

Even then, assuming sold minerals add to the pool and roughly stays the same until manipulated, you could simply wait for the price to crash and re-buy what you just sold.

**Comment by YakumoChen** [comment]
The market fluctuates too wildly, too often. Nearly every time something trends down, it doesn't stop until it hits near its minimum, and when it trends up, even the most expensive minerals give 6x returns on a typical high.

It does these in 5 or so minute cycles constantly, it's more rare to see a material price stagnate and that's usually due to a market event.
