### ISSUE TITLE
vileworm spit atacks hit directly and bypass mechs?

### ISSUE THREAD

**Issue by gueba14** [tgstation/tgstation#79246]
## Round ID:
[217437](https://scrubby.melonmesa.com/round/217437)

## Testmerges:
unk

## Reproduction:
get shot by a vileworm while in a mech

**Comment by moocowswag** [comment]
Were you in a ripley mk1?

Projectiles can hit the pilot of a ripley directly.

**Comment by Jacquerel** [comment]
I can't replicate this when testing it locally

**Comment by githubuser4141** [comment]
> Were you in a ripley mk1?
> 
> Projectiles can hit the pilot of a ripley directly since the only thing covering the cockpit is basically a grille / lattice of rods.

This is an opinion piece but vileworms aren't aiming their shots, right..? They are sprayingband praying that they'll score lots of hits, then they search for their kill to eat them. A Ripley mk1 doesn't stand at human height, the pilots canopy looks like it covers the pilots legs which are above a the heads if someone on the ground. So really, vileworm spit should be hitting the mechs legs or the lower canopy, not the pilot.

**Comment by Jacquerel** [comment]
ok well we don't model that in this video game
