### ISSUE TITLE
medical PENLITE holobarrier does NOT stop passage through it from people with diseases

### ISSUE THREAD

**Issue by deathrobotpunch** [tgstation/tgstation#79248]
## Reproduction:
1. make a PENLITE holobarrier using the medical PENLITE holobarrier projector
2. have a disease that can be detected by health analyzers
3. walk through
4. wonder why it lets you through even though your sick

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/ab058330b4449f133b7672565c91d28af8ed7e05/code/game/objects/structures/holosign.dm#L150-L196

It's likely that someone disabled it, since all it requires is someone to click on it with their hand.

**Comment by timothymtorres** [comment]
So I just tested it now and this part:

https://github.com/tgstation/tgstation/blob/ab058330b4449f133b7672565c91d28af8ed7e05/code/game/objects/structures/holosign.dm#L185-L189

means that any type of harmless disease, like coughing or sneezing, will allow people to still pass through. When I increased the disease lethality, I could not pass.

**Comment by MrMelbert** [comment]
Good catch, I didn't even know you could disable access. ~~Also why would you ever disable access that's so useless~~

**Comment by deathrobotpunch** [comment]
ok thanks for letting me know!
