### ISSUE TITLE
Growth serum does not have a cap on increasing mob size and will look extremely funky and broken when vaped to the extreme

### ISSUE THREAD

**Issue by Isratosh** [tgstation/tgstation#79267]
Reporting client version: 514.1589

## Round ID:
[217479](https://scrubby.melonmesa.com/round/217479)

## Testmerges:
- [Makes lighting objects objects again](https://www.github.com/tgstation/tgstation/pull/78857)
- [Cuts the number of `apply_damage` copypaste procs from 3(.5) to 1, fixing a few bugs along the way](https://www.github.com/tgstation/tgstation/pull/79207)

## Reproduction:
1. acquire a vape with growth serum (I do not actually know how this was accomplished on this particular round, but I believe it may have been botany growing Fly Amanita plants? regardless, they were handing out vapes with growth serum in them)
2. put it in your mouth and suck
3. achieve a puberty level growth spurt every 5-10 seconds, using up miniscule quantities of the reagent each time
4. realize there is no upper bound on this growth
![](https://i.imgur.com/vlyoxvY.png)
Me after using the vape for a few minutes on view range 10, using up less than 5 units of growth serum

**Comment by timothymtorres** [comment]
Your momma so fat, she blocks out the screen

**Comment by Isratosh** [comment]
When sufficiently enbiggened, these mobs appear completely invisible. This bug has become a minor admin issue on the servers and I've handled a few players abusing this (players reading this beware). I have confirmed the growth serum source to be botany.
