### ISSUE TITLE
"Feature" Request: Certain Chaplain armors should get a bit of a coding fixup IMO

### ISSUE THREAD

**Issue by Hotmud9** [tgstation/tgstation#79274]
The chaplain "Leader" clothing puts the hood on both the suit and in the hat/helmet slot:
![image](https://github.com/tgstation/tgstation/assets/44795537/ff355cba-a8b2-41fb-9ab2-b405db2dbef7)
And the Divine Adept kit has a literal _HOOD_ that is a separate item from the armor instead of being an integrated hood, which is absolutely ANNOYING to store
![image](https://github.com/tgstation/tgstation/assets/44795537/a499dc3d-3507-45b1-a470-049210218079) ![image](https://github.com/tgstation/tgstation/assets/44795537/4c4ec2f7-768f-44b6-bd7b-2f01a2ea881f)
I feel like some tweaks are in order here

**Comment by deathrobotpunch** [comment]
make the feature request on the forum not in the issues section of github. this is for bugs only silly!

**Comment by Hotmud9** [comment]
Ah, eto.
*Bleh!*
