### ISSUE TITLE
Diagnostic HUDs do not update mech health or energy until that specific mech is entered or exited

### ISSUE THREAD

**Issue by Hotmud9** [tgstation/tgstation#79273]
## Round ID:
Every round ever since mechs got completely overhauled by PR #77221

## Testmerges:
N/A

## Reproduction:
Equip Diagnostic HUDs of any type (alternatively just ghost or be an observer)
Watch a mech get hit by something enough times
See that it doesn't update at ALL

**Comment by GPeckman** [comment]
I think I found the cause. In #77221, the `process` proc had its functionality split into 3 separate procs, and each proc has different conditions to be run. Probably for performance reasons. The part of the code responsible for updating the mech health hud was put into `process_occupants`, which, you guessed it, only runs if there is at least one person inside the mech.

I have to run now, so I can't really look into fixing it.
