### ISSUE TITLE
Tesla Zaps of all kinds now stun.

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#79297]
## Reproduction:

Well the most direct way you will find this out is if someone goes to genetics, gets themselves shock touch with the power chromosome, and then goes and touches someone. 

Anyone who isn't insulated from tesla zaps will be stunned by the tesla zap. Even though this particular tesla zap isn't flagged to stun.

Congratulations, Genetics now has aoe stun hands for all who aren't wearing at least an engineering hardsuit or have the insulated gene.

**Comment by necromanceranne** [comment]
If I had to take a guess, it's possibly related to some of the refactors that took place here https://github.com/tgstation/tgstation/pull/78310

It's also potentially why the zaps also do a considerable amount of damage on top of this. 

In addition, Tesla armor also seems to have this property, but lost a lot of its chaining power. It however now very rapidly kills people the more it procs.

**Comment by Pickle-Coding** [comment]
Can you tell me what the expected damages and stuff are? Kinda odd that all tesla zaps would stun if they aren't supposed to.
