### ISSUE TITLE
Possible oversight with Agent Ids and Cham Pdas

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#79305]
Reporting client version: 514.1589

## Testmerges:
- [Makes lighting objects objects again](https://www.github.com/tgstation/tgstation/pull/78857)

## Reproduction:
So if you get any pda and an agent ID, have someone message your pda and then change your identity. Instead of their recent messages staying as the old identity, it'll instead change to your current one. Immediately blowing your cover if that person happens to be paying attention

**Comment by Dorsisdwarf** [comment]
I dont think this is a bug, PDAs are supposed to update their name when you change the identity of the ID in them and messenger program sends connections between PDAs not between names.
