### ISSUE TITLE
RPD advanced design discs cannot be put into an RPD

### ISSUE THREAD

**Issue by restedwaves** [tgstation/tgstation#79301]
Reporting client version: 514.1589

## Round ID:
[217541](https://scrubby.melonmesa.com/round/217541)

## Testmerges:
Master commit: [8ac1bcfe164eef7504cd95743eac8d783f5c5a22](https://www.github.com/tgstation/tgstation/commit/8ac1bcfe164eef7504cd95743eac8d783f5c5a22)
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 1
Allow Latejoin Antagonists: 1

## Reproduction:
attempt to insert the advanced design disk into the RPD
fail miserably

Note: I also tried printing a fresh RPD to put the disc in and that also didn't work

**Comment by GPeckman** [comment]
As far as I know RPDs (Rapid Pipe Dispensers) don't have disks. Are you sure you aren't getting them mixed up with RCDs (Rapid Construction Devices)?

**Comment by SyncIt21** [comment]
Both RCD(any upgrade disk) and RPD(rapid unwrenching upgrade disk) have the name "Advanced design disk" in their name.

I'm sure that must have confused you and you tried to insert an RCD disk into the RPD by mistake cause I can't reproduce in local

**Comment by restedwaves** [comment]
> Both RCD(any upgrade disk) and RPD(rapid unwrenching upgrade disk) have the name "Advanced design disk" in their name.
> 
> I'm sure that must have confused you and you tried to insert an RCD disk into the RPD by mistake cause I can't reproduce in local

Nope, i'm certain it was the unwrenching disc that wasn't working. unless there's another disc that has something about being linked to the pipe destroyer button.

I wasn't able to see if anyone else could use the disk so i can't say if it somehow has something to do with that.

**Comment by SyncIt21** [comment]
So you can insert the disk into the RPD by clicking on the disk with it. You however cannot click on the RPD with the disk.

**Comment by restedwaves** [comment]
RCD ones were able to be clicked onto the device itself, i imagine whatever PR fixed that forgot about the RPD.
i'll amend the report
