### ISSUE TITLE
Becoming one with The Net for pseudo-fleshmend and perpetual stasis

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#79329]
1. Link two quantum swappers and hold them in your hands.
2. Activate one of them and drop it.
3. Enter a bitrunning pod with a simulation loaded just before the swap, such that the swap occurs during the do_after() for you entering The Net.
4. You will be swapped out of the pod, halting the process of sending you into The Net... but letting you keep that nice pod stasis status effect.
5. This status effect regenerates you quite swiftly (4 brute/burn per process tick, among other things) and keeps you in a state of stasis, similar to a stasis bed. You are not immobile, though, and can run around and do _most_ of the things you can normally do. Activating items in-hand, using action buttons, and opening inventories will stymie you, but you can still pick things up, change clothes, attack people, etc.
6. murderbone or get your organs removed or something idk

![beyonddeath3](https://github.com/tgstation/tgstation/assets/42606352/c71fe24e-390a-45f5-a73c-ff8500c4b1a0)
![image](https://github.com/tgstation/tgstation/assets/42606352/feee0907-bb70-4de6-abab-43119bde013b)
being in stasis makes most bleeding wounds harmless, so you can do funny things like this

**Comment by jlsnow301** [comment]
Thank you for all this bug hunting. Unhinged edge case scenarios, but the code is better for it
