### ISSUE TITLE
Dualwielding with a carbine type lasergun will allow the second non carbine gun to shoot at the same speed

### ISSUE THREAD

**Issue by trexter5555** [tgstation/tgstation#79331]
roundID 217639

get a carbine laser (i used the practice carbine) and another laser (normal egun)

the egun is now shooting at the same speed as the carbine

this works with ballistics and hilariously enough makes the russian revolver actually shoot like a 357

[combat mode is not required for this, firing the carbine with combat mode off will still fire the other gun]

**Comment by necromanceranne** [comment]
Same as https://github.com/tgstation/tgstation/issues/72705 but laser carbines shouldn't be able to be dual-wielded to begin with so that is a unique bug onto itself.

**Comment by GPeckman** [comment]
I tried to make it impossible to duel wield with laser carbines specifically to avoid this issue.

**Comment by GPeckman** [comment]
Wait, the practice carbine actually decided to allow dual wielding them. At least its an easy fix.
