### ISSUE TITLE
All guns fire very, very slowly.

### ISSUE THREAD

**Issue by Robustitron** [tgstation/tgstation#79350]
## Testmerges:
[#79316: 'Extends Halloween' by Jacquerel at commit 9cc0f029d3](https://www.github.com/tgstation/tgstation/pull/79316)
[#79340: 'Changes how halloween lighting works slightly' by LemonInTheDark at commit b85e056734](https://www.github.com/tgstation/tgstation/pull/79340)

## Reproduction:
I've noticed guns seem to fire at a rate of about 1 shot per 2-3 seconds.  regardless of their normal fire rate, this also applied to laser carbines. Time dilation was between 5-15% at the time.

The guns I've tried that round, where this happens, are:

-Laser gun
-Practice Laser Carbine
-Detective Revolver
-CTF laser

I didn't try the other guns, but they could have the same problem as well.

This also seems to coincide with the muzzle flash sprite being new, but who knows if that's related.

**Comment by Robustitron** [comment]
In the following round, 217695, it stopped happening.

**Comment by SyncIt21** [comment]
> In the following round, 217695, it stopped happening.

@Dorsisdwarf its best to close this issue based on this comment. Not reproducible on local till date
