### ISSUE TITLE
Blob spores and Blobbernauts don't move

### ISSUE THREAD

**Issue by Profakos** [tgstation/tgstation#79383]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:

Spawn a blobbernaut and a blob spore. Notice they are immobile instead of swarming you to beat you up.

Its probably something to do with a change to JPS two weeks ago, as I was giving a new basic mob JPS pathfinding, they were immobile, so I had change them back to basic avoidence, and they started moving again.

**Comment by lizardqueenlexi** [comment]
I have reproduced this locally, they just stand around and do nothing.

![image](https://github.com/tgstation/tgstation/assets/105025397/223f67c1-e720-4e77-94f7-216dd35352e3)

**Comment by Profakos** [comment]
Further tests show that JPS works for bots, they patrol the station. The blobbernaut was beating me up the moment i stepped next to them, so their AI was active.

**Comment by Profakos** [comment]
Further test: The blobbernauts set up the pathfinding script, which calls start, and adds itself to the list of active pathing.  Search_step however, is never entered.

**Comment by LemonInTheDark** [comment]
bro what the heck
