### ISSUE TITLE
Window sprites aren't updating while being damaged

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#79386]
Reporting client version: 514.1589

## Round ID:
[217779](https://scrubby.melonmesa.com/round/217779)

## Testmerges:
- [Changes how halloween lighting works slightly](https://www.github.com/tgstation/tgstation/pull/79340)
- [Makes lighting objects objects again](https://www.github.com/tgstation/tgstation/pull/78857)
- [Extends Halloween](https://www.github.com/tgstation/tgstation/pull/79316)
- [The Brawlening: Unarmed fighting interactions for shoving, grabbing and nonlethal takedowns (not martial arts)](https://www.github.com/tgstation/tgstation/pull/79362)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/62606051/ff066f94-c343-4974-83da-873b56851884)
Despite how this sprite may appear, the window is actually just about to break. I saw another issue report on this but perhaps this might be only affecting reinforced windows? This occurred on Manuel on Delta and Icebox

**Comment by SyncIt21** [comment]
Duplicate #79082
