### ISSUE TITLE
Nar'sie summon makes ghosts' screen black

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#79415]
Reporting client version: 514.1589

## Round ID:
[217833](https://scrubby.melonmesa.com/round/217833)

## Testmerges:
- [Changes how halloween lighting works slightly](https://www.github.com/tgstation/tgstation/pull/79340)
- [Extends Halloween](https://www.github.com/tgstation/tgstation/pull/79316)

## Reproduction:
Be an observer
Have Nar'sie be summoned
Your screen goes black and you can't see anything

**Comment by Jackal-boop** [comment]
![Screenshot (787)](https://github.com/tgstation/tgstation/assets/61211748/07c6f6ec-911a-4588-82df-5ebba508e833)
