### ISSUE TITLE
Rolling tables stop working

### ISSUE THREAD

**Issue by Dawnseer** [tgstation/tgstation#79411]
Reporting client version: 514.1589

Items stop attaching to rolling tables, making you just leave items behind if you pull or push the rolling table.

![hLy8Lrt](https://github.com/tgstation/tgstation/assets/126404225/550b0d36-e382-4cd3-8c62-06320cbab619)

## Round ID:
[217820](https://scrubby.melonmesa.com/round/217820)

## Testmerges:
- [Changes how halloween lighting works slightly](https://www.github.com/tgstation/tgstation/pull/79340)
- [Makes lighting objects objects again](https://www.github.com/tgstation/tgstation/pull/78857)
- [Extends Halloween](https://www.github.com/tgstation/tgstation/pull/79316)
- [The Brawlening: Unarmed fighting interactions for shoving, grabbing and nonlethal takedowns (not martial arts)](https://www.github.com/tgstation/tgstation/pull/79362)

## Reproduction:
Unsure what causes it, happens inexplicably midround after it working fine for most of it. This is not a particularly new issue and can often be observed.

**Comment by san7890** [comment]
let me know if this still happens
