### ISSUE TITLE
Bitrunning Glitch doesn't trigger sometimes?

### ISSUE THREAD

**Issue by Hotmud9** [tgstation/tgstation#79438]
Reporting client version: 514.1589

## Round ID:
[217884](https://scrubby.melonmesa.com/round/217884)

## Testmerges:
- [Changes how halloween lighting works slightly](https://www.github.com/tgstation/tgstation/pull/79340)
- [Makes lighting objects objects again](https://www.github.com/tgstation/tgstation/pull/78857)
- [Extends Halloween](https://www.github.com/tgstation/tgstation/pull/79316)

## Reproduction:
Wait for bitrunning glitch to trigger
This happens:
![image](https://github.com/tgstation/tgstation/assets/44795537/385f6dd9-3794-47c0-bf3f-30bb965fe0af)

**Comment by jlsnow301** [comment]
yes, this is fixed in the future content patch, see #78997

**Comment by Hotmud9** [comment]
Gaming
