### ISSUE TITLE
Wall-Mounted Flashes instantly stun borgs and holds them in stun for a good 5-10 seconds at the very LEAST

### ISSUE THREAD

**Issue by Hotmud9** [tgstation/tgstation#79449]
Reporting client version: 514.1589

## Round ID:
[217910](https://scrubby.melonmesa.com/round/217910)

## Testmerges:
- [Changes how halloween lighting works slightly](https://www.github.com/tgstation/tgstation/pull/79340)
- [Makes lighting objects objects again](https://www.github.com/tgstation/tgstation/pull/78857)
- [Extends Halloween](https://www.github.com/tgstation/tgstation/pull/79316)
- 
## Reproduction:
As a Cyborg, get flashed with a wall-mounted flash
Get fucked as you cannot proceed to do jack shit afterwards

**Comment by Time-Green** [comment]
Uhhhhh... What did you expect to happen? This is what flashes be doing

**Comment by Time-Green** [comment]
Oh wow I missed that completely

**Comment by Borisvanmemes** [comment]
mounted flashes in general are still a hard stun, even for carbons.

**Comment by Hotmud9** [comment]
how does it make it any different other than the fact that it's static?

**Comment by CCC23** [comment]
skill issue the borgs through the power of setup

**Comment by Hotmud9** [comment]
Still, even then, it lasts way longer than the length of time that you're blinded. Like enough for an AI with two turrets to kill you from full health.

**Comment by Dorsisdwarf** [comment]
Given that mounted flashes are the _only_ defense an AI has against a cyborg sat invasion I don't think this is terrible? Don't solo assault the AI core if it knows you're coming and is allowed to stop you.
