### ISSUE TITLE
Throwing labcoats comes with directional sprites

### ISSUE THREAD

**Issue by Jolly-66** [tgstation/tgstation#79450]
## Round ID:
Tested locally.

## Reproduction:

Noticed this when working on #79096 downstream. I didn't catch it initially here when I made the PR. Oops!

![image](https://github.com/tgstation/tgstation/assets/70232195/d766dcd7-f47a-41e5-9627-0e97d9facc1a)

Throwing GAGs labcoats causes them to take on their directional worn sprites.

**Comment by OrionTheFox** [comment]
![image](https://github.com/tgstation/tgstation/assets/76465278/79dd6960-ba03-4c2c-b9a5-63db64afef4a)

Both configs are pointing to the mob file. The object one needs to point to the object file (and the object config, since they have unique ones apparently? IDK why they need unique ones...)
