### ISSUE TITLE
Breacher Spiders can depower rooms

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#79466]
Reporting client version: 514.1589

## Round ID:
[217948](https://scrubby.melonmesa.com/round/217948)

## Testmerges:
- [Changes how halloween lighting works slightly](https://www.github.com/tgstation/tgstation/pull/79340)
- [Makes lighting objects objects again](https://www.github.com/tgstation/tgstation/pull/78857)
- [Extends Halloween](https://www.github.com/tgstation/tgstation/pull/79316)

## Reproduction:
Spiders can't attack power cables or APCs, theoretically to stop them from depowering the whole station as a wave. Breacher Spiders can destroy walls - When deconstructing a wall got changed to disconnect anything attached to the wall like, say, an APC, this meant Breacher Spiders can freely depower rooms on a short cooldown.

**Comment by timothymtorres** [comment]
Not a bug. This spider is supposed to cause environmental and structural damage to the station.
