### ISSUE TITLE
Tramstation Virology is consistently depowered by ONE rodent

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#79472]
Reporting client version: 514.1589

## Round ID:
[217966](https://scrubby.melonmesa.com/round/217966)

## Testmerges:
- [Changes how halloween lighting works slightly](https://www.github.com/tgstation/tgstation/pull/79340)
- [Makes lighting objects objects again](https://www.github.com/tgstation/tgstation/pull/78857)
- [Extends Halloween](https://www.github.com/tgstation/tgstation/pull/79316)

## Reproduction:
The virology office on tramstation has a closet. This closet has a roundstart mouse named Plaguebearer placed in it. This closet ALSO has the APC for the entire office in it, with a single cable perfectly placed for the roundstart mouse to chew it. I have consistently had to reconnect that wire to be able to do my job, including relocating that mouse to somewhere more appropriate, like the deathsposal chute.

**Comment by san7890** [comment]
could also add catwalk plating over the wires or relocate the APC
