### ISSUE TITLE
Incorrect value in the Chem Dispenser reference book

### ISSUE THREAD

**Issue by SchrodingerW** [tgstation/tgstation#79482]
## Reproduction:
1) Open the Chem Dispenser window
2) Click on the "Reaction search" icon
3) In the "Reagent lookup" window, find the reagents Libital, Salbutamol, Mannitol
4) Metabolization rate - incorrect value:
Libital - Metabolization rate: 0.05u/s 
Salbutamol - Metabolization rate: 0.025u/s 
Mannitol - Metabolization rate: 0.1u/s

TG Wiki:
Libital - Rate: 0.2u/tick
Salbutamol - Rate: 0.1u/tick
Mannitol - Rate: 0.4u/tick

![Screenshot_1](https://github.com/tgstation/tgstation/assets/49116858/daccb30e-1c5e-4bc7-8715-c66029ba7c90)
![Screenshot_2](https://github.com/tgstation/tgstation/assets/49116858/7de6a114-686f-4be4-9786-b83579cfa8ec)
![Screenshot_3](https://github.com/tgstation/tgstation/assets/49116858/d50755cb-53e9-4082-8a79-8255ee05c084)

**Comment by SyncIt21** [comment]
So like which is wrong? The wiki or the Chem Dispenser?

**Comment by SchrodingerW** [comment]
> So like which is wrong? The wiki or the Chem Dispenser?

Chem Dispenser is more likely

**Comment by SyncIt21** [comment]
> Chem Dispenser is more likely

Really? The wiki is pretty outdated so it could be that. This would be a big balance PR that nobody is interested in losing GBP over. Much easier to just update the wiki & call it a day

**Comment by SchrodingerW** [comment]
> > Chem Dispenser is more likely
> 
> Really? The wiki is pretty outdated so it could be that. This would be a big balance PR that nobody is interested in losing GBP over. Much easier to just update the wiki & call it a day

But doesn't TG Wiki use autowiki?

**Comment by SyncIt21** [comment]
> But doesn't TG Wiki use autowiki?

Yes there is an auto wiki but there is no dedicated page for chemistry.

![Screenshot (353)](https://github.com/tgstation/tgstation/assets/110812394/d622d968-5aab-4c6b-b28e-ae88f8832181)

Seems like that is the solution then

**Comment by cnleth** [comment]
Chem dispenser tells you the rate in seconds and on the wiki the rate is in cycles

**Comment by SyncIt21** [comment]
> Chem dispenser tells you the rate in seconds and on the wiki the rate is in cycles

Well, there is your answer then. Also, we should create an auto wiki for chemistry.

**Comment by FlufflesTheDog** [comment]
The reaction search is still inaccurate. As an example, I believe libital's wiki entry is accurate at 0.2/t. A metabolism tick is two seconds, so you'd expect the reaction search to show 0.1/s, instead of 0.05.
