### ISSUE TITLE
Charger-Type Holoparasites do not protect people riding them from Chasms despite the Holoparasite themselves being able to walk over them just fine

### ISSUE THREAD

**Issue by Hotmud9** [tgstation/tgstation#79485]
Reporting client version: 514.1589
## Round ID:
[218021](https://scrubby.melonmesa.com/round/218021)

## Testmerges:
- [Changes how halloween lighting works slightly](https://www.github.com/tgstation/tgstation/pull/79340)
- [Makes lighting objects objects again](https://www.github.com/tgstation/tgstation/pull/78857)
- [Extends Halloween](https://www.github.com/tgstation/tgstation/pull/79316)

## Reproduction:
Acquire a Charger-Type Holoparasite, Power Miner, or Guardian Spirit
Buckle your master (or anyone for that matter) to you
Run over a chasm and watch as the person buckled to you falls to their death

**Comment by san7890** [comment]
lol @Jacquerel do you think we should look into this during the refactor or wait until after

**Comment by Jacquerel** [comment]
I will give it a look
