### ISSUE TITLE
Suit Storage Units can't be locked anymore regardless of how many times you press the lock button

### ISSUE THREAD

**Issue by Hotmud9** [tgstation/tgstation#79486]
Reporting client version: 514.1589
## Round ID:
[218026](https://scrubby.melonmesa.com/round/218026)

## Testmerges:
- [Changes how halloween lighting works slightly](https://www.github.com/tgstation/tgstation/pull/79340)
- [Makes lighting objects objects again](https://www.github.com/tgstation/tgstation/pull/78857)
- [Extends Halloween](https://www.github.com/tgstation/tgstation/pull/79316)

## Reproduction:
Find an SSU
Press lock
Cope and seethe as all of your shit is stolen by a traitor with an airmag

**Comment by SyncIt21** [comment]
Question. Did you install a card reader in the unit and swipe your pda and selected Personal option to make it your unit? Else the lock button does not to do anything

**Comment by Hotmud9** [comment]
No, I didn't. Normally, it would turn the lights on the top red. But it was just going back to the radial menu with three options on it, which might happen if you install a card reader on it too.

**Comment by SyncIt21** [comment]
Yes it will still display the radial menu even after it is unlocked but with only 1 option I.e. unlock.

If you don't have access it will display the balloon alert saying so else it will unlock for you.

You must first install a card reader and swipe your ID in it and Select Personal option to enable this feature because by default all units are made public

**Comment by Hotmud9** [comment]
> Yes it will still display the radial menu even after it is locked but with only 1 option I.e. unlock.
Yes, that's what is SUPPOSED to happen.
I'm saying, without (or potentially with, I still have yet to test), the lock function straight up doesn't even LOCK it and goes back to the radial menu with the options of lock, open, or disinfect.

**Comment by Hotmud9** [comment]
> Yes it will still display the radial menu even after it is locked but with only 1 option I.e. unlock.

Yes, that's what is SUPPOSED to happen.
I'm saying, without (or potentially with, I still have yet to test), the lock function straight up doesn't even LOCK it and goes back to the radial menu with the options of lock, open, or disinfect.
