### ISSUE TITLE
mutate spell might last forever?

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#79491]
## Round ID: Round ID: [218035](https://scrubby.melonmesa.com/round/218035)

this was a ragin' mages round

I noticed that I could continue to shoot eye lasers long, LONG after I had cast Mutate (like, several minutes); I suspect that the spell doesn't properly remove the mutations it adds when its time is up

**Comment by SethLafuente** [comment]
Tested for 2 minutes without it stopping still a bug seems to last indefinitely when its meant to last 40 seconds
![image](https://github.com/tgstation/tgstation/assets/84478872/6b3fce8c-8024-4444-9459-1193e2e3f50d)
![YYMfkBo](https://github.com/tgstation/tgstation/assets/84478872/e38199b6-4b8b-4d5e-8bd3-3b509aa130b3)

Also tested with it been 1-3 upgrade rank there was no difference
