### ISSUE TITLE
Knock heretic spell disappear

### ISSUE THREAD

**Issue by Samag5** [tgstation/tgstation#79525]

**Comment by mc-oofert** [comment]
@Jacquerel   #79270

**Comment by Jacquerel** [comment]
Did you check if that was the cause or did you just feel like pinging me?

**Comment by mc-oofert** [comment]
> Did you check if that was the cause or did you just feel like pinging me?

i felt like pinging you honestly

**Comment by Dorsisdwarf** [comment]
Later duplicate explains this better
