### ISSUE TITLE
"All within theoretical limits" achievement is kinda broken

### ISSUE THREAD

**Issue by vertolodka** [tgstation/tgstation#79528]
Reporting client version: 514.1589

## Round ID:
[218162](https://scrubby.melonmesa.com/round/218162)

## Testmerges:
- [Extends Halloween](https://www.github.com/tgstation/tgstation/pull/79316)
- [Changes how halloween lighting works slightly](https://www.github.com/tgstation/tgstation/pull/79340)

## Reproduction:

1. Prepare SM for resonance cascade (fill it with hypernob antinob mix, i used ~10k each)
1.1 Basic N2 SM setup will work, just add hypernob and n2o to filter.
1.2 Make scrubbers expanded range and scrub only o2 n2 plasma co2 and h2o
1.3 Pump in hypernob
1.4 Remove n2 from filter
1.5 Pump in antinob
2. Wait for it (actually use guns until ~20%)
3. CRYSTAL DELAMINATION IMMINENT. The supermatter has reached critical integrity failure. Harmonic frequency limits exceeded. Causality destabilization field could not be engaged.
4. Pump in a lot of cold n2o(i used ~50k) and hypernob(~12k)
4.1 I used air injectors to pump it in
5. Turn on siphon on scrubbers
6. Crystaline hyperstructure returning to safe operating parameters. Failsafe has been disengaged.
6.1 (IMPROTANT) Do you see something off? Yea text is wrong, second part should be "..Harmonic frequency restored within emergency bounds. Anti-resonance filter initiated." but due to changing gas ratio in a way it no longer fits cascade resonance, it looks like delam type changed.
7. See it heal to ~~20%~~ ~~25%~~ (start injecting copium(optional)) ~~30%~~ ~~50%~~ 100% and no achievement.
8. Jump into sm with everyone who was hoping to get it.

**Comment by distributivgesetz** [comment]
delam strategy should not update during a countdown imo
