### ISSUE TITLE
Can't make Meat Product >:(

### ISSUE THREAD

**Issue by CMDRYouth** [tgstation/tgstation#79527]
## Round ID: 
Round ID: [218165](https://scrubby.melonmesa.com/round/218165)
BYOND Version: 515.1610
Server revision compiled on: 
Master commit: [9dba26fdf6aa46a59feac8b067a4132cb90ad88b](https://www.github.com/tgstation/tgstation/commit/9dba26fdf6aa46a59feac8b067a4132cb90ad88b)

Local commit: 7f152dc681b258959da46dd2ced32473120a82e5
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

## Testmerges: 
[#78997: 'Bitrunning content patch: Antag rework (READY)' by jlsnow301 at commit f249d1c21e](https://www.github.com/tgstation/tgstation/pull/78997)
[#79340: 'Changes how halloween lighting works slightly' by LemonInTheDark at commit 615818d8d1](https://www.github.com/tgstation/tgstation/pull/79340)

## Reproduction:

![image](https://github.com/tgstation/tgstation/assets/11749157/043191bc-9e26-4e39-b098-40aaaf25feb0)
![image](https://github.com/tgstation/tgstation/assets/11749157/d35305e3-f7fc-456d-a8b1-ac5c168b8d90)
![image](https://github.com/tgstation/tgstation/assets/11749157/b0c882bc-fcf7-4824-9529-ebd021da125f)

**Comment by SyncIt21** [comment]
Unable to reproduce on local

https://github.com/tgstation/tgstation/assets/110812394/f1c0fd19-7d30-4cfa-bb2d-d98ffedfe015

Also looking at the round ID it appears to be a downstream issue which reminds me of  
- #79058

Maybe report the issue on their repo and come back here

**Comment by HalfPunch** [comment]
> Also looking at the round ID it appears to be a downstream issue which reminds me of
> 
> * [Weakened virus plasma recepie acts weird and broken #79058](https://github.com/tgstation/tgstation/issues/79058)

My issue was closed because i figured out what was happening. 
My Synaptizine was heated to 640K after mixing, so plasma and virus plasma in beaker have been evaporated.

I belive reaction temperature isn't realated to this issue. Unless it's too cold to react if it's even possible

**Comment by SyncIt21** [comment]
But still not able to reproduce in local. Anyway it's best to keep this open for a week atleast and then close if it can't be reproduced
