### ISSUE TITLE
Books that link to the wiki are broken

### ISSUE THREAD

**Issue by Richie9999** [tgstation/tgstation#79545]
Reporting client version: 514.1589

## Round ID:
[218223](https://scrubby.melonmesa.com/round/218223)

## Testmerges:
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)
- [Extends Halloween](https://www.github.com/tgstation/tgstation/pull/79316)

## Reproduction:

Pick up space law book, try to read the book. Get HTML code instead of legible book, try with other books to similar results. 
```html
        <html>
        <head>
        <meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
        <style>
            iframe {
                display: none;
            }
        </style>
        </head>
        <body>
        <script type="text/javascript">
            function pageloaded(myframe) {
                document.getElementById("loading").style.display = "none";
                myframe.style.display = "inline";
        }
        </script>
        <p id='loading'>You start skimming through the manual...</p>
        <iframe width='100%' height='97%' onload="pageloaded(this)" src="http://tgstation13.org/wiki/Space_Law?printable=yes&remove_links=1" frameborder="0" id="main_frame"></iframe>
        </body>

        </html>
```
The Space law book, for example. Same results gained from other books that display text from the wiki that I tested in the dome.

**Comment by san7890** [comment]
i edited the issue report to have the code stylized in html so it didn't malformat itself

**Comment by san7890** [comment]
i was wrong
