### ISSUE TITLE
Mesons allows to see what items people pick up through the walls

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#79541]
## Reproduction:

Wear mesons, spy on traitors getting their contraband from the bags.

![Screenshot_393](https://github.com/tgstation/tgstation/assets/64209864/59a4501c-faab-4a26-8d68-ea4b14b14f50)

**Comment by Jackal-boop** [comment]
This has been a thing for a very long time and I think there's like 5 other issues about this

**Comment by MrMelbert** [comment]
Correct: dupe of #39799

**Comment by ZephyrTFA** [comment]
Duplicate of https://github.com/tgstation/tgstation/issues/39799
