### ISSUE TITLE
The Mass Driver is an old, buggy mess.

### ISSUE THREAD

**Issue by paprka** [tgstation/tgstation#7954]
It's not really issues with the mass driver itself, it's how it's set up. Currently, if you mass driver, it lets the air out, thus typically pulling people out in front of the mass driver towards space before it launches. The mass driver setup should not be letting any air out at all, and this really needs to be reconfigured to not create a breach when it's being used.

**Comment by mrpain666** [comment]
Could the opening be somehow timed to open at the very last second/later, like right after the launcher part of the driver begins to move?

**Comment by RandomMarine** [comment]
It only starts happening after a few launches drains the air out of the mass driver tiles. Putting a vent in front of the mass driver would solve it.

**Comment by Lumipharon** [comment]
It's a larger issue with how our atmos system works.

Realistically, an airlock with the double doors would equalise pressure before opening the other door (empty out when going EVA, filling up when coming in). Of course, this isn't practical and/or possible for us I don't think.

A lazy fix to this specific issue would be to have an air vent infront of the driver, because it's only an issue after repeated use.
Otherwise what, some sort of forcefield to keep the air in but let other shit out? I unno.

**Comment by Steelpoint** [comment]
Some servers/codebases do use the pressurization system as described above, but something tells me it would be easier to just plop a vent infront of the mass drive instead.

**Comment by Miauw62** [comment]
we have "proper" equalizing airlocks, but they're buggy as shit (they're
the ones you find in viro and toxins)

**Comment by paprka** [comment]
Equalizing airlocks can be ported from bay but they're fucking SLOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOW to cycle

**Comment by Delimusca** [comment]
airtight flaps under the blast doors? seems a bit silly but it'd work.

**Comment by paprka** [comment]
but people can't go through flaps

**Comment by Delimusca** [comment]
they can if they aren't standing.

**Comment by paprka** [comment]
decent idea, then.

**Comment by TheVekter** [comment]
I'll test this later on today and see if it works how I think it does.

**Comment by Core0verload** [comment]
@phil235, fixed.

**Comment by phil235** [comment]
I don't think it is fixed, the massdriver's blast door stay open for quite a while after launch and depressurize the two tiles in front of the massdriver. The launch is fine, but after just one you get spacewind dragging items away from the massdriver tile which means you have to wait for space wind to abate before doing a second launch.

**Comment by duncathan** [comment]
I swear airtight plastic flaps are a thing

**Comment by phil235** [comment]
@duncathan they would stop standing mobs and mechs from being launched through the mass driver.

**Comment by TheVekter** [comment]
They are, numbnuts, they just don't work with standing... anything.

**Comment by Lumipharon** [comment]
Just revert shitwind changes.
