### ISSUE TITLE
Non-antags using a nukeop induction kit on themselves works

### ISSUE THREAD

**Issue by Bm0n** [tgstation/tgstation#79547]
Reporting client version: 514.1589

## Round ID:
[218226](https://scrubby.melonmesa.com/round/218226)

## Testmerges:
- [Changes how halloween lighting works slightly](https://www.github.com/tgstation/tgstation/pull/79340)

## Reproduction:

Be a non-antag, use an induction kit implanter on yourself, be made a nukeop with antag datum.

This is obviously bad since the induction kit implanter is only suppose to work on antags.

**Comment by Isratosh** [comment]
Broken by #78597, that changed the check from "has an antag datum" to "doesn't have a fake antag datum" which having no antag datum at all will pass

**Comment by Isratosh** [comment]
Actually that PR set the root `/datum/antagonist` `antag_flags = FLAG_FAKE_ANTAG`, every antagonist datum is considered fake and this induction kit is currently working completely backwards
