### ISSUE TITLE
Chemical Mixing Belt can hold SO MANY FUCKING BEAKERS

### ISSUE THREAD

**Issue by Hotmud9** [tgstation/tgstation#79551]
Reporting client version: 514.1589

## Round ID:
[218235](https://scrubby.melonmesa.com/round/218235)

## Testmerges:
- [Changes how halloween lighting works slightly](https://www.github.com/tgstation/tgstation/pull/79340)

## Reproduction:
This is just an innate trait of the Chem Mixing belt what the actual shit
Why can it hold THIS MANY FUCKING BEAKERS
![image](https://github.com/tgstation/tgstation/assets/44795537/9afeacaa-2869-46a4-b30d-9d6ffe67b77f)

**Comment by ZephyrTFA** [comment]
I don't see the problem here

**Comment by Hotmud9** [comment]
You mean to tell me that it's intended that it can hold 50 fucking beakers?

**Comment by Helg2** [comment]
Doesn't chem bag can hold something similar to that number? What's the issue

**Comment by nikothedude** [comment]
> Doesn't chem bag can hold something similar to that number? What's the issue

the chem bag uses numeric stacking, to my understanding nothing else in the game shows EACH INDIVIDUAL ITEM with THIS capacity

**Comment by Helg2** [comment]
Well yeah, cause you need to properly see every beaker and not just a stack of them, so the mixing belt isn't just useless
