### ISSUE TITLE
ma mothefuckin chat died

### ISSUE THREAD

**Issue by whoisdeez** [tgstation/tgstation#79576]
## Round ID: 
[218323](https://scrubby.melonmesa.com/round/218323)

## Testmerges:
cant see

## Reproduction:
i joined and my chat was the bluescreen thing
1.join
2.bug

thing told me to write this here
SyntaxError: Syntax error
   at Anonymous function (https://tgstation13.download/byond/assets/e6/asset.e66f2f990370cf27fd821c438a054210.js:1:239105)
   at Anonymous function (https://tgstation13.download/byond/assets/e6/asset.e66f2f990370cf27fd821c438a054210.js:1:425650)
   at window.update (http://127.0.0.1:50093/tmp12992/browseroutput.html:468:5)
   at eval code (eval code:1:1)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0)
State: {}

**Comment by Dorsisdwarf** [comment]
Round 218323 was Sybil.

Testmerged PRs:
#79479: 'Adds a Chat Reliability Layer' by ZephyrTFA at commit 23d9762f25

Reproduced.


(For future reference, try the "Fix Chat" verb in the ooc tab for  this one)

**Comment by SyncIt21** [comment]
I don't think this is a test merge bug at all. 

It's a syntax error which means the client attempted to parse "corrupted assets". From the url you can see that it is a asset file 

> SyntaxError: Syntax error
> at Anonymous function (https://tgstation13.download/byond/assets/e6/asset.e66f2f990370cf27fd821c438a054210.js:1:239105)

And corrupted assets occur due to CDN issues. Have the server toggle CDN if it occurs again or clear your Byond client cache and it should fix it.

**Comment by san7890** [comment]
CDN doesn't matter because it happens on local

**Comment by SyncIt21** [comment]
> CDN doesn't matter because it happens on local

My bad, based on your comment https://github.com/tgstation/tgstation/issues/79814#issuecomment-1817365529 do you think 

- #79244
Might have something to do with it?

**Comment by san7890** [comment]
i will be discussing this further in #79814 because this does not have any usable information because toggling the CDN will not fix it and the stack trace is junk
