### ISSUE TITLE
Runechat linebreaks break text effects (or just italics)

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#79582]
## Round ID:
[218328](https://scrubby.melonmesa.com/round/218328)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/76874615/7a3d7b23-8f1e-4e76-893c-50c8b44a5f46)
Runechat versus log, the italic ends proper on one, but the linebreak on the runechat seems to make that effect stick instead

**Comment by ZephyrTFA** [comment]
Duplicate of https://github.com/tgstation/tgstation/issues/73470

**Comment by AdipemDragon** [comment]
whoops, my b
