### ISSUE TITLE
No bone gel or bone setter in Holodeck medbay (on metastation)

### ISSUE THREAD

**Issue by lilahnovi** [tgstation/tgstation#79591]
Reporting client version: 514.1589

## Round ID:
218353

## Testmerges:
- [Adds a Chat Reliability Layer](https://www.github.com/tgstation/tgstation/pull/79479)

## Reproduction:

Within the holodeck's medbay, there is no bonesetter or bone gel (This is on meta station. I am unsure if this is the case on other stations). It's probably just outdated.

![image](https://github.com/tgstation/tgstation/assets/124811534/457a1619-9ad7-4982-bf91-face299fd552)

**Comment by SethLafuente** [comment]
![image](https://github.com/tgstation/tgstation/assets/84478872/30aab410-0f9b-4533-a277-dc48af9cf6a2)
every holodeck is the same regardless of station not really a bug someone just forgot to add it
