### ISSUE TITLE
Something about being in stasis alters a mob's time of death (prevents corpse aging?)

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#79593]
Reporting client version: 514.1589

## Round ID:
[218350](https://scrubby.melonmesa.com/round/218350)

## Testmerges:
- [Extends Halloween](https://www.github.com/tgstation/tgstation/pull/79316)
- [Changes how halloween lighting works slightly](https://www.github.com/tgstation/tgstation/pull/79340)

## Reproduction:

Which can result in their "subject died <time interval> ago" to go backwards.  Such as these two consecutive scans of a poor NPC i created and wand of deathed then shoved in stasis (consider this the reproduction steps)

![image](https://github.com/tgstation/tgstation/assets/3789327/46b4853b-21f2-4cfd-8bfe-a9b9fdbab382)

Hooray, they're 0.9 seconds less dead in the second!

(Oddly the died X ago seems fairly stable, which seems odd.  either way be good if stasis doesn't stop this counter since its a useful measure for a doctor sometimes, like if i'm busy a 1 minute old corpse is less concerning than a 10 minute old one)

(Possibly even more useful as an admin to get an assessment when people pray/complain about medical)

**Comment by iprice** [comment]
I guess this came from #77820 which changed a line in stasis behaviour, not really sure why, "no player facing changes" hehe.  But everything else there is years old and I guess this change touches the right sorta area (i guess the time of death was always updating but no-one would notice because we'd just read the subject died X seconds ago?)

**Comment by MrMelbert** [comment]
Relevant code

https://github.com/tgstation/tgstation/blob/48522a8a70af27e50e692c420995cad7a59a3c9c/code/datums/status_effects/debuffs/debuffs.dm#L261-L275

Every tick of stasis your time of death is set to the world.time you entered stasis. 

However (I believe) if you analyzer them before stasis ticks for the first time you will catch it "in action", because it requires 1 tick to update correctly. 

This is working as designed, albiet a little finnicky. 

> I guess this came from https://github.com/tgstation/tgstation/pull/77820

All that PR did was rename a variable... I think it did not change anything.

**Comment by iprice** [comment]
Okay, this is my bad, seems like it has done this since at least start of 2022 and I've never noticed.  A little horrifying given I do use this information and was never aware of this consideration.

The anecdotal as to how I discovered this is low pop (like 3-4 people), dead miner, someone shoved them in stasis and never came back.  Was talking in ASAY about something unrelated and attention went back to the corpse, had they waited long enough to deserve some divine intervention?  Clicked on them and bam, 2 minutes.  But I know I'd been talking so much longer than that so started looking into this and unravelled all of this.

But I've probably done that before where I hadn't sat next to a corpse for long enough I knew the "time of death" simply couldn't be right, and trusted it.

I guess this can be closed or turned into a feature request or something, my claims of it as a new bug / change certainly aren't validated, and this whole discovery has made me a little disturbed overall.  At least something was learned.
