### ISSUE TITLE
Vote result processing may crash, not implementing the result, or starting the next vote cooldown

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#79601]
Reporting client version: 514.1589

## Round ID:
[218393](https://scrubby.melonmesa.com/round/218393)

## Testmerges:
- [Extends Halloween](https://www.github.com/tgstation/tgstation/pull/79316)
- [Changes how halloween lighting works slightly](https://www.github.com/tgstation/tgstation/pull/79340)

## Reproduction:

No idea how to reproduce it, a player reported it as "I can chain call map votes with no cooldown, though they do nothing" sort of thing, and lo and behold a seemingly relevant runtime

```
[2023-11-08 19:14:08.600] RUNTIME: runtime error: undefined proc or verb /datum/client_interface/is afk().
 - 
 - proc name: process vote result (/datum/controller/subsystem/vote/proc/process_vote_result)
 -   source file: code/controllers/subsystem/vote.dm,69
 -   usr: null
 -   src: Vote (/datum/controller/subsystem/vote)
 -   call stack:
 - Vote (/datum/controller/subsystem/vote): process vote result()
 - Vote (/datum/controller/subsystem/vote): fire(0)
 - Vote (/datum/controller/subsystem/vote): ignite(0)
 - Master (/datum/controller/master): RunQueue()
 - Master (/datum/controller/master): Loop(2)
 - Master (/datum/controller/master): StartProcessing(0)
 -
```

**Comment by ZephyrTFA** [comment]
how the fuck do we have a fake client datum on live

**Comment by san7890** [comment]
![image](https://github.com/tgstation/tgstation/assets/34697715/70694d3e-2354-4eba-ae31-44e188e5c8bc)

this is why
