### ISSUE TITLE
The bayonet doesn't align right with pipeguns or regal pipeguns on the sprite.

### ISSUE THREAD

**Issue by Cadunkus** [tgstation/tgstation#79607]
## Reproduction:

Slap a bayonet of any type on any pipegun (survival knife, combat knife, bone dagger) and the sprite for the bayonet goes off to the side suspended in the air.

**Comment by SethLafuente** [comment]
![3LeTSBH](https://github.com/tgstation/tgstation/assets/84478872/7ce6d077-a4fd-4369-bd68-c9b007f234b7)
weird stuff
