### ISSUE TITLE
Debug Chem Synthesizer broken

### ISSUE THREAD

**Issue by TwistedCicrularConvexLens** [tgstation/tgstation#79610]
## Testmerges:

None.

## Reproduction:

Attempt to use: code/modules/reagents/chemistry/machinery/chem_synthesizer.dm.
It no longer can add reagents to beakers, only create them. This was probably an oversight.

Broken by https://github.com/tgstation/tgstation/pull/79395#issue-1968696051
<details>
  <summary>Before</summary> 

https://github.com/tgstation/tgstation/assets/106436013/3a1ad7eb-b015-41bc-83ab-a4aa04960769

</details>

<details>
  <summary>After</summary> 

https://github.com/tgstation/tgstation/assets/106436013/3fdd8da0-b336-47d5-a4d1-08f0cf600571

</details>

**Comment by SethLafuente** [comment]
![image](https://github.com/tgstation/tgstation/assets/84478872/ad6db753-4913-4048-b983-27ad0df1cbf8)
Reproduced it on my local didnt used to happen until a few updates ago this is a very recent bug

**Comment by TwistedCicrularConvexLens** [comment]
https://github.com/tgstation/tgstation/pull/79395#issue-1968696051 was merged about 6 hours ago.

**Comment by SyncIt21** [comment]
I'm on it

**Comment by SyncIt21** [comment]
Why was this closed? Did somebody else fix the bug?

**Comment by TwistedCicrularConvexLens** [comment]
Ahhhhh!!! my Bad. The fix you made hasn't been merged yet, I missed that. Sorry.
