### ISSUE TITLE
AI portrait picker cannot search 

### ISSUE THREAD

**Issue by unit0016** [tgstation/tgstation#79619]
Reporting client version: 515.1619

## Round ID:
[218439](https://scrubby.melonmesa.com/round/218439)

## Testmerges:
- [Adds a Chat Reliability Layer](https://www.github.com/tgstation/tgstation/pull/79479)

## Reproduction:
Try and pick a painting as your AI Core display via search
doesn't work
mfw 

Also the picker incorrectly assumes all paintings have the same aspect ratios, squashing large paintings down into a square

Also also: searching by frame type was commented out

**Comment by deathrobotpunch** [comment]
how do you even pick an AI portrait in the first place?

**Comment by unit0016** [comment]
Only in-round, cant set it in prefs - AI tab, change AI display, flip through the radial until you find the painting option.
