### ISSUE TITLE
You can make reagents hotter than the surface of the sun

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#79633]
Reporting client version: 514.1589

## Round ID:
[218480](https://scrubby.melonmesa.com/round/218480)

## Testmerges:
- [Adds a Chat Reliability Layer](https://www.github.com/tgstation/tgstation/pull/79479)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/66640614/9c8d351b-df1d-43fb-899f-46d86a762d3d)
(Left: really hot chems, Right: regular maxed out temp chems from a chem heater)

Inject reagents into a monkey
Set the monkey on fire and wait for it to get REALLY HOT 
![image](https://github.com/tgstation/tgstation/assets/66640614/607d53be-1aaa-4b59-99c1-afdf6863ae45)
Gib the monkey, grind the meat, and extract the chems
Your reagents are now extremely hot, allowing you to make oil so hot it kills people instantly

**Comment by dragomagol** [comment]
Honestly the monkey should be char by that point

**Comment by zxaber** [comment]
Fire should probably have a cap on how hot it can make a mob, too.

**Comment by san7890** [comment]
there is no upper limit to how hot something can get as long as the particles keep vibrating- it would be nice if fire could tell when it used up all of it's fuel source (aka burn it to a char) and then stop being on fire after that point. that is a lot of work however

**Comment by Y0SH1M4S73R** [comment]
are there even any reagents this would have a significant gameplay impact on?

**Comment by necromanceranne** [comment]
I mean, can't lighters/other direct heat tools take it over 1000 kelvin?

**Comment by dragomagol** [comment]
> are there even any reagents this would have a significant gameplay impact on?

Yes! Currently it is being used to heat oil very very hot, causing it to instantly kill and husk people.

**Comment by dragomagol** [comment]
> I mean, can't lighters/other direct heat tools take chems in beakers it over 1000 kelvin?

Yeah I realized that after I posted, I'll change that
