### ISSUE TITLE
PDA mafia achievements are broken

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#79658]
## Reproduction:
Multiple rounds, Town and Mafia victory didn't count towards the achievements, only "neutral" ones. I tried both PDA and modular console games. Other players who was in the game said they also don't get achievements most of the time, but got some mafia-town victories. 

![Screenshot_445](https://github.com/tgstation/tgstation/assets/64209864/dd8c9e37-8a59-4401-98c0-c4102721c23b)

**Comment by Time-Green** [comment]
If you're playing against yourself for the achievements, you need to keep the UI open or you wont get it. Also make sure you don't force an early start, that disables achievements

**Comment by Time-Green** [comment]
I can pretty confidently say it's not bugged because I got them all

**Comment by Livrah** [comment]
All windows was open and I played with other ppl, but started early.

**Comment by Time-Green** [comment]
> All windows was open and I played with other ppl, but started early.

Yeah you need 12 "people" and not early start, then you can get achievements. I believe the only exceptions are the ones that give direct achievements, like obsessed for getting their target, assistants for getting assasinated, clowns for getting lynched etc, which seems consistent with your experience
