### ISSUE TITLE
Lava is still capable of giving a permanent, stuck fire overlay

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#79654]
## Reproduction:

- Step on lava
- Extinguish yourself
- Step off lava
- Permanent fire

https://github.com/tgstation/tgstation/assets/51863163/8644ae76-a02d-4223-ab32-e347928969ed

**Comment by SyncIt21** [comment]
Related
- #77701

Also, in the video its weird that you can extinguish yourself while still on the lava turf. Like you should recatch on fire instantly (or you should not be able to put yourself out at least)

Maybe have some flag that says "non extinguishable" while on the turf and when you exit it you remove the flag or something like that
