### ISSUE TITLE
Using a polymorphic field inverter to become a mob that can eat objects/mobs does not drop things you eat when you turn back

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#79679]
## Round ID: 
Reported from https://github.com/Skyrat-SS13/Skyrat-tg because of course it is

## Reproduction:
As title. If you use the PFI to become a morph, space dragon, etc and eat items while the consuming mob, changing back to human will not drop the items you consumed while transformed, effectively making them lost forever.

**Comment by moocowswag** [comment]
so if you eat the nuke disk... does it teleport or become unobtainium

**Comment by deathrobotpunch** [comment]
the way the nuke disk is coded when deleted somehow it automatically respawns where it usually is roundstart

**Comment by Admiral-Gigaton** [comment]
how did you become a morph? weren't morphs pretty much REMOVED from /TG/

**Comment by Admiral-Gigaton** [comment]
Weird, I've just never seen them, nor do I remember them ever be in the antag selection screen

**Comment by YakumoChen** [comment]
They fall under xenos in antag selection I'm pretty sure

**Comment by deathrobotpunch** [comment]
> how did you become a morph? weren't morphs pretty much REMOVED from /TG/

also they are mentioning the use of an item that allows you to turn into any simple / basic mob if you can scan it

**Comment by Admiral-Gigaton** [comment]
> > how did you become a morph? weren't morphs pretty much REMOVED from /TG/
> 
> also they are mentioning the use of an item that allows you to turn into any simple / basic mob if you can scan it

i see now this is from skyrat, not here, nvm

**Comment by YakumoChen** [comment]
updated issue report as it includes any mob capable of eating other objects (like Space Dragon)
