### ISSUE TITLE
pete cant be milked

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#79684]
Reporting client version: 514.1589

## Round ID:
[218637](https://scrubby.melonmesa.com/round/218637)

## Testmerges:
- [Adds a Chat Reliability Layer](https://www.github.com/tgstation/tgstation/pull/79479)

## Reproduction:

1. try to milk pete
2. fail

**Comment by Annihilit** [comment]
>Needs Reproducing
I mean yeah...

**Comment by HalfPunch** [comment]
Wait but... isn't Pete a male?

**Comment by Coconutwarrior97** [comment]
You know not what you ask. 
![d3bbea2db0132ea9bcde5873e48aef7f](https://github.com/tgstation/tgstation/assets/40315842/072c8023-8d44-4067-8798-136fd5979d4b)

**Comment by Time-Green** [comment]
Oh thats sad, Pete was THE milkmachine

**Comment by JohnFulpWillard** [comment]
Im marking it as a bug because it was a balance change labelled refactor

**Comment by Fikou** [comment]
![image](https://github.com/tgstation/tgstation/assets/23585223/57f8b083-c10a-4ba4-b63e-47036c7f8b64)

**Comment by san7890** [comment]
![image](https://github.com/tgstation/tgstation/assets/34697715/99a2962e-708e-483b-9bff-fcc7f4a091df)

this was addressed in the original PR but it was merged anyways.

**Comment by ninjanomnom** [comment]
I don't care what the label says, you shouldn't be able to milk male goats.
