### ISSUE TITLE
Chat Panel BSOD.

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#79682]
Reporting client version: 514.1589

## Round ID:
[218628](https://scrubby.melonmesa.com/round/218628)

## Testmerges:
- [Adds a Chat Reliability Layer](https://www.github.com/tgstation/tgstation/pull/79479)

## Reproduction:
So far, I seem to be getting these often when I join the server, or the round reboots. Fix chat fixes it, but its happening often. (This particular example occurred twice in a row. One round when first joining, one after a server reboot.)
![image](https://github.com/tgstation/tgstation/assets/85206687/cd87d4ea-6340-4f99-a032-a82b8085ba5c)

**Comment by SyncIt21** [comment]
Duplicate #79576
