### ISSUE TITLE
Some impure reagents cannot be cooked/do not affect the body

### ISSUE THREAD

**Issue by DarkHunter7756** [tgstation/tgstation#79692]
Round ID: [218654](https://scrubby.melonmesa.com/round/218654) (https://statbus.space/rounds/218654)

## Reproduction:
1. Add hydrogen/sodium/stable plasma to obtain a pH sufficient to reduce purity to 1-30% in future
2. Add reagents from wiki recipe
3. Move to High-performance liquid chromatography machine and see clean (not impure; not inverted) reagent
4. Drink/inject to see no impure reagent in blood and stomach and no effect

Lentslurri
![image](https://github.com/tgstation/tgstation/assets/76823962/9df79bc5-0b36-4390-a28e-f9f55043b153)
![image](https://github.com/tgstation/tgstation/assets/76823962/d979af00-f45d-45d3-922f-2dcb6f01abc8)
![image](https://github.com/tgstation/tgstation/assets/76823962/1bd9d7e9-a4f2-4171-8363-09b253016feb)
This one "will cause the patient to move slowly" but no effect did

A similar situation with:

- Aivime
- Libitoil
- Eigenswap

**Comment by FlufflesTheDog** [comment]
Impurities don't really exist (or aren't obtainable) anymore, the wiki is quite outdated on that #68385

**Comment by DarkHunter7756** [comment]
> Impurities don't really exist (or aren't obtainable) anymore, the wiki is quite outdated on that #68385

ok, thanks, most reagents have been converted from impure to inverted

![image](https://github.com/tgstation/tgstation/assets/76823962/73b4a168-69a7-4457-84f5-f7bb2800c206)

but the ones described above (Aivime, Libitoil etc) were not. 

They are still here with all the effects
https://github.com/tgstation/tgstation/blob/6088b5424eb34fc1d1c9f24e809d2ac03b57044a/code/modules/reagents/chemistry/reagents/impure_reagents/impure_medicine_reagents.dm

So, does this mean this is not a bug, but a flaw?
