### ISSUE TITLE
Newscasters log hallucinations

### ISSUE THREAD

**Issue by read-0nly** [tgstation/tgstation#79709]
## Round ID:
[218712](https://scrubby.melonmesa.com/round/218712)

## Reproduction:
Mass hallucination was triggered, mine was as follows:
#### Central Command Higher Dimensional Affairs
Figments from an eldritch god are being summoned by monkey (420) into the Supermatter Engine from an unknown dimension. Disrupt the ritual at all costs!

Confirmed with crew it was a hallucination, the newscaster feed was flooded with similar messages, one for each crewmember. Are newscasters supposed to hallucinate?

**Comment by MrMelbert** [comment]
Caused by #79179 , very silly
