### ISSUE TITLE
Can't open the interface for PCM

### ISSUE THREAD

**Issue by xXPawnStarrXx** [tgstation/tgstation#79710]
## Testmerges:
This was discovered on a downstream of TG and tested/reported by myself.

## Reproduction:
Create a portable chem mixer, insert beakers with chems, close the storage, insert beaker to output slot. Attempt to open the interface and get told in a balloon alert over and over that it is 'closed'.

**Comment by SyncIt21** [comment]
Unable to reproduce on local

https://github.com/tgstation/tgstation/assets/110812394/7ea1c091-b8f1-492e-9f41-d9892bd4d215

This must be a test merge bug
- #79563

**Comment by SyncIt21** [comment]
This cannot be reproduced on local and i was wrong about the test merge as well. Please report this issue on that downstream repo as nothing can be done here

**Comment by xXPawnStarrXx** [comment]
Will do.
