### ISSUE TITLE
ascended knock heretics lose access to all of their spells while human apart from ascended shapechange after using it

### ISSUE THREAD

**Issue by Borisvanmemes** [tgstation/tgstation#79713]
Reporting client version: 514.1589

## Round ID:
[218720](https://scrubby.melonmesa.com/round/218720)

## Testmerges:
- [Adds more bitrunning antagonists + fixes (READY)](https://www.github.com/tgstation/tgstation/pull/79522)
- [Mob `attackedby` / `check_block` refactor, plus some minor cleanup of `attack_x` procs](https://www.github.com/tgstation/tgstation/pull/79563)

**Comment by Profakos** [comment]
Duplicate of #79525
