### ISSUE TITLE
Cannot deconstruct modular computers.

### ISSUE THREAD

**Issue by Higgin** [tgstation/tgstation#79728]
Suspect to be related to the attack proc changes in #79563 

## Round ID: [218737](https://scrubby.melonmesa.com/round/218737)
BYOND Version: 515.1610
Server revision compiled on: 
Master commit: [f73f6d76a16f4b07ad288cdd23e7f5c25b42402b](https://www.github.com/tgstation/tgstation/commit/f73f6d76a16f4b07ad288cdd23e7f5c25b42402b)

## Testmerges:
The following pull requests are currently test merged:
[#79563: 'Mob `attackedby` / `check_block` refactor, plus some minor cleanup of `attack_x` procs' by MrMelbert at commit afe0c59bd5](https://www.github.com/tgstation/tgstation/pull/79563)
[#79522: 'Adds more bitrunning antagonists + fixes (READY)' by jlsnow301 at commit 4b415fe925](https://www.github.com/tgstation/tgstation/pull/79522)
[#79698: '[READY] Adds rabbit infusion to genetics' by Iamgoofball at commit 2a65710b8b](https://www.github.com/tgstation/tgstation/pull/79698)

Local commit: 19d464941c5d8a05d8c23faf9df88eea7e2ec7df
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

## Reproduction:

1. Try to screwdriver or use any other tool to deconstruct a modular computer (like the identification computers, or the ones with cargo chatrooms in the various depts.)
2. No feedback.
3. Have to physically destroy the computer to get rid of it.

**Comment by distributivgesetz** [comment]
Did you try wrench right click? That's what the code expects

**Comment by Time-Green** [comment]
> Did you try wrench right click? That's what the code expects

I did this two weeks ago, worked perfectly fine then

**Comment by SyncIt21** [comment]
> Did you try wrench right click? That's what the code expects

Tested locally and works fine. This can be closed

**Comment by Higgin** [comment]
Yeah, I'm not sure how I missed that. Retested today and it works.
