### ISSUE TITLE
northstar map rotation is not mandatory

### ISSUE THREAD

**Issue by deathrobotpunch** [tgstation/tgstation#79756]
## Reproduction:
1. go to statbus
2. look at rounds
3. realise that rounds with northstar as the map do not happen as regularly then they are supposed to. ex 2 north star rounds happening over two days

**Comment by cnleth** [comment]
Are you sure it's not just that people don't vote it? After all, it's a highpop map so there's less map votes with it included and on top of that, people often just vote more popular maps like delta or meta on highpop. I don't think this is a bug

**Comment by san7890** [comment]
people not voting for a map is not an issue. if you want mandatory map rotation, please create a thread on the forums asking headmins to toggle that configuration as right now we are on the "player's choice" configuration

**Comment by san7890** [comment]
if five map votes run and north star is not included in any single one of them, then there is a bug.

otherwise, there's no logical reason for this to be breaking the way it is, especially since there were indeed rounds with it running.
