### ISSUE TITLE
NTOS error in chat on server join

### ISSUE THREAD

**Issue by dallaszzz** [tgstation/tgstation#79769]
NTOS error in chat on server join for unknown reasons with "syntax error" as listed reason (image below)

EDIT: i got the exact same error again next round start and the fix chat verb works to fix it

roundID: 218851

Test merges:
[#79479: 'Adds a Chat Reliability Layer' by ZephyrTFA at commit 32a13db1fe](https://www.github.com/tgstation/tgstation/pull/79479)
[#79698: '[READY] Adds rabbit infusion to genetics' by Iamgoofball at commit 4e8b094aa7](https://www.github.com/tgstation/tgstation/pull/79698)
[#79721: 'The Tackleling: Unarmed bonuses and features contribute to tackle success and failure, significant outcome overhaul, among other things' by necromanceranne at commit 3e08a8d345](https://www.github.com/tgstation/tgstation/pull/79721)

![image](https://github.com/tgstation/tgstation/assets/96160322/d708c556-ab65-473e-9d47-405cd7230447)

**Comment by SyncIt21** [comment]
Duplicate #79576
