### ISSUE TITLE
Atrocinator module still makes you slip on wet tiles

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#79764]
Reporting client version: 514.1589

## Round ID:
[218843](https://scrubby.melonmesa.com/round/218843)

## Testmerges:
- [[READY] Adds rabbit infusion to genetics](https://www.github.com/tgstation/tgstation/pull/79698)
- [Adds more bitrunning antagonists + fixes (READY)](https://www.github.com/tgstation/tgstation/pull/79522)
- [Mob `attackedby` / `check_block` refactor, plus some minor cleanup of `attack_x` procs](https://www.github.com/tgstation/tgstation/pull/79563)

## Reproduction:
- Use Atrocinator module to start walking on ceilings
- Walk over lube
- Slip
- Immersion ruined

**Comment by Admiral-Gigaton** [comment]
my immersion is dead and my day is ruined
