### ISSUE TITLE
Bitrunner got no hands

### ISSUE THREAD

**Issue by TheSilverNuke** [tgstation/tgstation#79786]
Reporting client version: 514.1589

## Round ID:
218929
218954
218965

## Testmerges:
- [Adds a Chat Reliability Layer](https://www.github.com/tgstation/tgstation/pull/79479)
- [[READY] Adds rabbit infusion to genetics](https://www.github.com/tgstation/tgstation/pull/79698)
- [The Tackleling: Unarmed bonuses and features contribute to tackle success and failure, significant outcome overhaul, among other things](https://www.github.com/tgstation/tgstation/pull/79721)

## Reproduction:

When entering a domain, regardless of which avatar you use or which domain is activated you will have no hands. I'm not sure how to replicate this as it was a pre-existing condition. As a result of this bug you cannot hold any items at all whatsoever.

![image](https://github.com/tgstation/tgstation/assets/36066032/78f3044f-e489-47f5-b15a-46488a1d6608)

**Comment by jlsnow301** [comment]
Will fix this when I get home- likely cause is the recent commit where I tried to shortcut deleting handheld items
