### ISSUE TITLE
Bitrunner hands disappear

### ISSUE THREAD

**Issue by Rustybuckets6601** [tgstation/tgstation#79808]
Reporting client version: 514.1589

## Round ID:
[218969](https://scrubby.melonmesa.com/round/218969)

## Testmerges:
- [[READY] Adds rabbit infusion to genetics](https://www.github.com/tgstation/tgstation/pull/79698)
- [Mob `attackedby` / `check_block` refactor, plus some minor cleanup of `attack_x` procs](https://www.github.com/tgstation/tgstation/pull/79563)

## Reproduction:
Start as bitrunner, choose a domain, enter and notice that your hands on your hud disappear and notice that you cannot pick up anything or adjust your sensors. The only thing i did differently was put on different clothes on my character that wasn't the bitrunner jumpsuit.

**Comment by jlsnow301** [comment]
Duplicate #79786
