### ISSUE TITLE
Plethora of issues in `tgui-sonar` analysis

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#79815]
## Reproduction:

Just go into the `/bin` file from the root of your repository and run `tgui-sonar.cmd`. You'll get a shitload of issues with excellent ones such as these:

![image](https://github.com/tgstation/tgstation/assets/34697715/5a262c64-f3f0-415e-a386-8aabe58fef70)

![image](https://github.com/tgstation/tgstation/assets/34697715/d9959d52-e9d3-4675-9bc4-26d7de439a85)

sigh... there's a bunch so if you're bored and competent at fixing js/tsx issues then you can easily crack a few of these out

**Comment by san7890** [comment]
why _don't_ we use `sonar` in CI anyways

**Comment by optimumtact** [comment]
wyci

**Comment by san7890** [comment]
@stylemistake was there ever an explicit reason why we don't use `tgui-sonar` in CI testing or did we just never use it that way? seems like a good utility to have for sanity unless it's not intended for that function

**Comment by stylemistake** [comment]
I felt many of the warnings would be annoying and require suppression, so I left it as a manual script to run.

**Comment by jlsnow301** [comment]
Should note that radar is considered deprecated
![image](https://github.com/tgstation/tgstation/assets/42397676/fec4af36-296a-4203-aa42-3b17f3ad6edd)

https://github.com/SonarSource/eslint-plugin-sonarjs
However, running this produces far less errors. Perhaps we (or I) could fix these then move to sonarjs
