### ISSUE TITLE
Mesons can see people through walls on multi-z

### ISSUE THREAD

**Issue by Rustybuckets6601** [tgstation/tgstation#79817]
Reporting client version: 514.1589

## Round ID:
[218987](https://scrubby.melonmesa.com/round/218987)

## Testmerges:
- [[READY] Adds rabbit infusion to genetics](https://www.github.com/tgstation/tgstation/pull/79698)
- [Mob `attackedby` / `check_block` refactor, plus some minor cleanup of `attack_x` procs](https://www.github.com/tgstation/tgstation/pull/79563)

## Reproduction:
put on mesons on tram, spawn a person on a lower floor, and block your sight with a wall between you and them. you'll see them and other objects on the lower floor when you shouldn't be able to.

**Comment by SyncIt21** [comment]
Duplicate #53783
