### ISSUE TITLE
Ethereal Pirates can't use their own launchpad

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#79818]
Reporting client version: 514.1589

## Round ID:
[218987](https://scrubby.melonmesa.com/round/218987)

## Testmerges:
- [[READY] Adds rabbit infusion to genetics](https://www.github.com/tgstation/tgstation/pull/79698)
- [Mob `attackedby` / `check_block` refactor, plus some minor cleanup of `attack_x` procs](https://www.github.com/tgstation/tgstation/pull/79563)

## Reproduction:

Turns out that the Geode pirates can't even use their own launchpad because launchpads are designed to not be usable on shuttles. Which kind of defeats the entire purpose of having one on the shuttle to begin with

**Comment by DaydreamIQ** [comment]
Upon looking into prs involving the launchpad I found that #79335 is responsible for it.

**Comment by Admiral-Gigaton** [comment]
> Upon looking into prs involving the launchpad I found that #79335 is responsible for it.

campbell's revenge: small, but strong
