### ISSUE TITLE
autolathe printed items seem to have less and less material when printing in bulk

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#79828]
Reporting client version: 514.1589

## Round ID:
[219023](https://scrubby.melonmesa.com/round/219023)

## Testmerges:
- [Fixes chat bluescreen](https://www.github.com/tgstation/tgstation/pull/79821)
- [[READY] Adds rabbit infusion to genetics](https://www.github.com/tgstation/tgstation/pull/79698)

## Reproduction:

1. print 5 toolboxes in bulk
2. put them back into the autolathe
3. they contain much less material

**Comment by moocowswag** [comment]
Autolathes do not print stuff at 100% efficiency unless fully upgraded i think.

**Comment by mc-oofert** [comment]
> Autolathes do not print stuff at 100% efficiency unless fully upgraded i think.
> 
> Youre paying like an extra 50% or so of the material cost at t1 parts or something like that.

it had a femto servo

**Comment by Dorsisdwarf** [comment]
Is the bug being reported here that bulk-printed toolboxes contain less material than toolboxes printed one at a time?

**Comment by SyncIt21** [comment]
Is the problem specific only to toolboxes or all items in general?. If it's only toolboxes then you should change the title to specify that and wether they are printed in bulk or not could be irrelevant
