### ISSUE TITLE
Radioactive Nebula active at round start

### ISSUE THREAD

**Issue by lessthnthree** [tgstation/tgstation#79845]
## Round ID: [219074](https://scrubby.melonmesa.com/round/219074)

The round has the Radioactive Nebula trait and it's radioactive at roundstart, before the 20 minute timer.

![image](https://github.com/tgstation/tgstation/assets/83487515/2580439c-561a-48a7-a49e-3fb0eff7e0ed)

8 minutes in, this ran twice.

![image](https://github.com/tgstation/tgstation/assets/83487515/a04a8758-cd55-47cb-a1c0-6a5374a8b21c)

![image](https://github.com/tgstation/tgstation/assets/83487515/e5009287-ec55-4ae1-b16c-a7d1ca97a35b)

**Comment by Time-Green** [comment]
For fucks sake it's not allowed to run on icebox. I swear if it's an admin again

**Comment by Time-Green** [comment]
It's not really a bug or oversight, I was aware of this. Admins can force radioactive nebula on icebox, either accidentally by the mapvote or just by not knowing it's consequences. I didn't think this would be a thing that would actually happen, but it happens (and this is not the first time)

I'll leave this up as a reminder for me to add baby proofing
