### ISSUE TITLE
staff of healing bolts do not heal babelism

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#79855]
if an admin runs the Summon Magic event and someone rolls a staff of babel, anyone that person blasts with it will be FUCKED for the rest of the round, unable to understand or speak to anyone who doesn't speak their specific language. it is literally drone-tier gameplay.

I'd be fine with this if you could heal this with magic, but, uh, even aheals from staves of healing can't cure it. I think your only hope is a bolt of change?

**Comment by ninjanomnom** [comment]
It wouldn't be a bad change to make a way of curing the staff of babel, but this isn't a bug.
