### ISSUE TITLE
The bag of a latejoining security officer can be darkened and unusable.

### ISSUE THREAD

**Issue by Pickle-Coding** [tgstation/tgstation#79850]
## Round ID:
[219093](https://scrubby.melonmesa.com/round/219093)

## Reproduction:
Choose department satchel as your character's bag. Latejoin as a security officer. Notice that your bag is oddly darker than usual. Attempt to access its contents or examine it. Unresponsive.

**Comment by deathrobotpunch** [comment]
I use satchel and have never had that issue
