### ISSUE TITLE
Basic mobs move during nuke of  station/narnar/other

### ISSUE THREAD

**Issue by Admiral-Gigaton** [tgstation/tgstation#79870]
Reporting client version: 514.1589

## Round ID:
[219176](https://scrubby.melonmesa.com/round/219176)

## Reproduction:

basic mobs (or at least lavaland mobs, when on lavaland) move during cutscene of station going bye bye. this supposed to happen? if so, am stuppy. if not, help!

**Comment by MrMelbert** [comment]
They should be respecting `no_transform` when moving, see #79627
