### ISSUE TITLE
Bitrunning with Claustrophobia kills you

### ISSUE THREAD

**Issue by Xander3359** [tgstation/tgstation#79900]
Reporting client version: 514.1589

## Round ID:
[219336](https://scrubby.melonmesa.com/round/219336)

## Reproduction:
- Give yourself claustrophobia quirk
- Enter a bitrunning simulation
- ( I personally did the fishing one for ~20 minutes)
- Exit the pod
You will now suffocate to death.

**Comment by DATA-xPUNGED** [comment]
Ohh so that was what that was, it basically "holds" the no oxygen thing until you leave bitrunning, where it will then be unstoppable

**Comment by timothymtorres** [comment]
Duplicate of #79226
