### ISSUE TITLE
Dimentional Anomalies also transform surgery tables

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#79901]
Reporting client version: 514.1589

## Round ID:
[219336](https://scrubby.melonmesa.com/round/219336)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/76874615/65c007a2-9d61-4e42-9727-03495c9dfed7)
I know that they're called surgery *tables*, but this is ridiculous
(I mostly just want to know if this is an intended interaction or not)

**Comment by nianjiilical** [comment]
more of an oversight than a bug i'd think, since surgery tables are just silver tables, and all silver tables are surgery tables

it wouldn't hurt to split them up since theres no way to build a normal silver table

**Comment by Time-Green** [comment]
> I know that they're called surgery tables, but this is ridiculous

![image](https://github.com/tgstation/tgstation/assets/7501474/d0dac123-d788-4ca2-aba7-997a109bcfb2)

**Comment by Jacquerel** [comment]
I mean its annoying for it to remove your surgery tables but on the other hand anomalies are sort of supposed to at least inconvenience you

**Comment by AdipemDragon** [comment]
Inconvenience or not, it's funny how this just shows the operating table being a basic table subspecies, which honestly just. has so much soul to it, like "what do we surgery on" "uhhhh fuck, silver table, got it"
again, i just want to know if this is an intended interaction or not, since it Is a Separate'y Feeling Furniture that doesn't feel like it meshes with the other tables, and yet here we are

**Comment by Jacquerel** [comment]
my personal opinion as The Person Who Made It is that this isnt a bug because it _is_ a silver table and it messing up rooms is sort of the point (even if it is not how it usually happens)
I can't think of a good fix for this which wouldn't be "just exclude this one specific kind of material when applied to a table" which would be a cure worse than the disease

**Comment by san7890** [comment]
me myself personally i think science should do their job and dispel anomalies faster before they completely screw up important equipment

**Comment by SuperNovaa41** [comment]
I agree
