### ISSUE TITLE
Vault doors on derelict drone station are conventionally hackable

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#79926]
Reporting client version: 514.1589

## Round ID:
[219427](https://scrubby.melonmesa.com/round/219427)

## Testmerges:
- [Black Widow DLC - Spider Poison Rework ](https://www.github.com/tgstation/tgstation/pull/79746)

## Reproduction:

That is, the doors to the vault on Kosmicheskaya Stantsiya 13 can be breached by standard engineering means where you remove the wire-guard plasteel using a standard engineering toolkit, thus bypassing entirely the vault controller's "power goal" requirement to unlock the doors.

Maybe they're supposed to be bolted but aren't or something?  Not entirely sure whats going on here but have seen drones more than once just wires hacking open the vault without doing the "objective" of filling the power computer thing.

**Comment by deathrobotpunch** [comment]
more of an oversight than bug
