### ISSUE TITLE
Cooking with reagents creates blank reagent

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#79931]
Reporting client version: 514.1589

## Round ID:
[219461](https://scrubby.melonmesa.com/round/219461)

## Testmerges:
- [Updates several packages for tgui](https://www.github.com/tgstation/tgstation/pull/79895)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/76874615/3cdfe687-7e91-429f-9ec3-8ecc0bc03cd9)

Basically on the tin. Try to make a khachapuri and enjoy your leftover pure white [ ________ ] that used to be the egg reagents. It goes away if the contents gets updated again, by, say, putting another egg in the beaker.

**Comment by SyncIt21** [comment]
Your screenshot does not explain the problem. I don't see [ ________ ] in the screenshot. Also by blank reagent you mean upon examining the reagent name is blank right? Put that in the tin cause it sounds misleading

**Comment by Dorsisdwarf** [comment]
Screenshot seems to show the issue? - there are 6 units of reagents in the beaker, but there is only empty space in the "beaker contents" part of the condimaster UI where it should show what those 6 units of reagent are.

**Comment by xXPawnStarrXx** [comment]
I can confirm this is a current issue. It will take reagents from containers, replacing them with a null reagent. The container could have 100u Tomato Ketchup, you could use 80u and it'd have 100u in the beaker, 20u being ketchup, 80u being blank.
