### ISSUE TITLE
pyrosium changing temperature of a beaker does not set off stabilized sorium (possibly other chems?)

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#79933]
Reporting client version: 514.1589

## Round ID:
[219479](https://scrubby.melonmesa.com/round/219479)

## Testmerges:
- [Removes autophago, ARDS, and alkali; bumps plasma fixation and regen coma down to level 7 to fill the void](https://www.github.com/tgstation/tgstation/pull/79873)
- [Changes Virology Rather Than Killing It](https://www.github.com/tgstation/tgstation/pull/79854)

## Reproduction:

1. make stabilized sorium
2. put pyrosium in the same beaker
3. heat a lot via oxygen + pyrosium reaction
4. sorium does not trigger, changing temperature via reaction chamber immediately sets it off

**Comment by MrMelbert** [comment]
this is because Pyrosium sets chem temp directly rather than using the `expose_temperature` helper, meaning `handle_reactions` is never called. 

Chem temp should be read only.
