### ISSUE TITLE
Ai buttons don't work on 515

### ISSUE THREAD

**Issue by Rex9001** [tgstation/tgstation#79962]
## Reproduction:

Upgrade to most recent BYOND beta
Play AI
![Skärmbild 2023-11-26 203613](https://github.com/tgstation/tgstation/assets/120136161/e6179e16-1d12-445e-a4ab-d5d8801924b5)
Marvel as none of your buttons except the regular action buttons/antag prompts function

**Comment by nevimer** [comment]
I tried to report this bug to Lummox, the coordinate types are entirely broken in 515. Someone has to send them a code sample to demo the bug in 515.

**Comment by JohnFulpWillard** [comment]
515.1561 reportedly fixes this, can you confirm?

**Comment by SyncIt21** [comment]
This isn't a byond bug at all. It has  been the case for a quite a while now 

- #78827

**Comment by TheSmallBlue** [comment]
> 515.1561 reportedly fixes this, can you confirm?

Does this version even... exist? The earliest version of 515 is 515.1590, 1561 would be 514

**Comment by JohnFulpWillard** [comment]
Yeah lummox said it was fixed but it hasn't been released yet

**Comment by SuperNovaa41** [comment]
Duplicate

**Comment by Rex9001** [comment]
> Duplicate

Didnt see that, mb

**Comment by Dorsisdwarf** [comment]
> Duplicate

You're supposed to mention the duplicate issue number
