### ISSUE TITLE
some heretic mobs don't have unique names (e.g. "Raw Prophet" instead of "Raw Prophet (343)")

### ISSUE THREAD

**Issue by Fikou** [tgstation/tgstation#79969]
![image](https://github.com/tgstation/tgstation/assets/23585223/b2b8806b-c09b-41c4-84f8-935333d78f5b)

like its raw prophet instead of raw prophet (731) which makes investigation confusing

**Comment by san7890** [comment]
this isn't an issue with the Player Panel? raw prophets just do not have the `unique_name` boolean set on them.

**Comment by san7890** [comment]
anyways to fix this just add `unique_name = TRUE` on `/mob/living/basic/heretic_summon` and remove it for stuff like Armsy and the like?

**Comment by san7890** [comment]
in an ideal world we would be using the unique mob tag system more often but sadly we do not live in one

**Comment by MrMelbert** [comment]
I don't think the should be `Raw Prophet (420)` so IMO it's a player panel issue

**Comment by san7890** [comment]
it's an issue that impacts logging and the player panel (though you really should be searching by ckey or something at that point imo)

**Comment by san7890** [comment]
i still think searching by ckey is a better idea but whatever
