### ISSUE TITLE
Transforming into hulk with advanced cybernetic arms changes your arms into regular, non-advanced cybernetic arms

### ISSUE THREAD

**Issue by Eronymun** [tgstation/tgstation#79998]
Reporting client version: 515.1620

## Round ID:
[219638](https://scrubby.melonmesa.com/round/219638)

## Testmerges:
- [Removes autophago, ARDS, and alkali; bumps plasma fixation and regen coma down to level 7 to fill the void](https://www.github.com/tgstation/tgstation/pull/79873)
- [Blood brothers is now a single person conversion antagonist](https://www.github.com/tgstation/tgstation/pull/79971)

## Reproduction:
Simply install advanced cybernetic arms and then inject yourself with a hulk mutator, you arms will transform from the advanced arms to the regular cybernetic arms.

**Comment by moocowswag** [comment]
thats strange cause hulk isnt necessarily a full species transform, atleast it never triggered the healing like others used to.

**Comment by necromanceranne** [comment]
![image](https://github.com/tgstation/tgstation/assets/40847847/f969f8f0-d647-4934-bfe7-6d4b96a5b623)

I can't seem to recreate this?

**Comment by Eronymun** [comment]
I think I failed to mention that I also had the strong arm implant added when I transformed from human to hulk with the advanced arms added. Maybe that plays some part in this?

> ![image](https://private-user-images.githubusercontent.com/40847847/286372739-f969f8f0-d647-4934-bfe7-6d4b96a5b623.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyOTA4NTYsIm5iZiI6MTcwMTI5MDU1NiwicGF0aCI6Ii80MDg0Nzg0Ny8yODYzNzI3MzktZjk2OWY4ZjAtZDY0Ny00OTM0LWJmZTctNmQ0Yjk2YTViNjIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDIwNDIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzOGY4M2RhZDk1YzY4ZmMwYTE2ZmQ3MTkwM2QyMWQyOTRkZGQxMzdkZmFjMjdjYjdhNjA4NzU2YTVlODk3NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MSaK6hAEOITQcxLWPP9FE1708nsUZVR2_Gi9mng2QSQ)
> 
> I can't seem to recreate this? Note that I included surplus limbs, just in case.

**Comment by necromanceranne** [comment]
tested that too, still nothing.

**Comment by Artemchik542** [comment]
Tested, all works fine with all types of robo limbs, nothing changed as it should be.
<details>![543](https://github.com/user-attachments/assets/80795b26-eeb9-4355-ace8-a5ccc2370936)</details>
And also with strong-arm implants. One arm normal, one robo (not transformed as suggested in the problem)
<details>![12](https://github.com/user-attachments/assets/dab0bb5c-9aee-468e-95f2-5acb29dee89f)</details>

**Comment by Sadboysuss** [comment]
reproduce the issue and re-report if you like
