### ISSUE TITLE
Lamps in inventories act weird

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#80005]
Reporting client version: 515.1620

## Round ID:
[219652](https://scrubby.melonmesa.com/round/219652)

## Testmerges:
- [Improves tgui build speed](https://www.github.com/tgstation/tgstation/pull/79916)
- [Changes Virology Rather Than Killing It](https://www.github.com/tgstation/tgstation/pull/79854)
- [Blood brothers is now a single person conversion antagonist](https://www.github.com/tgstation/tgstation/pull/79971)

## Reproduction:
![light2](https://github.com/tgstation/tgstation/assets/76874615/8629698b-4532-413d-8f2d-f42a184c4bd9)
![light3](https://github.com/tgstation/tgstation/assets/76874615/f91a4dbe-c4a7-42ed-8474-2e3fe8456232)

originally I thought it was only about them being in belts, but just having it in hand makes them act like this too.
and apparently the location update on map state update isn't consistent, either, but it's still Weird that it happens.

**Comment by deathrobotpunch** [comment]
#79753 maybe related with this?

**Comment by GPeckman** [comment]
At a random guess, this might be because lamps use `light_system = STATIC_LIGHT` instead of one of the movable variants.

**Comment by LemonInTheDark** [comment]
it isn't. static is a shitty name I will scalp roh. it's really turf vs overlay lighting.
lamps should be turf based, looks better and they rarely move (maybe we could update dynamically? regardless).
the issue is objects don't update turf lighting on movement properly
