### ISSUE TITLE
Debug mode  broken in 515

### ISSUE THREAD

**Issue by SyncIt21** [tgstation/tgstation#80008]
1)Upgrade your Byond to 515.1620
2)Open visual studio code
3)Add a break point anywhere in your code and test it
4)Run in debug mode
5)Test that code where you put the break point on and watch as nothing happens 
6)The pause button on the debug bar also does not work 

Can confirm this is a 515 bug because just yesterday it was working until I did a clean build and updated my branch today after which it complained about the compiler version being too low and I upgraded and now we are here.

Also my Dreammaker language server extension is crashing way more frequently now. Now I know this is a Byond issue but in this repo we can atleast revert the 515 Upgrade PR till they have figured this out or maybe something else can be done about it here?

**Comment by Y0SH1M4S73R** [comment]
This is because the debugger relies on auxtools, which hasn't been updated to support 1620.

**Comment by MrMelbert** [comment]
Not our issue

**Comment by san7890** [comment]
@willox FYI in any case

**Comment by SyncIt21** [comment]
As a temporary workaround i downgraded to the minimum supported version of Byond on this repo that 515.1609 which i downloaded from [here](http://www.byond.com/download/build/515/) and everything works again.

Currently auxtools only has support for 515.1606 so until that is upgraded i'll stick to this version
