### ISSUE TITLE
changeling external slot items aren't deleted on gibbed by shuttles, and can be worn.

### ISSUE THREAD

**Issue by dalmationer** [tgstation/tgstation#80028]
## Round ID: [219719](https://scrubby.melonmesa.com/round/219719)

In the round above, I put on a toolbelt which was left over from a gibbed changeling. I figured that as it dropped, it was a real item.
It can be put on as normal, but once on, cannot be removed or interacted with. An admin had to delete it. 
My GUESS at why this happened is that the jumpsuit was destroyed first, which makes the toolbelt fall off, but it's anyone's guess if that's right.

## Reproduction:
Gib a changeling, e.g. with a shuttle, while it's wearing a toolbelt.
Put on the toolbelt.

**Comment by Sadboysuss** [comment]
couldn't reproduce on latest master, looks like this isn't an issue anymore
