### ISSUE TITLE
Motorised Wheelchair raises and lowers when climbing tables.

### ISSUE THREAD

**Issue by dalmationer** [tgstation/tgstation#80027]
## Round ID: [219717](https://scrubby.melonmesa.com/round/219717)

![image](https://github.com/tgstation/tgstation/assets/7063681/e6c589b2-ceae-47a0-872e-54236d8b971b)

## Reproduction:

Get on a motorised wheelchair, get off of it.
Occasionally it will rise upwards or lower downwards.
I'm not very sure what causes this, but it looks very funny.

**Comment by deathrobotpunch** [comment]
where d you even get a motorised wheelchair?

**Comment by lizardqueenlexi** [comment]
This appears to happen when you climb onto any subtype of `vehicle/ridden` from a table (and not even always). As to why, I can't figure that out.

**Comment by AdipemDragon** [comment]
oh, from a table? then https://github.com/tgstation/tgstation/pull/79797 is at play, it probably trying to reset the offset while also locking you in goes wrong, or something around there

**Comment by dalmationer** [comment]
> where d you even get a motorised wheelchair?

they can be made via the crafting menu. recipe is 10 iron, 8 rods, 2 servos, one capacitor

**Comment by dalmationer** [comment]
hilariously, I found out in round 219753 that this also affects ridden animals horizontally. I was flying about beside a space shark.
