### ISSUE TITLE
Confirming that you have read an admin message does not work and it will continue to appear on login

### ISSUE THREAD

**Issue by Isratosh** [tgstation/tgstation#80020]
Reporting client version: 514.1589

## Round ID:
[219703](https://scrubby.melonmesa.com/round/219703)

## Testmerges:
- [Blood brothers is now a single person conversion antagonist](https://www.github.com/tgstation/tgstation/pull/79971)
- [Changes Virology Rather Than Killing It](https://www.github.com/tgstation/tgstation/pull/79854)
- [Drops ie8 support](https://www.github.com/tgstation/tgstation/pull/79974)

## Reproduction:
1. do something dumb and log off
2. have an admin give you a message (the variant of admin note)
3. log in, see the message, and click the link that says "Click here to verify you have read this message"
4. get no feedback in chat, log in again later and continue to see the message forever

I have tested and reproduced this by giving myself a message and logging in with admin status still active which may affect it, but I have also had a player report this issue to me.

**Comment by wesoda25** [comment]
duplicate: #66619
