### ISSUE TITLE
Gulag teleporter seemed to gib someone

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#80029]
Reporting client version: 514.1589

## Round ID:
[219721](https://scrubby.melonmesa.com/round/219721)

## Testmerges:
- [Organ movement refactor *Un-nullspaces your organs*](https://www.github.com/tgstation/tgstation/pull/79687)

## Reproduction:

Not big on reporting one offs but another admin said they'd seem similar on a different map so I guess its not a one off.

Player gets teleported to gulag and gibs, on the source teleporter pad, there doesn't seem to be much log trace other than acknowledgements that the mob died (deaths.html just says they died at 7.5 burn damage total, the game log shows the teleport from gulag and 30ms later the mob is disowned.  there is no trace of the mob under 'dead entities', no sign of a brain, pretty hard gibbed)

```
    Line  7969: [2023-11-29 21:16:51.348] GAME: CoolCatIsFeelingGroovy/(Ashley Quinn) teleported DINKO4/(Lawrence Quinn) to the Labor Camp  (69,32,6) for 300 points. (Transfer Centre (145,104,5))
    Line  7970: [2023-11-29 21:16:51.376] GAME: *no key*/(Lawrence Quinn) *no key*/(Lawrence Quinn) is no longer owning mob Lawrence Quinn(/mob/living/carbon/human) (Transfer Centre (145,105,5))
    Line  7971: [2023-11-29 21:16:51.376] GAME-ACCESS: Mob Login: DINKO4/(Lawrence Quinn) was assigned to a /mob/dead/observer
```

```
2023-11-29 21:16:51 [mob_3414] (0,0,0) || Lawrence Quinn (dinko4) has died at (Transfer Centre (145,105,5)).
BRUTE: 0 BURN: 7.5 TOX: 0 OXY: 0 CLONE: 0 STAM: 0
Brain damage: 0
Blood volume: 560cl (100%)
Reagents:
Blood:
Stomach:
```

**Comment by Jacquerel** [comment]
The testmerge is very suspect for this one

**Comment by Jacquerel** [comment]
```
// strips and stores all occupant's items
/obj/machinery/gulag_teleporter/proc/strip_occupant()
	if(linked_reclaimer)
		linked_reclaimer.stored_items[occupant] = list()
	var/mob/living/mob_occupant = occupant
	for(var/obj/item/W in mob_occupant)
		if(!is_type_in_typecache(W, telegulag_required_items))
			if(mob_occupant.temporarilyRemoveItemFromInventory(W))
				if(istype(W, /obj/item/restraints/handcuffs))
					W.forceMove(get_turf(src))
					continue
```

As located by Pepsiman, with the testmerged #219721 these lines likely result in removing every organ from those destined for the gulag.

**Comment by iprice** [comment]
Yeah, further testing showed that the gulagged mob was dismantled into parts and put into the gulag storage thing like posessions normally are.

Additionally the VV dropdown menu "Drop Everything" will brutally murder the mob which will then manage to show the rare medical scan line of "Is missing a torso".  (Foot note, TP 'undress' command works properly)

But all do seem related to the TM

**Comment by Time-Green** [comment]
100% the testmerge, it apparently confiscates someones bodyparts and organs as well as their clothed

**Comment by DaxDupont** [comment]
Should've kept this as a feature
