### ISSUE TITLE
Closets not affected when sprayed with Eigenstasium

### ISSUE THREAD

**Issue by Confrade** [tgstation/tgstation#80039]
## Reproduction:
I wanted to make some Eigenstasium for some closets, i done everything correctly.
Correct pH(around 11 to 12), correct purity(above 80%) and when i sprayed on the closets it didn't worked.

Tried the station's closets, nothing. Tried to make some closets myself, still nothing.
So i'm either very dumb or there's something wrong with it, i'd like to ask for the coders to check it please.

Thanks.

**Comment by Confrade** [comment]
I did stacked them, didn't worked.
Sorry i should've said that in the OP.

**Comment by Confrade** [comment]
I tested on the purity machine and i had it between 80% to 93% purity.

The exact recipe i do is:

10u Caramel
10u Bluespace Dust
10u Stable Plasma
30u Oxygen

All of it with the pH of 11 to 12(sweetspot is 11.7)

**Comment by SyncIt21** [comment]
I don't know what else to do. Did you follow the instructions on the video to stack lockers in that exact way? Either way the reagent itself works so there is nothing that can be done here

**Comment by ATH1909** [comment]
what were you using to apply the eigenstasium? a spray bottle? a beaker splash?

**Comment by Confrade** [comment]
Maybe it was the location then, i tested yesterday and it worked.

I put the closets outside the medbay, where the disposals from Cargo comes from.
Still weird not working, i'll try again when i have the opportunity and send a video if i can, otherwise you can ignore this issue.

**Comment by newfren** [comment]
Reporting client version: 514.1589



## Issue Summary



## Round ID:
220375




## Testmerges:
- [the unfuckening of clothing rendering](https://www.github.com/tgstation/tgstation/pull/79784)
- [Remove delayed in MassInsert](https://www.github.com/tgstation/tgstation/pull/80196)
- [Reworks SDQL2 Code to not be as reliant on `usr`](https://www.github.com/tgstation/tgstation/pull/80222)


## Reproduction:
issue reproduced on tramstation this round, no matter of spraying would work, 100% pure eigen.
