### ISSUE TITLE
Laying down on some stuff is bad now

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#80050]
Reporting client version: 515.1620

## Round ID:
[219769](https://scrubby.melonmesa.com/round/219769)

## Testmerges:
- [Changes Virology Rather Than Killing It](https://www.github.com/tgstation/tgstation/pull/79854)
- [Drops ie8 support](https://www.github.com/tgstation/tgstation/pull/79974)

## Reproduction:
![slep](https://github.com/tgstation/tgstation/assets/76874615/92e97dab-95eb-4deb-bcf6-811a96400ad9)
Simply put, the beds were already made with the preexisting player offset when laying down, OR they had their own (i.e. operating table)
but now the "standing on top" offset from #79797 doesn't go away when laying down on some of these, so laying down in something like any bed or an open crate just looks kind of weird
Beds (and operating tables, maybe more) are doubly weird, too, since this offset kind of goes in the negative or something?? when you buckle to them, so now the offset's too low.

**Comment by Ghommie** [comment]
Oh sheep, I'll take care of it soon.

**Comment by deathrobotpunch** [comment]
also FUCKING MAKE IT SO YOU SLEEP FACING THE PILLOW please it is ruining mah immersion
