### ISSUE TITLE
Chat isn't interpreting line breaks properly

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#80100]
Reporting client version: 515.1620

## Round ID:
[219896](https://scrubby.melonmesa.com/round/219896)

## Testmerges:
- [Changes Virology Rather Than Killing It](https://www.github.com/tgstation/tgstation/pull/79854)
- [Attack chain refactoring: Broadening `tool_act` into `item_interact`, moving some item interactions to... `atom/item_interact` / `item/interact_with_atom`](https://www.github.com/tgstation/tgstation/pull/79968)
- [Ports React](https://www.github.com/tgstation/tgstation/pull/80044)

## Reproduction:

1) Run a vote
2) Pick options
3) Observe

![image](https://github.com/tgstation/tgstation/assets/7019927/3a5312ce-be6b-458f-8806-f02b3bae4b79)

These should be linebroken as such:

Restart Vote
Restart Round: 3
Continue Playing: 63
Vote Result: Continue Playing

**Comment by Potato-Masher** [comment]
This perhaps might be due to #80044 being testmerged.

**Comment by jlsnow301** [comment]
Fixed in the latest commit
