### ISSUE TITLE
Chasms can have teleporter beacons thrown into them, allowing for exceedingly lame antagonist play

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#80101]
This is a weird one, because it's almost certainly not an oversight or a bug, but it's leading to some fuckshit, so I think it needs to be changed. Someone can close this if it's not technically an issue.

Basically, the gimmick goes like this:

1) Throw a teleporter beacon into a chasm.
2) Use a hand teleporter to open a portal to that beacon.
3) Either run into the portal as a changeling while being chased (who can survive falling into a chasm) or force someone into the portal.
4) They die in an unrecoverable state.

There is very, very little actual counterplay to this. The non-changeling method is not as bad, but having a portal opened directly in front of you while walking just to end up dead and unrecoverable is about as lame as it gets.

Not sure what the fix to this should be. Maybe find a way to qdel beacons if they fall into a chasm?

**Comment by TheVekter** [comment]
> skill issue

See, I don't think it is, because if someone can open a portal one space in front of someone who's walking and they lag and can't _not_ walk into it...

**Comment by Dawnseer** [comment]
Not unrecoverable. You can fish people up from chasms. Even got a rescue hook that really raises the chance of recovering them.
