### ISSUE TITLE
Selecting `/obj/narsie` with advanced buildmode will end the round

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#80125]
## Reproduction:

This is essentially a dupe of #80124 , but I'm creating a separate issue to highlight the importance of this:

Because selecting an object with build-mode instantiates one of that object in nullspace to create a preview image of it, selecting Nar'sie will.. run the whole 'round end' thing. And end the round. Without actually spawning it. This is not ideal.

**Comment by Fikou** [comment]
cause is https://github.com/tgstation/tgstation/pull/79538
i dont know why it uses an atom to create as arg instead of a mutable appearance
