### ISSUE TITLE
Red Medibot can't heal anyone

### ISSUE THREAD

**Issue by Vermidia** [tgstation/tgstation#80135]
## Reproduction:

Make a red medibot from an assembly (the one made from an advanced first aid kit)
Watch as it doesn't try to heal anyone

Becoming the bot also makes it not heal anyone (It doesn't spout out a message that it's done healing, and doing a heal action doesn't heal a person and doesn't spout one of their done healing lines)

I also gave it a hat but that shouldn't effect anything I think.

**Comment by san7890** [comment]
@Ben10Omintrix

**Comment by Windryn** [comment]
Just to add to this, medbots cannot seems to emote anymore *ping *chime *warn *buzz all seem to no longer work
Also when playing a medbot, they seem to move slower than before
