### ISSUE TITLE
Tram coffee maker lacks cartridges

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#80131]
Reporting client version: 515.1620

## Round ID:
[219949](https://scrubby.melonmesa.com/round/219949)

## Testmerges:
- [Attack chain refactoring: Broadening `tool_act` into `item_interact`, moving some item interactions to... `atom/item_interact` / `item/interact_with_atom`](https://www.github.com/tgstation/tgstation/pull/79968)
- [Changes Virology Rather Than Killing It](https://www.github.com/tgstation/tgstation/pull/79854)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/76874615/7ff8ecbf-acfc-4179-8984-ceacd339e284)
in this side of tram's sec hallway, this coffee maker has a cartridge pack rack. in here, you would expect it to have something to make coffee with, but no
unsure if this appears anywhere else, and if it also empty, but I wanna assume that these would have to be pre-filled

**Comment by MrStonedOne** [comment]
Your issue report should describe what is wrong in plain terms. ideally at the start of the issue report and/or in the issue title

Something like "Coffee maker on tram has no coffee cartridges"

**Comment by AdipemDragon** [comment]
i should stop making issue reports at 2 am
