### ISSUE TITLE
Medibot being flipped makes their hat float

### ISSUE THREAD

**Issue by Vermidia** [tgstation/tgstation#80134]
## Reproduction:

Flip a medibot over or use the *flip emote, you can see the hat floats
![upsidedown](https://github.com/tgstation/tgstation/assets/32827189/99c6972b-61af-439b-b019-3e61d75ae462)

**Comment by san7890** [comment]
@Ben10Omintrix maybe hook into the flipped medibot signal (one has to exist right, if not make one) and then figure out the offsets on the element? blurgh

**Comment by san7890** [comment]
actually easiest thing to implement + makes the most sense is to just detach the element and hat on flip
