### ISSUE TITLE
Toasted Seeds lack nutrients and cannot be eaten.

### ISSUE THREAD

**Issue by Bibarra** [tgstation/tgstation#80143]
## Round ID:
 219990

## Reproduction:

Make Toasted Seeds
Try to eat Toasted Seeds
Realize you can't
Grind it up
Nothing in the beaker

E: After further testing, both seeds harvested from a grown plant and seeds straight from the vendor produce the same result. Other people also are unable to eat the toasted seeds.

**Comment by the-orange-cow** [comment]
I love noticed something similar to plants that contain no reagent.  Completely inedible.

**Comment by Bibarra** [comment]
Reproduced it on live, on round 220238, even offered it to another player to try and they couldn't eat it either.
![image](https://github.com/tgstation/tgstation/assets/2476001/5f075a73-e815-421d-ae1f-347d93ed5c4f)
Both seeds harvested from a grown plant and seeds straight from the vendor produce the same result.

**Comment by SyncIt21** [comment]
> Both seeds harvested from a grown plant and seeds straight from the vendor produce the same result.

This is Important information. Make sure to add it to your issue body
