### ISSUE TITLE
Achieving Nirvana by Spiting God and Playing with Loaded Firearms: A Five-Step Guide

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#80158]
1. Burn a bible.
2. Empty a Russian revolver's cylinder and load 5 live .357 rounds back into it.
3. Spin the Russian revolver's cylinder.
4. Attempt to shoot yourself **in the head** with the Russian revolver. Your attempt will fail. If you don't hear a click, repeat from step 3.
5. Bask in the glory of your **+32** positive moodlet that will last for the next 5 minutes. Whenever you want to refresh it, repeat from step 3. No ammunition refills are necessary, as no ammunition was consumed in step 4.

Disclaimer: Side effects may include, but are not limited to, heart attacks, being targeted by hostile paranormal phenomena, spontaneous combustion, and unusually long slip distances. Consult your CMO to see if nirvana is right for you.

**Comment by ATH1909** [comment]
## What the fuck is going on here?

Alright, theatrics aside, what's going on here is pretty simple.

Burning a bible in step 1 causes that bible's corresponding god to curse you (indefinitely). This curse uses the bad omen system and has numerous effects, including the ones mentioned in the disclaimer (although the heart attacks can only happen if you stand near a mirror or get a cursed coupon).

One of these effects is preventing you from shooting yourself with a Russian revolver- presumably, the spirits don't want you to get off that easy. However, they only intervene _if the revolver has a live round in the active chamber_. Thus, you can keep playing Russian roulette with yourself until you win with no risk of dying, as the spirits will prevent you from actually firing the gun if doing so would make you lose. If the chamber is empty, the spirits won't stop you, and the gun will produce a telltale click.

Okay, so you can farm Russian roulette wins. So what? Your "prize" is just not dying, right?

Wrong.

If you win a game of Russian roulette while targeting your head and with at least one live round in the revolver's cylinder, you will receive the russian_roulette_win moodlet. This moodlet lasts for 5 minutes and has a strength equal to 2^[the number of live rounds in the gun's cylinder, not including the chambered round]. Since we have 5 bullets in our gun and can only win if the chamber is empty, that means we receive a 2^5=**+32 moodlet** whenever we win one of our rigged games of Russian roulette. For reference, being honked by a clown gives a +2 moodlet, being high gives a +6 moodlet, and being a fanatical cultist of a forbidden blood god gives a +10 moodlet.

The fix to this is to move the curse check to earlier in the code for shooting yourself with a Russian revolver.

**Comment by ATH1909** [comment]
https://www.youtube.com/watch?v=UuwtgoImxmM

**Comment by timothymtorres** [comment]
This is a pretty cool bug report. I was the one who coded the Russian roulette moodlet and I'm surprised someone prevented suicide by using it... regardless, having the bad omen is probably not worth the positive moodlet risk since you can die or get injured quite easily from it.

**Comment by timothymtorres** [comment]
Is there a reason you aren't fixing this yourself ATH? It sounds like a 5 minutes hotfix.

**Comment by ATH1909** [comment]
(for the record, I started working on this PR before tim made his comment)
