### ISSUE TITLE
Glass tables are broken beyond belief 2: Electric boogaloo

### ISSUE THREAD

**Issue by lnGoror** [tgstation/tgstation#80169]
Reporting client version: 514.1589

## Issue Summary
Remember #80085? ye the same thing, just glass tables instead of beds.

## Round ID:
[220082](https://scrubby.melonmesa.com/round/220082)

## Reproduction:

1.Build a glass table. 
2:
Table someone? does it.
Climb the table yourself? does it.
Shove someone over the table? Doesn't do it, but if you shove them off of another solid table onto a glass one, it will give em the offset too.

![image](https://github.com/tgstation/tgstation/assets/103280043/43782afb-9d99-4bc2-a260-8a7cb7b8a559)

**Comment by Mothblocks** [comment]
round isnt over yet, what server was this? this looks like a bug we fixed a while ago but some servers haven't updated (like bagil)

**Comment by san7890** [comment]
This round was on this commit, which is from a day ago (took a while to figure it out since scrubby didn't pull the logs womp womp): https://github.com/tgstation/tgstation/commit/7f704bb73ba71c1684adee88568766f65ab8ce75/
