### ISSUE TITLE
Starfront Saloon generating space tiles

### ISSUE THREAD

**Issue by linkylink21** [tgstation/tgstation#80163]
## Issue Summary
The new Starfront Saloon bitrun is spawning with space tiles, venting the entire place and making the run impossible to complete. It seems to be one of the modular bits that is causing it, as this issue only happens when it spawns in.

## Round ID:
[220030](https://scrubby.melonmesa.com/round/220030)

## Reproduction:
Load the Starfront Saloon bitrun.
Progress as normal.
Realize you are dying of no pressure or O2.
Push forwards and see a box with some space tiles around it.

**Comment by Mothblocks** [comment]
CC @jlsnow301
