### ISSUE TITLE
Coffin Cookies are invisible

### ISSUE THREAD

**Issue by excalisword** [tgstation/tgstation#80161]
Reporting client version: 514.1589

## Issue Summary

I made some coffin cookies, and they are invisible for some reason. 

## Round ID:
[220031](https://scrubby.melonmesa.com/round/220031)

## Testmerges:

None

## Reproduction:

Just make some coffin cookies and they will be invisible.

**Comment by deathrobotpunch** [comment]
SPOOOOKKKYYYYY
