### ISSUE TITLE
Marauder and Seraph mech cannons don't deal damage

### ISSUE THREAD

**Issue by Bm0n** [tgstation/tgstation#80170]
Reporting client version: 515.1620

## Issue Summary

The Marauder and Seraph's heavy pulse rifle cannon do no damage.

## Round ID:
[220085](https://scrubby.melonmesa.com/round/220085)

## Testmerges:
- [Changes Virology Rather Than Killing It](https://www.github.com/tgstation/tgstation/pull/79854)
- [Attack chain refactoring: Broadening `tool_act` into `item_interact`, moving some item interactions to... `atom/item_interact` / `item/interact_with_atom`](https://www.github.com/tgstation/tgstation/pull/79968)
- [Organ movement refactor *Un-nullspaces your organs*](https://www.github.com/tgstation/tgstation/pull/79687)

## Reproduction:

spawn mech in thunder dome, shoot someone, does nothing

**Comment by san7890** [comment]
Once fixed, someone should also write a unit test for this one (can be in same PR)

**Comment by CRITAWAKETS** [comment]
Seems to be a symptom of a much bigger issue where projectile_piercing doesn't seem to be actually hitting anything.
