### ISSUE TITLE
Blindfold In Pocket Blinds You

### ISSUE THREAD

**Issue by IsaacExists** [tgstation/tgstation#80184]
Reporting client version: 515.1620

## Issue Summary

Putting a blindfold in your pocket blinds you for some reason. Had an admin check up on it to confirm that it wasn't some sort of special blindfold or scenario.

## Round ID:
[220139](https://scrubby.melonmesa.com/round/220139)

## Testmerges:
- [Attack chain refactoring: Broadening `tool_act` into `item_interact`, moving some item interactions to... `atom/item_interact` / `item/interact_with_atom`](https://www.github.com/tgstation/tgstation/pull/79968)
- [Organ movement refactor *Un-nullspaces your organs*](https://www.github.com/tgstation/tgstation/pull/79687)
- [the unfuckening of clothing rendering](https://www.github.com/tgstation/tgstation/pull/79784)

## Reproduction:

Grab blindfold.
Put in pocket.
???
Blind!

**Comment by MrMelbert** [comment]
Caused by #79784 @Fikou 

![image](https://github.com/tgstation/tgstation/assets/51863163/109bd705-629a-48d5-9a62-9f9c0561a95f)

**Comment by SyncIt21** [comment]
This still a bug? If you look above the test merge was closed a while back
