### ISSUE TITLE
You can once again use goldgrubs to block colossus bolts

### ISSUE THREAD

**Issue by 1393F** [tgstation/tgstation#80181]
Reporting client version: 514.1589

## Issue Summary
You can tame a goldgrub and drag it behind you to use as a shield against colossus

## Round ID:
[220104](https://scrubby.melonmesa.com/round/220104)

## Reproduction:
tame a goldgrub and tell it to follow(so it won't run away)
drag it behind you
use as shield
![Screenshot (1758)](https://github.com/tgstation/tgstation/assets/59183821/3a06df32-2a74-45e4-9ac6-342bb0d18b77)

**Comment by IndieanaJones** [comment]
Gold grubs have always been immune to projectiles, no? What was stopping players from using them as shields before?

**Comment by 1393F** [comment]
> Gold grubs have always been immune to projectiles, no? What was stopping players from using them as shields before?

https://github.com/tgstation/tgstation/pull/72635
