### ISSUE TITLE
Crowbarring a holopad will buckle any mobs overtop into its contents

### ISSUE THREAD

**Issue by Dawnseer** [tgstation/tgstation#80183]
Reporting client version: 514.1589

## Issue Summary
Right. so long story short, you can become buckled INSIDE of a holopad, by standing on top of it, crowbaring it while there is no power to the equipment in the room.
![c4hc24Y](https://github.com/tgstation/tgstation/assets/126404225/4c620f86-fdd9-4cc2-a833-15e6c192f63c)
Tested it over two rounds. The first one when I first found out. Second round when I had to figure out how exactly it happened.
This also somehow manageed to completely break my characters ability to hear or see any chat from nearby. Could only hear whatever was said over radio. 
An admin had to make me a completely new body, because nothing worked, and even if they took over my body, they also had it.
You can also use tools while inside of it. So if you have a screwdriver and still got the crowbar, you can rescue yourself. Just gotta disassemble the holopad to free yourself. But if you can't break it, you're stuck. Haven't tested if I could shoot a gun from in there, but I probably could. Because I could hit my surroundings.

## Round ID:
[220122](https://scrubby.melonmesa.com/round/220122)

## Testmerges:
- [Attack chain refactoring: Broadening `tool_act` into `item_interact`, moving some item interactions to... `atom/item_interact` / `item/interact_with_atom`](https://www.github.com/tgstation/tgstation/pull/79968)
- [Organ movement refactor *Un-nullspaces your organs*](https://www.github.com/tgstation/tgstation/pull/79687)
- [the unfuckening of clothing rendering](https://www.github.com/tgstation/tgstation/pull/79784)

## Reproduction:
Make sure equipment isn't powered in the room
Stand over a holopad
Crowbar it

**Comment by optimumtact** [comment]
why in the flying fuck does crowbaring a holopad buckle you to it, who wrote this crap

**Comment by MrMelbert** [comment]
My hunch is that this is happening because you can pry open holopads (`default_pry_open`), which opens it and dumps its contents, but after you pry it open it closes, which takes any mobs in the turf as an occupant

**Comment by Dawnseer** [comment]
You can even crowbar it while others are standing over it, like I did with the admin who was so nice as to help me test it.

**Comment by Floofies** [comment]
@MrMelbert
The holopad's proc `/obj/machinery/holopad/attackby` does indeed call `default_pry_open` so I agree, as it calls `close_machine` which is responsible for setting the occupant. It looks easy to fix
