### ISSUE TITLE
Painting is broken.

### ISSUE THREAD

**Issue by celulamp** [tgstation/tgstation#80229]
Reporting client version: 514.1589

## Issue Summary
Painting is broken. Crayons and paint cans do not work the menu is pulled up but I cannot right click or left click to add any colors.

## Round ID:
[220248](https://scrubby.melonmesa.com/round/220248)

## Testmerges:
- [Reworks SDQL2 Code to not be as reliant on `usr`](https://www.github.com/tgstation/tgstation/pull/80222)

## Reproduction:

Try to paint

**Comment by Mothblocks** [comment]
Almost certainly related to React migration. Told jlsnow
