### ISSUE TITLE
Various Meteors (safe) shuttle event is not safe

### ISSUE THREAD

**Issue by SkeletalElite** [tgstation/tgstation#80227]
## Issue Summary

Various meteors (safe) is extremely destructive. Like completely wiping parts of the shuttle away destructive

## Round ID: 
[220239](https://scrubby.melonmesa.com/round/220239)

## Reproduction:

trigger the various meteors safe shuttle event, its more dangerous for larger shuttles
For example if done on monastery the sides of the shuttle will basically get annihilated, but even regulary sized shuttles can get hit during the event, here is one example I had of that happening to the meta emergency shuttle when testing 
![image](https://github.com/tgstation/tgstation/assets/26270704/edf76260-612b-4743-878e-19fd3dbcbc45)

**Comment by Jacquerel** [comment]
Relevant code:
https://github.com/tgstation/tgstation/blob/f2d9e84f36d85aaeb0b96deb3f5bc3b50fa9af3c/code/modules/shuttle/shuttle_events/_shuttle_events.dm#L96-L102

Something here isn't working.

**Comment by SkeletalElite** [comment]
Okay for regular sized shuttles I think they can only be hit by bluespace meteors which are able to teleport to the safe areas, however certain shuttles have parts that are not safe, such as the monastary which gets its sides destroyed

**Comment by timothymtorres** [comment]
Somewhat repeated but when I was testing adding the black hole admin spawnable shuttle event I noticed that massively large shuttles (Montestary) would break the boundary box.  Objects that should spawn as missed would hit.  Regular spawned objects would spawn out of the shuttle hyperspace boundary.  It was pretty janky.
