### ISSUE TITLE
Regenerative meshes wont heal burn wounds

### ISSUE THREAD

**Issue by TheWolfbringer** [tgstation/tgstation#80223]
## Issue Summary

Regenerative meshes wont heal burn wounds
## Round ID:
[220234](https://scrubby.melonmesa.com/round/220234)

## Reproduction:
Get a burn wound and attempt to heal it with regenerative mesh. Once you fully heal the burn damage from the wound, attempt to apply extra regenerative mesh. It will tell you that it can't heal it and refuse to apply or consume the mesh.

**Comment by MrMelbert** [comment]
https://github.com/tgstation/tgstation/blob/5893bc47f4e5597aa69246af029803630a16e74f/code/game/objects/items/stacks/medical.dm#L36-L41

Meshes / sutures will return with `ITEM_INTERACT_SUCCESS` regardless of any healing was done

https://github.com/tgstation/tgstation/blob/5893bc47f4e5597aa69246af029803630a16e74f/code/modules/mob/living/carbon/carbon.dm#L31-L45

As a consequence the part in carbon item interactions that handle wound tending is never reached.
