### ISSUE TITLE
Cannot interact with some features of the character creator

### ISSUE THREAD

**Issue by Draggeru** [tgstation/tgstation#80239]
## Issue Summary
You are completely unable to interact with the backpack icon, all the way down to the hairstyle icon on the character creator

## Round ID:
[220269](https://scrubby.melonmesa.com/round/220269)

## Testmerges:
#79784 #80196 #80222

## Reproduction:

open character creator, attempt to change hairstyle, cry

**Comment by san7890** [comment]
Client version? Also, was the round fully initialized?

**Comment by Draggeru** [comment]
> Client version of your BYOND? Also, was the round fully initialized?

514

And yes.

**Comment by san7890** [comment]
Im suspect of the clothing rendering refactor testmerge then

**Comment by Mothblocks** [comment]
@jlsnow301 Potential React port bug
