### ISSUE TITLE
Stamps Can't Be Moved Around On Paper

### ISSUE THREAD

**Issue by Higgin** [tgstation/tgstation#80237]
## Issue Summary

Likely issue with #80044 - you can't move a stamp around with your mouse when trying to place a stamp on a piece of paper. It sticks in the upper left corner.

## Testmerges:

The following pull requests are currently test merged:
[#79784: 'the unfuckening of clothing rendering' by Fikou at commit 5c77a7ca89](https://www.github.com/tgstation/tgstation/pull/79784)
[#80196: 'Remove delayed in MassInsert' by Mothblocks at commit 5b6f6dfdd9](https://www.github.com/tgstation/tgstation/pull/80196)
[#80222: 'Reworks SDQL2 Code to not be as reliant on `usr`' by san7890 at commit 3736b8ee96](https://www.github.com/tgstation/tgstation/pull/80222)

## Reproduction:

Try to use a stamp on a piece of paper. Expect stamp to follow mouse. It does not.

**Comment by san7890** [comment]
@jlsnow301
