### ISSUE TITLE
the ash drake can use an attack after using the triple breath attack in its second stage a little too fast

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#80236]
Reporting client version: 515.1620

## Issue Summary
the ash drake can use an attack after using the triple breath attack in its second stage a little too fast

## Round ID:
[220259](https://scrubby.melonmesa.com/round/220259)

## Testmerges:
- [the unfuckening of clothing rendering](https://www.github.com/tgstation/tgstation/pull/79784)
- [Remove delayed in MassInsert](https://www.github.com/tgstation/tgstation/pull/80196)
- [Reworks SDQL2 Code to not be as reliant on `usr`](https://www.github.com/tgstation/tgstation/pull/80222)

## Reproduction:
fight ash drake
get it down to under 50%
it does the attack where it breathes fire in a bunch of different directions, 3 times.
just before it breathes for the third time, it starts up a new attack (can be regular breath, can be the pattern again, can be lava arena swoop)

**Comment by the-orange-cow** [comment]
i've seen this as well, somewhat agrivating
