### ISSUE TITLE
Cannot Right-Click Genomes in Genetics Machine to Toggle Backwards Through Bases

### ISSUE THREAD

**Issue by Higgin** [tgstation/tgstation#80257]
## Issue Summary

![image](https://github.com/tgstation/tgstation/assets/3894717/2c0ec5be-de41-4b0f-bdf3-ec29dbd0978c)

Trying to right-click to go back through the bases does not work. Instead, it brings up a dropdown with 'Copy' and 'Select All.'

Going to guess this is another issue with #80044 

## Testmerges:

BYOND Version: 515.1620
Server revision compiled on: 
Master commit: [43d9862758d1692b8b2aef3e82fa4686bbc0b773](https://www.github.com/tgstation/tgstation/commit/43d9862758d1692b8b2aef3e82fa4686bbc0b773)
The following pull requests are currently test merged:
[#79784: 'the unfuckening of clothing rendering' by Fikou at commit 5c77a7ca89](https://www.github.com/tgstation/tgstation/pull/79784)
[#80196: 'Remove delayed in MassInsert' by Mothblocks at commit 5b6f6dfdd9](https://www.github.com/tgstation/tgstation/pull/80196)
[#80222: 'Reworks SDQL2 Code to not be as reliant on `usr`' by san7890 at commit 3736b8ee96](https://www.github.com/tgstation/tgstation/pull/80222)

Local commit: 5dd627c4deb8b2274fc40c5ff6a356f8ad2b9100
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

## Reproduction:

Open DNA Console, try to modify a gene sequence with RMB, get drop-down instead of actually toggling gene.

**Comment by Mothblocks** [comment]
Fixed by #80201, servers haven't updated
