### ISSUE TITLE
Revized NTTS Independence Lies To You

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#80251]
## Issue Summary
I _thought_ that the new NTSS from #80110 lacks a sentience balloon in its prebuild, but it's just labeled wrongly as the default giant spider bunch. So when the shuttle is about to land, ghosts are told some spiders are ready to go, when that's definitely not the case.

## Round ID:
[220198](https://scrubby.melonmesa.com/round/220198)

## Testmerges:
Don't be like me, kids, start the issue report while the round is ongoing and not 2 days later, when you won't remember the ongoing TM's.

## Reproduction:
Be dead; Have NTTS Independence be the shuttle of choice 
Cry when you missed your chance to make a sippy because you thought something else was wrong

See pictured: me thinking that the balloon was gone instead of mislabeled
![image](https://github.com/tgstation/tgstation/assets/76874615/c7d8ab28-a4c3-4356-999d-380c3f1cc73f)

**Comment by san7890** [comment]
it was there in the strongdmm screencap so idk what went wrong

**Comment by AdipemDragon** [comment]
FOUNT THE ACTUAL PROBLEM
![image](https://github.com/tgstation/tgstation/assets/76874615/5cef96e8-67d5-463c-bb0b-a34d4edeb44c)
The balloon DOES exist. It just not edited!

**Comment by san7890** [comment]
ahm
