### ISSUE TITLE
Advanced Plastic Surgery is available from roundstart

### ISSUE THREAD

**Issue by SlendyOfDaMawn** [tgstation/tgstation#80266]
## Issue Summary

Advanced Plastic Surgery is available from roundstart, to everyone.

## Round ID:

**N/A**

## Testmerges:

**N/A**

## Reproduction:

Advanced Plastic Surgery's last PR _(#78504)_ indicated that it was supposed to be a rare maint spawn or a role-restricted traitor item.

However immediately upon roundstart i am able to fully perform this surgery with no requirements?

If this is intentional, why is this not locked behind advanced surgery research at the very least? 

![image](https://github.com/tgstation/tgstation/assets/34933487/a3149344-62fc-4a07-adf3-15afccdae956)

**Comment by MrMelbert** [comment]
Also it's not capitalized, that's the real sin here

**Comment by DaydreamIQ** [comment]
It also isn't advanced plastic surgery iirc, its the regular one. Advanced lets you change based on a photo

**Comment by SlendyOfDaMawn** [comment]
The highlighted advanced plastic surgery does indeed present you with a drop down box of everyone in the photo in your offhand. Allowing you to change the patient into any of them.

Which also i figured out with guesswork because it isn't written down anywhere.

**Comment by Singul0** [comment]
![ah-eto-bleh-anime](https://github.com/tgstation/tgstation/assets/127663818/2a55cfcc-1339-4535-a8c1-183971171ad6)
