### ISSUE TITLE
Spyglass camera is fucked

### ISSUE THREAD

**Issue by Singul0** [tgstation/tgstation#80294]
## Issue Summary
![image](https://github.com/tgstation/tgstation/assets/127663818/2eda37f8-d559-443c-b338-1945ca73cf17)
Shit's fucked fr fr no cap on god man

## Round ID:
Local machine

## Testmerges:
N/A

## Reproduction:
1. spawn a spyglass kit
2. try to see through the camera with your sunglass action button
3. see its fucked

**Comment by LemonInTheDark** [comment]
BYOND issue, unclear if 1621 will resolve this

**Comment by DATA-xPUNGED** [comment]
I think this has been fixed
