### ISSUE TITLE
Morgue trays husk people

### ISSUE THREAD

**Issue by Iajret** [tgstation/tgstation#80302]
## Issue Summary
Caused by https://github.com/tgstation/tgstation/pull/80219. Placing dead bodies inside tray causes them to recieve burn damage until they are husked. Takes about an hour or so.

40 minutes mark roundstart body
![image](https://github.com/tgstation/tgstation/assets/8430839/4240b851-5f07-4138-aa62-4f52ec53e30e)

two minutes later

![image](https://github.com/tgstation/tgstation/assets/8430839/405312c0-5094-4678-9213-ac294900e1a6)

## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:

1. Place dead crewmember inside a tray during some red alert bad thing something
2. Forget about them for an hour
3. Get your flash frozen husked body from thetray

**Comment by Time-Green** [comment]
Bravo @FlufflesTheDog

**Comment by Singul0** [comment]
Better have that as a funny emag action

**Comment by the-orange-cow** [comment]
Idea:  bodybags prevent corpses from taking damage, but still allow them to get cold.

**Comment by ZephyrTFA** [comment]
I see no issues with this.
Just don't die in the first place!
