### ISSUE TITLE
the crew is routinely making enough money to buy bikes

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#80316]
Reporting client version: 514.1589

## Issue Summary
the ore selling machine thing in cargo OFTEN makes enough money to buy multiple bikes

## Round ID:
[220473](https://scrubby.melonmesa.com/round/220473)

## Testmerges:
- [Bridge Assistant Station Trait](https://www.github.com/tgstation/tgstation/pull/80279)
- [the unfuckening of clothing rendering](https://www.github.com/tgstation/tgstation/pull/79784)
- [Revert "FOV is Dead (Long Live FOV)"](https://www.github.com/tgstation/tgstation/pull/80301)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/12635164/c522aa6b-7439-48be-b2c6-5308f3a9a8c1)
pretty sure this is just the result of buying low selling high with the mats stock market thing but I'm not the one doing it every round I'm just sick of seeing everyone on a bike!

**Comment by SyncIt21** [comment]
Duplicate #79978
