### ISSUE TITLE
making someone a ai via player panel gibs them

### ISSUE THREAD

**Issue by rageguy505** [tgstation/tgstation#80314]
Reporting client version: 515.1621

## Issue Summary
they arent supposed to be gibbed

## Round ID:
[220467](https://scrubby.melonmesa.com/round/220467)

## Testmerges:
- [Bridge Assistant Station Trait](https://www.github.com/tgstation/tgstation/pull/80279)
- [Revert "FOV is Dead (Long Live FOV)"](https://www.github.com/tgstation/tgstation/pull/80301)

## Reproduction:
right click a human, go to player panel and select 'make ai'. they get gibbed
![image](https://github.com/tgstation/tgstation/assets/54517726/b7ab53ff-8d99-48cc-b1e7-30df5eccaa38)

**Comment by rageguy505** [comment]
oh yeah i imagine its #79687 causing it

**Comment by Time-Green** [comment]
> oh yeah i imagine its #79687 causing it

100000000%. AI transform proc is probably snowflake and manually stripping someone, it needs to use drop_everything

**Comment by Time-Green** [comment]
https://github.com/tgstation/tgstation/blob/32fb42d19e0c763f7e5e3dafb9844d0f05e86630/code/modules/mob/transform_procs.dm#L130-L131

Just removing this should fix it (I have no idea why it does this, it’s completely psychotic)

**Comment by Time-Green** [comment]
Bonus points for replacing this with drop_everything() using the appropriate oarams
https://github.com/tgstation/tgstation/blob/32fb42d19e0c763f7e5e3dafb9844d0f05e86630/code/modules/mob/transform_procs.dm#L176-L180
