### ISSUE TITLE
Admin Create Command Report UI "Submit Report" button broke

### ISSUE THREAD

**Issue by Isratosh** [tgstation/tgstation#80343]
Reporting client version: 514.1589

## Issue Summary
Using create-command-report and clicking "Submit Report" makes the button just disappear instead of doing anything. It returns when the interface is clicked anywhere again.

## Round ID:
[220512](https://scrubby.melonmesa.com/round/220512)

## Testmerges:
- [Bridge Assistant Station Trait](https://www.github.com/tgstation/tgstation/pull/80279)
- [the unfuckening of clothing rendering](https://www.github.com/tgstation/tgstation/pull/79784)

## Reproduction:
1. create-command-report
2. insert text
3. click "Submit Report"
4. the button fucks off

![image](https://github.com/tgstation/tgstation/assets/13789168/5a0b7ba1-ddc2-4b83-8680-c138ba4e1429)

**Comment by san7890** [comment]
@jlsnow301

**Comment by Isratosh** [comment]
same thing as https://github.com/tgstation/tgstation/issues/80331
