### ISSUE TITLE
Revs can flash through beer goggles

### ISSUE THREAD

**Issue by AyamePup** [tgstation/tgstation#80342]
## Issue Summary

A revhead approached me from behind and flashed me. I was a bartender at the time, and wearing beer goggles. Im pretty sure being able to revflash from the person facing any direction is intentional, but not through sunglasses. I dont know if this is just problem with the beer goggles or with all sunglasses.

## Round ID:

[220504](https://scrubby.melonmesa.com/round/220504)

## Reproduction:

Well I guess try to rev flash (or normal flash maybe?) someone with beer goggles on.

**Comment by MrMelbert** [comment]
Hmm if this is true the unit test might be broken. Either that or it's a test merge issue. Maybe #79784 ?

https://github.com/tgstation/tgstation/blob/8615d8b9ce2d996421849d024a44b52a50c8fd8f/code/modules/unit_tests/antag_conversion.dm#L27-L34

**Comment by MrMelbert** [comment]
Testing on master, 
![image](https://github.com/tgstation/tgstation/assets/51863163/7085ab55-01f6-4345-9871-c5f5c47784bb)
![image](https://github.com/tgstation/tgstation/assets/51863163/44daf22e-5d88-41d8-b7a8-406ebc1a4545)

**Comment by MrMelbert** [comment]
@AyamePup Were you playing a ch arcer with Photophobia or a moth? If so, you had flash vulnerable eyes which glasses alone could not protect. If not, then ???

**Comment by AyamePup** [comment]
@MrMelbert 

AH. It was photophobia. God ive had that quirk since it came out and I guess no ones tried to flash me when I was wearing sunglasses since?? I had no idea it made flashes go through base protection, but that makes sense. Hey at least it isnt a bug. Thanks mr melblem.
