### ISSUE TITLE
Some potential? issues with Birdshot science

### ISSUE THREAD

**Issue by plutori** [tgstation/tgstation#80350]
Reporting client version: 515.1621

## Issue Summary - Noticed several issues with Birdshot Science. Have been informed several times this is where to provide such feedback, so here we go:

1. Xenobiology completely lacks any syringes - this is necessary for extracting blood from monkeys
2. Xenobiology has a locker for Cytology equipment while having a completely separate cytology lab on the other side of the department. Remove the locker but leave a science bag spawn in xenobiology for picking up monkey cubes and slime cores easily.
3. Xenobiology and Cytology should both have a box of beakers that spawn inside the department. Xenobiology for holding blood and plasma, and Cytology for their 999999 different reagents they use.

## Round ID:
[220524](https://scrubby.melonmesa.com/round/220524)

**Comment by LemonInTheDark** [comment]
We do not take requests via the issue tracker. There's a line between intentional scarcity and "oh I forgot that", so I'll leave this up for zy, but the way you're framing this is not right

**Comment by plutori** [comment]
> We do not take requests via the issue tracker. There's a line between intentional scarcity and "oh I forgot that", so I'll leave this up for zy, but the way you're framing this is not right

Oh my bad. In the past all the maintainers kept saying "play on the map" and "give feedback for what you think needs changing", so I thought this was the correct place to do so.

**Comment by LemonInTheDark** [comment]
I've never said that IMO if you don't like it that's a skill issue.
That said uh, feedback generally goes here https://tgstation13.org/phpBB/viewforum.php?f=10 or in tgcord talking to the mapper (if you are a dick I will throw you into the sun)

**Comment by LemonInTheDark** [comment]
Sall good either way it's not all that clear
