### ISSUE TITLE
Holodeck monkeys gib on despawn

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#80369]
Reporting client version: 514.1589

## Round ID:
[220557](https://scrubby.melonmesa.com/round/220557)

## Reproduction:

Spawn in the holodeck beach scene.
All the monkeys spawn in dead with zero organs. (this has already been reported in #79184 though maybe the cause has changed over time (?))

Despawn the holodeck scene.
All the monkeys gib (free limbs!) and ADMIN LOG: *no key*/(monkey (912) was gibbed after their chest teleport to Recreational Holodeck (144,158,4)

**Comment by Fikou** [comment]
@san7890 why u make a holodeck spawned carbon bruh
