### ISSUE TITLE
Cleanbot Foam does nothing and is missing the acid spray

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#80363]
Reporting client version: 514.1589

## Round ID:
[220548](https://scrubby.melonmesa.com/round/220548)

## Reproduction:
Spawn in as a sentient cleanbot
Foam up your nearest bloodstain
Nothing happens
Try to clean up any trash you see
You mop it instead

**Comment by Ben10Omintrix** [comment]
the old cleanbot's foam didnt clean anything, it was just a fun thing for emagged and sentient cleanbots to have from what i can see so i kept it as is. ive tried reproducing the acid spraying bug but it seems they can acid spray trash type objects just fine

**Comment by DaydreamIQ** [comment]
Odd, but fair enough then. I'm not sure what was stopping me from aciding anything but I'll make a new report if it comes up again

**Comment by Ben10Omintrix** [comment]
aciding is only limited to trash objects, mice and humans. but maybe we can expand that to include all items ?
