### ISSUE TITLE
PAI host scan does not work

### ISSUE THREAD

**Issue by NoodleNoms** [tgstation/tgstation#80370]
Reporting client version: 515.1620

## Issue Summary

PAI host scan does not work it does not bring up scan results no matter what button you press to scan

## Round ID:
[220556](https://scrubby.melonmesa.com/round/220556)

## Reproduction:

PAI host scan installed and click attempt to scan by any means

**Comment by jlsnow301** [comment]
@MrMelbert this may be related to #79968

**Comment by MrMelbert** [comment]
![image](https://github.com/tgstation/tgstation/assets/51863163/494a16a6-c9d7-431e-b80e-28c00745f938)
Why did they call attack directly >:(((
