### ISSUE TITLE
New player interview responses not saving

### ISSUE THREAD

**Issue by Isratosh** [tgstation/tgstation#80378]
Reporting client version: 514.1589

## Issue Summary
For the last few days, new players connecting to Manuel have been sending in interviews with all the answers as "No response." Several of them have been asked over admin PM and they claim to have filled out the answers, including one in the round ID below. We receive probably dozens of interviews a day and I haven't seen an answer saved for at least 2 or 3 days. I've handled a couple of newcomers that have responded to my PMs promptly and explained that their answers didn't save.

## Round ID:
[220565](https://scrubby.melonmesa.com/round/220565)

## Reproduction:
I haven't done this myself but,
1. connect to a server with the new player interview system enabled as a new player (i think it's less than 1 hour logged?)
2. fill out the interview and hit "submit"
3. have an admin deny it because its empty
4. go to sybil instead

**Comment by lessthnthree** [comment]
Likely after https://github.com/tgstation/tgstation/pull/80276

**Comment by Isratosh** [comment]
@jlsnow301
