### ISSUE TITLE
Slaughter/Laughter demons don't drop the corpses of the people they've eaten when they die.

### ISSUE THREAD

**Issue by excalisword** [tgstation/tgstation#80383]
Reporting client version: 514.1589

## Issue Summary

When a laughter demon or slaughter demon dies, instead of reviving them in the case of the laughter demon or just dropping their corpses in the case of the slaughter demon, the demon won't drop any corpses at all.

## Round ID:
[220585](https://scrubby.melonmesa.com/round/220585)

## Reproduction:

Kill a slaughter or laughter demon that has eaten humanoids.

**Comment by MrMelbert** [comment]
Slaughter demons don't drop corpses, so that part is WAD, laughter demons though definitely sounds bugged.

**Comment by MrMelbert** [comment]
Well that's probably why

![image](https://github.com/tgstation/tgstation/assets/51863163/c6e580fb-c016-40ab-8bbe-732512bd6699)
