### ISSUE TITLE
Trying to use global circuit variables bluescreens TGUI

### ISSUE THREAD

**Issue by Exester509** [tgstation/tgstation#80387]
## Issue Summary

If you set and call a global variable in an integrated circuit, it will immediately bluescreen. In some instances, it won't even let you define the var.

## Round ID:

N/A (found on a synced local)

## Reproduction:

First, get any circuit shell and add an integrated circuit to it. Access it with a multitool and try to set a global variable.
In some cases, I've had it bluescreen right when I tried to define the variable, else, it will bluescreen when you try to write on, or read from that variable.

**Comment by jlsnow301** [comment]
Might be difficult to track this after #80340 was merged

**Comment by jlsnow301** [comment]
Are you able to repro this with a screenshot of the bluescreen?

**Comment by Exester509** [comment]
> Are you able to repro this with a screenshot of the bluescreen?

Sure thing
![BSOD](https://github.com/tgstation/tgstation/assets/62149527/8f0d2892-1285-4e18-b8cd-db5ff16c3e70)

This is what happens when you try to define a global variable.
