### ISSUE TITLE
Getting your leg blown off by an explosion that destroys your wheelchair can heal paraplegia

### ISSUE THREAD

**Issue by dalmationer** [tgstation/tgstation#80396]
## Issue Summary

https://youtu.be/L27PXZb8WtA

Somehow, getting a leg blown off in this round cured my paraplegia, even after the leg was reattached. Walking speed appears to be set to the one legged walking speed.

## Reproduction:

Be paraplegic
have a leg cut off (may only work with explosions?)
regain control of your legs.
emote *walks about.

EDIT:

OKAY so in round ID: 224324 I worked out finally how to reproduce this. (this glitch has been my white whale for some time.)

It appears that it only happens in the following circumstance:

    You are on a wheelchair.
    You are caught in an explosion which destroys the wheelchair.
    at least one leg is blown off by the explosion.

This lets you walk about slowly. Crucially, though it is affected by movement effects such as knockdowns due to slipping, slowdown from having an open duffelbag, and speed-up from meth, you can still walk upright even if BOTH legs are blown off.

**Comment by dalmationer** [comment]
I've been trying to replicate this and i have NO idea what caused it.

**Comment by Isratosh** [comment]
examining the mob still showed 2 "leg is limp and lifeless"

**Comment by Admiral-Gigaton** [comment]
a miracle from Rat'var, before his power truely faded

**Comment by dalmationer** [comment]
OKAY so in  round ID: 224324 I worked out finally how to reproduce this. (this glitch has been my white whale for some time.)

It appears that it only happens in the following circumstance:

1. You are on a wheelchair.
2. You are caught in an explosion which destroys the wheelchair.
3. at least one leg is blown off by the explosion.

This lets you walk about slowly. Crucially, though it is affected by movement effects such as knockdowns due to slipping, slowdown from having an open duffelbag, and speed-up from meth, you can still walk upright even if BOTH legs are blown off.

Usually, an explosion strong enough to blow off a leg will also crit you, but if you get healed up, it can be quite strong-- in a malf round recently, this glitch occurred to me as paraplegic captain, after I was caught in a cyborg selfdestruct explosion. It wasn't the sole reason we killed the AI, but it was a significant help.

**Comment by dalmationer** [comment]
method that reliably appears to reproduce this glitch:

put myself in a wheelchair, give myself paraplegic quirk
bash one leg with a blunt object enough that the limb's health is very low
bash the wheelchair with a blunt object till it's falling apart
then throw an IED on the tile next to me
