### ISSUE TITLE
Reaction chamber won't dispense buffer into a full beaker

### ISSUE THREAD

**Issue by lessthnthree** [tgstation/tgstation#80409]
## Issue Summary

Putting a full beaker in the reaction chamber, the dispense buffer buttons don't work.

https://github.com/tgstation/tgstation/assets/83487515/a8787872-a78f-4861-aa59-59cdcd0cfb60

## Reproduction:

Put a beaker full of reagent into the reaction chamber, attempt to change the pH with the buffer buttons

**Comment by ZephyrTFA** [comment]
This is inherent to the way buffers work.
There needs to be space for the buffer to actually get added, and when added it modifies the ph of the reagents and then deletes itself out.

**Comment by Toparai** [comment]
> This is inherent to the way buffers work. There needs to be space for the buffer to actually get added, and when added it modifies the ph of the reagents and then deletes itself out.

i distinctly remember that up to like 2 months ago you could add buffer into a full beaker, or was that working incorrectly all this time?

**Comment by Toparai** [comment]
> This is inherent to the way buffers work. There needs to be space for the buffer to actually get added, and when added it modifies the ph of the reagents and then deletes itself out.

@ZephyrTFA i distinctly remember that up to like 2 months ago you could add buffer into a full beaker, or was that working incorrectly all this time?

**Comment by lessthnthree** [comment]
> > This is inherent to the way buffers work. There needs to be space for the buffer to actually get added, and when added it modifies the ph of the reagents and then deletes itself out.
> 
> @ZephyrTFA i distinctly remember that up to like 2 months ago you could add buffer into a full beaker, or was that working incorrectly all this time?

You could, and have been able to for years. A PR changed that, but perhaps that was considered a fix. Makes it a pain in the ass though when your chem dispenser presets revolve around giving you a full beaker.
