### ISSUE TITLE
Polymorphing someone into a drone gibs them and doesn't put their mind in the drone

### ISSUE THREAD

**Issue by Y0SH1M4S73R** [tgstation/tgstation#80436]
## Issue Summary

Exactly what the title says. Two people got hard-rred by this bug on the listed round. Though to be honest, it was a friendly wizard trying to be friendly so I guess they deserved to deal with any confusion this may have caused.

## Round ID:

[220694](https://scrubby.melonmesa.com/round/220694)

## Testmerges:

#80362

## Reproduction:

Polymorph someone with a staff/wand until they turn into a drone.

**Comment by Admiral-Gigaton** [comment]
happened to me recently (yay first wiz round! i almost had a stroke seeing "YOU ARE THE WIZARD.") i was polymorphing people and a guy fucking exploded into gibs, i didnt see a drone (probably covered in lizard giblets) but polymorph has been doing some funky shit. also, can they still turn people into lesser ash drakes?

**Comment by Time-Green** [comment]
Fixed in #80527
