### ISSUE TITLE
Eslint is set to the wrong react version

### ISSUE THREAD

**Issue by jlsnow301** [tgstation/tgstation#80432]
## Issue Summary
We're using React 18.2 but eslint was set for 16.10 compat. Changing this will expose some errors like the use of ReactDOM.render.

## Round ID:
N/A

## Reproduction:
- Change the version in `eslintrc.yml`
- Run tgui:lint

**Comment by SyncIt21** [comment]
Yup, it is slightly annoying. Just slightly though
![Screenshot (369)](https://github.com/tgstation/tgstation/assets/110812394/274fcc6d-bbd4-4359-afdf-d6f24aa2d919)

**Comment by jlsnow301** [comment]
> Yup, it is slightly annoying. Just slightly though

This error in particular will be fixed by #80454. There are actually more if you set the eslint version to 18.2 :)

**Comment by SyncIt21** [comment]
Might be unrelated but you have any idea why vs code is complaining about this
![Screenshot (372)](https://github.com/tgstation/tgstation/assets/110812394/4b1e0d25-c0fc-4d14-9eb9-0d583b948817)
It compiles and works fine but sill. 

Changing the path from `common/react` to `../../common/react` seems to fix the probelm but i have no clue about
`import { useState } from 'react'`

**Comment by jlsnow301** [comment]
you dont need the extension, make sure your workspace is set to the right TS version
![image](https://github.com/tgstation/tgstation/assets/42397676/e37539c8-6d02-4957-ae36-50f347ac757c)
and you've installed everything via `ctrl shift B`

**Comment by SyncIt21** [comment]
Yup that fixes it. The reason I installed the extension is to fix [this](https://github.com/microsoft/vscode/issues/174209) issue  and the last comment suggested this solution(which works for me)

Any ideas why the service crashes multiple times randomly and how to fix?

**Comment by jlsnow301** [comment]
> Looks like I have to find another solution for that

That is also most likely caused by not having the workspace version installed and selected

Let me know if you're still getting that message
