### ISSUE TITLE
You can hold defib paddles while dead

### ISSUE THREAD

**Issue by SconesC** [tgstation/tgstation#8044]
![defibmem](https://cloud.githubusercontent.com/assets/9714964/6420858/cffbd216-be7e-11e4-88bb-51818025c1da.png)

Not sure how to reproduce

**Comment by phil235** [comment]
Easy to reproduce, just get the paddles in your hand (wielded or not) and suicide/ghost/get killed.

**Comment by paprka** [comment]
This is intentional so you can defibrillate yourself

I'm pretty sure this is due to the nodrop of the paddles, they're very hacky and this should also happen with the firefighter nozzle.

**Comment by kingofkosmos** [comment]
Happens also with the firefighter nozzle.

**Comment by phil235** [comment]
The whole issues stems from the fact that swapping an item from one hand to another actually drops it on the found and picks it up. With NODROP, we have the current problem. Without NODROP swapping the paddles to your other hand puts the paddles back in the defib but the code then moves the paddles in your other hand so the paddles are both in the defib and in your hand.

**Comment by SconesC** [comment]
i opened this over a year ago jesus christ

**Comment by tedward1337** [comment]
Snowflake code, etc. Is there a possible work around for this?

**Comment by Qbopper** [comment]
![ded](http://i.imgur.com/6SK6d7U.png)

Still reproducible, despite the unique sound/message for defib suicides
