### ISSUE TITLE
Genetics DNA Console UI broken

### ISSUE THREAD

**Issue by Isratosh** [tgstation/tgstation#80455]
Reporting client version: 514.1589

## Issue Summary
![image](https://github.com/tgstation/tgstation/assets/13789168/df1af421-940c-4e12-8b7d-457b8773098b)

Clicking these DNA icons does nothing. No sequences can be selected for manipulation.

## Round ID:
[220757](https://scrubby.melonmesa.com/round/220757)

## Testmerges:
- [Updates eslint + sorts imports](https://www.github.com/tgstation/tgstation/pull/80430)

## Reproduction:
1. put a monkey or human into the DNA scanner
2. open the computer's UI and click on the DNA icon
3. nothing happens

**Comment by Mothblocks** [comment]
Fixed by https://github.com/tgstation/tgstation/pull/80441
