### ISSUE TITLE
Buildmode Copy tool unable to select turfs for copying despite the description implying so.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#80457]
Reporting client version: 515.1621

## Issue Summary

Attempting to use the copy tool function of buildmode to copy a turf, be it a wall or floor, doesn't seem to actually carry out the copying as stated in the help description of the tool. It still works on objects and mobs, though.

![dreamseeker_uwRUzq5Yik](https://github.com/tgstation/tgstation/assets/33107541/1a484e0e-746b-45cc-88d4-c9313d4c0586)

## Round ID:
[220762](https://scrubby.melonmesa.com/round/220762)

## Testmerges:
- [Updates eslint + sorts imports](https://www.github.com/tgstation/tgstation/pull/80430)

## Reproduction:

1. Enter buildmode as an admin.
2. Select the Copy tool.
3. Right click a wall or floor turf. Receive no copy confirmation in the chatbox, and left click doesn't produce any copies.

**Comment by Isratosh** [comment]
Not a bug or a typo, the copy mode does not work on turfs intentionally. The second line directs you to right click on an obj/mob, not a turf. The first line is just indicating where you can left click to spawn a copy of your selection, you can of course click a turf to spawn something there.
https://github.com/tgstation/tgstation/blob/8b7576b90a92ed30dfd03634eece52b07d39ef82/code/modules/buildmode/submodes/copy.dm#L23-L26
You can use the advanced mode to copy a turf type for spawning, but variable edits won't be preserved.

**Comment by Potato-Masher** [comment]
I am bad at reading.

Very tragic news as preserving the variable edits from turfs was the entire intent behind me using copy, despite it's current broken state regarding copying variable edited items (#72636).

Is there something preventing copy from doing turfs? The code comment in there doesn't really elaborate.
