### ISSUE TITLE
Auto-observing no longer displays target hud

### ISSUE THREAD

**Issue by FlufflesTheDog** [tgstation/tgstation#80460]
Reporting client version: 515.1621

## Issue Summary
As a ghost, "observing" someone will lock your camera to them, but will no longer display the hud of whoever you're observing. Likely caused by #80407

## Round ID:
[220767](https://scrubby.melonmesa.com/round/220767)

## Testmerges:
- [Updates eslint + sorts imports](https://www.github.com/tgstation/tgstation/pull/80430)

## Reproduction:
Be a ghost
Orbit + toggle auto observe, or use the observe verb
Select a mob
Hud doesn't change, try moving your ghost to confirm you're "observing"

**Comment by MrMelbert** [comment]
Yes, caused by #80407 because `src` is **always** `usr` here @Diamond-74 
Maybe they wanted `mob_eye != src`

**Comment by Diamond-74** [comment]
I probably should've tested it with another person before thinking it worked fine

**Comment by Iajret** [comment]
> I probably should've tested it with another person before thinking it worked fine

use byond guest account for such things. This way it will allow you to have separate dreamseekers without the need of creating another acc or finding another person to test things.
