### ISSUE TITLE
Plasmamen No Longer Decay (in their suits)

### ISSUE THREAD

**Issue by RikuTheKiller** [tgstation/tgstation#80467]
## Issue Summary

#80219 has (likely) caused plasmamen to no longer experience organ decay.

Their regular body temperature is slightly below freezing, so that's why.

This is kind of stupid considering plasmamen are supposed to be difficult to revive by design.

Perhaps decrease the threshold to -5 or so? It's a little unrealistic, but gameplay over realism.

## Reproduction:

Die as a plasmaman.

Observe a notable lack of organ decay.

**Comment by SethLafuente** [comment]
It seems plasmaman as of right now do decay.

![image](https://github.com/tgstation/tgstation/assets/84478872/7bc9f75c-44df-4902-8594-faec71909208)

**Comment by RikuTheKiller** [comment]
Seth if you'd bother to read the issue report before closing it, that'd be nice.
The issue body isn't there for show, it's meant to be read, too.

Either way, the issue report clearly states this is due to body temperature.
The image you showed has the plasmaman on fire. Last I checked, 1000+ degrees is above freezing.

**Comment by moocowswag** [comment]
In other words, test by spawning another plasmaman in and giving them an enviro suit then killing them.

**Comment by necromanceranne** [comment]
I agree, the issue remains. Probably make it so that plasmamen organs decay at lower temperatures than nornal organs or something. Seems like the best solution.

**Comment by SethLafuente** [comment]
Alright after doing some testing I have concluded two things, first plasmamen in fact do decay even inside their suit as shown below;
![image](https://github.com/tgstation/tgstation/assets/84478872/e6ed7a0c-57f2-4221-a008-a2873f348112)

I also conducted a test of one plasmamen dead in suit with their plasma tank and another without their plasma tank the first one I posted being the one with the second one below the one without;
![image](https://github.com/tgstation/tgstation/assets/84478872/ae4e7ed0-21e2-4a90-9a13-cc83638b0a53)

It seems plasmamen without plasma tanks dead have bigger organ decay with the ones without.

The process of organ decay is extremely slow taking more than an hour to see notable amounts of decay and still being functional non the less they do suffer from organ decay so I think this issue should be closed, I already closed it and Im not closing it again to be reopened and look like a fool.

**Comment by necromanceranne** [comment]
No, it seems you've tested the issue. It's a matter of 'do they never decay' not 'do they decay at the same rate as humans'. If that is an issue, it should be separate.
