### ISSUE TITLE
full face mask makes me nonbinary, sometimes

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#80461]
Reporting client version: 514.1589

## Issue Summary
wearing a mime mask and eva helmet changes your pronouns on examine to they/them

## Round ID:
[220767](https://scrubby.melonmesa.com/round/220767)

## Testmerges:
- [Updates eslint + sorts imports](https://www.github.com/tgstation/tgstation/pull/80430)

## Reproduction:
have she her pronouns
wear both mime and eva mask
(optional, remove your id and put it back on maybe? I was fucking about at the hop when this happened)
they them pronouns until masks are removed

not sure on the EXACT repro steps but it's something like this

**Comment by Fikou** [comment]
yeah they cant tell your identity

**Comment by newfren** [comment]
they should be able to, I'm wearing my id

**Comment by JohnFulpWillard** [comment]
Your pronouns don’t depend on the ID you wear it depends on whether you’re visible

**Comment by MrMelbert** [comment]
https://github.com/tgstation/tgstation/blob/fbbdb2dae2b92ca4bbcbf553d6ccb0a922031508/code/__HELPERS/pronouns.dm#L250-L256

**Comment by Mothblocks** [comment]
nanotrasen isnt progressive enough
