### ISSUE TITLE
Changing your name in Character Preferences is agonizing

### ISSUE THREAD

**Issue by PapaMichae1** [tgstation/tgstation#80476]
## Issue Summary

Trying to type in the character preferences boxes to change a name has an annoying bug.
Click the text box to enter edit mode
Every letter typed immediately kicks you back out of edit mode, so basically, you have to click back into it for each character you type. And the "default state" of clicking into edit mode is to have the whole name highlighted, in which case trying to type anything kicks you back out again with no effect.

## Round ID: 
220790

## Testmerges:
[#80304: 'Increase TGUI connection lost threshold' by lessthnthree at commit 2e01d39a34](https://www.github.com/tgstation/tgstation/pull/80304)

## Reproduction:
Open Character Preferences, try to change a character's name (or change any of the alternate names, e.g. clown name, mime name, etc)
(Running Byond version 515.1621, as you've told me to)

**Comment by SyncIt21** [comment]
Fixed by #80490
