### ISSUE TITLE
Cant enter a new name in character setup

### ISSUE THREAD

**Issue by Lufferly** [tgstation/tgstation#80481]
## Issue Summary

Trying to enter a new name in the character editor just kicks you out of the box, you can sometimes delete a character or put one in but then it stops. This appears to happen in all the name boxes.

## Round ID:  [220810](https://scrubby.melonmesa.com/round/220810)
Tested locally as well 

## Testmerges:
#80304 
#80368

## Reproduction:

Open Character Setup
Click on your name or the alternate names
Try to type a new name
See that it kicks you out of the box

**Comment by newfren** [comment]
this also effects naming diseases, and can be worked around with copy and paste

**Comment by Dorsisdwarf** [comment]
Same issue as #80486 , but that report has pictures
