### ISSUE TITLE
Naming characters is broken.

### ISSUE THREAD

**Issue by lilahnovi** [tgstation/tgstation#80486]
Reporting client version: 515.1621

## Issue Summary

In character set up (someone claimed this was only on Sybil), when trying to change the name of a character, it doesn't allow you. You can delete one letter at a time before the box resets, until you get to the last two letter, and it won't let you delete anything else.

I cannot enter any letters or choose where my typing cursor goes. This is the same situation when I click the triple dots next to the name entry and try that way.

## Round ID:
[220834](https://scrubby.melonmesa.com/round/220834)

## Testmerges:
- [Refactors TS in Box component](https://www.github.com/tgstation/tgstation/pull/80368)
- [(Testmerge Ready) New Antagonist: Tiger Cooperative Fanatic](https://www.github.com/tgstation/tgstation/pull/80313)
- [[TM ONLY] Remove 'natural' beheading](https://www.github.com/tgstation/tgstation/pull/80439)
- [Optimizes the pipeline of basic mobs](https://www.github.com/tgstation/tgstation/pull/79498)

## Reproduction:

I'm renaming Lilah!:
![image](https://github.com/tgstation/tgstation/assets/124811534/e03955d7-bfb0-4227-8271-b6523f77b999)

After clicking backspace once:
![image](https://github.com/tgstation/tgstation/assets/124811534/82190869-68c9-47ea-a5cd-2be7d6602d90)

On another character, I deleted the name down to the last two letters:
![image](https://github.com/tgstation/tgstation/assets/124811534/033f688d-239e-480c-a69b-e32eece92fa8)

From there, I can no longer add any letters or delete any letters. It is permanently stuck as the two letters. As long as I don't go down to the last two letters, I can add letters one by one, but that's it.

**Comment by gorillion** [comment]
i can confirm this also is the case on Manuel, so its likely agnostic of which server the user's on.
