### ISSUE TITLE
Portable Song Tuning doesn't work

### ISSUE THREAD

**Issue by vertolodka** [tgstation/tgstation#80497]
Reporting client version: 514.1589

## Issue Summary
Portable Song Tuning from Festival God sect doesn't work

## Round ID:
[220891](https://scrubby.melonmesa.com/round/220891)

## Testmerges:
- [[TM ONLY] Remove 'natural' beheading](https://www.github.com/tgstation/tgstation/pull/80439)
- [Epic RPD Update: Multiple Pipe Layers With 1 Click](https://www.github.com/tgstation/tgstation/pull/80073)

## Reproduction:
1. Get synthesizer or violin from Cogitandi Fidis rite(didn't check other instruments).
2. Place them on top of the altar and use Portable Song Tuning.
3. Try to make any rite by using bible on the synthesizer/violin.
4. Get "This cannot perform that kind of rite." error.

**Comment by dalmationer** [comment]
I've reproduced this in game.

**Comment by DATA-xPUNGED** [comment]
Even though this is the older issue, I'm closing this as #83997 contains more information
