### ISSUE TITLE
515 - Lighting and visibility bugs - can see thru walls, not certain open tiles

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#80504]
Reporting client version: 515.1622

## Issue Summary
![dreamseeker_IPSEpWRRSx](https://github.com/tgstation/tgstation/assets/37246588/0e5e3327-299b-45eb-8903-e909e65b89a5)
fundamentally this is what it is. I notice tiles just north of a wall had a tendency to be black, and I could see through certain tiles pretty much anywhere that wasnt to the south of me.

for more context, that first row of black tiles just south of me were open space, two tiles south of me there were closed turfs

## Round ID:
[220917](https://scrubby.melonmesa.com/round/220917)

## Testmerges:
- [Optimizes the pipeline of basic mobs](https://www.github.com/tgstation/tgstation/pull/79498)
- [[TM ONLY] Remove 'natural' beheading](https://www.github.com/tgstation/tgstation/pull/80439)
- [(Testmerge Ready) New Antagonist: Tiger Cooperative Fanatic](https://www.github.com/tgstation/tgstation/pull/80313)

**Comment by wesoda25** [comment]
Downgrading to 514 fixed the issue

**Comment by LemonInTheDark** [comment]
![image](https://github.com/tgstation/tgstation/assets/58055496/1d46fd99-186a-453c-81ae-9f0442e00651)
Byond issue, resolved. use 1623
