### ISSUE TITLE
Circuits UI for adding new components is bugged

### ISSUE THREAD

**Issue by MoffNyan** [tgstation/tgstation#80506]
Reporting client version: 514.1589

## Issue Summary

The UI to add new components within Integrated Circuit boards is broken.

## Round ID:
[220924](https://scrubby.melonmesa.com/round/220924)

## Testmerges:
- [Increase TGUI connection lost threshold](https://www.github.com/tgstation/tgstation/pull/80304)

## Reproduction:

Take an Integrated Circuit, link it to the Component Printer, use it in hand to display the normal circuits UI
At the very top next to the gear, press the + which normally should open up a UI for adding new components

NtOS bluescreen of sad

If you print out components from the Component Printer and add it to the Integrated Circuit it works just fine, Variables do as well. It's just a little harder when you aren't 100% sure what you're doing or experimenting.

**Comment by SyncIt21** [comment]
Duplicate #80491

**Comment by Sealed101** [comment]
^
