### ISSUE TITLE
Autolathe and crafting UI is bugged

### ISSUE THREAD

**Issue by TheWolfbringer** [tgstation/tgstation#80516]
## Issue Summary
Autolathe and the crafting searchbar is broken, and the autolathe fails to display anything searched up. 

## Round ID:
[220955](https://scrubby.melonmesa.com/round/220955)

## Reproduction:
Attempt to use the autolathe or the crafting UI's searchbar, the autolathe one refuses to work and the crafting one requires you to move the scroll bar in order for it to function.

**Comment by Thunder12345** [comment]
Did you try hitting enter after typing? I was having to do that earlier today with other tgui things

**Comment by TheWolfbringer** [comment]
> Did you try hitting enter after typing? I was having to do that earlier today with other tgui things

Don't think I tried that, I'm used to it auto updating when you type it in.

**Comment by Thunder12345** [comment]
Yeah that’s what stopped working them

**Comment by TheWolfbringer** [comment]
> Yeah that’s what stopped working then

works with crafting and the autolathe, but for some reason the "all designs" part of the autolathe is completely empty

**Comment by TheWolfbringer** [comment]
> Yeah that’s what stopped working then

also, pressing enter doesn't  show the items it should show in a normal search for the autolathe and protolathe UI
for example, typing "serv" for a servo will not work

**Comment by jlsnow301** [comment]
Confused about the crafting menu bug, can you give me some steps to replicate?

**Comment by TheWolfbringer** [comment]
> Confused about the crafting menu bug, can you give me some steps to replicate?

if you type something into the crafting menu, it won't auto update and you need to press enter instead
