### ISSUE TITLE
Ghost polls that refresh on their own spam chat if you don't hit ignore

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#80517]
Reporting client version: 515.1623

## Round ID:
[220953](https://scrubby.melonmesa.com/round/220953)

## Testmerges:
- [Increase TGUI connection lost threshold](https://www.github.com/tgstation/tgstation/pull/80304)
- [Tones down cyborg lover to cyborg fan](https://www.github.com/tgstation/tgstation/pull/80508)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/62606051/16364f7b-e722-49ab-8083-e334768846aa)
Obviously you can just hit ignore but this fills up your chat pretty fast if nobody takes it

**Comment by Mothblocks** [comment]
@13spacemen
