### ISSUE TITLE
Viewing cameras as a silicon/cyborg fails to display the camera's view.

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#80524]
Reporting client version: 515.1623

## Issue Summary
(SIDE NOTE: Was on tramstation, if this is somehow relevant.)
When using a security camera console as a cyborg, the image of what the camera sees seems to fail to show. Instead, showing either a blank, blackened screen. Or, just a single tile.
![image](https://github.com/tgstation/tgstation/assets/85206687/8fecaa9c-63c3-4139-a87b-51ab73525d58)

## Round ID:
[220973](https://scrubby.melonmesa.com/round/220973)

## Testmerges:
- [Save json savefiles to disk in pretty print form](https://www.github.com/tgstation/tgstation/pull/80512)
- [(Testmerge Ready) New Antagonist: Tiger Cooperative Fanatic](https://www.github.com/tgstation/tgstation/pull/80313)
- [[TM ONLY] Remove 'natural' beheading](https://www.github.com/tgstation/tgstation/pull/80439)
- [Tones down cyborg lover to cyborg fan](https://www.github.com/tgstation/tgstation/pull/80508)

## Reproduction:
1. Become silicon. (As a cyborg, specifically.)
2. Find a security camera console.
3. Go to any camera you want.
4. Lack of picture in the UI.

**Comment by SyncIt21** [comment]
Duplicate #79954?

Dies the camera work when you're human though?

**Comment by Derpguy3** [comment]
> Duplicate #79954?
> 
> Does the camera work when you're human though?

I had somebody else check the console too, during that round. They were human and they said it worked fine for them.

**Comment by GregariousJB** [comment]
I'm fairly certain this can be closed as a duplicate.

This issue reminded me of when I couldn't see cameras as a borg a few days ago, but I assumed it was an in-game power issue or something. I set out to test this myself after compiling a local server. Cameras don't work in Byond beta 1623, but they do work from v1609-1614, and then they stop working in v1615.

**Comment by JohnFulpWillard** [comment]
> I had somebody else check the console too, during that round. They were human and they said it worked fine for them.

It depends what their BYOND version was. Reason explained in https://github.com/tgstation/tgstation/issues/79954
