### ISSUE TITLE
Circuits don't work

### ISSUE THREAD

**Issue by Vect0r2** [tgstation/tgstation#80526]
## Issue Summary
When you open up a circuit and it's "+", if you have linked it to a circuit imprinter, you will get a fatal exeception error.

## Round ID:
Don't remember, but it has happened multiple times.

## Reproduction:

Grap circuit board
Link circuit board to imprinter
Open up circuit board
Press the plus button at the top
Watch it blue screen

**Comment by SyncIt21** [comment]
Duplicate #80437
