### ISSUE TITLE
Protolathe/imprinter not searching nor showing all designs.

### ISSUE THREAD

**Issue by lilahnovi** [tgstation/tgstation#80540]
Reporting client version: 515.1621

## Issue Summary

(Just checked, and this is also the same way in medical as it is in engineering.) However, both fabrication machines are having this issue. This was on Tramstation (also Birdshot, now.) This could be on my end, I'm not sure.

1. All designs is not showing all designs on Dept. Protolathe or the Circuit Imprinter.
2. Search no longer functions.

===================================
-  **(All Designs not listing.)**

![image](https://github.com/tgstation/tgstation/assets/124811534/4b617613-5986-4962-bd30-9e976b1d5a48)
![image](https://github.com/tgstation/tgstation/assets/124811534/ac9ca317-6c09-449e-a9ee-429fcaa6b59f)

-  **(Going into another tab, items do show up. However...)**

![image](https://github.com/tgstation/tgstation/assets/124811534/aed8c19b-c585-4b29-bc50-117bc08d9351)

-  **(Partial search)**

![image](https://github.com/tgstation/tgstation/assets/124811534/a339ee89-c01c-4e76-88bb-23cf27043e66)

-  **(Searching the whole word or with proper capitalization)**

![image](https://github.com/tgstation/tgstation/assets/124811534/961e959a-5de4-43ed-a1fe-3ad974c9222d)
![image](https://github.com/tgstation/tgstation/assets/124811534/9dc93c48-7b52-47c5-a529-bb94baa12f28)

## Round ID:
[221018](https://scrubby.melonmesa.com/round/221018)

## Testmerges:
- [Save json savefiles to disk in pretty print form](https://www.github.com/tgstation/tgstation/pull/80512)
- [(Testmerge Ready) New Antagonist: Tiger Cooperative Fanatic](https://www.github.com/tgstation/tgstation/pull/80313)
- [[TM ONLY] Remove 'natural' beheading](https://www.github.com/tgstation/tgstation/pull/80439)
- [Tones down cyborg lover to cyborg fan](https://www.github.com/tgstation/tgstation/pull/80508)

## Reproduction:

Just go to a departmental protolathe or a circuit imprinter and try to search.

**Comment by jlsnow301** [comment]
Duplicate #80516 #80528 and closed in #80520
