### ISSUE TITLE
Sentient legions make you passive to Megafauna if you haven’t killed any lavaland mobs

### ISSUE THREAD

**Issue by General-Gaston** [tgstation/tgstation#80548]
## Issue Summary

When a player uses a sentience potion on a legion, they heal the player and anyone who is injured. This puts the player and anyone who was healed on the lavaland mob team which makes megafauna passive to anyone who hasn’t harmed a lavaland creature before being skulled. 

## Round ID:

[221019](https://scrubby.melonmesa.com/round/221019)

## Reproduction:

Obtain a sentience potion and use it on a legion.
Make sure to not harm ANY lavaland mob  other than legion skulls before you use the sentience potion or it will not work. Hide behind rock walls so that the skulls don’t bite your toes until the sentience potion gets taken by a player. Command the sentient legion to skull you. if you are at full health, damage yourself so that the skulls can heal you. Now you can damage megafauna without them retaliating, buckle them to a scooter for a fun joy ride around lavaland or bring them on station. Most megafauna are affected by this method, with the exception of Heirophant which promptly murders you for even having the balls to approach him

**Comment by CCC23** [comment]
this seems cool
