### ISSUE TITLE
Lavaland Golem ORM Gives 0 Points

### ISSUE THREAD

**Issue by wulfenbach-jpg** [tgstation/tgstation#80559]
## Issue Summary
When golems deposit raw ores into their freshly constructed ORM, there are no points given in return. Typically, ORMs reward their depositors with points, even without an ore silo. Without a standard method to access points, golem R&D progression via their exclusive mining vendor is halted, except for gathering points through geysers. Golem silos are locked behind mining points because a golem must be able to construct the devices found in _The Liberator's Legacy._
![image](https://github.com/tgstation/tgstation/assets/53832839/57d67d9a-78e1-42b6-aedd-c34f8548ee5d)

## Round ID:
[221084](https://scrubby.melonmesa.com/round/221084)

## Testmerges:
Master commit: [cb19fd33d7ce92c9eba1769a176c48dbd5a86352](https://www.github.com/tgstation/tgstation/commit/cb19fd33d7ce92c9eba1769a176c48dbd5a86352)
The following pull requests are currently test merged:
[#80512: 'Save json savefiles to disk in pretty print form' by MrStonedOne at commit b5556b1e6e](https://www.github.com/tgstation/tgstation/pull/80512)
[#80313: '(Testmerge Ready) New Antagonist: Tiger Cooperative Fanatic' by itseasytosee at commit 6342b58e21](https://www.github.com/tgstation/tgstation/pull/80313)
[#80439: '[TM ONLY] Remove 'natural' beheading' by Mothblocks at commit ab7dae6065](https://www.github.com/tgstation/tgstation/pull/80439)

Local commit: e94e7a4c7b034de5fbbc2a0b0b5af7e260019456
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

## Reproduction:
1. Spawn as a golem.
2. Construct your ORM.
3. Mine ore. (ash/silver/iron/etc.)
4. Drag the ore inside an ore box onto the input area.
5. Observe as the ORM takes in the ore.
6. Observe as you receive no points.

**Comment by SyncIt21** [comment]
> Typically, ORMs reward their depositors with points, even without an ore silo

This was never the case. maybe it is downstream but here you need an ore silo connection to redeem points. This has always been the case, this was done so people don't Un wrench and drag the ore silo with them to Lava land and hoarding all the mining points for themselves.

![Screenshot (378)](https://github.com/tgstation/tgstation/assets/110812394/a36071a9-71c1-4608-a6dd-27f9868eb88c)

Changing it would be a balance PR and nobody is interested in that.
