### ISSUE TITLE
Cats cannot reproduce naturally or through cytology

### ISSUE THREAD

**Issue by krookodilehunter** [tgstation/tgstation#80560]
## Issue Summary
Cats no longer make kittens if you get a male and female together. Nor can you even swab a cat for samples to use for cytology purposes. (Also they don't make tippy tap sounds on the floors anymore.)

## Round ID:

[Round ID]: # 221083

## Testmerges:

Master commit: [33780514d9268a2682372a6911255b1cdd38d3a9](https://www.github.com/tgstation/tgstation/commit/33780514d9268a2682372a6911255b1cdd38d3a9)
The following pull requests are currently test merged:
[#80304: 'Increase TGUI connection lost threshold' by lessthnthree at commit 29474fd7c3](https://www.github.com/tgstation/tgstation/pull/80304)
[#80519: 'Add system for safely manipulating JSON databases and apply it to photo albums and photo frames' by Mothblocks at commit 8bea963b43](https://www.github.com/tgstation/tgstation/pull/80519)

Local commit: d7e745f0837b230ed5f455c29eb2c09cc9df321d
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

## Reproduction:
Naturally: Get a male and female cat together, wait a bit. Wait a bit more. Continue waiting forever because it nothing happens.
Cyology: Find a cat, try to use the biopsy tool, be told that you cannot find anything on the cat.

**Comment by 00-Steven** [comment]
#81108 should handle the cytology and footstep parts, looking into the breeding part will have to wait until later.

**Comment by krookodilehunter** [comment]
> Would've been easier if these were separate issue reports, but anyhow. Breeding I haven't yet looked into, but for cytology and stepping sounds it seems like the update of cats to basic mobs failed to carry over those properties. Those two don't sound like hard fixes, lemme look into it.

sorry i didn't realize they should've been two reports, my bad! but thank you for taking and a look and fixing the cytology end!

**Comment by 00-Steven** [comment]
Hey it's better to make an issue report than no issue reports!
Anyhow, #81121 should fix the normal breeding part.
