### ISSUE TITLE
Oversight?: Breathing and Body Temperature Thresholds

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#8057]
Currently your body temp must be above 460 before you start taking heat damage level 3

That said, when breathing in hot air, the amount required to trigger heat breath damage level 3 is 1000 instead of 460.

Is this intentional or an oversight?

**Comment by hornygranny** [comment]
Should be the opposite, your skin is a lot tougher than your lungs are.

**Comment by Fox-McCloud** [comment]
Breathing in hot/cold air also doesn't impact your body temp; it just causes you to take damage.

**Comment by Fox-McCloud** [comment]
Upon further examination, it would appear that potentially having body temp thresholds of 1000+ would break heat damage application.

**Comment by Miauw62** [comment]
breathing code a shit.
anybody remember that time that breathing in a locker would cause you to
suffocate really quickly?

**Comment by Jalleo** [comment]
Yep this needs to be refactored for sure.

**Comment by Miauw62** [comment]
was this fixed?

**Comment by phil235** [comment]
probably not.

**Comment by duncathan** [comment]
This isn't a bug lol
