### ISSUE TITLE
Conveyors maintain movement if you z-level transition off one

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#80575]
Reporting client version: 514.1589

## Round ID:
[221081](https://scrubby.melonmesa.com/round/221081)

## Testmerges:
- [Epic RPD Update: Multiple Pipe Layers With 1 Click](https://www.github.com/tgstation/tgstation/pull/80073)
- [[TM ONLY] Remove 'natural' beheading](https://www.github.com/tgstation/tgstation/pull/80439)

## Reproduction:

Haven't re-tested this, centcom doesn't care much for stairs, but this player made contraption below seems to cause issues when the conveyors move the mob up the stairs ; the mob maintains its upwards movement thereafter keeping them moving even when no longer on any conveyors.  Walking over a laid conveyor seems to reset this movement.

![image](https://github.com/tgstation/tgstation/assets/3789327/9f29e60d-4bae-4624-928d-adb04c82841a)

(Shot from Icebox chapel, lower floor)

The upper level may need flooring/lattice but also needs a gap in it probably to ascend the stairs, some experimentation may be required to reproduce this.

**Comment by mc-oofert** [comment]
Reproduction:
1. Build conveyors into stairs, with conveyors also under the tile
2. Make sure people can actually ascend the stairs
3. Put conveyors after the stairs on the bottom
4. Walk onto conveyors
5. 
![image](https://github.com/tgstation/tgstation/assets/70376633/0194fc58-9a80-439e-916e-5350d8e2a509)
