### ISSUE TITLE
AI camera static persists when using mech domination/beacon

### ISSUE THREAD

**Issue by trexter5555** [tgstation/tgstation#80582]
roundid 221140
client version: 515.1621

put yourself in a mech and walk around, and areas with static will still have static in them
may be intentional i have no idea

**Comment by zxaber** [comment]
This has been a thing for years, probably forever.

AI static is like a bad stain, once it's on the screen it's impossible to get rid of.

**Comment by Sealed101** [comment]
not a bug; there is a mech camera equipment for this. neither do i recall any code in mechs/ai interactions that would imply granting sight to ai pilots. i suppose we can tell AIs whether or not the mech they're about to pilot has a camera or not but that's the extent of it
