### ISSUE TITLE
deconstructing the wall the spare id safe is on drops the spare

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#80588]
Reporting client version: 515.1623

## Issue Summary

destroying the wall under the spare safe
destroys the safe and drops the spare

## Round ID:
[221164](https://scrubby.melonmesa.com/round/221164)

## Testmerges:
- [Save json savefiles to disk in pretty print form](https://www.github.com/tgstation/tgstation/pull/80512)
- [(Testmerge Ready) New Antagonist: Tiger Cooperative Fanatic](https://www.github.com/tgstation/tgstation/pull/80313)
- [[TM ONLY] Remove 'natural' beheading](https://www.github.com/tgstation/tgstation/pull/80439)

## Reproduction:

1. destroy wall supporting safe
2. profit

**Comment by Admiral-Gigaton** [comment]
QUICKLY, DELETE THIS SO WE CAN ABUSE IN GAME
