### ISSUE TITLE
New voting means that you can't pick a cult leader (or it's at least weirder than before?)

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#80620]
## Issue Summary
A cultist trying to start a vote shows only a ghost poll for whether or not you yourself want to be cult leader.

From there, I saw Gay Johnson try to request cult leader several times with zero votes popping up.

## Round ID:
[221210](https://scrubby.melonmesa.com/round/221210)

**Comment by Overuseddart** [comment]
Sentience ballons do not work either as the poll is to take control of the balloon and not the mobs around it

**Comment by 13spacemen** [comment]
@Overuseddart sentience fun balloon should work with https://github.com/tgstation/tgstation/pull/80536, it was runtiming
the poll is NOT to take control of the balloon, it's just the role_name_text that says "sentience fun balloon"

as for this cult issue i am trying to fix it

**Comment by Admiral-Gigaton** [comment]
should probably add the "FUCK" tag, as i think voting broke with things such as:

soulstones
sentient animals (as stated previously)
possibly posi brains? you can still possess but you gotta manually click on em, at least i think
a decent amount of ghost roles got borked

**Comment by 13spacemen** [comment]
@Admiral-Gigaton IIRC soulstones and posibrains dont use the SSpolling system
if it doesnt have big text on the left its not SSpolling
