### ISSUE TITLE
Janiborg does not clean tiles below itself automatically

### ISSUE THREAD

**Issue by rabbetbunzel** [tgstation/tgstation#80629]
Reporting client version: 514.1589

## Issue Summary

When playing a Janiborg normally, walking over dirty/bloodied tiles should instantly clean them. However, this does not happen.

## Round ID:
[221245](https://scrubby.melonmesa.com/round/221245)

## Testmerges:
- [Add system for safely manipulating JSON databases and apply it to photo albums and photo frames](https://www.github.com/tgstation/tgstation/pull/80519)

## Reproduction:

Step 1: be Janiborg
Step 2: have mess on floor
Step 3: walk over
Step 4: mess still there

**Comment by dragomagol** [comment]
Intended.
https://github.com/tgstation/tgstation/pull/64131
