### ISSUE TITLE
Chemical Reactions Don't Start Sometimes

### ISSUE THREAD

**Issue by dalmationer** [tgstation/tgstation#80632]
## Issue Summary

I've noticed over the last two days or so that some chemical reactions haven't been starting properly. Some examples: The bastion bourbon reaction (berry juice, tea, creme de menthe and triple citrus) doesn't finish reacting until heated with a lighter. The seiver synthesis reaction is most notable, as despite being a very easy reaction of three chemicals, it often will not start. It seems to be especially prevalent when there are other chems in the beaker, such as iron, which I often heat and use as a buffer to keep the PH stable while synthesising it. 

## Reproduction:

1. Set up a macro for Seiver in the chemical dispenser with a buffer chem.
2. note that sometimes the reaction will not work, when by all means it should.
3. move the reagents about using the chemmaster. Sometimes it will cause the reaction to start again, other times it will not.

**Comment by Mothblocks** [comment]
this has been happening to me with blood + unstable mutagen especially
