### ISSUE TITLE
UI on Explorer drones are stacked up against each other

### ISSUE THREAD

**Issue by iansdoor** [tgstation/tgstation#80636]
Reporting client version: 514.1589

## Issue Summary
Summary,
The UI that allows you pick choices and interact with the chosen anomaly looks like this.
![Screenshot_1168](https://github.com/tgstation/tgstation/assets/109386467/03603e68-af98-4d58-a03d-1f0fc4a834fa)

## Round ID:
Round ID 221275 and 221276 

## Testmerges:
- [[TM ONLY] Remove 'natural' beheading](https://www.github.com/tgstation/tgstation/pull/80439)

**Comment by OverwatchVoice** [comment]
Tried it out today, can confirm the issue's still persistent.
Aditionally, adding equipment to a drone "multiplies" the invenotry vertically, with no upper limit
