### ISSUE TITLE
Staff of Change can gib and/or ghost target, occasionally sending brains to secret room

### ISSUE THREAD

**Issue by RandomlyEvil** [tgstation/tgstation#80640]
Reporting client version: 514.1589

## Round ID:
[221297](https://scrubby.melonmesa.com/round/221297)

## Testmerges:
- [[TM ONLY] Remove 'natural' beheading](https://www.github.com/tgstation/tgstation/pull/80439)
- [Heretic DLC: Path of Moon](https://www.github.com/tgstation/tgstation/pull/79536)

## Reproduction:

Using staff of change on other beings can ghost or gib them, occasionally sending their brain (if sentient) to the secret room.  Does not happen every change.
Seems that it ghosts the player hit if turning them into a borg or drone (?).  It does create the borg/drone body but leaves the new "body" catatonic, meanwhile the player for the brain is ghosted.  
Other changes will gib the target.  Some brains wind up in the secret room.  No recognizable pattern found during this round.

**Comment by Time-Green** [comment]
I just fucking fixed this I am going insane

**Comment by MrMelbert** [comment]
not unit tests

**Comment by timothymtorres** [comment]
Related and/or dupes:

- https://github.com/tgstation/tgstation/issues/80436
- https://github.com/tgstation/tgstation/issues/80093
- https://github.com/tgstation/tgstation/issues/42685

**Comment by Time-Green** [comment]
> Related and/or dupes:
> 
> * [Polymorphing someone into a drone gibs them and doesn't put their mind in the drone #80436](https://github.com/tgstation/tgstation/issues/80436)
> * [Polymorph belt can cause nullspacing of the mob (while dead at that) #80093](https://github.com/tgstation/tgstation/issues/80093)
> * [Change staff making people invisible and mute #42685](https://github.com/tgstation/tgstation/issues/42685)

The second and third are unrelated, the first I forgot to close
