### ISSUE TITLE
Antagonist rolls take priority over preferences

### ISSUE THREAD

**Issue by RikuTheKiller** [tgstation/tgstation#80645]
## Issue Summary

It seems antagonist rolls take priority over the "what do if all roles full" setting.

I had it set to "return to lobby if unavailable" and when all roles were full, it booted me to a random job.

It's likely due to the fact I rolled antag and the issue had to be fixed via ahelp.

This does not include any in-round information except "an antagonist was rolled" thus it should be fine.

## Reproduction:

1. Select "return to lobby if unavailable" as your backup preference.
2. Roll antag while all roles you tried to roll for are occupied.
3. Get sent to a random job which really shouldn't happen.

**Comment by MrMelbert** [comment]
This is WAD, if you roll an antagonist but fail to be given any of your jobs the game will force you into one, being unable to reject you (because at this point, it cannot reroll antags). 

![image](https://github.com/tgstation/tgstation/assets/51863163/3b4c44b4-fba3-4d8e-a29d-0be3bae2e055)
