### ISSUE TITLE
Build.bat error

### ISSUE THREAD

**Issue by Foteboup** [tgstation/tgstation#80657]
Downloading Node v14.16.1 (may take a while)
Using vendored Node v14.16.1
:: Juke Build version 0.8.1
=> Starting 'yarn'
=> Starting 'cutter'
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 332ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 30 packages were already cached, 973 had to be fetched
➤ YN0000: └ Completed in 2s 793ms
➤ YN0000: ┌ Link step
=> Finished 'cutter' in 5.186s
=> Starting 'icon-cutter'
Hypnagogic CLI v3.0.1
Found 110 files!
Successfully processed 110 files! (Took 718.17ms)
=> Finished 'icon-cutter' in 1.15s
=> Starting 'dm'
:: Using defines: CBT
=> Target 'dm' failed in 0.278s, unhandled exception:
Error: spawn dm.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn dm.exe',
  path: 'dm.exe',
  spawnargs: [ '-DCBT', 'tgstation.dme' ]
}
➤ YN0000: └ Completed in 11s 424ms
➤ YN0000: Done in 14s 795ms
=> Finished 'yarn' in 15.645s
=> Target 'tgui' failed
=> Target 'build' failed
=> Please inspect the error and close the window.

this is at first startup and through BUILD.cmd

and this is a direct launch via build.bat.

Using vendored Node v14.16.1
:: Juke Build version 0.8.1
:: Skipping 'cutter' (condition unmet)
:: Skipping 'yarn' (up to date)
=> Starting 'tgui'
:: Skipping 'icon-cutter' (up to date)
=> Starting 'dm'
:: Using defines: CBT
=> Target 'dm' failed in 0.109s, unhandled exception:
Error: spawn dm.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn dm.exe',
  path: 'dm.exe',
  spawnargs: [ '-DCBT', 'tgstation.dme' ]
}

and then it closes with an error, but the dmb file has not appeared.

**Comment by ZephyrTFA** [comment]
Byond is not on your path. verify it is installed and on your path environment variable

**Comment by MrStonedOne** [comment]
this means it couldn't find byond to compile the game. make sure it is installed.

**Comment by MrStonedOne** [comment]
> Byond is not on your path. verify it is installed and on your path environment variable

byond has never been in path

**Comment by Foteboup** [comment]
I've got it

**Comment by Foteboup** [comment]
Now what's wrong with that?

Using vendored Node v14.16.1
:: Juke Build version 0.8.1
:: Skipping 'cutter' (condition unmet)
:: Skipping 'yarn' (up to date)
=> Starting 'tgui'
:: Skipping 'icon-cutter' (up to date)
=> Starting 'dm'
:: Using defines: CBT
DM compiler version 514.1589
-DCBT does not exist.
-DCBT.dmb - 0 errors, 0 warnings (12/29/23 9:08 pm)
Total time: 0:00
=> Target 'dm' failed in 0.2s, exit code: 4294967295
assets by path *.js 2.98 MiB
  asset tgui.bundle.js 2.02 MiB [compared for emit] [minimized] (name: tgui)
  asset tgui-panel.bundle.js 664 KiB [compared for emit] [minimized] (name: tgui-panel)
  asset tgui-say.bundle.js 325 KiB [compared for emit] [minimized] (name: tgui-say)
assets by path *.css 529 KiB
  asset tgui.bundle.css 414 KiB [compared for emit] [minimized] (name: tgui)
  asset tgui-panel.bundle.css 105 KiB [compared for emit] [minimized] (name: tgui-panel)
  asset tgui-say.bundle.css 11 KiB [compared for emit] [minimized] (name: tgui-say)
Entrypoint tgui 2.42 MiB = tgui.bundle.css 414 KiB tgui.bundle.js 2.02 MiB
Entrypoint tgui-panel 768 KiB = tgui-panel.bundle.css 105 KiB tgui-panel.bundle.js 664 KiB
Entrypoint tgui-say 335 KiB = tgui-say.bundle.css 11 KiB tgui-say.bundle.js 325 KiB
2023-12-29 21:09:14: webpack 5.89.0 compiled successfully in 19067 ms
=> Finished 'tgui' in 25.058s
=> Target 'build' failed
=> Please inspect the error and close the window.

**Comment by ZephyrTFA** [comment]
We require 515 to compile

**Comment by Igz0m** [comment]
Finally a god damn up-to-date solution
