### ISSUE TITLE
protolathe searchbars are horrible to type in

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#80679]
Reporting client version: 515.1623

## Issue Summary

i dont even know what the fuck is wrong with them but typing in them is laggy as shit and it messes with your input

## Round ID:
[221386](https://scrubby.melonmesa.com/round/221386)

## Testmerges:
- [[TM ONLY] Remove 'natural' beheading](https://www.github.com/tgstation/tgstation/pull/80439)
- [Rewrites dropdown and popper components as FCs](https://www.github.com/tgstation/tgstation/pull/80556)

## Reproduction:

1. open protolathe
2. try to search a phrase like "autolathe"
3. struggle

**Comment by jlsnow301** [comment]
most likely caused by searchbar having a built in debounce and #80614
