### ISSUE TITLE
Rev/cult and golems.

### ISSUE THREAD

**Issue by SeikoTheSeal** [tgstation/tgstation#8068]
Right now when golem is created, it recieves this message:

You are an adamantine golem. You move slowly, but are highly resistant to heat and cold as well as blunt trauma. You are unable to wear clothes, but can still use most tools. Serve Ronnette Paynter, and assist them in completing their goals at any cost.

Golems can also be reved, which will result in cases like this:

Serve Ronnette Paynter, and assist them in completing their goals at any cost.

You are now a revolutionary! Help your cause. Do not harm your fellow freedom fighters. You can identify your comrades by the red "R" icons, and your leaders by the blue "R" icons. Help them kill the heads to win the revolution!

This is   Ronnette Paynter!
She is wearing   Ronnette Paynter's ID Card (Chief Engineer).

Say, non rev master orders golem to protect a head of staff. Antag status tells golem to kill said head of staff. Golem is now confused and wants to suicide becouse it has no idea which one takes precedence, antag status or masters orders.

Making golems unable to be reved, or giving them a notification that they no longer have to assist and listen to their master once they are brainwashed might help with the confusion.

**Comment by Incoming5643** [comment]
This is more a policy thing than a code thing, but my personal stance has always been that it works like this in terms of priority, with lower numbers trumping higher ones:

1. Actual explicit in game antagonist status (converted to cult|revolution)
2. Secondary implicit antagonist status (from having an antagonist creator)
3. Tertiary servitude (every other instance of being a golem)

**Comment by AnonymousNow** [comment]
If only it were possible to make golem revability (new word copyright Now 2015) linked to their master - so a golem would only be able to be rev'd if their summoner was already a rev. Same with cult.

**Comment by Jalleo** [comment]
We should create a sort of config to manage this sort of policy stating so it is more easily designated by policy of the servers than having the code half conflict with it by oversight.
