### ISSUE TITLE
Reaction chamber rounding issue

### ISSUE THREAD

**Issue by RikuTheKiller** [tgstation/tgstation#80685]
## Issue Summary

#80495 general maintenance more like general breakage.

Somehow, reaction 2 batches of 50u lenturi with 50u lithium as a buffer and then combining the resulting lenturi results in 99.99u of lenturi, A.K.A a rounding issue is happening somewhere.

This issue did not exist before the PR and it resulted in the correct (100u) amount of lenturi.

## Testmerges:

[#80439: '[TM ONLY] Remove 'natural' beheading' by Mothblocks at commit ab7dae6065](https://www.github.com/tgstation/tgstation/pull/80439)
[#79536: 'Heretic DLC: Path of Moon' by Rex9001 at commit 41c48879b6](https://www.github.com/tgstation/tgstation/pull/79536)

## Reproduction:

1. React 50u of pure lenturi with 50u of lithium as a buffer.
2. Do it again.
3. Merge the resulting batches.
4. Observe the rounding error.

**Comment by SyncIt21** [comment]
Unable to reproduce on local

https://github.com/tgstation/tgstation/assets/110812394/e826b98b-0258-4dfb-bbfe-b4758f0cf4e9

The only explanation is that Lenturi overheating temperature is above 500k after which it evaporates and its volume decreases so cranking the chem heater to 1000k isn't always the best solution, and if it does work anyway (which it did in my case) it's only by fluke

As long as you keep your temps in control this won't be an issue
