### ISSUE TITLE
Getting ejected from a cryo tube puts your sprite below the tube

### ISSUE THREAD

**Issue by 13spacemen** [tgstation/tgstation#80699]
## Issue Summary
Getting ejected from a cryo tube puts your sprite below the tube instead of above it

It's difficult to tell if someone is "under" a cryo tube due to the huge sprite
seems like a layer issue?

## Reproduction:
Get healed in a cryo tube, get ejected, your sprite is below the huge cryo tube sprite

**Comment by Mothblocks** [comment]
same with the beakers
