### ISSUE TITLE
"Blue" traitor codewords are not formatted properly

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#80700]
Reporting client version: 514.1589

## Round ID:
[221449](https://scrubby.melonmesa.com/round/221449)

## Testmerges:
- [[TM ONLY] Remove 'natural' beheading](https://www.github.com/tgstation/tgstation/pull/80439)
- [Heretic DLC: Path of Moon](https://www.github.com/tgstation/tgstation/pull/79536)

## Reproduction:

Be traitor
Say blue codeword 

![image](https://github.com/tgstation/tgstation/assets/3789327/9bc9c933-a8d4-43fe-adaa-37311711fceb)

![image](https://github.com/tgstation/tgstation/assets/3789327/f41517b1-f3a2-481e-9cf7-be878cf9e1f4)

**Comment by lessthnthree** [comment]
I can't seem to replicate this.

![image](https://github.com/tgstation/tgstation/assets/83487515/e1cb5ad4-8845-4794-a2a6-e8b463e0e267)

**Comment by iprice** [comment]
Does seem gone now, maybe some brief issue with something cached and a change, that cleared up.  Idk, happy for this to be closed though.
