### ISSUE TITLE
damp rags can instantly transfer reagents

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#80716]
Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [221510](https://scrubby.melonmesa.com/round/221510)
BYOND Version: 515.1623
Server revision compiled on: 
Master commit: [b15cd9ccea8101b4ed03ac248597cd63365865cc](https://www.github.com/tgstation/tgstation/commit/b15cd9ccea8101b4ed03ac248597cd63365865cc)
The following pull requests are currently test merged:
[#80635: 'The Anomacyberbrawlening: Spinal Implants (Normal and Anomaly Crafted), Strong-arm Implant Change, Boxing Changes' by necromanceranne at commit 3901340b4a](https://www.github.com/tgstation/tgstation/pull/80635)
[#80556: 'Rewrites dropdown and popper components as FCs' by jlsnow301 at commit 72e0fd8115](https://www.github.com/tgstation/tgstation/pull/80556)

Local commit: 04584176c986cb8f7b1e05591ae215f10a4f33b4
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 1
Allow Latejoin Antagonists: 1
## Issue Summary

using a damp rag on a target will instantly transfer reagents to the target

## Reproduction:

attack someone with a rag containing whatever, they will instantly recieve the chems in the rag

**Comment by JohnFulpWillard** [comment]
isn't this intentional?

**Comment by Jackal-boop** [comment]
> isn't this intentional?

i was always under the assumption that it required a do after

**Comment by Mothblocks** [comment]
Intentional yeah
