### ISSUE TITLE
Admin Healing monkeys makes them into humans

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#80744]
Reporting client version: 514.1589

## Round ID:
[221567](https://scrubby.melonmesa.com/round/221567)

## Testmerges:
- [[TM ONLY] Remove 'natural' beheading](https://www.github.com/tgstation/tgstation/pull/80439)

## Reproduction:

See title

**Comment by GPeckman** [comment]
Monkeyification is a mutation, and it is considered to be a negative mutation. Aheal heals all negative mutations (although it was bugged for a long time), so monkeys become human when ahealed.

**Comment by SethLafuente** [comment]
> Monkeyification

could be fixed by just making monkeyfication not a negative mutation or just make removing mutation an option thing in the admin panel.

still a bug as of now
