### ISSUE TITLE
Vents that are turned off replay their shutting down animation when brought back into a player's view.

### ISSUE THREAD

**Issue by Treachce** [tgstation/tgstation#80748]
## Issue Summary
Vents that are disabled reset their animations when a player moves far enough away then goes back.

## Reproduction:
Have an unary vent turned off or otherwise disabled, run maybe a dozen tiles away, and then run back, and you'll see the vent's stop spinning animation run again. This is easiest to see as a ghost but can be seen as a player.

![untitled](https://github.com/tgstation/tgstation/assets/69348667/f1fb1626-6b8b-4039-87d3-3e6385d8f9bd)

**Comment by lessthnthree** [comment]
It's a larger thing with icons that have an 'animate once' loop. Things that animate forever seem fine, but the ones that only play once will replay when they come back into view. The tram signs do the same thing (see left.)

https://github.com/tgstation/tgstation/assets/83487515/a9a28cc9-d2f2-4561-909d-eb70125ebf7b
