### ISSUE TITLE
Randomization buttons doesn't work

### ISSUE THREAD

**Issue by Traysoul** [tgstation/tgstation#80754]
## Issue Summary

Randomization buttons doesn't work, you can click, you can choose, but they don't change the value. And its too width. Tried clearing my cache, it didn't helped.
![изображение_2024-01-03_173559706](https://github.com/tgstation/tgstation/assets/58553282/24f8cec9-0f8b-48ad-a27c-392cb7fdbab7)
## Round ID:

any

**Comment by jlsnow301** [comment]
Duplicate #80689
