### ISSUE TITLE
FREE MATS!!!

### ISSUE THREAD

**Issue by TwistedCicrularConvexLens** [tgstation/tgstation#80755]
## Issue Summary

You can get literally infinite materials as long as you have one sheet of the original (including bananium thanks to Airhorns).

## Reproduction:

Step 1: Upgrade any protolathe with sufficiently better servos.
Step 2: Upgrade an autolathe with sufficiently better servos.
Step 3: Make an item from the protolathe and get a discount on the material costs.
Step 4: Get the undiscounted material costs back by putting it into an autolathe.
Step 5: Repeat for infinite profit.

Optional Step 6: Use a recycler instead since it can handle larger loads.

https://github.com/tgstation/tgstation/assets/106436013/03be8ca3-0a6c-473f-b78d-55f76e9417b8

Materials Out Vs Materials In:

![image](https://github.com/tgstation/tgstation/assets/106436013/354bd539-9a2b-4be3-9ce3-50a82ea038bd)

**Comment by lessthnthree** [comment]
https://github.com/tgstation/tgstation/pull/80164

Items that are printed from lathes/techfabs should only be providing 0.4 the material cost when recycled/fed to the machine, not 1.

**Comment by SyncIt21** [comment]
That PR touches on material container which is shared my many machines and isn't specifically target at autolathes in any way,  not related .

The real solution is to simply scale the custom materials of printed items based on the parts efficiency so the problem is solved for both autolathe and recycler

**Comment by Mothblocks** [comment]
i swear to god i've seen this same flavor of bug come up a hundred times man
