### ISSUE TITLE
Becoming a psyker will lower your fps over a few minutes until your entire client is frozen and crashes.

### ISSUE THREAD

**Issue by Xkallubar** [tgstation/tgstation#80798]
## Issue Summary

This is my first time becoming a psyker after this pr: https://github.com/tgstation/tgstation/pull/80042. This time it was from dna instability but it would probably have the same result when becoming a psyker from the punished sect. Upon becoming a psyker, all was normal, until I noticed my fps was a bit lower, and it kept getting lower and lower and lower and eventually the game was completely frozen. This affects the entire client, including chatting and ahelping. Rejoining the game resets you back to normal fps, but the cycle will continue and your fps will drop until you freeze and crash.

## Reproduction:

Simply become a psyker.

**Comment by MrStonedOne** [comment]
Hello what is your byond username, i want to find details from the logs

**Comment by Xkallubar** [comment]
> Hello what is your byond username, i want to find details from the logs

CrazyPro

**Comment by iprice** [comment]
Seen a few cases but in the interests of providing details
Reported by Onjec in round 223306 Terry.  Acquired via gene mutation.
