### ISSUE TITLE
sentience balloons not working

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#80821]
Reporting client version: 515.1623

## Round ID:
[221750](https://scrubby.melonmesa.com/round/221750)

## Testmerges:
- [[TM ONLY] Remove 'natural' beheading](https://www.github.com/tgstation/tgstation/pull/80439)
- [tgui now disables topics on world reboot, should fix reconnects randomly failing](https://www.github.com/tgstation/tgstation/pull/80779)

## Reproduction:
The ghost poll appears, but people that sign up don't get put into blooned mobs.

**Comment by 13spacemen** [comment]
I was in a Terry round a few days ago and an admin used the balloon and it worked fine, I can't see any runtimes from the round log so not sure why you had that problem

**Comment by necromanceranne** [comment]
What kind of mobs were you trying to sentience?

**Comment by Striders13** [comment]
> What kind of mobs were you trying to sentience?

humans, but it seems to be working now, so i guess nobody just signed up last time?

closing
