### ISSUE TITLE
Bitrunning virtual domains sometimes fling objects into space due to race condition with atmos

### ISSUE THREAD

**Issue by BurgerLUA** [tgstation/tgstation#80843]
## Issue Summary

When a bitrunning virtual domain is in the process of getting deleted, not everything gets deleted at once (this is good as it prevents lag) and slowly loops through all the turfs. Unfortunately, sometimes atmos can push items from a deleting turf, to a deleted turf (now a space turf), which then in turn causes it to exist in the real world as the item is now floating through the space z-levels. In rare cases, items and corpses can even float to the station.

## Round ID: Bubberstation (degenerate)

https://github.com/Bubberstation/Bubberstation

**Comment by jlsnow301** [comment]
Duplicate #79196
