### ISSUE TITLE
Backpack, ID and belt slot become unclickable at the start of a round sometimes

### ISSUE THREAD

**Issue by kawoppi** [tgstation/tgstation#80847]
## Issue Summary

This has happened to me twice in total so far, each time at the start of a new round after reconnecting. My BYOND version is 515.1623. I have no clue what exactly causes this. Your backpack, ID and belt slot become unclickable. You can still remove/insert stuff using shift+b or shift+e. But you can't take or place any items with clicking, nothing happens. You also can't inspect them nor do stuff like taking the pen out of the PDA with ctrl+click. You also can't right click your bag to see what's in there. The suit and pocket slots seem to be working just fine.

Using ctrl+b you can take your survival box out of your backpack. You can right click the box to see what's inside just like normally, but you can only take items if they are in the first slot, the last slot or the second to last slot. Clicking any item in the 2nd, 3rd, etc. slot doesn't do anything. You can also only insert items into the first slot, the last slot or the second to last slot, You can get around it by holding the item in your hand and just clicking the box with it. But also SOMETIMES the 2nd slot DOES work and I feel like I'm going insane.

Last time I tried reconnecting, closing BYOND or clearing the cache until things went back to normal but in this round I can't seem to fix it. An admin recreated my character and that also didn't fix it. I also tried downgrading my BYOND version to 514.1589 and reconnecting which also did not fix it.

Also after I died the first two ghost buttons didn't work properly either (spawners menu and orbit). No idea if that's related or not. Orbit would only bring up the menu half of the time, the other half it made my mouse invisible until I moved it a bit. Clicking spawners menu made my mouse invisible until I moved it a bit and did nothing else.

## Round ID:

[221821](https://scrubby.melonmesa.com/round/221821)

## Testmerges:
The following pull requests are currently test merged:
[#80779: 'tgui now disables topics on world reboot, should fix reconnects randomly failing' by MrStonedOne at commit 35909a042d](https://www.github.com/tgstation/tgstation/pull/80779)

## Reproduction:
I don't know how :(

**Comment by lessthnthree** [comment]
Likely: There's an invisible BYOND window covering the area where those inventory slots are. If you try toggling to widescreen, or moving out of full screen (such as where there's an inch or two between the game and the Windows taskbar) do the slots start working to click on again?

If that's it, unfortunately no clue so far how to force close those. They're persistent until the server restarts.

**Comment by SyncIt21** [comment]
Duplicate #79651

**Comment by Sealed101** [comment]
^ sounds about right
