### ISSUE TITLE
Autolathe searchbars are STILL laggy and unresponsive

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#80853]
## Issue Summary

Autolathes appear to still be suffering the bugs outlined in https://github.com/tgstation/tgstation/issues/80797

While the PR to fix the search bars worked for techfabs, it did not do so for autolathes.

**Comment by jlsnow301** [comment]
They use the same component, so I'm a bit confused. Testing this with admins on live it seems to do it every so often. I'll play with the debounce more to see if that doesn't resolve the issue.

**Comment by Inari-Whitebear** [comment]
I dunno still same with protolathe for me.. among other issues

**Comment by moocowswag** [comment]
Same issue with component printer and circuit breadboard ui.
