### ISSUE TITLE
Space Spawned Antagonist Just Die in the Rad Nebula station trait

### ISSUE THREAD

**Issue by Draggeru** [tgstation/tgstation#80864]
## Issue Summary

Space spawned humanoid antagonist are immediately put under the effects of radiation poisoning and are automatically at a disadvantage when the POINT of spawning antagonists in space is so they have some time to think and minorly prepare before facing the station. If the rad nebula trait is active these kinds of antagonists need some form of rad protection or to be spawned on station so they do not start dying moments upon spawning.

## Round ID:

221860

## Reproduction:

Spawn as a lone op or space ninja on the radiation nebula, be forced to use TC for a medicine kit or just die because you SPAWN in a lethal situation

**Comment by ZeroKelvn** [comment]
https://github.com/tgstation/tgstation/pull/76825#issuecomment-1635762723

Intended feature, though may still justify tweaking the dynamic formula

**Comment by Draggeru** [comment]
> [#76825 (comment)](https://github.com/tgstation/tgstation/pull/76825#issuecomment-1635762723)
> 
> Intended feature, though may still justify tweaking the dynamic formula

It should never be an intended feature to place a player in a lethal situation upon being spawned. I took count after spawning a ninja and it was 10 seconds before they were irradiated, it would be better to change where the players are spawned instead of gatekeeping something that negatively impacts a players experience because its an "intended feature". Nanites had a lot of things that were "intended features" but were still removed.

**Comment by Time-Green** [comment]
Actually I could probably give non-station antags a temporary shield on spawn, like 60s of immunity total that’ll activate when in space. It’ll give them the chance to get on station, but after that they’ll have to just figure it out

**Comment by MrMelbert** [comment]
You could simply add a some code in `/datum/dynamic_ruleset/midround/from_ghosts/proc/finish_setup(mob/new_character, index)` to apply a one-size-fits-all radiation-shield-on-spawn-in-space behavior
