### ISSUE TITLE
mythril from alternative space anomaly science outpost

### ISSUE THREAD

**Issue by EDGELORD333** [tgstation/tgstation#80866]
Hey there I think there is inconsistency with this space ruin. you should be able to get mythril from Alternative science since it has liquid plasma just like in icebox but it is currently not possible for some reason

**Comment by Jacquerel** [comment]
This requires more information about how the presence of liquid plasma would lead directly to the presence of mythril.

**Comment by rageguy505** [comment]
> This requires more information about how the presence of liquid plasma would lead directly to the presence of mythril.

fishing?
![image](https://github.com/tgstation/tgstation/assets/54517726/e5b892e0-dcec-4a44-aaa1-3b9c6de3cbda)

**Comment by EDGELORD333** [comment]
Easy fishing the only 2 ways tó hét Mythril is tó either find it in
lavapand and mine it with full mining skill or to fish for it in liquid
plasma! Sorry I forgot to add the fishing part

rageguy505 ***@***.***> (időpont: 2024. jan. 8., H, 19:19)
ezt írta:

**Comment by EDGELORD333** [comment]
Kovács Gergő ***@***.***> (időpont: 2024. jan. 8., H, 21:10)
ezt írta:

**Comment by EDGELORD333** [comment]
Aye Fishing is one of the only ways of getting mythril other than randomly finding
A mythril rock in lavaland and of course you still need a mining mastery to mine it.
And of course the only way to Fish for mythril is to Fish in liquid plasma, and the alternative science outpost is full of liquid plasma ( and dangerous anomalies ) and yet it is not possible to fish in it

**Comment by MrMelbert** [comment]
Ok but who put Mythil sheets in fishing, that stuff is so unbalanced it's supposed to be admin only for the most part

**Comment by EDGELORD333** [comment]
I don't think it's so unbalanced cause it's rare to Fish and you only get one sheet of it, you cannot do much with one sheet

**Comment by CCC23** [comment]
I mean 1 mythril at 2.22% seems kinda funny and it is kind of goofy that through massive effort in FISHING of all things you can get the funny magic toolbox that sends people to hell instantly

**Comment by EDGELORD333** [comment]
Aye and if it would be possible to Fish on the alterantive science outpost it would be even rarer since that place doesn't always spawn, but it would be nice to have more places to Fish for mythril other than ice box and that place would be perfect for it
