### ISSUE TITLE
Character creation main screen is absurdly laggy when scrolling

### ISSUE THREAD

**Issue by nikothedude** [tgstation/tgstation#80878]
Reporting client version: 515.1624

## Issue Summary

Title. 

## Round ID:
[221938](https://scrubby.melonmesa.com/round/221938)

## Testmerges:
- [tgui now disables topics on world reboot, should fix reconnects randomly failing](https://www.github.com/tgstation/tgstation/pull/80779)
- [[pr only for the moment] A|B test new 515 list clear nulls method](https://www.github.com/tgstation/tgstation/pull/80869)

## Reproduction:

Step 1: Open char creation's main screen
Step 2: Try to scroll through the bottom right panel
Step 3: Suffer through a 0.8 second lag spike every 2 seconds

I have no idea what could be causing this, but its fucking agonizing, especially on nova sector, where you have a HUGE list of things to scroll through.

**Comment by nikothedude** [comment]
@vinylspiders suggested https://github.com/tgstation/tgstation/pull/80746 could be the cause, paging @jlsnow301

**Comment by nikothedude** [comment]
see https://github.com/NovaSector/NovaSector/issues/361

**Comment by jlsnow301** [comment]
> @vinylspiders suggested #80746 could be the cause, paging @jlsnow301

Doesnt seem to be the issue
