### ISSUE TITLE
cant heal simple/basicmobs with sutures

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#80884]
Reporting client version: 515.1620

## Round ID:
[221958](https://scrubby.melonmesa.com/round/221958)

## Testmerges:
- [tgui now disables topics on world reboot, should fix reconnects randomly failing](https://www.github.com/tgstation/tgstation/pull/80779)
- [Make list clear nulls faster](https://www.github.com/tgstation/tgstation/pull/80869)

## Reproduction:
says "no chest!" when you try to heal em

**Comment by 13spacemen** [comment]
cause is https://github.com/tgstation/tgstation/pull/80698

fix is simple, prob just make try_heal_checks() return true for simple mobs

i would fix it rn but i dont have access to my ss13 coding laptop

**Comment by 13spacemen** [comment]
fixed by https://github.com/tgstation/tgstation/pull/80889
