### ISSUE TITLE
Talking as ghost on ghoulbot causes client crash

### ISSUE THREAD

**Issue by MisterGrimm** [tgstation/tgstation#80886]
Reporting client version: 515.1625

## Issue Summary
If you talk while on a ghoulbot your client will instantly CTD.

## Round ID:
[221960](https://scrubby.melonmesa.com/round/221960)

## Testmerges:
- [tgui now disables topics on world reboot, should fix reconnects randomly failing](https://www.github.com/tgstation/tgstation/pull/80779)
- [Make list clear nulls faster](https://www.github.com/tgstation/tgstation/pull/80869)

## Reproduction:

1. Find ghoulbot
2. load yourself onto ghoulbot as ghost
3. Speak

**Comment by MrStonedOne** [comment]
Upstream tracking ids:

[ID:2908156](https://www.byond.com/forum/post/2908156) (515.1625, 515.1626)

Please confirm if this still happens on 1627

**Comment by ZephyrTFA** [comment]
Resolved (515.1627)
