### ISSUE TITLE
Service borgs can no longer pour drinks from beverage storage apparatus

### ISSUE THREAD

**Issue by trexter5555** [tgstation/tgstation#80881]
roundid 221946

be service borg, make a drink in your storage apparatus

try and pour it into another glass, it does not work, cant pour it into a beaker either

**Comment by trexter5555** [comment]
reportedly engieborg arm for holding mats is broken as well

**Comment by MrMelbert** [comment]
Maybe caused by #80835

**Comment by zxaber** [comment]
Yeah, this is my fault. I misread a proc and re-ordered it incorrectly.
