### ISSUE TITLE
jittering makes really weird spasms

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#80885]
Reporting client version: 515.1623

## Round ID:
[221956](https://scrubby.melonmesa.com/round/221956)

## Testmerges:
- [Optimizes Reftracking (Bigly) (Plus harddel fixes)](https://www.github.com/tgstation/tgstation/pull/80443)
- [Ref Tracking (Live)](https://www.github.com/tgstation/tgstation/pull/80879)

## Reproduction:
1. shove a guy
2. they have a seizure

**Comment by Inari-Whitebear** [comment]
I thought this is intentional to show them being "off balance"
