### ISSUE TITLE
Crash to desktop when ice box weather ends

### ISSUE THREAD

**Issue by MisterGrimm** [tgstation/tgstation#80910]
Reporting client version: 515.1626

## Issue Summary
Played as AI specifically, so don't know if this is specific to the AI or not.

When the ice box weather ends it causes a crash to desktop.

## Round ID:
[222008](https://scrubby.melonmesa.com/round/222008)

## Testmerges:
- [tgui now disables topics on world reboot, should fix reconnects randomly failing](https://www.github.com/tgstation/tgstation/pull/80779)

## Reproduction:

1. Play as AI?
2. Wait for ice box weather to start
3. Look outside
4. Wait for weather to stop
5. Crash to Desktop when weather stops

**Comment by dessysalta** [comment]
This also happens with the radiation storm, I won't ick ock but I've crashed like 10 times in one round because of both.

**Comment by Drulikar** [comment]
Might be worth retesting on 515.1627, but I don't know if the fix is purely client side or if it has a server component to it.

**Comment by MisterGrimm** [comment]
Can confirm I still crash on 515.1627

**Comment by MrStonedOne** [comment]
Upstream tracking ids:

[ID:2908156](https://www.byond.com/forum/post/2908156) (515.1625, 515.1626)
[ID:2909026](https://www.byond.com/forum/post/2909026) (515.1676)
