### ISSUE TITLE
Radiation Hood is the new old biosuit hood

### ISSUE THREAD

**Issue by iansdoor** [tgstation/tgstation#80917]
Reporting client version: 514.1589

## Issue Summary

I am aware of the nerf to the biohood as they were the get all against biohazard and facehuggers. I see their sprites are the same ish. Are the radiation hood not ment to have the vision blockers?

#consistency
![Screenshot_840](https://github.com/tgstation/tgstation/assets/109386467/a255a485-d793-4ae2-9091-8aeffc5a0246)
![Screenshot_839](https://github.com/tgstation/tgstation/assets/109386467/43e3df4f-ddd7-4477-8225-14e47eca8193)

## Testmerges:
- [tgui now disables topics on world reboot, should fix reconnects randomly failing](https://www.github.com/tgstation/tgstation/pull/80779)

**Comment by CCC23** [comment]
:(

**Comment by SethLafuente** [comment]
you really couldn't keep your mouth shut could you... you had to make me do it.
