### ISSUE TITLE
Laser carbine + Root beer = MINIGUN

### ISSUE THREAD

**Issue by nikothedude** [tgstation/tgstation#80921]
Reporting client version: 515.1621

## Issue Summary

Reported from downstream, tested upstream on a local server

Title. Drinking root beer and firing a laser carbine increases your rate of fire by significantly more than just 2x.

## Reproduction:

Step 1: Get a laser carbine and root beer
Step 2: Drink root beer
Step 3: Fire at the fastest ROF of any gun in the game, far more than the root beer should let you fire at

See https://github.com/NovaSector/NovaSector/issues/406

https://github.com/tgstation/tgstation/assets/59709059/c644abe5-62cf-438b-8f38-9b84e9ff8e90

**Comment by nikothedude** [comment]
also happens with the tesla cannon, likely due to this code working with low delay values

`
	if(HAS_TRAIT(shooter, TRAIT_DOUBLE_TAP))
		next_delay = round(next_delay * 0.5)
`

**Comment by jughu** [comment]
Its working as intended
Laser carbines are already weaker then normal lsser guns by being 10 burn a shot so you need 3 shots to outdamage a normal lasergun which isnt really that better then auctall using a lasergun plus you can't dualwield the carbines either where you can with yhe laserguns which will heavily out perform the carbine+root beer interraction

**Comment by necromanceranne** [comment]
@GPeckman your feature, intended?

**Comment by jughu** [comment]
> > Its working as intended Laser carbines are already weaker then normal lsser guns by being 10 burn a shot so you need 3 shots to outdamage a normal lasergun which isnt really that better then auctall using a lasergun plus you can't dualwield the carbines either where you can with yhe laserguns which will heavily out perform the carbine+root beer interraction
> 
> did you even watch the video
> 
> I can kill someone in less than half a second with this

Yeah but you forget every laser is 10 burn and your target will not always stand still it falls in line with lasergun since its 25 burn do the damage output stays the same when your root beering

**Comment by GPeckman** [comment]
> @GPeckman your feature, intended?

To be honest I had no idea root beer affected firing speed until now.

**Comment by necromanceranne** [comment]
I'll put it as oversight for now for anyone to resolve.

**Comment by jughu** [comment]
this is a feature added by #63956 in its own it isn't a bug or anything just balance

**Comment by nikothedude** [comment]
@Ryll-Ryll you added root beer, is this intentional by your metrics?

**Comment by LemonInTheDark** [comment]
![image](https://github.com/tgstation/tgstation/assets/58055496/ca3c323c-e749-4a73-88b5-df18ea856681)
Bug

**Comment by LemonInTheDark** [comment]
round needs a resolution that matches the wait of the projectile subsystem, instead of using floor()

**Comment by SethLafuente** [comment]
FEATURE???, anyways still a bug right now

**Comment by LemonInTheDark** [comment]
this should be trivial to fix
