### ISSUE TITLE
Admin healing a slime person removes all slime jelly from them and drains hunger bar.

### ISSUE THREAD

**Issue by SeikoTheSeal** [tgstation/tgstation#8094]
Rejuvenate removes all reagents, including slimepersons slime jelly. Due to the fact that slime people use their hunger bar to replenish jelly, slime person ends up with a red hunger bar and 29.5u of slime jelly instead of 100u after healing them.

**Comment by Incoming5643** [comment]
Will be fixed after a planned change to exotic blood

**Comment by Kromgar** [comment]
Only took a year to fix it.

I suppose slime people aren't that common
