### ISSUE TITLE
changeling last resort's egg don't work

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#80944]
Reporting client version: 515.1623

## Round ID:
[222128](https://scrubby.melonmesa.com/round/222128)

## Testmerges:
- [tgui now disables topics on world reboot, should fix reconnects randomly failing](https://www.github.com/tgstation/tgstation/pull/80779)

## Reproduction:
be slug, bite corpse, die
the egg gets placed into chest but you're never revived
forcing the egg to pop via vv makes the ling into a monkey in debug room

**Comment by Time-Green** [comment]
Fixed in #80916
