### ISSUE TITLE
Radiation Storms / Radiation Nebula seem to cause client crashes during transitions

### ISSUE THREAD

**Issue by Higgin** [tgstation/tgstation#80945]
## Issue Summary
When a radstorm is announced and starts up, or starts to 'cool down' and disappear, multiple people in-round reported and experienced client crashes. Not sure what the exact cause is - some people didn't report crashing, some people who crashed were on stable, some on beta. I'm on the latest beta as of this and the previous round reported. It happened in both.

## Round ID: [22131](https://scrubby.melonmesa.com/round/22131), 22132

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [222132](https://scrubby.melonmesa.com/round/222132)
BYOND Version: 515.1626
Server revision compiled on: 
Master commit: [548cad95963dbdbd0dfe2d640b520d12e31cc703](https://www.github.com/tgstation/tgstation/commit/548cad95963dbdbd0dfe2d640b520d12e31cc703)
The following pull requests are currently test merged:
[#80887: 'Refactors pod launcher UI' by jlsnow301 at commit 8f1cb908b5](https://www.github.com/tgstation/tgstation/pull/80887)

Local commit: dd5367207e766d4a7852ed0696487a40084bc3a5
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 1
Allow Latejoin Antagonists: 1

## Testmerges:

The following pull requests are currently test merged:
[#80887: 'Refactors pod launcher UI' by jlsnow301 at commit 8f1cb908b5](https://www.github.com/tgstation/tgstation/pull/80887)

## Reproduction:

1. experience radstorm (either from the nebula station trait or from the event)
2. crash after the announcement, then again when the announcement of an end to the event fires

**Comment by Time-Green** [comment]
Probably the overlays adds are crashing clients? I don't really understand why this breaks

**Comment by Drulikar** [comment]
Might be worth retesting on 515.1627, but I don't know if the fix is purely client side or if it has a server component to it.

**Comment by MrStonedOne** [comment]
Upstream tracking ids:

[id:2908156](https://www.byond.com/forum/post/2908156) (515.1625, 515.1626)
[id:2909026](https://www.byond.com/forum/post/2909026) (515.1676)

**Comment by ZephyrTFA** [comment]
Status: | Resolved (515.1628)
