### ISSUE TITLE
Cyborg inducer doesn't respect cell changes

### ISSUE THREAD

**Issue by zkxs** [tgstation/tgstation#80956]
## Issue Summary

When an engineering cyborg with an inducer has its cell upgraded, the inducer doesn't update to reference the new cell. It instead references the old cell, which is no longer in the cyborg.

## Round ID & Testmerges:

```
Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [222187](https://scrubby.melonmesa.com/round/222187)
BYOND Version: 515.1626
Server revision compiled on: 
Master commit: [be9924d85de31f738159f5fbe4b502330dbca36c](https://www.github.com/tgstation/tgstation/commit/be9924d85de31f738159f5fbe4b502330dbca36c)
The following pull requests are currently test merged:
[#80887: 'Refactors pod launcher UI' by jlsnow301 at commit 8f1cb908b5](https://www.github.com/tgstation/tgstation/pull/80887)

Local commit: 9a40792bd7b6406d51bef2bc8de936c86139b545
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 1
Allow Latejoin Antagonists: 1
```

## Reproduction:

1. Install inducer into cyborg
2. Replace the cyborg's cell
3. Note that the old cell is still "inside" the inducer. This renders the inducer useless once the old cell is emptied.
4. For bonus points, put the old cell in a cell charger. The cyborg can now inducer itself to recharge forever. This is broken.

**Comment by Kitfox88** [comment]
> For bonus points, put the old cell in a cell charger. The cyborg can now inducer itself to recharge forever. This is broken.

something something bluespace something wireless energy something lore friendly
