### ISSUE TITLE
NumberInput autoselect is broken

### ISSUE THREAD

**Issue by RikuLeinonenVuoksi** [tgstation/tgstation#80969]
## Issue Summary

Likely suspect is the react refactor causing issues with NumberInput.

Clicking on the temperature (and likely any other number) won't highlight the number in blue.
This means you have to manually highlight the number before you can type in what you want.

## Reproduction:

1. Click on a number input in the reaction chamber UI.
2. It doesn't get highlighted automatically.

**Comment by SyncIt21** [comment]
Nope, not my problem. It's a general issue with textboxes which was likely caused by the react refactor. 
Same problem occurs with plumbing reaction chamber.
@jlsnow301 thoughts?

**Comment by RikuLeinonenVuoksi** [comment]
> Nope, not my problem. It's a general issue with NumberInput which was likely caused by the react refactor. Same problem occurs with plumbing reaction chamber, when you try to edit the ph, temps there Edit your Issue to specify that @jlsnow301 thoughts?

Guh, that's so much worse. Hope this gets fixed quick because it's really, really annoying.

**Comment by SyncIt21** [comment]
Edit your issue title as well to reflect the body.

**Comment by RikuLeinonenVuoksi** [comment]
wrong acc lmao
