### ISSUE TITLE
NumberInput autoselect is broken

### ISSUE THREAD

**Issue by RikuTheKiller** [tgstation/tgstation#80971]
## Issue Summary

Due to the react change, NumberInputs no longer have their number autoselected when you click on them.

@SyncIt21 @jlsnow301 new issue on my actual acc.

## Reproduction:

Just click any NumberInput like the temperature on a reaction chamber and observe the lack of autoselect.

**Comment by scriptis** [comment]
taking a stab at this along with refactoring `NumberInput` and `AnimatedNumber` to functional components
