### ISSUE TITLE
northstar lacks bluespace gas vendors, and atmos lacks gas sender

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#80988]
Reporting client version: 515.1623

## Round ID:
[222341](https://scrubby.melonmesa.com/round/222341)

## Testmerges:
- [Bumps rust-g to `3.1.0`](https://www.github.com/tgstation/tgstation/pull/80955)
- [Wait 10s in TGS build for ESBuild to exit](https://www.github.com/tgstation/tgstation/pull/80958)

## Reproduction:
need gas sender in atmos, plus there are only 2 vendors outside atmos

**Comment by DaxDupont** [comment]
People actually use these?

**Comment by DATA-xPUNGED** [comment]
> People actually use these?

I have never seen anyone use these at all

**Comment by Cheshify** [comment]
Oh fuck I had no idea this was an issue, will add
