### ISSUE TITLE
the "blob zombie infestation" wizard event causes a catastrophic, thermonuclear eruption of chat spam+audio pings

### ISSUE THREAD

**Issue by nianjiilical** [tgstation/tgstation#80998]
remember when we improved the ghost role selection so that it makes a ping noise and puts a box in chat (#80283)

the wizard event that offers up every single corpse on all z-levels as a blob zombie results in that system ass blasting ghostchat/admins with billions of BRRRRRRRRRRRRRRRRBRBRBRRRBRBRRRIIING noises

help

(i know this is a low effort issue but its more of an oversight than a bug)

**Comment by Rhials** [comment]
Hey so, this isn't actually fixed. It didn't occur to me that blob spores all use different mob identifiers, so the fix implemented here doesn't actually cover this specific use case. Dang.
