### ISSUE TITLE
Bounty Pad and Console started unlinked, making the latter's buttons "inactive"

### ISSUE THREAD

**Issue by Justice12354** [tgstation/tgstation#81028]
Reporting client version: 515.1623

## Issue Summary
The Bounty Pad and the Bounty Console started the round unlinked. Attempting to use the buttons on the Console's TGUI did not do anything, including the "Eject ID" button, despite the UI being accessible.
Relinking the Pad and the Console with a multitool made the UI usable again.

## Round ID:
[222498](https://scrubby.melonmesa.com/round/222498)

## Testmerges:
- [Bumps rust-g to `3.1.0`](https://www.github.com/tgstation/tgstation/pull/80955)
- [Wait 10s in TGS build for ESBuild to exit](https://www.github.com/tgstation/tgstation/pull/80958)

**Comment by MrMelbert** [comment]
Computer starts linked on latest master
