### ISSUE TITLE
Infinite Oatmeal (or how I learned to love bluespace)

### ISSUE THREAD

**Issue by ButterChugger** [tgstation/tgstation#81038]
## Issue Summary

Attempting to cook oatmeal invokes strange and wrathful presences that are unheard of in the likes of god fearing cooks.

Cooking oatmeal causes it to infinitely boil oatmeal in the pot, generating an amount that eventually will exceed the capacity of the pot then in some strange act of ungodly power, remove the oatmeal in it's entirety or bring it down to a random amount below 10 u in the pot without overflow.

## Round ID:
Multiple, still ongoing

## Testmerges:
Don't quite know, been going on for two months now.

## Reproduction:

1. Get yer oats.
2. Get yer millk.
3. Mix yer oats and milk in the sacred stew pot of feeding spacemen.
4. Incant the ritual of good cooka-ing and ignite the stovetop burners
5. Wait.
6. Watch as your oatmeal begins to rapidly rise above 100 u's. Frantically scoop out a bit with a ladle into a bowl and watch it continue to go.
7. Oatmeal becomes an integer singularity and deletes itself if left alone in the pot without boil overflow

As a side bonus any oatmeal scooped out in the process of this will also infinitely boil and mix in it's own bowl, randomly switching it's reagents while spamming the boiling noise. If you time it right, you can get on average 4 to 9(!) bowls of oatmeal from one pot.  I've found out that getting multiple bowls of the stuff and letting the barkeep bask in the boiling oatmeal vaporwave noises is a fantastic way to get the bartender to volunteer you to be used as target practice.

**Comment by Profakos** [comment]
Does this only happen with oatmeal, or does it happen with any other 'soup'?

**Comment by ButterChugger** [comment]
Some soups refuse to cook properly (8 u's soup, more water) but I'll be opening separate bug reports. Oatmeal is the only one that truly breaks reality.
