### ISSUE TITLE
lavaland spawn rates got fucked part 3

### ISSUE THREAD

**Issue by LePiromano** [tgstation/tgstation#81032]
once again the amount of tendrils and megafauna that spawn in lavaland have been multiplied by at least 5, making it virtually impossible to survive, the amount of enemies being spawned by the 30 tendrils present in every single round seed also make the game run worse
how the fuck does this shit keep happening?

**Comment by JohnFulpWillard** [comment]
Thanks for the round ID now we definitely know if this is on master or caused by arcmining

**Comment by LePiromano** [comment]
> Thanks for the round ID now we definitely know if this is on master or caused by arcmining

222523

**Comment by ArcaneMusic** [comment]
No TMs on that round claims scrubby.

**Comment by LePiromano** [comment]
Seemingly fixed itself when arcmining released
