### ISSUE TITLE
Losing your legs cancels out being paraplegic

### ISSUE THREAD

**Issue by Justice12354** [tgstation/tgstation#81059]
Reporting client version: 514.1589

## Issue Summary/Reproduction
Become paraplegic
Lose your legs
Walk freely with no legs

## Round ID:
[222621](https://scrubby.melonmesa.com/round/222621)

## Testmerges:
- [Bumps rust-g to `3.1.0`](https://www.github.com/tgstation/tgstation/pull/80955)
- [Wait 10s in TGS build for ESBuild to exit](https://www.github.com/tgstation/tgstation/pull/80958)

**Comment by SyncIt21** [comment]
Duplicate #80396

**Comment by Jackal-boop** [comment]
this reminds me i need to add peg legs

**Comment by ZephyrTFA** [comment]
duplicate of #80396
