### ISSUE TITLE
You can fill a survival box with ttvs using bread slices (or any other custom food that can fit in a survival box)

### ISSUE THREAD

**Issue by RandomDudeFromTheRim** [tgstation/tgstation#81052]
## Issue Summary
If you store a custom food (or a bread slice) in a survival box and put a deepfried bulky-sized item (for example, a ttv) into it, it will allow you to store said item in the survival box

## Reproduction:
Get bread slice/custom food (custom food can be anything as long as it fits in a survival box, and something already has to be in it (bread slice is exempt from this))
Deepfry your bulky-sized item (for example, ttv WITHOUT tanks (unless you wish to die) and then prepare it (add tanks and trigger))
Put custom food/bread slice in survival box
Put bulky-sized item onto bread slice/custom food
You now have a bulky-sized item in a survival box. What shall you do with it? No idea. A fun idea is a RD modsuit ai filled to the brim with voice-activated maxcaps

This may or may not work, haven't tested in a month

**Comment by ArcaneMusic** [comment]
Labeling needs reproduction since it may not be recent but if true this could get wild

**Comment by PapaMichae1** [comment]
I can reproduce on localhost commit [fee9ff584bcfa3e924203cf9787a56d038396973](https://www.github.com/tgstation/tgstation/commit/fee9ff584bcfa3e924203cf9787a56d038396973)

**Comment by MrMelbert** [comment]
Related: #58008

**Comment by SethLafuente** [comment]
![image](https://github.com/tgstation/tgstation/assets/84478872/6d35ba4e-4f8b-456a-97e5-ad0102ce6213)
Yeah as of right now this 100% works I even put a signaler inside it and it gave a noise so it should even be functional within the small box... terrifying 7 full sized active ttvs in a single box as many as more than 70 possible ttvs in a single duffle bag in a single block

**Comment by RandomDudeFromTheRim** [comment]
> as many as more than 70 possible ttvs in a single duffle bag in a single block
Yeah good luck getting that many valves, but kinda stupid how it is STILL not fixed.

**Comment by SethLafuente** [comment]
> > as many as more than 70 possible ttvs in a single duffle bag in a single block
> 
> Yeah good luck getting that many valves, but kinda stupid how it is STILL not fixed.

a single one in a box is one too many

**Comment by jughu** [comment]
deepfrying was a mistake
