### ISSUE TITLE
Arc Mining machines delete mining points

### ISSUE THREAD

**Issue by Skebulba** [tgstation/tgstation#81057]
Reporting client version: 514.1589

## Issue Summary
The amount of mining points in the boulder refinery and smelter seems to be overwriting itself whenever a new boulder is inserted. This is leading to tens, if not hundreds of thousands of mining points being sent to the void.

## Round ID:
[222612](https://scrubby.melonmesa.com/round/222612)

## Testmerges:
- [Newspapers now use TGUI](https://www.github.com/tgstation/tgstation/pull/80991)

## Reproduction:
Put a boulder into one of the machines and wait for it to finish. Then, look at the points in the machine. Place another boulder in and wait. Look at the points again. They will not have added up, and may even have gone down.

**Comment by ArcaneMusic** [comment]
Found it:
`		points_held = round((points_held + (quantity * possible_mat.points_per_unit)) * MINING_POINT_MACHINE_MULTIPLIER) // put point total here into machine`
Multiplied one parenthesis over 😁 
easy fix
