### ISSUE TITLE
Color changer chems (dont know name i dont do chem) can change colors of ghosts

### ISSUE THREAD

**Issue by Admiral-Gigaton** [tgstation/tgstation#81072]
Reporting client version: 514.1589

## Issue Summary
now i can impersonate admns, and make john security ghost think bob admin is about to say "what the actual fuck do you think you're doing"
![image](https://github.com/tgstation/tgstation/assets/130595499/84d7ecb5-873a-464a-987e-ecee8569c01a)

## Round ID:
[222661](https://scrubby.melonmesa.com/round/222661)

## Testmerges:
- [Newspapers now use TGUI](https://www.github.com/tgstation/tgstation/pull/80991)

**Comment by lessthnthree** [comment]
Are the ghosts made visible to the player when it happens? The coloring of ghosts itself is intentional, I believe. The reagent has a var to color all mobs.
