### ISSUE TITLE
Heretic not being able to use transmutation circle without a living heart

### ISSUE THREAD

**Issue by Maxipat112** [tgstation/tgstation#81074]
Reporting client version: 515.1623

## Issue Summary

Heretic after having his heart replaced to not-living heart is unable to open rituals menu clicking on transmutation circle. Been told that not having a heart was meant to only lock you out of tracking and sacrificing targets, yet it seems to nuke entire rituals menu.

## Round ID:
[222662](https://scrubby.melonmesa.com/round/222662) (doubt it has any impact)

## Testmerges:
- [Bumps rust-g to `3.1.0`](https://www.github.com/tgstation/tgstation/pull/80955)
- [Wait 10s in TGS build for ESBuild to exit](https://www.github.com/tgstation/tgstation/pull/80958)

## Reproduction:

1. Have a transmutation circle.
2. Replace your heart with a different non-heretic heart. (in this case, once replaced by VV dropdown "modify organs" to normal human heart AND second time with miner's cursed heart item)
3. TGUI menu with rituals list is unable to be opened.

**Comment by MrMelbert** [comment]
Cannot seem to reproduce on latest master 

![image](https://github.com/tgstation/tgstation/assets/51863163/765d1700-500d-4cd0-9ac3-bef520ed02ff)
