### ISSUE TITLE
Gondolas don't leave corpses behind when killed, making Geneticists sad.

### ISSUE THREAD

**Issue by Bibarra** [tgstation/tgstation#81070]
## Issue Summary
Gondolas don't leave a corpse, but will drop their meat and hide immediately on death. This means that you cannot butcher them for more meat (they only leave one slab) nor can you use them for genetic infusion.

## Round ID:
[222654](https://scrubby.melonmesa.com/round/222654)

## Testmerges:
[#80991: 'Newspapers now use TGUI' by JohnFulpWillard at commit 725d500a22](https://www.github.com/tgstation/tgstation/pull/80991)

## Reproduction:
Find a Gondola.
Kill it.

**Comment by Jacquerel** [comment]
I am reasonably certain that this is not a bug and how they have always acted, the meat IS what you use for the infusion.

**Comment by Jacquerel** [comment]
See: https://github.com/tgstation/tgstation/pull/73796
