### ISSUE TITLE
Poor logging of a combat event

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#81098]
Reporting client version: 514.1589

## Round ID:
[222727](https://scrubby.melonmesa.com/round/222727)

## Testmerges:
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)

## Reproduction:

```
[2024-01-24 19:52:36.155] ATTACK: Thekillerchef/(Chadwick Nelson) (mob_4307) has been shot by  with the bolt (Central Primary Hallway (92,145,2))
```

Not really sure what this means, i don't find any adjacent cause of "a bolt" in the combat logs, the firer seems missing, there's not even a damage mark on this line to tell if it did anything?

**Comment by iprice** [comment]
Based on some grep work, there's a few places that fire 'bolts' like the e-bow, but they all tend to log NEWHP and stuff.

Given the lack of ckey I'm beginning to suspect its actually hallucination derived from here

code/modules/hallucination/stray_bullet.dm:     name = "bolt"

I'm not sure if there's some way this could be made clearer if it is the case, or if i'm simply wrong in my speculations here?

**Comment by LemonInTheDark** [comment]
![image](https://github.com/tgstation/tgstation/assets/58055496/cb7f7b1c-763c-4114-82ce-73a6e310dbd2)
checks out
