### ISSUE TITLE
Heretic's transmutation rune seems to be unusable most of the time

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#81095]
Reporting client version: 515.1623

## Round ID:
[222720](https://scrubby.melonmesa.com/round/222720)

## Testmerges:
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)

## Reproduction:
You can click it on it, but it doesn't bring up the menu. One heretic was able to use the rune only by opening an airlock above the rune for some reason? Very inconsistent

**Comment by MrMelbert** [comment]
Likely related to #81074 in some way, but I cannot reproduce this on latest master

**Comment by Time-Green** [comment]
Is it possible anothet heretic interacted with it? I’ve ran into some weirdness with that before

**Comment by Striders13** [comment]
> Is it possible anothet heretic interacted with it? I’ve ran into some weirdness with that before

I drew my own rune in the same round and was unable to interact with it at all

**Comment by Striders13** [comment]
Just happened again in 22288. Heretic drew a rune and was completely unable to use it, had to go to a different rune.

**Comment by mc-oofert** [comment]
I don't know if I remember correctly but the actual tile of the rune is the bottomleft corner

**Comment by MrMelbert** [comment]
The other issue helped highlight the issue... kinda.

I think it has something to do with backing the bottom of it to the side of a wall. But also not always. 

![image](https://github.com/tgstation/tgstation/assets/51863163/fcfe3e3a-d3e6-4177-ae4c-3cb581eb75e4)

**Comment by MrMelbert** [comment]
Oookay. 

![image](https://github.com/tgstation/tgstation/assets/51863163/1152ed5d-7f10-47dd-a335-e29f5b1dc8ac)
