### ISSUE TITLE
Material Sheets are sometimes rejected?

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#81109]
Reporting client version: 515.1630

## Issue Summary
Materials ejected from a department techfab are sometimes rejected when you try to put them back into the ore silo/an autolathe. If you remove one sheet from the stack, that one sheet can be put back, but the rest still cannot.
![image](https://github.com/tgstation/tgstation/assets/44104681/f4ce184b-b670-47c0-83d5-e57fe80d358d)
I cannot *consistently* reproduce this. I am not doing anything special I am aware of, this just seems to happen sometimes. I've noticed it in several rounds now, with... at least glass and iron, off the top of my head. I do not have the round ID for the other times I've seen it; the whole point of joining the round linked to this issue was because I realized no one had reported it. (as far as I could find, anyway)

## Round ID:
[222783](https://scrubby.melonmesa.com/round/222783)

## Testmerges:
- [Newspapers now use TGUI](https://www.github.com/tgstation/tgstation/pull/80991)
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)

## Reproduction:
Eject materials from a techfab/protolathe.
Try to put them back in.

**Comment by Kitfox88** [comment]
I can't reproduce it either but I can say it's happened to me as well as an engiborg trying to put stuff back in with the material apparatus.

**Comment by Iajret** [comment]
Figured a bit about this strange bug. Sometimes sheets of material come without some of the vars

![image](https://github.com/tgstation/tgstation/assets/8430839/8de762f2-38e2-4116-a429-d2533344fb96)

Glass is the one container that gets rejected. No runtimes though. Cant quite understand why it happens, but I have a feeling, it is related to ArcMining.

**Comment by Iajret** [comment]
https://github.com/tgstation/tgstation/pull/81015

I think, bug appeared after this PR.
