### ISSUE TITLE
Lathe searching pain. Swallowed letters, missing results.

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#81132]
## Issue Summary

If you change something in a search bar, while the item list is loading, it can swallow letters
This messes up the result, unless you type very slowly.
For instance, when trying to type in "capacitor".

Some results do not show up at random (?) or unless you match something specific in their name.

## Round ID:
persistant, last at the time of writing this:
222891

## Testmerges:
[#81089: 'Temp keybinds patch for 515.1628' by MrStonedOne at commit 45649ea7a5](https://www.github.com/tgstation/tgstation/pull/81089)

## Reproduction:

1. (trying to type capacitor but it started loading in the middle)
![obraz](https://github.com/tgstation/tgstation/assets/68878861/db69e0fb-510c-4602-b637-244b497ddc84)
![obraz](https://github.com/tgstation/tgstation/assets/68878861/c924b9f1-e7e7-4543-9b3c-fe506211d079)
![obraz](https://github.com/tgstation/tgstation/assets/68878861/62ecad19-74ac-4e80-b045-a62ecf3dc059)

2.
![obraz](https://github.com/tgstation/tgstation/assets/68878861/f274a463-0a29-40b8-85d4-531561f58d49)
![obraz](https://github.com/tgstation/tgstation/assets/68878861/f09945a6-7d6b-43cc-9f0a-41a1455637bc)

**Comment by SyncIt21** [comment]
Duplicate #80853.

**Comment by Inari-Whitebear** [comment]
Not a complete duplicate.

The missing results seem to happen sometimes when list size changes.
Like if you have a 2 item result and then search for something else that would have 5 items as a result, it can end up just showing the first 2 items.
My usual fix to that is to click All designs which clears everything and then search again. But the laggy input makes that extra annoying too
