### ISSUE TITLE
Imaginary Friend spawned without being attached to a person

### ISSUE THREAD

**Issue by DATA-xPUNGED** [tgstation/tgstation#81138]
## Issue Summary

I joined in as an imaginary friend and i spawned somewhere in maints, completely unable to move or do anything, this is what showed in the chat, too, which seems odd:
`Ghost Poll: DATAxPUNGED was selected for the role (Wayne Lemire's imaginary friend).
You are the imaginary friend of !
You are absolutely loyal to your friend, no matter what.
You cannot directly influence the world around you, but you can see what  cannot.`

## Round ID:

[222925](https://scrubby.melonmesa.com/round/222925)

## Testmerges:

[#80991: 'Newspapers now use TGUI' by JohnFulpWillard at commit 725d500a22](https://www.github.com/tgstation/tgstation/pull/80991)
[#81089: 'Temp keybinds patch for 515.1628' by MrStonedOne at commit 45649ea7a5](https://www.github.com/tgstation/tgstation/pull/81089)

## Reproduction:

- Sign up for imaginary friend?

**Comment by RandomDudeFromTheRim** [comment]
There is someone in the walls
