### ISSUE TITLE
Using Ghetto Tools For Revival Surgery Isn't Working

### ISSUE THREAD

**Issue by TagGamerGang22** [tgstation/tgstation#81142]
Reporting client version: 515.1630

## Issue Summary

I attempted to do ghetto revival surgery and got to the 'cut through bone' step. According to the wiki the butchers cleaver has a 25% chance of attempting a ghetto surgery however I did it 25-30 times and failed every single time. So I believe using it is bugged. Possibly other ghetto tools are bugged but i've only tried the butchers cleaver.
![image](https://github.com/tgstation/tgstation/assets/147560041/872ae9fd-fe50-4c2f-a2ea-75438f10db32)

## Testmerges:
- [Newspapers now use TGUI](https://www.github.com/tgstation/tgstation/pull/80991)
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)

## Reproduction:

1. Do revival surgery
2. Get to the saw bone step
3. Attempt to use butchers cleaver
4. Fail 30 times

**Comment by RandomDudeFromTheRim** [comment]
Is this what people mean when they say that they are big boned?

**Comment by Higgin** [comment]
```	
var/implement_speed_mod = 1
	if(implement_type) //this means it isn't a require hand or any item step.
		implement_speed_mod = implements[implement_type] / 100.0

speed_mod /= (get_location_modifier(target) * (1 + surgery.speed_modifier) * implement_speed_mod) * target.mob_surgery_speed_mod
	var/modded_time = time * speed_mod


fail_prob = min(max(0, modded_time - (time * SURGERY_SLOWDOWN_CAP_MULTIPLIER)),99) //if modded_time > time * modifier, then fail_prob = modded_time - time*modifier. starts at 0, caps at 99
modded_time = min(modded_time, time * SURGERY_SLOWDOWN_CAP_MULTIPLIER)//also if that, then cap modded_time at time*modifier
```

unfortunately this is probably working as intended. 

for an example - 

the bone saw step has a time of 54 deciseconds
the cleaver has a value of 25/100, or a .25 implement_speed_mod
this means that if calculating speed_mod, you've got 1/.25 assuming no other variables are different - or a speed_mod of 4.
this makes modded_time 4 * 54, or 216 - about twenty-two seconds.
SURGERY_SLOWDOWN_CAP_MULTIPLIER is 2
fail_prob then ends up being the smaller of 99 or 216 - 54(2),
216-108, gives you 108, which is larger than 99, so gives you a 1% chance to succeed by default, the bare minimum.

arguably an oversight, but we'll see
