### ISSUE TITLE
You cannot tap a patients knee with a claw hammer

### ISSUE THREAD

**Issue by rageguy505** [tgstation/tgstation#81144]
Reporting client version: 515.1623

## Issue Summary
you cant use a claw hammer to test brain health. Probably a oversight since who ever uses this or knows it exists.

## Round ID:
[222939](https://scrubby.melonmesa.com/round/222939)

## Testmerges:
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)

## Reproduction:
get a /obj/item/crowbar/hammer and right click on someones leg, you hit them instead.

**Comment by LemonInTheDark** [comment]
Not a bug, go make a feature pr you nerd
