### ISSUE TITLE
Minebot shoot-through pka mod does not function at all since minebot's conversion to a basicmob

### ISSUE THREAD

**Issue by Xkallubar** [tgstation/tgstation#81141]
## Issue Summary

 You can still shoot minebots with the minebot shoot-through pka mod.

## Round ID: 
Not applicable

**Comment by Admiral-Gigaton** [comment]
do you apply the mod to the PKA or the bot? it never works when i use it :(

**Comment by Xkallubar** [comment]
> do you apply the mod to the PKA or the bot? it never works when i use it (this was before basic mod-enning)

You can apply it to both but it doesn't work on either

**Comment by JohnFulpWillard** [comment]
Closed by https://github.com/tgstation/tgstation/pull/81940
