### ISSUE TITLE
Anomaly Bioscrambler Reactive Armor causes PERMANENT, unfixable blindless

### ISSUE THREAD

**Issue by githubuser4141** [tgstation/tgstation#81186]
## Issue Summary

The bioactive reacitve naomaly armour does a diceroll that has the chance of people nearby developing blindness that can't be cured.
Cures tried:
Replacing eyes - impossible, eyes could not be retrieved from head OR put in head
Monkeying + Mutadone
HARS + Mutadone
Replacing eyes after HARS + Monkeying - failure, replaced eyes and was still blind

Randomly gained eyesight about 10-15 minutes later (???)

## Testmerges:

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [223057](https://scrubby.melonmesa.com/round/223057)
BYOND Version: 515.1626
Server revision compiled on: 
Master commit: [c817b2c1893fd70e9d7ff76712e782cdbec546dd](https://www.github.com/tgstation/tgstation/commit/c817b2c1893fd70e9d7ff76712e782cdbec546dd)
The following pull requests are currently test merged:
[#81089: 'Temp keybinds patch for 515.1628' by MrStonedOne at commit 45649ea7a5](https://www.github.com/tgstation/tgstation/pull/81089)
[#81097: 'Kicks Martial Arts out of the attack chain (yippee), makes it use signals, plus a large clean up of existing martial arts' by MrMelbert at commit 1d0fb33933](https://www.github.com/tgstation/tgstation/pull/81097)

Local commit: c26c3b488efa23b4101fe714b73ef4f823092186
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 1
Allow Latejoin Antagonists: 1

## Reproduction:

1. Use a bioscrambler reactive armor.
2. Get someone to disarm/hit you a few times
3. Repeat #2 until people complain about being blind
4. Profit achieved - several people are essentially round removed

**Comment by newfren** [comment]
possibly psyker eyes? do they have unique eye organs that force blindness?

I have in the past cured this with xenobio regenerative extracts

**Comment by Admiral-Gigaton** [comment]
wait, what? i didnt know the bioscrambler armor worked like that, what else does it do?

**Comment by Admiral-Gigaton** [comment]
ok after a recent shift i had where i encountered a corpse with bio armor, and accidentally triggered it, its possible you got morphed into some weird fuck up with species and organs. i got the headless persons eyes, which made me completely blind, put a button on my HUD that did nothing but was labeled "switch to head view" and had to ahelp it.

or you just got fucked particularly hard

**Comment by newfren** [comment]
dullahan eyes I think

**Comment by Sadboysuss** [comment]
This is a bug with dulahans, not bioscrambler armor
