### ISSUE TITLE
The dangerous old crusher cannot be unwrenched

### ISSUE THREAD

**Issue by Justice12354** [tgstation/tgstation#81205]
Reporting client version: 515.1630

## Issue Summary
The dangerous old crusher cannot be unwrenched, making it impossible to rotate or move it. When you try to rotate it, it says "needs to unwrench!", so it looks like you should be able to unwrench it at least...

The other recyclers (recycler and lumbermill saw) can be unwrenched just fine

## Round ID:
[223120](https://scrubby.melonmesa.com/round/223120)

**Comment by Higgin** [comment]
The deathtrap version has the NO_DECONSTRUCTION flag which prevents unfastening to move it around. I'm guessing this is in part to both make it harder to cheese by deconstructing it and to prevent dragging it around to use as a weapon. Not sure if actually a bug.
