### ISSUE TITLE
Mining cyborg's mining scanner turns off on unequip

### ISSUE THREAD

**Issue by honkpocket** [tgstation/tgstation#81207]
https://github.com/tgstation/tgstation/assets/77534246/e2d6c7d7-0374-4dd5-acac-135bfa3b2008

![Code_3En3Z7x4fq](https://github.com/tgstation/tgstation/assets/77534246/3dd14d86-fb6f-42f4-8060-91738bd5dac1)

`code\game\objects\items\devices\scanners\t_scanner.dm`

**Comment by dragomagol** [comment]
Not a bug, that's the functionality of the module,

**Comment by dragomagol** [comment]
Oh I see, it spawns in enabled. It turning off when it goes back into your storage makes sense to me (I think welders do this too?) but it should definitely be one way or the other

**Comment by dragomagol** [comment]
@ArcaneMusic

**Comment by Kitfox88** [comment]
Still happening, still irritating as hell to waste a module slot on.
