### ISSUE TITLE
Lathes not printing multiple items correctly

### ISSUE THREAD

**Issue by the-orange-cow** [tgstation/tgstation#81236]
Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [223218](https://scrubby.melonmesa.com/round/223218)
BYOND Version: 515.1626
Server revision compiled on: 
Master commit: [943f38bf7c5f9c048cc785deb0c537d57ee6ba77](https://www.github.com/tgstation/tgstation/commit/943f38bf7c5f9c048cc785deb0c537d57ee6ba77)
The following pull requests are currently test merged:
[#81089: 'Temp keybinds patch for 515.1628' by MrStonedOne at commit 45649ea7a5](https://www.github.com/tgstation/tgstation/pull/81089)
[#81120: 'Comprehensive cleanup of storage datum, replaces the weakrefs with just refs (because they were managed already)' by MrMelbert at commit bb98f3e02a](https://www.github.com/tgstation/tgstation/pull/81120)

Local commit: 97bde235abf11a67c68b2db76a092a0d613bcbd1
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

I tried to print 5 large beakers at the service lathe, and it only printed 1.  There were sufficient materials.  It was the same whether I set the custom amount to 5, or I hit the button that said x5.

**Comment by Inari-Whitebear** [comment]
God this is so annoying, how are we making lathes worse all the time :P
