### ISSUE TITLE
Plant bags are set to only pick up one item per click by default

### ISSUE THREAD

**Issue by the-orange-cow** [tgstation/tgstation#81237]
Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: 223218
BYOND Version: 515.1626
Server revision compiled on: 
Master commit: [943f38bf7c5f9c048cc785deb0c537d57ee6ba77](https://www.github.com/tgstation/tgstation/commit/943f38bf7c5f9c048cc785deb0c537d57ee6ba77)
The following pull requests are currently test merged:
[#81089: 'Temp keybinds patch for 515.1628' by MrStonedOne at commit 45649ea7a5](https://www.github.com/tgstation/tgstation/pull/81089)
[#81120: 'Comprehensive cleanup of storage datum, replaces the weakrefs with just refs (because they were managed already)' by MrMelbert at commit bb98f3e02a](https://www.github.com/tgstation/tgstation/pull/81120)

Local commit: 97bde235abf11a67c68b2db76a092a0d613bcbd1
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

Up until very very recently, plant bags would pick up everything on the tile that was clicked on by default.  Now they pick up one item at a time by default.  Clicking on a ready to harvest hydroponics tray still picks up all of the yield.

**Comment by MrMelbert** [comment]
https://github.com/tgstation/tgstation/pull/81120/commits/b8d1084e2392e01b44087d638dd6fd8f84ee8d8a I think. 

Default collection mode is `COLLECT_ONE`, but it has always been `COLLECT_ONE`, I didn't change it in this PR, which leads me to believe *something* was broken before, and in my code cleanup I accidentally revealed a bug, but I don't know what that was exactly.
