### ISSUE TITLE
Autolathes break when you attempt to construct anything with a custom material

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#81247]
## Issue Summary

Attempting to construct something which uses custom materials, such as a toolbox, will break the autolathe. It appears to not recognize the existence of that material and enters a permanent, endless loop until the autolathe is reconstructed.

**Comment by SyncIt21** [comment]
Duplicate #81192

**Comment by necromanceranne** [comment]
oops somehow I missed that
