### ISSUE TITLE
Okay a whole lot of things lack proper sanity checks for alt-clicking

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#81242]
## Issue Summary

- Tape recorder (partially)
- Autolathe
- Pillow
- Ethereal Disco Ball
- Health Assembly
- Medical roller bed
- Toilet Bong
- Cigarette boxes
- Wrapping Paper
- Medical Mesh (partially0
- Cyborg organ storage
- Cyborg apparatuses in general
- Borg Hypospray
- Rapid Wiring Device
- Plumbing Device
- Electrolyzer (partially)
- Thermomachine (partially)
- Universal Scanner
- Glasses / Debug glasses
- Inspector Gadget fedora
- Animal mask
- Bandanas (partially)
- Neck ties
- Uniforms (partially)
- Hotel door (partially)
- Goliath Cloak (partially) 
- Clipboard
- Papercutter (partially)
- Bow (partially)
- Chem mass spectrometer (partially)
- Chem reaction tester (though this is debug, so it doesn't really matter)
- Portable chem mixer (partially)
- Mortar (partially)
- Syrup bottle
- Coffee cup
- Water bottle
- Sales Tagger
- Destructive Analyzer
- Tram remote assemblies
- Tram crossing signals

**Comment by DATA-xPUNGED** [comment]
What do you mean by sanity check, by the way? Just curious

**Comment by MrMelbert** [comment]
> What do you mean by sanity check, by the way? Just curious

- Check that the mob is in range
- Check that the mob is a valid mob (Humans, generally)
- Check that the mob is not dead, or otherwise incapapicated (handcuffed, stunned, or in crit)
