### ISSUE TITLE
Attacking mechs with melee weapons from various directions does not modify their armor.

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#81260]
## Issue Summary

Mechs do not use facing to determine armor variance against melee weapons. It only checks for ``run_atom_armor`` with a facing in the ``bullet_act()`` proc.

This was not true prior to this PR https://github.com/tgstation/tgstation/pull/65375

And was only fixed for projectiles in this pr https://github.com/tgstation/tgstation/pull/67411

## Reproduction:

Step 1: Spawn in a mech with, like, melee armor. Let's maybe var edit it to 50 melee armor for ease.

Step 2: Get a melee weapon without a demolition modifier. Let's make it 10 force for ease, as above.

Step 3: Hit the mech, and check its integrity. 

You'll discover that, when you smack the mech from any direction, it does not alter the damage dealt except by the standard value of the armor (so, 50%, therefore 5 damage)

**Comment by MrMelbert** [comment]
This means https://github.com/tgstation/tgstation/blob/master/code/modules/unit_tests/mecha_damage.dm may be wrong in some way? It unit tests that melee damage is affected by armor, so if it's actually wrong, the test may be wrong.

**Comment by necromanceranne** [comment]
It only checks attacks from the east as far as I can tell, so I suspect it needs to be expanded.

**Comment by githubuser4141** [comment]
Did mechs ever check for directionals facing item attacks? I remember messing with mechs in sandbox prior to even 2020 vehicle mechs and thought mechs directionals only ever checked for mob (e.g. - goliath) and projectile attacks.

**Comment by necromanceranne** [comment]
It was broken for many years, then broken again during the refactor. There was a brief, brief period before the refactor where it worked because I told someone it was broken.
