### ISSUE TITLE
Ghost hair seems to be completely wrong

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#81261]
## Issue Summary

Your hair while a ghost appears to be the completely wrong color.

## Reproduction:

Hair as a ghost
![green hair ghost](https://github.com/tgstation/tgstation/assets/40847847/6ebaea43-11b7-4a1e-b6f3-329d26075288)

Hair as a living person (cat)
![purple hair cat](https://github.com/tgstation/tgstation/assets/40847847/31ba1d7f-f028-424f-bdab-01ce857c4f5f)

**Comment by LemonInTheDark** [comment]
maybe? a consequence of https://github.com/tgstation/tgstation/pull/81182, though playing with the old code with a bot it seems to behave the exact same way.

The algorithm is take how far away you are from max brightness, multiply it by 0.4, and then add it to your color value
This is kinda dumb tbh, the goal is to "lighten" the hair, but it's sorta shit at that
