### ISSUE TITLE
ethereal disco ball is broken as shit

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#81269]
## Issue Summary

![image](https://github.com/tgstation/tgstation/assets/70376633/ddcbfeca-50fe-4b9e-89d1-d02f4cabeb95)

## Reproduction:

1. turn it on
2. woe

**Comment by LemonInTheDark** [comment]
![image](https://github.com/tgstation/tgstation/assets/58055496/c46052a9-18b4-413e-8240-39f7bd106e8d)
It has no leading # so byond fails to parse it. easy fix

**Comment by LemonInTheDark** [comment]
was this fixed?

**Comment by mc-oofert** [comment]
I swear it was but I don't know if I'm remembering correctly
