### ISSUE TITLE
`/atom/movable/screen/fishing_hud` seems to hard delete consistently 

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#81275]
## Issue Summary

![image](https://github.com/tgstation/tgstation/assets/51863163/39474f5a-798f-4370-9d62-cab68c279aa3)

**Comment by LemonInTheDark** [comment]
Just gonna leave this here
![image](https://github.com/tgstation/tgstation/assets/58055496/483d360f-9d22-468e-b648-e511abcbd651)
![image](https://github.com/tgstation/tgstation/assets/58055496/e66a6889-0e7c-437a-b874-e9d509eb41f2)

**Comment by LemonInTheDark** [comment]
It is cleared, but it doesn't seem like it's done consistently? that or it's some other ref and I'm silly
![image](https://github.com/tgstation/tgstation/assets/58055496/4eff0045-e685-4f58-8380-dba663de6b7c)

**Comment by LemonInTheDark** [comment]
@SmArtKar was this fixed?

**Comment by LemonInTheDark** [comment]
does actually appear to be fixed (I used admin perms to download the month data from https://superset.moth.fans/superset/dashboard/8/?native_filters_key=w1DXAHkEaVQ7idBH2k0LLIk7ficSTNUvl9k4uDiR74td9gnV39_2vtc9jQmP4f8E and check if it's 0 total harddels, and it is.)
