### ISSUE TITLE
Certain Hotkeys + Combos Don't Work On Beta

### ISSUE THREAD

**Issue by Higgin** [tgstation/tgstation#81299]
## Issue Summary

Keybinds using ` and several other combos such as shift, or any combination of shift and other buttons for the Block Movement function do not work.

I use ` as my keybind for block movement and it's terribly annoying. Most of the rest seem to work fine. Suspect it's the beta that we're supposed to be on, but I've gotten this issue on locals without the TM as well. #81089 

## Round ID: 223391

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: 223391
BYOND Version: 515.1626
Server revision compiled on: 
Master commit: [104fcf10fe839718f6cdcab291444210fbcd757f](https://www.github.com/tgstation/tgstation/commit/104fcf10fe839718f6cdcab291444210fbcd757f)

## Testmerges:

The following pull requests are currently test merged:
[#81089: 'Temp keybinds patch for 515.1628' by MrStonedOne at commit 45649ea7a5](https://www.github.com/tgstation/tgstation/pull/81089)
[#81103: 'Fixes ore vents spawning without ores on icebox, sets up map specific ore configurations' by ArcaneMusic at commit 865262f70b](https://www.github.com/tgstation/tgstation/pull/81103)

Local commit: 0d28d69c366dfc04e0bb6fe5dc9160a8e088e130
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

## Reproduction:

Join on latest beta, 515.1626.

Try to set Block Movement hotkey to ` and use it in conjunction with movement keys to change facing.

Be sad.

**Comment by SyncIt21** [comment]
> Join on latest beta, 515.1626.

1630 is the latest version . Does it happen there as well?

**Comment by MrStonedOne** [comment]
>Keybinds using ` and
[Byond bug ID:2909981](https://www.byond.com/forum/post/2909981)

fixed in 1631 (not released yet)


>and several other combos such as shift, or any combination of shift and other buttons for the Block Movement function do not work.

You are going to need to detail this in full, with examples, so we can send byond test cases.

**Comment by Higgin** [comment]
what's a webpage, is that something spiders write on

in seriousness thank you, good to know it's already on the horizon, I'll close this then
