### ISSUE TITLE
Cargo exploration drone UI is STILL broken

### ISSUE THREAD

**Issue by NoodleNoms** [tgstation/tgstation#81297]
Reporting client version: 515.1630

## Issue Summary

The UI for the exploration drones from cargo is very broken and hard to use and some of the buttons just cant be used

## Round ID:
[223373](https://scrubby.melonmesa.com/round/223373)

## Reproduction:
try to use the exploration drone console

**Comment by SyncIt21** [comment]
Duplicate #80636
