### ISSUE TITLE
Unable to do anything ias a ghost when your body is thrown into a chasm

### ISSUE THREAD

**Issue by bigfatbananacyclops** [tgstation/tgstation#81308]
If you go into a chasm, die or whatever, while your body is stuck inside the chasm, you cannot talk, press anything, jump anywhere as a ghost.

I have a video of the reproduction if you need it dm me bigfatbananacyclops

This happened in other several rounds

[Round ID]: #223415

**Comment by SyncIt21** [comment]
> I have a video of the reproduction if you need it dm me bigfatbananacyclops

Just compress the video and post it in the issue body.

**Comment by Admiral-Gigaton** [comment]
before anybody whines about no round ID, or test merges, this has happened in pretty much every round for a decent amount of time now. its even happened to me too (except i forget to make an issue about it on github lol)

this also inhibits your way of ahelping, but you can still ahelp anyways or talk in OOC - "OOC: JohnMcMiner:  i need an admin here, shits really fucked and i cant ahelp" - you gotta press the "having trouble ahelping? click HERE" to ahelp, which not everyone thinks of right away

**Comment by Xkallubar** [comment]
This has happened to me many times

**Comment by TheMidnightRose** [comment]
Still happens. It prevented me from submitting the ticket though, however as long are you return to your (nonexistant) body you can speak and ahelp.

**Comment by moocowswag** [comment]
Its a big death match issue since so many people can fall into the chasms, atleast lavaland is tucked a way for a minority to fall.

**Comment by MrMelbert** [comment]
This seems to be an issue with the verb manager subsystems, investigating further..

**Comment by MrMelbert** [comment]
Seems as if it was caused by #79964 but the issue is deeper than that
