### ISSUE TITLE
launch pads on shuttles dont work

### ISSUE THREAD

**Issue by Blacklist897** [tgstation/tgstation#81314]
Reporting client version: 515.1630

## Issue Summary
some shuttles used by bounty hunters and pirates possess a bluespace launchpad when its attempted to be used it gives the message 
:ERROR: Launchpad not operative. Heavy area shielding makes teleporting impossible. 

## Round ID:
[223439](https://scrubby.melonmesa.com/round/223439)

## Testmerges:
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)
- [Fixes ore vents spawning without ores on icebox, sets up map specific ore configurations](https://www.github.com/tgstation/tgstation/pull/81103)

## Reproduction:
Spawn in as crystal pirates or normal bounty hunters, link your ships launch pad to its console and try to use it

**Comment by Admiral-Gigaton** [comment]
likely an oversight from https://github.com/tgstation/tgstation/pull/79335#issue-1966460136

**Comment by Singul0** [comment]
Looks like the if() check was way more discriminatory. it blocks all shuttles from being able to teleported to. Maybe just the ferry and supply shuttle is fine?
