### ISSUE TITLE
deconverted cultists see the cult icon on other cultists

### ISSUE THREAD

**Issue by celulamp** [tgstation/tgstation#81341]
Reporting client version: 515.1620

## Issue Summary

I drank holy water and got deconverted but I could still see people who were cultists by the icon. 

## Round ID:
223544

## Reproduction:
be a cultist then drink holy water? I got killed revived then fed holy water after, I had my eyes pulled out cus my brain was bashed in. idfk..

**Comment by MrMelbert** [comment]
Dupe of #77530
