### ISSUE TITLE
Lathe APC energy cost makes round start unfairly punishing to medical

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#81366]
Reporting client version: 515.1630

## Round ID:
[223600](https://scrubby.melonmesa.com/round/223600)

## Reproduction:

Medical is a department who don't even get full toolkits on their main jobs (unlike say engineers who just got given free RCDs), every medic needs to print a bunch of items, the rest of medical tend to want to print all the tools, every chemist and doctor wants to print half a dozen or so beakers.

Having just played a round the lathe basically just drained the APC in minutes at round start, there was a queue and a large ammount of frustration over the seemingly "buggy" nature of the lathe.

Getting setup basically required getting a cell charger and swapping out the APC cell, which isn't exactly a very normal medical activity to be doing.

While the energy costs here may just about work in other departments, the fact medical more than any other department lacks their equipement and needs being met at round start puts a huge unsustainable strain on the lathe.

And honestly i dont know why you keep trying to make lathes suck with printing delays, costs, energy costs and so on.  Whatever ends up blocking people significantly from using the lathe is just going to suck at that point in game play.  And if it doesn't block people then whats the point.

**Comment by Deadgebert** [comment]
This shit is absolutely wild. A tier 4 lathe still requires 20% of the base APC cell to print mechanical pincers. I understand the need to add more power requirements, but this shit is NOT it. This is a don't play until it's changed angle.
