### ISSUE TITLE
Multitile airlocks go sideways when they break

### ISSUE THREAD

**Issue by Rhials** [tgstation/tgstation#81406]
## Issue Summary

![image](https://github.com/tgstation/tgstation/assets/28870487/ebb4dbed-0048-401f-91d6-bbc3cc65f936)

Double-airlocks make this really ugly shape when they break.

## Round ID:

Reproduced locally

## Reproduction:

Make double-wide door.

Left click x20.

Whaaaaat???? crazy door.

![image](https://github.com/tgstation/tgstation/assets/28870487/679a01b9-43ca-4929-9841-16cd383e8a6b)

**Comment by LemonInTheDark** [comment]
based?
