### ISSUE TITLE
Blob Zombies Don't Have Blob Spore Heads

### ISSUE THREAD

**Issue by Das15** [tgstation/tgstation#81414]
## Issue Summary

Blob zombies do not have the blob "hats" on their heads, making it impossible to distinguish between zombies and normal humans. The issue started happening around month ago, I'm not exactly sure which PR broke this behavior.

## Round ID:
[223711](https://scrubby.melonmesa.com/round/223711)

## Reproduction:
- Get a corpse
- Get a blob spore to possess a corpse
- Realise its indistinguishable from the non-blob people.

**Comment by cnleth** [comment]
>The issue started happening around month ago, I'm not exactly sure which PR broke this behavior.

It's like this for several months at least. I think it broke in summer, but I'm not sure about that

**Comment by Admiral-Gigaton** [comment]
Spore espionage
