### ISSUE TITLE
psyker vision scanning is very laggy

### ISSUE THREAD

**Issue by Witherael** [tgstation/tgstation#81446]
Reporting client version: 514.1589

## Issue Summary

Psyker vision was incredibly laggy and made me crash multiple times near even slightly object dense locations.

## Round ID:
[223853](https://scrubby.melonmesa.com/round/223853)

## Testmerges:
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)

**Comment by optimumtact** [comment]
i dont really know what we can do to improve this it replaces everything on your screen with a bunch of icons so your client has to render extra stuff.

it's just gonna lag if you have a shit computer.

**Comment by SyncIt21** [comment]
Also why are using 514.1589? The latest version is 514.1560, perhaps that can help with rendering?
