### ISSUE TITLE
Paradox Clone Does Not Inherit Original's TTS Voice

### ISSUE THREAD

**Issue by Higgin** [tgstation/tgstation#81450]
## Issue Summary

paradox clones don't get their original's TTS voice and so get outed in a very quick if also very funny fashion.

## Testmerges:
BYOND Version: 515.1626
Server revision compiled on: 
Master commit: [b6b4f1cf987eaca8f51ee6543db7513a1aacf912](https://www.github.com/tgstation/tgstation/commit/b6b4f1cf987eaca8f51ee6543db7513a1aacf912)
The following pull requests are currently test merged:
[#81089: 'Temp keybinds patch for 515.1628' by MrStonedOne at commit 45649ea7a5](https://www.github.com/tgstation/tgstation/pull/81089)

Local commit: dc6677cc5b10622cbeaaef94294b2cb6203e3aca
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

## Reproduction:

1. spawn pclone
2. have pclone speak
3. pclone has different voice to original
4. pclone despairs

**Comment by Jackal-boop** [comment]
Changlings also don't inherent their genomes voice
