### ISSUE TITLE
Space Cat cannot survive in Space

### ISSUE THREAD

**Issue by Rustybuckets6601** [tgstation/tgstation#81479]
Reporting client version: 515.1630

## Issue Summary
The Space Cat simplemob cannot survive in space, despite its name and cute EVA suit.

## Round ID:
[223959](https://scrubby.melonmesa.com/round/223959)

## Testmerges:
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)
- [A red spy has entered the base: Adds Spies, a roundstart antagonist inspired by Goonstation's Spy-Thief](https://www.github.com/tgstation/tgstation/pull/81231)

## Reproduction:
Become space cat, go to space, notice you are suffocating, die.

**Comment by 00-Steven** [comment]
Old code:
![image](https://github.com/tgstation/tgstation/assets/42909981/c85f119b-c650-496e-92dd-f44fb73a9ac9)
New code after basic pets refactor:
![image](https://github.com/tgstation/tgstation/assets/42909981/8517205a-4141-4fb7-a4cc-e8b60076f675)
It seems like `unsuitable_atmos_damage` was just lost in translation.
Basics do have this value, though:
![image](https://github.com/tgstation/tgstation/assets/42909981/efc0e78a-adeb-4260-8a7b-d48849b371ae)
So should be a simple fix?

**Comment by 00-Steven** [comment]
Implying, I'll look into it after I get some food.

**Comment by Ghommie** [comment]
Cat cannot into space.
