### ISSUE TITLE
Pai can be insterted into the Ore Redemption Machine and get sent to the Ore Silo

### ISSUE THREAD

**Issue by Sightld2** [tgstation/tgstation#81486]
## Issue Summary
Pai cards can be directly inserted into ore drop off and get sent here:
![image](https://github.com/tgstation/tgstation/assets/93492992/eb779e71-8514-4f36-8dfb-d2f1a8aa882b)

## Testmerges:
#81089 
#81231 

## Reproduction:
grab a /obj/item/pai_card of your choice.
Flush your best friend down the Ore Redemption Machine

**Comment by Blacklist897** [comment]
This is nearly as good as the bubblegum bug

**Comment by Singul0** [comment]
Feature

**Comment by Kitfox88** [comment]
> This is nearly as good as the bubblegum bug

it really is

**Comment by moocowswag** [comment]
If pais can do it, i wonder if anything else can.

**Comment by nikothedude** [comment]
an exception should be made for this its just too funny
