### ISSUE TITLE
borg can't state custom laws

### ISSUE THREAD

**Issue by Holoo-1** [tgstation/tgstation#81494]
## Issue Summary
Can't change custom law state status to YES

## Reproduction:
no idea
<details>
  <summary>Click me</summary>

https://github.com/tgstation/tgstation/assets/38228316/43a9f579-4927-4b38-93c3-74771c2e1aa1

</details>

**Comment by necromanceranne** [comment]
Is it possible this is because the master AI had set these laws not to be stated?

**Comment by Sealed101** [comment]
Duplicate of #67998
