### ISSUE TITLE
paraplegic and robotic leg allow you to walk, and can be rolled together via hc random

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#81508]
Reporting client version: 515.1630

## Issue Summary
paraplegic and robotic leg allow you to walk, and can be rolled together via hc random

## Round ID:
[224044](https://scrubby.melonmesa.com/round/224044)

## Testmerges:
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)
- [A red spy has entered the base: Adds Spies, a roundstart antagonist inspired by Goonstation's Spy-Thief](https://www.github.com/tgstation/tgstation/pull/81231)

## Reproduction:
choose hc random
get lucky enough to roll paraplegic and prosthetic limb at the same time, with prosthetic limb choosing one of your legs
walk around (slowly)

**Comment by deathrobotpunch** [comment]
also just putting this here, having the chronic illness perk and paraplegic also does around the same thing allowing you to walk once your leg comes off
