### ISSUE TITLE
BBQ ribs burn in a grill

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#81511]
## Issue Summary
![obraz](https://github.com/tgstation/tgstation/assets/68878861/6ca5e80f-c0a0-4e8a-bce1-00b8d5906ee5)
![obraz](https://github.com/tgstation/tgstation/assets/68878861/084fa776-038c-4b20-8afe-8baf8e4f3283)

## Round ID:
[224060](https://scrubby.melonmesa.com/round/224060)

## Testmerges:
[#81371: 'bindable action buttons' by mc-oofert at commit b8bb7bf46a](https://www.github.com/tgstation/tgstation/pull/81371)

## Reproduction:
- Acquire grill (cargo)
- Put fuel in (coal/monkey energy)
- Put BBQ ribs in (2 rods, 2 steaks, 5u BBQ sauce)
- Wait 20s (minimal grilling time)
- Despair

BBQ ribs are weird. They look raw (?) and wiki text encourages to grill them, which makes sense. But they're made with cooked steaks.
Either way this displeases me.

**Comment by SyncIt21** [comment]
@Time-Green this is more of a feature request because by default food items on grilling give burned messes & BBQ does not override that because we have no grilled version of BBQ

![Screenshot (391)](https://github.com/tgstation/tgstation/assets/110812394/daa8385c-27a1-4dba-8593-b660cd263ecc)

Putting it at high priority is meh.. nobody is starving here for some grilled some ribs you know :)

**Comment by Time-Green** [comment]
> @Time-Green this is more of a feature request because by default food items on grilling give burned messes & BBQ does not override that because we have no grilled version of BBQ
> 
> ![Screenshot (391)](https://private-user-images.githubusercontent.com/110812394/305645186-daa8385c-27a1-4dba-8593-b660cd263ecc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNzg1MjMsIm5iZiI6MTcwODE3ODIyMywicGF0aCI6Ii8xMTA4MTIzOTQvMzA1NjQ1MTg2LWRhYTgzODVjLTI3YTEtNGRiYS04NTkzLWI2NjBjZDI2M2VjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QxMzU3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOWQzNjA0YTgwZjE1NjliNDA3NzllNmViZmUxNGY1MGRjNGViMTY0YzZkN2FiODQwY2I4NWVlYjJlNmI5MWI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ibL0hMDm_JC5vSYaOEAA8yCu7XMpSlJbMLWZaM5QV6Y)
> 
> Putting it at high priority is meh.. nobody here is starving for some grilled some ribs you know :).
> 
> Also good to see you long time

I am starving for grilled ribs, I don’t care which seas need to be parted.

Also this did use to work. Ribs are already cooked, but the BBQ adds grill stripes or something and not turn it to a burned mess.

Also hi, I’m not dead just somewhat inactive. Can’t wait to see when you add General Maintenance

**Comment by SyncIt21** [comment]
> Also hi, I’m not dead just somewhat inactive. Can’t wait to see when you add General Maintenance

I've become a meme, the "General maintainence" guy, in a good way though :)

**Comment by Likteer** [comment]
> we have no grilled version of BBQ

I meant THE grill, not griddle or bonfire grill.
It works like a deep frier and just applies an overlay to anything, including inedible and already cooked stuff.

It might be sharing the condition with griddles though.
