### ISSUE TITLE
Can't examine as pAI

### ISSUE THREAD

**Issue by MIC132** [tgstation/tgstation#8152]
Apparently, you can't examine as a pAI. Not sure if only if you are in a container or at all times.

**Comment by phil235** [comment]
Given that the pAI mob is already inside a container (the pAI card) it's most likely all the time.

**Comment by MIC132** [comment]
Also semi-related, the pAI currently has the access to the hud modes (medical/security) from the get go, without downloading the software, making the software obsolete.

**Comment by MIC132** [comment]
And one more. Turning the Universal Translator module on and off makes you unable to understand anyone without turning it on again.

**Comment by Miauw62** [comment]
yeah these two are separate bugs, please make separate bug reports for them.

**Comment by MIC132** [comment]
Made separate issues for those:
#8167
#8168

**Comment by Miauw62** [comment]
Thank you.

**Comment by phil235** [comment]
Bug looks fixed, pAi can examine even when inside a pda that's in a box inside a backpack on a mob inside a closet.
