### ISSUE TITLE
Mech Drills do not respect proximity during their drilling once it starts, allowing you to drill from an infinite distance. God help you if you're hit with this.

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#81527]
## Issue Summary

When you start drilling something with a mech drill, so long as you face in the direction of the drilling, you will continue to drill the thing you have used the drill on. Even if you move away. There really isn't an upper limit it seems....

## Reproduction:

Step 1: GET IN THE FUCKING MECH
Step 2: Raise your mech drill and use it on...whatever. A chair. A door. A person.
Step 3: Let the drill begin the drilling windup.
Step 4: Move away from the target of the drilling. Use strafe to maintain facing towards the target.

Congratulations, you're now drilling at range. The most terrifying ranged weapon ever conceived.

**Comment by SyncIt21** [comment]
Unable to reproduce in local. What were the circumstances or round ID?

https://github.com/tgstation/tgstation/assets/110812394/5b51db60-8505-4ed4-977b-6558a52f30a7

**Comment by necromanceranne** [comment]
You missed the part which said 'face the same direction'. You need to use strafe. I'll update the reproduction steps.

**Comment by SyncIt21** [comment]
> You missed the part which said 'face the same direction'. You need to use strafe to backpedal. I'll update the reproduction steps.

Lol ok i see what you mean now. That's some good shit
