### ISSUE TITLE
Hearts of Darkness don't actually swap your species when they revive you.

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#81546]
## Issue Summary

When you die with a Heart of Darkness (the nigthmare special heart) inserted in your chest, you don't actually revive as a shadowperson. In fact, you just end up losing your cool heart and revive as normal.

## Round ID: [224173](https://scrubby.melonmesa.com/round/224173)

Just look for my ckey for any relevant runtimes.

## Reproduction:

Step 1: Get a heart of darkness inserted into your chest (probably from eating it)
Step 2: DIE while in darkness
Step 3: Wait a bit before BOOM you're back and you're completely normal.

Most likely, the culprit is this right here
https://github.com/tgstation/tgstation/blob/a45400b388c6257584db16cd96ffd8da3de19340/code/modules/antagonists/nightmare/nightmare_organs.dm#L122

I suspect this is just straight up replacing your heart with one from your old species, because none of the code beneath it seemed to run. No sounds, no spooky effects, nothing.

**Comment by Time-Green** [comment]
Only the brain is supposed to cause a species change. The heart being reppaced with a normal
heart is unintended though

**Comment by necromanceranne** [comment]
https://github.com/tgstation/tgstation/blob/cee3b860412da2a9780a6c778eea819a7dd6be2f/code/modules/antagonists/nightmare/nightmare_organs.dm#L126

Then what is this bit of code doing here? It would only be reached if you're neither a nightmare or a shadowperson.

**Comment by Time-Green** [comment]
Oh wow, I had no idea that was a mechanic

**Comment by 00-Steven** [comment]
Neat!

**Comment by 00-Steven** [comment]
Yeah seems like it cuts off after that line, weird.

**Comment by 00-Steven** [comment]
Right forgot to add context, `revive` calls `fully_heal`, which on carbons with flags set to either `HEAL_ORGANS` or `HEAL_REFRESH_ORGANS` calls `regenerate_organs`, which then in turn calls `regenerate_organs` on the species, which just fucking deletes the nightmare heart before it can do anything else because it's not a part of your original species.
