### ISSUE TITLE
Pizza made from tofu contains dairy anyways and will cause an allergic reaction

### ISSUE THREAD

**Issue by dallaszzz** [tgstation/tgstation#81543]
## Issue Summary
as in the title

## Reproduction:
make pizza dough and click it with tofu

**Comment by xXPawnStarrXx** [comment]
![image](https://github.com/tgstation/tgstation/assets/53197594/07d4d668-d5fe-4e7c-90be-d7108d4e631c)
It seems to force pizzas to be a margherita as base, let me take a closer look.

**Comment by xXPawnStarrXx** [comment]
This should resolve it.
https://github.com/tgstation/tgstation/pull/81683

**Comment by deathrobotpunch** [comment]
close?

**Comment by xXPawnStarrXx** [comment]
I resolved the issue, yeah.
