### ISSUE TITLE
Deathmatch Underground thunderdome chasms fuck up your ability to use UI speak and use Ahelps

### ISSUE THREAD

**Issue by SomeoneYouProbablyKnow** [tgstation/tgstation#81559]
## Issue Summary
If you fall into a chasm in the deathmatch thunderdone tgui and adminhelp all break. its fixed by summoning the person and killing them properly (admins did it a few times). Works consistently

**Comment by Rhials** [comment]
Duplicate of #81559, this is apparently an issue with all chasms
