### ISSUE TITLE
Bottom Floor Ice Box Station Hands Don't Work Bug

### ISSUE THREAD

**Issue by SpiffiestTea** [tgstation/tgstation#81554]
Reporting client version: 515.1630

## Issue Summary

On the bottom floor of Ice Box Station, you cannot select anything on the floor. For instance, to pull something, you have to alt-click, then crtl-click on the "floor" tab on the top right. To pick up anything, you have to alt-click, the click in the same way. 

## Round ID:
[224188](https://scrubby.melonmesa.com/round/224188)

## Testmerges:
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)
- [A red spy has entered the base: Adds Spies, a roundstart antagonist inspired by Goonstation's Spy-Thief](https://www.github.com/tgstation/tgstation/pull/81231)

## Reproduction:

Not much detail to say on this one if I'm honest and I couldn't think of a better title. If you go down to the last floor on Ice Box Station where most of the valuable materials are placed, characters are unable to interact with any items, including doors, alarms, or useful things like regen cores from legion. Weirdly enough, when as a Ghost, you are able to interact with things, like checking the details of an Air Alarm or APC.

**Comment by Livrah** [comment]
This happens after you slip/fall and have meson googles on. re-equip it to fix.

**Comment by Sealed101** [comment]
^
