### ISSUE TITLE
deathmatch preserves ling powers

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#81550]
Reporting client version: 515.1630

## Issue Summary

i should have accounted for this lmao
anyway as a ling you get your powers in deathmatch

## Round ID:
[224179](https://scrubby.melonmesa.com/round/224179)

## Testmerges:
- [bindable action buttons](https://www.github.com/tgstation/tgstation/pull/81371)

## Reproduction:

1. roll ling before playing
2. get cremated cuz valid!!!
3. play deathmatch
4. free powers

**Comment by Time-Green** [comment]
You preserve the mind????

**Comment by mc-oofert** [comment]
> You preserve the mind????

yeah
