### ISSUE TITLE
Necropolis Tendrils spawned directly next to an ore vent, shenanigans ensued.

### ISSUE THREAD

**Issue by Kitfox88** [tgstation/tgstation#81564]
Reporting client version: 515.1630

Two necropolis tendrils were by an ore vent, I cleared them out expecting it to not be affected by the chasms. I was wrong, and it ended up floating on the outermost boundary of one. Oh well, right? Call down the NODE to tap it and... Node falls into chasm. Funny, but problematic. Presumably not a huge one since it was just random luck that they all spawned that close, but figured I should report it.

## Round ID:
[224221](https://scrubby.melonmesa.com/round/224221)

## Testmerges:
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)
- [A red spy has entered the base: Adds Spies, a roundstart antagonist inspired by Goonstation's Spy-Thief](https://www.github.com/tgstation/tgstation/pull/81231)

## Reproduction:

Get (un)lucky with ore vent and tendril spawns close to each other, laugh at poor hardhat bot falling into the depths when he lands.

![poor lad](https://github.com/tgstation/tgstation/assets/16981475/60ebc8cf-fa75-49d7-abdd-b983a995fddd)
![Silly](https://github.com/tgstation/tgstation/assets/16981475/440296c2-5b96-46ae-84ac-d467f8dddf5a)

**Comment by Admiral-Gigaton** [comment]
solution: get rods and cover the chasm

**Comment by ArcaneMusic** [comment]
Absolutely based (I will look into it)
