### ISSUE TITLE
Breath mask not blocking force feeding from Ladles

### ISSUE THREAD

**Issue by Kurzaen** [tgstation/tgstation#81576]
Reporting client version: 515.1630

## Issue Summary

Breath masks don't stop others from being able to feed you, and you can still eat soup with breath masks on, as long as its from the ladle.

## Round ID:
 Round ID was 224258

## Reproduction:

>Wear breathing mask
> Get soup pot filled with liquid
> Get ladle
> Fill ladle with liquid
> Somehow consume ladle liquid through mask

or

>get a 'willing' participant
>they are wearing a breath mask
>with a ladle full of liquid
>feed them the liquid through their mask
>profit.

![bugimage1](https://github.com/tgstation/tgstation/assets/125766963/064eb507-0e2d-4b96-96d8-e85331eb6584)

![bugimage2](https://github.com/tgstation/tgstation/assets/125766963/4ad0c095-92c9-414e-910a-4fc00e2c8159)

![bugimage3](https://github.com/tgstation/tgstation/assets/125766963/49b465bd-a28e-48cc-8980-4d3c5651d8a7)

**Comment by the-orange-cow** [comment]
Obviously you are pouring the soup into the breath mask tube.  Working as intended.
