### ISSUE TITLE
TGUI is borked after falling into a pit during Deathmatch

### ISSUE THREAD

**Issue by Zargoar** [tgstation/tgstation#81578]
Reporting client version: 514.1589

## Issue Summary
After falling into a pit during Deathmatch TGUI gets totally borked.

## Round ID:
[224264](https://scrubby.melonmesa.com/round/224264)

If you discovered this issue from playing tgstation hosted servers:
Manuel.

## Testmerges:
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)
- [A red spy has entered the base: Adds Spies, a roundstart antagonist inspired by Goonstation's Spy-Thief](https://www.github.com/tgstation/tgstation/pull/81231)

## Reproduction:

1. Play a few rounds of deathmatch and win like a chad.
2. Play a few rounds of deathmatch and die :(.
3. Play a round of deathmatch and be thrown into the pit by a conveyor belt.
4. Observe TGUI is BORKED.

**Comment by PapaMichae1** [comment]
duplicate https://github.com/tgstation/tgstation/issues/81308
