### ISSUE TITLE
Deathmatch broke my game

### ISSUE THREAD

**Issue by WarerBrow** [tgstation/tgstation#81574]
Reporting client version: 515.1630

## Issue Summary

Participation in **Deathmatch** minigame broke my game to _completely unplayable state_. UI elements are interactive, but character movement is impossible, in tandem with crazy input lag (press "adminwho" - get response in 10-20 seconds).

## Round ID:
[224256](https://scrubby.melonmesa.com/round/224256)

## Testmerges:
- [bindable action buttons](https://www.github.com/tgstation/tgstation/pull/81371)

## Reproduction:

At the Ice Box Station (Terry), after going straight observing I played a couple of matches of DM (can't remember exact maps, should've been Brig and Ragecage). When I was trying to observe station events after that, game broke, like lagging, freezing and inability to move (as a ghost). UI remained somewhat intact though. I could hover my cursor over buttons, and they would blink, but game screen went dead (part of tiles were seen, part of em were somewhat darkened). 

I waited till rounds end, and went observing before roundstart. Instead of appearing at stations center, I spawned at the Deathmatch Z-level (in empty space). Again - ghost is immovable, heavy input lag on UI elements (25k ping). I was able to orbit ghost spawner though, but issues remained. I tried clearing cache multiple time, will try to reinstall BYOND now, also I joined other server Manuel - everything was OK, game fully playable. Only Terry, where issue occurred, is broken for me. 

https://github.com/tgstation/tgstation/assets/106118256/9a3bcbc7-cf46-47c8-8c62-cb3c6732a3f4

P.S. In the attached video you can see me frantically trying to move my ghost, the input lag and artificial ping (internet atm was exceptionally good).

P.S.S. After BYOND re-installment, issue _still remains_...

**Comment by Admiral-Gigaton** [comment]
Did you fall in a chasm

**Comment by WarerBrow** [comment]
> Did you fall in a chasm
![image](https://github.com/tgstation/tgstation/assets/106118256/f7fe3541-cd4c-462a-b037-4978d3ec73e0)
It seems that joining as a character (Not observer) indeed fixes this. I'm leaving this issue for moderator to close.
