### ISSUE TITLE
Breath temperature does not modify body temperature

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#8161]
Breathing in hot/cold air doesn't impact your body temperature; it just triggers the temperature warnings and displays flavortext messages to convince you of such.

**Comment by phil235** [comment]
9086 fixes point 1 and 2.

**Comment by duncathan** [comment]
This is life code, not atmos code; removing the tag

**Comment by Cyberboss** [comment]
This was fixed right?

**Comment by Cyberboss** [comment]
@lzimann

**Comment by lzimann** [comment]
Seems like it was fixed.
