### ISSUE TITLE
stable cerulean extracts can be used to cure any disease, including that uncurable antag one

### ISSUE THREAD

**Issue by nianjiilical** [tgstation/tgstation#81675]
## Testmerges: 
[#81231: 'A red spy has entered the base: Adds Spies, a roundstart antagonist inspired by Goonstation's Spy-Thief' by MrMelbert at commit 33778691b3](https://www.github.com/tgstation/tgstation/pull/81231)
[#81089: 'Temp keybinds patch for 515.1628' by MrStonedOne at commit 45649ea7a5](https://www.github.com/tgstation/tgstation/pull/81089)
[#81477: 'Comprehensive frame refactor to fix being unable to thwack frames with brute force to break them' by MrMelbert at commit 3149c449ad](https://www.github.com/tgstation/tgstation/pull/81477)

## Reproduction:

1) get a disease
2) use the cerulean stable extract to make a clone of your self that doesnt have the disease
3) unalive yourself (without gibbing or beheading)
4) transfer to the clone
5) no more disease

**Comment by MrMelbert** [comment]
I don't see why this wouldn't cure the disease, it's an entirely new mob

**Comment by moocowswag** [comment]
its meant to be a clone of you so maybe it should copy the exact current state of you when its made?

Otherwise it seems fine.

**Comment by MrMelbert** [comment]
I think it's fine that it doesn't copy diseases.
