### ISSUE TITLE
Boulders have a bad tendency to start rolling forever

### ISSUE THREAD

**Issue by ArcaneMusic** [tgstation/tgstation#81685]
## Issue Summary

In a few specific circumstances, boulders can be ejected from a refinery/smelter with a conveyor belt such that they start moving one direction forever.

https://github.com/tgstation/tgstation/assets/41715314/6e68a485-ed3e-4997-bdbc-70127a3946b1

It appears that this setup seems to reproduce the issue more often than not:
![image](https://github.com/tgstation/tgstation/assets/41715314/9a16290b-c5af-4d4b-b962-cf77c93bb821)

Another way to cause this to occur: Take a boulder in hand, and if you feed it into the machine, the attackby handles it, and it'll eject one tile off as expected. But if you place the boulder on the conveyor, it'll keep moving as seen in the above video.

## Round ID:
(https://statbus.space/rounds/224609)

Worth noting, there were no runtimes that jumped out to be as being relevant at the time that hopped into the round.

## Testmerges:
[#81231: 'A red spy has entered the base: Adds Spies, a roundstart antagonist inspired by Goonstation's Spy-Thief' by MrMelbert at commit 33778691b3](https://www.github.com/tgstation/tgstation/pull/81231)
[#81089: 'Temp keybinds patch for 515.1628' by MrStonedOne at commit 45649ea7a5](https://www.github.com/tgstation/tgstation/pull/81089)
[#81477: 'Comprehensive frame refactor to fix being unable to thwack frames with brute force to break them' by MrMelbert at commit 3149c449ad](https://www.github.com/tgstation/tgstation/pull/81477)

## Reproduction:

See the image above for reference, but a mining setup of one refinery/smelter next to each other appears to cause this to happen consistently. Conveyors must be on and powered, but once the boulder gets locked in it's movement pattern it'll keep on moving forever.

**Comment by ArcaneMusic** [comment]
Immediate thoughts: maybe it has to do woth the implementation of canMove that prevents boulders from sharing a turf? Alternatively to do with how boulders are held in processing machines

**Comment by SyncIt21** [comment]
I think #82085 might have fixed this?

**Comment by ArcaneMusic** [comment]
Appears so.
