### ISSUE TITLE
Radioactive nebula affects bitrunning domains

### ISSUE THREAD

**Issue by cnleth** [tgstation/tgstation#81689]
## Issue Summary
Space is radioactive in bitrunning domains and you get potassium iodide pills as a bit avatar when the station rolls radioactive nebula. These domains are supposed to be virtual, so I don't think rad nebula should affect them.

## Round ID:
[224590](https://scrubby.melonmesa.com/round/224590)

## Testmerges:
https://github.com/tgstation/tgstation/pull/81089
https://github.com/tgstation/tgstation/pull/81231
https://github.com/tgstation/tgstation/pull/81477

**Comment by Admiral-Gigaton** [comment]
inception, shit that happens outside the dream can affect the inside (joke)
