### ISSUE TITLE
The multi-dimensional bomb simply doesn't work.

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#81713]
## Issue Summary

Once you select your chosen type of bomb (or don't) and insert the bomb core into a bomb assembly, the resulting explosion causes....nothing to happen. It doesn't consume the bomb, nor does it actually do anything once it hits the point of detonation.

## Reproduction:

I'm not going to go over the process of inserting a bomb core into a bomb assembly and detonating it. That should be self evident. So I'll at least explain what was done to try and get it to explode;

Premature detonations by pinging the explode wires didn't work

Hitting it to speed up the timer didn't work

The actual countdown, un-changed, didn't work

Whether or not the bomb had the dimensional type set did not work in either state

**Comment by necromanceranne** [comment]
@Ghommie direct pinging ghommie with an apology

**Comment by Ghommie** [comment]
Oh, I'll fix it in a jiffy.
