### ISSUE TITLE
Cyborg flashes are not eligible for blood brother conversion, contrary to advertising.

### ISSUE THREAD

**Issue by OverwatchVoice** [tgstation/tgstation#81731]
Reporting client version: 515.1630

Self-explanatory. As a bloodbrother-turned-cyborg, try to convert someone using your built-in flash.
This is contrary to the objective description, which states: "Any flash will work if you lose or break your starting flash."
## Round ID:
[224739](https://scrubby.melonmesa.com/round/224739)

## Testmerges:
- [A red spy has entered the base: Adds Spies, a roundstart antagonist inspired by Goonstation's Spy-Thief](https://www.github.com/tgstation/tgstation/pull/81231)
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)

**Comment by Higgin** [comment]
yeah, that's an oversight on my part - it doesn't carry over to cyborgs or their flashes. I'll add 'handheld.'
