### ISSUE TITLE
apc wires don't open when you use a multitool on them

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#81745]
## Issue Summary
apc wires don't open when you use a multitool on them

## Round ID:
seen over the past few weeks, maybe longer

## Reproduction:
screwdriver open an apc
try to open the wire interface with a multitool, fail
open the interface with wirecutters, then switch to the multitool to pulse wires
why do I need wirecutters for this process

**Comment by moocowswag** [comment]
you can also use empty hand to open ui
