### ISSUE TITLE
Icebox hermit doesnt get a cultivator

### ISSUE THREAD

**Issue by NoodleNoms** [tgstation/tgstation#81743]
Reporting client version: 515.1631

## Issue Summary

the stranded hermit base on icebox does not have a cultivator for removing weeds

## Round ID:
[224774](https://scrubby.melonmesa.com/round/224774)

## Testmerges:
- [A red spy has entered the base: Adds Spies, a roundstart antagonist inspired by Goonstation's Spy-Thief](https://www.github.com/tgstation/tgstation/pull/81231)
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)

## Reproduction:
1. spawn as stranded hermit 
2. look for cultivator
3.weep

**Comment by mariadkgdmgdmi** [comment]
Did you forgot about rake?

**Comment by NoodleNoms** [comment]
there is no rake either

**Comment by tGyro** [comment]
https://github.com/tgstation/tgstation/pull/82219
