### ISSUE TITLE
Crafting melon fruit bowls blows you up

### ISSUE THREAD

**Issue by ophaq** [tgstation/tgstation#81763]
## Issue Summary
The water and potassium in melons + bananas (a classic combo) react to each other upon crafting this fruit item. As such, you become blown the fuck up. Not very fun when you have all your ingredients on your table next to you and they go flying along with all your limbs! Not sure if this is intended or an oversight. Regardless, I feel this needs fixing as it has been around for a long ass time and I kept forgetting to report this. Maybe substitute banana for a different fruit or somehow make it... not react.

## Round ID:
[224851](https://scrubby.melonmesa.com/round/224851)

## Reproduction:
Gather the ingredients needed for a melon fruit bowl and then craft it. Potassium and water react in it, causing you to become nugget.

**Comment by SyncIt21** [comment]
Duplicate #81226
