### ISSUE TITLE
Spies can steal cryo tubes, and their occupant

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#81776]
Reporting client version: 515.1631

## Round ID:
[224882](https://scrubby.melonmesa.com/round/224882)

## Testmerges:
- [Pathfinding will now initially run until tick_check before queuing work in the subsystem.](https://www.github.com/tgstation/tgstation/pull/81758)

## Reproduction:

Which just results in the occupant being deleted.  Nothing in logs, no deaths.html log, not even a stack trace in runtimes for a mob deleted with a soul.  Which was kinda funny, but also pretty rough to discover the cause (spy objectives dont seem that visible to admins right now)

I guess either protect cryotubes (sleepers, any thing else that contains people?) or add something for logging this ideally.

**Comment by MrMelbert** [comment]
No this is a problem with cryotubes, when a spy steals a machine it deconstructs it (which means it SHOULD dump all mobs inside, like the genetics scanner), which means it's not properly dumping its occupants on deconstruct

**Comment by Admiral-Gigaton** [comment]
Would have been pretty funny if when the tube was stolen, if someone bought it back the occupant came with it

**Comment by MrMelbert** [comment]
Upon further inspection I forgot that it only calls deconstruct if it is sold to the black market, and machines aren't guaranteed
