### ISSUE TITLE
Clown car can be controlled by passengers

### ISSUE THREAD

**Issue by Tekkuni** [tgstation/tgstation#81806]
## Issue Summary
Clown cars without enforce_clown_role=1 can be driven by abducted passengers. They also get access to all the action buttons intended for drivers, like removing key from ignition. Seems to be an issue with clown cars rewarded by spy objectives as well. Judging by testing in thunderdome, anyone in the car pressing the "eject passengers" button ejects everyone but the first person to have entered the car.

## Reproduction:
Spawn clown car, change to enforce_clown_role=0, abduct people and see what happens when they use their movement keys. Alternatively have a spy acquire a clown car as a reward and observe them.

**Comment by moocowswag** [comment]
This is also a funny issue with clown car during clown overflow, any and all clowns can press the buttons and force movement, although its probably intended at that point since you dont know which clown is the bad guy when they all come flooding out.

**Comment by Dawnseer** [comment]
Forceful backseat driving
