### ISSUE TITLE
Ranged Pirate Mobs without the space suits drop laser gun lenses on the ground when they fire.

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#81812]
## Issue Summary

The pirates are using lasers. They, for some reason, drop lenses? This is clearly not working properly.

## Reproduction

Spawn in a ranged pirate. Get shot at. It'll drop lenses on the floor.

**Comment by Singul0** [comment]
They drop their corpses though...?

**Comment by necromanceranne** [comment]
they didn't it's a ranged basic mob problem.
