### ISSUE TITLE
Accelerator Cannon projectiles expand to absolutely ridiculous sizes in an extremely short amount of time (and probably shouldn't be infinite in the first place)

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#81811]
## Issue Summary

Accelerator cannon projectiles gain infinite upward damage and also increase in size infinitely as they fly through the air. The transform occurs every tile, but the transformation itself seems to expand a lot more quickly than it did in the past.

## Reproduction

Shoot an accelerator cannon. Obviously.

**Comment by moocowswag** [comment]
Noticed this too, there is video evidence that it didnt expand this quickly in one of Livrah's videos in the past (Sun god one i think?)

If the damage also scales alot faster than it used to then its probably an issue with the ramp per tile rather than transform getting scuffed.

**Comment by necromanceranne** [comment]
I'm not terribly sure if the damage is scaling as rapidly, but since the damage is the determining factor for the scale, it's....possible?

**Comment by necromanceranne** [comment]
![image](https://github.com/tgstation/tgstation/assets/40847847/820688c9-7744-46b7-b85d-83e35b69ec7b)

Testing it, it doesn't appear as though the damage is scaling incorrectly. At 7 tiles, this is expected for accelerators.
