### ISSUE TITLE
you can start tapping an ore vent multiple times, spawning more than one drone(and megafauna)

### ISSUE THREAD

**Issue by 1393F** [tgstation/tgstation#81817]
## Issue Summary
opening multiple TGUI alerts for starting to tap a ore vent allows you to spawn multiple drones(and megafauna for menacing vents)

the TGUI alert also has no range check, allowing you to start it at any distance

## Round ID:
downstream

## Reproduction:
scan an ore vent and start clicking on it with your scanner to create multiple TGUI alerts, then click yes on all of them.
This spawns multiple megafauna for the menacing vents

**Comment by JohnFulpWillard** [comment]
I also think you can just put walls all around the ore vent to prevent it from being destroyed, which kinda takes away the whole challenge.
