### ISSUE TITLE
Cant bang baton on ballistic (maybe ghetto shield too, didnt test) shield

### ISSUE THREAD

**Issue by Admiral-Gigaton** [tgstation/tgstation#81838]
Reporting client version: 514.1589

## Round ID:
[225006](https://scrubby.melonmesa.com/round/225006)

## Testmerges:
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)

## Reproduction:
>get ballistic shield
>click baton on it in hand
>no banging
WTF dude, immersion ruined!!!1! >:(((

**Comment by MrMelbert** [comment]
They're not subtypes of riot shields, so they don't have this behavior

**Comment by Singul0** [comment]
you can component that relatively easily, you know what. i'll try it when I have the time

**Comment by SyncIt21** [comment]
After labelling  "not a bug" the next logical thing is to close this issue.
