### ISSUE TITLE
Plasmaman Deathmatch Blues

### ISSUE THREAD

**Issue by TagGamerGang22** [tgstation/tgstation#81858]
## Issue Summary

If you have a plasmaman character you spawn as a plasmaman in deathmatch. Thus immediately being set on fire and suffocating.

## Reproduction:
1. Make a plasmaman character
2. Play deathmatch
![image](https://github.com/tgstation/tgstation/assets/147560041/41c7fc77-def7-4cf9-b0ef-76823b043348)
![image](https://github.com/tgstation/tgstation/assets/147560041/34e85bb1-ee8a-48bd-b8ac-514fd9dbb27b)

**Comment by YakumoChen** [comment]
Challenge mode race
