### ISSUE TITLE
Parrots eat headsets instead of putting them on

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#81861]
## Issue Summary

When placing a headset on a parrot that is not Poly, the headset will disappear and not be on the parrot. It's like the parrot straight up ate it.

Reported by Banement on fulpstation codebase
https://github.com/fulpstation/fulpstation/issues/1143

## Reproduction:

1.Find a parrot that isn't Poly 
2. Place headset on the parrot.
3. Headset gets destroyed

**Comment by BanementI** [comment]
https://github.com/tgstation/tgstation/assets/47301693/9106feba-70c9-43ce-9128-69e914cc46a7

1. Find a parrot that isn't Poly
2. Place headset on the parrot
3. Headset disappears, the parrot is wearing it but can't be removed. This allows for infinite headset stacking.

**Comment by Sadboysuss** [comment]
The video shows reproduction, please update the label
