### ISSUE TITLE
Newscaster can't print newspapers, the Print Newspaper button is always greyed out

### ISSUE THREAD

**Issue by kawoppi** [tgstation/tgstation#81866]
## Issue Summary
The "Print Newspaper" button on newscasters is always greyed out. Where am I supposed to read my daily garfield now?

## Round ID:
[225100](https://scrubby.melonmesa.com/round/225100)

## Testmerges:
The following pull requests are currently test merged:
[#81813: 'Fix shutdown hanging if the db went away. gives shutdowns a time out. improves db shutdown logging' by MrStonedOne at commit f6007ead03](https://www.github.com/tgstation/tgstation/pull/81813)
[#81816: 'refactor db connection timeouts' by MrStonedOne at commit 3d88f539dc](https://www.github.com/tgstation/tgstation/pull/81816)
[#81821: 'Fix job time stuff not detecting the database was down.' by MrStonedOne at commit 73a00ede45](https://www.github.com/tgstation/tgstation/pull/81821)
[#81823: 'Protected admins can skip 2fa if the db is down.' by MrStonedOne at commit 611b9b066d](https://www.github.com/tgstation/tgstation/pull/81823)

## Reproduction:

1. Open newscaster and view Station Announcements
2. See that the button to print newspapers is greyed out and you can't click it
3. Create your own news channel because maybe you're not allowed the print the normal one
4. See that you can't print a newspaper for that one either

**Comment by Namwty** [comment]
You need to put paper into newscaster, after you can print them... if I remember correctly.

**Comment by DrDiasyl** [comment]
> You need to put paper into newscaster, after you can print them... if I remember correctly.

But WHY? We should make them spawn pre-loaded with like 10-20 sheets.

**Comment by kawoppi** [comment]
> You need to put paper into newscaster, after you can print them... if I remember correctly.

Tried it locally and it worked. Had no idea this was even possible. Maybe the print button could have a tooltip saying that you need to insert paper into it first? But I guess this technically isn't a bug anymore then
