### ISSUE TITLE
You Can Become A Cyborg In Deathmatch

### ISSUE THREAD

**Issue by TagGamerGang22** [tgstation/tgstation#81860]
Reporting client version: 515.1630

## Issue Summary

You can become a cyborg in the deathmatch minigame thus theoretically being able to speak about antagonists and metainformation to the in-round silicons.

## Testmerges:
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)

## Reproduction:
1. Get 3 people in dchat
2. Get them to join the meat tower map and not immediately murder eachother
3. Find a specific Margarita Pizza that spawns near the southeast of the conveyor belt which has nanomachines
4. Only one person eats the pizza
5. Said person now has cyborg conversion virus
6. In a few minutes said person will turn into a cyborg and be able to speak to the silicons in the round
![CyborgInDeathmatch](https://github.com/tgstation/tgstation/assets/147560041/02ecbee9-27a4-4def-a503-9fa89ed44a40)

**Comment by mc-oofert** [comment]
This seems to be a RNG thing
