### ISSUE TITLE
the civilian bounty control terminal does not display the bounty descriptions

### ISSUE THREAD

**Issue by kawoppi** [tgstation/tgstation#81867]
## Issue Summary

![image](https://github.com/tgstation/tgstation/assets/94711066/7d884970-36ef-4908-a9d8-568a0f909e21)
I'm pretty sure each bounty used to have a description in the little green box telling you flavortext and how many of the thing you needed to get.

## Round ID:
[225100](https://scrubby.melonmesa.com/round/225100)

## Testmerges:

The following pull requests are currently test merged:
[#81813: 'Fix shutdown hanging if the db went away. gives shutdowns a time out. improves db shutdown logging' by MrStonedOne at commit f6007ead03](https://www.github.com/tgstation/tgstation/pull/81813)
[#81816: 'refactor db connection timeouts' by MrStonedOne at commit 3d88f539dc](https://www.github.com/tgstation/tgstation/pull/81816)
[#81821: 'Fix job time stuff not detecting the database was down.' by MrStonedOne at commit 73a00ede45](https://www.github.com/tgstation/tgstation/pull/81821)
[#81823: 'Protected admins can skip 2fa if the db is down.' by MrStonedOne at commit 611b9b066d](https://www.github.com/tgstation/tgstation/pull/81823)

## Reproduction:

1. Insert your ID into civilian bounty control terminal
2. Press the pencil button to get request a new bounty
3. Only see the titles of the three bounties shown but not their descriptions

**Comment by ArcaneMusic** [comment]
And it wasn't in a tooltip either? (Mobileposting so I can't check)

**Comment by kawoppi** [comment]
> And it wasn't in a tooltip either? (Mobileposting so I can't check)

Nope, no tooltip comes up when you hover over it.
