### ISSUE TITLE
paper preview only updates when you press enter and writing no longer supports newlines

### ISSUE THREAD

**Issue by kawoppi** [tgstation/tgstation#81868]
## Issue Summary
Paper preview only updates when you press enter and no longer supports newlines.

## Round ID:
[225100](https://scrubby.melonmesa.com/round/225100)

## Testmerges:
The following pull requests are currently test merged:
[#81813: 'Fix shutdown hanging if the db went away. gives shutdowns a time out. improves db shutdown logging' by MrStonedOne at commit f6007ead03](https://www.github.com/tgstation/tgstation/pull/81813)
[#81816: 'refactor db connection timeouts' by MrStonedOne at commit 3d88f539dc](https://www.github.com/tgstation/tgstation/pull/81816)
[#81821: 'Fix job time stuff not detecting the database was down.' by MrStonedOne at commit 73a00ede45](https://www.github.com/tgstation/tgstation/pull/81821)
[#81823: 'Protected admins can skip 2fa if the db is down.' by MrStonedOne at commit 611b9b066d](https://www.github.com/tgstation/tgstation/pull/81823)

## Reproduction:

1. Click on a piece of paper while holding a pen in your hand
2. Write something in the `Insert Text` tab
3. It won't show up in the preview above no matter how long you wait
4. Now write something and press enter afterwards
5. The text you wrote will show up on the preview, instead of letting you write on a new line

**Comment by Derpguy3** [comment]
Can also report similar issues when trying to write on paper. Enter key is not doing anything
