### ISSUE TITLE
Combat disc plus natural malf roll creates two malf pages.

### ISSUE THREAD

**Issue by the-orange-cow** [tgstation/tgstation#81877]
Round ID: [225123](https://scrubby.melonmesa.com/round/225123)
BYOND Version: 515.1626
Server revision compiled on: 
Master commit: [87f43f140e4bd95b4e193a51a1bde82d21c6a7d9](https://www.github.com/tgstation/tgstation/commit/87f43f140e4bd95b4e193a51a1bde82d21c6a7d9)
The following pull requests are currently test merged:
[#81089: 'Temp keybinds patch for 515.1628' by MrStonedOne at commit 45649ea7a5](https://www.github.com/tgstation/tgstation/pull/81089)

Local commit: b96c5b7989e7c2b99f7ecedda3fca81777f0a3dd
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

This occurred on the round PRIOR to the above info(Round ID: [225119](https://scrubby.melonmesa.com/round/225119)).

Not sure if this is a bug or not, but I gave the AI the combat disc from the lizard ruins.  Later, the AI gained malf naturally.  This created two pages of malf abilities, with malf points only being gained on one of the pages.  Not sure if this is intended behavior or not, but it confused the AI who didn't realize there were two pages.  The ai believed they weren't gaining any points, thus putting a damper on their malf round since they weren't aware they had the budget to use malf abilities.

**Comment by MrMelbert** [comment]
There is code in place to handle a malf AI getting combat upgrades but not the other way around. Fix should be simple, just add the other-way-around code in malf AI `add_law_zero`. Also maybe make `add_law_zero` runtime if called when they already have one.
