### ISSUE TITLE
Holoparasites can't wash off slime

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#81888]
## Issue summary

It is is currently impossible to wash off the slime effect from slimes off of a holoparasite

## Round ID:

 Reported on fulpstation codebase: https://github.com/fulpstation/fulpstation

## Reproduction:

1) Get a holoparasite
2) Get a slime to attack itself to the holoparasite
3) Try to shower the holoparasite with water

**Comment by RandomDudeFromTheRim** [comment]
You can't wash off EMOTIONAL DAMAGE with simple water. Try giving your holoparasite some Canned Laughter. (But for real the situation sucks)
