### ISSUE TITLE
Drone vision filter is evidently not working for everything

### ISSUE THREAD

**Issue by dannno** [tgstation/tgstation#8191]
![](http://a.pomf.se/rqzbeh.png)
@RemieRichards

**Comment by RemieRichards** [comment]
it worked fine in my tests:
* Drone spawned before humans
* Drone spawned after humans
* Humans spawned while drones exist
etc.

**Comment by WJohn** [comment]
Drone static sometimes just cuts out.

**Comment by SouDescolado** [comment]
It happens when you enter vents with drones.

**Comment by optimumtact** [comment]
old higgs bugson
