### ISSUE TITLE
100% off sales on uplink

### ISSUE THREAD

**Issue by iansdoor** [tgstation/tgstation#81912]
Round ID: https://statbus.space/rounds/225254

A player self-reported and went ham on buying out the implants to give to crew. 

I haven't seen this myself or tested on the why yet. If its implant sale, wouldn't that mean that station implant trait had something to do with this. I am not sure.

**Comment by Archie700** [comment]
Log where it happened was [here](https://tgstation13.org/parsed-logs/terry/data/logs/2024/03/09/round-225253/uplink.txt)

**Comment by Profakos** [comment]
Hm, do note later in the notes that if something is discounted, they have the discount in their names. None of the implants have their names discounted. Furthermore, only nuke ops can buy this implant, and only nuke ops can have infinite stock of discounts. Peculiar! Another note in the log: a few times they bought "random uplink item" for 0 TC.

**Comment by projectkepler-ru** [comment]
I dont think this is a bug

**Comment by iansdoor** [comment]
oh right, let me update what it looks like. 0 cost is
![Screenshot_172](https://github.com/tgstation/tgstation/assets/109386467/a1c28254-dd1b-45e9-bd54-de8b4ce9bb1d)
 not store related at all

**Comment by Profakos** [comment]
You know what is also weird? These implants are supposed to be nuke op exclusive.
