### ISSUE TITLE
Fire Sharks are on a too high plane

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#81916]
Reporting client version: 515.1630

## Round ID:
[225268](https://scrubby.melonmesa.com/round/225268)

## Testmerges:
- [Fix shutdown hanging if the db went away. gives shutdowns a time out. improves db shutdown logging](https://www.github.com/tgstation/tgstation/pull/81813)
- [refactor db connection timeouts](https://www.github.com/tgstation/tgstation/pull/81816)
- [Fix job time stuff not detecting the database was down.](https://www.github.com/tgstation/tgstation/pull/81821)
- [Protected admins can skip 2fa if the db is down.](https://www.github.com/tgstation/tgstation/pull/81823)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/66640614/9e0e4a1b-969e-4f74-8fc1-897f72eecae1)

**Comment by LemonInTheDark** [comment]
This implies the shark is not on a higher layer, but a higher plane

How

**Comment by dragomagol** [comment]
![image](https://github.com/tgstation/tgstation/assets/66640614/e4e2835c-a988-4846-895f-9cfc21acf976)

It seems to be spreading, I've seen it a dozen times since. R 225535
