### ISSUE TITLE
Syndicate Assualt Shuttle's ballistic turrets fire through and ignore windows.

### ISSUE THREAD

**Issue by Kitfox88** [tgstation/tgstation#81910]
Reporting client version: 515.1630

## Issue Summary

As said in the title, midround nukies sent their shuttle directly adjacent to the escape shuttle and the turrets on it opened fire on me through the cockpit windows without causing any damage to said windows, or being blocked by them, despite the turrets being labeled as ballistics. Destroying the windows, or penetrating them as they damaged maybe, but the windows appeared totally fine until a big bomb went off like 30 seconds later.

## Round ID:
[225240](https://scrubby.melonmesa.com/round/225240)

## Testmerges:
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)

## Reproduction:

Go to cockpit as an engiborg in an attempt to reinforce it against dastardly syndicates. Get shot by half a dozen .50 BMG aggression dissuasion rounds before I realize what's happening and barely survive.

**Comment by necromanceranne** [comment]
They're penetrators, this is intended.
