### ISSUE TITLE
Lemon Lime is advertised as Orange Soda

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#81915]
## Issue Summary
Go to a vendor
Buy what is labeled as Orange Soda
It is lemon lime soda

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/66640614/d6a8a533-13f1-4df7-96cd-25cd93ec95a6)
![image](https://github.com/tgstation/tgstation/assets/66640614/935f7076-6785-459e-aa36-a167d4997f66)

**Comment by san7890** [comment]
This is intentional iirc (haha funny Deus Ex joke) but I think the bug is that it's showing an icon of lemon-lime soda while the name is orange soda. It should be all-or-nothing imo

**Comment by Rhials** [comment]
Are you sure you pressed the right button?

**Comment by Ghommie** [comment]
https://www.youtube.com/watch?v=hxVPPy5w9NA
