### ISSUE TITLE
Ore vents can spawn plastic

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#81948]
## Issue Summary

Plastic is not a natural resource or mineral, it is a synthetic material made by humans derived from oil, it's even organic and burns so it makes absolutely no sense for ore vents to have a chance in spawning plastic on a hot planet. This devalues chemists.

## Round ID:

N/A

## Reproduction:

Plastic has a chance to spawn in the arcmining ore vents

**Comment by ArcaneMusic** [comment]
This is intentional, while also being rare.
1 out of all 15 ore vents will have plastic as a resource found in ore vents.

Plastic isn't a hard resource to make either. It's 7 clicks on a chem dispenser so it's hardly that much of a gate anyway.

**Comment by Sadboysuss** [comment]
> This is intentional, while also being rare. 1 out of all 15 ore vents will have plastic as a resource found in ore vents.
> 
> Plastic isn't a hard resource to make either. It's 7 clicks on a chem dispenser so it's hardly that much of a gate anyway.

it's not that big of an issue, you guys do whatever you like with it but I personally don't like it cause I'm a nerd

**Comment by Time-Green** [comment]
I’m sure someone can make up a reason, sci-fi magicks or whatever. 

I’m personally more concerned about the feature creep of putting the chemistry-only material into mining, but this isn’t the place for either discussion.
