### ISSUE TITLE
`budgetordering` causes runtimes due to `HAS_SILICON_ACCESS` (but honestly, probably shouldn't be checking `usr` anyways)

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#81949]
## Issue Summary

https://github.com/tgstation/tgstation/blob/a3d141febacc45fe41f2af037a2eca042931f135/code/modules/modular_computers/file_system/programs/budgetordering.dm#L36-L38

https://github.com/tgstation/tgstation/blob/a3d141febacc45fe41f2af037a2eca042931f135/code/modules/modular_computers/file_system/programs/budgetordering.dm#L87-L88

`usr` cannot be relied on, and here, it's probably null

**Comment by MrMelbert** [comment]
I would wager this proc maybe was always silently broken and no one's noticed?

**Comment by MrStonedOne** [comment]
ui_data passes the user as an argument.

this should use that.

it is perfectly normal for ui_data to look at the user looking at the ui, this can't be avoided.

usr will be null in ui_data except the first call when the user first opens the ui.

**Comment by MrStonedOne** [comment]
lul, ui_data_static here has the user arg in the override, which i don't think is valid
