### ISSUE TITLE
fuck you coupons still make you permanently cursed

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#81946]
Reporting client version: 515.1630

## Issue Summary
fuck you coupons still make you permanently cursed

## Round ID:
[225361](https://scrubby.melonmesa.com/round/225361)

## Testmerges:
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)

## Reproduction:
get a fuck you coupon from cigarette packs
get crushed by a vending machine/door/shocked by a light
think "thank god https://github.com/tgstation/tgstation/pull/81814 got merged so I can go about the rest of my shift without being cursed"
go about the rest of your shift getting continuously light shocked/door crushed/vendor crushed

**Comment by 00-Steven** [comment]
Baaaaased on the round ID this looks like this was before the server updated to that pr? Lemme check in an updated version anyway for sanity's sake.

**Comment by 00-Steven** [comment]
So yeah this seems to coincidentally still be an issue, lemme see about fixing it.

**Comment by 00-Steven** [comment]
yeah that should do it
