### ISSUE TITLE
Buttons can no longer have circuitry removed 

### ISSUE THREAD

**Issue by MajManatee** [tgstation/tgstation#81961]
## Issue Summary
Wall-mounted buttons can no longer have their internal circuitry removed. Believed to be in relation to #81681.

## Round ID:
N/A. All rounds since #81681 was merged.

## Testmerges:
N/A

## Reproduction:
Screwdriver open a wall mounted button
Attempt to remove electronics with empty hand
fail to do so.

**Comment by 00-Steven** [comment]
This seems to be because it changed `attack_hand` to `interact`, which I *believe* can't happen when the panel is open without a specific flag?

**Comment by 00-Steven** [comment]
I mean `interact` *is* called on `attack_hand`, it just first does a bunch of checks before calling it.
It's blocking `interact` from being called there because `panel_open` being true blocks it unless the machine has `INTERACT_MACHINE_OPEN` in its `interaction_flags_machine`.

**Comment by 00-Steven** [comment]
![image](https://github.com/tgstation/tgstation/assets/42909981/f1b556d2-1cf1-440a-a4a9-e3e6896d7b1b)
![image](https://github.com/tgstation/tgstation/assets/42909981/a7e4870a-f731-408d-8525-44791b369444)
