### ISSUE TITLE
Protolathe hangs on 'building items' forever

### ISSUE THREAD

**Issue by lessthnthree** [tgstation/tgstation#81972]
## Issue Summary

On the rare occasion the protolathe will sit unusable 'building items' until it's dismantled and rebuilt. Toggling the power on/off with the APC doesn't seem to fix it.

![GYqQNG5PmY](https://github.com/tgstation/tgstation/assets/83487515/3bc5e9cb-773e-4f12-a13c-a898c4f114db)

## Round ID:

[225436](https://scrubby.melonmesa.com/round/225436)

## Reproduction:

Not sure how to reproduce, but I've seen it happen a few times in the past couple weeks.

**Comment by necromanceranne** [comment]
Definitely seen it happen. Also haven't been able to reproduce. As far as I can tell, one fix is to unscrew the panel and screw it back. I believe this should fix the interface.

**Comment by Time-Green** [comment]
I thought it was due to the building materials being used somewhere else while it’s in progress? When I experienced it, that’s at keasg what the UI seemed to indicate

**Comment by Striders13** [comment]
seen it happen twice in one round. Screwing and unscrewing panel fixed the UI, but the lathe was still unusable, to fully fix it you need to deconstruct

**Comment by lessthnthree** [comment]
> This function is common for all UIs and is nothing specific to lathes. Simply closing and reopening the UI should fix it.

It doesn't and multiple players will all have the same issue with the lathe.

**Comment by FlufflesTheDog** [comment]
https://github.com/tgstation/tgstation/assets/25628932/b6ef1aff-438f-491e-b91b-e9f6f3cf3e94
