### ISSUE TITLE
You can lock or unlock turret controls with anything

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#81978]
Reporting client version: 515.1630

## Issue Summary
Using any item on a turret panel will lock/unlock it. You can't hit it at all, with right/left click, on and off combat mode. All it does is toggle the lock.

## Testmerges:
- [Might fix reagent loop](https://www.github.com/tgstation/tgstation/pull/81952)

## Reproduction:
Was a regular station engineer, went to go investigate malf AI. used screwdriver on turret panel, then tried to use a multitool on it, and noticed that this toggled the lock also. Turned off the turrets, and decided to try and destroy it with a crowbar so that it couldn't be re-activated. This only toggled the lock. I tried to break it. Only toggled the lock. Cried about it.

**Comment by ArcaneMusic** [comment]
Holy shit lol

**Comment by 00-Steven** [comment]
lmao
