### ISSUE TITLE
You can put an off hand into a bag of holding.

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#82019]
## Issue Summary
You can put an Off-hand into a bag of holding. I don't know how to explain this so just watch the video.

## Round ID:

reported on fulpstation codebase: https://github.com/fulpstation

## Testmerges:

Fulpstation.
https://github.com/fulpstation/fulpstation/pull/1107
https://github.com/fulpstation/fulpstation/pull/1145
https://github.com/fulpstation/fulpstation/pull/1146
https://github.com/fulpstation/fulpstation/pull/1153
https://github.com/fulpstation/fulpstation/pull/1156

## Reproduction:

https://imgur.com/a/PiQtkPa

**Comment by Sadboysuss** [comment]
> why didnt you file this at fulpstation

fulpstation is a downstream of /tg/ and I don't think this is caused by fulpstation codebase edits

**Comment by Rhials** [comment]
Problem reproduced with same steps as in the imgur video on tg master.

![it works](https://github.com/tgstation/tgstation/assets/28870487/dbd3843f-fee3-401f-aa97-6eaae0d3cd52)

This is being reported in the correct place.

**Comment by remove32** [comment]
i think that even though you are right about the location of the issue report, you should also take a minute to replicate the bug in tg master before submitting. including fulp info here isn't exactly helpful and could be avoided without issue by simply replicating it in a local instance. that being said, good find this is very funny
