### ISSUE TITLE
deathmatch_loadout species overrides that change equip slots cause outfit_sanity unit test to fail

### ISSUE THREAD

**Issue by remove32** [tgstation/tgstation#82022]
## Issue Summary

outfit_sanity uses a consistent human to perform testing
![image](https://github.com/tgstation/tgstation/assets/27014495/ee544db8-9628-499c-ada3-0629b4cec0a8)
deathmatch_loadout pre_equip checks for isdummy and then early returns 
![image](https://github.com/tgstation/tgstation/assets/27014495/52046215-790d-47ce-bed2-0bf0b4e39221)
but since the test doesn't use a dummy, it changes species during unit testing. this can lead to failures

## Reproduction:

make a deathmatch loadout that changes species to monkey for example, and run the unit test. since the loadout changes the species of our John Doe to a monkey he can no longer equip a large number of items, causing failures until another loadout changes it back to a species that can equip items in those slots. 
changing the test to use a consistent dummy does not work either and causes test failures. if i had to propose a solution it'd be having deathmatch_loadout do a more robust check but i'm not sure what form that should take

**Comment by mc-oofert** [comment]
it could return if UNIT_TESTS is defined but im not sure if that would fix it
