### ISSUE TITLE
Self-inserted strings on circuits not saving

### ISSUE THREAD

**Issue by Glu-furro** [tgstation/tgstation#82023]
Reporting client version: 515.1632

## Issue Summary

I attempted to input strings on a circuit myself (for a name to a circuit) and when i re opened the circuit it didnt save, and it keeps not saving.

## Round ID:
[225583](https://scrubby.melonmesa.com/round/225583)

## Reproduction:
 Use integrated circuit with a module that you can insert a string into, insert a string and close the window, open the window again and it wont be saved (empty)

**Comment by moocowswag** [comment]
its not just an issue with strings i found that any manual input (like for arithmatic) has been alittle painful around the same time lathes have started having similar issues with their search boxes.

**Comment by moocowswag** [comment]
dealt with it in a recent round, the strings still functionally save, the bug is purely visual/ a ui issue.

**Comment by Glu-furro** [comment]
> dealt with it in a recent round, the strings still functionally save, the bug is purely visual/ a ui issue.

Not for me, i had made a brain radio circuit and it did not work, seen by the fact that nothing was sent, but ill see if its fixed

**Comment by moocowswag** [comment]
i literally did a brain radio circuit last night it worked and i think i recorded it, the strings just didnt visually save.

Did you remember to output to your own brain too?
