### ISSUE TITLE
You cannot START self surgery

### ISSUE THREAD

**Issue by DATA-xPUNGED** [tgstation/tgstation#82034]
## Issue Summary

The surgery menu that picks the surgery you want only works if you're standing up, but you can only start surgery on someone laying down...

## Reproduction:

- Have a robotic limb of some sort
- Attempt to start a surgery on yourself, which should be a feature of robotic limbs
- The surgery menu that picks the surgery you want only works if you're standing up, but you can only start surgery on someone laying down...

**Comment by Dawnseer** [comment]
Is this recent? I always start my self surgeries standing.

**Comment by Dawnseer** [comment]
Given it a go and I can seemingly still do it just fine

**Comment by JohnFulpWillard** [comment]
It should def be possible to do it while resting
