### ISSUE TITLE
Flight Potion Wings Act as Jetpacks

### ISSUE THREAD

**Issue by TagGamerGang22** [tgstation/tgstation#82035]
## Issue Summary
Wings from a flight potion allow you to fly in space as if you had a jetpack.

## Testmerges:
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)

## Reproduction:
1. Get a flight potion from mining or xenobio
2. Activate your wings in a pressurized environment
3. Go into space or a place with no air
![image](https://github.com/tgstation/tgstation/assets/147560041/0e34baf5-2c3a-43fb-9a83-4758f81374b1)

**Comment by moocowswag** [comment]
If dragon wings and carp tail can do it so can spaceman wings.

**Comment by gueba14** [comment]
wings are hard to get tho
