### ISSUE TITLE
APC fully charged but no power

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#82031]
Reporting client version: 515.1633

## Round ID:
[225595](https://scrubby.melonmesa.com/round/225595)

## Testmerges:
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/62606051/27f2c309-fd9e-4878-a36d-20d8d15a9df9)
This made me unable to use the lathe in the same room but the lights were on as though power was working, an admin was able to fix it with a power restoration however

**Comment by Sadboysuss** [comment]
Not sure if it's intended or not but this happens when there is no cell in the apc.
