### ISSUE TITLE
Bounty Hunter cycler shotgun stops working after pumping/tube swap

### ISSUE THREAD

**Issue by Higgin** [tgstation/tgstation#82056]
## Issue Summary

/obj/item/gun/ballistic/shotgun/automatic/dual_tube/bounty stops functioning after trying to pump or cycle tubes.

Doesn't receive shells. Doesn't continue swapping. If you alt-click on the gun to pump it, you can no longer add shells, fire it without it just 'clicking,' or even swap tubes back. Not sure what sort of refactor might've done it. Cursed 666 round ID predicts evil afoot.

## Testmerges:

BYOND Version: 515.1633
Server revision compiled on: 
Master commit: [75ecfae1a25226ee9b373f6cf803853030a52ba4](https://www.github.com/tgstation/tgstation/commit/75ecfae1a25226ee9b373f6cf803853030a52ba4)
The following pull requests are currently test merged:
[#81089: 'Temp keybinds patch for 515.1628' by MrStonedOne at commit 45649ea7a5](https://www.github.com/tgstation/tgstation/pull/81089)

Local commit: 777ec70b2445b187baeca18b49077b1c73e3abd9
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3
## Reproduction:

take /obj/item/gun/ballistic/shotgun/automatic/dual_tube/bounty
shoot two rubbershot rounds
hit Z (switching to tube B) OR alt-click it to pump
be unable to do anything but pump, unable to add shells, shoot, or otherwise 
:(

**Comment by SyncIt21** [comment]
Duplicate #81315
