### ISSUE TITLE
Unable slapcraft ED-209s

### ISSUE THREAD

**Issue by 80sFreshness** [tgstation/tgstation#82057]
Reporting client version: 515.1633

## Issue Summary

When slapcrafting an ED-209 I AND others are unable to get past welding, after you finish welding the ED-209 I am no longer  able to to do any of the other steps.  I was not able to add a Sec helmet to the ED-209 when the wiki told me so.  On a sidenote: we had three ED-209s getting all stuck on the same step.
## Round ID:
[225668](https://scrubby.melonmesa.com/round/225668)

## Testmerges:
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)

## Reproduction:
To simply reproduce this bug is to simply slapcraft an ED-209.  In which after welding it wont work.

**Comment by Sealed101** [comment]
unless you were using a nonstandard sec helmet i can't see how this would fail as i have successfully completed the recipe with slapcraft

https://github.com/tgstation/tgstation/blob/d0db1ff267557017ae7bde68e6490e70cbb6e42f/code/modules/mob/living/simple_animal/bot/construction.dm#L137-L146
