### ISSUE TITLE
Cargo drone Ui is broken

### ISSUE THREAD

**Issue by Blacklist897** [tgstation/tgstation#82050]
Reporting client version: 515.1631

## Issue Summary
the ui for the exploration drone control console is mangled to the point its useable

## Round ID:
[225646](https://scrubby.melonmesa.com/round/225646)

## Testmerges:
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)

## Reproduction:
Walk into cargos drone room and use the console

**Comment by SyncIt21** [comment]
Duplicate #80636

**Comment by Sealed101** [comment]
fixed by https://github.com/tgstation/tgstation/pull/82061
