### ISSUE TITLE
Spare ID Safe Not Spawning on Tram

### ISSUE THREAD

**Issue by TagGamerGang22** [tgstation/tgstation#82054]
## Testmerges:
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)

## Reproduction:
1. Play a round of tram
2. Look at where the spare ID safe is meant to be
3. Realize it doesn't exist
![image](https://github.com/tgstation/tgstation/assets/147560041/f2e4fd84-b4d6-4054-b8ac-771020dee367)

**Comment by JohnFulpWillard** [comment]
![image](https://github.com/tgstation/tgstation/assets/53777086/f9373e38-6db1-4771-977f-5b14b14a29e0)

**Comment by JohnFulpWillard** [comment]
Basically, unless someone deleted my safe it should be there

**Comment by JohnFulpWillard** [comment]
im running master on local and it seems to very much exist.
I checked manuel and there's no testmerges that seem to fuck w/ it
![image](https://github.com/tgstation/tgstation/assets/53777086/56a14330-4f07-45f5-ab51-37d40e8c6fd9)
