### ISSUE TITLE
objection: none! (blood brother)

### ISSUE THREAD

**Issue by wizzardmuffin** [tgstation/tgstation#82064]
Reporting client version: 515.1630

## Issue Summary

for two round when i rolled blood brother i have been given no objection but only says none (the first one said the objection in the end round report)(second time admin just gave me new objectives)
![Screenshot 2024-03-17 163633](https://github.com/tgstation/tgstation/assets/123269287/b98134ea-8d12-4e10-aab8-6a8c76f83787)

## Round ID:
[Round ID]: [225684](https://scrubby.melonmesa.com/round/225684)

## Testmerges:
- [Might fix reagent loop](https://www.github.com/tgstation/tgstation/pull/81952)

## Reproduction:
when i rolled blood brother the first round it said none and the same the the second occurrence. during the second occurrence the admin WalterMeldron removed the role and added back but the objective stayed as none

**Comment by JohnFulpWillard** [comment]
The objectives show to the people you cover but not to yourself, I assume it's something about not giving your datum the team objectives but we really should just make Team objectives visible in the first place.

**Comment by Watermelon914** [comment]
I was actually checking the team datum, there was no objectives on the team objectives either.
