### ISSUE TITLE
Selling Stock Blocks from the Galactic Materials Market does not put any money into the cargo budget

### ISSUE THREAD

**Issue by iamcooldan** [tgstation/tgstation#82070]
Reporting client version: 515.1632

## Issue Summary
When selling a stock block from the galactic mineral market no money is placed into the cargo budget, and the console does not register that a block has been sold

## Round ID:
[225704](https://scrubby.melonmesa.com/round/225704)

## Testmerges:
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)

**Comment by JohnFulpWillard** [comment]
I think selling stuff at cargo is still not working @Ghommie

**Comment by ArcaneMusic** [comment]
Confirmed, it's not runtiming now, but it isn't being added to the cargo wallet.
![image](https://github.com/tgstation/tgstation/assets/41715314/00e167b5-85f5-4c0a-9199-5fa77576db1e)

**Comment by Ghommie** [comment]
> Confirmed, it's not runtiming now, but it isn't being added to the cargo wallet.

Does this apply to normal exports too?
