### ISSUE TITLE
the mafia role description for Obsessed reveals their target to everyone in the game.

### ISSUE THREAD

**Issue by iamafsh** [tgstation/tgstation#82088]
## Issue Summary
![image](https://github.com/tgstation/tgstation/assets/20996272/dddf40f2-6671-4bc7-b45b-552bc4cc278d)

mafia panel --> (?) next to Obsessed tells you their target. Even if you aren't the Obsessed.

Round ID: [225742](https://scrubby.melonmesa.com/round/225742)

The following pull requests are currently test merged:
[#82074: '[NO GBP] bumps auxlua to 1.4.4' by Y0SH1M4S73R at commit 6ad49f03fc](https://www.github.com/tgstation/tgstation/pull/82074)

**Comment by san7890** [comment]
@JohnFulpWillard

**Comment by JohnFulpWillard** [comment]
Didn't even see this until now, I'll look into it when I next can
