### ISSUE TITLE
Painting patron runtimed (runtime included)

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#82091]
Reporting client version: 515.1633

## Round ID:
[225744](https://scrubby.melonmesa.com/round/225744)

## Testmerges:
- [[NO GBP] bumps auxlua to 1.4.4](https://www.github.com/tgstation/tgstation/pull/82074)

## Reproduction:

Had a player try to pay 10k to patron a frame (they had apparently had these issues before) painting details if relevant are
title: General Goldenbar III Esquire

Patron payment failed to take and upon investigation a related runtime was found suggesting some kind of function call arguments issue (?)
```
[2024-03-18 22:53:26.749] RUNTIME: runtime error: type mismatch: 0 - /datum/bank_account (/datum/bank_account)
 - proc name: patron (/obj/item/canvas/proc/patron)
 -   source file: code/modules/art/paintings.dm,279
 -   usr: General Goldenbar III Esquire (/mob/living/carbon/human)
 -   src: the painting - General Goldenb... (/obj/item/canvas/twentythree_twentythree)
 -   usr.loc: the carpet (59,97,3) (/turf/open/floor/carpet)
 -   src.loc: the painting - General Goldenb... (/obj/structure/sign/painting/library_secure)
 -   call stack:
 - the painting - General Goldenb... (/obj/item/canvas/twentythree_twentythree): patron(General Goldenbar III Esquire (/mob/living/carbon/human))
 - the painting - General Goldenb... (/obj/item/canvas/twentythree_twentythree): ui act("patronage", /list (/list), /datum/tgui (/datum/tgui), /datum/ui_state/physical_obscu... (/datum/ui_state/physical_obscured_state))
 - /datum/tgui (/datum/tgui): on act message("patronage", /list (/list), /datum/ui_state/physical_obscu... (/datum/ui_state/physical_obscured_state))
 - /datum/callback/verb_callback (/datum/callback/verb_callback): Invoke()
 - /datum/callback/verb_callback (/datum/callback/verb_callback): Invoke()
 - world: push usr(General Goldenbar III Esquire (/mob/living/carbon/human), /datum/callback/verb_callback (/datum/callback/verb_callback))
 - /datum/callback/verb_callback (/datum/callback/verb_callback): InvokeAsync()
```

**Comment by Likteer** [comment]
*Tried to donate 22K in a hand-crafted painting frame (outside of library) the first time it failed
then tried doing it in another round donating exact 12K for an sm border, in a proper library painting frame

**Comment by Son0rus** [comment]
We found a temporary fix by commenting out the section of code for giving the curators a cut. After this we were able to donate successfully
![image_2024-03-20_003616296](https://github.com/tgstation/tgstation/assets/164028050/fdea84b7-e104-4fba-b20b-572de423c650)
