### ISSUE TITLE
Unclickable items from autodrobes

### ISSUE THREAD

**Issue by iansdoor** [tgstation/tgstation#82097]
Not sure if this was made an issue yet.

If you have the UI to buy something and place your ID on the floor/backpack. The buy buttons no longer work. The only fix is to take apart and put the autodrobe back together. 

Edit: Works on all buyable machines.

**Comment by iansdoor** [comment]
![example](https://github.com/tgstation/tgstation/assets/109386467/498d5818-4c51-4a69-98a1-da488b799986)
yeah, ID open and dropping/placing in your backpack will brick any buying till you rebuild the machine.

**Comment by SyncIt21** [comment]
This is intentional and not a bug. You need an ID on you to use the vendor so making it unavailable buy dropping it or placing it in bag will disable the UI.

**Comment by newfren** [comment]
does buying begin working again when you wear or hold the id? or is the machine permanently unable to sell to you

**Comment by SyncIt21** [comment]
> does buying begin working again when you wear or hold the id? or is the machine permanently unable to sell to you

It will work again once you re-equip the ID either in your hand or on your belt like the PDA.

**Comment by Admiral-Gigaton** [comment]
> This is intentional and not a bug. You need an ID on you to use the vendor so making it unavailable by dropping it or placing it in bag will disable the UI.
> 
> Just like how you need an ID to open doors and other stuff the UI functions in this way to deny you the buy action

Read again: once they equip, it still doesn't work, and there's not even a message
