### ISSUE TITLE
Using reagent containers on envelopes adds a new stamp.

### ISSUE THREAD

**Issue by DaCoolBoss** [tgstation/tgstation#82122]
## Issue Summary
When "attacking" an envelope with a reagent container (drinking glass, beaker, etc) the envelope receives a new stamp decal over the old one. The reagent container doesn't have to contain reagents. This can be done repeatedly until you hit the decal limit, which replaces all the stamps with a single ERROR sprite.

## Round ID:
Reproduced locally.

## Reproduction:
Spawn mail envelope.
Spawn reagent container.
Have a carbon pick up the reagent container.
Have carbon attack envelope with reagent container.
Observe.
Optionally, repeat until error sprite shows up.

**Comment by 00-Steven** [comment]
seems like it's somehow just, continuously adding more and more overlays...
