### ISSUE TITLE
Driving Clown Car Into the SM Doesn't Kill Anyone

### ISSUE THREAD

**Issue by IndieanaJones** [tgstation/tgstation#82135]
## Issue Summary

Driving the clown car into the supermatter results in the clown car's destruction, with all occupants being left on the tile where the clown car was unharmed.

## Testmerges:

#82085: 'Canonical Movement' by Kapu1178 at commit d8a650b23d](https://www.github.com/tgstation/tgstation/pull/82085)

## Reproduction:

- Get clown car
- Get passengers
- Drive clown car into SM
- Note the passengers are deposited safely on the tile where the clown car was, free to escape what should be an iconic death for all

**Comment by Blacklist897** [comment]
Its not from the test merge its been around for ages
https://www.youtube.com/watch?v=Ov2ihvRtfwM

**Comment by moocowswag** [comment]
This has been and on and off issue i think actually, ive had times where the clown car instantly dusted everyone and times when it didnt and i learned to loop around the sm crystal to consistently get everyone with it.

**Comment by moocowswag** [comment]
Oh thats my video being shown and i even talked about it briefly back then, ya its a timeless quirk with sm dusting im just not sure if there is other variables at play because it didnt always happen.

**Comment by Kapu1178** [comment]
> This has been and on and off issue i think actually, ive had times where the clown car instantly dusted everyone and times when it didnt and i learned to loop around the sm crystal to consistently get everyone with it or atleast try to hit the sm crystal on the side with the vents so the scrubbers pull them.

The clowncar will throw people in random directions after they leave. So its pure RNG.
