### ISSUE TITLE
Chaplain god's hand item deleted when arm is amputated

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#82133]
## Issue Summary
Other attached null rod variants like the chainsaw get dropped to the ground, god hand instead gets deleted and the null rod is gone completely.

## Round ID:
N/A

## Reproduction:
1. Choose god hand null rod as chaplain
2. Amputate the arm your god hand is on
3. Ponder about your life choices because your holy weapon is gone forever

**Comment by moocowswag** [comment]
This has been a known issue for years and years and years its even a timeless relic on the wiki i think.

**Comment by Sadboysuss** [comment]
still feels like a bug, the null rod is a special item and even a secondary objective
