### ISSUE TITLE
Musiver can be rolled as Metalgen reagent

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#82140]
## Reproduction:

I don't think it's intentional
![Screenshot_241](https://github.com/tgstation/tgstation/assets/64209864/cb0e90fc-5c6b-4b73-953b-9c24262aafc8)

**Comment by Time-Green** [comment]
Yeah it’s not something you’d realistically get. The secret chems could use a whitelist tbh or the reagents thenselves need a complexity var
