### ISSUE TITLE
Deathmatch modifier Random Modifiers doesnt work + ideally Heightened Hearing should be a modifier

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#82149]
## Issue Summary
Deathmatch modifier Random Modifiers doesnt work + ideally Heightened Hearing should be a modifier
## Reproduction:

1. use random modifiers modifier
2. it doesnt do anything

**Comment by OuroborusReporter** [comment]
![9](https://github.com/tgstation/tgstation/assets/88996803/92980c96-1d65-4223-a25b-41b0c57024d8)
