### ISSUE TITLE
Mech Facing Does Not Modify Damage

### ISSUE THREAD

**Issue by Higgin** [tgstation/tgstation#82142]
## Issue Summary

mechs don't adjust damage/armor from incoming attacks based on their facing relative to the attacker.

they're supposed to take 1.5x damage from behind and .5x damage from the front (this really should be 2x and .5x for parity,) but they don't - they take all damage from any direction the same.

## Testmerges:

BYOND Version: 515.1633
Server revision compiled on: 
Master commit: [8dfc3a8a3077a63761d8eede004e91e4f99332bd](https://www.github.com/tgstation/tgstation/commit/8dfc3a8a3077a63761d8eede004e91e4f99332bd)
The following pull requests are currently test merged:
[#82131: 'Moves lua off of the timer subsystem and onto its own internal scheduler.' by Watermelon914 at commit 2e7b859db2](https://www.github.com/tgstation/tgstation/pull/82131)

Local commit: e8ab33c29933a0326cfc3244b75aa51aad33e402
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

## Reproduction:

1. Take a mech.
2. Hit it from the front, side, and behind. 
3. Get the same damage from every angle.
4. Wonder why the facing modifiers exist.

**Comment by necromanceranne** [comment]
Repeat of https://github.com/tgstation/tgstation/issues/81260

It does check it for projectiles. Not melee. Unless this now no longer works with projectiles either. In which case that is a new bug.

**Comment by githubuser4141** [comment]
> Repeat of #81260
> 
> It does check it for projectiles. Not melee. Unless this now no longer works with projectiles either. In which case that is a new bug.

It does check for melee, as in simple mob melee but it doesn't check for item attacks like toolboxes.
