### ISSUE TITLE
No ref handling for `/obj/item/virgin_mary`

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#82158]
## Issue Summary

`/obj/item/virgin_mary` shoves mobs in a global(static) list and then just forgets about 'em. 

## Reproduction:

https://github.com/tgstation/tgstation/blob/5a3938ce3ee87235cc36a81bf80c6ea7032a46b1/code/game/objects/items/virgin_mary.dm#L1-L10

https://github.com/tgstation/tgstation/blob/5a3938ce3ee87235cc36a81bf80c6ea7032a46b1/code/game/objects/items/virgin_mary.dm#L23

https://github.com/tgstation/tgstation/blob/5a3938ce3ee87235cc36a81bf80c6ea7032a46b1/code/game/objects/items/virgin_mary.dm#L42

**Comment by LemonInTheDark** [comment]
I hate this world
