### ISSUE TITLE
Virologists are labeled "Virology" on crew sensors

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#82163]
Reporting client version: 515.1630

## Round ID:
[225933](https://scrubby.melonmesa.com/round/225933)

## Testmerges:
- [Canonical Movement](https://www.github.com/tgstation/tgstation/pull/82085)
- [Fixes lua error logging and a few timer.lua functions](https://www.github.com/tgstation/tgstation/pull/82160)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/66640614/9cc95139-af59-4e80-84d5-50457e0422a3)

**Comment by 00-Steven** [comment]
So looking at the logs, I think this mayyy have been hop fuckery? Or chameleon ID fuckery.
Because John McJohnson wasn't on the manifest, and the only mention of John McJohnson was from someone else holding the ID.

**Comment by dragomagol** [comment]
I guess you must be right; I don't see any evidence that it was changed, but maybe it was from the cham kit.

**Comment by MrMelbert** [comment]
![image](https://github.com/tgstation/tgstation/assets/51863163/3875bcc9-cba8-4db9-ad70-54bf1cf3e5cb)
