### ISSUE TITLE
polymorphed brimdemons can make a forever brimbeam

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#82177]
Reporting client version: 515.1633

## Round ID:
[225990](https://scrubby.melonmesa.com/round/225990)

## Testmerges:
- [Canonical Movement](https://www.github.com/tgstation/tgstation/pull/82085)

## Reproduction:

1. use polymorph belt to become brimdemon
2. charge beam attack
3. once the beam has formed die
4. forever beam

**Comment by SyncIt21** [comment]
Duplicate #81994. Even though the circumstances are different in both reports the issue is the same because the beam does not delete itself with the brimdemon

**Comment by Sealed101** [comment]
^
