### ISSUE TITLE
flesh worm and whatever else uses what it uses looks jank as fuck

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#82179]
Reporting client version: 515.1633

## Round ID:
[225995](https://scrubby.melonmesa.com/round/225995)

## Testmerges:
- [Canonical Movement](https://www.github.com/tgstation/tgstation/pull/82085)

## Reproduction:

1. be fleshworm
2. move
3. jank

**Comment by Sealed101** [comment]
cool issue bro, care to elaborate? 
like a week ago i tied the worm form out and i saw no quote unquote jank

**Comment by mc-oofert** [comment]
its been 225d since the merge
