### ISSUE TITLE
Variety of TGUI elements working improperly

### ISSUE THREAD

**Issue by OverwatchVoice** [tgstation/tgstation#82175]
## Issue Summary

- "Click-and-drag" vertical sliders highlight the number instead of changing it's value. (For example, pump pressure settings, radio frequency.)
- Editable typefields (Such as IDs of telecommunication machinery or the color settings when customising a color of clothes from a vendor) start empty, even if they should not.
- PDA text message typefield doesn't get cleared out after sending a message. Probably linked to previous entry.

All these issues make what should be trivial actions every player needs to use incredibly tedious, and in the case of telecommunications makes diagnosis of networks / machine IDs impossible.

## Round ID:
[225988](https://scrubby.melonmesa.com/round/225988)

## Testmerges:

[#81886: '[Testmerge Only] [No React Randys] Removes the paralyse from shoving someone while they are knocked down' by necromanceranne at commit 1b0f34a93f](https://www.github.com/tgstation/tgstation/pull/81886)
[#82160: 'Fixes lua error logging and a few timer.lua functions' by Watermelon914 at commit 26ee18b58c](https://www.github.com/tgstation/tgstation/pull/82160)

**Comment by SyncIt21** [comment]
> "Click-and-drag" vertical sliders highlight the number instead of changing it's value. (For example, pump pressure settings, radio frequency.)

This is handled in #82000. You can remove it. With that change your title to specifically talk about input fields. I got an PR coming for that

**Comment by OverwatchVoice** [comment]
I hope this also fixes the triple click required to highlight the number input on sliders, that part's been bugging me too.
