### ISSUE TITLE
APC controller consoles improper functionality on linked Z-level stations

### ISSUE THREAD

**Issue by OverwatchVoice** [tgstation/tgstation#82174]
## Issue Summary

APC control consoles (The ones in CE's office) only have access to unsecure APCs that are in the same Z-level as the console, not the entire station as one would expect. (Tested on tramstation)

## Testmerges:

[#81886: '[Testmerge Only] [No React Randys] Removes the paralyse from shoving someone while they are knocked down' by necromanceranne at commit 1b0f34a93f](https://www.github.com/tgstation/tgstation/pull/81886)
[#82160: 'Fixes lua error logging and a few timer.lua functions' by Watermelon914 at commit 26ee18b58c](https://www.github.com/tgstation/tgstation/pull/82160)

**Comment by SyncIt21** [comment]
Duplicate #72868

**Comment by OverwatchVoice** [comment]
Didn't realise, thank you.

**Comment by OverwatchVoice** [comment]
Didn't realise, thank you.

**Comment by OverwatchVoice** [comment]
Didn't realise, thank you.
