### ISSUE TITLE
Borg RCD can make an absurd number of floors and walls without incurring a significant charge penalty.

### ISSUE THREAD

**Issue by excalisword** [tgstation/tgstation#82193]
Reporting client version: 514.1589

## Issue Summary
most likely due to PR #81579 , the Engineering Cyborg now has a 10000000 roundstart unit amount. However, the amount of units used by each RCD option has not been adjusted to fit this new amount, thus resulting in an absurd amount of anything the RCD can print being able to be printed off a single power cell without any recharging.

## Round ID:
[226024](https://scrubby.melonmesa.com/round/226024)

## Testmerges:
- [Canonical Movement](https://www.github.com/tgstation/tgstation/pull/82085)

## Reproduction:

1. Go engineering cyborg.
2. Grab out your RCD.
3. Select anything and start printing mass quantities of it. Select walls/floors to see the most disparity between old RCD power consumption and joules RCD power consumption.

**Comment by MrMelbert** [comment]
Electroadaptive pseudocircuit is also affected

**Comment by Pickle-Coding** [comment]
> Electroadaptive pseudocircuit is also affected

What even is that?

**Comment by MrMelbert** [comment]
Also just for posterity: 
- Sec batons
- Cyborg stun arm
- Cyborg energy sword
- Cyborg hypospray
- Cyborg projectile dampener
- Defib EMP
- Cell EMP

**Comment by zxaber** [comment]
> > Electroadaptive pseudocircuit is also affected
> 
> What even is that?

it's a consumable that engiborgs get, and can use to take the place of firelock circuits, fire alarm circuits, APC circuits, and what's supposed to be a very small uncharged cell for APCs.

**Comment by moocowswag** [comment]
>Electroadaptive pseudocircuit is also effected

In other words it means borgs can spam out new rooms with new apcs for malf ais to hack, resulting in a much bigger deal than the apparent appraisal.

**Comment by zxaber** [comment]
You still have a stock limit of five uses before you need more supplies. And it's not refilled from a charger; you have to find an APC circuit and add it to your count.
