### ISSUE TITLE
Ninja can't recharge from APCS

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#82215]
Reporting client version: 515.1633

## Round ID:
[226074](https://scrubby.melonmesa.com/round/226074)

## Testmerges:
- [[Testmerge Only] [No React Randys] Removes the paralyse from shoving someone while they are knocked down](https://www.github.com/tgstation/tgstation/pull/81886)
- [Makes lua file upload work with bigger files and standardizes a few file|null](https://www.github.com/tgstation/tgstation/pull/82202)

## Reproduction:
With the recent power changes it seems charging from apcs (Didn't have chance to test wires directly) no longer recharge the ninja modsuit. Requiring you to run around scrounging for power from cells

**Comment by Bilbo367** [comment]
This is fixed, I think it was done in https://github.com/tgstation/tgstation/pull/82227/files#diff-1540cdd6882686f9163c6f30cd5a643e991045a70ad4535b8e86e1a1d818247b
