### ISSUE TITLE
bangammer

### ISSUE THREAD

**Issue by MelokGleb** [tgstation/tgstation#82211]
Reporting client version: 515.1633

## Issue Summary

NAME are stroking the head of NAME with a bangammer.

## Round ID:
none

## Testmerges:

none

## Reproduction:

smack someone with a banhammer toy

**Comment by MrMelbert** [comment]
https://github.com/tgstation/tgstation/blob/71c0293fa716e7c0d2c601e070e0d2f940c9f42a/code/game/objects/items/weaponry.dm#L29-L34
