### ISSUE TITLE
Gunpowder pills explode

### ISSUE THREAD

**Issue by iansdoor** [tgstation/tgstation#82217]
I love gunpowder, but in a pill aka (container) they explode and when there is 362* pills that explode cause the pills are jumping around, this stopped the server by the sheer overlays made and smoke. Iansdoor/(Vents-Hot-Air) deleted all objects of type /obj/effect/particle_effect/expl_particles (3640 objects deleted)

Edited the number pills that exploded in a small time frame.

**Comment by deathrobotpunch** [comment]
how would you fix this without making pills not containers or hardcoding gunpowder to be unpillable?

**Comment by SyncIt21** [comment]
This isn't a bug and just bad gameplay. Gun powder pills are meant to explode so don't make a shit ton of them cause a shit ton of anything will lag any game.

**Comment by iansdoor** [comment]
> This isn't a bug and just bad gameplay. Gun powder pills are meant to explode so don't make a shit ton of them cause a shit ton of anything will lag any game.
> 
> What did you expect to happen with a whopping 120 pills of gunpowder? Stuff works as expected

Cool, I asked admins and oranges told me to report it. 120+ pills of gunpowder explodes in a chain and stops the server. I haven't the slightest idea why you don't see an issue with that.

**Comment by SyncIt21** [comment]
> 120+ pills of gunpowder explodes in a chain and stops the server. I haven't the slightest idea why you don't see an issue explodiing 

Explodiing 362 of anything all at once will lag/crash the server. Whoever did dumb shit like this should be banned and it isn't a problem with a codebase.

The only issue I see here is with the person who decided this was a good idea. 

There is no feasible solution here besides preventing gun powder from being put in capsules and nobody likes that solution

**Comment by deathrobotpunch** [comment]
it’s really easy to make 362 pills of gunpowder

**Comment by SyncIt21** [comment]
> it’s really easy to make 362 pills of gunpowder

Then we should nerf gun powder from being put In pills. Good luck trying to push for that change cause I would definitely downvote that PR

**Comment by moocowswag** [comment]
We have imposed hard limits in the past over similar things and nothing is stopping us from pulling out old-reliable again.

**Comment by Sadboysuss** [comment]
> it’s really easy to make 362 pills of gunpowder

do you have any suggestions to fix this

**Comment by Sadboysuss** [comment]
> > > it’s really easy to make 362 pills of gunpowder
> > 
> > 
> > do you have any suggestions to fix this
> 
> if you want my suggestion. What really got the server was the overlays, there was so many. I think gunpowder making smoke is fine for the tell. explosive visual was 8 overlays attempting to move away from the epicenter.

so you think removing smoke will help with this issue?

**Comment by iansdoor** [comment]
> > > > it’s really easy to make 362 pills of gunpowder
> > > 
> > > 
> > > do you have any suggestions to fix this
> > 
> > 
> > if you want my suggestion. What really got the server was the overlays, there was so many. I think gunpowder making smoke is fine for the tell. explosive visual was 8 overlays attempting to move away from the epicenter.
> 
> so you think removing gunpowder smoke will help with this issue?

Maybe? The main issue to me was the visual overlays attempting to cross tiles. Each pill made 8 of those expl_particles and they would travel 2 tiles outerwards from epicenter. Iansdoor/(Vents-Hot-Air) deleted all objects of type /obj/effect/particle_effect/expl_particles (3640 objects deleted). This was basically all chemistry and a good deal of Maintenace.

**Comment by ZephyrTFA** [comment]
362 of anything exploding will cause lag.
This is an admin issue not a codebase issue.
