### ISSUE TITLE
Contractor PDA from traitor contractor kit doesnt work

### ISSUE THREAD

**Issue by KickPaw** [tgstation/tgstation#82229]
Reporting client version: 515.1633

## Issue Summary

Contractor PDA from traitor contractor kit doesn't work. It doesn't depend on charge, syndicate implant, cell, ID card in it etc. Maybe the reason is PR with converting every energy units to joules: https://github.com/tgstation/tgstation/pull/81579

## Round ID:
[226108](https://scrubby.melonmesa.com/round/226108)

## Testmerges:
- [[Testmerge Only] [No React Randys] Removes the paralyse from shoving someone while they are knocked down](https://www.github.com/tgstation/tgstation/pull/81886)

## Reproduction:

buy traitor contractor kit, get the message in chat that power button does nothing

**Comment by lessthnthree** [comment]
Confirmed it occured in round 226112 as well.

**Comment by necromanceranne** [comment]
probably related to https://github.com/tgstation/tgstation/issues/82196
