### ISSUE TITLE
Space heater cell drains near instantly

### ISSUE THREAD

**Issue by lessthnthree** [tgstation/tgstation#82228]
## Issue Summary

After https://github.com/tgstation/tgstation/pull/82197 the space heater consumes its cell nearly instantly.

## Reproduction:

15c change, hyper cell

Before https://github.com/tgstation/tgstation/pull/82197

https://github.com/tgstation/tgstation/assets/83487515/e2dcc9ad-0d1c-4125-a065-59076d29787b

After

https://github.com/tgstation/tgstation/assets/83487515/2b15d03b-b78a-428d-9520-834cb80f4e17

**Comment by SyncIt21** [comment]
I scaled efficiency down by 1000 which was suggested in https://github.com/tgstation/tgstation/pull/82197#discussion_r1536821690. Don't know what went wrong/right after? @Pickle-Coding thoughts?

**Comment by Pickle-Coding** [comment]
Oh. I already scaled the efficiency variable in my energy PR, so we scaled it twice. Just undo that I guess.

**Comment by SyncIt21** [comment]
> Oh. I already scaled the efficiency variable in my energy PR, so we scaled it twice. Just undo that I guess.

I think i addressed the issue in https://github.com/tgstation/tgstation/pull/82208#issuecomment-2018641091?

**Comment by Pickle-Coding** [comment]
> > Oh. I already scaled the efficiency variable in my energy PR, so we scaled it twice. Just undo that I guess.
> 
> 
> 
> I think i addressed the issue in https://github.com/tgstation/tgstation/pull/82208#issuecomment-2018641091?

https://github.com/tgstation/tgstation/pull/82208#issuecomment-2018648711
