### ISSUE TITLE
Contractor tablet does not work

### ISSUE THREAD

**Issue by plutori** [tgstation/tgstation#82245]
Reporting client version: 515.1630

## Issue Summary

The contractor tablet does not work. Attempting to turn it on returns a message of "You press the power button but the contractor tablet does not respond." and nothing else happens.

## Round ID:
[226145](https://scrubby.melonmesa.com/round/226145)

## Testmerges:
- [[Testmerge Only] [No React Randys] Removes the paralyse from shoving someone while they are knocked down](https://www.github.com/tgstation/tgstation/pull/81886)
- [Makes lua file upload work with bigger files and standardizes a few file|null](https://www.github.com/tgstation/tgstation/pull/82202)

## Reproduction:

1. Be a syndicate infiltrator
2. Buy a contract kit
3. Try to turn on your contractor tablet
4. cry

**Comment by KickPaw** [comment]
yeah, i've reported it already. sad bug
