### ISSUE TITLE
Using TK, you can beat people with items you embeded into them with TK grab.

### ISSUE THREAD

**Issue by SeikoTheSeal** [tgstation/tgstation#8225]
Grab an item with TK, embed it into someone and then beat them and everyone around them with it to death while that can do nothing to counter it (besides pulling the item out, but you'll be dead before you manage to do that).

Not really a bug i guess, but even a damn rod or glass shard becomes super lethal, ranged weapon with TK. And people cant even save said person without taking down the TK user becouse they will get beaten to death by the item embeded into the victim.

![image](https://cloud.githubusercontent.com/assets/10717398/6546287/c520cc02-c5ae-11e4-83ed-f6be60bec906.png)

**Comment by WJohn** [comment]
That's actually really awesome. It's more like shifting the item stuck in their guts around. Given some desc changes when that happens, this could become a really cool feature.

**Comment by SeikoTheSeal** [comment]
Still tho, beating people around the victim with a glass shard stuck into someones head? This also works if the item is in someones backpack, also possible to beat the carrier and people around with TK grabbed item.

**Comment by Anonus** [comment]
This has been a bug for a while; if you grabbed an item and someone picked it up, you could use it to beat them and people near them

**Comment by PKPenguin321** [comment]
@Anonus that has never not been a feature
this is pretty cool too and i think it should stay

**Comment by WJohn** [comment]
This'd make you closer to magneto, you can't lift people so much, but if you threw a chunk of steel through them, THEN you could toss em around with that.

**Comment by phil235** [comment]
Probably check that the item's loc is a turf when trying to use the telekinetic grab, if it isn't a turf, we deleted the tk grab.

**Comment by PKPenguin321** [comment]
shouldnt even be considered a bug
