### ISSUE TITLE
Of TK and Syringes

### ISSUE THREAD

**Issue by TheSadFox** [tgstation/tgstation#8226]
TK grab a syringe and embed it into someone, inject them with said syringe, once syringe falls out this happens.

![image](https://cloud.githubusercontent.com/assets/10717398/6546333/5e6a0738-c5b0-11e4-8719-72576ab92e21.png)

Picking up the syringe fixes it.

**Comment by ike709** [comment]
name it "Of TK and Syringes"

**Comment by SeikoTheSeal** [comment]
Dun and dun.

**Comment by RemieRichards** [comment]
Stupid title. I hate this "Of X and Y" stuff.

**Comment by Cheridan** [comment]
Embed it into someone? Like, surgically implant or what?

**Comment by SeikoTheSeal** [comment]
Embeded by moving the syringe on the same tile the mob is. Or just throwing it at them.

**Comment by tedward1337** [comment]
Is this stil an issue?

**Comment by XDTM** [comment]
I doubt syringes can embed now.

**Comment by optimumtact** [comment]
Yeah likely overhauled
