### ISSUE TITLE
Emagged medibots only hurt people when they're already damaged

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#82261]
Reporting client version: 515.1633

## Round ID:
[226188](https://scrubby.melonmesa.com/round/226188)

## Testmerges:
- [[Testmerge Only] [No React Randys] Removes the paralyse from shoving someone while they are knocked down](https://www.github.com/tgstation/tgstation/pull/81886)
- [Makes lua file upload work with bigger files and standardizes a few file|null](https://www.github.com/tgstation/tgstation/pull/82202)

## Reproduction:
Playing Revenant this round I noticed none of the medibots I was emagging were actually poisoning people. Then it turned out they only did so if the person was already damaged

**Comment by ZephyrTFA** [comment]
when emagged medibots damage by the amount they should have healed.
and if the player doesn't have any damage that amount is zero
