### ISSUE TITLE
Ordnance Chamber Ignition Switch only ignites briefly, not creating fire

### ISSUE THREAD

**Issue by o-d-a-z** [tgstation/tgstation#82294]
Reporting client version: 515.1633

## Issue Summary

Ordnance chamber ignition switch on Icebox immediately disengages itself without ever creating fire

## Round ID:
[226311](https://scrubby.melonmesa.com/round/226311)

## Testmerges:
- [[Testmerge Only] [No React Randys] Removes the paralyse from shoving someone while they are knocked down](https://www.github.com/tgstation/tgstation/pull/81886)
- [Makes lua file upload work with bigger files and standardizes a few file|null](https://www.github.com/tgstation/tgstation/pull/82202)

## Reproduction:
I put 1000 mol of Oxygen in the chamber and started feeding plasma. I pressed the ignition switch which should create fire for tritium but instead it only lights up for a second and then turns off. Was able to light the mix manually using a lighter
Try use combustion chamber ignition switch  in Ordnance on Icebox
Switch turns on briefly then immediately off

I think it's related to the power stuff I have no idea though

**Comment by SyncIt21** [comment]
This bug is more serious than it looks as it affects all types of machinery.

Upon running through the debugger `use_energy()` for the igniter fails because the area in which the igniter is located does not have a apc

![Screenshot (407)](https://github.com/tgstation/tgstation/assets/110812394/e587259d-0ff1-4cde-9b95-0aed584461c0)

We have 2 options

a) Pass `ignore_apc = TRUE` to this proc so we don't need one to run. But then we should have a debate on when should machinery use this var and when not to

b) Modify `use_energy()` to somehow work without a apc.

@Pickle-Coding your expertise is mush required here

**Comment by Pickle-Coding** [comment]
use_energy() was designed for machines to use their APC or the APC's grid. Didn't really expect there to be machines without APCs to use this in non magic power areas.

For this case it seems like we should link the ordnance chamber or whatever to an APC. If a machine should be able to run without an APC, it should be turned into a power machinery and connect to the powernet via cable.

I'd go with option C, then go with option D (reworking some machines to power machinery that connect to cables) for cases where C isn't feasible.

**Comment by SyncIt21** [comment]
> I'd go with option C, then go with option D (reworking some machines to power machinery that connect to cables) for cases where C isn't feasible.

We goanna have to wait for a mapper to tackle this then. This issue might be open for a while :(.

**Comment by Iamgoofball** [comment]
you can't put an APC in the burn chamber, it'll literally get destroyed
cable may have the same issue

**Comment by SyncIt21** [comment]
> you can't put an APC in the burn chamber, it'll literally get destroyed
> cable may have the same issue

We don't put an apc but merge the burn chamber with the rest of ordanance lab and make it one area. Just like the incinerator room in atmospherics, the igniter works there

**Comment by Iamgoofball** [comment]
That will then set off the fire alarm every time they do a burn.

**Comment by SyncIt21** [comment]
> That will then set off the fire alarm every time they do a burn.

Yeah i don't understand how atmospherics incinerator chamber did it correctly. We have to follow that example somehow

**Comment by Pickle-Coding** [comment]
It would only set it off if the fire was next to a firelock or fire alarm.

Also cables under reinforced floors are safe from fire.

**Comment by Singul0** [comment]
in the mean time you can get a signaller and igniter assembly to ghetto ignite the burn chamber
