### ISSUE TITLE
Slimes taken out of BZ keep stasis effect

### ISSUE THREAD

**Issue by Thlumyn** [tgstation/tgstation#82300]
## Issue Summary

Slimes taken out of BZ keep stasis effect forever. This means they can no longer be used for xenobiology beyond just killing them. 

Happened since the merge of this: https://github.com/tgstation/tgstation/pull/82176

## Round ID:

(testing on private server)

## Reproduction:

Put a slime in a BZ filled room. Take it out. They don't lose the stasis effect

**Comment by Profakos** [comment]
I'll take a look asap.

**Comment by Profakos** [comment]
The reason is that the stasis handling part had to be moved to handle_environment. This is not called when the target is in stasis.
