### ISSUE TITLE
CI Uses Global Node (v18) instead of switching to Node v14 like we try and get it to

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#82315]
## Issue Summary

Per `install_node.sh`:

```bash
#!/bin/bash
set -euo pipefail

source dependencies.sh

if [[ -e ~/.nvm/nvm.sh ]]; then
	source ~/.nvm/nvm.sh
	nvm install $NODE_VERSION
	nvm use $NODE_VERSION
fi
```

$NODE_VERSION here is set to `14`. However, CI will use the Global Node version `18` (as you can see in this following excerpt):
![image](https://github.com/tgstation/tgstation/assets/34697715/14fa67d4-f77e-4098-9b45-71dc707bc840)
![image](https://github.com/tgstation/tgstation/assets/34697715/357bdfe8-9b8a-40a0-a62e-7ffd84ce00ba)

This occurs on both Windows (Compile Windows) and Linux (Compile Maps) as seen in the screenshots above. You can view the CI runs here: https://github.com/tgstation/tgstation/actions/runs/8488367763

Anyways, this is only an issue because we are compatible with Node 14 in order to accomodate to Windows 7 users (this is just a basic fact) and currently the whole Node 14 compatibility could break at any point, silently (!!!), since GitHub seems to pull the system-wide Node instead of the version we want it to use. This could cause some grief later on (or is currently causing grief to Windows 7 users), just need to figure out a way to make it actually respect the `nvm use` command we use in the aforementioned script.

**Comment by jlsnow301** [comment]
Now uses matching versions (20)

**Comment by LikeLakers2** [comment]
@jlsnow301 I don't believe this issue is fixed. I noticed that, even in one of the latest commits, it still appears to say `Using system-wide Node v18.20.3`. https://github.com/tgstation/tgstation/actions/runs/9622277404/job/26543372300#step:4:8

This doesn't appear to be a big issue since it compiles successfully anyways, but perhaps look into ensuring it actually uses Node v20 in the CI?

**Comment by jlsnow301** [comment]
> @jlsnow301 I don't believe this issue is fixed. I noticed that, even in one of the latest commits, it still appears to say `Using system-wide Node v18.20.3`. https://github.com/tgstation/tgstation/actions/runs/9622277404/job/26543372300#step:4:8
> 
> This doesn't appear to be a big issue since it compiles successfully anyways, and from what I can tell, win7 compilation is done using a slightly older version of Node v20... but perhaps look into ensuring it actually uses Node v20 in the CI anyways?

Pure speculation on my part, but it might be cached. It looks like these CI steps are each referring to the same cache, `Linux-byond-47e9f`

**Comment by LikeLakers2** [comment]
@jlsnow301 I don't believe this has to do with the Github caches, as I deleted all caches on my Monkestation fork, then reran the workflows on a branch that was set up to use Node v20. Yet, it still wants to use the system-wide Node v18. https://github.com/LikeLakers2/Monkestation2.0/actions/runs/9625186459/job/26558340333

**Comment by san7890** [comment]
Hopefully whatever this was is purged in the post-bun world (especially post-#96949)
