### ISSUE TITLE
Ordering more of a material than exists on the market causes prices to spike higher than possible.

### ISSUE THREAD

**Issue by ArcaneMusic** [tgstation/tgstation#82329]
Goddamnit.

## Issue Summary

As the title says, when using the stock market, both the prices and the quantities of materials fluxuate with every fire of the SSstock_market subsystem. Both quantity and value are bounded by a maximum and minimum defined by the material datum.

Price minimums and maximums are 0.5 * the value of a sheet to 3 * the value of a sheet.
Quantities can vary from 0, to double the trading quantity, defined by the material's `tradable_base_quantity`.

When buying and selling a material, the change in demand will cause the price to increase or decrease as well, so that repeated sales will decrease the value while purchasing will cause a small uptick in value.

This was reported downstream as follows, and reproduced by me this afternoon:
> Don’t have a GitHub 
> But how it works is you buy more materials then the market has, and the price will skyrocket to 100k+ per sheet

![image](https://github.com/tgstation/tgstation/assets/41715314/b25f4d30-5e86-4a99-b306-2a84ebcb1210)
If the natural quantity available becomes less than the amount you're attempting to order, the order can still go through, but the price adjustment that occurs when the shuttle is sent causes something like the following to happen:

![image](https://github.com/tgstation/tgstation/assets/41715314/7a35c286-ccb7-4930-b8ce-db084593b60d)

This is likely due to the price formula not accounting for going overstock.

## Round ID:

N/A, produced locally on date of posting (3/30/2024)

## Testmerges:

n/a, running on clean master.

## Reproduction:

* Spawn in.
* Collect enough money to buy all of the current available stock for a given material (The material must have <500 sheets, since you can only place 10 stacks worth of sheets coming in at a single time.
* Place an order within the stock market ui for a quantity high enough to buy out the entire stock.
* Wait for the stock market to update so that the quantity goes down, without cancelling your order.
* Place the order to buy your quantity of that material over what exists on the market.
* Wait for the price to skyrocket, before it gets clamped by the next stock market tick.
* Create disgusting levels of profit.

**Comment by 00-Steven** [comment]
oh boyyy
