### ISSUE TITLE
Borg built-in station alerts not functioning

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#82345]
## Issue Summary
Station alerts currently on the borg UI show as always *systems nominal*

![image](https://github.com/tgstation/tgstation/assets/96586172/daabb3bb-dc32-4505-bc7e-f716cd28ebf7)

## Round ID:
[226431](https://scrubby.melonmesa.com/round/226431) Manuel

## Reproduction:
compare station alert menus of a console and borg UI

**Comment by StrangeWeirdKitten** [comment]
When a borg initalizes, the alert UI does not properly update with current alarms. It instead only updates when new alarms are generated.

**Comment by Sadboysuss** [comment]
> When a borg initalizes, the alert UI does not properly update with current alarms. It instead only updates when new alarms are generated.

I believe I was a round start borg that round so I'm not sure if that's true

**Comment by Sadboysuss** [comment]
closing in favor of (dupe) https://github.com/tgstation/tgstation/issues/83042
