### ISSUE TITLE
Trying to pick your alcoholic settings will give a bluescreen

### ISSUE THREAD

**Issue by DATA-xPUNGED** [tgstation/tgstation#82346]
Reporting client version: 515.1633

## Issue Summary

![image](https://github.com/tgstation/tgstation/assets/44149906/a6a06c84-855c-495e-a942-b94f4e630e16)
I wasn't done with my PR...

## Round ID:
[226431](https://scrubby.melonmesa.com/round/226431)

## Testmerges:
- [[Testmerge Only] [No React Randys] Removes the paralyse from shoving someone while they are knocked down](https://www.github.com/tgstation/tgstation/pull/81886)
- [Makes lua file upload work with bigger files and standardizes a few file|null](https://www.github.com/tgstation/tgstation/pull/82202)

## Reproduction:

- Give your character the alcoholic quirk
- Press the cogwheel

**Comment by Jacquerel** [comment]
well then finish it and next time mark draft PRs as draft

**Comment by DATA-xPUNGED** [comment]
> well then finish it and next time mark draft PRs as draft why are you even posting this instead of doing that?

Might aswell make the issue myself so someone in the near future doesn't have to
