### ISSUE TITLE
Eigenstasium no longer links lockers when thrown or sprayed.

### ISSUE THREAD

**Issue by iansdoor** [tgstation/tgstation#82353]
![no linked lockers](https://github.com/tgstation/tgstation/assets/109386467/70f262f2-ff2a-450a-a148-d95012690b53)
No more Eigenstasium lockers, not sure what even broke them. Iain and I tested them, trying to add properties and purity. The chemical doesn't take.
![Screenshot_217](https://github.com/tgstation/tgstation/assets/109386467/96c15a2c-aa2f-4f2b-b72e-705af3a0cfa9)

**Comment by moocowswag** [comment]
there was a station trait pr that had some lockers linked at round start, maybe that might have broke something.

**Comment by iansdoor** [comment]
> there was a station trait pr that had some lockers linked at round start, maybe that might have broke something.
Was there? That is actually cool! I love those stupid lockers
Either way, the chemical adding is broken or did the PR block more being made on that station trait?

**Comment by moocowswag** [comment]
It shouldnt have blocked making new ones but it likely touched the code involved with lockers being linked.
