### ISSUE TITLE
Reticence UI is just a bluescreen.

### ISSUE THREAD

**Issue by iansdoor** [tgstation/tgstation#82374]
Click the UI to Reticence and you get this.
![Screenshot_218](https://github.com/tgstation/tgstation/assets/109386467/f8c5d359-7ea4-48a6-8c33-386b5b5788cd)
Reported by a player in a ticket today and yesterday.

**Comment by jlsnow301** [comment]
Attempts to map over a null value, likely something not being sent from backend
