### ISSUE TITLE
Minebots are incredibly dangerous

### ISSUE THREAD

**Issue by ZeroKelvn** [tgstation/tgstation#82396]
Reporting client version: 515.1632

## Issue Summary
There's two issues I found with the Minebots this round.
1. Minebots are susceptible to taking damage from Offensive Explosion PKAs that have Minebot Passthrough, effectively negating the point of having it in the first place. This also applies to humans with the Human Passthrough.
2. Minebot landmines can be set off by and destroy other Minebots, and the explosion can hurt Miners as well. It's possible that miners can set these off as well, though this occurred with admin-spawned Minebots when testing. Still, I think the original PR said Miners wouldn't set them off either, so it's an issue.

## Round ID:
[226527](https://scrubby.melonmesa.com/round/226527)

## Testmerges:
- [[April Fools] [MBD Ignore] Tramstation is now a part of The NanoTrasen -Childrens- FunZone! Pizza Chain](https://www.github.com/tgstation/tgstation/pull/82379)
- [The Great Saiyan Race](https://www.github.com/tgstation/tgstation/pull/82347)
- [Adds Frieza Midround Antagonist](https://www.github.com/tgstation/tgstation/pull/82368)
- [[april fools] Makes robotics more realistic](https://www.github.com/tgstation/tgstation/pull/82351)

## Reproduction:
1. Get a few Minebots under your control
2. Sic them on some Lavaland fauna
3. Watch them all die horribly and maybe kill you in the process

**Comment by iansdoor** [comment]
As a large mining bot user myself. 
Offensive Explosion PKA deals damage in a 3x3. miner bot or human, you should hit everything.
Yeah, I think the issue of them first action is dropping mines and them walking into them kills a clump of bots. Why I turn them off now by hand.
With all that said, Mining bots only die to AoE abilities and melt everything else in numbers. Goliaths in particular, wreck mining bots.

**Comment by san7890** [comment]
@Ben10Omintrix i forgot, did you do a rework of minebots?
