### ISSUE TITLE
Borg chargers charge slow and ignore upgrades

### ISSUE THREAD

**Issue by Kubisopplay** [tgstation/tgstation#82406]
## Issue Summary
Borg chargers charge much slower compared to before the power rework, around 0.1 to 0.3 % of default cell per tick, and they dont change that speed when upgraded, or when VVd.

## Reproduction:
Go engiborg, use your cell, try to charge.

**Comment by Metekillot** [comment]
Borg charger speed is now reliant on the amount of power in the network at the moment as I recall from my playing of borg after the rework. Could you try to reproduce this with differing levels of power in the network?

**Comment by Kubisopplay** [comment]
Alright, that explains everything. Should probably specify the charging power is the max rated power then.
