### ISSUE TITLE
birdbox map atmos doesn't work properly 

### ISSUE THREAD

**Issue by ClingFoil** [tgstation/tgstation#82409]
## Issue Summary
It seems that some of atmos on the Birdbox map isn't properly connected or labeled. An example for this would be the layer adapter connecting the distro to the pure pipe on the southside, with those pipes along the adapter on the north and south side also being mislabeled. Also the O2 supply seemed to run out not that far into the round. There may be more of these faults around atmos in Birdbox please check it out when you can. 

## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
N/A

**Comment by Zytolg** [comment]
A fix for this went live a few hours ago. https://github.com/tgstation/tgstation/pull/82380

**Comment by projectkepler-ru** [comment]
@ClingFoil @Ghommie  think this is good to close?
