### ISSUE TITLE
cyborgs out of cyborg factory come with shit cells which go down to 0 after 3 seconds or so

### ISSUE THREAD

**Issue by vertolodka** [tgstation/tgstation#82426]
Reporting client version: 515.1630

## Issue Summary
cyborgs out of cyborg factory come with shit cells which go down to 0 after 3 seconds or so

## Round ID:
[226601](https://scrubby.melonmesa.com/round/226601)

## Testmerges:
- [Compiling the servers works again](https://www.github.com/tgstation/tgstation/pull/82420)

## Reproduction:
place cyborg factory
get human into it
get cyborg with cell that have 5000 max capacity, while roundstart borgs have 10 millions.

**Comment by Jacquerel** [comment]
Be careful about making issue reports about ongoing rounds, they get reported in the Discord channel when posted so technically you could be revealing what is supposed to be secret information.

**Comment by GPeckman** [comment]
https://github.com/tgstation/tgstation/blob/3c71b14df0957749f31fb2e678130daf4cfb3250/code/game/machinery/transformer.dm#L23

This is the cause, should probably be changed to `5 MEGAJOULES`

**Comment by StrangeWeirdKitten** [comment]
> https://github.com/tgstation/tgstation/blob/3c71b14df0957749f31fb2e678130daf4cfb3250/code/game/machinery/transformer.dm#L23
> 
> This is the cause, should probably be changed to `5 MEGAJOULES`

No, bluespace cells have 4 megajouls. It should be changed to 1 megajoul
