### ISSUE TITLE
Some of RND discount experiments don't work

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#82421]
## Issue Summary 

Experiments where you have to scan a certain material don't work (chairs, walls, etc). Machinery upgrade and ordnance experiments work fine.
![Screenshot_17](https://github.com/tgstation/tgstation/assets/64209864/5bde4fae-55ee-4bd4-84d5-a4a9393914f2)

## Testmerges: 
#82347: 'The Great Saiyan Race' by Jacquerel at commit 5c3e6171af 
#82368: 'Adds Frieza Midround Antagonist' by IndieanaJones at commit 56a7a98d2a 
#82371: '[April Fools] Makes the multitool into a multimeter like god intended' by EricZilla at commit b56ae69735 
#82362: '[April Fools] Restart votes are now weighted random' by Crushtoe at commit 287169febe 
#82370: '[APRIL FOOLS] renames the Head of Personnel job to better suit emergent play patterns' by ATH1909 at commit 1cb2c67cfe 
#82379: '[April Fools] [MBD Ignore] Tramstation is now a part of The NanoTrasen -Childrens- FunZone! Pizza Chain' by Zytolg at commit bb8396eb97 
#82340: '[IDB IGNORE] Adds pAI avatar mode' by AnturK at commit c58885c53d

**Comment by iansdoor** [comment]
Can't even do industrial either.
![Screenshot_223](https://github.com/tgstation/tgstation/assets/109386467/00d53f1a-fd7c-4566-bb80-e2b9bfe1ccde)
