### ISSUE TITLE
Alcoholic trait customize menu NtOS

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#82433]
![obraz](https://github.com/tgstation/tgstation/assets/68878861/c665e4a6-a5df-4c9a-8769-c0a0cd0a2e28)
![obraz](https://github.com/tgstation/tgstation/assets/68878861/c54330ff-3f31-428f-b2d5-f9ea6346e4e2)

## Issue Summary
Trying to press the cog button bluescreens instead of a dropdown menu.
Other customizable traits are fine.

## Round ID:
[226613](https://scrubby.melonmesa.com/round/226613)

## Testmerges:
[#82420: 'Compiling the servers works again' by ZephyrTFA at commit 4751ed5b19](https://www.github.com/tgstation/tgstation/pull/82420)

## Reproduction:
Select the trait.
Click the cog button.

**Comment by 00-Steven** [comment]
Duplicate of #82346.

**Comment by Likteer** [comment]
Dupe, issue solved
