### ISSUE TITLE
Narsie Shits Out Tons of Harvesters With No Players Controlling Them

### ISSUE THREAD

**Issue by IndieanaJones** [tgstation/tgstation#82445]
## Issue Summary

Something's causing Narsie to spawn in Harvesters with no souls, and every time a ghost does something that would make them a harvester it spawns a new empty one.

## Round ID:

[226635](https://scrubby.melonmesa.com/round/226635)

## Testmerges:

[#82416: 'Creates a "busy" animation for players' by jlsnow301 at commit ac6d4648ea](https://www.github.com/tgstation/tgstation/pull/82416)

## Reproduction:

- Summon Narsie
- ???
- After a couple of normal interactions, Narsie will begin creating soulless harvesters en masse

**Comment by ATH1909** [comment]
I'm not cult banned, and I was also unable to become a harvester by clicking on nar'sie in two separate rounds (barring one instance where I became one when nar'sie spawned but couldn't respawn as one)

**Comment by BanementI** [comment]
deja vu, ive seen a similar issue like this before a while ago, https://github.com/tgstation/tgstation/issues/72150
