### ISSUE TITLE
Deathmatch can send you to nullspace

### ISSUE THREAD

**Issue by jughu** [tgstation/tgstation#82466]
## Issue Summary
Was playing deathmatch on the underground thunderdome map with the modifiers triple health no wounds and thermal vision. instead we got send to the secret room and we could enter the station with this very modifiers this could be a issue with instagib map

## Reproduction:
Dunno play till it happens?
![image-51](https://github.com/tgstation/tgstation/assets/14280283/054731ea-a1fe-4e72-b86d-7d271954f551)

**Comment by mc-oofert** [comment]
Something is somehow passing null location to the spawn player proc, this is gonna need extra logging or reproduction steps to figure out how

**Comment by mc-oofert** [comment]
On second thought this might have something with the lazy template loaded signal;
Possible reproduction might be starting two games with the same map at once (possible delay too maybe?)
