### ISSUE TITLE
Medibots can be thrown into doors to open them

### ISSUE THREAD

**Issue by Deadgebert** [tgstation/tgstation#82475]
## Issue Summary

Medibots can be _**aggro grabbed**_ and thrown into doors to open them
https://www.youtube.com/watch?v=6TlEMjaryuQ

## Round ID: 
[226654](https://scrubby.melonmesa.com/round/226654)

## Testmerges:

[#82458: 'Cleans up the SS13_base lua file and adds a new lua file for easily handling multiple signals on different objects.' by Watermelon914 at commit 785ac3a525](https://www.github.com/tgstation/tgstation/pull/82458)

## Reproduction:

> Be assistant
> Drag medibot around
> Throw at any door you wish to open

**Comment by Jacquerel** [comment]
Hmm, I mean this isn't a _bug_ per se in that this is the logical result of those actions (throwing something against a door means it tries to open that door, and medbots have all access).  
Not sure we want all access cards to be functionally printable in robotics (unless they are called cyborgs) though, tricky one.

**Comment by Likteer** [comment]
> throwing something against a door means it tries to open that door

Funnily enough, I think throwing actual people with IDs into doors has been broken for a while.

**Comment by xzero314** [comment]
The actual issue here is that all of a sudden bots all of AA. Its a recent thing

**Comment by Deadgebert** [comment]
bots have always had AA, but medibots specifically can suddenly be aggro grabbed, which allows them to be thrown

**Comment by xzero314** [comment]
Up until recently as ai ive always had to let sentient bots out of the SAT myself so they for sure had some limits. I noticed all of a sudden that they hey AA when a clown bot let itself all the way into my core.

**Comment by Deadgebert** [comment]
i think the best fix would be that medibots shouldn't be able to be aggro grabbed. no other bots can be thrown like this.
