### ISSUE TITLE
ethereal not being able to eat power

### ISSUE THREAD

**Issue by unknown-user397** [tgstation/tgstation#82470]
Reporting client version: 515.1634

## Issue Summary

ethereal eating gives no power issue. When I do try to get power from a light, borg charger or even eat a energy bar, no power happens instead of getting power

## Round ID:
 226675

## Testmerges:
- [Creates a "busy" animation for players](https://www.github.com/tgstation/tgstation/pull/82416)

## Reproduction:

 when i joined the sever the first thing i did was grab a suit and got insulated gloves. then when i noticed my power running i went to a light to grab some power then when that wasn't working i went to the borg charger and when that didn't help i tried to eat a power bar then i took off my suit. I still had the same problems i even tried to take off my gloves and that didn't work

**Comment by Pickle-Coding** [comment]
Guess I forgot about those cases. In the meantime, you can try to charge from the APCs.

**Comment by unknown-user397** [comment]
how would i charge from the APCs?

**Comment by unknown-user397** [comment]
> Guess I forgot about those cases. In the meantime, you can try to charge from the APCs.

how do i charge from the APCs?

**Comment by Pickle-Coding** [comment]
Either left, right, alt or ctrl click it I think. There should be a screentip at the top that tells you which one when you hover your cursor over it.

**Comment by wesoda25** [comment]
> > Guess I forgot about those cases. In the meantime, you can try to charge from the APCs.
> 
> how do i charge from the APCs?

Right click while on combat mode to steal power from an APC, if you do it while off of combat mode you will instead feed it power
