### ISSUE TITLE
Can't hide items in cheese/bread

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#82480]
![obraz](https://github.com/tgstation/tgstation/assets/68878861/dddba2f3-18da-4d42-b81c-ab8145a9d40e)

## Issue Summary
Bread gives a balloon alert. Cheese wedge does nothing. Dunno if there are any other foods intended for that (tried a birthday cake too).

## Round ID:
[226701](https://scrubby.melonmesa.com/round/226701)

## Testmerges:
[#82458: 'Cleans up the SS13_base lua file and adds a new lua file for easily handling multiple signals on different objects.' by Watermelon914 at commit ad53a75b2b](https://www.github.com/tgstation/tgstation/pull/82458)

## Reproduction:
Click with a small item on a loaf of bread or a cheese wedge.

**Comment by Metekillot** [comment]
I'm not able to reproduce this. When I right click an empty bread loaf with a small item, it slips inside.

**Comment by Likteer** [comment]
ok it worked on rmb with combat mode off, thx

**Comment by Likteer** [comment]
ok it worked on rmb with combat mode off, thx
