### ISSUE TITLE
Races that don't feel hunger are still slower when they have not eaten

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#82482]
I swear I'm not crazy
## Issue Summary
This is independent of mood & sanity ofc, or even the "hand-crafted meal" status added by "The Foodening" PR.

Maybe intended, though I'd assume not feeling hunger would just lock you out of food-based moodboosts, not speed from... not feeling hungry.

## Round ID:
[226706](https://scrubby.melonmesa.com/round/226706)

## Testmerges:
[#82458: 'Cleans up the SS13_base lua file and adds a new lua file for easily handling multiple signals on different objects.' by Watermelon914 at commit 785ac3a525](https://www.github.com/tgstation/tgstation/pull/82458)

## Reproduction:
Play something like plasmaman.
Max out mood & sanity. Note the speed.
Eat nutritious food. Note the speed.
Return to normal when the nutriment is gone from your body (?)

**Comment by Metekillot** [comment]
Do you remember what food you ate?

**Comment by Likteer** [comment]
> what food

1st warm Honk Pocket, then I went for smth less peculiar, to confirm: a grilled cheese sandwich, a cheese burger, and a custom cheese wedge burger.
