### ISSUE TITLE
Disassembling tables with wrench no longer gives iron rods.

### ISSUE THREAD

**Issue by Dman757** [tgstation/tgstation#82503]
## Issue Summary

Noticed when disassembling a table with a wrench that iron rods aren't generated. Only a single piece of iron is returned.

Same for screwdriver.

## Testmerges:

After looking at the table/frame files and doing a blame I came across this recent change and left a comment on the potentially offending code https://github.com/tgstation/tgstation/pull/82280#pullrequestreview-1984476683

I haven't contributed to this codebase in years so take my guess with a grain of salt.

## Reproduction:

1. Grab 2 pieces of iron + wrench
2. Turn one sheet into rods
3. Create Table Frame
4. Add remining iron sheet to frame.
5. Disassemble the table with wrench.

(repeat above with screwdriver for step 6 produces same result which is also different than it used to be)

**Expected** result is 1 iron sheet + 2 rods
**Actual** result is 1 iron sheet

**Comment by 00-Steven** [comment]
yeah lemme look into it

**Comment by delaron** [comment]
Same with screwdriver. Just drops the material for the top and no frame is left.
