### ISSUE TITLE
All RPED interactions broken.

### ISSUE THREAD

**Issue by OverwatchVoice** [tgstation/tgstation#82525]
Reporting client version: 515.1630

## Issue Summary

Replacing parts and checking parts of any device do not work. Parts can still be inserted into the RPED, but without any effect.

## Round ID:
[226779](https://scrubby.melonmesa.com/round/226779)

**Comment by 00-Steven** [comment]
how the fuck

**Comment by 00-Steven** [comment]
So this seems to be about a specific check that got changed.
https://github.com/tgstation/tgstation/blob/f0ed4ba4ce6b114509c10ee2f36ab0af6d7c81d2/code/game/machinery/_machinery.dm#L956-L957

https://github.com/tgstation/tgstation/blob/1583cf0cc968cd9f5da2398035feb8d70d58bcf2/code/game/machinery/_machinery.dm#L958-L959
