### ISSUE TITLE
Doing xenobio while dead/far away from it

### ISSUE THREAD

**Issue by RandomDudeFromTheRim** [tgstation/tgstation#82520]
Reporting client version: 515.1633

## Issue Summary
Being dragged away from xenobio console while you are laying down causes you to permanently use that console unless you log off/it gets destroyed(?).

## Round ID:
[226769](https://scrubby.melonmesa.com/round/226769)

## Testmerges:
- [Cleans up the SS13_base lua file and adds a new lua file for easily handling multiple signals on different objects.](https://www.github.com/tgstation/tgstation/pull/82458)

## Reproduction:
1. Use console
2. Lay down
3. Get dragged away
4. Camera is still locked in xenobio console mode
5. (optional) get stuffed into anything (locker/disposals/cryo/crate)
6. (optional) your camera gets forced back to you, yet you can't move and retain the xenobio buttons.
7. (optional) DIE
8. (optional) work in xenobio while dead lmao

**Comment by Profakos** [comment]
Astounding bug. I wonder if this affects every camera console, like the Aux Base Construction one.

**Comment by RandomDudeFromTheRim** [comment]
https://github.com/tgstation/tgstation/assets/71607168/b94351c8-2b6a-4913-a3cf-da2ad20c6874
IM NOT KIDDING

**Comment by Livrah** [comment]
Same for abductor's console. And xeno console worked for me even when depowered.
