### ISSUE TITLE
The text box and tab box is broken, just completely blank

### ISSUE THREAD

**Issue by RendezookJS** [tgstation/tgstation#82523]
i have literally no clue what caused it or why but im pretty sure im not the only one affected, unfortunately all i can really provide is this screenshot: 
![image](https://github.com/tgstation/tgstation/assets/144733510/ac707135-867b-46f8-91eb-1d49fee50e50)

also restarting doesn't fix it, I've tried restarting my PC still didn't work so idk what to do really

**Comment by newfren** [comment]
does typing fix-chat in the chat bar fix it

**Comment by RendezookJS** [comment]
nope
