### ISSUE TITLE
big hands makes you unable to use the departmental order console

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#82532]
Reporting client version: 515.1634

## Issue Summary
big hands makes you unable to use the departmental order console

## Round ID:
[226800](https://scrubby.melonmesa.com/round/226800)

## Testmerges:
- [Cleans up the SS13_base lua file and adds a new lua file for easily handling multiple signals on different objects.](https://www.github.com/tgstation/tgstation/pull/82458)
- [General maintenance for chem master](https://www.github.com/tgstation/tgstation/pull/82002)
- [Plane Master Refactor + Mutliz Rendering Optimizations (Bigly)](https://www.github.com/tgstation/tgstation/pull/82419)
- [Monkeys now use height offset (and monkey tail works)](https://www.github.com/tgstation/tgstation/pull/81598)

## Reproduction:
have big hands (via quirk in this instance, or via insulated gloves)
the order console was merged with the chat console
now it's a modular computer and you can't use it anymore

this didn't seem like an intentional balance lever when the two computers were condensed into one

**Comment by MrMelbert** [comment]
It was not intentional but I cannot imagine we would change it to be inconsistent with all other mod PC apps
