### ISSUE TITLE
you can delete papers

### ISSUE THREAD

**Issue by norsvenska** [tgstation/tgstation#82536]
Reporting client version: 515.1634

## Issue Summary
title. alt double clicking a paper will delete it

## Round ID:
[226820](https://scrubby.melonmesa.com/round/226820)

## Testmerges:
- [Cleans up the SS13_base lua file and adds a new lua file for easily handling multiple signals on different objects.](https://www.github.com/tgstation/tgstation/pull/82458)
- [General maintenance for chem master](https://www.github.com/tgstation/tgstation/pull/82002)
- [Plane Master Refactor + Mutliz Rendering Optimizations (Bigly)](https://www.github.com/tgstation/tgstation/pull/82419)
- [Monkeys now use height offset (and monkey tail works)](https://www.github.com/tgstation/tgstation/pull/81598)

## Reproduction:

grab paper
alt double click
paper gone

**Comment by SyncIt21** [comment]
Duplicate #78676

**Comment by norsvenska** [comment]
> Duplicate #78676

in my defense it's been a couple months
