### ISSUE TITLE
Reviving with a replaced heart causes heart attack

### ISSUE THREAD

**Issue by ZeroKelvn** [tgstation/tgstation#82551]
Reporting client version: 515.1632

## Issue Summary
After revival, if your heart's been replaced, you take crippling suffocation damage. This had happened to me before, and an AHeal hadn't been able to fix me, and so the admin had to regenerate my body completely. Now that I've been able to spectate it happening as a ghost, I can confirm the issue is caused by a heart attack. Probably another fuck-up of https://github.com/tgstation/tgstation/pull/82305.

## Round ID:
[226874](https://scrubby.melonmesa.com/round/226874)

## Testmerges:
- [Cleans up the SS13_base lua file and adds a new lua file for easily handling multiple signals on different objects.](https://www.github.com/tgstation/tgstation/pull/82458)
- [General maintenance for chem master](https://www.github.com/tgstation/tgstation/pull/82002)
- [Plane Master Refactor + Mutliz Rendering Optimizations (Bigly)](https://www.github.com/tgstation/tgstation/pull/82419)
- [Monkeys now use height offset (and monkey tail works)](https://www.github.com/tgstation/tgstation/pull/81598)

## Reproduction:
1. Replace a dead body's heart with a new one (example is upgraded cybernetic?)
2. Defibrillate the body
3. Despite having just shocked the heart to make it beat, watch them die because their heart isn't beating

**Comment by MrMelbert** [comment]
Followed reproduction steps exactly and nothing out of the ordinary happened. Are you sure you didn't insert a broken heart?

**Comment by MrMelbert** [comment]
Especially weird that aheal "didn't work" when aheal stops heart attacks.

**Comment by ZeroKelvn** [comment]
I don't know entirely what was happening, all I know is that they were having a Heart Attack immediately after being defibrillated, and that it's happened to me before in a prior round as well.

**Comment by necromanceranne** [comment]
I observed this in round [226912](https://tgstation13.download/parsed-logs/manuel/data/logs/2024/04/09/round-226912/), where suede falcon ended up dying early into the shift and had their heart replaced with a surplus heart. Despite defibrillation, he was stuck in a permanent heart attack state until I hit him with an aheal.

His current, actual heart was fine, and was seemingly not failing. I should have tried tracking down his original heart, because I have a weird feeling that maybe it is holding some reference to that original heart.

**Comment by Sadboysuss** [comment]
> I don't know entirely what was happening, all I know is that they were having a Heart Attack immediately after being defibrillated, and that it's happened to me before in a prior round as well. I wasn't the one performing the surgery in either case, but both times it's been done to a Miner with organs replaced. <img alt="image" width="302" src="https://private-user-images.githubusercontent.com/108566257/320636228-57e923f4-5596-4079-9cd9-b0ae33e2ef58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NjA2NDMsIm5iZiI6MTcxMjY2MDM0MywicGF0aCI6Ii8xMDg1NjYyNTcvMzIwNjM2MjI4LTU3ZTkyM2Y0LTU1OTYtNDA3OS05Y2Q5LWIwYWUzM2UyZWY1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQxMDU5MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZGNjZDE1NTUwNTYyMWEwYTI4NWRlNGYwZDc3ZWEwY2RjM2U1MDliOGI4MjRjYzYxOTk4MjYwMGVmYjcwNjQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MoYXChgwVDjv5b3JfCPTRpC3ntARlKZuZbkchFJh4y4">

if your heart breaks you can only replace it to stop the next heart attack, cybernetic hearts can break via emp.

**Comment by necromanceranne** [comment]
In my own observation, there was no instance where the heart would have broken. At least, the heart put in. The original heart was definitely dead.

**Comment by lessthnthree** [comment]
I saw last night a patient with Myocardial Infarction receive a heart replacement and the newly printed heart didn't function correctly, might have been an attack.

I'm going to try and replicate it on local.

**Comment by ATH1909** [comment]
> I saw last night a patient with Myocardial Infarction receive a heart replacement and the newly printed heart didn't function correctly, might have been an attack.
> 
> I'm going to try and replicate it on local.

check the state of the original heart as well, if you can

**Comment by lessthnthree** [comment]
> > I saw last night a patient with Myocardial Infarction receive a heart replacement and the newly printed heart didn't function correctly, might have been an attack.
> > I'm going to try and replicate it on local.
> 
> check the state of the original heart (that's no longer in their body) as well, if you can

Organs are not my strong suit, what information do you want from VV?

**Comment by Profakos** [comment]
Tried to reproduce this, and turns out, if cyber hearts are turned off (not damaged, just not beating), defibbing will not turn them back on, as they are immune to heart attacks, and if the patient is immune to heart attacks, set_heartattack returns early.

So I guess when this happened to me, I did not notice that the cyber heart was not animated? I will have to do more tests.

**Comment by Profakos** [comment]
Important addendum: If someone dies with a Surplus Cybernetic Heart, they are rather doomed. Their heart can only be restarted by being removed and started by hand, and those surplus cyber organs explode when removed.

**Comment by Profakos** [comment]
Probably #82738 has fixed this.
