### ISSUE TITLE
Incorrect rendering of obstructed tiles and bodies.

### ISSUE THREAD

**Issue by HappyD0gg** [tgstation/tgstation#82554]
## Issue Summary:
 Obstructed tiles occasionally render as space tiles instead of blacked out, as well as bodies occasionally rendering as fully blacked out.

## Round ID:
 [226883](https://scrubby.melonmesa.com/round/226883)

## Testmerges: 
[#82419: 'Plane Master Refactor + Mutliz Rendering Optimizations (Bigly)' by LemonInTheDark at commit 8295b172ea]([](https://www.github.com/tgstation/tgstation/pull/82419))

## Reproduction:
Out of view tiles naturally happen without any effort, just walk around ant it will happen. The incorrect rendering of bodies can be reproduced by Changing haircut or beard.

![imaage](https://github.com/tgstation/tgstation/assets/105516305/b019e9b8-426b-4509-9f05-9d5b2f44d5a5)

![image](https://github.com/tgstation/tgstation/assets/105516305/1708f4ae-edc1-4290-9128-bfb43cf43a4f)

**Comment by SyncIt21** [comment]
@MrMelbert this can be closed as the test merge PR was closed ages ago
