### ISSUE TITLE
Cult Victory doesn't allow ghosts to become harvesters

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#82568]
Reporting client version: 515.1635

## Round ID:
[226943](https://scrubby.melonmesa.com/round/226943)

## Testmerges:
- [Cleans up the SS13_base lua file and adds a new lua file for easily handling multiple signals on different objects.](https://www.github.com/tgstation/tgstation/pull/82458)
- [General maintenance for chem master](https://www.github.com/tgstation/tgstation/pull/82002)
- [Plane Master Refactor + Mutliz Rendering Optimizations (Bigly)](https://www.github.com/tgstation/tgstation/pull/82419)
- [Monkeys now use height offset (and monkey tail works)](https://www.github.com/tgstation/tgstation/pull/81598)

## Reproduction:
- Watch Cult win as a ghost
- Click on Nar'sie to join the harvest
- Cry as nothing happens
- Then find out every time you click a harvester spawns under nar'sie with no mind

**Comment by DaydreamIQ** [comment]
![image](https://github.com/tgstation/tgstation/assets/62606051/a4d8692a-b3cd-4987-9aac-63ed32f2ecf7)

**Comment by Rhials** [comment]
I would like to add that, in the same round, clicking on the ghost orbit notification (toast popup) let me spawn in as a harvester as normal. I didn't try spawning in afterwards but the ghost notif instantly made me a construct without any issue.
