### ISSUE TITLE
Solar panels missing textures

### ISSUE THREAD

**Issue by gueba14** [tgstation/tgstation#82564]
## Issue Summary
Well Solar panels are missing textures on places like here in Tramstation map
![image](https://github.com/tgstation/tgstation/assets/97851168/ae3e1007-93fc-4c29-a180-77fb4f92181b)

## Round ID:
[226937](https://scrubby.melonmesa.com/round/226937)

## Testmerges:
Unknown

**Comment by Rhials** [comment]
Probably has some relation to #82301

**Comment by MrMelbert** [comment]
Dupe of #82301
