### ISSUE TITLE
Sugar + Ants = Less Ants

### ISSUE THREAD

**Issue by dopamiin0** [tgstation/tgstation#82575]
## Issue Summary

have ants
need more ants
mix it with sugar
end up with less ants
wtf

## Round ID:[226970](https://scrubby.melonmesa.com/round/226970)

[Round ID]: [226970](https://scrubby.melonmesa.com/round/226970)

## Reproduction:
i mix ants with sugar
the sugar is used up in the reaction and then ants just fucking disappear
why god

**Comment by the-orange-cow** [comment]
They're putting chemicals in the sugar to make the friggen ants stop reproducing!

**Comment by moocowswag** [comment]
Likely a weird issue with purity i think.

**Comment by Metekillot** [comment]
you ended up helping the less fertile ants outcompete the more fecund ants. don't you understand darwininan evolution?
