### ISSUE TITLE
[Icebox] Ordnance incinerator ignition switch non-functional.

### ISSUE THREAD

**Issue by OverwatchVoice** [tgstation/tgstation#82584]
Reporting client version: 515.1630

## Issue Summary

Pressing the button to start ignition doesn't work. not sure if this is because the button itself is broken, or if the igniter is. Either way, this makes ordnance inoperable.

## Round ID:
[226997](https://scrubby.melonmesa.com/round/226997)

## Testmerges:
- [Cleans up the SS13_base lua file and adds a new lua file for easily handling multiple signals on different objects.](https://www.github.com/tgstation/tgstation/pull/82458)
- [General maintenance for chem master](https://www.github.com/tgstation/tgstation/pull/82002)
- [Plane Master Refactor + Mutliz Rendering Optimizations (Bigly)](https://www.github.com/tgstation/tgstation/pull/82419)

**Comment by SyncIt21** [comment]
Duplicate #82294
