### ISSUE TITLE
pickpocketing and tying someone else's shoelaces shows a cog above your head

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#82583]
Reporting client version: 515.1630

## Issue Summary
pickpocketing always does
tying shoelaces seems to be showing the cog, but only some times ???
both should be stealthy actions

## Round ID:
[226993](https://scrubby.melonmesa.com/round/226993)

## Testmerges:
- [Cleans up the SS13_base lua file and adds a new lua file for easily handling multiple signals on different objects.](https://www.github.com/tgstation/tgstation/pull/82458)
- [Admin Verb Datums MkIII | Now with functional command bar](https://www.github.com/tgstation/tgstation/pull/82511)

**Comment by newfren** [comment]
also a shame that trying to break out of handcuffs does as well
