### ISSUE TITLE
Lighting doesn't update after smoke grenade clears

### ISSUE THREAD

**Issue by lessthnthree** [tgstation/tgstation#82600]
## Issue Summary

515.1635

After a smoke grenade blocks lighting in an area, when the smoke clears the lights are functional but don't re-light the area until toggled off/on to manually trigger an update.

https://github.com/tgstation/tgstation/assets/83487515/7d7cdf17-ce88-48c3-835e-5373b9bb2eb6

## Reproduction:

Throw smoke grenade, lights won't light area until toggled.

**Comment by tralezab** [comment]
"Opaque smoke despawning does not fix light properly. This must be an issue with directional opacity." - Kapu
The first part comes to me as another way to say it isn't updating, but the second part is a lead on this bug
