### ISSUE TITLE
Oven Produces Infinite Inedible Food

### ISSUE THREAD

**Issue by slayer129123** [tgstation/tgstation#82610]
## Issue Summary
The Oven Is Able to Turn a single item of uncooked food into an infinite amount of food that is considered inedible, The original is Never Cooked but instead produces copies of cooked versions that cant be eaten.
These Copies are still Valid for Recipes such as turning Plain Cake into Pound Cake will make it now edible.
Additionally the oven tray if removed cannot be inserted back into the oven instead only the serving tray can be used, causing the bug.

## Round ID:
[2277087](https://scrubby.melonmesa.com/round/2277087) and 2277088

## Reproduction:
Was able to perform this bug as soon as i entered a game, I Replaced the Oven Plate inside an oven and replaced it with a Serving Tray, Every Item that could be cooked inside an oven i was able to Duplicate its cooked form after cooking for a short time, This Includes, Dough, Pie Dough,Cake Batter, and Cheese Wheels, Was also able to perform this bug with the Starting Range as well as building my Oven.

**Comment by SyncIt21** [comment]
Yup

![Screenshot (408)](https://github.com/tgstation/tgstation/assets/110812394/7225cfeb-6500-4113-9d2d-fc91573f9ce5)

Solution is to not allow putting serving trays inside ovens cause that's stupid. Should add a check to stop people from doing that
