### ISSUE TITLE
Arcade battle bugs

### ISSUE THREAD

**Issue by adamkad1** [tgstation/tgstation#82613]
## Issue Summary
New Arcade battle has two bugs that I've noticed. One: Counterattack doesnt kill enemies, it will leave them in negatives. Two: After unlocking moon, the shop has a 'Gear' weapon in it. Buying that and getting in a fight has you do 0 damage with your attack and softlocks the game, requiring you to reset it to keep playing.

## Round ID:
[227089](https://scrubby.melonmesa.com/round/227089)

## Testmerges:
[#82511: 'Admin Verb Datums MkIII | Now with functional command bar' by ZephyrTFA at commit 94fc2fb7bb](https://www.github.com/tgstation/tgstation/pull/82511)

## Reproduction:
For 1, get the last weapon and counterattack an enemy from first stage or so.
For 2, unlock 'The moon' and check the shop, buy the gear and get in a fight.

**Comment by JohnFulpWillard** [comment]
I didn't see you edited your comment on my PR, thank you for making an issue report
