### ISSUE TITLE
Recharging Stations Don't Always Recharge

### ISSUE THREAD

**Issue by RonaldThomas** [tgstation/tgstation#82626]
Reporting client version: 515.1630

## Issue Summary

Occasionally, when attempting to recharge in a recharging station as a cyborg, I've found that the recharger simply doesn't charge.

## Round ID:
[227101](https://scrubby.melonmesa.com/round/227101)

## Testmerges:
- [RPG Loot: Revisited & READY](https://www.github.com/tgstation/tgstation/pull/82533)
- [Fixes AI lag by re-adding idle mode to all AI that was lost with the simple mob to basic mob conversion.](https://www.github.com/tgstation/tgstation/pull/82539)
- [Admin Verb Datums MkIII | Now with functional command bar](https://www.github.com/tgstation/tgstation/pull/82511)

## Reproduction:

I have not been able to find any method of reliably reproducing the issue. I have confirmed that power is present in the room, I have attempted upgrading the recharger, and moving to other chargers. On one occasion, I heard another player suggest that the problem could be related to excessive time dilation, but the issue occurred in this round when the average time dilation was 0%.

**Comment by norsvenska** [comment]
I had the same issue on [#227604](https://statbus.space/rounds/227604), only some charging stations were able to recharge us borgs. The rooms were charged, the stations were upgraded, and some of them worked fine. For example, two of the three chargers in the mech bay worked, but the last one did not.

**Comment by Pickle-Coding** [comment]
Think someone changed it so they only consider excess power from the grid. The recharge station might not be able to charge if there's no excess power.
