### ISSUE TITLE
Wrongly looking pipes sprites after unscrewing catwalk

### ISSUE THREAD

**Issue by KickPaw** [tgstation/tgstation#82622]
Reporting client version: 515.1633

Wrongly looking pipes sprites after unscrewing catwalk. After toggling its appearance, the pipes will peek out of the floor

## Round ID:
[227095](https://scrubby.melonmesa.com/round/227095)

## Testmerges:
- [Admin Verb Datums MkIII | Now with functional command bar](https://www.github.com/tgstation/tgstation/pull/82511)

## Reproduction:

Find catwalk floor with pipes underneath it. Toggle rods visibility on and off. There's horrible pipes peeking out of my floor!!
![image](https://github.com/tgstation/tgstation/assets/105122420/589a0e61-2271-4858-9bf7-af486175d448)

**Comment by DingleFlop** [comment]
Likely related to #82335, seems pipes just really like to be on top of things they're not supposed to be on top of.

**Comment by FlufflesTheDog** [comment]
Started with #81800 iirc
