### ISSUE TITLE
Mushroom bowl turns invisible when filled with liquid.

### ISSUE THREAD

**Issue by OverwatchVoice** [tgstation/tgstation#82624]
Reporting client version: 515.1630

## Issue Summary

When reagents are inserted into a bowl, the bowl dissapears, leaving behind only the "reagent in container" layer.
![obrazek](https://github.com/tgstation/tgstation/assets/39193093/0174140f-598a-4697-a9f3-1ec6c4ca90ec)

## Round ID:
[227094](https://scrubby.melonmesa.com/round/227094)

## Testmerges:
- [RPG Loot: Revisited & READY](https://www.github.com/tgstation/tgstation/pull/82533)
- [Fixes AI lag by re-adding idle mode to all AI that was lost with the simple mob to basic mob conversion.](https://www.github.com/tgstation/tgstation/pull/82539)
- [Plane Master Refactor + Mutliz Rendering Optimizations (Bigly)](https://www.github.com/tgstation/tgstation/pull/82419)

**Comment by OverwatchVoice** [comment]
Similiar to [80182](https://github.com/tgstation/tgstation/issues/80182)

**Comment by SyncIt21** [comment]
> Similiar to [80182](https://github.com/tgstation/tgstation/issues/80182)

Not similar, it's an exact duplicate. Close this in favor of that
