### ISSUE TITLE
Resisting no longer unbuckles you from things

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#82634]
Reporting client version: 515.1635

## Round ID:
[227112](https://scrubby.melonmesa.com/round/227112)

## Testmerges:
- [Admin Verb Datums MkIII | Now with functional command bar](https://www.github.com/tgstation/tgstation/pull/82511)

## Reproduction:

Nor does pressing 'b' or clicking on the button.

You basically have to click the chair as if you were unbuckling someone else.  Which is fine, but this has made quite a few ahelps now :P

**Comment by 00-Steven** [comment]
Should already have a fix up, hold on.

**Comment by 00-Steven** [comment]
er, editing the pr to say it fixes this hasn't done much, but #82627.
