### ISSUE TITLE
Deepfried medipens chems can be syringed and any chems can be put in and used like a medipen

### ISSUE THREAD

**Issue by jughu** [tgstation/tgstation#82631]
## Issue Summary
Medipens can be deepfried and chems can be freely exchanged with syringes

## Round ID:
Not relevant

## Testmerges:
Not relevant

## Reproduction:
Deepfry a medipen
Syringe chems out
Syringe other chems in
Inject your victim

Prob a similiar issue to https://github.com/tgstation/tgstation/issues/79178

**Comment by Metekillot** [comment]
For future reference, Round ID is very helpful for debugging, because almost everything (including injection of chems into food, I believe) is logged and it's easier to track down code if you have the investigation log

**Comment by JohnFulpWillard** [comment]
I can't replicate this unfortunately
![image](https://github.com/tgstation/tgstation/assets/53777086/cbb556d9-ceed-42b2-b8f5-1d6ad0e93044)
