### ISSUE TITLE
random camera static visible while not looking through a camera

### ISSUE THREAD

**Issue by kawoppi** [tgstation/tgstation#82657]
## Issue Summary
![image](https://github.com/tgstation/tgstation/assets/94711066/73a0046c-419e-4a78-bea4-9c8e14bff54d)
![image](https://github.com/tgstation/tgstation/assets/94711066/eccbf58b-7089-47c3-a5b8-6278174a19c7)
I asked the lizard and they didn't see anything out of the ordinary.

## Round ID:
[227173](https://scrubby.melonmesa.com/round/227173)

## Testmerges:
The following pull requests are currently test merged:
[#82511: 'Admin Verb Datums MkIII | Now with functional command bar' by ZephyrTFA at commit 94fc2fb7bb](https://www.github.com/tgstation/tgstation/pull/82511)

## Reproduction:
I have no idea. It was there when I got there. Later in the round it was gone though.
![image](https://github.com/tgstation/tgstation/assets/94711066/dfdde4e5-cfcc-46c6-b4fa-12adce456fce)

**Comment by Sealed101** [comment]
may have been cleaned up by https://github.com/tgstation/tgstation/pull/82699 ? just a random static tile is weird as fuck
