### ISSUE TITLE
the Booze-O-Mat and ShadyCigs Deluxe vending machines sell to underage characters

### ISSUE THREAD

**Issue by kawoppi** [tgstation/tgstation#82653]
## Issue Summary
![image](https://github.com/tgstation/tgstation/assets/94711066/95db1e02-c6e8-44f5-8a3d-1d56b8347606)
Normally they deny the purchase and alert security when you're under the drinking age. The cigar vendor doesn't block you from buying either.

## Round ID:
[227168](https://scrubby.melonmesa.com/round/227168)
227171

## Testmerges:
The following pull requests are currently test merged:
[#82511: 'Admin Verb Datums MkIII | Now with functional command bar' by ZephyrTFA at commit 94fc2fb7bb](https://www.github.com/tgstation/tgstation/pull/82511)

## Reproduction:

1. Have your character be 19 or any other age under 21 I think? As long as your ID says "(MINOR)" when you use it inhand.
2. Buy from a Booze-O-Mat or ShadyCigs Deluxe (make sure you're not buying something that's unrestricted)

**Comment by nikothedude** [comment]
game breaking we need to fix this before the feds find us

**Comment by Dawnseer** [comment]
I was wondering why my miner could buy em
