### ISSUE TITLE
Unable to ventcrawl with alt+click 

### ISSUE THREAD

**Issue by Zargoar** [tgstation/tgstation#82668]
Reporting client version: 515.1635

## Issue Summary

Unable to crawl through vents with alt+click

## Round ID:
[227228](https://scrubby.melonmesa.com/round/227228)

## Testmerges:
- [Alt click refactor](https://www.github.com/tgstation/tgstation/pull/82656)

## Reproduction:

1. Be a rat King or a xeno near a vent.
2. Alt+click the vent to attempt to ventcrawl.
3. Observe you are unable to crawl into the vent.

**Comment by NoxVS** [comment]
Probably conflicts with the alt-click on a tile to see it's contents change

**Comment by MrMelbert** [comment]
![image](https://github.com/tgstation/tgstation/assets/51863163/7e3be4df-2387-4653-83f9-6087fa3c01d7)

**Comment by jlsnow301** [comment]
Fixed in 85a3356
