### ISSUE TITLE
Latex straight jackets permanently block hand usage after being resisted out of

### ISSUE THREAD

**Issue by nikothedude** [tgstation/tgstation#82663]
Reporting client version: 515.1635

## Issue Summary

Title.

## Reproduction:

Just resist out of one and see how your hands are blocked.

Only tested with resisting out of.

**Comment by nikothedude** [comment]
it doesnt do this if you delete it

**Comment by nikothedude** [comment]
FUCK YOU REPORT ISSUE BUTTUN FUCK YOU SO MUCH FUCK YOU FUCK YOU FUCK YOU FUCK YOU FUCK YOU FUCK YOU FUCK YOU FUCK YOU

**Comment by Iamgoofball** [comment]
![venom-venom-antag](https://github.com/tgstation/tgstation/assets/4081722/9439ea52-8584-4b42-b75c-411ede8e40f4)
