### ISSUE TITLE
Cyborg pseudocircuit adaptor seems to take much longer than it used to in order to recharge

### ISSUE THREAD

**Issue by moocowswag** [tgstation/tgstation#82688]
## Issue Summary
The cyborg pseudocircuit adaptor seems to have a much longer recharge time than it used to

https://github.com/tgstation/tgstation/blob/abbee36f1d02741426e4ef9f10e3f82ab8379c05/code/game/objects/items/devices/electroadaptive_pseudocircuit.dm#L2

This code that controls the recharge time seems to suggest that it scales with power cost to use it, likely effected by power changes

var/recharge_time = min(600, circuit_cost * 5)  //40W of cost for one fabrication = 20 seconds of recharge time; this is to prevent spamming
	addtimer(CALLBACK(src, PROC_REF(recharge)), recharge_time)
	return TRUE //The actual circuit magic itself is done on a per-object basis
	

likely caused by https://github.com/tgstation/tgstation/pull/81579

## Reproduction:
Be engineer cyborg

Use pseudocircuit adaptor to do literally anything like build a firelock or apc or fire alarm or air alarm.

Be forced to wait literal minutes for it to recharge when before the cooldown seemed rather low especially since you wernt  fabricating circuits out of nowhere you had to reload it with similar circuits.

**Comment by Vect0r2** [comment]
It seems to reset everytime that I attempt to use it. I haven't looked at the code to confirm it, but that's how it feels
