### ISSUE TITLE
OpenDream Linter Consistently Warns On Missing Pragmas

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#82696]
## Issue Summary

This is showing up on every PR/CI Run.

![image](https://github.com/tgstation/tgstation/assets/34697715/ebac1183-a7bb-442b-a971-6b1e80751d97)

I spoke about it in #maintainerbus and there are at least three options (please do add more alternate options if you have any good ideas).

1. Add a pragma or CLI-flag that makes it not warn on missing pragmas because it has the potential to lint on pragmas that exist outside of its namespace. This is the better option, but this would be up to the maintainers on OpenDream. MSO suggested having all OpenDream specific pragmas be prepended with `OD` (making it `OD-SoftReservedKeyword` as an example), but again, this is up to their maintainers.
2. Update our `od_annotator.py` to ignore `OD1002` codes (which are specifically designed to lint against unrecognized pragmas). This is only an option if number 1 doesn't work for any reason as it could cause issues down the line, but I'm mentioning it now because it is certainly an option.
3. Remove the TooManyArguments pragma. probably don't need it?

I'm a bit busy right now but I wanted to make sure I got it written down somewhere more public and eternal before I nag opendream maintainers about it (someone else can take up this mantle if they are so inclined). let's just get an issue regarding this on our tracker and we can just talk about it in this spot. i am operating on snail time sadly

**Comment by san7890** [comment]
btw the reason why BYOND doesn't error on unknown pragmas in this `od_lints.dm` file is because it's only ticked when we compile with opendream if you were wondering

**Comment by ike709** [comment]
> Add a pragma or CLI-flag that makes it not warn on missing pragmas

This has been around for quite a while already as `InvalidWarningCode` ([documentation](https://github.com/OpenDreamProject/OpenDream/wiki/Pragmas---Error-Emissions#1002---invalidwarningcode))
