### ISSUE TITLE
can't change chat font style to custom one

### ISSUE THREAD

**Issue by vertolodka** [tgstation/tgstation#82700]
Reporting client version: 515.1636

## Issue Summary
trying to change font style in chat to custom one causes ntos error

## Round ID:
[227307](https://scrubby.melonmesa.com/round/227307)

## Reproduction:
1. open chat settings
2. press "custom font"
3. typing anything into the input field (or just click on it once and then again anywhere else) causes ntos error
![изображение](https://github.com/tgstation/tgstation/assets/42512271/abbaa10e-745b-4bbd-b8c6-13a0427b33c9)

**Comment by ShadowLarkens** [comment]
The reason custom fonts cause an error and don't work is because this needs to be (e, value) instead of (value)
https://github.com/tgstation/tgstation/blob/master/tgui/packages/tgui-panel/settings/SettingsPanel.jsx#L143-L149
```diff
-onChange={(value) =>
+onChange={(e, value) =>
  dispatch(
    updateSettings({
      fontFamily: value,
    }),
  )
}
```

**Comment by Cyberboss** [comment]
#84601
