### ISSUE TITLE
Can't finish construction

### ISSUE THREAD

**Issue by jlsnow301** [tgstation/tgstation#82716]
## Issue Summary
Using a screwdriver on a machine frame with all parts installed yields "can't add that!"

## Round ID:
[227353](https://scrubby.melonmesa.com/round/227353)

## Testmerges:
[#82691: 'ai controllers use cell trackers to know when to idle' by Ben10Omintrix at commit 02cd647d95](https://www.github.com/tgstation/tgstation/pull/82691)
[#82697: 'Makes dropdowns better' by jlsnow301 at commit ec8d06dba4](https://www.github.com/tgstation/tgstation/pull/82697)
[#82625: 'Makes it EVEN EASIER to work with atom item interactions ft. "Leaf and Branch" & "Death to Chains"' by MrMelbert at commit 609163723d](https://www.github.com/tgstation/tgstation/pull/82625)

## Reproduction:
Complete a machine frame
Add components, circuit
Attempt to complete with screwdriver

**Comment by jlsnow301** [comment]
@MrMelbert possibly related

**Comment by MrMelbert** [comment]
Yes

**Comment by MrMelbert** [comment]
https://github.com/tgstation/tgstation/pull/82625/commits/81828199a87d31d636aebb618ba95527d606e76c
