### ISSUE TITLE
Hands remain blocked for 12 seconds after removing fake cuffs

### ISSUE THREAD

**Issue by iliyaxox** [tgstation/tgstation#82711]
## Issue Summary

Your hands will continue to be unusable (as if you were still restrained) if you resist out of fake cuffs for [around] 12 seconds (counting from the moment you start resisting out of them).

## Round ID:

Local host

## Testmerges:

N/A

## Reproduction:

1. Cuff yourself/get cuffed with fake cuffs;
2. Resist out of it (by either pressing 'Resist' or the resist hotkey);
3. Perform any action with your hands

**Comment by MrMelbert** [comment]
Not a bug - resisting while in handcuffs applies a 10 second click CD

With normal cuffs it is difficult to notice but it becomes painfully obvious when using fakes

**Comment by itseasytosee** [comment]
Another victim of click cool down.
