### ISSUE TITLE
Player panel is still missing from admin verbs

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#82728]
Reporting client version: 515.1635

## Round ID:
[227372](https://scrubby.melonmesa.com/round/227372)

## Testmerges:
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/66640614/91766e61-331a-4e6b-a124-fb67258044b0)

Also Inisimin

**Comment by SyncIt21** [comment]
![Screenshot (410)](https://github.com/tgstation/tgstation/assets/110812394/d36e9ce0-811c-4259-95b3-19ec2a806123)

**Comment by SyncIt21** [comment]
Will be fixed by #82757
