### ISSUE TITLE
KS13 drones are broken

### ISSUE THREAD

**Issue by Zenog400** [tgstation/tgstation#82737]
## Issue Summary

KS13 drones are unable to construct machines

## Round ID:

[227381](https://scrubby.melonmesa.com/round/227381)

## Testmerges:

82691
82625
82697

## Reproduction:

1) Spawn as derelict drone
2) Go to circuit storage
3) Get autolathe/circuit imprinter/protolathe boards
4) Build machines
5) Add components
6) Use screwdriver
7) "Can't add this!"

**Comment by MrMelbert** [comment]
82716
