### ISSUE TITLE
Screwdrivers cannot finish machines

### ISSUE THREAD

**Issue by ZeroKelvn** [tgstation/tgstation#82731]
Reporting client version: 515.1632

## Issue Summary
For some reason, building a new machine and trying to complete it with a screwdriver was trying to add the screwdriver to the machine, which meant it couldn't be screwed shut. This happened to a set of tesla coils, and while I was a Cyborg trying to finish them, an admin spawned in to try and screw them shut and was also unable to do so.

## Round ID:
227374

## Testmerges:
- [ai controllers use cell trackers to know when to idle](https://www.github.com/tgstation/tgstation/pull/82691)
- [Makes dropdowns better](https://www.github.com/tgstation/tgstation/pull/82697)
- [Makes it EVEN EASIER to work with atom item interactions ft. "Leaf and Branch" & "Death to Chains"](https://www.github.com/tgstation/tgstation/pull/82625)

## Reproduction:
1. Build a machine frame and get it ready (in this case, tesla coil)
2. Try to screw the machine shut to complete it
3. Cry as you 'can't add this!'

**Comment by MrMelbert** [comment]
#82716
