### ISSUE TITLE
Research Console is NTOS

### ISSUE THREAD

**Issue by Rex9001** [tgstation/tgstation#82749]
Reporting client version: 515.1636

## Issue Summary
The research console just shows an NTOS error

## Round ID:
[227423](https://scrubby.melonmesa.com/round/227423)

## Testmerges:
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)
- [Adds Medieval Pirates (and small assault_pod change)](https://www.github.com/tgstation/tgstation/pull/82392)
- [[READY] the unfuckening of clothing rendering](https://www.github.com/tgstation/tgstation/pull/79784)

## Reproduction:
Open the research console
NTOS error

**Comment by SyncIt21** [comment]
Fixed in #82750
