### ISSUE TITLE
Slime Damage over time status effect has no wear off timer leaving some nonhuman antags with constant DOT

### ISSUE THREAD

**Issue by ZAMODA** [tgstation/tgstation#82746]
Reporting client version: 514.1589

## Issue Summary

Be a non-human antag (xenomorph, sentient creature or space dragon)
Get attacked by a slime, latched onto, and get the slime damage over time effect.
Be completely unable to remove it, stuck with constant damage over time that adds onto burn damage and other DOT effects.
In the case of xenomorphs it would require said xenomorph to be over weeds constantly, the rest are just screwed.

## Round ID:
[227409](https://scrubby.melonmesa.com/round/227409)

## Testmerges:
- [ai controllers use cell trackers to know when to idle](https://www.github.com/tgstation/tgstation/pull/82691)
- [Makes dropdowns better](https://www.github.com/tgstation/tgstation/pull/82697)
- [Makes it EVEN EASIER to work with atom item interactions ft. "Leaf and Branch" & "Death to Chains"](https://www.github.com/tgstation/tgstation/pull/82625)

**Comment by Profakos** [comment]
Double checked,  it can only be removed by having it wash off, and non human mobs won't be able to turn on showers or use fire extinguishers to do so. Best they can do is to punch a water tank until it ruptures.
