### ISSUE TITLE
Context menu pops up when piloting a mech

### ISSUE THREAD

**Issue by githubuser4141** [tgstation/tgstation#82753]
## Issue Summary

The alt click context menu pops up when controlling a mech, thus 'photobombing' by stealing the client window's highlight. This un-focuses your client (gaming) window, meaning you stop moving/interacting unlick you click it again.

## Reproduction:

1. Be in a mech, use strafe (Alt + WASD to change  direction, and click because you're attacking/tooling when changing direction.)
2. Spawn some fast-moving enemies that like to dodge
3. Try to hit the enemies when you have held ALT down and end up clicking - the context menu will continously un-focus the game window.

**Comment by MrStonedOne** [comment]
why is alt enabling the context menu?

**Comment by jlsnow301** [comment]
> why is alt enabling the context menu?

they mean the item object window

**Comment by githubuser4141** [comment]
> REALLY do not want to add an is_user_in_mech_and_strafing check to every single alt-click interaction so im very tempted to just change the strafe toggle to another key

could people see the context menu in mechs before the changes? I actually can't recall somehow.

**Comment by jlsnow301** [comment]
> could people see the context menu in mechs before the changes? I actually can't recall somehow.

It's extremely likely. Basically, alt click chain has been broken for some time but the object item window was so far out of player vision that no one complained
