### ISSUE TITLE
Alt-clicking things in your inventory or storage does not work.

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#82768]
## Issue Summary

Alt-clicking objects in your inventory or storage does not work. Period.

## Testmerges:

[#82298: 'Wawastation' by mc-oofert at commit e229259992](https://www.github.com/tgstation/tgstation/pull/82298)
[#82765: 'Fixes sight range on lootpanel [no gbp]' by jlsnow301 at commit f225ebf277](https://www.github.com/tgstation/tgstation/pull/82765)

## Reproduction:

Equip something with an alt-click functionality into an equippable slot.

Observe that nothing happens when you attempt to use that functionality.

**Comment by jlsnow301** [comment]
Fixed in c681908

> lootpanel is so bad (❁ᴗ͈ˬᴗ͈) ༉‧ ♡*.✧

thank you for your input
