### ISSUE TITLE
Toggle-nuke admin verb scope is wrong, brings up a list of every obj in the game

### ISSUE THREAD

**Issue by Isratosh** [tgstation/tgstation#82766]
Reporting client version: 515.1635

## Issue Summary
Using the toggle-nuke verb used to show (before the recent admin verbs shakeup) a list of possible nuclear devices to arm, generally just the station self destruct and the beer nuke. Now it lags the client for 10 seconds and generates a list of what seems like every object on the map. It's also not available on a right click (it wasn't before either and that's fine). It is still useable by following the verb with the name of the nuclear device in the command bar, like: toggle-nuke "nanotrasen-brand" and pressing space bar for autocomplete. I have not been brave enough to test what happens if I run this on an invalid object.

![image](https://github.com/tgstation/tgstation/assets/13789168/ec96bc99-3465-4452-b1b5-18b0d22c38ba)

## Round ID:
[227458](https://scrubby.melonmesa.com/round/227458)

## Testmerges:
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)

## Reproduction:
1. press Toggle Nuke

**Comment by Sealed101** [comment]
multiple dupes of this issue huh
closed by #85744
