### ISSUE TITLE
Engineering cyborg's circuit manipulation apparatus non-functional, and obselete

### ISSUE THREAD

**Issue by OverwatchVoice** [tgstation/tgstation#82774]
Reporting client version: 515.1630

## Issue Summary
When attempting to assemble a space heater by using a circuit manipulator on a wired machine frame, a balloon popup appears, saying the item cannot be added when it should.

I'd also like to take the opportunity to note that the circuit manipulation apparatus is an obselete item in an already cluttered cyborg interface, since RPEDs can do the job way, way better, and don'are researched in the same tree as manipulator is.

## Round ID:
[227472](https://scrubby.melonmesa.com/round/227472)

## Testmerges:
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)

## Reproduction:

Build a machine frame (5x iron from crafting menu)
Add wires to the frame (5x cable coil on machine frame)
Attempt to add a space heater circuit board via circuit manipulation apparatus.

**Comment by moocowswag** [comment]
They would have a niche if they could hold integrated circuit boards c:

**Comment by MrMelbert** [comment]
This just happens because it's trying to "add" the manipulator itself to the machine 

It can be fixed if the manipulator is changed to use new attack chain

**Comment by Vect0r2** [comment]
I have suggested it would be baller if Borgs could use circuits

**Comment by Sadboysuss** [comment]
closing in favor of https://github.com/tgstation/tgstation/issues/84205
