### ISSUE TITLE
Changelings Cannot Sting with Alt-Click any more

### ISSUE THREAD

**Issue by Weisyl** [tgstation/tgstation#82777]
Reporting client version: 515.1636

## Issue Summary

With the new alt-click menu / system, changelings cannot alt-click targets to sting them. This is especially problematic for players without a functioning middle-click.

## Round ID:
[227496](https://scrubby.melonmesa.com/round/227496)

## Testmerges:
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)
- [Cargo ui refactor -> TS](https://www.github.com/tgstation/tgstation/pull/82745)

**Comment by jlsnow301** [comment]
Fixed in #82758 just isnt on live yet
