### ISSUE TITLE
BCI chambers can't get unanchored

### ISSUE THREAD

**Issue by PeterMX16** [tgstation/tgstation#82786]
Brain-computer interface manipulation chambers are permanently anchored once constructed. The only way to remove them is to deconstruct, unanchor the frame and construct it somewhere else, inconvenient when you don't have a RPED on you at all times.

**Comment by MrMelbert** [comment]
Not all machines can be unanchored, this is just a facet of machines

**Comment by Metekillot** [comment]
For what it's worth Peter, you can un-anchor a machine frame that has every part in it. You just won't be able to finish it if it requires being anchored to be finished.
