### ISSUE TITLE
nerf the mime mech

### ISSUE THREAD

**Issue by Slykirby116** [tgstation/tgstation#82793]
The mime mech needs serious nerfing as it's able to be invisible indefinitely and can move incredible fast making fighting it incredibly hard. A time limit for the mech's cloak would be nice to see and it's speed taken down a notch, as fighting it in is current state is nearly impossible without a group of people all attacking it at once and preventing it from moving. Not to mention this mech can clear low pop servers like bagil with ease and there would be no stopping it.

**Comment by Blacklist897** [comment]
skill issue
use a ion gun or lasers, it's made of tissue paper

**Comment by SyncIt21** [comment]
This isn't a bug but a balance request. Close the issue and make a PR on your own to change it.

**Comment by MrMelbert** [comment]
Feature requests are not handled in the repository. The best place to discuss these ideas would be on the /tg/station 13 forums here: https://tgstation13.org/phpBB/viewforum.php?f=9&sid=5153c1c704a4fb1006bf7a265e45e03f
