### ISSUE TITLE
Deathmatch cyborgs talking in binary

### ISSUE THREAD

**Issue by Hexflash24** [tgstation/tgstation#82802]
## Issue Summary

Cyborgs made through the Wand of polymorph loot in Ragin' Mages deathmatch are able to communicate in the binary channel for the main station.

## Round ID:

227597

## Reproduction:

 Join the new deathmatch mode called ragin mages, someone must get the wand of polymorph through the mysterious boxes, the wand of polymorph must then polymorph someone into a cyborg, that cyborg will then be able to use the binary channel like any other borg would, leading to it being able to communicate with the ai and cyborgs on the station.

**Comment by MrMelbert** [comment]
Polymorph wand should be deleted from deathmatch

**Comment by Admiral-Gigaton** [comment]
> Polymorph wand should be deleted from deathmatch

in its current state, in deathmatch, if you polymorph (especially on a 1v1) it instantly counts them as dead or having lost, so yes, this is the solution. (keep in mind wand belt exists and holds the polymorph wand and can be obtained from crates)
