### ISSUE TITLE
Borg omnitool gets stuck on drapes functionality

### ISSUE THREAD

**Issue by Dawnseer** [tgstation/tgstation#82805]
Reporting client version: 515.1636

## Issue Summary

Exactly what it says in the title
Both my scalpels and both my cauteries in the omnitools got stuck with drape functionality.
Also the drapes show as this. Not sure it wants the _ in there.
![image](https://github.com/tgstation/tgstation/assets/126404225/4c46012c-0011-444d-bef5-fdfc986cd3b0)

## Round ID:
[227600](https://scrubby.melonmesa.com/round/227600)

## Testmerges:
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)
- [Refactors how basic ais do their success/failures](https://www.github.com/tgstation/tgstation/pull/82643)

## Reproduction:
Unsure of the specifics, it was working undtil it weren't. I did have the omnitool upgrade though.

**Comment by MrMelbert** [comment]
The surgery tool uses `RemoveComponentSource(/datum/component/surgery_initiator)` to de-drape-ify it but this is not the proper use of the proc, 
1. Surgery initiator is not a sourced component
2. Its first arg is the source, not the component type
So This is likely runtiming and breaking it

**Comment by MrMelbert** [comment]
Also `tool_behaviour == (TOOL_SCALPEL && TOOL_SAW)` is not valid code so whoever tackles this can fix that while there

**Comment by Dawnseer** [comment]
While I'm at it, want to mention that it's not using the new fancy looking borg tool sprites

**Comment by ophaq** [comment]
> While I'm at it, want to mention that it's not using the new fancy looking borg tool sprites

Using the non-arm sprites was maybe intended for better readability but it can be changed. 

Currently all of the tools are functioning as drapes so you can't attack at all as a mediborg.

Also the omnitool for engineering borgs doesn't let you sync on the multitool too. I already told Singul0 about this but if someone fixes it first that's cool. It was an oversight and I don't think it will be that hard to fix.

**Comment by Singul0** [comment]
I'll take a look at this

**Comment by Singul0** [comment]
> The surgery tool uses `RemoveComponentSource(/datum/component/surgery_initiator)` to de-drape-ify it but this is not the proper use of the proc,
> 
>     1. Surgery initiator is not a sourced component
> 
>     2. Its first arg is the source, not the component type
>        So This is likely runtiming and breaking it

Weirdly enough, there isn't a proc for removing non-sourced components...... i'm half debating to just make a new proc for deleting non-sourced components
