### ISSUE TITLE
Ghosts can interact with the synthesizer.

### ISSUE THREAD

**Issue by Pickle-Coding** [tgstation/tgstation#82803]
Reporting client version: 515.1630

## Issue Summary
Ghosts can interact with the synthesizer. They can control all aspects except starting a song.

## Round ID:
[227597](https://scrubby.melonmesa.com/round/227597)

## Testmerges:
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)
- [[READY] the unfuckening of clothing rendering](https://www.github.com/tgstation/tgstation/pull/79784)
- [Controller Overview UI](https://www.github.com/tgstation/tgstation/pull/82739)

## Reproduction:
Watch someone play a synthesizer. Immediately click the synthesizer when they fall down a z-level and drop it, then import the mii theme. Watch as it plays when the victim starts the song. Note that you can also modify it when it's in their hands with observe.

**Comment by WarerBrow** [comment]
it's a feature

**Comment by Sadboysuss** [comment]
Closing in favor of https://github.com/tgstation/tgstation/issues/84971
