### ISSUE TITLE
You can't photocopy paper slips 

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#82811]
Reporting client version: 515.1636

## Round ID:
[227609](https://scrubby.melonmesa.com/round/227609)

## Testmerges:
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)
- [Refactors how basic ais do their success/failures](https://www.github.com/tgstation/tgstation/pull/82643)

## Reproduction:
- Make a paper slip by cutting it up in the paper cutter
- Stick it in the photocopier to make a bunch of Gnarly buisnesscards
- It makes a normal sheet of paper
- Perish

**Comment by Sadboysuss** [comment]
a photocopier holds normal pieces of paper and empty paper slips can't be put into a photocopier for printing on them, not a bug, maybe a bit of an oversight.
