### ISSUE TITLE
Felinids with freerunning no longer land on their feet.

### ISSUE THREAD

**Issue by JohnHenryEton** [tgstation/tgstation#82818]
## Issue Summary
Felinids with freerunning do not land on their feet. After speaking with a maintainer it appears the code is not checking for both freerunning and catlike grace, overriding behavior.

## Round ID:
[227616](https://scrubby.melonmesa.com/round/227616)

## Reproduction:
As a felinid with the freerunning quirk fall one z level. Observe that you do not land on your feet.
See instead that you brace for the fall. You make a hard landing on the floor, but remain unharmed.

**Comment by MrMelbert** [comment]
For the record this was intentional - freerunning takes priority

I think it was Swanni that told me they made z-falling to inhibit your movement in some way, even in cases like moth wings, because being able to fall 1 z-level consequence free would be far too annoying

**Comment by JohnHenryEton** [comment]
When I had talked to Jacquerel they thought it was probably a bug, so I made this.
I agree there should be consequences, though.

**Comment by Dorsisdwarf** [comment]
Tagging as a consistency issue since it's intentional but doesn't work how people should expect given how the cat grace trait works normally
