### ISSUE TITLE
Replaced tiles previously exposed to space are pitch black.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#8282]
http://i.imgur.com/nXBMe4H.png

Likely related to #8264

**Comment by xxalpha** [comment]
Actually...
#7806
#7920 
#7972

**Comment by phil235** [comment]
Pretty sure this is fixed already.

**Comment by Jordie0608** [comment]
This is still happening actually.

**Comment by phil235** [comment]
Do we even know what causes this? I tested with explosions and clf3 smokes but their hull breaches don't cause that.

**Comment by Jordie0608** [comment]
It happens sometimes when replacing a tile by spawning a turf, so it's not just because of space.

**Comment by Miauw62** [comment]
Are the tiles dark or are they missing an icon state?

**Comment by phil235** [comment]
@Miauw62 the tiles are dark.

**Comment by MrStonedOne** [comment]
@Jordie0608 @WJohn @phil235 next time this happens ping me so i can debug. I know lighting.

This shouldn't happen, but i know a few cases that could cause it, mainly runtimes at certain points, so i'd need to vv the turf, the turf's lighting object, and try some things

**Comment by MrStonedOne** [comment]
Actually, i might have fixed this in #13333 I found an edge case where turfs wouldn't show up in a view() because view() takes luminosity into account in odd ways. So i have lighting setting their luminosity to a high number before running view()

**Comment by tedward1337** [comment]
Is this fixed?

**Comment by nullbear** [comment]
IS THIS RELATED TO THE DEVIL GAME MODE BECAUSE IF IT IS THEN UR ALL DUMB

**Comment by phil235** [comment]
Haven't seen the bug occur in a long time, probably fixed.

**Comment by Jordie0608** [comment]
Seems it happened again
