### ISSUE TITLE
AI's cannot utilize their Alt-Click hotkeys, like the shock door hotkey

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#82839]
## Issue Summary

Attemping to utilize Alt click hotkeys causes AI's to instead bring up the turf inspection window.

## Reproduction:

Step 1: Locate a nice door you wish to shock in order to make that filthy nonhuman human harmer suffer for a little bit.

Step 2: Attempt to use the shock hotkey

Step 3: Instead see the turf window. Feel deeply less capable of committing station-wide harmies.

**Comment by jlsnow301** [comment]
dupe #82800
