### ISSUE TITLE
Moon heretic lunatics do not get the lunatic antagonist hud

### ISSUE THREAD

**Issue by Rex9001** [tgstation/tgstation#82835]
Reporting client version: 515.1636

## Issue Summary
See title, when a moon heretic ascends lunatics are meant to be able to see other lunatics.

## Round ID:
[227654](https://scrubby.melonmesa.com/round/227654)

## Testmerges:
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)
- [Refactors how basic ais do their success/failures](https://www.github.com/tgstation/tgstation/pull/82643)

## Reproduction:
Ascend as a moon heretic, lunatics may not get their hud to see each other. 
RELATED: I was a traitor when I was converted, I was also on a seperate z-level if that might have caused it.

**Comment by Rex9001** [comment]
> I'm pretty sure the only indication that you're a lunatic is the moon amulet? They don't have a hud thing to show they're a lunatic, although maybe they should

The intent is that they should have a hud, there is a merged pr adding that.

**Comment by Sealed101** [comment]
link your issues properly gawdammit, fixes %foo _and_ %bar doesn't work!!!!!!!!
#83977
