### ISSUE TITLE
eating apparatus doesn't work

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#82850]
Reporting client version: 515.1636

## Issue Summary
eating apparatus doesn't work

## Round ID:
[227682](https://scrubby.melonmesa.com/round/227682)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/12635164/52dbc460-f5d4-486b-9249-fa3ba4bb4139)
my suit had the eating apparatus
no mask on
can't eat

**Comment by Sadboysuss** [comment]
Seems to be working fine
https://github.com/tgstation/tgstation/assets/96586172/3d09c927-8ae9-4d0f-ba01-5a1b96accf86

**Comment by newfren** [comment]
I was using a handmade civilian modsuit, if that's relevant.

**Comment by projectkepler-ru** [comment]
I couldn't reproduce this again either
