### ISSUE TITLE
Mediborg Omni-Tool is borderline unusable.

### ISSUE THREAD

**Issue by CMDR-Gungnir** [tgstation/tgstation#82868]
Reporting client version: 515.1636

## Issue Summary

This thing didn't get tested at all.  For starters, the Bonesetter doesn't work. I started the surgery, I got to the Bonesetter step, and it just wouldn't work. I had to call a Human over to use a real Bonesetter.

Sometimes the module you select isn't actually the one it brings out, despite it having the sprite for it. This one is only a Maybe because it could be tied to the next issue, which is in my opinion the absolute worst of them all.

At some point during the design process for it, I assume, the idea was given to make it so that a Mediborg can't Accidentally Commit A Harmies. So every single tool counts as Drapes. Perhaps it's a bug, but this became extremely noticeable when I was trying to fight a Broodmother Spider in defense of Law 1, and all of my attempts to fight kept having me trying to begin surgery on the spider. Opening the Drapes menu. This lead to me needing to fight off an entire Spider Infestation with my Fire Extinguisher. Now, fair enough. Maybe you don't want mediborgs hunting valids or something. Ignoring that having the ability to do so is somewhat needed for Law 1 (the Organics were very slow to mobilize to the Spider Call, and it was the AI Shell and I that ended up doing most of the work because the only people who showed up needed to build entire Durands first) it's a problem even for proper surgery, when you start the surgery and then your scalpel removes the drapes instead of actually doing the surgery step.

The Circular Saw also made a regular Scalpel noise when sawing, so I don't actually know if it was even working or if I ended up ghetto'ing it every time.

## Round ID:
[227753](https://scrubby.melonmesa.com/round/227753)

## Testmerges:
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)

## Reproduction:

Just play a round as Mediborg. :)

**Comment by jlsnow301** [comment]
@Singul0

**Comment by 00-Steven** [comment]
Looks like there's already a pr up for at least some of this #82825.

**Comment by Metekillot** [comment]
I understand there's a few bugs with it right now but it'd be more constructive to be less caustic with reporting them. I also understand you're no doubt frustrated so don't get me wrong, but maintainers and contributors work hard to get new stuff and old stuff working. If you're really that upset about it, doing some coding yourself might be a better answer.

**Comment by Singul0** [comment]
Most of the bugs you mentioned has already been in the fix for a while. I noticed the toolset saw was making the incision noise too in debugging. Did a cursory check to see if it's intended. Pretty sure it is? Will do a check later on
