### ISSUE TITLE
Cigarettes can be damaged, making them unwearable

### ISSUE THREAD

**Issue by cnleth** [tgstation/tgstation#82870]
Reporting client version: 515.1636

## Issue Summary
In this round a blob passed over a pack of cigarettes, leaving these "shredded cigarettes" behind. I don't know if only blob can damage them (and if it was really blob and not the infinitely burning fire that stayed on top of the blob because of lag), but they probably shouldn't inherit that behavior from clothing
![shreddedcig](https://github.com/tgstation/tgstation/assets/113535457/1c616d05-834c-4647-9a1c-8c262a07d913)

## Round ID:
[227759](https://scrubby.melonmesa.com/round/227759)

## Testmerges:
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)

**Comment by newfren** [comment]
I bet they can be repaired by cloth lmao
