### ISSUE TITLE
I was spirit of a sword, got thrown and went to black

### ISSUE THREAD

**Issue by deltawest** [tgstation/tgstation#82879]
## Issue Summary

I was spirit of a sword, got thrown and went to black. I believe I was thrown at a wall. My screen went to black, I stopped hearing anything in chat, and couldn't type in LOOC. I could only type in OOC and ahelp, otherwise nothing would open, such as notes or preferences, and the ghost panel would open for a second before disappearing.

## Round ID:

[52342](https://scrubby.melonmesa.com/round/52342)

## Reproduction:

Become a sword spirit, get thrown towards something, everything fades to black. Happened in the Game Room accessible via teleporter.

**Comment by optimumtact** [comment]
what is LOOC?

**Comment by tralezab** [comment]
i have reproduced not being able to talk in LOOC

**Comment by optimumtact** [comment]
What server did you have this issue on?

**Comment by optimumtact** [comment]
You're looking for https://github.com/yogstation13/Yogstation we think.

**Comment by deltawest** [comment]
yeah somehow i ended up on the wrong github, i don't use github at all, sorry

**Comment by neeshacark** [comment]
bro come home this isnt yogs bro

**Comment by lbnesquik** [comment]
He got thrown server to server

**Comment by RipGrayson** [comment]
sounds like a skill issue

**Comment by Dorsisdwarf** [comment]
We are not able to fix problems on Yogstation, unfortunately.

**Comment by Addust** [comment]
how the fuck did he get here from yogs what the fuck

**Comment by deltawest** [comment]
> how the fuck did he get here from yogs what the fuck

magic and a healthy dose of idiocy
