### ISSUE TITLE
getting borged by a cyborg factory gives you a default cyborg name instead of the one set in your preferences

### ISSUE THREAD

**Issue by kawoppi** [tgstation/tgstation#82880]
## Issue Summary 
After getting borged by a cyborg factory you get a name like "Default Android-123" instead of whatever cyborg name you have set in your character preferences.

## Round ID:
[227809](https://scrubby.melonmesa.com/round/227809)

## Testmerges:
The following pull requests are currently test merged:
[#82298: 'Wawastation' by mc-oofert at commit ca9b797e08](https://www.github.com/tgstation/tgstation/pull/82298)

## Reproduction:

1. Set a cyborg name in your character preferences before joining the round.
2. Get kidnapped by borgs and dragged into the borg factory.
3. Check your name.

**Comment by Metekillot** [comment]
This seems kinda on brand for being unwillingly made into a disposable automaton for a rampaging silicon intelligence

Feature not a bug vibes

**Comment by msgerbs** [comment]
INFO: Is this consistent with other cases where you get converted to another species mid-round?

I'm guessing it is, as far as I can recall you don't generally get your preference name if you get transformed mid-round.

**Comment by Dorsisdwarf** [comment]
After looking at the code, it seems that Robotize() is slightly broken and despite checking for a client, is not able to accept one as an argument (unlike its partner AIize()),  and hence can never run the part of the code that updates the new cyborg's name to the client's preferences.

https://github.com/tgstation/tgstation/blob/cf4cc899027116a9f586b51e9d35093d256899eb/code/modules/mob/transform_procs.dm#L134
