### ISSUE TITLE
Plasmacutter projectiles hit one rock and then disappear

### ISSUE THREAD

**Issue by epicgamer545** [tgstation/tgstation#82886]
Reporting client version: 515.1636

## Issue Summary
Plasmacutter projectiles are supposed to pierce rock. Right now, all it does is hit one rock and then disappear into nothing. This isn't intended behavior

## Round ID:
[Round ID]: [227834](https://scrubby.melonmesa.com/round/227834) 

## Testmerges:
#82298 

## Reproduction:
1. pick up a plasma cutter
2. shoot a rock
3. watch the projectile hit one rock then disappear
4. ?!?!?

**Comment by ArcaneDefence** [comment]
Based

**Comment by Dorsisdwarf** [comment]
While this is probbably a better way for this incredibly OP tool to work, its not intended to my knowledge.
