### ISSUE TITLE
Medical Borg Omnitool cautery cant heat beakers, Engie borg crowbar cant be used to quick swap floor tiles. (Omnitool tools lost their original functionality)

### ISSUE THREAD

**Issue by moocowswag** [tgstation/tgstation#82918]
Reporting client version: 515.1631

## Issue Summary
Cyborg omni tool modules seem to have lost a lot of their alternative functionality that they used to have which basically makes
#82425 a massive balance pr if its allowed to stay.

## Round ID:
[227944](https://scrubby.melonmesa.com/round/227944)

## Testmerges:
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)

## Reproduction:
Be medical borg
try to use your now different omnitool cautery to heat up a beaker

nothing happens

Be engie borg
have floor tiles equipped and hold crowbar in other module
click a floor tile

nothing happens

**Comment by moocowswag** [comment]
Also using wirecutter omnitool on a cable cuffed person just has you attack them (rip asimov engie borgs)

**Comment by Singul0** [comment]
I have been thinking of just refactoring the omnitool code with a less shit implementation, the second the first issue hit about it. haven't had the time to do it yet. If anyone wants to refactor it now, you'd probably be faster than me. go ahead

**Comment by norsvenska** [comment]
Looking into this. It seems the code for the borg omnitools were copied from the debug omnitool, and, after further testing, I found the debug omnitool has the same issues. I'm trying to work out a fix, hopefully for the debug tool too.

**Comment by ShizCalev** [comment]
> Looking into this. It seems the code for the borg omnitools were copied from the debug omnitool, and, after further testing, I found the debug omnitool has the same issues. I'm trying to work out a fix, hopefully for the debug tool too.

The debugging omnitool was explicitly NOT supposed to have the additional element/buffer/effect functionality of the actual tools. It shouldn't have been used as a design base lol

**Comment by ShizCalev** [comment]
> Looking into this. It seems the code for the borg omnitools were copied from the debug omnitool, and, after further testing, I found the debug omnitool has the same issues. I'm trying to work out a fix, hopefully for the debug tool too.

I tried adding the proper functionality to the debugging omnitool before and got yelled at, don't add stuff to it.

#70881 / @Fikou

**Comment by moocowswag** [comment]
Just revert https://github.com/tgstation/tgstation/pull/82425 At this point it makes borgs undesireable to play, also only getting 2 omni tools means you can only have 2 of your 3 module slots using a select group of items which kills certain active loadouts

**Comment by Singul0** [comment]
wyci, I have been super busy for two months straight. Give me another month or so and i'll have more than ample time to refactor the whole thing to be less shoddily coded. I do stand by my case for omnitools being better ux/ui intuitively.
