### ISSUE TITLE
You can blink outside the arena, into other z-levels, and possibly onto the station in Deathmatch

### ISSUE THREAD

**Issue by nickup9** [tgstation/tgstation#82922]
## Issue Summary

As a Necromancer on the Ragin Mages map for deathmatch, you can blink out of bounds to get into other z-levels, and possibly onto the station.

Deadass.

![image](https://github.com/tgstation/tgstation/assets/16405947/7a471469-f5c9-47ca-bfe0-0b90e6caf1b9)

![image](https://github.com/tgstation/tgstation/assets/16405947/37e9b037-fbca-44e9-9e5d-8ff4d05d02c8)

![image](https://github.com/tgstation/tgstation/assets/16405947/4c0941f0-56ed-4279-84aa-15c66a6a4faa)

## Testmerges:

#82904

## Reproduction:

Step 1: Go as a necromancer on the Ragin Mages map
Step 2: Blink outside the arena
Step 3: Keep spamming blink at the bounds of the z-level until you teleport into the next z-level
Step 4: ???
Step 5: Profit!
Optional: Get a staff/fire-extinguisher in order to move better in space

I also tried this on Arena Station and it didn't work, it seems there's a noteleport flag on other DM maps to prevent this chicanery but not on Ragin Mages.

**Comment by MrMelbert** [comment]
#82815
