### ISSUE TITLE
Malfunctioning AI cannot hack APCs

### ISSUE THREAD

**Issue by Isratosh** [tgstation/tgstation#82948]
Reporting client version: 515.1635

## Issue Summary
Opening an APC interface and clicking "Override Programming" does nothing. No runtimes when reproduced locally, however the linked live round had a bunch of these possibly related runtimes as pasted below.
```
[2024-04-29 03:14:50.789] RUNTIME: runtime error: undefined variable /mob/dead/observer/var/malf_picker
 - proc name: ui data (/datum/antagonist/malf_ai/ui_data)
 -   source file: code/modules/antagonists/malf_ai/malf_ai.dm,169
 -   usr: null
 -   src: Malfunctioning AI (/datum/antagonist/malf_ai)
 -   call stack:
 - Malfunctioning AI (/datum/antagonist/malf_ai): ui data(Tik-Tok (/mob/dead/observer))
 - /datum/tgui (/datum/tgui): get payload(null, 1, null)
 - /datum/tgui (/datum/tgui): send update(null, null)
 - tgui (/datum/controller/subsystem/tgui): try update ui(Tik-Tok (/mob/dead/observer), Malfunctioning AI (/datum/antagonist/malf_ai), /datum/tgui (/datum/tgui))
 - Malfunctioning AI (/datum/antagonist/malf_ai): ui interact(Tik-Tok (/mob/dead/observer), /datum/tgui (/datum/tgui))
 - /datum/tgui (/datum/tgui): process(0.9, 0)
 - tgui (/datum/controller/subsystem/tgui): fire(1)
 - tgui (/datum/controller/subsystem/tgui): ignite(1)
 - Master (/datum/controller/master): RunQueue()
 - Master (/datum/controller/master): Loop(2)
 - Master (/datum/controller/master): StartProcessing(0)
 ```

## Round ID:
[228030](https://scrubby.melonmesa.com/round/228030)

## Testmerges:
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)
- [[no gbp] Fixes deathmatch observers](https://www.github.com/tgstation/tgstation/pull/82931)

## Reproduction:
1. be malfunctioning AI (I ran the midround ruleset locally)
2. click APC
3. click Override Programming red button
4. nothing happens

**Comment by MrMelbert** [comment]
That runtime is unrelated and has to do with malf AIs that ghost using their antag ui

**Comment by Isratosh** [comment]
https://github.com/tgstation/tgstation/pull/82590

**Comment by Metekillot** [comment]
Will fix when I get home from work

**Comment by Metekillot** [comment]
Apc_malf.dm line 15 is where the bug is I believe; if anyone wants to jump it before me feel free because I'll be doing no GBP anyway
