### ISSUE TITLE
You can put the nuclear authentication disk in a burger by putting it in a forensic bag, frying it then putting the bag in a burger.

### ISSUE THREAD

**Issue by Pickle-Coding** [tgstation/tgstation#82958]
Reporting client version: 515.1630

## Issue Summary
You can put nuclear authentication disks in the burger by putting it in a forensic bag, frying it then putting the bag in a burger.

## Round ID:
[228065](https://scrubby.melonmesa.com/round/228065)

## Testmerges:
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)

## Reproduction:
Get the nuclear authentication disk. Put the disk in a forensic bag. Fry the forensic bag. Put the forensic bag in a burger. The disk is now in a burger. Nukies cheesed.

**Comment by msgerbs** [comment]
Does it get spit out if you eat the burger?

**Comment by norsvenska** [comment]
put the nuke disk in a burger in a box full of burgers in a backpack full of boxes full of burgers in a locker full of backpacks full of boxes full of burgers. oh and add mint toxin to a few of the burgers so that the nukies get gibbed for eating the burgers. just as the gods intended.

**Comment by projectkepler-ru** [comment]
that sounds incredibly broken

good thing flamethrower and crematorium exist

**Comment by Sealed101** [comment]
![изображение](https://github.com/user-attachments/assets/fc63220c-177c-4d75-b72a-0011ea65d601)
currently not reproduceable; also how was this a bug, again?
