### ISSUE TITLE
Accelerator cannon turrets going insane and blocking the whole screen

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#82965]
## Issue Summary

Lok at the video. WTf

## Reproduction:

https://cdn.discordapp.com/attachments/280051925154660363/1234642530667200594/Desktop_2024.04.29_-_20.07.47.04.DVR.mp4?ex=663179f5&is=66302875&hm=989aa4891e163615ae5134646c7b9acda661a564052536ff330c722c6d1143ad&

**Comment by TheVekter** [comment]
> This content is no longer available.

**Comment by msgerbs** [comment]
Please upload the video to Github directly, Discord links don't work for more than a few days.

**Comment by private-tristan** [comment]
discord videos do work, but you need to put them back into discord to have them function.
https://github.com/tgstation/tgstation/assets/54422837/b1379da0-0d8b-4332-82e2-0fa264fc2a40

**Comment by paganiy** [comment]
praise the sun
