### ISSUE TITLE
crew manifest lobby button is broken

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#82971]
Reporting client version: 515.1636

## Issue Summary
crew manifest lobby button displays most crew as Unknown working Unknown job, with the except of the rd.

## Round ID:
[228103](https://scrubby.melonmesa.com/round/228103)

## Testmerges:
- [[no gbp] Fixes deathmatch observers](https://www.github.com/tgstation/tgstation/pull/82931)
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)
- [General IP intel tweaks](https://www.github.com/tgstation/tgstation/pull/82904)

## Reproduction:
hit the crew manifest button from the lobby
![image](https://github.com/tgstation/tgstation/assets/12635164/a5e57a7b-7ff0-4648-8003-94ceed32288a)
reconnect and check again
![image](https://github.com/tgstation/tgstation/assets/12635164/2f274f2f-fd95-4ae0-a969-e7a9b240490b)

**Comment by Ossa88** [comment]
So, not a bug.

Someone hacked/purged the manifest... these picture were inbetween the AI (myself) correcting everyone back in. All entries were done by hand.
