### ISSUE TITLE
Human bitrunner mobs gib upon attempting to leave the simulation

### ISSUE THREAD

**Issue by Rhials** [tgstation/tgstation#82973]
## Issue Summary

Human bitrunner mobs get gibbed upon trying to leave the domain, as the result of their chest being teleported instead of the mob (I think?)

## Round ID:

Tested Locally

## Testmerges:

Tested Locally

## Reproduction:

Be a cyber-police or cyber-tac mob.

Walk into the goalpost in an emagged domain to leave.

Oh what the fuck dude you just exploded?? What?? You aren't supposed to be doing that come on man.

![image](https://github.com/tgstation/tgstation/assets/28870487/699c0d69-386c-4f6c-ac55-fe7e1a786ffc)

**Comment by jlsnow301** [comment]
Thank you for this, closing as dupe because #83181 had more info
