### ISSUE TITLE
Look Out, Sir! achievement is broken

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#82989]
## Issue Summary

You don't get an achievement.

## Reproduction:

Arm a frag grenade, throw it near other players, stand on it and die in proccess.

**Comment by Time-Green** [comment]
You intentionally don’t get the achievement from doing it on yourself

**Comment by SyncIt21** [comment]
Best to add a cleanup flag to this or close the issue

**Comment by Time-Green** [comment]
Yeah just wanted to give them a chance to respond
