### ISSUE TITLE
Placing map templates introduces several unintended overlaying effects

### ISSUE THREAD

**Issue by Majkl-J** [tgstation/tgstation#83009]
## Issue Summary

Several overlays seem to either not hide/generate weirdly when placing templates.

See below for visual explanation

![image](https://github.com/tgstation/tgstation/assets/49160555/e005fb7a-7e36-4911-badd-115c64684152)

Edit: This also applies to the `Spawn ruin` verb

## Round ID:

N/A

## Testmerges:

N/A

## Reproduction:

1. Use the `Map Template - Place` verb
2. Place a map template
3. Pipe and area overlays get very fucky

**Comment by Time-Green** [comment]
Runtime in map loading causes this half-initialized state. Got any logs?

**Comment by Majkl-J** [comment]
> Runtime in map loading causes this half-initialized state. Got any logs? Or preferably just the first runtime

There are absolutely no runtimes to speak off curiously enough.

[2024-05-02 06:30:43.558] GAME: Space-Ruin Survivalist Bunker loaded at 156,134,5

The end of the runtime file, being completely empty:
![image](https://github.com/tgstation/tgstation/assets/49160555/4b752cb6-d298-43a7-811d-adb3c2507e54)

**Comment by IgiariValkyr** [comment]
Vents will also all start off, while scrubbers all start on.

**Comment by Majkl-J** [comment]
Seems to have since been fixed
