### ISSUE TITLE
You can no longer change z-levels when ventcrawling through z-level adapters

### ISSUE THREAD

**Issue by Y0SH1M4S73R** [tgstation/tgstation#83007]
## Issue Summary

Putting a do_after on multi-z movement (#81666) somehow broke ventcrawling up/down z-level adapters.

## Round ID: 

N/A

## Testmerges:

N/A

## Reproduction:

1. Enter the vents on a multi-z map
2. Go to a z-level adapter
3. Move Up/Down, whichever is appropriate for the adapter you are in
4. Nothing happens

**Comment by JohnFulpWillard** [comment]
Fixed by https://github.com/tgstation/tgstation/pull/82996

**Comment by Sealed101** [comment]
i'll take your word on that
