### ISSUE TITLE
Material crafting does not craft objects of the correct material

### ISSUE THREAD

**Issue by Watermelon914** [tgstation/tgstation#83023]
## Issue Summary

Crafting any sort of object from a sheet of materials will produce the iron version of that object, instead of the sheet of material you are crafting it from.

## Reproduction:

Spawn in a bunch of glass sheets
Try crafting a toilet or a chair, see that it's made of iron.

**Comment by larentoun** [comment]
Issue is https://github.com/tgstation/tgstation/pull/82833
