### ISSUE TITLE
Adjusting suit after Alt+click update

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#83039]
## Issue Summary
Can't adjust suit while lying down.
Likely caused by these:
https://github.com/tgstation/tgstation/pull/82533
https://github.com/tgstation/tgstation/pull/82656
You cannot adjust your suit sensors while laying down or on a bed.

## Round ID:
[228315](https://scrubby.melonmesa.com/round/228315) Manuel

## Reproduction:
1) Lie down on a bed or rest.
2) Alt+click your jumpsuit to adjust it.
3) Doesn't work.

**Comment by JackEnoff** [comment]
A lot of tgui menus, not only the suit sensors one, dont work  while resting, for example you cant use drapes to select surgery while lying down, and I think instrument menu doesnt work either while lying down
