### ISSUE TITLE
Sentient bots can't escape the AI sat

### ISSUE THREAD

**Issue by AMyriad** [tgstation/tgstation#83047]
## Issue Summary
They just don't have the access. Some bots spawn in the AI sat, and if there's no one to let them out they'll be stuck there for eternity.

## Round ID:
[228329](https://scrubby.melonmesa.com/round/228329)

## Reproduction:
1. Become sentient bot in AI sat
2. Try to open door
3. ![image](https://github.com/tgstation/tgstation/assets/143908044/39571971-ddb0-47aa-bfd4-4715204f745f)

**Comment by Jacquerel** [comment]
This can be annoying to a player but I am also not sure that it is a bug; those were placed there by mappers for people who can summon bots to mess with rather than with the intention that they become sapient.

**Comment by MrMelbert** [comment]
The fix for this is to make AI satellite bots spawn with player control flag disabled

**Comment by AMyriad** [comment]
> The fix for this is to make AI satellite bots spawn with player control flag disabled

man I'd hate to see that happen, they're fun to play as and sat's the best source of guaranteed bot spawns

**Comment by msgerbs** [comment]
Ask the AI to be let out, pray if there's no AI.

**Comment by Livrah** [comment]
> Ask the AI to be let out, pray if there's no AI.

Happened to me before, AI BOLTED airlocks and never answered again, prays left unheard.

**Comment by xzero314** [comment]
Really annoying as the ai to have bots have access to the SAT.

**Comment by AMyriad** [comment]
> Really annoying as the ai to have bots have access to the SAT.

Why? What is a basic bot going to do, clean your turrets?

**Comment by xzero314** [comment]
> > Really annoying as the ai to have bots have access to the SAT.
> 
> 
> 
> Why? What is a basic bot going to do, clean your turrets?

Letting people in is the big thing. One time while they had access to the sat for that brief period somebody popped in as one and then went and got somebody and brought them to the sat to show them my hacked apcs.

**Comment by AMyriad** [comment]
> Letting people in is the big thing. One time while they had access to the sat for that brief period somebody popped in as one and then went and got somebody and brought them to the sat to show them my hacked apcs.

Wow that is petty as fuck, sorry to hear that. Though imma be real that sounds like more of an admin/player issue than an issue with them having access.

**Comment by moocowswag** [comment]
> > Letting people in is the big thing. One time while they had access to the sat for that brief period somebody popped in as one and then went and got somebody and brought them to the sat to show them my hacked apcs.
> 
> Wow that is petty as fuck, sorry to hear that. Though imma be real that sounds like more of an admin/player issue than an issue with them having access.

Its both a code and policy issue.

Ai, silicons, and emag can all hack bots to change their behavior and tot's agent id is meant to make bots ignore them.

But now we have sentient bots that dont get any text popup when a silicon or tot hacks them to change what team they are on and how they behave


and im 99% sure some admins will still expect hacked bots to be sided with crew even when hacked just because of that.

**Comment by Dorsisdwarf** [comment]
Don't take the AI satellite bots if theres no AI to let you run off with their toys I guess. It's a ghost role, you can check before taking it.
