### ISSUE TITLE
Venus fly trap can move lavaland plants with thier vine ability

### ISSUE THREAD

**Issue by KevinTheGreat333** [tgstation/tgstation#83072]
## Issue Summary
the title says it all, Venus fly trap can move lavaland plants with thier vine ability

## Round ID:
[32053](https://scrubby.melonmesa.com/round/32053) 

I have found it while playing on fulpstation https://github.com/fulpstation/fulpstation

## Testmerges:
https://github.com/fulpstation/fulpstation/pull/1200

## Reproduction:
get the venus fly trap from the kudzu, take it to lavaland and use the vine pulling ability on mushrooms and walk backwards

**Comment by Dawnseer** [comment]
Finally, now that the seraka mushrooms got drafted into the great plant wars we might finally win and see the world covered in flowers
