### ISSUE TITLE
Engiborg omnitool multitool does not link to ore silo

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#83077]
## Issue Summary
It does not link.

https://github.com/tgstation/tgstation/assets/96586172/b98ac7e6-d985-492d-b0a2-81d9a313bce1

## Reproduction:
1. Be cyborg
2. Use your omnitool and select multitool
3. Try to link to a silo

**Comment by moocowswag** [comment]
Its not just omnitools that are broken
**https://github.com/tgstation/tgstation/issues/82918**

**Comment by Sadboysuss** [comment]
@Singul0

**Comment by ShizCalev** [comment]
rewritting multitool buffers to be an element, everything's hardcoded to the item/multitool type atm which is why this is happening.

**Comment by TheRyeGuyWhoWillNowDie** [comment]
#83854
