### ISSUE TITLE
"He seem%PRONOUN_S unable to stay still" - examine text

### ISSUE THREAD

**Issue by norsvenska** [tgstation/tgstation#83083]
Reporting client version: 515.1637

## Issue Summary
![image](https://github.com/tgstation/tgstation/assets/73006946/a3e60fce-c4cb-4e66-9d08-5ad40264172a)

## Round ID:
[228404](https://scrubby.melonmesa.com/round/228404)

## Testmerges:
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)
- [Implements dynamic scaling for spies](https://www.github.com/tgstation/tgstation/pull/82961)
- [Fixes lua breaking when registering signals on turfs](https://www.github.com/tgstation/tgstation/pull/83018)
- [[testmerge] Split up a key parallax proc for profiler purposes](https://www.github.com/tgstation/tgstation/pull/83031)

## Reproduction:
I have no idea, I just examined the guy and got this. Probably something wrong with the file for that text

**Comment by 00-Steven** [comment]
Code in question:
https://github.com/tgstation/tgstation/blob/4b10ed53426bdc1164678090ff4925403281a5b3/code/game/machinery/dna_infuser/organ_sets/carp_organs.dm#L116
![image](https://github.com/tgstation/tgstation/assets/42909981/20403d30-996f-4d18-a6bb-149ae313e244)

Based on other instances:
https://github.com/tgstation/tgstation/blob/4b10ed53426bdc1164678090ff4925403281a5b3/code/game/machinery/dna_infuser/organ_sets/gondola_organs.dm#L34
![image](https://github.com/tgstation/tgstation/assets/42909981/362452ce-4e3d-49d7-b437-8e59f16807c5)

https://github.com/tgstation/tgstation/blob/4b10ed53426bdc1164678090ff4925403281a5b3/code/datums/ai/monkey/monkey_controller.dm#L48
![image](https://github.com/tgstation/tgstation/assets/42909981/30c9e9cd-2d5d-4698-a060-043d9e7c0bee)

This looks like a capitalization issue, where the system checks for `%PRONOUN_s` but not `%PRONOUN_S`.
