### ISSUE TITLE
Having a photo of the blueprints while having the photographer quirk carries it over to the next round

### ISSUE THREAD

**Issue by improvedname** [tgstation/tgstation#83092]
## Issue Summary
Taking a photo of the blueprints allows you to carry it to the next round with photographer quirk. which allows you to use the photo to check the wiring.

## Reproduction:

1. Take photo of blueprints
2. Put the photo in your photographer album
3. Wait for next round
4. Use the photo in the next round to check for wires
5. it works...

**Comment by ZephyrTFA** [comment]
this is just two features interacting with each other.
tempted to called it a feature
