### ISSUE TITLE
Landmines can be pressed by thin windows

### ISSUE THREAD

**Issue by EEASAS** [tgstation/tgstation#83112]
Reporting client version: 515.1636

## Issue Summary

Mapped landmines can be pressed by a thin window, causing it to explode if you step on it, rather than stepping on it
and stepping off

## Round ID:
[228465](https://scrubby.melonmesa.com/round/228465)

## Testmerges:
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)
- [Implements dynamic scaling for spies](https://www.github.com/tgstation/tgstation/pull/82961)

## Reproduction:
Examine a landmine that is behind a windoor or thindow
![image](https://github.com/tgstation/tgstation/assets/109891564/21d88114-be0e-40b0-803a-55d88aa3b128)
![image](https://github.com/tgstation/tgstation/assets/109891564/e067d68b-905b-4eef-91c1-5a02d73aef41)

**Comment by ShizCalev** [comment]
Got it fixed, just tweaking some timings. Will pr tonight
