### ISSUE TITLE
Recurring slime extracts dissapears after a few uses

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#83126]
## Issue Summary

Use I injected a Recurring Dark Purple exctract 3~ times with plasma syringe, it dissapeared. Same when I tried it in plumbing.

## Round ID: [228450](https://scrubby.melonmesa.com/round/228450)

**Comment by ZeroKelvn** [comment]
How quickly did you inject the Recurring extract? It's probable that the extract wasn't given enough time to recharge another use before its last charge was used up.

**Comment by Time-Green** [comment]
nature is healing 🥺

**Comment by Livrah** [comment]
> How quickly did you inject the Recurring extract? It's probable that the extract wasn't given enough time to recharge another use before its last charge was used up. For reference, a Recurring Dark Purple requires 20 seconds per charge.

Is it suppose to just dissapear? It limites xenobio plumbing even more

**Comment by CCC23** [comment]
> > How quickly did you inject the Recurring extract? It's probable that the extract wasn't given enough time to recharge another use before its last charge was used up. For reference, a Recurring Dark Purple requires 20 seconds per charge.
> 
> Is it suppose to just dissapear? It limites xenobio plumbing even more

recurring slowly regenerates uses over time its not infinite so that you cant automate everything but it still can techically be used infinitely if you wait after cause it can get up to 9 uses

**Comment by ZeroKelvn** [comment]
> > How quickly did you inject the Recurring extract? It's probable that the extract wasn't given enough time to recharge another use before its last charge was used up. For reference, a Recurring Dark Purple requires 20 seconds per charge.
> 
> Is it suppose to just dissapear? It limites xenobio plumbing even more

As somebody who regularly plumbs with Xenobiology, you just need to keep in mind how long it takes for the recurring extract to recharge. I'd recommend looking at the crossbreeding/recurring.dm file to see what their charge times are, and adjusting the dose on the plumber appropriately. For instance, a recurring dark purple could be drip fed 0.05u a second and theoretically never delete itself.

**Comment by Livrah** [comment]
Still weird what it deletes self instead of being on cooldown.
