### ISSUE TITLE
Haunted eightball ghost vote is late and answer is random

### ISSUE THREAD

**Issue by cnleth** [tgstation/tgstation#83120]
## Issue Summary
Haunted eightball ghost vote starts only when the do_after is over and it gives a random answer to the user just like a normal magic eightball.
The vote is triggered once a person starts shaking it, but the window is empty and says something like "No question was asked" and does not change if that person says something, although there is a question that can be seen in the chat announcement and in the vote after do_after. The vote works correctly only after the person finished shaking it, but then it's too late because the ball already gave a random answer

## Round ID:
[228450](https://scrubby.melonmesa.com/round/228450)

## Testmerges:
#83043 
#83045 
#83046

**Comment by Admiral-Gigaton** [comment]
weighted random moment
