### ISSUE TITLE
Slimes sometimes dont feed

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#83136]
## Issue Summary

idk if this is about slime refactor (which made xenobio slimes feed 1/3 slower than before) or current highpop server lags. (840) and (987) number slimes didn't eat at all this round.

**Comment by Profakos** [comment]
The feeding slower bug has been fixed in  #82284.
Server lag  can turn off every basic mob at once, if there is not enough server processing power, this is being worked on by others.

**Comment by Livrah** [comment]
> The feeding slower bug has been fixed in #82284.

Not the amount of monkeys, but the time to eat 1 monkey

**Comment by Profakos** [comment]
Other possible cause is the refactor of how AI planning works.

**Comment by Sadboysuss** [comment]
doesn't seem to be an issue anymore, please tell us if you experience it again.
