### ISSUE TITLE
Cook has two job slots open, but only one is filled during roundstart, causing buggy looking behaviour.

### ISSUE THREAD

**Issue by ZAMODA** [tgstation/tgstation#83140]
Reporting client version: 515.1636

## Issue Summary
Cook has two job slots open, but only one is filled during roundstart, making it where if you were to roll antag with only cook, you just don't get it despite the job slot being open.
![image](https://github.com/tgstation/tgstation/assets/36141254/d88a04c1-6dd5-49e8-949b-7d9d3d91d0d3)
![image](https://github.com/tgstation/tgstation/assets/36141254/4ebbc4e5-f7cb-4e27-a6e7-c8841779bc19)

## Round ID:
[228525](https://scrubby.melonmesa.com/round/228525)

## Testmerges:
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)
- [Implements dynamic scaling for spies](https://www.github.com/tgstation/tgstation/pull/82961)

## Reproduction:
Have two people ready up for chef/cook
One gets in, other gets antag but can't get in due to wacky cook/chef coding.

**Comment by JohnFulpWillard** [comment]
This is for any job that has a different amount of job positions for roundstart and latejoin, and it's normal

**Comment by Dorsisdwarf** [comment]
The number of jobs available to latejoiners and the number of jobs available to roundstart selection are frequently not set to the same, to avoid it being absolutely mandatory to be present at roundstart. This includes atmos techs, cargo techs, cooks, botanists, janitor, and scientists by default on the codebase. (cyborgs do it the other way around, with more roundstart spawns than latejoins)
