### ISSUE TITLE
Fultons Can Extract Mining Vent Drones

### ISSUE THREAD

**Issue by Weisyl** [tgstation/tgstation#83164]
Reporting client version: 515.1636

## Issue Summary

As the title says, you can use a fulton to extract the drone that comes to secure the vent. What this means is that you can trigger the vent defense, fulton the drone off elsewhere, and run off, completely skipping out on having to defend said drone. It will be safe and eventually tap the ore vent as normal without any defense necessary.

## Round ID:
[228600](https://scrubby.melonmesa.com/round/228600)

## Testmerges:
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)

## Reproduction:

Set up a fulton extraction beacon basically anywhere, such as on station. Go find an ore vent, begin tapping it. Once the drone starts hovering over the vent, simply click with the fulton beacon to extract it. It'll get airlifted out to safely but since it's still alive and moved elsewhere (and this interaction was never though of), it'll continue tapping the ore vent from wherever it gets extracted to.

**Comment by ArcaneMusic** [comment]
Say it with me now

FUCK
