### ISSUE TITLE
She hunch%PRONOUN_ES

### ISSUE THREAD

**Issue by RengaN02** [tgstation/tgstation#83188]
## Issue Summary
Rat heart owners examine text:
![image-4.png](https://github.com/tgstation/tgstation/assets/60517664/c2909b26-cb2b-460f-bf6a-13666108a5f7)

## Round ID:

Downstream: [Psychonaut](https://github.com/psychonaut-station/PsychonautStation)

## Reproduction:

Examine a rat heart owner

**Comment by ShizCalev** [comment]
Downstream issue. 
![image](https://github.com/tgstation/tgstation/assets/6209658/92c3006a-8296-454f-9f44-946612e4a050)
