### ISSUE TITLE
human bitrunning glitches get gibbed when attempting to escape the domain through an emagged server

### ISSUE THREAD

**Issue by Y0SH1M4S73R** [tgstation/tgstation#83181]
## Issue Summary

`reset_equipment` qdels all datums in `get_contents` before re-equipping the outfit. For humans, `get_contents` includes bodyparts. When the chest gets deleted, the mob gets gibbed.

## Testmerges:

#82298

## Reproduction:

1. Emag bitrunning server
2. Spawn cyberpolice or cybertac
3. Try to escape
4. Get gibbed

**Comment by Y0SH1M4S73R** [comment]
This bug fucked me out of being able to assault the station as a cybertac
And the admins had the gall to just let a random applying ghost get the amelioration

**Comment by SyncIt21** [comment]
Duplicate #82973

**Comment by Y0SH1M4S73R** [comment]
well this issue explains the code responsible for the bug
