### ISSUE TITLE
Favorite brand selection for smoker quirk not working

### ISSUE THREAD

**Issue by Dawnseer** [tgstation/tgstation#83196]
Reporting client version: 515.1637

## Issue Summary
Picking a favorite brand seems to not work, it's stuck to random.

## Round ID:
[228715](https://scrubby.melonmesa.com/round/228715)

## Testmerges:
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)
- [Fixes some bitrunning related issues [no gbp]](https://www.github.com/tgstation/tgstation/pull/83184)

## Reproduction:
Get smoker quirk. Try to pick a favorite brand. Watch as it defaults back to random after you change page

**Comment by SyncIt21** [comment]
Duplicate #82538

**Comment by ShizCalev** [comment]
Duple of #82538
