### ISSUE TITLE
Bandoliers sort junk ammo

### ISSUE THREAD

**Issue by Loafin34** [tgstation/tgstation#83201]
## Issue Summary
If you put junk rounds into a bandolier, it sorts it by what type it is. This is bad, because then one could theoretically have a solely-incendiary junk round belt/

## Round ID:
[228731](https://scrubby.melonmesa.com/round/228731)

## Testmerges:
[#82298: 'Wawastation' by mc-oofert at commit a63ece8a62](https://www.github.com/tgstation/tgstation/pull/82298)
[#83184: 'Fixes some bitrunning related issues [no gbp]' by jlsnow301 at commit 2851fe9a52](https://www.github.com/tgstation/tgstation/pull/83184)

## Reproduction:
Bandolier
Junk Ammo crafted
Place inside
see

**Comment by necromanceranne** [comment]
This isn't a bug, just an incidental feature. It doesn't openly tell you what shells are what in your belt, so you need to still experiment and determine which is which by some method.

I don't think there is any problem with assistants spending time in maintenance test firing junk shells to produce a reliable load out. We call that gameplay. The difference is when you're making shells in an emergency and you don't have the time to determine which is which, which is gameplay onto itself.
