### ISSUE TITLE
Chamelion gun can spawn green locken uppon transfrom into locker staff.

### ISSUE THREAD

**Issue by Holinka4ever** [tgstation/tgstation#83204]
Reporting client version: 515.1636

## Issue Summary

The chamelion gun, if you transform it into llocker staff, it will spawn green magical locket
## Round ID:
[228749](https://scrubby.melonmesa.com/round/228749)

## Reproduction:
1.Find chamelion gun in space ruins
2.Transform it into locker staff
3.It will spawn green magic locker upon transform

**Comment by SyncIt21** [comment]
Duplicate #67618

**Comment by Holinka4ever** [comment]
These problem is too aged seems
