### ISSUE TITLE
Wawa station lacks camera consoles for the labour camp.

### ISSUE THREAD

**Issue by Pickle-Coding** [tgstation/tgstation#83234]
Reporting client version: 515.1630

## Issue Summary
There are no consoles for the labour camp in Wawa station.

## Round ID:
[228870](https://scrubby.melonmesa.com/round/228870)

## Testmerges:
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)
- [Creates a heatmap for atmos processing](https://www.github.com/tgstation/tgstation/pull/83217)
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)

## Reproduction:
Attempt to monitor the labour camp. Notice that there are isn't a way to do that without flying into the labour camp.

**Comment by SyncIt21** [comment]
You can report the issue directly in #82298 while it's still drafted
