### ISSUE TITLE
Malf AI cant interact with hacked APCs

### ISSUE THREAD

**Issue by JackEnoff** [tgstation/tgstation#83254]
## Issue Summary
 
Title, Malf AIs cant interact with an APC they hacked at all, none of the actions with an APC can be made.

## Round ID:

Tested on local, and at least another person has complained about this issue in the discord

## Reproduction:

-Be malf AI
-Hack any APC
-Despair as you cant use it anymore at all

**Comment by ShizCalev** [comment]
@Echriser ?

**Comment by Echriser** [comment]
> @Echriser ?

Yes?

**Comment by ShizCalev** [comment]
#82590 @Metekillot

**Comment by Metekillot** [comment]
I see the problem but I also see another bug that fixing this bug will reveal so I will have to take a day or two
