### ISSUE TITLE
Cult slurring can produce phrases that trip the IC filter

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#83276]
Reporting client version: 515.1637

## Issue Summary
Drank Nar-Sour, tried to yell about an incoming issue, it got filtered because the slurring made one stretch turn into ' ngl ', and PEOPLE DIED [got slightly inconvenienced by a monkey I couldn't call security about]

## Round ID:
[229013](https://scrubby.melonmesa.com/round/229013)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [lavaland raptors](https://www.github.com/tgstation/tgstation/pull/82537)
- [Micro-optimizes _SendSignal a bit](https://www.github.com/tgstation/tgstation/pull/83244)

## Reproduction:
1. Drink Nar-Sour or presumably get Cult Funny-Handed
2. Try to talk
3. Uh oh! Can't say that on our good christian station!
![Screenshot 2024-05-17 134534](https://github.com/tgstation/tgstation/assets/88996803/c3e79ce9-5856-4d3c-919c-16a05a400866)

**Comment by PapaMichae1** [comment]
Duplicate of https://github.com/tgstation/tgstation/issues/78181

**Comment by OuroborusReporter** [comment]
I'm cooler than pickle though /s
