### ISSUE TITLE
Smoker quirk customisation does not update

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#83277]
Reporting client version: 515.1637

## Round ID:
[229017](https://scrubby.melonmesa.com/round/229017)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Micro-optimizes _SendSignal a bit](https://www.github.com/tgstation/tgstation/pull/83244)

## Reproduction:

(I thought this was already logged, apologies if so)

Set up your character preferences, select the smoker quirk, click the cog, change the setting.  I'm not sure if there's a missing 'save/confirm' option here, seems the only way forward after this is to click outside the setting subwindow but if you then go back into the cog the setting still says random.

When messing on myself, at no point does my preference in my client/preferences/values ever change from /datum/preference/choiced/smoker = "Random" (not with the sub preference window open with a different choice or after clicking outside it)

**Comment by Dman757** [comment]
The other open issue unfortunately doesn't have "quirk" in the title or body so doesn't come up in search easily. Duplicate #82538
