### ISSUE TITLE
Hivelord spawns worms on point-click

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#83280]
## Issue Summary

Player controlled Hivelord (from polymorph belt) was spawning aggressive AI worms on shift middle click. HUD button to spawn it was off. Maybe the same with legions.

**Comment by Jacquerel** [comment]
I can't reproduce this with middle click, although I can with left click. Seems to be intentional that any ranged click will spawn worms.

**Comment by Sadboysuss** [comment]
please reproduce:

> was spawning aggressive AI worms on shift middle click

via video or new reproduction steps

**Comment by Sealed101** [comment]
cleanup flagged epic fail + you don't actually need the action to be on to spawn a brood. toggling the action on then pointing with shift-MMB does spawn broods as well, which is kinda janky but not really IMO?

this code means that any left click will spawn a brood during `ClickOn()` 
https://github.com/tgstation/tgstation/blob/01bb03e02f595b7013b3b569bac4ce72ee914a3d/code/modules/mob/living/basic/lavaland/hivelord/hivelord.dm#L67-L68
