### ISSUE TITLE
Random when antagonist can metagame late revolution (?)

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#83289]
## Issue Summary

With "random when antag" prefs, you get random things roundstart if you was chosen for Provocateur before the roll.
*Previous round was the same charcater slot and worked properly. After the revolution round, character saved as this random choices.

**Comment by Watermelon914** [comment]
This wasn't a bug, by the way.
You were selected a headrev at the start of the round. Head rev doesn't get handed out immediately to give you a bit of time, but it's determined at the start of the round.
