### ISSUE TITLE
Conflicting objectives for spies

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#83284]
## Issue Summary
![image](https://github.com/tgstation/tgstation/assets/96586172/00637cdc-5e8a-406e-9da1-57adcb34b7c0)

## Round ID:
[228990](https://scrubby.melonmesa.com/round/228990) manuel

**Comment by MrMelbert** [comment]
They're entirely randomly generated so this is bound to happen eventually. IMO not worth "fixing" but if someone wants to go the mile they are free

**Comment by Sadboysuss** [comment]
no one is gonna bother doing this
