### ISSUE TITLE
Vow of silence doesn't prevent you from entering a reason for shuttle call.

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#83285]
## Issue Summary
A mime can "speak" when entering a reason for a shuttle call.

## Round ID:
228990 manuel

## Reproduction:
1. Have vow of silence trait
2. Call the shuttle from a comms cobsole with a reason
3. Speak?

**Comment by MrMelbert** [comment]
Wontfix (IMO), I'd rather there be a reason than none
