### ISSUE TITLE
Queen can be grabbed by the sec mech paddy

### ISSUE THREAD

**Issue by CursedBirb** [tgstation/tgstation#83292]
## Issue Summary
Is it intended behaviour that sec mech puddy can grab xeno queen?

## Reproduction:

Be xeno queen.  Get grabbed by the paddy. Die to shuttle gib cause you cant get out in less than 45s

**Comment by Blacklist897** [comment]
both a skill issue and accurate to the film

**Comment by moocowswag** [comment]
Just use acid on it and if you cant ask your drones to

**Comment by githubuser4141** [comment]
> both a skill issue and accurate to the film

but in film it was the yellow ripley not a police ripley :(

btw I don't want to ruin anyone's party but mechs do not care about acid.....

**Comment by CursedBirb** [comment]
> Just use acid on it and if you cant ask your xenos to break it
> 
> That being said, queen should probably break out of a container alot faster than a normal spaceman

I had time to use acid four time and it did nothing

**Comment by CCC23** [comment]
Skill Issue
