### ISSUE TITLE
Nuclear operative modsuit AI can have their laws changed

### ISSUE THREAD

**Issue by Watermelon914** [tgstation/tgstation#83291]
Reporting client version: 515.1635

## Issue Summary

As title says.
Nuclear operative silicons should not hijack-able via the crew remotely.

## Round ID:
[229028](https://scrubby.melonmesa.com/round/229028)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Micro-optimizes _SendSignal a bit](https://www.github.com/tgstation/tgstation/pull/83244)

## Reproduction:

Spawn a intellicard nuke op AI card.
Put them into a modsuit.
Their laws can then be changed via the upload console.

**Comment by carlarctg** [comment]
lmao did the pr author not see this coming? dumbass
