### ISSUE TITLE
Loot panel menu (alt click) floods inputs

### ISSUE THREAD

**Issue by FlufflesTheDog** [tgstation/tgstation#83315]
Reporting client version: 515.1637

## Issue Summary
Loot panel from #82533 floods inputs if there's enough items to display. Seems inconsistent how many items that takes.

## Round ID:
[229070](https://scrubby.melonmesa.com/round/229070)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)

## Reproduction:
Observe a populated server
Alt click the disposals conveyor
![image](https://github.com/tgstation/tgstation/assets/25628932/77b7724f-0060-48b8-9742-80ec7374a2f7)

**Comment by jlsnow301** [comment]
This is fixed in 1638+, please update your client and reopen if its still occurring
https://www.byond.com/docs/notes/515.html
