### ISSUE TITLE
New orbit menu floods inputs

### ISSUE THREAD

**Issue by FlufflesTheDog** [tgstation/tgstation#83314]
Reporting client version: 515.1637

## Issue Summary
Opening the orbit menu (or clearing the search bar, just populating the list) triggers anti-spam protection. Started with #83186 

## Round ID:
[229070](https://scrubby.melonmesa.com/round/229070)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)

## Reproduction:
Join a populated server
Open orbit menu
![image](https://github.com/tgstation/tgstation/assets/25628932/032c513c-b1d4-4fe8-bab1-d3bd26d3b39e)

**Comment by jlsnow301** [comment]
calling an image using 515 image generation is a topic call apparently

**Comment by jlsnow301** [comment]
Similar to https://github.com/tgstation/tgstation/issues/83315#issuecomment-2133970997 this has been fixed in the latest byond version
