### ISSUE TITLE
Peacekeeper cyborg's hyperkinetic dampening field doesn't show the actual field when active

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#83320]
Reporting client version: 515.1637

## Issue Summary
The peacekeeper's dampening field module seems to have broken in a way where it does not project a visual field at all, but still slows projectiles within a certain range.
It supposed to project a visual 5x5(?) field from the cyborg which slows any projectiles fired into it, however the field doesn't show up at all upon activating the module.

## Round ID:
[229090](https://scrubby.melonmesa.com/round/229090)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Sets cache lifespan to 0](https://www.github.com/tgstation/tgstation/pull/83316)

## Reproduction:
1. Become a peacekeeper cyborg.
2. Pull out the dampening field module.
3. Turn the field on.
4. Where's the field?
5. Have somebody shoot nearby while field is active, and see it still functions.

**Comment by projectkepler-ru** [comment]
This issue was also noticed downstream with the projectile dampener module itself

**Comment by Sealed101** [comment]
closing in favor of #83682 because it has visuals
