### ISSUE TITLE
Monkey Powder in Monkey Cubes is too high

### ISSUE THREAD

**Issue by Chowder-McArthor** [tgstation/tgstation#83347]
## Issue Summary

Monkey cubes currently contain 30 units of monkey powder. It only takes one unit of powder with one unit of water to make one monkey. Therefore, players can grind up the monkey cubes, and make thirty monkeys per cube. Using a setup with plumbing, this can be done automatically, and the absurdity skyrockets with the more cubes that are added.

## Round ID:

[229129](https://scrubby.melonmesa.com/round/229129)

## Reproduction:

Get a monkey cube and grind it. You now have 30 units of monkey powder. You can use a dropper to transfer 1 unit at a time, or use a plumbing set up to automate the process to get tons and tons of monkeys.

**Comment by ShizCalev** [comment]
Infinite monkey glitch

**Comment by ShizCalev** [comment]
![image](https://github.com/tgstation/tgstation/assets/6209658/d33e56ac-b08b-453f-9ff0-792656d346ba)
it takes 50 units to do the reaction

**Comment by Chowder-McArthor** [comment]
This isn't a hypothetical, I was able to do this in round. I made dozens and dozens of monkeys with plumbing, but I was also able to do it just with a pair of beakers. I don't think that limiter works anyways because it will use up all the monkey powder, not just 50 units.

**Comment by CCC23** [comment]
monkey powder smoke grenade infinite monkey glitch?

**Comment by Chowder-McArthor** [comment]
From my testing, it uses all the monkey powder to make one monkey, so I don't think you can do monkey smoke.

**Comment by Chowder-McArthor** [comment]
![image](https://github.com/tgstation/tgstation/assets/166885501/72e1006a-4863-47a9-a1df-f7999bc5649e)
As can be seen here, it is too early in the round for me to have this normally - this is all just from the starting monkey cubes.
