### ISSUE TITLE
Paraplegics are horizontal riding raptors (and some other mobs)

### ISSUE THREAD

**Issue by dalmationer** [tgstation/tgstation#83342]
## Issue Summary

When you have the Paraplegic quirk, riding some animals makes you somewhere in between being upright and prone. You are able to do some actions you wouldn't be able to do while prone, but not others. This appears to be the case on raptors as well as wolves. You will appear to be horizontal rather than upright.

![image](https://github.com/tgstation/tgstation/assets/7063681/f43eae63-895c-4c3d-8409-62012fa9b4f2)

## Reproduction:

As paraplegic, drag yourself onto a tamed raptor. You'll be sideways.

**Comment by ElGitificador** [comment]
feature
