### ISSUE TITLE
alt+click necktie broken

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#83359]
## Issue Summary
Trying to alt+click a horrific neck tie opens the alt+click context menu

## Round ID:
[229163](https://scrubby.melonmesa.com/round/229163) manuel

## Reproduction:
1. get a horrific necktie, possibly any other necktie
2. try alt clicking

**Comment by jlsnow301** [comment]
horrific neckties are clip ons

**Comment by Sadboysuss** [comment]
> horrific neckties are clip ons

there is a context tip saying you can alt+click it

**Comment by jlsnow301** [comment]
![image](https://github.com/tgstation/tgstation/assets/42397676/a363b6e9-9c1d-46b9-827a-ca8d32c53c24)
