### ISSUE TITLE
Graphical effects frequently cause performance issues during rounds

### ISSUE THREAD

**Issue by Muffindrake** [tgstation/tgstation#83370]
## Issue Summary

I think we've all been there. Effects that stand out:

- carbons being on fire
- smoke from fire
- items being on fire, with smoke
- stink lines from rotting food
- (stacking) lighting from (stacks of) light-emitting items like produce
- water dripping from carbons
- pollen from hydroponics trays
- condensation/smoke from ovens and cooktops

Whenever there are more than a couple of these on screen at any given time, frame rate will drop to very low values. This is even worse with weak machines, and somewhat terrible on virtual machines (I personally use VMware with VMware Tools).

It's so bad it makes me want to avoid walking anywhere near kitchen and hydroponics every round, because I see enough slideshow presentations at work.

## Reproduction:

- acquire ten monkeys
- light room on fire

## Suggestions:

An on-off toggle for these effects is probably not the way to go, since people with effects enabled will still be unable to do anything if they walk into a pile of rotten items. They get the FPS drop from the stink lines AND the FPS drop from having lots of items on screen. If anything, they would have to be globally disabled.

**Comment by Muffindrake** [comment]
I just encountered a situation where for some reason, burning bodies inside His Grace caused a Chaplain, that was immune to fire, to have a portable framerate killing device. So people are already abusing it :)

**Comment by SmArtKar** [comment]
Mitigated partially by #87892, need to move more particles to the new system but after that we can close this.
