### ISSUE TITLE
Nausea from rust heretic tiles is permanent if you scrub the rust from the tile while standing on it

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#83375]
Reporting client version: 515.1637

## Issue Summary
Stepped onto a rust tile for a few seconds while cleaning them, and immediately stepped off once I noticed the low-end nausea icons. I got to spend the rest of the round (~25-30 minutes) vomiting or trying to vomit, essentially paralyzing me. Had a nutriment pump installed to counteract the hunger debuffs, but it also meant I got to ACTUALLY vomit for the rest of the round.

## Round ID:
229196

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Sets cache lifespan to 0](https://www.github.com/tgstation/tgstation/pull/83316)

**Comment by OuroborusReporter** [comment]
For added context, the DISGUSTED effect persisted through chugging 60u of tea and 30u of Sol Dry, on top of the wait

**Comment by EnterTheJake** [comment]
> For added context, the DISGUSTED effect persisted through chugging 60u of tea and 30u of Sol Dry, on top of the wait

There's a chance your nutrient implant got EMPd, which causes constant disgust.

**Comment by OuroborusReporter** [comment]
> > For added context, the DISGUSTED effect persisted through chugging 60u of tea and 30u of Sol Dry, on top of the wait
> 
> There's a chance your nutrient implant got EMPd, which causes constant disgust.

I received the implant around the 5-10 minute mark, after I had already ahelped to determine if something had bugged out (admin response was 'It's just like that, unfortunately'

**Comment by EnterTheJake** [comment]
> > > For added context, the DISGUSTED effect persisted through chugging 60u of tea and 30u of Sol Dry, on top of the wait
> > 
> > 
> > There's a chance your nutrient implant got EMPd, which causes constant disgust.
> 
> I received the implant around the 5-10 minute mark, after I had already ahelped to determine if something had bugged out (admin response was 'It's just like that, unfortunately'

Hey! I've managed to reproduce the bug, apparently removing rust while standing on it doesn't trigger an ExitTurf.

I'm brainstorming a solution, but for the time being, don't scrape off rust while standing on it, and if you do, step on a rusted tile and then get out.
