### ISSUE TITLE
Living flesh grammar weirdness

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#83373]
## Issue Summary
![image](https://github.com/tgstation/tgstation/assets/66640614/ed99c54c-0719-4e5a-a259-d4fae4e9aef0)
Specifically `The living flesh tears off and attaches itself to where Sam MCR limb used to be!` and `Sam MCR the meat arm instinctually starts feeling the floor!`

**Comment by projectkepler-ru** [comment]
I got around to this and is looking at it now
![image](https://github.com/tgstation/tgstation/assets/99981766/2404a83f-4f54-40f6-a4c5-25449e00b935)
