### ISSUE TITLE
Paradox Clones ignore hair gradient

### ISSUE THREAD

**Issue by PapaMichae1** [tgstation/tgstation#83388]
## Issue Summary
Paradox clones don't spawn with the same hair color gradients that the originals do. If the gradient is a large part of the hair, this can make the clone exceedingly obvious.

![dreamseeker_uqBKrpQ3iw](https://github.com/tgstation/tgstation/assets/152340324/49d1d52e-bc3b-4b44-a747-c0a2e5cb70d9)

## Round ID:
[229225](https://scrubby.melonmesa.com/round/229225)

## Testmerges:
[#82298: 'Wawastation' by mc-oofert at commit 1f7ced9dd6](https://www.github.com/tgstation/tgstation/pull/82298)
[#82877: 'Cult Vs. Heretic: 7 Months Later Edition' by carlarctg at commit d65b59db1a](https://www.github.com/tgstation/tgstation/pull/82877)
[#83227: '[TM ONLY] Hijacked Revision Date for v3 TGS Api' by ZephyrTFA at commit 8575d21082](https://www.github.com/tgstation/tgstation/pull/83227)

**Comment by Admiral-Gigaton** [comment]
hmmm, so youre saying i should make my character has almost completely, say, blue hair, but it turns out to be a gradient, so my clone has, again, say, red hair
