### ISSUE TITLE
Heretic for some reason could not sacrifice their targets, regardless of circumstance.

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#83389]
## Issue Summary

A heretic made later in the round could not sacrifice any target. Their targets, both alive and dead, just couldn't be sacrificed no matter what.

## Round ID: [229225](https://scrubby.melonmesa.com/round/229225)

You're looking for MercuryArrow in this round if you're looking at logs.

## Reproduction:

I don't honestly know! We couldn't figure out what caused the heretic to stop being able to sacrifice. None of the typical blockers were present, they were a fresh heretic, the target was exactly right. The only interesting part of the round was the other heretic had a body swap. No idea if that has any relevance.

**Comment by Jacquerel** [comment]
Testmerge issue created by https://github.com/tgstation/tgstation/pull/82877

**Comment by Sadboysuss** [comment]
since that pr is closed now:
