### ISSUE TITLE
Psyker echolocation lags heavily around spiderwebs (and presumably large amounts of objects in general)

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#83385]
Reporting client version: 515.1637

## Issue Summary
With the psyker form's echolocation being changed to permanently show anything you see that doesn't move, walking near a large amount of items (say, a nest of webs from spiders) causes extremely heavy lag, presumably from updating them constantly or something along those lines.

## Round ID:
[229220](https://scrubby.melonmesa.com/round/229220)

## Testmerges:
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)
- [Cult Vs. Heretic: 7 Months Later Edition](https://www.github.com/tgstation/tgstation/pull/82877)

## Reproduction:
1. Be geneticist and get your instability over 100, or be Punished Chaplain and get enough bad mutations
2. Detroit: Become Psyker
3. Walk near a spider nest
4. Watch as your game drops from 60 fps to 2 spf

**Comment by Admiral-Gigaton** [comment]
honestly, psykers and their vision has been a shitshow from the start, so this isnt the least bit surprising

**Comment by Jacquerel** [comment]
I think that #83125 probably reintroduced the bug fixed in #82005 because #83125 wasn't tested at all
