### ISSUE TITLE
Clowns cannot smoke

### ISSUE THREAD

**Issue by jlsnow301** [tgstation/tgstation#83383]
> Feature requests are not handled in the repository. The best place to discuss these ideas would be on the /tg/station 13 forums here: https://tgstation13.org/phpBB/viewforum.php?f=9&sid=5153c1c704a4fb1006bf7a265e45e03f

Clowns cannot equip cigarettes while masked as both count as a mask. 

![ddjdpax-bd4b4841-a530-4e3a-81df-692f2678cb6f](https://github.com/tgstation/tgstation/assets/42397676/c66ee7c9-fb32-47c5-b0ae-960f6a32fbab)
Art by [TheJiggyDC](https://www.deviantart.com/thejiggydc)

**Comment by Fikou** [comment]
Feature requests are not handled in the repository. The best place to discuss these ideas would be on the /tg/station 13 forums here: https://tgstation13.org/phpBB/viewforum.php?f=9&sid=5153c1c704a4fb1006bf7a265e45e03f

**Comment by jlsnow301** [comment]
> Feature requests are not handled in the repository. The best place to discuss these ideas would be on the /tg/station 13 forums here: https://tgstation13.org/phpBB/viewforum.php?f=9&sid=5153c1c704a4fb1006bf7a265e45e03f

#76881
