### ISSUE TITLE
the new bar movement and botany expansion fucked up which apcs power where

### ISSUE THREAD

**Issue by MaineTheMan** [tgstation/tgstation#83392]
## Issue Summary
botany (and probably other apcs) are not correctly set to rooms, in this case botany was fully powered and functional with a destroyed APC, that shouldnt be possible, there was no other APC that makes sense to power botany

## Reproduction: break botany apc, it doesnt lose power, at all. 
![Screenshot_17](https://github.com/tgstation/tgstation/assets/64584757/3e181d82-d2c2-4d73-80b7-03c1ab9794bb)

**Comment by MrMelbert** [comment]
downstream issue? cannot reproduce

![image](https://github.com/tgstation/tgstation/assets/51863163/6df2b4fa-8dbe-47f4-9c25-026aad67c229)

**Comment by MrMelbert** [comment]
Actually this may be an issue with all APCs in general rather than Icebox, try testing this on some random room

**Comment by Zergspower** [comment]
This either corrected itself or is one of those really fun intermittent issues.
