### ISSUE TITLE
Epi malfunction with allergies.

### ISSUE THREAD

**Issue by DoomAngelBlade** [tgstation/tgstation#83393]
Reporting client version: 515.1636

## Issue Summary

Epinephrine works incorrectly with allergen chemicals.
While testing, it was found that Epi stops meds that patient is allergic to, from ticking(Depleting, while affecting patient) until Epi is gone.

If patient receives 2 chemicals that they are allergic to - first med, that they are allergic to, is not ticking.
Second med is ticking, not stopped by epi without forming histamine.

In result - they are receiving effects of one med they are allergic to, wait till epi leaves, die from chem number two.

## Round ID:
[229245](https://scrubby.melonmesa.com/round/229245)
## Testmerges:
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)
- [Cult Vs. Heretic: 7 Months Later Edition](https://www.github.com/tgstation/tgstation/pull/82877)
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
## Reproduction:

Inject Epi.
Inject 2 meds patient is allergic to.
Watch it how ticks in patient.

(me, actually wanting all allergic chems to tick as usual)

**Comment by PapaMichae1** [comment]
I can reproduce at [fc9656170026fbd841c3786786cb1b3a406b2ba0](https://www.github.com/tgstation/tgstation/commit/fc9656170026fbd841c3786786cb1b3a406b2ba0)
