### ISSUE TITLE
infiltrator modsuit sprites are fucked

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#83446]
## Issue Summary
as title, side sprites are fucked up and either missing pixels or layered wrong

## Reproduction: put on infil mod, watch as side sprite is fuck 
![Screenshot_23](https://github.com/tgstation/tgstation/assets/64584757/9274758e-8e87-458d-b5d4-8025cf2b6092)
![Screenshot_22](https://github.com/tgstation/tgstation/assets/64584757/390239c9-271c-4642-9669-705778dcaa82)
without modsuit
![Screenshot_24](https://github.com/tgstation/tgstation/assets/64584757/2434f55d-3472-4ba4-840c-6e6847a2983d)
![Screenshot_25](https://github.com/tgstation/tgstation/assets/64584757/092c3da5-1880-4c61-bf37-a30a212d31b4)

**Comment by Sadboysuss** [comment]
are you talking about the white stripe that shows?
