### ISSUE TITLE
You can bypass the nukie shuttle by simply being above it's Z level on multi deck map

### ISSUE THREAD

**Issue by projectkepler-ru** [tgstation/tgstation#83443]
## Issue Summary
Nukie shuttle cannot land ontop most of station, so any station with a deck above it allow crew to simply fly above and enter it

## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
There might not actually be a map currently ran on TG that can do this but it can occur downstream 
Currently, if the shuttle is parked, someone could fly above it's Z level and then drop down to bypass any defense system inside

**Comment by projectkepler-ru** [comment]
> the nukie shuttle was given an unbreakable roof decades ago because of maps like tram and northstar

yeah unfortunately despite being a downstream of TG SR/Bubber was able to replicate this issue I mentioned so I'm putting it up here again

**Comment by Likteer** [comment]
I think iff the issue is not present upstream, thanks to a deliberate fix
there's little people here can do without going to work on your codebase instead.

**Comment by MrMelbert** [comment]
Please try to replicated on the lastest master branch.
