### ISSUE TITLE
new northstar medbay has several issues ive seen so far

### ISSUE THREAD

**Issue by Admiral-Gigaton** [tgstation/tgstation#83469]
Reporting client version: 515.1639

## Issue Summary
medbay has cargo disposal units (the ones with destination taggers hanging on them), lacks the "access free one-way exit" parts of their entrance doors, and there appears to be a section of medbay that requires an APC, but is missing one, and is counted as its own room,e ven though its connected to several

## Round ID:
[229450](https://scrubby.melonmesa.com/round/229450)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)
- [disable client auth checks because byond is down](https://www.github.com/tgstation/tgstation/pull/83435)
- [/icons/ folder cleansing crusade part 3](https://www.github.com/tgstation/tgstation/pull/83420)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/130595499/ead842ac-8acb-4b09-912d-f9081fc28499)
![image](https://github.com/tgstation/tgstation/assets/130595499/196d74ed-fbf3-40b6-9517-4b674ce2cba9)
![image](https://github.com/tgstation/tgstation/assets/130595499/2374e663-e71d-478b-9ce0-a9e8eff85b43)

![image](https://github.com/tgstation/tgstation/assets/130595499/82a97632-3136-4165-8ad4-911ff98150ae)
this one is the "no APC" part. you can see in the image a lack of powered lights, and to the right of the janitor, a door that was forced to be crowbarred open due to this. also, to the right of the area with the crowbarred door, was a single normal powercell, likely meaning that it was either destroyed, or counted as invalid (no wall, maybe?) and thus was destroyed

theres a chance this was an in-round issue, though, and not a general one brought about from this PR.

**Comment by TheVekter** [comment]
I can probably fix the first two, I'll try to have a PR up some time tonight. I'll take a whack at the third but powernets are deep magic I don't quite grok so I can't promise I'll fix that.

**Comment by TheVekter** [comment]
The "no APC" thing has either been fixed or was a round thing, as it's got power now.

![image](https://github.com/tgstation/tgstation/assets/7019927/b0ebc097-0c32-4fd7-a9a3-abba5cd0a3fa)

I'm PRing the fix for the other two issues now.
