### ISSUE TITLE
 Importing music to instruments doesn't work

### ISSUE THREAD

**Issue by dalmationer** [tgstation/tgstation#83468]
## Issue Summary

Importing music to instruments doesn't work since the most recent byond update.
The import popup appears, but doesn't let you actually submit the song. The cancel button works, however. 

## Reproduction:

Pick up an instrument,
use e.g. Midi2piano to get a ABC file to copy into the instrument
Attempt to press the submit button.

**Comment by dalmationer** [comment]
my reason to think this was due to the latest byond update is that this worked fine when I was on the older version of byond yesterday, but when I updated today it stopped working. As far as I could tell nothing else was merged recently which touched instrument code.

**Comment by moocowswag** [comment]
Is midi2piano the part that isnt working or actually applying the musical notes to an instrument >(in game)<

**Comment by dalmationer** [comment]
> Is midi2piano the part that isnt working or actually applying the musical notes to an instrument via ui >(in game)<

It's applying them via UI in game that's the issue. Here are the reproduction steps I took:

-Open the popup for the instrument by using the instrument in hand (I used the synth). The instrument popup will appear as normal in the new NTOS style.
-Press the [Import sheet music] button on the popup. The import prompt will appear, where you can paste a pre-written piece of ABC notation. This can be from Midi2piano, or the TG wiki, or self-written. Anything works.
-Press the [Submit] button on the import prompt, which should be green. It appears that on the most recent Byond version, nothing happens and the popup remains up, as if you hadn't pressed the button. You can press the [Cancel] button as normal to clear the sheet music.

If this isn't a BYOND issue, it may be on my end, it's hard to say-- I had another player able to use it in a round.

**Comment by SiyahUsta** [comment]
The problem continues. Although there seems to be a limit of 30.0000 characters, the send button or enter button does not work after 2000 characters.

**Comment by dalmationer** [comment]
I've reproduced this-- it works fine on the previous version of byond, but it doesn't on the latest. It's defs a version issue.

**Comment by Zargoar** [comment]
Songs that worked previously no longer work.

**Comment by lessthnthree** [comment]
Reported started in BYOND 515.1638

**Comment by lessthnthree** [comment]
Consolidating under https://github.com/tgstation/tgstation/issues/83654
