### ISSUE TITLE
Fugitive Icon got that error drip

### ISSUE THREAD

**Issue by TwistedCicrularConvexLens** [tgstation/tgstation#83478]
## Issue Summary

Purple and black never looked so good.

## Round ID:

 [229477](https://scrubby.melonmesa.com/round/229477)

## Testmerges:
[#83227: '[TM ONLY] Hijacked Revision Date for v3 TGS Api' by ZephyrTFA at commit 8575d21082](https://www.github.com/tgstation/tgstation/pull/83227)
[#83316: 'Sets cache lifespan to 0' by Watermelon914 at commit 51e08117a3](https://www.github.com/tgstation/tgstation/pull/83316)
[#83307: 'STATION TRAIT GAMEMODE: Station-Wide Background Checks' by Time-Green at commit daa20a8fa4](https://www.github.com/tgstation/tgstation/pull/83307)
[#83435: 'disable client auth checks because byond is down' by MrStonedOne at commit 27434a41a1](https://www.github.com/tgstation/tgstation/pull/83435)
## Reproduction:

Step 1: Log on.
Step 2: ![image](https://github.com/tgstation/tgstation/assets/106436013/772a7e0e-20e9-4a50-8a89-c9b0ad96bf76)

**Comment by Rhials** [comment]
![image](https://github.com/user-attachments/assets/18b4e878-456a-4c34-9632-9057fa818644)

I believe this has resolved itself?
