### ISSUE TITLE
heretic organs caused unending movement of a body

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#83493]
## Issue Summary
I'm not sure if it's actually caused by the heretic organs but that's my only explanation, even though after removing the heretic organs they didn't stop moving, while alive they didn't stop moving and while dead they didn't stop moving.
https://imgur.com/a/RdxKDDh

## Round ID:
[229495](https://scrubby.melonmesa.com/round/229495) manuel

## Testmerges:
#83227 #83195

## Reproduction:
The player had a corrupted liver, lungs and tongue, after removing them it didn't go away, but it appeared to happen after getting sacced.

**Comment by Time-Green** [comment]
My first guess was Primal Instinct brain trauma but looks like they didn't have that?

**Comment by Sadboysuss** [comment]
> My first guess was Primal Instinct brain trauma but looks like they didn't have that?
> 
> edit: nvm it looks like we don't log brain traumas and the video you posted perfectly obscures the brain trauma section. Do you know if they had primal instinct?

ahah, my bad I didn't notice the window was blocking the traumas, I don't know if they had primal instinct brain trauma and I didn't notice a brain trauma when I was checking health analyzer, the organs popped out to me.
