### ISSUE TITLE
If you click a job icon in the orbit menu, scrolling while hovering over it causes the icon to scroll up and down

### ISSUE THREAD

**Issue by nikothedude** [tgstation/tgstation#83492]
Reporting client version: 515.1635

## Issue Summary

Title.

## Round ID:
[229495](https://scrubby.melonmesa.com/round/229495)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)

## Reproduction:

Step 1: Open orbit menu
Step 2: Click the job icon of someone
Step 3: Place your cursor over the job icon
Step 4: Scroll and watch in amazement as the icon scrolls up and down

**Comment by Iajret** [comment]
@jlsnow301 https://github.com/tgstation/tgstation/pull/83790 reverted the fix and you can scroll icons once again. I wonder if `overflow: clip` would help? Tho, its starting to look more like a weird hack already
