### ISSUE TITLE
Sentient Disease still exists in antag preferences

### ISSUE THREAD

**Issue by PapaMichae1** [tgstation/tgstation#83516]
## Issue Summary
![image](https://github.com/tgstation/tgstation/assets/152340324/86042990-afe0-494b-a874-85d132907265)

## Round ID:
[229542](https://scrubby.melonmesa.com/round/229542)

## Testmerges:
[#83227: '[TM ONLY] Hijacked Revision Date for v3 TGS Api' by ZephyrTFA at commit 8575d21082](https://www.github.com/tgstation/tgstation/pull/83227)
[#83483: 'Removes logging each lua function called on the dm side of things.' by Watermelon914 at commit e031dd21cf](https://www.github.com/tgstation/tgstation/pull/83483)

**Comment by Time-Green** [comment]
Oh wow that is hard to notice
