### ISSUE TITLE
Engineering cyborg circuit manipulation apparatus can't put circuit boards into machine frames.

### ISSUE THREAD

**Issue by L0pz** [tgstation/tgstation#83511]
Reporting client version: 515.1637

When you try to do it it just says "can't add that" even though it used to be able to. I'm pretty sure what's happening is that it's attempting to insert the tool rather than the circuit the tool is holding.

## Round ID:
[229538](https://scrubby.melonmesa.com/round/229538)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Removes logging each lua function called on the dm side of things.](https://www.github.com/tgstation/tgstation/pull/83483)

## Reproduction:

1.Make a machine frame
2. Anchor and wire the machine frame
3. Get a circuit board that is supposed to go in a machine frame and pick it up with the circuit manipulator
4. Try to insert it

**Comment by SyncIt21** [comment]
Duplicate #82774

**Comment by L0pz** [comment]
> Duplicate #82774

Oops sorry
