### ISSUE TITLE
Cooldown Timestamp Wrong Sign

### ISSUE THREAD

**Issue by Gottfrei** [tgstation/tgstation#83514]
## Issue Summary
Okay, so we got timestamp here:
```dm
#define COOLDOWN_START(cd_source, cd_index, cd_time) (cd_source.cd_index = world.time + (cd_time))
```

Now we check if we are good to go:
```dm
#define COOLDOWN_FINISHED(cd_source, cd_index) (cd_source.cd_index < world.time)
```

But the problem is that only proper sign for the macro above is "<=" (cd_source.cd_index <= world.time). Since it will skip equality otherwise, and we are checking for finished state.

**Comment by Jacquerel** [comment]
No offence but it probably took you longer to type this issue report than it would have for you to fix this issue yourself

**Comment by Gottfrei** [comment]
> No offence but it probably took you longer to type this issue report than it would have for you to fix this issue yourself

well in not really a TG contributor, just want you to know about this issue guys.
