### ISSUE TITLE
Explosion Damage Isn't the Full Amount

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#8351]
Currently explosions are only doing 80% of the damage they're supposed to; this is due to how the damage is applied.

Take for example a human getting hit by a severity level 2 explosion: https://github.com/tgstation/-tg-station/blob/d6e435c4407aa7613b12ed642372475e6a53dcd4/code/modules/mob/living/carbon/human/human.dm#L100

it should do 60 brute and 60 fire, but the actual damage you'll take will be 48 brute and 48 fire.

This is because of this section here: https://github.com/tgstation/-tg-station/blob/d6e435c4407aa7613b12ed642372475e6a53dcd4/code/modules/mob/living/carbon/human/human.dm#L124

The total damage adds up to 80%; I suspect that left+right hand and left+right foot were included in this at one point were were planned to be included; either case, since hands and feet aren't a thing on TG, shouldn't all the 0.05's be 0.1's?

**Comment by Supermichael777** [comment]
best way to fix it would be to adjust the values to preserve the present values bomb-code needs a balance anyway due to throw-force shrapnel mechanics

**Comment by Fox-McCloud** [comment]
Upon looking at this further, this seems to be an oversight from a long time ago.

In 4407, it worked like this:
Head: 20%
Chest: 40%
Groin: 10%
Left/right arm (each): 5% (total of 10%)
left/right hand (each): 2.5% (total of 5%)
left/right leg (each): 5% (total of 10%)
left/right foot (each): 2.5% (total of 5%)

It almost seems that when the transition to a more simplified body part system on TG, it was forgotten to merge the explosive damage values from groin, foot, and hands into their parent organs

Guessing this is what it *should* be on live:
Head: 20%
Chest: 50%
Left/right arm (each): 7.5% (total of 15%)
left/right leg (each): 7.5% (total of 15%)

**Comment by tedward1337** [comment]
Still an issue?

**Comment by Cyberboss** [comment]
@lzimann Code was refactored to use `take_overall_damage`, closable
