### ISSUE TITLE
Preferences Potential Bug 

### ISSUE THREAD

**Issue by deetrik** [tgstation/tgstation#8352]
Problem Description: Mid Round Antagonist Toggle either only allows the toggle to work once (OFF setting) or it doesn't report that the toggle has been switched to (ON)

What did you expect to happen: When the toggle mid round antagonist button is pressed it should be either on or off. 

What happened instead: Right now it is permanently off without the ability to switch it on. 

Why is this bad/What are the consequences: I would like to join mid game with a chance to play as the antagonist. Right now it is disabled for me without my ability to turn it on. 

Steps to reproduce the problem: I toggled the option once and then again without effect. 

Server: Which server were you playing on? Yog Station 13

Revision: most current

http://i.imgur.com/Qe9zMAP.png

**Comment by RandomMarine** [comment]
That toggle refers to mulligan antags. Does the server have them enabled?

**Comment by deetrik** [comment]
I confirmed with the admins that mid round antags are enabled for that server.

**Comment by Miauw62** [comment]
May be related to me splitting the toggles variable in two.

**Comment by Incoming5643** [comment]
might also explain the glut of midround antag defaulting to extended as well

**Comment by Incoming5643** [comment]
I cannot replicate this problem on just updated basil, so the problem seems to be somewhere in how yogstation handles their save files. They may need to update some customization they made

**Comment by deetrik** [comment]
I can email the admins if you can isolate where the problem is.

**Comment by deetrik** [comment]
Alright. Admins notified. Hopefully they will contact you guys for guidance.

**Comment by Incoming5643** [comment]
Sorry I didn't update you here, but it's kind of obviously our fault actuality. Like hilariously so.

**Comment by deetrik** [comment]
Well. I hope you guys can resolve it soon.
