### ISSUE TITLE
Can't replace or destroy metal foam floors

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#83526]
Reporting client version: 515.1637

## Issue Summary
Metal foam floor plating - The shitty looking one left behind when a smart metal foam grenade is used in a place with no plating - says 'That's a metal foam plating.
Thin, fragile flooring created with metal foam.
There are a few attachment holes for a new tile or reinforcement rods.'
Despite this, you can't currently:
1. Use floor tiles on it, either material-specific tiles or the generic Floor Tiles from iron, to replace it with a regular plating.
2. Use metal rods on it to reinforce it
3. Use a crowbar on it to remove it entirely

## Round ID:
229571

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Fixes free chemsplosion reagent purging by replacing it with the same thing but dangerous](https://www.github.com/tgstation/tgstation/pull/83195)
- [STATION TRAIT GAMEMODE: Station-Wide Background Checks](https://www.github.com/tgstation/tgstation/pull/83307)

## Reproduction:
1. Bomb medbay
2. Use a smart metal foam grenade in the crater left behind
3. Try to use floor tiles on the foam plating to fix them
4. Despair as you realize a chunk of the ground will look half-fixed for the rest of the round

**Comment by Sadboysuss** [comment]
Just tested this, you can replace these with new tiles when in combat mode, you can also destroy these tiles with one hit using any weapon. I'll work on a more-user friendly explanation
