### ISSUE TITLE
Legion megafauna chests despawning

### ISSUE THREAD

**Issue by Ilgradhr** [tgstation/tgstation#83524]
## Issue Summary

While fighting legion megafauna i saw 3 chests spawn but after the fight I found only two chests that i didnt open. The other one i opened midfight cuz why not. An admin said that there were no closed chests only opened ones. It was 5-10 people lowpop so i dont think that someone yionked them.

## Round ID:

[229564](https://statbus.space/rounds/229564)

**Comment by JohnFulpWillard** [comment]
It's not despawning but the other legions are breaking them which takes the loot out with it

**Comment by necromanceranne** [comment]
So, not really a bug then?

**Comment by Ilgradhr** [comment]
> So, not really a bug then?

I dont really know if thats intended or if it is its just grief. The whole point of legion megafauna is chests and they destroy them.
