### ISSUE TITLE
Shuttle decals duplicate on move

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#83535]
Reporting client version: 515.1639

## Issue Summary

Whenever a shuttle moves, all decals onboard duplicate.
This is most prevalent whenever the shuttle rotates, or on Lavaland, where transparent ash plating decals will build up over time.

## Round ID:
[229584](https://scrubby.melonmesa.com/round/229584)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Removes logging each lua function called on the dm side of things.](https://www.github.com/tgstation/tgstation/pull/83483)

## Reproduction:

- move shuttle
- more decals
- rotate for extra visibility

**Comment by Rhials** [comment]
Welcome back, pubbystation crash engine
