### ISSUE TITLE
Hydroponics tray autogrow with no power.

### ISSUE THREAD

**Issue by DoomAngelBlade** [tgstation/tgstation#83539]
Reporting client version: 515.1636

## Issue Summary
Hydroponics tray can be turned on autogrow even without power.
## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Fixes free chemsplosion reagent purging by replacing it with the same thing but dangerous](https://www.github.com/tgstation/tgstation/pull/83195)
- [STATION TRAIT GAMEMODE: Station-Wide Background Checks](https://www.github.com/tgstation/tgstation/pull/83307)

## Reproduction:
Find room with no power.
Turn on autogrow.
See it turn on for a sec, then turn off.
Turn it on again.
Second later - turn it on again.
It stays turned on, without switching off.

**Comment by the-orange-cow** [comment]
Out of curiosity, do you know if the autogrow effect was present(i.e. reduced nutrient consumption, auto water, auto weed removal), or was it just a normal mode tray with a autogrow sprite?

**Comment by DoomAngelBlade** [comment]
Yes.
Mutations prevented
Water refilled.
