### ISSUE TITLE
Stuck inside holopad?

### ISSUE THREAD

**Issue by K4rlox** [tgstation/tgstation#83540]
Reporting client version: 515.1633

## Issue Summary
crowbaring a holopad in this spesific spot
and nowhere else
causes players to get stuck inside the holopad

https://github.com/tgstation/tgstation/assets/118483925/7da84099-dd3e-48a0-9401-3ab62ab28189

if its moved, you will hit the holopad instead

## Round ID:
[229596](https://scrubby.melonmesa.com/round/229596)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Removes logging each lua function called on the dm side of things.](https://www.github.com/tgstation/tgstation/pull/83483)

## Reproduction:
>be on deltastation
>go to holopad in front of vault
>get ontop of it
>crowbar it
>get stuck inside

**Comment by MrMelbert** [comment]
#80183
