### ISSUE TITLE
Lobstrocities can be used to fish unlimited Tendril Crates, Adamantine and Runite.

### ISSUE THREAD

**Issue by OrbisAnima** [tgstation/tgstation#83565]
## Issue Summary

You can abuse the profound fisher AI behaviour introduced by PR #83146 , by trapping and reviving via lazarus or ashwalker rituals, to farm infinite limited resources from lava, as the check for the reward of the fish for such cases doesnt remove the amount of the special loot table on delivery, getting to ridiculous setups where you can get 1 tendril chest per 15 minutes of work of the lobstrocity recruited, with the expected escalability. This will of course not work if anyone in the shift fishes the tendril crate, as it will erase it from the list, which the AI datum profound fisher doesn't take into account.

## Reproduction:

Make an enclosure with lava. (plasma lake)
kills a lobstrocity
use a lazarus injector
let it work for you and get you unlimited tendril crates. (adamantium and runite)

**Comment by necromanceranne** [comment]
We're just expanding into the same genre as Palworld, don't worry. Lobster-based enslavement camps are the future of mining.

**Comment by necromanceranne** [comment]
Okay, having tested it for a really long time, I could get a decent mount of chests, but the lobsters couldn't pull up a single bit of adamantine or runite. It pulled up a lot of slag and lavaloops.

**Comment by CCC23** [comment]
Is this the future of arc mining? Lobstrocity based slave fishing networks so that you can finally get THAT FUCKING LOOT I ITEM I DONT WANT A GOD DAMN FUCKING PARADOX BAG STOP GIVING ME PARADOX BAGS AHHHHHHHHHHHHHHH ANOTHER FUCKING SHIP IN A BOTTLE IM GONNNA KILL MYSELF

**Comment by necromanceranne** [comment]
If you think thats bad, the lobsters can end up brawling with one another, destroying the chests they pull up. Those fuckers fiend hard for the loops.

**Comment by dalmationer** [comment]
The chests probably shouldn't be infinite (There's only supposed to be one in the pool) but imo lobstrosity domestication is an EMERGENT FEATURE and is funny as hell.
