### ISSUE TITLE
Railings build below the floor tile

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#83575]
Reporting client version: 515.1637

## Round ID:
[229670](https://scrubby.melonmesa.com/round/229670)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Removes logging each lua function called on the dm side of things.](https://www.github.com/tgstation/tgstation/pull/83483)

## Reproduction:

Go to thunderdome, spawn in rods/fifty
Use in hand and create a railing.  Invisible!  Will still block your movement though.
Crowbar up the floor tile you built it on.  Tada, now visible.  You can place the floor tile back down and it will work/look like normal.

**Comment by Time-Green** [comment]
Oops, may've been this PR #83450? @ShizCalev 
https://github.com/tgstation/tgstation/blob/e81f9c6ef0fcc79e301d4196346f4e4d44dd765f/code/game/objects/structures/railings.dm#L79-L80

**Comment by LSommers** [comment]
Oh good, it's not just me.
Was about to submit a report about really broken railings and found this.

It's inconsistent, whatever's causing it, as some players (on the same versions, no less) report no such visual issue, while others do.
