### ISSUE TITLE
faek chameleon hat makes you bald (showsn't hair)

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#83570]
## Issue Summary

fake cahemelon hat doesnt show ur hair

## Round ID:
n/a

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/53100513/f84a115a-26bc-40ae-bf92-4eee3f5f5c45)

**Comment by ShizCalev** [comment]
Which?

**Comment by necromanceranne** [comment]
What do you mean 'fake', do you mean the broken one?
