### ISSUE TITLE
Items can embed even when blocked

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#83574]
## Issue Summary

When you get hit with engi crossbow bolt and the projectile got blocked by riot shield, no damage. But it embededs with blood loss etc. Not sure if it's the same for thrown items.

## Reproduction:

https://private-user-images.githubusercontent.com/97964454/334537606-d71e2800-d9a6-4a9e-b3f4-eb7b506a46e4.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMzQ5NjksIm5iZiI6MTcxNzAzNDY2OSwicGF0aCI6Ii85Nzk2NDQ1NC8zMzQ1Mzc2MDYtZDcxZTI4MDAtZDlhNi00YTllLWIzZjQtZWI3YjUwNmE0NmU0Lm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDAyMDQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5MjVkMmI2YzNjZjFlYTI1NDFiMTY1M2ZkYmZmZjIzMDY2MjMyYzRmY2NlYTg4ZjUwYWVkYWM3NWU1MmU2ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8BpZ67bMbChxKLSx6bnbBdiRCHWHhm5wddke0Dv-NlY

**Comment by Jacquerel** [comment]
Have you experienced this generally or just with this specific item?  
Would help identify whether it's a problem in generic code or just this specific projectile missing a check

**Comment by Livrah** [comment]
> Have you experienced this generally or just with this specific item?

it only happened with the crossbow

**Comment by necromanceranne** [comment]
![image](https://github.com/tgstation/tgstation/assets/40847847/1b102012-8118-4fe1-959d-c2d28802ef48)

I put this to a test. My initial test was going to compared the rebar crossbow to the 9mm, which is also capable of an embed.

The test was using a 100% block shield. I used the PP-95 SMG just to speed up the rate of fire; this has no bearing on the embed chance, only damage (and accuracy, so this had to be fired point blank). Even on what was meant to be a control, I saw bullets embedding through the block. This example is two embeds in a single volley. So it appears this is not exclusive to rebar crossbows, but literally any projectile that can embed.

**Comment by MrMelbert** [comment]
![image](https://github.com/tgstation/tgstation/assets/51863163/e06faaf9-8945-4d46-8865-4e02930f9099)

**Comment by necromanceranne** [comment]
![image](https://github.com/tgstation/tgstation/assets/40847847/deb9ad17-d82e-4ec7-8871-6a83664ae08c)

Nevermind, that's definitely blocking via armor, I think I'll remove that part. I think I'm getting meme'd by armor penetration values :U
