### ISSUE TITLE
Blood-red letterman jacket sprite broken

### ISSUE THREAD

**Issue by Ilgradhr** [tgstation/tgstation#83593]
## Issue Summary

The blood-red letterman jacket that you can get from hacked ClothesMate vendor has its from sprite broken. Its front sprite is see through except the sleуves.

## Round ID:

[229714](https://statbus.space/rounds/229714)

**Comment by necromanceranne** [comment]
![image](https://github.com/tgstation/tgstation/assets/40847847/3ffb2c12-0b27-4f6a-8287-f019f173810d)

No? It's there, the jacket is just open. It doesn't have a closed state. This is also on a live server, by the way.

**Comment by Ilgradhr** [comment]
> ![image](https://private-user-images.githubusercontent.com/40847847/335403947-3ffb2c12-0b27-4f6a-8287-f019f173810d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMTc1MDQsIm5iZiI6MTcxNzExNzIwNCwicGF0aCI6Ii80MDg0Nzg0Ny8zMzU0MDM5NDctM2ZmYjJjMTItMGIyNy00ZjZhLTgyODctZjAxOWYxNzM4MTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDAxMDAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4OGE1ODk4NzRhZTBmNDY5OTEyZDhkNzg1MWU1MGExZmQ4MmY5MGE3ZDBiMjQyMGU4NjM4N2QwODJmNmUxYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._cC0-jq-uiMQHl6CUtnPO1zl5v2VOy6C5w6V-FqfttE)
> 
> No? It's there, the jacket is just open. It doesn't have a closed state. This is also taken from a live server, by the way.

Well i has the red part not being there. And it was 3 hours ago. Tried reequiping it and taking a new one from the vendor
