### ISSUE TITLE
Dullahan race from Genetic instability is broken

### ISSUE THREAD

**Issue by Ilgradhr** [tgstation/tgstation#83592]
## Issue Summary

While I was playing with genetic instability mutation I rolled a Dullahan race and it was bugged out. My body was not connected to the head. I could see with my body but could not hear anything or see any gesture. I hope this race gets a bit fixed (i know it was problematic before) or just cut out of genetic instabitily pool. You can continue rolling races and in a normal round without lavaland mirror you are stuck with a body that can interact with other players but that cant see or hear the reply back.

## Round ID:
[229714](https://statbus.space/rounds/229714)

**Comment by MrMelbert** [comment]
What a shock
