### ISSUE TITLE
Bitrunners on Wawastation can't access the correct side of the ORM to deposit GAMING ores

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#83638]
Reporting client version: 515.1637

## Issue Summary
Bitrunners get decent amounts of ores from encrypted caches when they finish a sim. Normally, they have access to both sides of the ORM, because they're in cargo, and can open the cache in front of the receiving end of the ORM to claim the ores. Wawastation has the ORM embedded in mining instead, which Bitrunners don't have access to, leaving them to have to load the ores into the ORM by hand like a peasant.

## Round ID:
[229813](https://scrubby.melonmesa.com/round/229813)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Borgs: the moduling (Various fixups to borg module code)](https://www.github.com/tgstation/tgstation/pull/83116)
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)
- [Incoming stamina damage while in stamcrit has diminishing returns applied](https://www.github.com/tgstation/tgstation/pull/83445)

## Reproduction:
Be a bitrunner
Have Weighted Random choose Wawastation
Finish a gaming session
Try to drop off your ore loot
Despair

![Screenshot 2024-06-01 151033](https://github.com/tgstation/tgstation/assets/88996803/e1772ee9-a5b1-4312-adcb-58235d42228d)

**Comment by jlsnow301** [comment]
@mc-oofert

**Comment by SyncIt21** [comment]
Report this directly in #82298. Don't create new issues while that PR is still open

**Comment by OuroborusReporter** [comment]
Reported this directly in https://github.com/tgstation/tgstation/pull/82298, so as to avoid creating new issues while that PR is still open
