### ISSUE TITLE
Background check station trait prevents admins from manually executing rulesets.

### ISSUE THREAD

**Issue by Watermelon914** [tgstation/tgstation#83631]
## Issue Summary

As the title says. Admins should be able to manually execute rulesets but they should not run automatically.

This is likely happening because the rulesets are getting filtered out.

## Reproduction:

- Enable background check station trait
- Check antagonists
- Open Game Mode Panel
- Try executing Syndicate Sleeper Agent or forcing a latejoin ruleset.

**Comment by jlsnow301** [comment]
@Time-Green

**Comment by Time-Green** [comment]
I’ll take a look at it sunday or monday
