### ISSUE TITLE
Crutches induce paraplegic tendencies permanently when picked up.

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#83646]
Reporting client version: 515.1639

## Issue Summary
Involves the recent addition of crutches; #83242

When you pick up a crutch (Or vend one from the medical vendor), your character suddenly and immediately falls to the floor. 

From that point there on you will remain on the floor as if you were paraplegic. Regardless if your legs are functional, attempting to rest and unrest yourself, buckle yourself to something and unbuckle, **including even after being given an a-heal.** 

My character needed to be respawned in the round order to be able to walk again, and having testing it on a local host, I had to give myself the paraplegic quirk and remove it to stand up again.

## Round ID:
[229822](https://scrubby.melonmesa.com/round/229822)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Borgs: the moduling (Various fixups to borg module code)](https://www.github.com/tgstation/tgstation/pull/83116)
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)
- [Incoming stamina damage while in stamcrit has diminishing returns applied](https://www.github.com/tgstation/tgstation/pull/83445)

## Reproduction:
1. Go to a Nanomed vendor. (Or spawn a crutch.)
2. Pick up/Vend a crutch.
3. Have a sudden paraplegic affliction occur to your character.
4. Remain on the floor forever.

**Comment by Rhials** [comment]
![image](https://github.com/tgstation/tgstation/assets/28870487/7907301b-1624-4ec8-9536-3c3548079722)

Live footage produced from authentic /TG/station servers.

**Comment by the-orange-cow** [comment]
You've fallen, and you can't get up?

**Comment by TheVekter** [comment]
It's worse, because if you're already a paraplegic and you pick up a cane, you stop being one.
