### ISSUE TITLE
Writing with pen and paper fails at large inputs

### ISSUE THREAD

**Issue by Goat-Real** [tgstation/tgstation#83647]
Reporting client version: 515.1639

## Issue Summary

When writing with pen & paper, if you try to write a large amount of characters at once (~2000 character from my minor testing) it will fail to save what you wrote. Clicking the save button will delete your input and put the character count at what it was before you started writing while failing to write to the paper. You are able to write the 2000 characters in if written into smaller chunks which do not bypass this bugged input limit.

## Round ID:
[229821](https://scrubby.melonmesa.com/round/229821)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)

## Reproduction:

Attempt to write 2000 character with pen and paper.

**Comment by FlufflesTheDog** [comment]
Seems to have started as of byond 515.1638, effects most if not all text inputs

**Comment by dalmationer** [comment]
Yeah, this is also the cause of #83468 and #83654 it's absolutely a 515.1638 issue.

**Comment by lessthnthree** [comment]
Consolidating under https://github.com/tgstation/tgstation/issues/83654
