### ISSUE TITLE
Cryptographic Sequencers can't be placed into containers by clicking them

### ISSUE THREAD

**Issue by dalmationer** [tgstation/tgstation#83643]
## Issue Summary

When an emag is used on a container with left click, instead of being put inside, nothing happens. My theory is that it is trying to apply its emag effect on the container. Right click also doesn't open the container's menu. The only way to put an emag into a container is to right click the container with an empty hand to open it, then click a slot directly.

## Reproduction:

Buy a cryptographic sequencer in the traitor uplink.
attempt to use right or left click to put it into your backpack or open the backpack's inventory menu.
You will note that nothing happens.
Use an empty hand to open the backpack's inventory menu.
place the emag in directly by clicking an empty slot in the inventory.

**Comment by projectkepler-ru** [comment]
hilarious
