### ISSUE TITLE
You can bypass shuttle navigation restrictions using move-up move-down verb

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#83655]
## Issue Summary

Bypass shuttle nav restrictions, permitting "free" exploration of all Z-levels - while this doesn't let you dock in CentCom or Hyperspace Z-levels as they have magic shuttle warding technology from the wizard's federation, you can still see them with meson vision, so admin shenanigans be seen.
It's pretty unreliable, but it works.

i have had my fun with this issue and it may now be put to rest

## Round ID:

[229852](https://scrubby.melonmesa.com/round/229852), terry my beloved (discovered before that)

## Reproduction:

- be nukie reinforcement

"i fly"

- open nav console

- Move Upwards

- you have reached SPACE LOOT AHAHAHHAHAHAHAHHAHAHAHAHAHAHAHAHAHAHHAHA

- pray i dont find the traderoute as nukie before this is fixed inshallah

**Comment by projectkepler-ru** [comment]
oh god the jank
