### ISSUE TITLE
A Cultist With A Steak And A Dream

### ISSUE THREAD

**Issue by LSommers** [tgstation/tgstation#83665]
## Issue Summary

Due to raw meat being able to effectively dispense infinite blood, a cultist can use a single piece of meat to generate infinite blood for infinite Blood Rites charge. A whole cult can source their healing from a single slab of butchered Pun-Pun. The station can be terrorized with countless cult kamehameha beams because some dude is dragging around a goddamn filet mignon.

## Reproduction:

Step One: Be a cultist
Step Two: Blood Rites
Step Three: Pull around a piece of meat
Step Four: ?????
Step Five: PROFIT

**Comment by projectkepler-ru** [comment]
![image](https://github.com/tgstation/tgstation/assets/99981766/323bd1ed-edea-46f0-a1d0-d902ab21e9bb)

**Comment by projectkepler-ru** [comment]
![image](https://github.com/tgstation/tgstation/assets/99981766/bb717f87-8459-4f7e-abce-ef0a156af7ee)

**Comment by carlarctg** [comment]
the meat component is supposed to have a max amount of spread possible with meat chunks specifically for this reason, i dont know why it broke

**Comment by the-orange-cow** [comment]
Dimensional Rending?  I just want to grill, for Nar'Sie's sake!

**Comment by LSommers** [comment]
> the meat component is supposed to have a max amount of spread possible with meat chunks specifically for this reason, i dont know why it broke

Yeah sadly the bloody spreader thing as a whole seems a bit overzealous (**M E A T** having infinite blood spread though is 100% working as intended if you ask me though)- While I have you captive in the comments of this issue report, let me ideasman a little and suggest making cook/surgeon aprons block bloody spreader while worn so sec can more easily tell when the chef has just brutalized an assistant into a spreadable paste vs "I touched a steak".
