### ISSUE TITLE
Cyborg Integrated Omnitools Fail To Include Unique Mechanics

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#83667]
## Reproduction:

Cyborg wirecutters don't snip cuffs, as they lack the cuffsnapping element.

Cyborg cauteries can't heat up beakers. 

There are likely a number of other things taken for granted which don't work for them

This happened due to the omnitool PRs

**Comment by Jacquerel** [comment]
Cyborg omnitools will inevitably fail any check which is based on object behaviour or typepaths rather than purely on tooltype
This isn't really solveable without refactoring how the base item works to pass clicks to an internally held tool or something like that
