### ISSUE TITLE
Traitor Code Phrases bugged

### ISSUE THREAD

**Issue by Chocodaemon** [tgstation/tgstation#83671]
Reporting client version: 515.1635

## Issue Summary

Traitor Code Phrases are bugged, and always have a "blue'>" preceding the word. For example a code phrase of warehouse would show as "blue'>Warehouse" in chat. This would automatically give away any syndicate traitor which is obviously not good.

## Round ID:
[229882](https://scrubby.melonmesa.com/round/229882)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)

## Reproduction:

Have a traitor say any Code Phrase. Code Responses work as intended though, and show in red text.

**Comment by necromanceranne** [comment]
Is this for non-traitors or other traitors? Or just stated in general? I cannot replicate this on the most up-to-date code.

**Comment by Sadboysuss** [comment]
please reproduce the issue via video or provide new reproduction steps
