### ISSUE TITLE
Picking up a cane sets usable_legs to null, making you unable to stand

### ISSUE THREAD

**Issue by FlufflesTheDog** [tgstation/tgstation#83678]
## Issue Summary
Title. #83242 
https://github.com/tgstation/tgstation/blob/0cd8bf38dc4c97d58596a02e1e1a8c6e026975e2/code/game/objects/items/weaponry.dm#L522-L524

https://github.com/tgstation/tgstation/blob/0cd8bf38dc4c97d58596a02e1e1a8c6e026975e2/code/modules/mob/living/carbon/carbon_movement.dm#L20

## Round ID:
Downstream

## Reproduction:
Pick up a cane, fall over

**Comment by SyncIt21** [comment]
Duplicate #83646

**Comment by FlufflesTheDog** [comment]
Whoops
