### ISSUE TITLE
Berserker armor augmentation doesn't work

### ISSUE THREAD

**Issue by MythicJavelin** [tgstation/tgstation#83684]
## Issue Summary

The current iteration of the berserker armor/ash drake armor merge can never be done in game as the ash drake armor is always considered to "contain" the helmet, and attempting to use the drake armor on the berserker armor gives the message "The drake armor cannot be used for armoring while there's something inside!"

On further testing, if the helmet is removed via debug commands, it can be used to augment the armor.

## Round ID:

N/A, tested on a server hosted on my own PC running the latest source code publicly available as of 7am PST on Monday June 3rd 2024

## Testmerges:

Unsure, as the locally hosted server doesn't contain server revision information, see above for code sourcing.

## Reproduction:

See summary, or spawn in a set of berserker armor and drake armor.

**Comment by necromanceranne** [comment]
Ah bugger
