### ISSUE TITLE
Digging up a grave you built gives mood debuff

### ISSUE THREAD

**Issue by Rustybuckets6601** [tgstation/tgstation#83704]
Reporting client version: 515.1636

## Issue Summary
If you dig a grave with a shovel using right click on lavaland or icebox, you will make a closed grave. digging that grave open will give you the mood debuff of "i just desecrated a grave! :(" which is silly.

## Round ID:
[229944](https://scrubby.melonmesa.com/round/229944)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Borgs: the moduling (Various fixups to borg module code)](https://www.github.com/tgstation/tgstation/pull/83116)
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)
- [Incoming stamina damage while in stamcrit has diminishing returns applied](https://www.github.com/tgstation/tgstation/pull/83445)
- [Genetics Rebalance: Negative mutations add stability, standarized instability cost for mutations](https://www.github.com/tgstation/tgstation/pull/83439)
- [Cult Vs. Heretic: 7 Months Later Edition](https://www.github.com/tgstation/tgstation/pull/82877)

## Reproduction:
get shovel, right click icebox snow, left click grave to open, notice that you're now sad.

**Comment by SyncIt21** [comment]
It's not silly cause it's an intentional feature and not a bug.

**Comment by necromanceranne** [comment]
The silly part might be that it is created closed. @Rhials any thoughts?

**Comment by Rustybuckets6601** [comment]
> It's not silly cause it's an intentional feature and not a bug. 

I don't see how. If you dig a grave yourself, why would you feel like you're graverobbing for opening it up to bury someone? If you decided to bury bodies instead of throw them in the morgue, you'd get a mood debuff even though it makes no sense. 

If anything, graves you build yourself shouldn't be able to affect mood. Because if you decide to make a grave to hide something out in the icebox wastes, getting a mood debuff for digging it back up is silly.

**Comment by Rustybuckets6601** [comment]
> The silly part might be that it is created closed. @Rhials any thoughts?

That too, but I think that opening a grave you built shouldn't give the feeling of graverobbing, especially if it's empty.

**Comment by Rhials** [comment]
Ah, yeah this shouldn’t be happening for fresh graves, it makes no sense. 

Fortunately, fresh graves are their own subtype so separating the mood buff from them while keeping it on natural graves should be easy. Will fix shortly

**Comment by PawnAtWork** [comment]
Yeah. Maybe it should only give the debuff if the grave contains any form of creature.
