### ISSUE TITLE
Chemical reactions occuring with errors

### ISSUE THREAD

**Issue by DoomAngelBlade** [tgstation/tgstation#83719]
Reporting client version: 515.1636

Have no idea what or why it is happening, but some reagents either do not react fully, or there are leftovers that shouldn't be there.
Reaction chamber, after this, halts its production

This is my reaction chamber for aiuri.
It has standard recipe from wiki
1 part Ammonia
2 parts Hydrogen
1 part Sulfuric Acid
But multiplied by 5.
Also it has silicon added as PH Buffer.
PH Buffer is requested somewhere in setup to be disposed, therefore it's not an issue.

![image](https://github.com/tgstation/tgstation/assets/46872312/9d2d0d30-5c65-4e90-b6d7-6a294e46e15b)

Instead of properly reacting, there are either some leftovers from the reaction, that shouldn't be there or reaction is not completed fully, before reaction chamber freezes chemicals and starts releasing chemicals, 

## Round ID:
[229983](https://scrubby.melonmesa.com/round/229983)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Borgs: the moduling (Various fixups to borg module code)](https://www.github.com/tgstation/tgstation/pull/83116)
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)
- [Incoming stamina damage while in stamcrit has diminishing returns applied](https://www.github.com/tgstation/tgstation/pull/83445)
- [Genetics Rebalance: Negative mutations add stability, standarized instability cost for mutations](https://www.github.com/tgstation/tgstation/pull/83439)
- [Cult Vs. Heretic: 7 Months Later Edition](https://www.github.com/tgstation/tgstation/pull/82877)

## Reproduction:

no idea. Needs reproduction, unless I fucked up somewhere and im blind

**Comment by newfren** [comment]
aiuri is endothermic enough to stop (or severely slow) its own reaction, which might be contributing to your problem?

**Comment by SyncIt21** [comment]
> aiuri is endothermic enough to stop (or severely slow) its own reaction, which might be contributing to your problem?

Agreed, the optimal temp is 300k and the minimum temp is 50k. The reaction has a thermic constant of -400. From your screenshot you're temps are barely above minimum(85K).

Even when creating aiuri in an regular reaction chamber we set the temps to full(1000k) before inserting the beaker.

Try applying more aggressive heating and see if the problem persists.
