### ISSUE TITLE
Grav core makes wrong anomaly armor

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#83712]
## Issue Summary

I put grav anomaly core in core armor and got Stealth armor (which uses pyro/vortex anomaly)

## Round ID: [229802](https://scrubby.melonmesa.com/round/229802)

**Comment by PawnAtWork** [comment]
Interesting. I can't see anything in the code that'd be causing this. I'll see if I can replicate it later.

**Comment by projectkepler-ru** [comment]
Weirdly enough I couldn't replicate this and was able to get a repulsor armor just fine

**Comment by projectkepler-ru** [comment]
> Interesting. I can't see anything in the code that'd be causing this. I'll see if I can replicate it later.

It's caused by when it's given a core that there is no subtype for the armour of
So it give stealth as a compensation to ensure you atleast get something

**Comment by Livrah** [comment]
https://clips.twitch.tv/InnocentFurtiveGoblinJKanStyle--sMCCUr-4-0k1GKo
![Screenshot_3](https://github.com/tgstation/tgstation/assets/64209864/fe52ee08-5b7e-46e9-a85f-2249c25a3be2)

**Comment by projectkepler-ru** [comment]
> https://clips.twitch.tv/InnocentFurtiveGoblinJKanStyle--sMCCUr-4-0k1GKo ![Screenshot_3](https://private-user-images.githubusercontent.com/64209864/336686011-fe52ee08-5b7e-46e9-a85f-2249c25a3be2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2ODYyNTIsIm5iZiI6MTcxNzY4NTk1MiwicGF0aCI6Ii82NDIwOTg2NC8zMzY2ODYwMTEtZmU1MmVlMDgtNWI3ZS00NmU5LWE4NWYtMjI0OWMyNWEzYmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE0NTkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljYWNhMWQ2OGU2YWNkNzMyNmI3YzFjM2M2YjU1YjliMDRlMzFhMGU1NDMzZDIzMjk5MGYwZWFkMmY3Y2FhYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mUWP5YVsaIzLleB-GUwQdGXBx-czo4DDOFQ-8z1my8E)

Yeah that is fucking weird
I'll take a look at it when i have free time, there might be some typepath error somewhere
