### ISSUE TITLE
Birdshot 2 Disposals Mismapping

### ISSUE THREAD

**Issue by LSommers** [tgstation/tgstation#83714]
## Issue Summary
The New And Improved (TM) Birdshot holodeck area has some kind of disposals routing error that causes all trash and assistants to get stuck in a loop that goes around and around between the jani office and holodeck.

## Reproduction:

Toss trash and/or yourself down a disposals unit on Birdshot and be banished to the pipe realm

**Comment by EEASAS** [comment]
I'll take a look

**Comment by EEASAS** [comment]
actually it would be nice if you had a video of it happening

**Comment by Goat-Real** [comment]
I believe it's an issue with the sorting pipe in the janitor closet. The sorter is facing the wrong direction and will always send things back.
