### ISSUE TITLE
TGUI's text input is broken

### ISSUE THREAD

**Issue by SmthAwfl** [tgstation/tgstation#83722]
## Issue Summary
You can't submit anything longer than 1963 characters to the TextInputModal. It's only on tgui side cuz ui_act proc is never called

## Reproduction:
1. Open any musical instrument TGUI
2. Click on Import Song
3. Try to submit something that is more than 1963 characters long.

![reproduction](https://i.imgur.com/WfkRG4h.gif)

**Comment by GoldenAlpharex** [comment]
Which version of BYOND are you using?

**Comment by SmthAwfl** [comment]
> Because I noticed there was some issues with that text input modal when going to 515.1639. If you revert to, like, 1636, it might be working again.

Yep, I failed to replicate this on 515.1636
byond issue, lol

**Comment by SyncIt21** [comment]
Duplicate #83654

**Comment by Sealed101** [comment]
^

**Comment by Vallat** [comment]
Relevant again on version 516.1656
