### ISSUE TITLE
Activating internals causes welder gas masks to lower

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#83728]
Reporting client version: 515.1639

## Round ID:
[229999](https://scrubby.melonmesa.com/round/229999)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Borgs: the moduling (Various fixups to borg module code)](https://www.github.com/tgstation/tgstation/pull/83116)
- [Wawastation](https://www.github.com/tgstation/tgstation/pull/82298)
- [Incoming stamina damage while in stamcrit has diminishing returns applied](https://www.github.com/tgstation/tgstation/pull/83445)
- [Genetics Rebalance: Negative mutations add stability, standarized instability cost for mutations](https://www.github.com/tgstation/tgstation/pull/83439)
- [Cult Vs. Heretic: 7 Months Later Edition](https://www.github.com/tgstation/tgstation/pull/82877)

## Reproduction:
Strangely if you try to activate your internals with a welding gas mask on it'll activate both the visor and the internals rather than just the internals.

**Comment by projectkepler-ru** [comment]
looking into this
