### ISSUE TITLE
Orbit menu mouse cursor is inaccurate

### ISSUE THREAD

**Issue by Formerxboxgamer** [tgstation/tgstation#83731]
## Issue Summary

When hovering over a name in the orbit list, The bottom/center of the cursor is needed to properly select a target to orbit. This is annoying.

![4da73ce83ecce8fd8f8a4389b2207b72](https://github.com/tgstation/tgstation/assets/161751529/a88a34b0-766c-4102-af4b-e8830cd648ef)

See above image wherein my cursor is trying to select Arcticus, but the game wants me to click on "Big Brother"
## Testmerges:

[#83227: '[TM ONLY] Hijacked Revision Date for v3 TGS Api' by ZephyrTFA at commit 8575d21082](https://www.github.com/tgstation/tgstation/pull/83227)

## Reproduction:

Open the orbit menu on a live server, move your mouse off an orbit target to the next target above it.

**Comment by Wayland-Smithy** [comment]
Seems to only occur with the Alive category and/or when icons are present.
