### ISSUE TITLE
Fishing a Charred Skeleton in Lavaland causes an impasable tile

### ISSUE THREAD

**Issue by OrbisAnima** [tgstation/tgstation#83730]
## Issue Summary

Fishing in Lavaland (/datum/fish_source/lavaland) generates an impassable tile when the following effect is triggered (/obj/effect/mob_spawn/corpse/human/charredskeleton), even using admins to delete the skeleton or moving the skeleton make the area to persist. tried in different tiles and was able to repeat the steps.

## Reproduction:

Fish in Lavaland with reinforced line (and maybe magnetic tackle)
get the /obj/effect/mob_spawn/corpse/human/charredskeleton
move
try to go back to the tile you were, now you cant, nobody can.

**Comment by SmArtKar** [comment]
Cannot reproduce?

**Comment by lizardqueenlexi** [comment]
Reproduced. This bug occurs because the mob spawner remains in the turf's contents despite being deleted, and somehow this makes the tile impassable. I can't tell _why_ this is, since it does get queued for deletion.
