### ISSUE TITLE
shunting yourself on different z level APC of your core just  deletes the core 

### ISSUE THREAD

**Issue by projectkepler-ru** [tgstation/tgstation#83753]
## Issue Summary
shunting yourself on different z level APC of your core prevent you from shunting back

## Round ID:
Not Applicable/Off-Server

Was done on tram station

## Testmerges:
N/A

## Reproduction:
Be malf AI on tram
shunt to APC on lower level
cant return to core

**Comment by projectkepler-ru** [comment]
additionally this also fuck my overlay irreversibly but it might be a tram issue

**Comment by Metekillot** [comment]
No round ID?

**Comment by Metekillot** [comment]
Did you shunt yourself or did you get force-shunted?

**Comment by projectkepler-ru** [comment]
> Did you shunt yourself or did you get force-shunted?

round ID wasnt applicable as I was playing around personally with malf AI power 
I shunted into an APC on my lower sat on tram and then it deleted my core

**Comment by zxaber** [comment]
AI cores are weird and behind the scenes they're just cardboard props. The core you see is actually your own AI mob sitting on the ground.

Best guess, a runtime prevented the empty core prop being spawned on your old location. If you can get a round ID, we can check for that.

**Comment by Metekillot** [comment]
> AI cores are weird and behind the scenes they're just cardboard props. The core you see is actually your own AI mob sitting on the ground.
> 
> Best guess, a runtime prevented the empty core prop being spawned on your old location. 

Been peeking at this; I cleaned up malf code a little bit a while back and it seems like some of my reworks broke things that other hacky things were keeping from breaking.

Anyway; malf shunting has a z level check that hard returns if it isn't the station z level, but it predates multi z maps, so I'll need to address that
