### ISSUE TITLE
Emaged cyborg chemical synthesiser bug

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#83764]
Reporting client version: 515.1639

## Issue Summary
![image](https://github.com/tgstation/tgstation/assets/96586172/fc3df9de-1318-43e2-bad4-129062a75fac)

## Round ID:
[230085](https://scrubby.melonmesa.com/round/230085)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Borgs: the moduling (Various fixups to borg module code)](https://www.github.com/tgstation/tgstation/pull/83116)
- [Incoming stamina damage while in stamcrit has diminishing returns applied](https://www.github.com/tgstation/tgstation/pull/83445)
- [Genetics Rebalance: Negative mutations add stability, standarized instability cost for mutations](https://www.github.com/tgstation/tgstation/pull/83439)
- [Adds some logging to roundstart, to figure out why it's been taking longer recently](https://www.github.com/tgstation/tgstation/pull/83745)

## Reproduction:
1. have illegal modules as medborg
2. get advanced synthesiser upgrade

**Comment by projectkepler-ru** [comment]
wat?

**Comment by Sadboysuss** [comment]
> wat?

syndicate synthesiser isn't supposed to get more chems after getting advanced hypo upgrade
