### ISSUE TITLE
Photo albums not saving

### ISSUE THREAD

**Issue by Metekillot** [tgstation/tgstation#83761]
Reporting client version: 515.1639

## Issue Summary

My photos from this round didn't save.

## Round ID:
[230058](https://scrubby.melonmesa.com/round/230058)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Borgs: the moduling (Various fixups to borg module code)](https://www.github.com/tgstation/tgstation/pull/83116)
- [Incoming stamina damage while in stamcrit has diminishing returns applied](https://www.github.com/tgstation/tgstation/pull/83445)
- [Genetics Rebalance: Negative mutations add stability, standarized instability cost for mutations](https://www.github.com/tgstation/tgstation/pull/83439)
- [Adds some logging to roundstart, to figure out why it's been taking longer recently](https://www.github.com/tgstation/tgstation/pull/83745)

## Reproduction:

I put photos in my album and dropped it when a sec officer stunned me. The next round, none of my photos were in the album. This happened in a previous round. This wiped out about 12 photos.

**Comment by 00-Steven** [comment]
Is this the round ID for the round in which you dropped your album or the round after?

**Comment by Metekillot** [comment]
The round where the album was dropped
