### ISSUE TITLE
His grace has same damage as regular toolbox

### ISSUE THREAD

**Issue by davethwave** [tgstation/tgstation#83779]
## Issue Summary
His Grace takes takes about 9 hits. Technically 8.3 to take down an unarmored guy. Exactly the same as a normal one. I realize it does upgrade after a number of kills but this seems a bit low for what I remember this used to be like.

## Reproduction:
Bash someone's head in and you would have an almost equal chance to win vs that greytide that walked in with a toolbox.

**Comment by projectkepler-ru** [comment]
might be a calculation error, will try to check

**Comment by SuperNovaa41** [comment]
Intended
