### ISSUE TITLE
Borg modules broken - causing runtimes and bugged interfaces

### ISSUE THREAD

**Issue by Zergspower** [tgstation/tgstation#83773]
## Issue Summary

Various borg modules broke completely when https://github.com/tgstation/tgstation/pull/83116 was merged

3 of the service modules such as the extra beaker, service apparatus and rolling table among other things either cant be added to them or they get an icon that cant be clicked at all.

/obj/item/borg/upgrade/service_cookbook
/obj/item/borg/upgrade/rolling_table
/obj/item/borg/upgrade/service_apparatus
/obj/item/borg/upgrade/drink_app
/obj/item/borg/upgrade/circuit_app

were just the few i found
![image](https://github.com/tgstation/tgstation/assets/22140677/3a56fe98-baa1-4061-8e35-1ded9d3b97d1)

It'll both 'add' a icon to the bar that cant be clicked or used on top of also saying there's no mounting point

It looks at least on paper that their functions were completely removed and never refactored to actually work
![image](https://github.com/tgstation/tgstation/assets/22140677/f8e6a710-5dc0-4ab6-9126-93e64d788a48)

These also cause runtimes when trying as well
![image](https://github.com/tgstation/tgstation/assets/22140677/9d258d0b-6ebb-44a9-80fc-11264ffd6e56)

## Reproduction:

Select borg module
Try to add/use one of the upgrades listed above among others.

**Comment by projectkepler-ru** [comment]
fug

**Comment by Majkl-J** [comment]
Oh shit well I'll fix this. This one is on me

**Comment by Majkl-J** [comment]
![image](https://github.com/tgstation/tgstation/assets/49160555/8a4b428f-a73c-4fb1-9b92-63ab1b99e471)
![image](https://github.com/tgstation/tgstation/assets/49160555/08b5882c-5637-4847-8306-954c3eb6ae2e)

Got it, PR underway

**Comment by Zergspower** [comment]
> 
> 
> Got it, PR underway

Appreciate it! Now to apply it to our modular items and see how bad i fuck them up lol
