### ISSUE TITLE
Welding helmet/mask/goggles don't protect moth eyes from welder

### ISSUE THREAD

**Issue by Deadgebert** [tgstation/tgstation#83783]
## Issue Summary

Welding helmet doesn't protect moth eyes from welder. 
Welding helmet still protects against flash and flashbangs though.

Is this bug? It should be, it's weird to require two of welding goggles/mask/helmet

## Round ID:
[230120](https://tgstation13.download/parsed-logs/manuel/data/logs/2024/06/07/round-230120/)

## Testmerges:

https://github.com/tgstation/tgstation/pull/82877
https://github.com/tgstation/tgstation/pull/83227
https://github.com/tgstation/tgstation/pull/83445
https://github.com/tgstation/tgstation/pull/83745

## Reproduction:

> Be moth
> Equip welding helmet
> Attempt to weld
> Suffer

**Comment by Deadgebert** [comment]
probably this https://github.com/tgstation/tgstation/pull/83703

**Comment by ZephyrTFA** [comment]
this is an intended mechanic, and was broken.
Its just that the welder doesn't make you instantly blind for using it as a moth if you have eye protection below max

**Comment by Deadgebert** [comment]
wild

**Comment by necromanceranne** [comment]
you need to stack welding protection. Welding goggles AND welding mask/helmet.

**Comment by captainfrost20** [comment]
I'm only now realizing this is not a bug. What the fuck, that's genuinely terrible game design
