### ISSUE TITLE
Emagged red medbots dont seem to do anything

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#83822]
Reporting client version: 515.1640

## Round ID:
[230220](https://scrubby.melonmesa.com/round/230220)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Incoming stamina damage while in stamcrit has diminishing returns applied](https://www.github.com/tgstation/tgstation/pull/83445)
- [Cult Vs. Heretic: 7 Months Later Edition](https://www.github.com/tgstation/tgstation/pull/82877)
- [Adds some logging to roundstart, to figure out why it's been taking longer recently](https://www.github.com/tgstation/tgstation/pull/83745)

## Reproduction:
I got emagged as an advanced medbot in this round and instead of making me damage people I just...did no damage at all. Still seemed to inject people with chloral though

**Comment by ZephyrTFA** [comment]
you can only deal damage based on the amount you would have healed.

**Comment by ZephyrTFA** [comment]
you can absolutely pr having a minimum damage amount though, I'll support it

**Comment by DaydreamIQ** [comment]
> you can only deal damage based on the amount you would have healed.

Probably should've mentioned this was a fully upgraded medbot so that very much wasn't the case
