### ISSUE TITLE
Entire pharmacy in your mouth

### ISSUE THREAD

**Issue by DoomAngelBlade** [tgstation/tgstation#83820]
Reporting client version: 515.1640

## Issue Summary

You can have seemingly infinite amount of pills in your mouth!

Discovered by me and Sherman Cottle
## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Incoming stamina damage while in stamcrit has diminishing returns applied](https://www.github.com/tgstation/tgstation/pull/83445)
- [Cult Vs. Heretic: 7 Months Later Edition](https://www.github.com/tgstation/tgstation/pull/82877)
- [Adds some logging to roundstart, to figure out why it's been taking longer recently](https://www.github.com/tgstation/tgstation/pull/83745)

## Reproduction:

Drapes
Mouth
Drill
Insert pill
Repeat

![image](https://github.com/tgstation/tgstation/assets/46872312/6b249a7b-ca31-47a0-ac9c-be28d7841b8e)

Please cap it at like... 6 or 4.

**Comment by Dawnseer** [comment]
Feature. A spessman's head is made entirely of teef.

**Comment by Dman757** [comment]
Adults should have 32~ teeth according to colgate[dot]com™️®️ 
![image](https://github.com/tgstation/tgstation/assets/4275720/a37f9bcd-47a0-40e4-a557-6bbba8257246)

**Comment by DoomAngelBlade** [comment]
> Adults should have 32~ teeth 

39 on screen.

**Comment by Dawnseer** [comment]
> > Adults should have 32~ teeth
> 
> 39 pills on screen.

You forgot to take into account how many teeth moths have. Which is a lot more.

**Comment by carlarctg** [comment]
> i mean, its also unlikely you can use thin (front) teeth for implants, you're gonna be using the crushing teeth (big)

nerd
