### ISSUE TITLE
Tooth pill - wrong pop up or a bug

### ISSUE THREAD

**Issue by DoomAngelBlade** [tgstation/tgstation#83839]
## Issue Summary
When in crit and trying to pop up a pill, it says - Unconcious!
While in reality you can talk and move. Not through radio but can.
## Reproduction:
Get dental pill
Get into soft crit
Try using dental pill.

It's either a typo because you're not unconcious when in soft crit
Or a bug.
I mean, you can talk. Sure as hell you can chew on a pill/capsule when in soft crit, don't you?

**Comment by distributivgesetz** [comment]
Affected code:
https://github.com/tgstation/tgstation/blob/master/code%2Fdatums%2Factions%2Faction.dm#L193-L196

Could be fixed by using a status effect proc like `IsUnconscious()` instead of checking `stat`, because `stat` is slightly jank and has a lot of meaning

**Comment by MrMelbert** [comment]
Concious is very deliberately a stat thing, changing it to `IsUnconscious` would be changing behavior to a ton of things

**Comment by DoomAngelBlade** [comment]
Question is - what will be / should be changed?

The Pop Up Message or Ability to chew capsules when in soft crit?

**Comment by MrMelbert** [comment]
Either 
- change the message 
or 
- go to the tooth pill action datum and remove the check flag, then add a snowflake `IsAvailable` for `stat <= SOFT_CRIT`

**Comment by LucyGrind** [comment]
I think we should allow soft crit pill popping, can i implement this for my first issue?

**Comment by distributivgesetz** [comment]
> can i implement this for my first issue

no one will ever stopping you from contributing

**Comment by LucyGrind** [comment]
> Affected code: https://github.com/tgstation/tgstation/blob/master/code%2Fdatums%2Factions%2Faction.dm#L193-L196
> 
> Could be fixed by using a status effect proc like `IsUnconscious()` instead of checking `stat`, because checking `stat` is slightly jank because it has a different meaning

are we sure about this? looks like code\modules\surgery\dental_implant.dm has something to do with it but i genuinely don't know, MrMelbert *looks* right though.

**Comment by LucyGrind** [comment]
ok boys i just got rid of the /hands_free/ part of the proc, and all the places its mentioned, and added a flag to the
/datum/action/item_action/activate_pill
	name = "Activate Pill"
	check_flags = NONE
and you can now crit pill. i think hard crit pilling is funny so we should allow that to be a thing too :) how do i like, request to merge this or test merge or however that works?

**Comment by carlarctg** [comment]
> ok boys i just got rid of the /hands_free/ part of the proc, and all the places its mentioned, and added a flag to the
> /datum/action/item_action/activate_pill
> name = "Activate Pill"
> check_flags = NONE
> and you can now crit pill. i think hard crit pilling is funny so we should allow that to be a thing too :) how do i like, request to merge this or test merge or however that works?
join the TGstation discord and ask us contributors and coders there, git comments aren't a very good place for it

**Comment by LucyGrind** [comment]
> > ok boys i just got rid of the /hands_free/ part of the proc, and all the places its mentioned, and added a flag to the
> > /datum/action/item_action/activate_pill
> > name = "Activate Pill"
> > check_flags = NONE
> > and you can now crit pill. i think hard crit pilling is funny so we should allow that to be a thing too :) how do i like, request to merge this or test merge or however that works?
> 
> join the TGstation discord and ask us contributors and coders there, git comments aren't a very good place for it

https://github.com/tgstation/tgstation/pull/83895

already did it
