### ISSUE TITLE
Items inside crates of holodock simulations do not vanish when changing simulation

### ISSUE THREAD

**Issue by Goat-Real** [tgstation/tgstation#83834]
## Issue Summary

Items inside of crate spawned by the  holodock, Emergency Medical in this case, do not disappear if you open the crate then change the simulation. Infinite blood and white uniforms are obtainable this way.
![image](https://github.com/tgstation/tgstation/assets/126099705/ab65b0b0-5f02-43fd-bcb3-8cace44db481)

## Round ID:
[230235](https://scrubby.melonmesa.com/round/230235)

## Reproduction:

Load the Emergency Medical simulation, open the blood and jumpsuit containers, then change simulation.

**Comment by Metekillot** [comment]
marking this

**Comment by Goat-Real** [comment]
Adding other types of containers to a holodock map.
![image](https://github.com/tgstation/tgstation/assets/126099705/3701e797-e430-4a46-ab05-152fb9361481)
![image](https://github.com/tgstation/tgstation/assets/126099705/4ed0fa6e-ca34-4be0-8d8e-65cb1bf82683)
Any sort of container part of a holodeck simulation makes it so the items inside of the container are now 'real' items.
