### ISSUE TITLE
Light tubes show up as broken when placing in floodlights

### ISSUE THREAD

**Issue by Rustybuckets6601** [tgstation/tgstation#83853]
Reporting client version: 515.1636

## Issue Summary
see above

## Round ID:
[230289](https://scrubby.melonmesa.com/round/230289)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Incoming stamina damage while in stamcrit has diminishing returns applied](https://www.github.com/tgstation/tgstation/pull/83445)
- [Cult Vs. Heretic: 7 Months Later Edition](https://www.github.com/tgstation/tgstation/pull/82877)
- [Adds some logging to roundstart, to figure out why it's been taking longer recently](https://www.github.com/tgstation/tgstation/pull/83745)

## Reproduction:
get light tube, from a an area with no power, try to place in floodlight, fail

**Comment by Likteer** [comment]
Did you place in cables first & screwed them in?

There is only 1 balloon alert and it incorrectly shows up for any issue.

**Comment by Rustybuckets6601** [comment]
Pretty sure I did, I remember also spawning in some a while back on a
localhost that were already completed minus the light tube. I very well
could've forgotten the cables, but in that case i guess the bug would be
that you get a popup saying it's broken when the issue is that you missed a
step
