### ISSUE TITLE
Miners on fire will burn their tools to ash even if they're wearing fireproof armor

### ISSUE THREAD

**Issue by Skebulba** [tgstation/tgstation#83851]
## Issue Summary
After #83616 was merged, items held in hand while on fire will also catch fire. This applies to Proto-kinetic crushers and accelerators, the two main methods of dealing damage to mobs available to miners. This is in spite of the fact that there are multiple sets of fireproof armor that miners can obtain, meaning that using said armors for their intended purpose comes with a high chance that your weaponry will burn away mid-fight (as well as all of the trophies you've painstakingly gathered in the case of crushers). I doubt that this is intended behavior, since what would the point of fireproof armor be if your primary tool gets destroyed anyway?

## Reproduction:
1. Wear any fireproof set of armor (Ash drake, H.E.C.K. suit, Godslayer, etc.)
2. Hold your trusty PKA/Crusher in hand.
3. Set yourself on fire.
4. Wait for it to crumble to ash between your fingers (may be nearly instant or take up to around a minute to happen).

**Comment by Iamgoofball** [comment]
PKAs and Crushers should probably have fire armor.

**Comment by GPeckman** [comment]
It's worth noting that, unlike burning clothes, you can't put held items out by resisting. Since, you know, you drop everything you're holding when you drop and roll.

**Comment by moocowswag** [comment]
>However, I cannot actually make the PKA ignite with just a bonfire, so I suspect that lava was involved in the relevant round.

Did you try holding the pka in your hand and walking into the bonfire with fireproof clothing? Maybe there is a unique bug there to begin with thats bypassing it.

**Comment by GPeckman** [comment]
I was in fact wearing the Captain's carapace and gloves, which are fireproof.

**Comment by GPeckman** [comment]
#83616 just got reverted by Oranges, so I think this is fixed.

**Comment by Jacquerel** [comment]
It should be fireproof anyway probably.
