### ISSUE TITLE
Broken interactions (screwdriver on modsuit, RPED picking up items)

### ISSUE THREAD

**Issue by Inari-Whitebear** [tgstation/tgstation#83876]
## Issue Summary

Some stuff doesn't work. What I noticed:
* Screwdrivering a modsuit will just have it go "no room" as it tries to stick the screwdriver into the modsuit instead of opening the cell slot, couldn't get it to work
* RPED wouldn't bulk pick up printed stock parts, had to manually stick each one into it

Maybe related to afterattack changes?
Fairly sure RPED worked a day or two ago at least.

## Testmerges:

[#83227: '[TM ONLY] Hijacked Revision Date for v3 TGS Api' by ZephyrTFA at commit 8575d21082](https://www.github.com/tgstation/tgstation/pull/83227)
[#83556: 'Significantly increases stamina recovery on most effects that provide it' by Metekillot at commit f409fd19e1](https://www.github.com/tgstation/tgstation/pull/83556)
[#83789: 'tgui: adds tgui npm library' by jlsnow301 at commit bf5fc260a4](https://www.github.com/tgstation/tgstation/pull/83789)
[#83818: 'Afterattack is dead, long live Afterattack' by MrMelbert at commit 4614454b48](https://www.github.com/tgstation/tgstation/pull/83818)

**Comment by SyncIt21** [comment]
Report these bugs on the test merge PR #83818. Don't create new issues while that PR is open

**Comment by Inari-Whitebear** [comment]
Well I can't be positive it's from that, but sure
