### ISSUE TITLE
Unable to deconstruct with plumbing constructor

### ISSUE THREAD

**Issue by DoomAngelBlade** [tgstation/tgstation#83877]
Reporting client version: 515.1640
## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Significantly increases stamina recovery on most effects that provide it](https://www.github.com/tgstation/tgstation/pull/83556)
- [tgui: adds tgui npm library](https://www.github.com/tgstation/tgstation/pull/83789)
- [Afterattack is dead, long live Afterattack](https://www.github.com/tgstation/tgstation/pull/83818)

## Reproduction:
Construct something with plumbing constructor via left mouse button
Try decronstructing it with plumbing constructor via left mouse button.

**Comment by Higgin** [comment]
Possibly intended by #83629 - @Time-Green ?

**Comment by SyncIt21** [comment]
Unrelated to my PR. Just tested locally & it works fine so it's definitely a teste merge bug
