### ISSUE TITLE
Catwalks eat rods

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#83875]
Reporting client version: 515.1640

## Issue Summary
If you mess up and have to wirecut a catwalk, you won't be refunded the 2 iron rods you used to make it, which Can be bad when on limited resources.

## Round ID:
[230350](https://scrubby.melonmesa.com/round/230350)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Significantly increases stamina recovery on most effects that provide it](https://www.github.com/tgstation/tgstation/pull/83556)
- [tgui: adds tgui npm library](https://www.github.com/tgstation/tgstation/pull/83789)
- [Afterattack is dead, long live Afterattack](https://www.github.com/tgstation/tgstation/pull/83818)

## Reproduction:
Put down a rod to make a lattice, get a rod back when cutting it ✔
Put down 2 rods to make a catwalk, get No rods when cutting it ❌

**Comment by Sadboysuss** [comment]
reproduced on master
