### ISSUE TITLE
Wawastation engineering foyer doesn't allow paramedics to tide

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#83889]
Reporting client version: 515.1639

## Issue Summary
I think it's supposed to be construction access?

## Round ID:
[230385](https://scrubby.melonmesa.com/round/230385)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Significantly increases stamina recovery on most effects that provide it](https://www.github.com/tgstation/tgstation/pull/83556)
- [tgui: adds tgui npm library](https://www.github.com/tgstation/tgstation/pull/83789)
- [Afterattack is dead, long live Afterattack](https://www.github.com/tgstation/tgstation/pull/83818)

## Reproduction:
Try using paramedic ID on engineering foyer access

**Comment by mc-oofert** [comment]
paramedics shouldnt have free access to every protolathe anyway

**Comment by Sadboysuss** [comment]
> paramedics shouldnt have free access to every protolathe anyway

they have access to the protolathe but not to the foyer lol

**Comment by mc-oofert** [comment]
the engineering breakroom is called the foyer

**Comment by Dawnseer** [comment]
Perhaps, paramedics should only receive access the same way janitors get to.
