### ISSUE TITLE
Trying to scan items with storage using a forensic scanner will just open the inventory

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#83885]
Reporting client version: 515.1639

## Issue Summary
See title

## Round ID:
230380

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Significantly increases stamina recovery on most effects that provide it](https://www.github.com/tgstation/tgstation/pull/83556)
- [tgui: adds tgui npm library](https://www.github.com/tgstation/tgstation/pull/83789)
- [Afterattack is dead, long live Afterattack](https://www.github.com/tgstation/tgstation/pull/83818)

## Reproduction:
1. Try scanning a toolbox using a forensic scanner

**Comment by MrMelbert** [comment]
Using combat mode will stop that

**Comment by Sadboysuss** [comment]
> Using combat mode will stop that

alright

**Comment by MrMelbert** [comment]
![image](https://github.com/tgstation/tgstation/assets/51863163/fca5e06d-c2c8-4e4f-8792-0251989796da)

**Comment by Sadboysuss** [comment]
> ![image](https://private-user-images.githubusercontent.com/51863163/338740709-fca5e06d-c2c8-4e4f-8792-0251989796da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMzkwMzIsIm5iZiI6MTcxODEzODczMiwicGF0aCI6Ii81MTg2MzE2My8zMzg3NDA3MDktZmNhNWUwNmQtYzJjOC00ZTRmLTg3OTItMDI1MTk4OTc5NmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDIwNDUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5Nzc2YTcxZTVkMGI0OGFmNjc4YmQ1ZjVmYTQ2MmVhOGRhZDkyYzMzODNjNGVhNGRhMzFiZTI4MDAyYWNiMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k92e_Rb-TtbpqInwIio-oa3x4r2IGvdA_EqXF9_cZWY)

yep
