### ISSUE TITLE
Some alt-clicks are not usable while prone

### ISSUE THREAD

**Issue by Deadgebert** [tgstation/tgstation#83896]
## Issue Summary

You are no longer able to alt+click fire extinguisher to empty it while crawling
You are no longer able to alt+click modsuit backpack while crawling to open inventory (this can be bypassed by just clicking though)
I can't think of any more alt+clicks atm, but i'm sure it applies to a few more things

## Round ID:

[230229](https://tgstation13.download/parsed-logs/manuel/data/logs/2024/06/09/round-230229/)

## Testmerges:

https://github.com/tgstation/tgstation/pull/82877
https://github.com/tgstation/tgstation/pull/83227
https://github.com/tgstation/tgstation/pull/83445
https://github.com/tgstation/tgstation/pull/83745

## Reproduction:

> grab fire extinguisher
> get knocked down by security
> frantically try to empty fire extinguisher while on the floor
> fail and die

**Comment by jlsnow301** [comment]
when you find more please just make an issue report or comment here.
