### ISSUE TITLE
Megafauna aren't dropping crusher trophies

### ISSUE THREAD

**Issue by LePiromano** [tgstation/tgstation#83906]
## Issue Summary

megafauna which usually have a 100% guarantee to drop a crusher trophy when killed with the crusher, are not dropping their trophy

## Round ID:
[230423](https://scrubby.melonmesa.com/round/230423)

## Reproduction:
kill a megafauna with the crusher and presence the lack of crusher trophies

**Comment by LePiromano** [comment]
not fixed

**Comment by MrMelbert** [comment]
damn
