### ISSUE TITLE
Metal h2 bolts piercing strangness

### ISSUE THREAD

**Issue by D4C-420** [tgstation/tgstation#83901]
## Issue Summary

Tossing these together cause its likely due to however the piercing works on the metal h2 bolts

When fired at a target metal h2 bolts will hit them, then hit whoever is on the other side of that window bypassing the solid object completely. Note that it normally will be stopped by the window if it does not hit anything prior. 

Also when using a crow barred cross bow when the bow misfires it will hit you then continue flying straight upwards hitting whoever is in its path 

## Reproduction:

For bypassing the window

1. get a metal h2 bolt and rebar crossbow
2. get 2 monkeys
3. get a window 
4. place monkies on opposite sides of the window
5.  fire bolt into monkey on one side and watch in amazement as it hits the other bypassing the window completely. 

-----

for the misfire oddity 
1. get a metal h2 bolt and rebar crossbow
2. crowbar it so it can misfire
3. misfire and watch as the bolt flies upwards hitting whoever is north of you

**Comment by Goat-Real** [comment]
I can confirm both occur. Tested on master. Another thing I discovered while testing this is that point blank shots will shoot another projectile north with metal hydrogen bolts. All of these bugs relate only to the metal hydrogen bolts and no other types of ammo.
