### ISSUE TITLE
Cannot unscrew modsuit panel with screwdriver

### ISSUE THREAD

**Issue by Deadgebert** [tgstation/tgstation#83902]
## Issue Summary

You cannot unscrew modsuit panel with screwdriver. I tried using left click, right click, alt left and right click, ctrl, etc.
Also tested when it was on my back, in hand, and on floor, still same results.
I was able to open it with left click while in combat mode though, so maybe it's not a bug?

## Round ID:

[230406](https://tgstation13.download/parsed-logs/manuel/data/logs/2024/06/12/round-230406/)

## Testmerges:
https://github.com/tgstation/tgstation/pull/83784
https://github.com/tgstation/tgstation/pull/83690
https://github.com/tgstation/tgstation/pull/83227

## Reproduction:

> get energy shield module from spy you murder
> try to put it into atmos hard suit
> spend 3 minutes fumbling around trying to open modsuit panel with screwdriver

**Comment by MrMelbert** [comment]
it requires combat mode now, that's correct. maybe revisited though
