### ISSUE TITLE
Jumpskirts are not previewed on character creation

### ISSUE THREAD

**Issue by sylvia-from-fulp-station** [tgstation/tgstation#83908]
## Issue Summary
Jumpskirts are not previewed on character creation

![dTJb5KVm0D](https://github.com/tgstation/tgstation/assets/157846764/97246335-6dee-4880-b152-62e4084b6145)

## Round ID:

noticed 230425 but its ui

## Reproduction:

Pick a skirt on character creation

**Comment by MrMelbert** [comment]
This is just for assistants because they're set up to only equip a consistent outfit (which doesn't take into account jumpskirts)
