### ISSUE TITLE
Ctrl+Shift+Click Admin quickspawning from ghost does not work

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#83905]
Reporting client version: 515.1635

## Issue Summary

Almost certainly a testmerge issue. Probably https://www.github.com/tgstation/tgstation/pull/83784.

## Round ID:
230414

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Mouse drag & drop refactored attack chain](https://www.github.com/tgstation/tgstation/pull/83690)
- [Ctrl click refactor](https://www.github.com/tgstation/tgstation/pull/83784)

## Reproduction:

Step 1: Be an admin
Step 2: Try to quick spawn a ghost into the round.

It will not work.

**Comment by Watermelon914** [comment]
Caused by #83784
