### ISSUE TITLE
Trying to place spray bottles on tables instead spray the bottle

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#83918]
Reporting client version: 515.1639

## Issue Summary
See title

## Round ID:
[230432](https://scrubby.melonmesa.com/round/230432)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Mouse drag & drop refactored attack chain](https://www.github.com/tgstation/tgstation/pull/83690)
- [Ctrl click refactor](https://www.github.com/tgstation/tgstation/pull/83784)

## Reproduction:
Try placing spray bottle on a table

**Comment by MrMelbert** [comment]
Moving tables to the new interaction chain would fix this natively but then break being able to deconstruct them with rmb. argh
