### ISSUE TITLE
Sleeper Module for Odysseus is Kidnapper Module

### ISSUE THREAD

**Issue by d9mz** [tgstation/tgstation#83938]
## Issue Summary

When using the Sleeper Module for the Odysseus, there is no way to eject the patient that is currently inside of it.

## Round ID:

[230462](https://scrubby.melonmesa.com/round/230462)

## Testmerges:

[#83227: '[TM ONLY] Hijacked Revision Date for v3 TGS Api' by ZephyrTFA at commit 8575d21082](https://www.github.com/tgstation/tgstation/pull/83227)
[#83690: 'Mouse drag & drop refactored attack chain' by SyncIt21 at commit c266cabd48](https://www.github.com/tgstation/tgstation/pull/83690)
[#83784: 'Ctrl click refactor' by SyncIt21 at commit 5e3a028bc9](https://www.github.com/tgstation/tgstation/pull/83784)
## Reproduction:

Pick up a body with the sleeper module, you cannot eject the patient. You can click View Stats but even with Safety Off you cannot eject the patient that is currently in the module.

![image](https://github.com/tgstation/tgstation/assets/101074954/45c38868-47a5-4abb-be8f-2e6666aa18d2)

**Comment by CCC23** [comment]
intentional feature :3
