### ISSUE TITLE
Permanent Mood Debuff After Surgery

### ISSUE THREAD

**Issue by TagGamerGang22** [tgstation/tgstation#83932]
Reporting client version: 515.1637
## Issue Summary
Got stuck with the recently added mood debuff for having surgery while you're awake seemingly permanently. Had a tongue replacement surgery ~20 minutes into the shift to use a xeno tongue I found in maints and kept the mood debuff until at least until ~1 hour and 10 minutes when I killed myself.

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Mouse drag & drop refactored attack chain](https://www.github.com/tgstation/tgstation/pull/83690)
- [Ctrl click refactor](https://www.github.com/tgstation/tgstation/pull/83784)

## Reproduction:
1. Have surgery on a stasis bed while awake
2. Suffer

**Comment by Profakos** [comment]
It looks like a lot of surgery steps apply the base permanent mood event instead of the success and fail subtypes that supposed to time out after a few minutes, like the generic incise step.

**Comment by GPeckman** [comment]
This should be fixed by #83826 if I'm not mistaken.

**Comment by GPeckman** [comment]
Ah heck, looks like there are a few more.
