### ISSUE TITLE
hiero club doesn't allow you to dash past 1 tile

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#83945]
Reporting client version: 515.1633

## Round ID:
[230482](https://scrubby.melonmesa.com/round/230482)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)

## Reproduction:
cant dash anywhere but the tiles next to you, didnt see any related runtimes

**Comment by MrMelbert** [comment]
#83907 #83910
