### ISSUE TITLE
toggle nuke verb lists every object in the game

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#83946]
Reporting client version: 515.1633

## Round ID:
[230482](https://scrubby.melonmesa.com/round/230482)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)

**Comment by ZephyrTFA** [comment]
lol

**Comment by Dorsisdwarf** [comment]
Just noticed that actually this is a dupe of #82766, which is formatted nicer
