### ISSUE TITLE
Crayon't Fit

### ISSUE THREAD

**Issue by LSommers** [tgstation/tgstation#83948]
Reporting client version: 515.1637

## Issue Summary

The Clown's PDA crayon, once removed, cannot be put back in. This is due to _**all**_ crayons not fitting in PDAs anymore.

## Round ID:
[230483](https://scrubby.melonmesa.com/round/230483)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Mouse drag & drop refactored attack chain](https://www.github.com/tgstation/tgstation/pull/83690)
- [Ctrl click refactor](https://www.github.com/tgstation/tgstation/pull/83784)

## Reproduction:

Remove pen/crayon/whatever from PDA. Attempt to insert crayon. Leave wax smushed against your PDA's pen port as you fail to do so. Void your PDA's warranty. Cry.

**Comment by LucyGrind** [comment]
https://github.com/tgstation/tgstation/pull/83951

fixed it :D
