### ISSUE TITLE
cant crush cigarette in a mortar

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#83947]
Reporting client version: 515.1633

## Round ID:
[230482](https://scrubby.melonmesa.com/round/230482)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)

## Reproduction:
But you can grind them in a grinder to get nicotine.

**Comment by DATA-xPUNGED** [comment]
Can you be more specific? What happens in hte process which doesn't let you crush it? You can't put it in the mortar or what?

**Comment by Striders13** [comment]
> Can you be more specific? What happens in hte process which doesn't let you crush it? You can't put it in the mortar or what?

can't put it in. The message you get when trying to put it in is 'The mortar is empty!'

**Comment by DATA-xPUNGED** [comment]
> > Can you be more specific? What happens in hte process which doesn't let you crush it? You can't put it in the mortar or what?
> 
> can't put it in. The message you get when trying to put it in is 'The mortar is empty!'

It's probably trying to put the mortar's reagent in the cigarrete, then, thanks for the info

**Comment by LucyGrind** [comment]
ooh as someone who likes to fuck with ghetto chem, and nearly constantly grinds up cigarettes when i get the chance cuz i find it funny, this is a bug i'd like to fix

**Comment by LucyGrind** [comment]
also lets be real, its attackby again

**Comment by LucyGrind** [comment]
fixed, it was relating to
/obj/item/clothing/mask/cigarette/interact_with_atom(atom/interacting_with, mob/living/user, list/modifiers)
added a check for mortar right before the message you got popped, and it worked. You can still dip cigs in filled mortars if i did this correctly ^^
