### ISSUE TITLE
Cannot drag click anything

### ISSUE THREAD

**Issue by wshuwshuwshi** [tgstation/tgstation#83967]
Reporting client version: 515.1640

## Issue Summary

Drag clicking is inaccessable. meaning that you cannot buckle yourself or anyone else. Likewise you cannot enter bitrunner pods or put other people into cryopods

## Round ID:
[230494](https://scrubby.melonmesa.com/round/230494)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)

## Reproduction:

Cannot drag click anything. No buckling into chairs, no bitrunning, etc.

**Comment by Deadgebert** [comment]
It looks like you cannot click drag yourself. I can drag other carbons to chairs and beds
I cannot click drag from me to something or something to me
this includes buckling to self chairs/beds, climbing tables, fireman carry, checking gear of player as ghost

**Comment by GPeckman** [comment]
You also cannot enter a mech (you can put an MMI/posibrain into one though)

**Comment by LSommers** [comment]
Yeah clickdrag is currently **_VERY_** broken. How did this not get caught during the 22 testmerge rounds?

**Comment by SyncIt21** [comment]
I'm on it

**Comment by MrMelbert** [comment]
> Yeah clickdrag is currently **_VERY_** broken. How did this not get caught during the 22 testmerge rounds?

Honestly no idea
