### ISSUE TITLE
Can't buckle to shuttle seats/maybe other chairs too?

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#83981]
Reporting client version: 515.1639

## Issue Summary
![image](https://github.com/tgstation/tgstation/assets/96586172/77564248-8b7e-4478-8957-e180320bd8b4)

## Round ID:
[230523](https://scrubby.melonmesa.com/round/230523)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Flatpacker](https://www.github.com/tgstation/tgstation/pull/83836)

## Reproduction:
Click drag your sprite to a shuttle seat

**Comment by Inari-Whitebear** [comment]
Had the same issue in that round
We were both spies maybe? No idea

**Comment by GPeckman** [comment]
Can't reproduce this on a local branch that was just synced to master

**Comment by Sadboysuss** [comment]
> Can't reproduce this on a local branch that was just synced to master



> Can't reproduce this on a local branch that was just synced to master

maybe manuel wasn't synced up then idk

**Comment by AdipemDragon** [comment]
it was an issue with the TM, manuel has since synced
