### ISSUE TITLE
Can't steal modsuit as spy

### ISSUE THREAD

**Issue by Inari-Whitebear** [tgstation/tgstation#83982]
## Issue Summary

Had the CMO modsuit as an objective but couldn't seem to make it work to steal it with the PDA.

## Testmerges:

The following pull requests are currently test merged:
[#83227: '[TM ONLY] Hijacked Revision Date for v3 TGS Api' by ZephyrTFA at commit 8575d21082](https://www.github.com/tgstation/tgstation/pull/83227)
[#83836: 'Flatpacker' by mc-oofert at commit 140a2bf75d](https://www.github.com/tgstation/tgstation/pull/83836)

## Reproduction:

1. Be spy
2. Have to steal CMO modsuit (or maybe any modsuit)
3. Get MODsuit
4. Try to PDA teleport it, can't make it work

**Comment by iprice** [comment]
Was raised (twice) as an issue in round 230710.  Suggested player tried combat mode clicking, however according to them no combination of combat/non combat, in hand / on floor, right click/left click, alt/ctl/no modifiers would work, only inserting the PDA into the modsuit.

Ultimately the bounty expired and neither me nor the player could come up with any idea that worked ; even if there is a combination missed it seems to need to be more evident, or it's just broken.

**Comment by Inari-Whitebear** [comment]
Yeah, I tried with and without combat mode and stuff since I knew screwdriver needs it to open the modsuit. But also wasn't able to make it work
