### ISSUE TITLE
Click-dragging literally any turf causes a stacktrace

### ISSUE THREAD

**Issue by GPeckman** [tgstation/tgstation#83985]
## Issue Summary

As the title says. This is caused by this particular line of code: https://github.com/tgstation/tgstation/blob/cebfb28b53b9f45234b35e6262ab48652d252151/code/_onclick/drag_drop.dm#L50

This line of code is in an atom-level proc, but `can_perform_action` requires an `atom/movable` as an arguments, and turfs aren't movables.

## Reproduction:

Spawn in. Click-drag literally any turf onto something else. Instant stacktrace.

**Comment by jlsnow301** [comment]
@SyncIt21
