### ISSUE TITLE
Can't remove a Bioscrambler without an anomaly neutralizer

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#83994]
Reporting client version: 515.1640

## Issue Summary
Trying to scan the anomaly with an air scanner just makes you scan the tile it's on, wether it's on a floor or in a wall. Without being able to scan it, you can't send the signal to neutralize it, not without waiting for the neutralizers to be researched and printed and such

## Round ID:
[230529](https://scrubby.melonmesa.com/round/230529)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Flatpacker](https://www.github.com/tgstation/tgstation/pull/83836)

## Reproduction:
Get an air analyzer and signaler to get rid of an anomaly oldstyle
Scan the anomaly
Get atmos readings
Cry, get mutated in the process

**Comment by LucyGrind** [comment]
common attack_by problem L

fix by using analyzer_act instead of attack_by in 

/obj/effect/anomaly/attackby(obj/item/weapon, mob/user, params)
    if(weapon.tool_behaviour == TOOL_ANALYZER && aSignal)
        to_chat(user, span_notice("Analyzing... [src]'s unstable field is fluctuating along frequency [format_frequency(aSignal.frequency)], code [aSignal.code]."))
        return TRUE

    return ..()
    
don't nobody snipe this from me though, i'll fix it :3
