### ISSUE TITLE
*gaspshock emote doesn't play a sound

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#84013]
Reporting client version: 515.1639

## Issue Summary
Previously played a sound.

## Round ID:
[230580](https://scrubby.melonmesa.com/round/230580)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Fixes free chemsplosion reagent purging by replacing it with the same thing but dangerous](https://www.github.com/tgstation/tgstation/pull/83195)

## Reproduction:
type *gaspshock as a human subtype

**Comment by MrMelbert** [comment]
Early return fail
https://github.com/tgstation/tgstation/blob/bce2c0f181a2dba71c681a6292992a7cda6c5a2c/code/modules/mob/living/emote.dm#L179-L180
