### ISSUE TITLE
H.A.R.S. Deletes your skillchips

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#84010]
Reporting client version: 515.1639

## Issue Summary
I was an engineer and my skillchip's function was non-existant after experiencing H.A.R.S.

## Round ID:
[230580](https://scrubby.melonmesa.com/round/230580)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Fixes free chemsplosion reagent purging by replacing it with the same thing but dangerous](https://www.github.com/tgstation/tgstation/pull/83195)

**Comment by Fikou** [comment]
my man it deletes your head

**Comment by AdipemDragon** [comment]
yeah, but the brain Goes In The Chest, and the brain is where the skillchips Are, no?

**Comment by Sadboysuss** [comment]
> yeah, but the brain Goes In The Chest, and the brain is where the skillchips Are, no?

Yes, if you had no brain you would die, and the skillchip is in the brain

**Comment by san7890** [comment]
the obvious solution is to have skillchips live on the brain organ (only slightly joking)
