### ISSUE TITLE
Getting hit while doing a [Me] emote can interrupt it and speak your actions outloud

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#84018]
Reporting client version: 515.1639

## Round ID:
[230580](https://scrubby.melonmesa.com/round/230580)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Fixes free chemsplosion reagent purging by replacing it with the same thing but dangerous](https://www.github.com/tgstation/tgstation/pull/83195)

## Reproduction:
1. Press the "m" key to start typing a [Me] emote
2. Get hit while typing me emote
3. John Doe exclaims, "dances to the so- GACK!"

**Comment by jlsnow301** [comment]
It was designed this way intentionally because it's considered an IC action. Technically not a bug, but I'm open to this not spilling their say contents if it's replaced with something stylistically fitting for interrupting someone as they're doing something

**Comment by Goat-Real** [comment]
https://github.com/tgstation/tgstation/blob/8618351b692959fdf476e3d5efc251f66853bcaa/code/modules/tgui_input/say_modal/speech.dm#L12-L14
This check is supposed to turn any forced speech from OOC or Me into just the hurt phrase without the any other part. However, it doesn't work and I cannot figure out why.
