### ISSUE TITLE
Putting a rag on a table cleans the table instead.

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#84025]
Reporting client version: 515.1639

## Round ID:
[230590](https://scrubby.melonmesa.com/round/230590)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Fixes free chemsplosion reagent purging by replacing it with the same thing but dangerous](https://www.github.com/tgstation/tgstation/pull/83195)

## Reproduction:
1. Place rag on table

**Comment by MrMelbert** [comment]
Consequence of the way cleaner component is setup, in reality we probably want to do the same thing that soap does to allow cleaning storage items, IE, go on the table if on combat mode. 

Probably fine to snowflake

**Comment by 00-Steven** [comment]
On current table logic, you can right click to place the items that have left click overrides.
