### ISSUE TITLE
can't scoop up mobs that have a strip menu

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#84023]
Reporting client version: 515.1630

## Round ID:
[230588](https://scrubby.melonmesa.com/round/230588)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)

## Reproduction:
try to scoop up ian, just open the strip menu and be unable to pick up that dog

**Comment by Striders13** [comment]
oh yeah its not just carbon mobs its every mob that has a strip menu (ian)

**Comment by Sadboysuss** [comment]
> oh yeah its not just carbon mobs its every mob that has a strip menu (ian)

Ian is a basic mob and you should be able to pick him up with an aggressive grab? also did you try other stances?

**Comment by Striders13** [comment]
tried everything no luck. It should work from passive grab with no combat mode anyway
