### ISSUE TITLE
Change Floor UI button is buggy

### ISSUE THREAD

**Issue by GPeckman** [tgstation/tgstation#84029]
Reporting client version: 515.1637

## Issue Summary

The "change floor" UI button that shows up for ghosts (and living carbons too IIRC) has some issues. First of all, although it's coded to make you move downwards on right click and upwards on left click, you can't actually right click it. It just brings up a list of everything on the tile instead. Second of all, the screentip that's supposed to tell you about the left/right click behavior doesn't actually appear.

## Round ID:
[230599](https://scrubby.melonmesa.com/round/230599)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)

## Reproduction:

Start a round, observe as a ghost, and mouseover/try to right click the floor change button.

**Comment by Jewelry-x** [comment]
The button was changed recently (not sure how recently) so it is two separate buttons so this is an non-issue.
