### ISSUE TITLE
Flatpacker issues (no screwdriver upgrading, doesn't flatpack higher tier parts)

### ISSUE THREAD

**Issue by bob-b-b** [tgstation/tgstation#84030]
## Issue Summary

Flatpacker can't be upgraded via non bluespace rped unlike most machines that are heavily impacted by part quality. It just consumes the screwdriver.

It also does not flatpack machines with higher tier parts, even if it has been upgraded with higher tier parts and the examine description says it can flatpack up to 2/3/4 tier.

## Round ID:

Round ID: [230596](https://scrubby.melonmesa.com/round/230596)
Server Time: 2024-06-15 21:11:46
Round Time: 01:11:34
Station Time: 08:26:40
Time Dilation: 12% AVG:(22%, 23%, 15%)

## Reproduction:

1. Build machine, try to open maintenance panel via screwdriver, screwdriver consumed.

2. Upgrade flatpacker with higher tier parts, input a machine board, flatpack, output is a machine with base tier parts.

**Comment by Goat-Real** [comment]
flatpacker is always supposed to use the lowest tier parts, it will only make the machines with higher tier parts if that machine has those parts as its base tier such as things like DNA vault or BSA. upgrading the parts is to make the machine more efficient cost wise.

**Comment by mc-oofert** [comment]
flatpack tier means what tier stock parts is it capable of printing, wherein the BSA requires t4 parts so it needs a flatpack of tier 4
intentional even, flatpacker is supposed to always pack the bare minimum

**Comment by SyncIt21** [comment]
So you can now open the panel with a screwdriver to allow for upgrading. And since the other part is intentional it's no longer a bug.

@Dorsisdwarf requesting this gets closed or a clean up flag get's added to it.

**Comment by Dorsisdwarf** [comment]
I am very timely.
