### ISSUE TITLE
MODsuits use the space suit cell tooltip

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#84039]
Reporting client version: 515.1639

## Issue Summary
![image](https://github.com/tgstation/tgstation/assets/96586172/99104fe3-072e-4a47-ae28-aa453f052ff8)

## Round ID:
[230642](https://scrubby.melonmesa.com/round/230642)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Fixes free chemsplosion reagent purging by replacing it with the same thing but dangerous](https://www.github.com/tgstation/tgstation/pull/83195)

## Reproduction:
Wear a MODsuit until it reaches low battery

**Comment by MrMelbert** [comment]
#81985
