### ISSUE TITLE
Mansus grasp gets blocked by shields/stuff with block chance

### ISSUE THREAD

**Issue by demir-pl** [tgstation/tgstation#84042]
## Issue Summary 
Mansus grab gets blocked by shields,deswords anything that blocks or has block chance (cqc/carp excluded as its meant to block/avoid it).
And i am pretty sure mansus grasp isnt meant to be blockable like cult stun isnt blockable

## Reproduction:  
1 give shield/anything with block chance to monkey or whatever
2 give yourself heretic and try to mansus grasp them few times 

we can observe mansus getting blocked when it should be unblockable like cult stun

**Comment by MrMelbert** [comment]
This is because they use afterattack while cult spells override attack directly

(I think we should probably add an item flag for unblockable or something)
