### ISSUE TITLE
As a roundstart Felinid QM, had the "my tail is back, but that was traumatic..." moodlet

### ISSUE THREAD

**Issue by JohnHenryEton** [tgstation/tgstation#84048]
Reporting client version: 515.1636

## Issue Summary
Roundstart felinid quartermaster, checked moodlets and had that one.

## Round ID:
[230656](https://scrubby.melonmesa.com/round/230656)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Fixes free chemsplosion reagent purging by replacing it with the same thing but dangerous](https://www.github.com/tgstation/tgstation/pull/83195)

## Reproduction:
Start a round as a felinid quartermaster, seemingly.

**Comment by MrMelbert** [comment]
Tail insert moodlet needs to respect the `special` arg
