### ISSUE TITLE
Trying to buckle yourself to a seat as a cyborg displays this messsage

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#84047]
Reporting client version: 515.1639

## Issue Summary
![image](https://github.com/tgstation/tgstation/assets/96586172/7d248975-28b2-4bec-bf1c-0edf6b17fe07)

## Round ID:
[230653](https://scrubby.melonmesa.com/round/230653)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Fixes free chemsplosion reagent purging by replacing it with the same thing but dangerous](https://www.github.com/tgstation/tgstation/pull/83195)

**Comment by OuroborusReporter** [comment]
I Have No Ass, and I Must Sit
