### ISSUE TITLE
These boulders are running away!!

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#84051]
Reporting client version: 515.1639

## Issue Summary
https://youtu.be/Fqy2RB2ZJOU

## Round ID:
[230658](https://scrubby.melonmesa.com/round/230658)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Fixes free chemsplosion reagent purging by replacing it with the same thing but dangerous](https://www.github.com/tgstation/tgstation/pull/83195)

## Reproduction:
Use the same setup as in the video

**Comment by ArcaneMusic** [comment]
Appears to be #81685 all over again.
