### ISSUE TITLE
nightmare can no longer attack glowing objects to kill their light

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#84065]
Reporting client version: 515.1630

## Round ID:
[230695](https://scrubby.melonmesa.com/round/230695)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)

## Reproduction:
Try to attack lamp with your light eater, does nothing.

**Comment by GPeckman** [comment]
Probably related to all the click refactors

**Comment by Striders13** [comment]
> To clarify is this about attacking things, or clicking on things which are not attackable

things that aren't attackable

**Comment by Potato-Masher** [comment]
Things like those glowing circuit tiles come to mind
