### ISSUE TITLE
cant put crayon into a washing machine

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#84063]
Reporting client version: 515.1630

## Round ID:
[230695](https://scrubby.melonmesa.com/round/230695)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)

## Reproduction:
try to put in a crayon, can't. Even if there's already clothes inside the machine it doesnt work.

**Comment by LucyGrind** [comment]
huge, will fix immedietly
