### ISSUE TITLE
rainbow slime extract plasma reaction is broken

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#84076]
## Issue Summary
rainbow slime extract plasma reaction is broken
after the slime clusters become individual extracts none of them are activated

## Reproduction:

1. inject rainbow slime extract with plasma
2. it clusters into slime extracts
3. slime extracts dont do anything like theyre supposed to

**Comment by GPeckman** [comment]
Per the wiki, the extracts aren't supposed to do anything with plasma. It's when you inject the core with slime jelly that its supposed to make active extracts.

**Comment by mc-oofert** [comment]
whoever wrote this wiki page should get better at it
