### ISSUE TITLE
Crayon't Write

### ISSUE THREAD

**Issue by LSommers** [tgstation/tgstation#84092]
Reporting client version: 515.1637

## Issue Summary

Crayons can't write, nor can they be used to mess with cardboard cutouts.

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [tgui: adds tgui npm library](https://www.github.com/tgstation/tgstation/pull/83789)
- [basic firebots refactor](https://www.github.com/tgstation/tgstation/pull/83861)
- [Adds a new power storage type: The Megacell. Drastically reduces power cell consumption/storage. [MDB Ignore]](https://www.github.com/tgstation/tgstation/pull/84079)

## Reproduction:

Obtain any crayon, paper, five cardboard.
Attempt to write on paper. Fail.
Attempt to make a cardboard cultist. Fail.
Cry and eat your crayon.

**Comment by lizardqueenlexi** [comment]
Could not replicate. Using every type of crayon, I was able to write on paper and change a cardboard cutout, as such:

![image](https://github.com/tgstation/tgstation/assets/105025397/77e5084c-2839-46b0-a5e2-acf27adfff92)

I will say, though, that the writing interface is kind of screwy around crayons. If you type something in and hit enter, it will appear on the page, but not actually save until you click the "save" button twice. This appears to be different from pens, where the text will not appear at all until you click save properly.
