### ISSUE TITLE
Borgs can't use modules while buckled.

### ISSUE THREAD

**Issue by Dawnseer** [tgstation/tgstation#84137]
Reporting client version: 515.1640

## Issue Summary
Exactly what it says on the tin. Borgs can't use their modules when they're buckled to a chair. Or a horse. Or anything.

## Round ID:
[230798](https://scrubby.melonmesa.com/round/230798)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Bitrunning: Tweaks, QoL and removals](https://www.github.com/tgstation/tgstation/pull/84125)
- [Adds a new power storage type: The Megacell. Drastically reduces power cell consumption/storage. [MDB Ignore]](https://www.github.com/tgstation/tgstation/pull/84079)

## Reproduction:
Step 1) Be a borg
Step 2) Buckle yourself to a chair
Step 3) Try to use a module
Step 4) Weep and unbuckle yourself, renouncing the comforts

**Comment by ATH1909** [comment]
priority: critical

skaterborg must be freed

**Comment by Sadboysuss** [comment]
Looks like this is intended:
```php
//while buckled, you can still connect to and control things like doors, but you can't use your modules
if(buckled)
	to_chat(src, span_warning("You can't use modules while buckled to [buckled]!"))
	return
```

**Comment by Dawnseer** [comment]
Malicious intentions should be classified as a bug.

**Comment by Sadboysuss** [comment]
> Malicious intentions should be classified as a bug.

this is technically not a bug but I don't see any reason to restrict cyborgs with this, so you're free to open a pr and try to get it merged, I don't think anyone would mind.
