### ISSUE TITLE
Fire Extinguishers cannot be refilled with holy water.

### ISSUE THREAD

**Issue by dalmationer** [tgstation/tgstation#84140]
## Issue Summary

Fire extinguishers, when used on a blessed water tank, return the "cannot be refilled with this reagent" pop-up text.
Probably caused by #84004

## Reproduction:

Bless a water tank by using a bible on it.
Attempt to refill a fire extinguisher, either partially or fully empty, by using it on the water tank.
You should recieve a popup which says 'cannot refill with this reagent'

**Comment by JupiterJaeden** [comment]
This looks like a super easy fix, I'll probably work on it later tonight.

**Comment by Rhials** [comment]
Appears to have been broken by https://github.com/tgstation/tgstation/pull/84004

An extra safety check that makes sure the reagent is the appropriate one that wasn't there prior (Line 193, [code/game/objects/items/extinguisher.dm](https://github.com/tgstation/tgstation/pull/84004/files#diff-aa507114907bc6e9e559c5f24e2b87c10fb609e15f9a3a27a77151303560c0a4)) seems to be the blocking function.
