### ISSUE TITLE
Wheelchairs cannot move in zero-G.

### ISSUE THREAD

**Issue by dalmationer** [tgstation/tgstation#84141]
## Issue Summary

Not sure whether this is a bug, but wheelchairs (and by extension, other vehicles), cannot move while in zero-g or space. They can be blasted about with an extinguisher as normal, though. This means that if you're e.g. playing a wheelchair character and you get sucked into space, you often have to get off the wheelchair to move, which freezes you in the place as the wheelchair continues moving, It can also make the boundary between an area with gravity and an area without gravity particularly difficult, as if you try to drag your chair back inside, you will often fall flat on your face and lose your grab.

## Reproduction:

Spawn as a character with the paraplegic quirk, or otherwise get a wheelchair, and drive it into space. Observe the unusual movement mechanics.

**Comment by Jacquerel** [comment]
at the very least getting off a wheelchair should preserve your newtonian movement, if that is at all possible

**Comment by ZephyrTFA** [comment]
something with wheels not having traction in zero-g makes sense.
