### ISSUE TITLE
MODsuit tool interactions broken

### ISSUE THREAD

**Issue by delingar** [tgstation/tgstation#84145]
## Issue Summary

You can't use screwdiver, multitool and so on at modsuit

## Round ID:

Found on down-downstream https://github.com/Fluffy-Frontier/FluffySTG

## Reproduction:

Get modsuit in ur hand. 
Get screwdiver.
Try to open MODsuit.
It doesn't. Cry about it

**Comment by MrMelbert** [comment]
#83902 Try combat mode 

also see #84083
