### ISSUE TITLE
bridge assistant access bugged

### ISSUE THREAD

**Issue by isotope436** [tgstation/tgstation#84159]
## Issue Summary
some odd reason bridge assistant's announcement access doesnt work me and dunham tried a few things like putting it on a silver ID or adding verious other command access to see if it would pop up but alas it seems to be completely borked.

## Round ID: [230803](https://scrubby.melonmesa.com/round/230803)

[Round ID]: [230803](https://scrubby.melonmesa.com/round/230803)

## Testmerges: The following pull requests are currently test merged:
[#83227: '[TM ONLY] Hijacked Revision Date for v3 TGS Api' by ZephyrTFA at commit 8575d21082](https://www.github.com/tgstation/tgstation/pull/83227)
[#84125: 'Bitrunning: Tweaks, QoL and removals' by jlsnow301 at commit f4d573f608](https://www.github.com/tgstation/tgstation/pull/84125)
[#84079: 'Adds a new power storage type: The Megacell. Drastically reduces power cell consumption/storage. [MDB Ignore]' by Watermelon914 at commit 14c13a9f6f](https://www.github.com/tgstation/tgstation/pull/84079)

**Comment by Sadboysuss** [comment]
Are you talking about the bridge request console that hangs on a wall? Also this is Wawastation
