### ISSUE TITLE
Flatpacker lets you stack machines ontop of eachother

### ISSUE THREAD

**Issue by moocowswag** [tgstation/tgstation#84150]
Reporting client version: 515.1631

## Issue Summary
Flatpacker packs do not check if a tile is already occupied by something dense when you unpack them, allowing machines to be stacked onto the same tile, this is particularly powerful with modular shield generators because you can make an infinitely large shield generator in a 2 tile space

## Round ID:
[230812](https://scrubby.melonmesa.com/round/230812)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)

## Reproduction:
Pack machines with flat packer

Stack packs on the same tile

multi tool them all

![image](https://github.com/tgstation/tgstation/assets/62126254/8962ccf5-f364-421d-9151-2a656067b567)

**Comment by Vect0r2** [comment]
Hahahahahaha
