### ISSUE TITLE
Using legion core on pulsing tumor gives 'invalid target' message

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#84151]
Reporting client version: 515.1630

## Round ID:
[230817](https://scrubby.melonmesa.com/round/230817)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)

## Reproduction:
Using the core is supposed to make you fight sentient elite.

**Comment by the-orange-cow** [comment]
There have been a lot of use/attack refactors lately.
