### ISSUE TITLE
Many Game Preference Settings Are Not Applied Correctly

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#8416]
Ghost ears will always effectively act as "Nearby mobs"
Ghost eyes will always effectively act as "All mobs"

These are some examples, there are probably more. It does not matter how you have them set in your savefile, you have to manually fix them every time after you become a ghost.

**Comment by Miauw62** [comment]
I have no fucking clue what is causing this.

**Comment by Incoming5643** [comment]
Problem  exists on how settings are applied so I'm going to baselessly accuse #8334 again

**Comment by Jalleo** [comment]
This is related to the character save i bet.

**Comment by Mervill** [comment]
@optimumtact closeable, no longer an issue
