### ISSUE TITLE
Sparks from Bluespace Drop Pods and Cargo Crates will ignite their contents and all surrounding flammable objects

### ISSUE THREAD

**Issue by DrAmazing343** [tgstation/tgstation#84169]
## Issue Summary
Specifically encountering this a lot as Cook— every time I use my produce console, I need a fire extinguisher on hand, as the sparks from the bluespace drop pod disappearing will set every single produce item I order on fire. Similarly, this happens to the contents and surrounding objects of all Cargo crates (specifically departmental orders) that have self-destructing locks on them, as they will also spark when the lock self-destructs upon being opened at its destination.

## Round ID:
[R230771](https://scrubby.melonmesa.com/round/230771)

## Testmerges:
[#83227: '[TM ONLY] Hijacked Revision Date for v3 TGS Api' by ZephyrTFA at commit 8575d21082](https://www.github.com/tgstation/tgstation/pull/83227)[#83227: '[TM ONLY] Hijacked Revision Date for v3 TGS Api' by ZephyrTFA at commit 8575d21082](https://www.github.com/tgstation/tgstation/pull/83227)[#83227: '[TM ONLY] Hijacked Revision Date for v3 TGS Api' by ZephyrTFA at commit 8575d21082](https://www.github.com/tgstation/tgstation/pull/83227)

## Reproduction:
Buy anything from the produce console and order it, then step back and watch your wonderful pile of onions and garlic turn into a fragrant bonfire. In the same vein, order a crate of pizzas now that your ingredients are charcoal, and open it inside your department only to be dismayed as all of the boxes are immediately set alight.

**Comment by Metekillot** [comment]
Surrounding flammable objects getting ignites is intended. Stop opening crates that throw shitloads of sparks around flammable stuff you don't want burned. All your food going up in flames isn't intended.

You can extinguish objects by wearing fireproof gloves btw.

**Comment by dalmationer** [comment]
This also affects instruments from the instrument beacon. I'll order the synthesiser and it will arrive on fire! Should I make a seperate issue about this?

**Comment by Livrah** [comment]
almost like the PR was a mistake

**Comment by DrAmazing343** [comment]
> Surrounding flammable objects getting ignites is intended. Stop opening crates that throw shitloads of sparks around flammable stuff you don't want burned. All your food going up in flames isn't intended.
> 
> You can extinguish objects by wearing fireproof gloves btw.

Good tip on that last bit— however, maybe we ought to change the particle for crates if, indeed, it's intended for everything surrounding it to burst into flame? Perhaps we ought to also move the produce consoles on each map into safely non-flammable areas, as well. Should each map have a designated Departmental Order crate opening 3x3?

I think it's just a little odd to simply say all of this is "intended" when, yes, it is the literal intended result of the sparks PR, but it's also a lot of very negative game effects that've seemingly spiraled off a PR that was made with good intentions but perhaps not forethought for each facet of the game it could affect.

**Comment by ATH1909** [comment]
do droppodded fuel tanks get detonated by their own droppods? would that enable a return of the old McAirstrike?

**Comment by Metekillot** [comment]
Alright ya got me I didn't intend to turn the station into a smoldering conflagration due to the chef ordering berries and mushrooms. Reworking the sparks tonight

**Comment by SyncIt21** [comment]
This was fixed by #84193 but the author did not link the issue properly to close it. Please close the issue if it doesn't occur anymore
