### ISSUE TITLE
Cash Deposit Problems

### ISSUE THREAD

**Issue by LSommers** [tgstation/tgstation#84185]
Reporting client version: 515.1637

## Issue Summary
Space cash, coins, credits, etc can no longer be added to your bank account by clicking them onto your PDA. You have to remove your ID and click them on that instead.

## Round ID:
[230873](https://scrubby.melonmesa.com/round/230873)

## Reproduction:

Obtain physical currency. Attempt to shove it into your PDA like you did not to long ago. Fail. Pull out ID, attempt to put coin into it, succeed. Stare in bafflement.

**Comment by 00-Steven** [comment]
agh yeah no
![image](https://github.com/tgstation/tgstation/assets/42909981/38ebf9c3-5540-4a5b-a468-d42b25efb10a)
it's because modular computer items still use `attackby(...)`

**Comment by 00-Steven** [comment]
https://github.com/tgstation/tgstation/blob/24a23009e8ee4d056b6671c70c41feab1a18590b/code/modules/modular_computers/computers/item/computer.dm#L790-L800

**Comment by 00-Steven** [comment]
yeah lemme make a pr
