### ISSUE TITLE
Attempting to insert Credits into your ID while inside your PDA fails to do anything.

### ISSUE THREAD

**Issue by DrAmazing343** [tgstation/tgstation#84199]
Reporting client version: 515.1637

## Issue Summary
During round 230899, I attempted to tap Space Cash directly into my PDA like I normally do to add to my ID, but it didn't work, and I dropped the Space Cash. During round 230901, I attempted to re-insert a 1cr chip I had used to move in zero-gee directly into the PDA, again, and it didn't work. I was able to add the Credits directly to my ID by taking it out and tapping the chit onto the ID, as usual.

## Round ID:
[230899](https://scrubby.melonmesa.com/round/230899)
230901

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)

## Reproduction:
Take Space Cash, or pull some Credits from your ID, and then put the ID back into your PDA and attempt to re-insert the Credits or add the Space Cash to your ID while it's inside the PDA.

**Comment by LSommers** [comment]
See https://github.com/tgstation/tgstation/issues/84185

**Comment by DrAmazing343** [comment]
Closing due to duplicate report, I was super sleep deprived and didn't see it!
