### ISSUE TITLE
Paraplegics can't buckle to any chair or ridable mob.

### ISSUE THREAD

**Issue by dalmationer** [tgstation/tgstation#84218]
## Issue Summary

Paraplegics can't buckle to certain chairs and mobs. You recieve the 'you can't do that right now' error.
Tested, this includes Raptors and Office Chairs.

Reported this to Higgin in-game in the round below, and they suggested that it may be due to some sort of issue with the recursion of loc (I might be misremembering what they said.) caused by #84006

I have not had the chance to see if this affects standing, resting or knocked down people yet.

EDIT: in [231020](https://scrubby.melonmesa.com/round/231020) it was discovered that this seems to affect ALL chairs and ridable mobs, except the wheelchair, however other players can still buckle you to things, you just can't do it to yourself.

## Round ID:  [230911](https://scrubby.melonmesa.com/round/230911)
[231020](https://scrubby.melonmesa.com/round/231020)

## Reproduction:
As paraplegic, get off of your wheelchair and attempt to buckle onto any chair or ridable mob. You should recieve the 'you can't do that right now' warning.

**Comment by 00-Steven** [comment]
willing to bet it's missing the `ALLOW_RESTING` interaction flag or something

**Comment by dalmationer** [comment]
> willing to bet it's missing the `ALLOW_RESTING` interaction flag or something

@SyncIt21 was asked in Discord to @ you regarding this.

**Comment by TheVekter** [comment]
I believe paraplegics are intended to not be able to be buckled to raptors given that they also can't ride borgs. Their legs can't squeeze down on them to keep themselves steady.

**Comment by Higgin** [comment]
It's also currently not possible to buckle yourself to a raptor while resting in general, which makes me think it's a bug/undocumented change.

**Comment by dalmationer** [comment]
> I believe paraplegics are intended to not be able to be buckled to raptors given that they also can't ride borgs. Their legs can't squeeze down on them to keep themselves steady.

they actually can do this, and so can dead bodies.

**Comment by SyncIt21** [comment]
Fixed by above PR. Also I don't use discord

**Comment by SyncIt21** [comment]
> willing to bet it's missing the `ALLOW_RESTING` interaction flag or something

You are correct. Let the linked PR know about this

**Comment by Rhials** [comment]
It's worth noting that other players can buckle you to these things, but you cannot buckle yourself.

**Comment by dalmationer** [comment]
in round 231020 I discovered this doesn't just affect riding raptors, it seems to affect almost everything you sit on when you buckle yourself to, except wheelchairs. This includes normal chairs, cows, raptors, shuttle seats, and the janicart, all of which you were previously able to buckle to. Other people can buckle you to all of these things. I will update the issue to reflect this.
