### ISSUE TITLE
Butchering isn't affected by meatspikes or knife type/sharpness

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#84228]
Reporting client version: 515.1640

## Issue Summary
I was expecting that using the meatspikes would do anything regarding meat, but it's a lot of extra work for no benefit from just butchering on the floor. Same with just using any knife as opposed to just any old kitchen one.

## Round ID:
[230941](https://scrubby.melonmesa.com/round/230941)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Cult Vs. Heretic: 7 Months Later Edition](https://www.github.com/tgstation/tgstation/pull/82877)
- [Bitrunning: Tweaks, QoL and removals](https://www.github.com/tgstation/tgstation/pull/84125)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/76874615/c7b36d31-17cd-4669-a77d-93e314f52efd)
Hanging something on a meatspike to butcher doesn't give more meat than the standard ammount (5 for monkeys).
Using better/sharpened knives for butchering doesn't give more meat (again, just 5 for monkeys).
Using a gibber actually gives Less meat, unless upgraded (3 slabs, +1 per tier, up to 6)

**Comment by newfren** [comment]
the survival knife has a chance to get extra stuff from butchering, as does the crusher.

**Comment by AdipemDragon** [comment]
yes yes, but i tested solely from a chef's capability of toolage, you probably wouldn't want to see a chef bummin round mining

**Comment by Sadboysuss** [comment]
everything here is working as intended but it is a bit silly that the gibber gives less meat than butchering manually.

**Comment by AdipemDragon** [comment]
I SWEAR there was a time when meatspike butchering gave a flat +1 meat or something like that, I genuinely distinctly remember a time when, while dead rats still counted as dead bodies and not items, I hung a rat on a meatspike and got Two Steaks out of it instead of one. is it that much for a small bonus to exist?

**Comment by Sadboysuss** [comment]
> I SWEAR there was a time when meatspike butchering gave a flat +1 meat or something like that, I genuinely distinctly remember a time when, while dead rats still counted as dead bodies and not items, I hung a rat on a meatspike and got Two Steaks out of it instead of one. is it that much for a small bonus to exist?

I'm sure nobody would mind if it did, but as it stands, after looking through the code - it works as intended, there is no bonus in the code

**Comment by Dawnseer** [comment]
I swear it should be somewhere in the examine description that it should get you more meat

**Comment by Sadboysuss** [comment]
```php
	name = "meat spike"
	icon = 'icons/obj/service/kitchen.dmi'
	icon_state = "spike"
	desc = "A spike for collecting meat from animals."
```
```php
/obj/structure/kitchenspike/examine(mob/user)
	. = ..()
	. += "<b>Drag a mob</b> onto it to hook it in place."
	. += "A <b>crowbar</b> could remove those spikes."
```
Maybe it was removed at some point? Last time the code for the meat spike was changed in any meaningful way was 2 years ago, and the examine proc was changed 17 months ago.
