### ISSUE TITLE
You can't put non clothes items into a washer as dye.

### ISSUE THREAD

**Issue by Moltovz** [tgstation/tgstation#84229]
## Issue Summary
It's over bros, you can't dye anything with crayons anymore, and more than likely this means TC and stamps can't be used either.
![image](https://github.com/tgstation/tgstation/assets/61367602/27e70460-68a6-4370-ae92-d22fb0e2b256)

## Round ID:
[230950](https://scrubby.melonmesa.com/round/230950)

## Reproduction:

- Get crayon
- Go to washer
- Put in item of choice
- Try to put in crayon/stamp
- Cope because you can't make your fake insuls

**Comment by SmArtKar** [comment]
Only applies to crayons.

**Comment by Moltovz** [comment]
Thank you bestie
