### ISSUE TITLE
You can't pull hydroponics trays

### ISSUE THREAD

**Issue by dalmationer** [tgstation/tgstation#84222]
## Issue Summary

Unwrenched hydroponics trays cannot be pulled. They can be pushed just fine, though.

## Reproduction:

Unwrench a hydroponics tray and attempt to pull it. Nothing will happen.

**Comment by dalmationer** [comment]
it wasn't just for me-- during the round ID'd above, myself and the chef were doing some botany, and we both noticed we couldn't pull them.

**Comment by dalmationer** [comment]
This also seems to affect medical beds. I haven't seen it affect anything else though.

**Comment by SyncIt21** [comment]
Fixed by above PR
