### ISSUE TITLE
Player monkies given sentience by the monkey mind magnificence helmet cannot ventcrawl because of the helmet

### ISSUE THREAD

**Issue by LikeLakers2** [tgstation/tgstation#84259]
This issue is a forward of an issue from the Monkestation repository: https://github.com/Monkestation/Monkestation2.0/issues/2378

## Issue Summary
> See title. Monkeys normally have the ability to ventcrawl but due to the helmet counting as an item, one which they cannot take off there is no way for those turned into one this way to ventcrawl.

Before submitting this issue to this repo, I checked if tgstation's codebase had any fixes for this issue (it did not). I also checked if there were any differences in code that could have pointed to tgstation having different behavior (I did not see any). Seeing those results, I felt it was reasonable to forward this issue to tgstation's repo.

I'm aware that this isn't a bug, per-se. But if a monkey wearing a mind-magnification helmet shouldn't be able to ventcrawl, then perhaps there should at least be a message stating as such? ("Going in the vents might knock off your precious helmet!")

## Round ID:
N/A, not from tgstation.

## Testmerges:
N/A, not from tgstation.

## Reproduction:
1. Become a mind-magnified monkey.
2. Attempt to ventcrawl.
5. Be blocked because of the mind-magnification helmet - which you cannot take off without losing sentience.

**Comment by DATA-xPUNGED** [comment]
I don't see where the issue is; When you try to vent crawl it already states that it's because you are using an item. Doesn't take much to realize that your mind magnification helmet is the culprit

**Comment by DATA-xPUNGED** [comment]
When you become a monkey you DO get the info that you can vent-crawl, but this info applies to anything that can vent crawl

**Comment by LikeLakers2** [comment]
> I don't see where the issue is; When you try to vent crawl it already states that it's because you are using an item. Doesn't take much to realize that your mind magnification helmet is the culprit

The issue is: Why allow mind-magnified monkies to even begin to ventcrawl, if the helmet will just block them anyways? It makes no sense to give them an ability that they can't use.

**Comment by DATA-xPUNGED** [comment]
That's fair enough, I stand corrected
