### ISSUE TITLE
Click-dragging to piggyback someone no longer works

### ISSUE THREAD

**Issue by TrashWitch23** [tgstation/tgstation#84264]
## Issue Summary
When trying to click-drag yourself to someone after being aggro-grabbed, you get the error message: "You can't do this right now!"

## Round ID:
[11097](https://scrubby.melonmesa.com/round/11097) on Nova Sector
https://github.com/NovaSector/NovaSector

## Reproduction:
1) Have someone aggressive-grab you.
2) Click-drag from yourself onto the person grabbing you.
3) Get error message "You can't do this right now!"

**Comment by 00-Steven** [comment]
Can confirm this is an issue on my dev instance (Which is on commit 1116f15)

**Comment by 00-Steven** [comment]
But yo @SyncIt21 this sounds like you'd have a clue

**Comment by Metekillot** [comment]
Set status CRITICAL
