### ISSUE TITLE
Bitrunner cargo bounties seem to be fully random/not tied to job

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#84283]
Reporting client version: 515.1637

## Issue Summary
When getting a bounty target as a bitrunner, it seems to generate choices from ALL possible bounties across all jobs, leaving you with few choices you can actually get.

## Round ID:
231040

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Cult Vs. Heretic: 7 Months Later Edition](https://www.github.com/tgstation/tgstation/pull/82877)
- [Moves tool use back higher in the chain, but makes it so tool acts are only called on non-combat-mode](https://www.github.com/tgstation/tgstation/pull/84083)
- [Bitrunning: Combat domain](https://www.github.com/tgstation/tgstation/pull/84196)

## Reproduction:
Be a gamer
Get a bounty to sell a canister of BZ
Cry

![Screenshot 2024-06-23 212446](https://github.com/tgstation/tgstation/assets/88996803/64bec89b-138a-4712-be82-445834745a64)

**Comment by ArcaneMusic** [comment]
Pretty cut and dry:
`	bounty_types = CIV_JOB_RANDOM`
This assignment in `/datum/job/bitrunner` is what's causing this behavior. There's no specific assignment for bounties that need to be completed by bitrunners as well, so there'll likely need to be a specific replacement that makes sense for the job, or possibly a small set of bitrunner specific bounties to be added.

**Comment by OuroborusReporter** [comment]
Not too many job-specific bounties they **can** complete, honestly. Maybe bounties for the rewards they sometimes get from finishing sims, or for the BEPIS data disks so they have use after you get all of the tech? It's a pretty material goods-low job

**Comment by TheVekter** [comment]
> Not too many job-specific bounties they **can** complete, honestly. Maybe bounties for the rewards they sometimes get from finishing sims, or for the BEPIS data disks so they have use after you get all of the tech? It's a pretty material goods-low job

I may just honestly give them cargo bounties since they're a subset of that job anyway.
