### ISSUE TITLE
My plague doctor hat does it all.

### ISSUE THREAD

**Issue by iansdoor** [tgstation/tgstation#84295]
I am curious about the thoughts of consistency on this one.
So a hat alone with nothing else blocks pepperspray and facehuggers, but my snout is clear to the world.
![Screenshot_620](https://github.com/tgstation/tgstation/assets/109386467/65228b40-db1e-4102-817b-1be8c37292ef)
![Screenshot_621](https://github.com/tgstation/tgstation/assets/109386467/d1e247d2-a22c-4957-a2ea-cc16abbaa583)
![Screenshot_622](https://github.com/tgstation/tgstation/assets/109386467/3a2af29b-7366-4e59-b852-ec94ba3eed2e)
![consistency](https://github.com/tgstation/tgstation/assets/109386467/915003a9-75e2-487e-89df-f7e5719d68f7)

**Comment by Sadboysuss** [comment]
Moving the hat to be a subtype of `/obj/item/clothing/head` and removing unneeded clothing flags, then giving the needed behaviors to the mask should be an easy fix here.

**Comment by Jackal-boop** [comment]
CMO should keep a biosuit subtype

**Comment by Sealed101** [comment]
i assume this was fixed by #84953 and not linked properly correct?
