### ISSUE TITLE
Integrated Circuitry UI manipulation is misaligned 

### ISSUE THREAD

**Issue by CrazyDrakkon** [tgstation/tgstation#84291]
Reporting client version: 515.1640

## Issue Summary
After zooming/scrolling in the Integrated Circuit window, moving modules and wiring is very misaligned and unweildly.

## Round ID:
[231050](https://scrubby.melonmesa.com/round/231050)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)

## Reproduction:
1. Open up an Integrated Circuit window.
2. Either zoom in/out or scroll within the Integrated Circuit UI.
3. Try placing new modules or wiring.

**Comment by Sadboysuss** [comment]
Couldn't reproduce on latest master
