### ISSUE TITLE
Stacks of duct pipes cannot be merged in hand

### ISSUE THREAD

**Issue by zoomachina** [tgstation/tgstation#84293]
## Issue Summary
Before, you could merge 2 stacks of duct pipes by clicking one with another in hand. Now, you cannot do that.

## Reproduction:
Have 2 stacks of plumbing pipes in your hands, click at one. Nothing happens.
You can still merge the stacks by dropping them and dragging them to eachother.
It's possible that the same issue persists with other stuff, like mats or floor tiles.

**Comment by Sadboysuss** [comment]
looks like something to do with `attackby`
