### ISSUE TITLE
Can't make a floor by clicking on lattice

### ISSUE THREAD

**Issue by zoomachina** [tgstation/tgstation#84294]
## Issue Summary
If you have a floor tile in hand and click on a lattice in space, nothing happens. You can still put it in by clicking on the space tile itself, which means that if you want to fix a breach, you need to pixel hunt the space between the lattice.

## Reproduction:
Click on a space tile to make a lattice out of 2 iron rods.
Click on the created lattice with a floor tile - nothing happens.
Click on the space behind the lattice with a floor tile - floor will be constructed.

**Comment by Sadboysuss** [comment]
In the future, please include the round ID and testmerges as it helps pinpoint the bug easier. If you reproduced it locally , check if you were on the latest master and if it was on a fork, please check if it can be reproduced on /tg/ master. Thank you for the report.
