### ISSUE TITLE
Peg legs can bleed.

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#84303]
Reporting client version: 515.1639

## Issue Summary
![image](https://github.com/tgstation/tgstation/assets/96586172/e4004fef-9616-46cc-bbf9-66501d8438e4)

@LucyGrind 

Also there is no way to remove a peg leg organically and you probably should be able to just pop it off.

## Round ID:
[231069](https://scrubby.melonmesa.com/round/231069)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Moves tool use back higher in the chain, but makes it so tool acts are only called on non-combat-mode](https://www.github.com/tgstation/tgstation/pull/84083)
- [Bitrunning: Combat domain](https://www.github.com/tgstation/tgstation/pull/84196)

**Comment by Dawnseer** [comment]
Cursed

**Comment by Profakos** [comment]
Supposedly fixed by #84394 by now, it didnt link the issue.
