### ISSUE TITLE
projectile damper field overlays dont appear to actually work

### ISSUE THREAD

**Issue by Paxilmaniac** [tgstation/tgstation#84301]
## Issue Summary

I was doing some testing to see how a resprited dampener field would look, but it turns out they don't look at all actually. The overlay just doesn't appear on either the PK borg or the modsuit module.

## Reproduction:
Use a projectile dampener field generator of some sort, the overlays that are supposed to project around you to show the field don't appear, but the field is still there because projectile that pass through where it should be still get reduced damage and the overlay effect they are supposed to get

**Comment by MrMelbert** [comment]
Using the debug field tool we can see Edge Turf Don't Exist anymore

(teal = field turf, purple = edge turf) 

![image](https://github.com/tgstation/tgstation/assets/51863163/ee4ec4fe-1f76-4b39-8a83-ef6b723cad5a)

**Comment by MrMelbert** [comment]
And [timestop](#73339) is back to being a 3x3 motherfu-

![image](https://github.com/tgstation/tgstation/assets/51863163/d70b5689-e3ec-4ce3-9420-2f5e3b1cfa40)
