### ISSUE TITLE
Space Heaters seem to burn through energy too quickly?

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#84329]
Reporting client version: 515.1640

## Issue Summary
Even with full T4 parts, a space heater seems to burn through an entire T4 bluespace cell within 2 minutes, and seems to burn through an unupgraded cell Instantly,

## Round ID:
[231115](https://scrubby.melonmesa.com/round/231115)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Some alt & ctrl click improvements](https://www.github.com/tgstation/tgstation/pull/84203)
- [Cult Vs. Heretic: 7 Months Later Edition](https://www.github.com/tgstation/tgstation/pull/82877)

## Reproduction:
Grab a space heater from maint.
It shuts off within 30 seconds,
Make your due diligence and upgrade it with T4 parts and a full bluespace cell.
![toofast](https://github.com/tgstation/tgstation/assets/76874615/7ea2388f-3c60-4851-a836-41d2d319a6d7)
While very powerful when it comes to actually fixing the freezing air when upgraded fully like this, I doubt that the power is supposed to explode This Fast
(unless it is, so then it's time to treat space heaters like eguns, then)

**Comment by Sadboysuss** [comment]
Likely caused by https://github.com/tgstation/tgstation/pull/84079

@Watermelon914

**Comment by Inari-Whitebear** [comment]
Yeah, when the megacells are in, they drain so quickly. Even a bluespace cell one.
Walked into a 300C room and it drained near instantly even on a full bluespace cell

**Comment by Watermelon914** [comment]
Any issue managers, if you see any other reports that are power consumption related, add them to the new milestone
