### ISSUE TITLE
Gatfruit can go into plant bags

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#84323]
Reporting client version: 515.1639

## Issue Summary
Technically not a bug but probably shouldn't be a thing

## Round ID:
[231102](https://scrubby.melonmesa.com/round/231102)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Moves tool use back higher in the chain, but makes it so tool acts are only called on non-combat-mode](https://www.github.com/tgstation/tgstation/pull/84083)
- [Bitrunning: Combat domain](https://www.github.com/tgstation/tgstation/pull/84196)

## Reproduction:
1. Get gatfruit
2. Put it in a plant bag
3. Have 50 .357 revolvers on stand-by

**Comment by MrMelbert** [comment]
Feature requests are not handled in the repository. The best place to discuss these ideas would be on the /tg/station 13 forums here: https://tgstation13.org/phpBB/viewforum.php?f=9&sid=5153c1c704a4fb1006bf7a265e45e03f
