### ISSUE TITLE
Spraycans cannot recolour items or furniture.

### ISSUE THREAD

**Issue by dalmationer** [tgstation/tgstation#84333]
## Issue Summary

Using spraycans on furniture or items usually recolours the item in question, however today this functionality has been broken. This also means it is currently not possible to use spraycans as a source of ethanol for improvised chemistry. Drawing on floors and walls works as normal.
Probably caused by #84231 as it touches crayon code which spraycans are a subtype of.

## Testmerges:

[#83227: '[TM ONLY] Hijacked Revision Date for v3 TGS Api' by ZephyrTFA at commit 8575d21082](https://www.github.com/tgstation/tgstation/pull/83227)
[#84203: 'Some alt & ctrl click improvements' by SyncIt21 at commit 2fed7e5673](https://www.github.com/tgstation/tgstation/pull/84203)
[#82877: 'Cult Vs. Heretic: 7 Months Later Edition' by carlarctg at commit 4fb796f624](https://www.github.com/tgstation/tgstation/pull/82877)

## Reproduction:

Print a spraycan in the service lathe, remove the top, and use it on the floor. You will be able to paint a picture.
Now attempt to use it on an item, chair or table (on combat mode with the table.) you will not be able to recolour the item or furniture.
Attempt to use the spraycan on a beaker or reagent container- it will not recolour the container, and will not add ethanol and welding fuel to it.

**Comment by SmArtKar** [comment]
Reproducable on master, so not #84203. Probably #84231

**Comment by dalmationer** [comment]
Updated to remove that.
