### ISSUE TITLE
Northstar toxins cooling scrubber has no output

### ISSUE THREAD

**Issue by bob-b-b** [tgstation/tgstation#84336]
## Issue Summary

The scrubber doesn't seem to connect to any pipe, trying to place one without breaking into the chamber is also, as far as I could tell, not feasible.

![image](https://github.com/tgstation/tgstation/assets/36081010/5a87f4d1-5d95-4d8d-8a9e-aca4e361ea96)

## Round ID:

Round ID: [231126](https://scrubby.melonmesa.com/round/231126)

## Reproduction:

Walk into toxins, try to place layer 3 pipe under either of the grilles, fail to connect to the scrubber.

**Comment by GPeckman** [comment]
![ordnance](https://github.com/tgstation/tgstation/assets/21979502/f4b3e971-095e-45f0-a48a-67cc644877d6)
Looks like the scrubber connects to that vertical pipeline there. Although it probably should be above the floor tiles, to make it more obvious that it exists.

**Comment by TheVekter** [comment]
![image](https://github.com/tgstation/tgstation/assets/7019927/7e2fd573-2177-4503-9414-c7a1270a456f)
Better screenshot. Definitely connects via that pipeline. I agree that it should be above the floor tiles, I'll see if I can make that happen.
