### ISSUE TITLE
Examine tips for cycling IDs on airlocks show "this airlock does not cycle." when they are supposed to be cycling

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#84330]
## Issue Summary
When trying to reproduce https://github.com/tgstation/tgstation/issues/84321 I discovered this.
![image](https://github.com/tgstation/tgstation/assets/96586172/07670a8e-adcf-46ce-af97-e2a6742a38b6)
![image](https://github.com/tgstation/tgstation/assets/96586172/f040ca9d-86b2-4841-be97-68f1cf527fd1)

And
![image](https://github.com/tgstation/tgstation/assets/96586172/d6c96d04-8f4d-409a-96e9-caddbc6f965d)
![image](https://github.com/tgstation/tgstation/assets/96586172/69437f57-2184-4ed8-84eb-3b5b2e78d7bc)

As examples. Functionally they work but the examine doesn't.

## Round ID:
reproduced locally

## Reproduction:
1. Examine an airlock that is supposed to cycle

**Comment by alien3301** [comment]
I have more than 400 hours on tg and I have never had the game tell me an airlock cycles lol

**Comment by Inari-Whitebear** [comment]
Yeah, it seems quite broken. Would be nice if it showed cycling ids, esp. for rebuilding doors

**Comment by ShizCalev** [comment]
Not actually a bug, that var just isn't really used by mappers anymore since I added the helpers for them years ago. More of a consistency problem.
