### ISSUE TITLE
Metallic Hydrogen Bolts can sometimes go through walls

### ISSUE THREAD

**Issue by Borisvanmemes** [tgstation/tgstation#84353]
Reporting client version: 515.1637

## Issue Summary
Metallic Hydrogen Bolts go straight through walls if shot at a mob next to them. If there's air between the mob and the wall, it acts as expected and gets stopped.

## Round ID:
[231162](https://scrubby.melonmesa.com/round/231162)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Some alt & ctrl click improvements](https://www.github.com/tgstation/tgstation/pull/84203)
- [Moves tool use back higher in the chain, but makes it so tool acts are only called on non-combat-mode](https://www.github.com/tgstation/tgstation/pull/84083)

## Reproduction:

Spawn a mob, put it next to a wall, shoot it, and see how the projectile goes flying through the wall. Drag the mob one tile away from the wall, shoot it again, and have the bolt stop at the wall.

**Comment by EnterTheJake** [comment]
We can probably close this, as metallic hydrogen bolts going through walls is now intended due to this https://github.com/tgstation/tgstation/pull/86116.

**Comment by Sealed101** [comment]
^ true!
