### ISSUE TITLE
Brain surgery is broken (for mediborgs?)

### ISSUE THREAD

**Issue by plutori** [tgstation/tgstation#84355]
Reporting client version: 515.1636

## Issue Summary

The last step in brain surgery is supposed to be to cauterize the wound to close up their noggin. Upon trying to do so, however, I would get the error message that "This step requires a different tool!". Other methods to end the surgery such as using a welder on my engineering shell, or ending the surgery with drapes still worked, so the issue is most likely with the omnitool Cautery.

## Round ID:
[231165](https://scrubby.melonmesa.com/round/231165)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Some alt & ctrl click improvements](https://www.github.com/tgstation/tgstation/pull/84203)
- [Moves tool use back higher in the chain, but makes it so tool acts are only called on non-combat-mode](https://www.github.com/tgstation/tgstation/pull/84083)

## Reproduction:

1. Be a medical AI shell (or presumably a mediborg)
2. Do a brain surgery up to the final step
3. Try to end the surgery with your cautery
4. Fail, and then cry.

**Comment by Sadboysuss** [comment]
likely to be fixed by https://github.com/tgstation/tgstation/pull/84341
