### ISSUE TITLE
Birdshot bathrooms lack privacy

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#84357]
Reporting client version: 515.1640

## Issue Summary
When you try to use the Bird bathrooms's locks, you get. Nothing, they stay unlocked.

## Round ID:
[231171](https://scrubby.melonmesa.com/round/231171)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Some alt & ctrl click improvements](https://www.github.com/tgstation/tgstation/pull/84203)
- [Moves tool use back higher in the chain, but makes it so tool acts are only called on non-combat-mode](https://www.github.com/tgstation/tgstation/pull/84083)

## Reproduction:
Push button
Cry
![image](https://github.com/tgstation/tgstation/assets/76874615/32126dbb-1205-4f1b-a721-a7b26d9e600c)

**Comment by AdipemDragon** [comment]
i'm stupid, had wawa on the brain.

**Comment by TheVekter** [comment]
Probably a signal mismatch. Gimme a few.
