### ISSUE TITLE
The Midas Hand will not detect gold in someones system while trying to perform the drain while adjacent to the victim.

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#84351]
## Issue Summary

The Midas Hand turns peoples blood into gold. It is meant to then drain the gold from their bloodstream, but cannot detect this gold when used in melee. It does work from two tiles away.

## Reproduction:

Step 1: Get ye Midas Hand
Step 2: Shoot a scallywag
Step 3: Right-click the blighed fool while nexto to them.

You will get the message 'No gold in their bloodstream' but, if we then take one step back and use it, it will drain as expected.

**Comment by DATA-xPUNGED** [comment]
Possible related to click refactors? Although i'm not sure on that

**Comment by necromanceranne** [comment]
Almost certainty since it's using the new interaction procs to do the thing. Might be worth a @MrMelbert
