### ISSUE TITLE
Engineering borgs unable to interact with airlock wires

### ISSUE THREAD

**Issue by SmilisticMusic** [tgstation/tgstation#84359]
Reporting client version: 515.1636

## Issue Summary
As an engineering cyborg if you try to cut/mend/pulse airlock wires with the corresponding tool it will say that you need the corresponding tool for that and it will not do anything. Works on the door itself, the issue seems to only be with airlock UI panel buttons.

## Round ID:
[231174](https://scrubby.melonmesa.com/round/231174)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Some alt & ctrl click improvements](https://www.github.com/tgstation/tgstation/pull/84203)
- [Moves tool use back higher in the chain, but makes it so tool acts are only called on non-combat-mode](https://www.github.com/tgstation/tgstation/pull/84083)

## Reproduction:
Unscrew the airlock panel and attempt to cut/mend/pulse any wire on it. It will give you a message like you are lacking a correct tool and not do anything.

**Comment by Sadboysuss** [comment]
may get fixed by https://github.com/tgstation/tgstation/pull/84341
