### ISSUE TITLE
NT Frontier partner's researchable technologies were not updated to new techweb

### ISSUE THREAD

**Issue by delingar** [tgstation/tgstation#84375]
## Issue Summary

NT Frontier partner research assistance feature is not working because there are only "Unknown technology" (Noone updated them to new techwebs)

## Round ID:

Found on down-downstream: https://github.com/Fluffy-Frontier/FluffySTG

## Reproduction:

Turn on NT Frontier
Get assistance points for any partner
Go to tab "Partners"
Open Partner's minitab and try to research something.
Cry, noone updated this tab to new techweb

**Comment by Profakos** [comment]
Supposed to be fixed by #84177 Looking at your downstream, it has not merged the changes yet.
