### ISSUE TITLE
Can no longer access inventories while on the ground

### ISSUE THREAD

**Issue by Deadgebert** [tgstation/tgstation#84373]
## Issue Summary

Attempting to access your bag while prone gives you 'You don't have the mobility for this!' message.
You can still access your bag as normal if you had it open before laying down

## Round ID:
[231200](https://scrubby.melonmesa.com/round/231200)

## Testmerges:
https://github.com/tgstation/tgstation/pull/83227
https://github.com/tgstation/tgstation/pull/84203
https://github.com/tgstation/tgstation/pull/84083

## Reproduction:

> lay on ground
> attempt to access bag
> BAG STUCK
> die

**Comment by SyncIt21** [comment]
By access bag you mean you Alt clicked it right?

**Comment by Deadgebert** [comment]
alt click or just open in general is blocked

**Comment by SyncIt21** [comment]
So even right click does not work?

**Comment by Deadgebert** [comment]
correct

**Comment by SyncIt21** [comment]
I'll look into it

**Comment by Deadgebert** [comment]
sorry, i think i linked the issues incorrectly and it propagated to your PR

**Comment by Sadboysuss** [comment]
Can reproduce on live servers
