### ISSUE TITLE
Wearing a firesuit hides your gloves

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#84389]
Reporting client version: 515.1639

## Issue Summary
![image](https://github.com/tgstation/tgstation/assets/96586172/d83ccb5f-33a6-4a1c-8e46-e9eb9d73b1f9)

## Round ID:
[231232](https://scrubby.melonmesa.com/round/231232)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Some alt & ctrl click improvements](https://www.github.com/tgstation/tgstation/pull/84203)
- [Moves tool use back higher in the chain, but makes it so tool acts are only called on non-combat-mode](https://www.github.com/tgstation/tgstation/pull/84083)

**Comment by necromanceranne** [comment]
I bet this is a holdover from when the sprite used to have gloves

**Comment by necromanceranne** [comment]
oh turns out we still use that old sprite. Yikes, I hope that isn't a goon sprite.
