### ISSUE TITLE
sliver extraction dusts you

### ISSUE THREAD

**Issue by MelokGleb** [tgstation/tgstation#84398]
Reporting client version: 515.1640

## Issue Summary

"You touch the supermatter bin with the supermatter extraction tongs, and everything suddenly goes silent.

The supermatter bin and the supermatter sliver flash into dust, and soon as you can register this, you do as well."

if you try to put sm sliver into sliver container you will get dusted

https://github.com/tgstation/tgstation/assets/99420088/6b447fdc-821d-451c-9082-38044fb3a527

## Round ID:
[231246](https://scrubby.melonmesa.com/round/231246)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Cult Vs. Heretic: 7 Months Later Edition](https://www.github.com/tgstation/tgstation/pull/82877)

## Reproduction:

1) use traitor scalpel to get SM sliver
2) use traitor tongs to hold SM sliver
3) try to put sliver into container
4) get dusted

**Comment by Sadboysuss** [comment]
Amazing, how could this happen
