### ISSUE TITLE
Anesthetic internals leak

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#84408]
## Issue Summary
Reported by someone from discord, was told that taking the anesthetic tank off someone leaks the Anesthetic into the air, which I don't think is intended.

## Reproduction
Needs reproduction

**Comment by Inari-Whitebear** [comment]
Yeah, as far as I know this is intended. And the code just does this. It makes the "breathe out" emit into the atmosphere of the tile the player is on.

Don't think it's an issue directly even, just need an air scrubber or the normal scrubber to set it to be scrubbed

**Comment by iansdoor** [comment]
> As far as I can tell whenever this was brought up before it _is_ working "as intended" based on our game mechanics. Breath out does not return to the internals tank (or you would quickly get a CO2 tank). Anaesthetic is not metabolised by humans in a way that depletes it. Some anaesthetic is breathed back into the atmosphere.
> 
> Resultingly: trace amounts of anaesthetic start to exist in enclosed surgery rooms- not enough to put you to sleep but enough to make surgeons giggle as if they are some kind of mad scientist.

I'll mention that it was me that said in discord. The main reason I don't use the n2o mix tanks cause n2o leaks trigger RDS with regards of a hypnotic trace often.

**Comment by Sadboysuss** [comment]
That really sucks and I'd say this is an oversight. It just puts off people from using anesthetic tanks when we should be encouraging it instead.

**Comment by MrMelbert** [comment]
I disagree, surgical rooms should be better ventilated

**Comment by MrMelbert** [comment]
Or, if you wanted to go the extra mile, add a ventilator machine to medical, which can be used to
a. administer anesthesia
b. keep someone without functioning lungs / in hardcrit breathing (basically same effects as a breathing tube)
c. collect a patient's exhalation gases (co2 and n2o)
