### ISSUE TITLE
brig cell timer ui doesnt update

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#84424]
Reporting client version: 515.1640

## Round ID:
[231286](https://scrubby.melonmesa.com/round/231286)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)

## Reproduction:
1. press the timer stuff on the ui
2. it doesnt update

**Comment by Sadboysuss** [comment]
saw this on live servers too
