### ISSUE TITLE
Spy interaction with MODsuits

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#84434]
Reporting client version: 515.1639

## Issue Summary
A player reported that they couldn't steal the captain's MODsuit with their pen uplink as a spy

## Round ID:
[231299](https://scrubby.melonmesa.com/round/231299)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Some alt & ctrl click improvements](https://www.github.com/tgstation/tgstation/pull/84203)
- [Moves tool use back higher in the chain, but makes it so tool acts are only called on non-combat-mode](https://www.github.com/tgstation/tgstation/pull/84083)

## Reproduction:
1. have objective for stealing the captain's modsuit as a spy
2. attempt theft
3. fail

**Comment by Metekillot** [comment]
You have to crowbar out the storage and screwdriver it shut, yeah. Doesn't seem intended.

**Comment by Dawnseer** [comment]
Sounds like it works the same as trying to use a modsuit paintkit. For that you also have to remove the storage first and close it.
