### ISSUE TITLE
Space heaters drain charge ludicrously quick

### ISSUE THREAD

**Issue by OverwatchVoice** [tgstation/tgstation#84440]
Reporting client version: 515.1636

## Issue Summary

A default T1 space heater will last a singular tick or two when activated. Higher tiers will be lucky to last 30-40 seconds.
## Round ID:
[231307](https://scrubby.melonmesa.com/round/231307)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Some alt & ctrl click improvements](https://www.github.com/tgstation/tgstation/pull/84203)
- [Moves tool use back higher in the chain, but makes it so tool acts are only called on non-combat-mode](https://www.github.com/tgstation/tgstation/pull/84083)

## Reproduction:
Self-explanatory.

**Comment by SyncIt21** [comment]
This was just fixed by #84360

**Comment by necromanceranne** [comment]
It's possible that whatever server this was on hasn't been updated to accommodate the new code. It is also possible, if it has been updated, that the actual required amount of power needed to adjust some extreme temperatures is enough to overwhelm roundstart powercells.

**Comment by Sadboysuss** [comment]
> if it has been updated, that the actual required amount of power needed to adjust some extreme temperatures is enough to overwhelm roundstart powercells.

they mentioned bluespace cells too so I don't think so.

**Comment by Sadboysuss** [comment]
if this still appears after the server updates its code - comment and I'll remove the cleanup flag

**Comment by OverwatchVoice** [comment]
> if this still appears after the server updates its code - comment and I'll remove the cleanup flag

Tested on tg/manuel. Issue is still very much there

**Comment by necromanceranne** [comment]
Well the servers not been updated so that's why.

**Comment by OverwatchVoice** [comment]
Power drain is managable, but the actual effectiveness of space heaters is still abysmal, not even T4s make a noticable dent in minor temperature offsets
