### ISSUE TITLE
Icebox escape pods don't actually save you from the nuke

### ISSUE THREAD

**Issue by GPeckman** [tgstation/tgstation#84450]
Reporting client version: 515.1637

## Issue Summary

As the title says. The pod launched just fine, but I died from the nuke anyways.

## Round ID:
[231314](https://scrubby.melonmesa.com/round/231314)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)

## Reproduction:

1. Be on icebox.
2. Delta alert.
3. Try to escape on a pod.
4. The pod launches, but you die anyways.

**Comment by rasepretep** [comment]
Isn't it that specifically on Icebox, the whole planetoid gets nuked, so there actually isn't anywhere you could survive?

**Comment by Sadboysuss** [comment]
there is no lavaland below, just the wastes, seems intended to me.

**Comment by AdipemDragon** [comment]
it IS possible to do it, but you just have to time it so that the pod is in transit as the nuke goes off, thus parrying the explosion

**Comment by Potato-Masher** [comment]
Honestly I thought the only way to survive it was to go to the lowest level on icebox, but that's just from memory
