### ISSUE TITLE
Ore vents resist chasming, but their boulders don't

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#84463]
Reporting client version: 515.1640

## Issue Summary
If you can somehow get an orevent to be close enough to a tendril and it collapses, then the vent becomes un-viale, albeit fully functional, if chasm'd, since the boulders just drop down instantly.

## Round ID:
[231335](https://scrubby.melonmesa.com/round/231335)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Some alt & ctrl click improvements](https://www.github.com/tgstation/tgstation/pull/84203)
- [Moves tool use back higher in the chain, but makes it so tool acts are only called on non-combat-mode](https://www.github.com/tgstation/tgstation/pull/84083)

## Reproduction:
Sink the ground under a vent:
![image](https://github.com/tgstation/tgstation/assets/76874615/729a705a-1c08-4d86-9ce4-3e51390f24f2)

**Comment by SyncIt21** [comment]
I feel like we want ore vents to be chasm proof. There are only 15 ore vents in lava land and if players could destroy them this way it would be grieving

**Comment by ArcaneMusic** [comment]
Ideally, we should just make the turf a chasm is on protected via the tendril drop, yeah. That's a mistake on my part.

**Comment by Dawnseer** [comment]
Time to fish up some boulders
