### ISSUE TITLE
[Administration] "Job Playtime Exempt" option non-functional.

### ISSUE THREAD

**Issue by OverwatchVoice** [tgstation/tgstation#84478]
Reporting client version: 515.1636

## Issue Summary

A new account has most jobs unavailable, requiring a set amount of hours played or a timed delay. An administrator is meant to be able bypass this option for other players. This feature is broken.
https://cdn.discordapp.com/attachments/705679956021215264/1256726059202641950/image.png?ex=6681d0d9&is=66807f59&hm=99020af6e0105a780f5e4148888727ee21d21addb5ab700088924c17e52886fe&

## Round ID:
[231353](https://scrubby.melonmesa.com/round/231353)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Moves tool use back higher in the chain, but makes it so tool acts are only called on non-combat-mode](https://www.github.com/tgstation/tgstation/pull/84083)

**Comment by optimumtact** [comment]
broken how?

**Comment by OverwatchVoice** [comment]
> broken how?

Should've clarified; It just doesn't work for timed delays

**Comment by san7890** [comment]
your image broke, can you upload it directly to github? discord tends to date links quickly so people don't abuse them as a CDN
