### ISSUE TITLE
New blood loss knocks you out even at 80%

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#84496]
Reporting client version: 515.1639

## Issue Summary
Having 80% of your blood drops you to 40 oxygen damage and knocks you out. I suspect this is due to how old blood loss worked and knocked you out when you had around 40 oxygen damage.

## Round ID:
[231397](https://scrubby.melonmesa.com/round/231397)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Moves tool use back higher in the chain, but makes it so tool acts are only called on non-combat-mode](https://www.github.com/tgstation/tgstation/pull/84083)

## Reproduction:
1. Bring blood down to 70-80%
2. Get knocked out

**Comment by carlarctg** [comment]
Might be I underestimated how much damage LOSEBREATH does?

**Comment by Sadboysuss** [comment]
> Might be I underestimated how much damage LOSEBREATH does?

players that use the blood deficiency quirk also reported that they just die

**Comment by GPeckman** [comment]
Is this fixed by #84476?

**Comment by Sadboysuss** [comment]
> Is this fixed by #84476?

it could be, I'm not sure if Manuel has been updated yet

**Comment by Sadboysuss** [comment]
Twas fixed
