### ISSUE TITLE
Paint kit right click doesn't work on Modsuits with storage

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#84490]
## Issue Summary

See title, paint kits are unable to recolour modsuits via right click, if the modsuit has storage

## Round ID:

Issue report from https://github.com/Bubberstation/Bubberstation

## Reproduction:

This seems to be due to a change after combat mode was made more needed to use tools on modsuits.
Paint kits can change modsuit skins (left click) but right click does nothing if the modsuit has a storage module (it just opens storage)

**Comment by SmArtKar** [comment]
The level of heck is worse than reported, left click does not seem to work either?
