### ISSUE TITLE
 trichromatic larynx spans get stammered

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#84509]
## Issue Summary
Trichromatic larynx stammered text exposes the html.
Befriends-The-Things stammers, "<-<sp-pan-n c-cl-las-s-s-ss=-='g-gr-r-reen-n'>->t-th-hat-ts-sss-s<-</-/s-span-n-n> <-<s-s-s-sp-pan-n-n c-c-cl-lass-s-s='g-gr-reen-n-n'>not<-</-/s-sp-p-p-pan-n>->-> <-<-<-<span c-class-s-s=-='gr-reen'>->s-ss-ss-sup-p-pos-ss-ss-sed-d<-</-/s-s-sp-p-pan> <-<s-span-n-n c-class=-='red-d'>->->t-to<-<-<-</-/-/s-sp-pan-n>-> <-<sp-p-p-pan-n-n-n c-cl-las-ss=-=-=-='gr-reen-n'>->h-hap-pp-pen!<-<-</-/s-s-sp-p-p-pan-n-n-n>->"

## Round ID:
[231405](https://scrubby.melonmesa.com/round/231405)

## Reproduction:
1. Get the larynx
2. stammer

**Comment by necromanceranne** [comment]
@carlarctg

**Comment by optimumtact** [comment]
you can't embed span classes into any kind of say message until the moment it's actually rendered, (see how the radio classes work).

Which poses a real problem for how this mutation is meant to work.

**Comment by DaxDupont** [comment]
I am usually on the improve and not remove side but euh, this is a visual nightmare and disruptive so if there's no proper way to fix it, reverting it might make more sense

**Comment by Sadboysuss** [comment]
https://github.com/tgstation/tgstation/pull/84515
