### ISSUE TITLE
Attacking AI's as a wraith (construct) proved to be useless

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#84508]
Reporting client version: 515.1639

## Issue Summary
I teleported into the AI sat and tried to attach the AI on combat mode but it did nothing.

## Round ID:
[231405](https://scrubby.melonmesa.com/round/231405)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Moves tool use back higher in the chain, but makes it so tool acts are only called on non-combat-mode](https://www.github.com/tgstation/tgstation/pull/84083)

## Reproduction:
1. Be a wraith (cult construct)
2. Attempt to attack the AI.

**Comment by lizardqueenlexi** [comment]
Couldn't reproduce on a local server. As a wraith I was able to beat the AI to death just fine.
![image](https://github.com/tgstation/tgstation/assets/105025397/1e317249-c7e1-48b0-8534-088662a6b0ba)

Wraiths shouldn't have anything special about their attacks that would cause them to fail, so I'm not sure what caused this.
