### ISSUE TITLE
Inventory UI bug with storage items

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#84507]
Reporting client version: 515.1639

## Issue Summary
![image](https://github.com/tgstation/tgstation/assets/96586172/639755f1-dd4e-47cd-b289-cd51c9329856)

## Round ID:
[231405](https://scrubby.melonmesa.com/round/231405)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Moves tool use back higher in the chain, but makes it so tool acts are only called on non-combat-mode](https://www.github.com/tgstation/tgstation/pull/84083)

## Reproduction:
Not sure how to reproduce

**Comment by Metekillot** [comment]
I saw something similar to this in my testing for stuff whenever Cross, Crossed, and get_equipment() were getting called, so that's probably a good place to look if this starts happening frequently.

**Comment by Sadboysuss** [comment]
Ok I just saw this bug with a modsuit and the UI wouldn't update so if I took an item out and put it back in, it wouldn't show up in the inventory, only fixed it by removing the storage module

**Comment by necromanceranne** [comment]
If you encounter this bug, the solution is to empty the contents of the storage by dumping the contents, accessing a separate storage/close the current storage you can access that is rendering, and then refilling the buggy storage container it again. It should re-render the background once again and things should go back to normal.

**Comment by Sadboysuss** [comment]
coming back with more information on this: The UI gets stuck specifically for the item, you can put items into or out of the bag, but the UI won't update. secondarily, this is not client-specific and other players can inspect your bag to see the same bug.

**Comment by plutori** [comment]
Just commenting to confirm that this is the same bug I saw in #84968

**Comment by Sealed101** [comment]
dupe #85259 closed by https://github.com/tgstation/tgstation/pull/86842
