### ISSUE TITLE
Being a slime person with the new anomaly heart kills you when falling into crit.

### ISSUE THREAD

**Issue by whatisthisplace** [tgstation/tgstation#84519]
## Issue Summary
Having the new voltaic heart implanted into a slime will kill you as it constantly deals toxin damage in an attempt to revive you

## Round ID:
N/A I did this on local to play test it

## Reproduction:
Become slime
Install voltaic heart
Watch as you steadily gain toxin damage and lose blood
Lose all your limbs and die

https://github.com/tgstation/tgstation/assets/78915563/aad42152-02a3-47f4-ac6c-6fe889545cdb

**Comment by EnterTheJake** [comment]
Not a bug, slimes take toxin damage whenever they heal toxin damage, the heart status heals a bit of everything upon entering into crit including toxin.

**Comment by Sadboysuss** [comment]
This is just like miners exploding if you put a T3 cybernetic heart in them, technically not a bug 😉

**Comment by SyncIt21** [comment]
You can also add an cleanup flag.
