### ISSUE TITLE
No longer able to use portable scrubber directly from under holofan

### ISSUE THREAD

**Issue by Deadgebert** [tgstation/tgstation#84539]
## Issue Summary

[This PR](https://github.com/tgstation/tgstation/pull/84412) made it so portable scrubbers no longer scrub gas directly under holofans
Expected behavior is to scrub the 1x1 under holofan and nothing extra
![d922f1c431454e2fc178d4259c2d2e0f](https://github.com/tgstation/tgstation/assets/109347230/86aa7e4e-a99c-47a1-b097-5c311ed80cc8)

## Round ID: 
[231433](https://scrubby.melonmesa.com/round/231433)

## Reproduction:

> Place portable scrubber under holofan
> Does nothing

**Comment by mc-oofert** [comment]
holofans are not atmos adjacent turfs

**Comment by Deadgebert** [comment]
non portable scrubbers behave exactly as described.

**Comment by Sadboysuss** [comment]
> holofans are not atmos adjacent turfs

the issue here is that you used to be able to, and now that functionality is lost.
