### ISSUE TITLE
Transparent Kudzu becomes 100% invisible

### ISSUE THREAD

**Issue by General-Gaston** [tgstation/tgstation#84537]
## Issue Summary
In round id 231440, a patch of kudzu spawned. It was perfectly normal until it branched off and suddenly turned all of the mutations of it completely invisible. There's no way to see the kudzu other than using the Alt menu or by right clicking

![dreamseeker_4xc4ue37LL](https://github.com/tgstation/tgstation/assets/90655347/745850f2-fbd3-436e-af4f-60fe1fc93e36)
![dreamseeker_L1I43lOyJ8](https://github.com/tgstation/tgstation/assets/90655347/ccea748e-e37e-4b31-98f0-eb7df7c9bcb4)

## Round ID: 

[231440](https://scrubby.melonmesa.com/round/231440)

## Testmerges:

Round ID: [231440](https://scrubby.melonmesa.com/round/231440)
BYOND Version: 515.1637
Server revision compiled on: 2024-07-01T06:49:36+00:00
Master commit: [8c605d151dc81da39515db23a9ecefca28c8c58f](https://www.github.com/tgstation/tgstation/commit/8c605d151dc81da39515db23a9ecefca28c8c58f)
The following pull requests are currently test merged:
[#83227: '[TM ONLY] Hijacked Revision Date for v3 TGS Api' by ZephyrTFA at commit 8575d21082](https://www.github.com/tgstation/tgstation/pull/83227)
[#83860: 'Allows for proxy atoms in object melee attack chain' by SyncIt21 at commit 39c3aca2f5](https://www.github.com/tgstation/tgstation/pull/83860)
[#84097: 'New Traitor mech: Justice.' by Xackii at commit 595b0ad524](https://www.github.com/tgstation/tgstation/pull/84097)
[#84350: 'Flattens The Floor Plane' by LemonInTheDark at commit 872c505050](https://www.github.com/tgstation/tgstation/pull/84350)

## Reproduction:

Wait for Kudzu to mutate, watch it become entirely invisible.

**Comment by Sadboysuss** [comment]
![image](https://github.com/tgstation/tgstation/assets/96586172/6d25d4ef-df68-45f6-8c1a-d6f9b4d27297)

Indeed

**Comment by the-orange-cow** [comment]
Oh, the hijinks that could be done with this...

**Comment by LemonInTheDark** [comment]
I do not know what the fuck is going on here

**Comment by LemonInTheDark** [comment]
handled
