### ISSUE TITLE
CNS Rebooter Is not activating on stam crit.

### ISSUE THREAD

**Issue by EnterTheJake** [tgstation/tgstation#84561]
## Issue Summary
CNS Rebooter no longer activates upon reaching stamcrit, still works on paralyze i tested it.

## Round ID:
https://scrubby.melonmesa.com/round/231459

## Testmerges:
Doesn't seem related to TM, i'm fairly sure.

## Reproduction:

Get stamcritted while having a CNS installed, cry as it doesn't activate.

**Comment by Metekillot** [comment]
It has a cooldown and activates on immobilize, paralyze, and stun, even if the stun is barely a second log. Please find in the logs where it didn't activate and I'll take a look though

**Comment by EnterTheJake** [comment]
> It has a cooldown and activates on immobilize, paralyze, and stun, even if the stun is barely a second log. Please find in the logs where it didn't activate and I'll take a look though

![image](https://github.com/tgstation/tgstation/assets/102721711/5006a59f-cadb-47ff-9a60-5cb0d56b82c8)

It used to also take you out of stamcrit, i know because i reworked it to be that way, this is the code, if someone wants to fix it before i do.

**Comment by Metekillot** [comment]
I'm saying it's possible you suffered a brief stun that it pulled you out of and activated the cooldown for. From the code, I saw that you called stamcrit recovery (hard setting stam loss to 0) on a callback? I implemented a component that would probably work better for the subsequent intended stun and stam loss resistance; not a bug per se but looks like it could be a design oversight

**Comment by Metekillot** [comment]
But I am also out and about lol but I could use the GBP

**Comment by EnterTheJake** [comment]
> I'm saying it's possible you suffered a brief stun that it pulled you out of and activated the cooldown for. From the code, I saw that you called stamcrit recovery (hard setting stam loss to 0) on a callback? I implemented a component that would probably work better for the subsequent intended stun and stam loss resistance; not a bug per se but looks like it could be a design oversight

Not an oversight, it was working just fine until a week ago, i used the implant several times.
