### ISSUE TITLE
Wawa Chemistry Signage for their little lab

### ISSUE THREAD

**Issue by iansdoor** [tgstation/tgstation#84565]
There ain't no dam signs to know where the chemistry factory is. 
But the main chemistry part has no tools yet plumbing device and 5 stacts of duct and metal
![Screenshot_652](https://github.com/tgstation/tgstation/assets/109386467/ca03bf8d-fd4b-48b9-b061-7cf6577fbece)
![image (4)](https://github.com/tgstation/tgstation/assets/109386467/f8c4ceaa-4e91-4cff-b060-c2909e11d848)
.

**Comment by Sadboysuss** [comment]
![image](https://github.com/tgstation/tgstation/assets/96586172/e20b0748-077c-4d85-ab6c-f1e0feb05e8f)

I don't think it's too much of an issue as there is a navigate verb to it but I guess it could use some more sign pointers or something.

**Comment by iansdoor** [comment]
> ![image](https://private-user-images.githubusercontent.com/96586172/344915049-e20b0748-077c-4d85-ab6c-f1e0feb05e8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MjQyMTksIm5iZiI6MTcxOTkyMzkxOSwicGF0aCI6Ii85NjU4NjE3Mi8zNDQ5MTUwNDktZTIwYjA3NDgtMDc3Yy00ZDg1LWFiNmMtZjFlMGZlYjA1ZThmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDEyMzgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NjNkNjVmZDg5NDZkZWQwZDNkMmNkYjUyNjNmMWIwZTI1NzE2NjRhNWU5YWFjNGVhOWIwYTMyMTIwNjAwMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5jQ6aAL1f33rvM_ovsMY3tX8BpyfVQJvU4uK4QLKZw4)
> 
> I don't think it's too much of an issue as there is a navigate verb to it but I guess it could use some more sign pointers or something.

I did not think about that. I just laughed that plumbing tool in the small area and out of all my rounds of observing, I see factories built into the walking areas. A sign and some flooring would be excellent, even a window.
