### ISSUE TITLE
Birdshot revamp rework service

### ISSUE THREAD

**Issue by iansdoor** [tgstation/tgstation#84564]
I believe someone has mentioned wires not being set down. they did not. So medical is still out of power. The park which looks really nice, makes chasms when exploded. Same issue with trams monkey room. All about that base turf jungle.

Two issues.
lack of wires
jungle base turf is chasms

![Screenshot_657](https://github.com/tgstation/tgstation/assets/109386467/a972757e-c321-43d2-bd97-0ae2cd968a23)

**Comment by Sadboysuss** [comment]
Fixed by https://github.com/tgstation/tgstation/pull/84571
