### ISSUE TITLE
Photographs are basically nonfunctional (Definitely a testmerge bug)

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#84560]
Reporting client version: 515.1640

## Issue Summary

![image](https://github.com/tgstation/tgstation/assets/40847847/a3084258-bec2-40a9-815f-e485177057bb)

## Round ID:
[231459](https://scrubby.melonmesa.com/round/231459)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Allows for proxy atoms in object melee attack chain](https://www.github.com/tgstation/tgstation/pull/83860)
- [New Traitor mech: Justice.](https://www.github.com/tgstation/tgstation/pull/84097)
- [Flattens The Floor Plane](https://www.github.com/tgstation/tgstation/pull/84350)

## Reproduction:

Take a picture. The map in question was a multi-z map, so it is worth testing on both normal and multi-z.

**Comment by Sadboysuss** [comment]
most likely https://github.com/tgstation/tgstation/pull/84350

**Comment by LemonInTheDark** [comment]
oh my god come on

**Comment by LemonInTheDark** [comment]
![image](https://github.com/tgstation/tgstation/assets/58055496/65c1ea3f-b36f-4ea2-b17d-c6a01c49de1f)

there we go, wasn't dealing with plane properly

**Comment by Sadboysuss** [comment]
> ![image](https://github.com/tgstation/tgstation/assets/58055496/65c1ea3f-b36f-4ea2-b17d-c6a01c49de1f)
> 
> there we go, wasn't dealing with plane properly 

That firelock looks a bit funny

**Comment by LemonInTheDark** [comment]
![345427424-601b422c-f6aa-42ba-bcd9-b1faebe236e3](https://github.com/tgstation/tgstation/assets/58055496/d4e90e52-6645-4672-98e8-dafb8d8dd9ad)
Fixed, also you baited me into adding lighting to photos

**Comment by necromanceranne** [comment]
feature get
