### ISSUE TITLE
Setting custom font in chat bluescreens it

### ISSUE THREAD

**Issue by kawaiinick** [tgstation/tgstation#84593]
## Issue Summary

When i set custom chat font in the settings it gets bluescreened
![image](https://github.com/tgstation/tgstation/assets/104280915/b0997a09-227e-4e01-966f-09ec64d8522e)

## Reproduction:
1.Open chat settings
2.Try setting custom font

**Comment by jlsnow301** [comment]
doing this on manuel, live
![image](https://github.com/tgstation/tgstation/assets/42397676/ad0631c6-01dc-41a6-afcc-2a467b78a6ba)

can you lend some more details about your setup? OS, server (if different)?

**Comment by kawaiinick** [comment]
Changing to one of the default fonts works fine yes. But i'm talking about custom font feature
https://www.youtube.com/watch?v=dOShc29JPlo&ab_channel=kawaiinick

**Comment by jlsnow301** [comment]
Ah I see. You're correct
