### ISSUE TITLE
Raptors get spooked by watchers and demonic watchers.

### ISSUE THREAD

**Issue by MortoSasye** [tgstation/tgstation#84596]
## Issue Summary

Raptors are spooked by watchers/demonic watchers, throwing off whoever is on top of them and rendering them useless for combat in that regard.

Pretty sure this happened because of: https://github.com/tgstation/tgstation/pull/84306 so I'm not sure if it was intended or an oversight.

Behold the consequences of being thrown by your raptor while on a plasma lake:

![image](https://github.com/tgstation/tgstation/assets/38175176/221578f6-f862-402c-a065-97856b7158bb)

## Round ID:

Happened in Nova, a downstream of /tg/, but it should be easy enough to recreate regardless of a round ID I believe.

Codebase: https://github.com/NovaSector/NovaSector

## Reproduction:

- Acquire a raptor.
- Go with your raptor to WAR against the beasts of lavaland.
- Get shot by a watcher/demonic watcher.
- Get thrown out of your bird at match speed, which means death if you were fighting on either planet's lava/plasma rivers.

**Comment by Iamgoofball** [comment]
reproduce it on /tg/

**Comment by MortoSasye** [comment]
> reproduce it on /tg/

![image](https://github.com/tgstation/tgstation/assets/38175176/f68cccde-3aa8-4905-addb-7c2cc822097c)

This is happening to /tg/ players too, as displayed above, which was commented on the mentioned pr.

**Comment by Sadboysuss** [comment]
https://github.com/tgstation/tgstation/issues/84655
