### ISSUE TITLE
Reagent containers are totally immune to fire damage

### ISSUE THREAD

**Issue by Metekillot** [tgstation/tgstation#84592]
## Issue Summary

There's a double define on them for fire act but the second one is newer and just does what the first one does without inheriting parent behavior, so they don't take fire damage from anything at all

## Round ID:

N/a I just remember this

## Reproduction:

Put anything that's a child of reagent container in a fire; including wood
Witness miracles

**Comment by the-orange-cow** [comment]
https://m.youtube.com/watch?v=K51yvpSX2mA
