### ISSUE TITLE
My welding helmet is a swiss army knive.

### ISSUE THREAD

**Issue by iansdoor** [tgstation/tgstation#84598]
There is an inconsistency in welding helmet. Armor isn't lower up or down.

When the helmet is up, This thing blocks pepperspray and not facehuggers

![mask up](https://github.com/tgstation/tgstation/assets/109386467/7fc613ed-a043-435c-ac7a-150d77a83b90)
![Screenshot_675](https://github.com/tgstation/tgstation/assets/109386467/4de9157c-4ad7-4375-b35b-9cdfc2e374e4)

When the helmet is down. This thing blocks facehuggers and not pepper spray.

![mask down](https://github.com/tgstation/tgstation/assets/109386467/cd8cd3ca-022a-4901-9f4a-918759994d11)
![Screenshot_676](https://github.com/tgstation/tgstation/assets/109386467/7ab2432b-2d88-4fbb-8a7f-404c6dbc7961)

**Comment by Sadboysuss** [comment]
Fixed by https://github.com/tgstation/tgstation/pull/84742
