### ISSUE TITLE
xenos cannot eat people

### ISSUE THREAD

**Issue by arnociiroc** [tgstation/tgstation#84608]
## Issue Summary
xenos cannot eat people, trying both grab states and with combat mode on and off only opens the strip menu
## Round ID:

[231539](https://scrubby.melonmesa.com/round/231539)

## Testmerges:

[#83227: '[TM ONLY] Hijacked Revision Date for v3 TGS Api' by ZephyrTFA at commit 8575d21082](https://www.github.com/tgstation/tgstation/pull/83227)

## Reproduction:

Aggro grab person/body
Drag to self on either combat/non combat mode
strip menu opens and no eats

**Comment by Sadboysuss** [comment]
We've been meaning to remove the xeno vore feature for a while. Even if there wasn't a pr merged that did this, it would be much better if we called this intended.

**Comment by ArcaneDefence** [comment]
>We've been meaning to remove the xeno vore feature for a while

Says fuckin' who

**Comment by Sadboysuss** [comment]
> >We've been meaning to remove the xeno vore feature for a while
> 
> Says fuckin' who

It's been talked about a lot in coding general
![Screenshot_20240703_183109_Discord.jpg](https://github.com/tgstation/tgstation/assets/96586172/cd9a4b7c-f8dd-4bb0-9b30-6a86a25f5ff6)

![Screenshot_20240703_183139_Discord.jpg](https://github.com/tgstation/tgstation/assets/96586172/2e7a4f3e-c360-40e0-af96-289b11fef60b)

**Comment by moocowswag** [comment]
Wasnt xeno vore readded by a maintainer?

**Comment by LemonInTheDark** [comment]
> It's been talked about a lot in coding general 

These posters are cowards and also lack the will to enact their dreams.

**Comment by Rhials** [comment]
I reckon this is closed by #84916
