### ISSUE TITLE
Birdshot's space emitters have issues with the catwalks/railings

### ISSUE THREAD

**Issue by Inari-Whitebear** [tgstation/tgstation#84612]
## Issue Summary

Birdshot has two emitters, the inside one and the ones outside (just outside the airlock northwest of the Supermatter).
Now that's a neat idea, but the outside ones kinda don't work easily:

* They are on catwalks, Maybe I'm just being dumb, but I couldn't find a way to anchor them to those (wrench/welder). So when I try to use them I basically have to snip the catwalk, put down a plating, then put the wire back down (that cut destroyed when snipping the catwalk) and then I can finally anchor the emitters.
Since unanchored emitters can't be turned on, this isn't great.
* There are railings around. Once I finally set up the emitters their first few shots destroy the railing on the tile of the reflectors and the tiles on (or maybe adjacent to) the emitters. Also not great.

**Comment by Sadboysuss** [comment]
closed by https://github.com/tgstation/tgstation/pull/84697
