### ISSUE TITLE
Mod paint kit fails

### ISSUE THREAD

**Issue by SpaceLoveSs13** [tgstation/tgstation#84620]
## Issue Summary

Mod paint kit cant re-skin or repaint modsuits. Which was based on left and right click respectively. This is happening despite the previous fix pr mentioned in #83442 

This seems to be happening due to the combat mode and dehardcoding of modsuits.

## Round ID:

NA

## Testmerges:

NA(Happens Locally as well)

## Reproduction:

1.  Print Modsuit paint kit
2. Try left clicking on modsuit, try right clicking, neither works.
3. Repeat step 2 with combat mode & Alt(see my run/walk change) on. Nothing.
4. Test on other modsuits. Nothing.

https://github.com/tgstation/tgstation/assets/68121607/13cc834b-fda2-4f33-b38c-1bcb9dc6cfd6

**Comment by CliffracerX** [comment]
Issue here is likely stemming from #82656 or one of the subsequent interaction refactors - MOD paint kits likely aren't properly asserting themselves in the click chain and so inventory & other functions end up taking precedence.

**Comment by SpaceLoveSs13** [comment]
> Issue here is likely stemming from #82656 or one of the subsequent interaction refactors - MOD paint kits likely aren't properly asserting themselves in the click chain and so inventory & other functions end up taking precedence.

I believe this is also true for Bluespace RPED. That thing is broken too for Remote piping Just to add.
