### ISSUE TITLE
Rev deconverted via mindshield kept rev hud

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#84645]
Reporting client version: 515.1633

## Round ID:
[231618](https://scrubby.melonmesa.com/round/231618)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)

## Reproduction:
Be rev, get mindshielded, keep hud. Reported by a player, reproduced in tdome.

**Comment by san7890** [comment]
I think this was fixed in https://github.com/tgstation/tgstation/pull/84704 surprisingly
