### ISSUE TITLE
Going up a z-level with mesons on hides your UI behind floor layer

### ISSUE THREAD

**Issue by Deadgebert** [tgstation/tgstation#84661]
## Issue Summary

If mesons are equipped on a lower z-level, the UI is hidden behind the floor layer when you go up a z-level
![ec1f7145f8877eddcfad589285f42846](https://github.com/tgstation/tgstation/assets/109347230/9596ad00-ebb4-4992-9ad1-b1129176b395)

if mesons are equipped at the highest z-level, everything seems to work fine and stays fine, even moving across z-levels

## Round ID: 
[231637](https://scrubby.melonmesa.com/round/231637)

## Testmerges:
[#83227: '[TM ONLY] Hijacked Revision Date for v3 TGS Api' by ZephyrTFA at commit 8575d21082](https://www.github.com/tgstation/tgstation/pull/83227)
[#84184: 'Offset render relays for non-offsetting planes to match highest matching render plane' by 00-Steven at commit aa0337019e](https://www.github.com/tgstation/tgstation/pull/84184)
[#84601: 'tgui: custom font bluescreen fix, typescript'd' by jlsnow301 at commit f57e98fa62](https://www.github.com/tgstation/tgstation/pull/84601)

## Reproduction:
Equip engineering scanning goggles on meson mode or mesons
walk up stairs

**Comment by LemonInTheDark** [comment]
Issue with https://github.com/tgstation/tgstation/pull/84184, closing as it is a TM bug
