### ISSUE TITLE
Cant craft a singularity hammer normally

### ISSUE THREAD

**Issue by rageguy505** [tgstation/tgstation#84664]
Reporting client version: 515.1637

## Issue Summary
You cant craft a singularity hammer with the default SM on the station, which is /obj/machiner/power/supermatter_crystal/engine.
But /obj/machiner/power/supermatter_crystal/ works, which is impossible to get.

## Round ID:
[231642](https://scrubby.melonmesa.com/round/231642)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Offset render relays for non-offsetting planes to match highest matching render plane](https://www.github.com/tgstation/tgstation/pull/84184)
- [tgui: custom font bluescreen fix, typescript'd](https://www.github.com/tgstation/tgstation/pull/84601)

**Comment by rageguy505** [comment]
from 84194

**Comment by rageguy505** [comment]
or uhh #84194

**Comment by rageguy505** [comment]
i dont know if the guy wanted to be craftable with SM subtypes like the shard or just the main SM engine

**Comment by Sadboysuss** [comment]
It should be working for subtypes but looks like it doesn't work cause there is an extra `/` at the end?

**Comment by Mothblocks** [comment]
Not relevant

![image](https://github.com/tgstation/tgstation/assets/35135081/e3edac3b-52e8-4a79-9540-43fd5433a52b)

**Comment by Iamgoofball** [comment]
every other part of crafting accepts subtypes
i trusted our systems for consistency and they failed me yet again

**Comment by LemonInTheDark** [comment]
goofcrafting, you cannot craft the thing
