### ISSUE TITLE
pepper spray is paralyzing people

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#84679]
Reporting client version: 515.1639

## Issue Summary
When pepper spray shoulders activated on a sec mod it paralyzed me completely
I don't think this is intended

## Round ID:
[231662](https://scrubby.melonmesa.com/round/231662)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Offset render relays for non-offsetting planes to match highest matching render plane](https://www.github.com/tgstation/tgstation/pull/84184)
- [tgui: custom font bluescreen fix, typescript'd](https://www.github.com/tgstation/tgstation/pull/84601)

## Reproduction:
1. Get pepper sprayed
2. notice how you can't move

**Comment by projectkepler-ru** [comment]
are you sure you're completely paralysed?

**Comment by Sadboysuss** [comment]
> are you sure you're completely paralysed?

it completely paralyzed me when I got sprayed with the secMOD module

**Comment by SmArtKar** [comment]
Cannot reproduce at all?
