### ISSUE TITLE
MK-II honk prototype shoes can't accept bananium

### ISSUE THREAD

**Issue by nukularpower** [tgstation/tgstation#84689]
Not sure what changed, but the mk-ii honk prototype clown combat shoes (from the clown ship space ruin - not sure I actually got the name right)  can no longer accept bananium, making them functionally useless.    Tested with both forms of bananium, neither works - get message that it "does not fit".

Round ID:  Forgot sorry, tried it last nite, though doubt it's relevant in this case

no idea how to put the bug tag on either

**Comment by Sadboysuss** [comment]
Likely attack chain

**Comment by Sealed101** [comment]
closed by #87676
