### ISSUE TITLE
You no longer need to breathe.

### ISSUE THREAD

**Issue by FlufflesTheDog** [tgstation/tgstation#84698]
## Issue Summary
Post #84529, if you do not have internals enabled, you will not need to breathe. Turning on your internals will resume the need to breathe.

## Round ID:
Local on [master](https://github.com/tgstation/tgstation/commit/a13d142badbcdd9663bbd650c81495f2aa8657d8), no runtimes

## Reproduction:
Walk into space
Forget internal tank
- Die, but without taking oxygen damage (no suit)
- Don't die (suit)

**Comment by EuSouAFazer** [comment]
Fuckup of the year candidate

**Comment by TheVekter** [comment]
@dragomagol you're doing god's work, thank you

**Comment by DATA-xPUNGED** [comment]
> Fuckup of the year candidate

How do I even come back from this my coding career is over
