### ISSUE TITLE
Humanized syndicate monkey reinforcements go go go.

### ISSUE THREAD

**Issue by iansdoor** [tgstation/tgstation#84701]
Issue Summary:
So they were added back in here
https://github.com/tgstation/tgstation/pull/79012

The current issue with them now is You can freely give mutadone to humanize the monkey person, gaining 3 humans that are loyal to you and are no longer bound by monkey things.

Round ID: [231685](https://scrubby.melonmesa.com/round/231685)

**Comment by carlarctg** [comment]
wtf

**Comment by Sadboysuss** [comment]
https://github.com/tgstation/tgstation/pull/83720 fixed this I think? I'll let you respond if you think otherwise and I misunderstood something
