### ISSUE TITLE
You may transfer martial arts to all your slime clones.

### ISSUE THREAD

**Issue by iansdoor** [tgstation/tgstation#84703]
Round ID: 231687

Basically, The bug itself is that holding Krav gloves on your main slime or any of them, and that slime host dies. The next slime host has the ability to use Krav martials without needing to wear the gloves.

Actually, there may be a bigger issue that all spells and martial arts work like by transferring your brain around after a body death. Where you keep the abilities of the previous.

**Comment by SyncIt21** [comment]
Close this in favour of #84710
