### ISSUE TITLE
Living limb limbs can interact with ghosts (or any invisible movable)

### ISSUE THREAD

**Issue by norsvenska** [tgstation/tgstation#84709]
Reporting client version: 515.1641

## Issue Summary
![image](https://github.com/tgstation/tgstation/assets/73006946/ac9ac494-cd39-477b-8665-6ab35dae8d21)
Cletus Smith, a living person who has a meat arm (makes him automatically feel things) had it trigger on me, a ghost. Not quite sure how to explain it

## Round ID:
[231709](https://scrubby.melonmesa.com/round/231709)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Offset render relays for non-offsetting planes to match highest matching render plane](https://www.github.com/tgstation/tgstation/pull/84184)
- [tgui: custom font bluescreen fix, typescript'd](https://www.github.com/tgstation/tgstation/pull/84601)

**Comment by MrMelbert** [comment]
`Cletus Smiths the meat right arm`

**Comment by dalmationer** [comment]
extremely funny
