### ISSUE TITLE
Blood filters don't work all the way

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#84716]
Reporting client version: 515.1639

## Issue Summary

https://github.com/tgstation/tgstation/assets/96586172/fdd0a2cd-4f1b-4e38-9c17-833382502eed

Continuously doing blood filter on a person eventually doesn't filter out the last bits of the reagents, resulting in the above video.

## Round ID:
[231713](https://scrubby.melonmesa.com/round/231713)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Offset render relays for non-offsetting planes to match highest matching render plane](https://www.github.com/tgstation/tgstation/pull/84184)
- [tgui: custom font bluescreen fix, typescript'd](https://www.github.com/tgstation/tgstation/pull/84601)

## Reproduction:
Use blood filter surgery

**Comment by Vect0r2** [comment]
Not a bug the code for removing reagents either gets rid of 10 or like 20% whichever is smaller.

**Comment by SyncIt21** [comment]
> Not a bug the code for removing reagents either gets rid of 10 or like 20% whichever is smaller.

Well it depends on how we judge this code

https://github.com/tgstation/tgstation/blob/371e929236b0f8084c5e03fa01edf391ba037841/code/modules/surgery/blood_filter.dm#L71

not sure what the logic behind the math is

**Comment by 00-Steven** [comment]
gonna say it's probably best to just put a lower cap on it so how much a step removes doesn't approach zero or in this case is zero

**Comment by Sadboysuss** [comment]
> Not a bug the code for removing reagents either gets rid of 10 or like 20% whichever is smaller.

for 4 ticks the reagents didn't move and wouldn't move anymore

**Comment by MrMelbert** [comment]
Yeah just clamp it `clamp(round(volume * 0.22, 0.2), 0.5, 10)`
