### ISSUE TITLE
Oxygen from helbital damage doesn't seem to heal on its own

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#84729]
## Issue Summary

After ingesting helbital, the damage from it doesn't heal on its own, for some reason. Code doesn't seem to indicate this is intentional. It may be related to my blood loss changes but I don't see how.

## Reproduction:

Drink some helbital

wait a few minutes

Notice your damage not healing

**Comment by Vect0r2** [comment]
I think it's related to not being able to breath in general

**Comment by Jewelry-x** [comment]
After testing locally by taking 15 units of helbital, the oxygen damage healed itself over time from 48 all the way down to 0, the PR must have fixed the issue that caused this.
