### ISSUE TITLE
Mesons can result in HUD elements disappearing, possibly due to moving across z-levels/multi-z levels

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#84734]
Reporting client version: 515.1640

## Issue Summary

The reporting user is github banned so I'm mostly having to relay this for them, I don't know exactly what the circumstances were that resulted in this problem.

Their hud apparently completely disappeared while they were a borg with Mesons active. They activated them on station (This being Wawastation), moved up to the second level and then took the shuttle down to lavaland. When they landed on lavaland they lost their hud.

When they returned to the station their hud returned but with an extremely low opacity.

I could not recreate it myself testing this. both as a human and a borg.

## Round ID:
[231734](https://scrubby.melonmesa.com/round/231734)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Offset render relays for non-offsetting planes to match highest matching render plane](https://www.github.com/tgstation/tgstation/pull/84184)
- [tgui: custom font bluescreen fix, typescript'd](https://www.github.com/tgstation/tgstation/pull/84601)

## Reproduction:

I couldn't reproduce the issue, so I'm not sure. I listed their actions as they recounted them to me.

**Comment by Robustitron** [comment]
Happened to me and two other people in one round, its pretty common, mesons related.

Your hud gets "stuck" downstairs, like its an object you left there, you will only see it if you go back downstairs, or see a hole or pit that lets you see downstairs, where your hud is, still tracking you horizontally, but on the wrong height level.

It's not just invisible, its not there, no buttons are clickable if you try.

**Comment by necromanceranne** [comment]
my best guess is that it is related to https://github.com/tgstation/tgstation/pull/84184

**Comment by Sadboysuss** [comment]
if it's related to https://github.com/tgstation/tgstation/pull/84184 then:

**Comment by 00-Steven** [comment]
I could SWEAR I already fixed this on the pr- so probably just needs a testmerge update

**Comment by 00-Steven** [comment]
(lemme try to reproduce it anyway just in case)

**Comment by 00-Steven** [comment]
I cannot reproduce this on the latest iteration of the pr

**Comment by necromanceranne** [comment]
You might want to ask someone to update the testmerge if you've pushed fixes for this already and you're fairly confident that this isn't an issue anymore. Testmerges aren't automatically updated I don't believe.
