### ISSUE TITLE
You are unable to sponsor paintings at all.

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#84735]
Reporting client version: 515.1640

## Issue Summary
For some reason, you're completely unable to sponsor paintings. When you try to sponsor a painting, put a cash amount in the bar and press the submit button, it will say "Too far away!", even if you are within interaction range of the painting.
![image](https://github.com/tgstation/tgstation/assets/85206687/2fb1719d-6ff7-476a-b60a-7302c3538744)
![image](https://github.com/tgstation/tgstation/assets/85206687/c47e7790-5abf-4585-a942-aaec6897d470)

## Round ID:
[231740](https://scrubby.melonmesa.com/round/231740)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Offset render relays for non-offsetting planes to match highest matching render plane](https://www.github.com/tgstation/tgstation/pull/84184)
- [tgui: custom font bluescreen fix, typescript'd](https://www.github.com/tgstation/tgstation/pull/84601)

## Reproduction:
1. Find a painting to sponsor.
2. Go up to the painting and put an amount of money in to sponsor it.
3. Submit.
4. "You are too far away!"
5. Cry.

**Comment by 00-Steven** [comment]
wild, lemme look into it

**Comment by 00-Steven** [comment]
seems like it's an issue with `can_perform_action(...)` now using `CanReach(target)` instead of `Adjacent(target)`, which doesn't actually seem to register the paintings as within reach for whichever reason

**Comment by 00-Steven** [comment]
So yeah, as expected, you *can* still patronise it- just press the patronage button, use wirecutters to take the painting off the frame, THEN submit the amount, then put it back on the frame -so this is probably some wonky fuckery with canvas item being on the frame `CanReach(...)` not recognizing this as being reachable.
