### ISSUE TITLE
Pause menu is fucked up

### ISSUE THREAD

**Issue by Moonlit2000** [tgstation/tgstation#84733]
Reporting client version: 515.1639

## Issue Summary
Pause menu looks like this:
![Screenshot 2024-07-06 200329](https://github.com/tgstation/tgstation/assets/130602214/49ea0e5a-32d8-4230-ba06-b8311eda1ff3)

## Round ID:
[231733](https://scrubby.melonmesa.com/round/231733)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Offset render relays for non-offsetting planes to match highest matching render plane](https://www.github.com/tgstation/tgstation/pull/84184)
- [tgui: custom font bluescreen fix, typescript'd](https://www.github.com/tgstation/tgstation/pull/84601)

## Reproduction:
Open pause menu

**Comment by Sadboysuss** [comment]
my pause menu works fine on live servers

**Comment by AdipemDragon** [comment]
might be linked to https://github.com/tgstation/tgstation/issues/84734?

**Comment by 00-Steven** [comment]
that would likely be correct, can reproduce it

**Comment by 00-Steven** [comment]
specifically on multiz
