### ISSUE TITLE
You can "climb" on tables from any distance

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#84751]
Reporting client version: 515.1639

## Issue Summary

https://github.com/tgstation/tgstation/assets/96586172/67263fd5-e33d-4fd9-8e56-5a75c87e0be5

## Round ID:
[231755](https://scrubby.melonmesa.com/round/231755)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Offset render relays for non-offsetting planes to match highest matching render plane](https://www.github.com/tgstation/tgstation/pull/84184)
- [tgui: custom font bluescreen fix, typescript'd](https://www.github.com/tgstation/tgstation/pull/84601)

## Reproduction:
climb on a table from afar

**Comment by ZephyrTFA** [comment]
Advanced mimery

**Comment by Xander3359** [comment]
![image](https://github.com/tgstation/tgstation/assets/66163761/94dd4392-b879-401d-9b48-6e374abdcd14)
We love excluding proximity checks
