### ISSUE TITLE
Crew manifest lost its colours

### ISSUE THREAD

**Issue by 00-Steven** [tgstation/tgstation#84768]
## Issue Summary

Seems the lobby crew manifest utterly lost all its colours, and became more compressed:

![image](https://github.com/tgstation/tgstation/assets/42909981/3d7caeb8-e0e4-4697-b100-12a11b9a3aba)

In comparison to an older one with a full debug crew on my dev instance:
![image](https://github.com/tgstation/tgstation/assets/42909981/a6490de8-77e1-44f1-81eb-e47cbe4d2c46)

## Round ID:

Round ID: [231770](https://scrubby.melonmesa.com/round/231770)
Manuel

## Testmerges:

[#83227: '[TM ONLY] Hijacked Revision Date for v3 TGS Api' by ZephyrTFA at commit 8575d21082](https://www.github.com/tgstation/tgstation/pull/83227)
[#84184: 'Offset render relays for non-offsetting planes to match highest matching render plane' by 00-Steven at commit aa0337019e](https://www.github.com/tgstation/tgstation/pull/84184)
[#84601: 'tgui: custom font bluescreen fix, typescript'd' by jlsnow301 at commit f57e98fa62](https://www.github.com/tgstation/tgstation/pull/84601)

## Reproduction:

Open of a server.
Look at the lobby crew manifest.
No Colours.

**Comment by 00-Steven** [comment]
cc @jlsnow301

**Comment by jlsnow301** [comment]
scoped scss modules. will try to cook up a fix
