### ISSUE TITLE
Atmos circuitboard bugs

### ISSUE THREAD

**Issue by 1393F** [tgstation/tgstation#84778]
## Issue Summary
https://github.com/tgstation/tgstation/pull/84201 All the boards list "1 pipe" as their needed component, only the crafted version of the needed part works and not the rpd version(why are they different?), and it doesn't force you to build it unachored which means unless you place a port connector under it after building to unachor it, it is now stuck there

## Round ID:
N/A
commit used: https://github.com/tgstation/tgstation/commit/1a8cb5de647e0f460f0f94720c378ddfab8a11d8

## Reproduction:
Print one of the new atmos circuit boards

**Comment by Sadboysuss** [comment]
This was a design choice with other items that require this iirc

**Comment by Sadboysuss** [comment]
second part is a bug though

**Comment by Sadboysuss** [comment]
https://github.com/tgstation/tgstation/pull/84187 and https://github.com/tgstation/tgstation/pull/84201
