### ISSUE TITLE
Paraplegics keep their rotation when buckled to animals

### ISSUE THREAD

**Issue by SmArtKar** [tgstation/tgstation#84772]
## Issue Summary
![image](https://github.com/tgstation/tgstation/assets/44720187/9728acd7-6be6-4c82-9563-aaf526961df6)
If you cannot stand up for whatever reason and get buckled to an animal, you keep you rotation.

## Reproduction:

Be paraplegic (or otherwise force-floored)
Buckle yourself to an animal
Keep your rotation
Get your mouth full of feathers

**Comment by dalmationer** [comment]
duplicate #83342

**Comment by Sadboysuss** [comment]
dupe
