### ISSUE TITLE
catwalks are fucked up

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#84789]
Reporting client version: 515.1641

## Issue Summary
![image](https://github.com/tgstation/tgstation/assets/70376633/ecf10ee9-b50f-4dde-bf23-5ddfed0de3f2)

## Round ID:
[231807](https://scrubby.melonmesa.com/round/231807)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Limits the methods through which you can be stunned by a shove. Shoves disarm people who are knocked down.](https://www.github.com/tgstation/tgstation/pull/84640)

**Comment by OrionTheFox** [comment]
Wonder if this has anything to do with #84350  (Floor Plane Flattening)?

**Comment by LemonInTheDark** [comment]
problem is the top overlay is on the floor plane (because I think? it uses floor layers?)
there's no reason it can't be on the game plane with a real low layer (or a higher one). fuckup on my part
