### ISSUE TITLE
Projectile Dampener effect does NOT go away

### ISSUE THREAD

**Issue by SpaceLoveSs13** [tgstation/tgstation#84793]
## Issue Summary

The projectile dampener once turned on, can be turned off simply from quick menu or MOD settings. However, its effect around the user does not go away. With the suit turned off, wearer fully naked, it still stays on. The actual effect might be gone, but the visuals stay there.

## Round ID:

NA

## Testmerges:

NA, reproducable in Local master at latest commit: 59353dcc55f153f647106653bf05a86da0d19bff as of now.

## Reproduction:

1.  Get a modsuit with projectile dampener on(like HOS Safeguard)
2. Activate Projectile dampener from either quick menu or MOD settings.
3. Turn it off from either.
4. Dampener visuals remain constant.
5. Take off mod and other clothing, field continues to go with you.
6. Visible by everyone.

https://github.com/tgstation/tgstation/assets/68121607/6319e378-87cc-47cb-b622-159dec9683fe

Sorry for the abhorrent quality near the end, I had to compress my 40MB recording down to 5MB for github to allow uploading!

**Comment by SmArtKar** [comment]
Not purely visual, field remains active

**Comment by SpaceLoveSs13** [comment]
> Not purely visual, field remains active

Ah yeah I couldnt test that, but that's even worse.
