### ISSUE TITLE
Turning off breathing sounds in settings doesn't turn it off when other people have internals on

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#84809]
Reporting client version: 515.1641

## Round ID:
[231831](https://scrubby.melonmesa.com/round/231831)

## Testmerges:
- [Offset render relays for non-offsetting planes to match highest matching render plane](https://www.github.com/tgstation/tgstation/pull/84184)
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [[tm only] Temporary fix on heretic ui](https://www.github.com/tgstation/tgstation/pull/84767)

## Reproduction:
While being able to mute the sounds of my own breathing was a nice option, its made irrelevant when I have to listen to the same sound any time i'm around someone else using internals

**Comment by SmArtKar** [comment]
Others sounds should probably either be quieter, only played for them by default, or muted when the option is toggled
