### ISSUE TITLE
Mothroaches are a bit too hungry and eat out of your pockets every 30 seconds

### ISSUE THREAD

**Issue by MoffNyan** [tgstation/tgstation#84825]
Reporting client version: 515.1637

## Issue Summary

When you put a mothroach into your bag (even a zipped up duffel bag), or put the mothroach on your head, after about 30 seconds to a minute it makes a chewing noise and writes;
"The mothroach wriggles free!"
"The mothroach uncurls!"
While it's cute, it's a bit frustrating and you can quickly lose your pet companion during high tension moments where you need to run away and don't have the time to pick up the mothroach endlessly. Sometimes the mothroach crawls out of your pocket _immediately_ after putting it in.

Maybe related to this PR?
https://github.com/tgstation/tgstation/pull/83695
It's a great PR, but having it eat out of your bag or crawl off your head is a bit much...

## Round ID:
[231848](https://scrubby.melonmesa.com/round/231848)

## Testmerges:
- [Offset render relays for non-offsetting planes to match highest matching render plane](https://www.github.com/tgstation/tgstation/pull/84184)
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [[tm only] Temporary fix on heretic ui](https://www.github.com/tgstation/tgstation/pull/84767)

## Reproduction:

Either
- Put mothroach in bag
- Put mothroach in duffel bag and zip it
- Put mothroach on head

And then wait 30 seconds to a minute, and watch as your hopes and dreams slip away...

**Comment by san7890** [comment]
@Ben10Omintrix
