### ISSUE TITLE
Dealing cards is not working

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#84834]
Reporting client version: 515.1641

## Issue Summary

https://github.com/tgstation/tgstation/assets/96586172/8c02fe42-1bfa-4022-a1fb-9bc9d2e0006a

## Round ID:
[231867](https://scrubby.melonmesa.com/round/231867)

## Testmerges:
- [Offset render relays for non-offsetting planes to match highest matching render plane](https://www.github.com/tgstation/tgstation/pull/84184)
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [[tm only] Temporary fix on heretic ui](https://www.github.com/tgstation/tgstation/pull/84767)

## Reproduction:
Wield a card deck in hand, try to hand out cards

**Comment by 00-Steven** [comment]
oh yeah lemme give this a shot
