### ISSUE TITLE
Extreme Edge Case: Exploding in Disposals can boot to nullspace

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/tgstation#8484]
I encountered an odd bug today on Sybil. A traitor accidentally triggered a syndieminibomb in disposals and jumped into the central delivery chute to escape. It's unclear whether they were still in the actual chute, or one of the disposals pipes nearby. The bomb detonated, sending them to nullspace, completely unharmed. I managed to recover them with a simple Get command.

We attempted to replicate it on the thunderdome to no success. I also attempted to place myself in a pipe's contents and detonating it but that also failed. It seems that there is some edge case in which an object travelling in disposals can be sent to nullspace when whatever it is travelling through gets deleted/damaged.

**Comment by Miauw62** [comment]
inb4 some other maintainer says "disposals code is awful in general"

**Comment by RemieRichards** [comment]
disposals code is awful in general

**Comment by Jordie0608** [comment]
I'm going to take a wild guess and say the pipe got destroyed, and thus had a null location, before the mob got kicked out of it and tried to be placed onto the pipe's loc.

**Comment by Razharas** [comment]
This is what happens when you make datums try to act like actual objects

**Comment by kevinz000** [comment]
I think this is fixed @optimumtact I tested a buncha times in thunderdome, can't find it happening.

**Comment by Jalleo** [comment]
@kevinz000 they tried to replicate it but couldn't.

**Comment by MrStonedOne** [comment]
close me
