### ISSUE TITLE
Painting gallery / Persistent paintings broke and the gallery is empty round to round

### ISSUE THREAD

**Issue by Robustitron** [tgstation/tgstation#84844]
## Issue Summary
"Initialized Persistent Paintings subsystem with errors within 0 seconds!" shows on round startup.

I noticed this starting yesterday and its happened in every round I've seen since, painting gallery is empty, just empty slots.

## Round ID: 
[231886](https://scrubby.melonmesa.com/round/231886)

## Testmerges:
[#84184: 'Offset render relays for non-offsetting planes to match highest matching render plane' by 00-Steven at commit f9fbe534f4](https://www.github.com/tgstation/tgstation/pull/84184)
[#83227: '[TM ONLY] Hijacked Revision Date for v3 TGS Api' by ZephyrTFA at commit 8575d21082](https://www.github.com/tgstation/tgstation/pull/83227)
[#84767: '[tm only] Temporary fix on heretic ui' by jlsnow301 at commit 3c78cac75f](https://www.github.com/tgstation/tgstation/pull/84767)

## Reproduction:
1) Run to the library 
2) Look at the paintings
3) Oh wait there are no paintings, only empty slots

**Comment by Sadboysuss** [comment]
I'm gonna assume it was the db failure and there is nothing we can do codeside for this
