### ISSUE TITLE
You can duplicate anomaly core items and bypass the core limit

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#84849]
## Issue Summary
Using the EXPERIMENTOR's irradiate feature - you can duplicate any item, therefore you can duplicate for example: bags of holding, and make any amount you want of them.

## Round ID:
[231906](https://scrubby.melonmesa.com/round/231906)

## Reproduction:
1. Put anomaly core item into experimentor
2. Use irradiate to duplicate it

**Comment by Sadboysuss** [comment]
Some information may be inaccurate but you get the gyst of it

**Comment by Time-Green** [comment]
It's a whitelist on the irradiate function of the experimentor. I figured you're more likely to end up deleting the BoH than actually getting the dupe experiment, but obviously recent youtube videos have proven me wrong

https://github.com/tgstation/tgstation/blob/c3562f828f3df6b003b18f3efd364a8cd0f02e0e/code/modules/research/experimentor.dm#L95-L101

**Comment by Sadboysuss** [comment]
An easy way to fix this would be to remove the BoH from that list 😢

**Comment by Livrah** [comment]
> It's a whitelist on the irradiate function of the experimentor. I figured you're more likely to end up deleting the BoH than actually getting the dupe experiment, but obviously recent youtube videos have proven me wrong
> 
> https://github.com/tgstation/tgstation/blob/c3562f828f3df6b003b18f3efd364a8cd0f02e0e/code/modules/research/experimentor.dm#L95-L101
It will delete a BoH most likely, video doesn't show what this was made 50 minutes into the round (when you know what you are doing/get lucky)
