### ISSUE TITLE
You cannot naturally recover from oxycrit (>50 oxyloss) if you have less than 90% blood volume

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#84857]
## Issue Summary

If you are above 50 oxyloss (say, from being defibrillated), but your blood volume is <90% (~480ml), you will never recover from oxycrit

The "passive oxygen damage level" from blood loss outheals the natural oxy healing from breathing

This issue is most problematic from being defibrillated (as mentioned above).
Most players usually to tend wounds to 0/0 before defibrillating, which places their patients at 150 oxyloss.
And because a majority of patients who come into medbay come in, probably, with a small amount of blood missing, it means being defibbed leaves you in oxycrit forever / until you die again if they don't give you a supplementary chemical (salbu / convermol) 

## Reproduction:

- Spawn in as a character
- VV oxyloss to 60
- VV blood volume to 480
- observe as you will not wake up until your blood volume recovers >90% (a process which naturally takes a very very long time, and is liable to kill you before then)

**Comment by MrMelbert** [comment]
![image](https://github.com/tgstation/tgstation/assets/51863163/018f325a-4c02-4222-b643-6af428d07c62)

**Comment by Dawnseer** [comment]
Just 5 more minutes, I promise
