### ISSUE TITLE
Outfit-Manager admin verb works once in a round and then never again

### ISSUE THREAD

**Issue by Isratosh** [tgstation/tgstation#84856]
Reporting client version: 515.1640

## Issue Summary
The outfit-manager verb for importing, exporting, and editing custom outfits for use with select-equipment is failing to open its UI after the first use.

## Round ID:
[231922](https://scrubby.melonmesa.com/round/231922)

## Testmerges:
- [Offset render relays for non-offsetting planes to match highest matching render plane](https://www.github.com/tgstation/tgstation/pull/84184)
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [[tm only] Temporary fix on heretic ui](https://www.github.com/tgstation/tgstation/pull/84767)
- [Full revert of #79995 (tri-ai station trait). Partal revert of #81681 (human ai)](https://www.github.com/tgstation/tgstation/pull/84850)

## Reproduction:
1. use outfit-manager and see the correct UI appear
2. close it
3. use outfit-manager again and see either nothing happen or an empty white box appear
4. ask other admins online and they can't open it either

**Comment by DATA-xPUNGED** [comment]
Can confirm I've experienced this in a localhost before, just thought it was a me issue
