### ISSUE TITLE
Bookcase weirdnesses

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#84884]
Reporting client version: 515.1641

## Issue Summary
If you take the wooden shelves out of a bookcase, you suddently can't interact with the bookshelf at all UNLESS it's either adding the planks back in or the expected tool usage of wrench -> crowbar. Flinging stuff / shooting to damage it still works fine, though.
Breaking a shelf always drops 4 planks, regardless if there's 2 planks set in as shelves set or not,

## Round ID:
[231946](https://scrubby.melonmesa.com/round/231946)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Offset render relays for non-offsetting planes to match highest matching render plane](https://www.github.com/tgstation/tgstation/pull/84184)
- [tgui: Loads icon refs at boot](https://www.github.com/tgstation/tgstation/pull/84853)

## Reproduction:
Crowbar the shelves out the bookcase
You no longer can bash the bookcase to break it

Break two bookcases, with or without shelves
Both drop the base ammout of planks to build (4)

**Comment by SmArtKar** [comment]
actually just bad code
