### ISSUE TITLE
You can roll midround antags as bitrunner ghost roles

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#84887]
## Issue Summary
![image](https://github.com/tgstation/tgstation/assets/96586172/85058b61-5945-49f6-b708-44ef3160bbe1)

## Reproduction:
1. be a bitrunning ghost role
2, wait for dynamic to hand out midround antags

**Comment by SuperNovaa41** [comment]
Could not recreate, with any of the bitrunning roles
