### ISSUE TITLE
justice is too good at cloaking

### ISSUE THREAD

**Issue by MelokGleb** [tgstation/tgstation#84894]
## Issue Summary
![image](https://github.com/tgstation/tgstation/assets/99420088/56500589-c926-4127-9be9-66250e174fce)
do you see Justice here? it IS here
justice became invisible and no longer can be climbed inside, there is no one in it

## Round ID:
not on official TG server

## Testmerges:
none

## Reproduction:
1) climb into justice
2) have grav off
3) climb out
4) Justicn't
(maybe i missed some steps but thats what i know about it)

**Comment by moocowswag** [comment]
mouse opacity issues too? have you tried alt click?
