### ISSUE TITLE
You cannot place evidence bags into lockers

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#84890]
Reporting client version: 515.1641

## Issue Summary

https://github.com/tgstation/tgstation/assets/96586172/f02d49d3-c22f-4cdd-85df-1b1baa464ecb

## Round ID:
[231958](https://scrubby.melonmesa.com/round/231958)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Offset render relays for non-offsetting planes to match highest matching render plane](https://www.github.com/tgstation/tgstation/pull/84184)
- [tgui: Loads icon refs at boot](https://www.github.com/tgstation/tgstation/pull/84853)

## Reproduction:
Video

**Comment by 00-Steven** [comment]
oh huh, lemme give it a shot after dinner

**Comment by 00-Steven** [comment]
yeah I feel like these should probably just be reworked into being an extension of the storage system, which should be able to do most of this already, rather than its own wonky insertion implementation- looking into that slowly
