### ISSUE TITLE
Heater charge depletes too fast

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#84892]
Reporting client version: 515.1641

## Issue Summary

https://github.com/tgstation/tgstation/assets/96586172/1de2fdb6-362b-444b-b270-28a57a17b2ad

## Round ID:
[231962](https://scrubby.melonmesa.com/round/231962)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Offset render relays for non-offsetting planes to match highest matching render plane](https://www.github.com/tgstation/tgstation/pull/84184)
- [tgui: Loads icon refs at boot](https://www.github.com/tgstation/tgstation/pull/84853)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)

## Reproduction:
Video

**Comment by Inari-Whitebear** [comment]
What cell was it?

**Comment by Sadboysuss** [comment]
> What cell was it?
> 
> I don't think they were ever "that" capable if unupgraded really. I do recall having to sometimes drag two from maints cause on died when I tried heating/cooling a room, and that was like a year ago

It was a normal cell but I later replaced ut with a bluespace cell and it didn't last very long either. It seems that the power consumption is tied to the "amount" of heating they did

**Comment by Inari-Whitebear** [comment]
> > What cell was it?
> > I don't think they were ever "that" capable if unupgraded really. I do recall having to sometimes drag two from maints cause on died when I tried heating/cooling a room, and that was like a year ago
> 
> It was a round start cell, but I later replaced it with a bluespace cell, and it didn't last very long either. It seems that the power consumption is tied to the "amount" of heating they did

Well yeah, if you need to heat or cool more you use more power? Always been that was as far as I know

Well no idea, in my tests they seemed to perform as well as before the megacell stuff
Did you try replacing teh capacitor? Better capacitors means it uses less energy for the heating/cooling

**Comment by SyncIt21** [comment]
This has become a very subjective issue at this point.

There have been several PRs that tried to fix this so when can we say it's actually fixed?

There is no baseline on how long a cell is supposed to last under specific circumstances.

Note that the Megacell PR lowered the capacity of all power cells, before that their charge was 1000x times than now so stuff that people are used to seeing last long is no longer the case and is mistaken as a bug.

I think we just have to close this issue before people tweak the numbers further and someone else complains later on that "they feel" the cell isn't lasting long enough.

**Comment by Inari-Whitebear** [comment]
Well at least they're useful now. Before the last fix they heated/cooled like 1C every few seconds, so good like cooling a 90C room if you don't want to wait for 10 minutes

And before that they basically drained instantly.

But yeah, bit of a question of how good they should be, especially with various parts. Capacitor reduces power usage too as said.

**Comment by Pickle-Coding** [comment]
https://github.com/tgstation/tgstation/commit/9995a0dde73035f6c46c5c2d6dde944c1e32975d scaled the heating energy instead of the efficiency, which changed how fast it heats or cools with the air, instead of the energy drain of the cell. It should stay as 40 kJ and not scale with cells. https://github.com/tgstation/tgstation/commit/35486c23dbd91ab1b7f5c1f2d8837381bfb15075 did scale it back up to be equal to 40 kJ, but it should not use the cell defines. Just make efficiency be 20 MEGA JOULES / STANDARD_CELL_CHARGE, then it'll scale properly with the cell defines.
