### ISSUE TITLE
Stopping Cascade resonance for the achievement is impossible

### ISSUE THREAD

**Issue by Hafahya** [tgstation/tgstation#84899]
**I have played 4 hour shift in the night to try and get impossible achievement**

## Issue Summary

Conditions for the Cascade Resonance (amount of moles in SM) cannot be physically removed in 15 seconds (countdown timer)

## Round ID:

round 1309 Massmeta
(https://github.com/Huz2e/massmeta)

## Reproduction:

Cascade Resonance delam is very tricky to set up and if conditions are broken it immediatly becomes any other delam for whom conditions are met. As such, you need to maintain the mole amount and gas percentages untill countdown starts, at which point you have whopping 15 seconds to siphon the required thousands of moles out of the, usually overheated SM. Which is not possible. Even if you have cold hypernob ready to flow in, it is simply ridicilous. 

Change conditions for the achievement from the countdown timer to below fixing the SM when it was below, for example, 10 % integrity. If not that, make the timer be a minute and also make Cascade resonance delam faster. Having to wait for it to sloooowly decrease in integrity is torture after you have spent two hours making hyper and anti - nobs. Maybe, make it so it will not change to other delam types when you got the message from CC about resonant flux, untill the integrity begins to restore.

**Comment by iansdoor** [comment]
> The fast way to syphon the SM is by applying a fireaxe to the windows.
> 
> Or fully building a custom setup with shutters/airlocks whatever else, the default atmos pipe syphons will have a hard time dealing with it, and personally, that is not an issue at all.
> 
> Gotta be creative to achieve the "peak" of atmos memery.

yep! exactly that! The fireaxe is the tool to break windows. There is tons of creative setups and you didn't even get to the hard part. You have to stay in the room till 20% of the SM is healed. The amount of anomalies is tricky! I wish you much luck on the going forth with the solution you come up with.

**Comment by Sadboysuss** [comment]
it's definitely possible because I've done it

**Comment by san7890** [comment]
post screenshot
