### ISSUE TITLE
click_alt_secondary unsupported on silicons

### ISSUE THREAD

**Issue by CliffracerX** [tgstation/tgstation#84900]
## Issue Summary

All uses of ``click_alt_secondary`` fail to work correctly with cyborgs (``/mob/living/silicon/robot`` and subtypes), *mostly* calling ``click_alt`` instead (and thus also opening the tile-search window) or doing nothing (and/or, again, opening tile-search) - I suspect the functionality died in #83736, but I'm not familiar enough with the COMSIG spaghetti to make heads or tails of why it's only cyborgs who suffer despite not being touched in the PR.

## Round ID: N/A, discovered on downstream and tested on baseline TG

Discovered first on my Nova Sector fork (ported lidded beakers from Shiptest with removal on alt-RMB), but verified the same issue is present on baseline TG by testing with a medical borg and a mass spectrometer (alt-RMB to remove output beaker) - silently fails.

## Reproduction:

As a borg, try to remove the output beaker from a Mass Spectrometer, swap a necktie lying on the ground to a different layer, or switch a soup pot to auto-clean.  All functions fail silently.

**Comment by CliffracerX** [comment]
Addendum: drones (``/mob/living/basic/drone/`` subtypes, though I could only actually test with the syndrone due to the "using <x> might break your laws!" warning) are able to use alt-RMB functions just fine.

**Comment by SyncIt21** [comment]
> I suspect the functionality died in https://github.com/tgstation/tgstation/pull/83736

This is false. Alt click functionality for borgs is implemented in `_onclick/cyborg.dm` file which my PR never touched.

In other words borgs never had alt right click functionality since the beginning, though the fix is easy
