### ISSUE TITLE
Nuclear Clown Reinforcements Spawn With TC

### ISSUE THREAD

**Issue by Das15** [tgstation/tgstation#84915]
## Issue Summary

Yes, clown op reinforcements item spawns in a nuke op with uplink containing the same amount of TC as normal spawn, meaning that a person buying uplink actually gets more TC. Funnily enough the normal nuclear reinforcement seems to work just fine.

## Reproduction:
- Become Clown Operative
- Use the clown reinforcement item
- Realize that the reinforcement clown gets uplink, which contains TC.
- Oh god, infinite TC glitch confirmed

**Comment by GPeckman** [comment]
I nominate this of Fuckup of the Year 2024

**Comment by Das15** [comment]
Yeah, I agree. Im looking into the code right now and trying to figure out what went wrong...
