### ISSUE TITLE
ChemMaster 3000 runtime when trying to transfer/delete reagents without a beaker inserted

### ISSUE THREAD

**Issue by zoomachina** [tgstation/tgstation#84938]
## Issue Summary
If you try to transfer or delete reagents from ChemMaster's buffer, the following runtime occurs if there's no beaker inserted:
`Runtime in code/modules/reagents/chemistry/machinery/chem_master.dm,438: Cannot read null.reagents`
The cause for this seems to be the following code:
```
if(target == "buffer")
	return transfer_reagent(ui.user, beaker.reagents, reagents, reagent_ref, amount, TRUE)
else if(target == "beaker")
	return transfer_reagent(ui.user, reagents, beaker.reagents, reagent_ref, amount, is_transfering)
```
When there's no beaker inserted, `beaker` is null, so we got a problem.
The side effect of this runtime is that you can only delete reagents from the buffer as long as there's a beaker inserted, even though that shouldn't matter.

## Reproduction:
1. Grab a beaker, fill it with some reagent
2. Transfer some of it into the chemmaster's buffer, then remove the beaker.
3. Press the transfer button - the runtime occurs.

**Comment by LemonInTheDark** [comment]
ftr if you know the fix you don't need to make an issue report, it's ok to just make a fix pr without one. this is also fine but so you're aware.

**Comment by zoomachina** [comment]
> ftr if you know the fix you don't need to make an issue report, it's ok to just make a fix pr without one. this is also fine but so you're aware.

I understand this, but I'm making the issue in case the pr gets closed, so someone else might have a try at it.

**Comment by LemonInTheDark** [comment]
it won't but your heart is in a good place, respect
