### ISSUE TITLE
Carrot swords have a broken description

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#84988]
## Issue Summary
On the can

## Reproduction:
![image](https://github.com/user-attachments/assets/57f7fc4d-d8c0-4a37-8ea6-1fcef9ca7c28)

**Comment by Sadboysuss** [comment]
nevermind I'll let a new contrib handle this.

**Comment by Sadboysuss** [comment]
Jacquerel said to fix it anyways

**Comment by AdipemDragon** [comment]
i mean yeah, it's probably one of those things I could've fixed myself too, but oh well

**Comment by Apocalypse96** [comment]
Hey @AdipemDragon pls assign this to me
