### ISSUE TITLE
Harmless meteor shuttle event is far from harmless

### ISSUE THREAD

**Issue by Rhials** [tgstation/tgstation#84994]
## Issue Summary

![image](https://github.com/user-attachments/assets/7c9032a7-71c8-4ff9-bdc4-3338e458c841)

METEOR PURGE METEOR PURGE METEOR PURGE NO SURVIVORS NO SURVIVORS.

## Round ID:

[232160](https://scrubby.melonmesa.com/round/232160)

## Testmerges:

[#84826: 'Adds new station map Nebulastation' by KikoWen0 at commit 36f1dfa793](https://www.github.com/tgstation/tgstation/pull/84826)
[#84951: 'Ghosts once again can see people's true names and roundstart jobs' by SmArtKar at commit 67b7238ae2](https://www.github.com/tgstation/tgstation/pull/84951)
[#84964: 'Reworks silicon/ai access checking & fixes some ui_act's' by JohnFulpWillard at commit 3951a2a798](https://www.github.com/tgstation/tgstation/pull/84964)

## Reproduction:

Harmless meteor shower shuttle event -> Nebulastation -> Oh dear...

![image](https://github.com/user-attachments/assets/f4a791da-249a-489d-a455-a7ba0cf948a2)

I can't really confirm that this is specific to Nebulastation or some sort of bug that only triggers under specific circumstances. I tested it on local and nothing happened.

I believe this is a revival of #77433.

**Comment by Dawnseer** [comment]
It was a very bumpy ride.

**Comment by Time-Green** [comment]
I can’t believe this bug still haunts me. I can never reproduce it and it’s so stupidly elusive

**Comment by Inari-Whitebear** [comment]
This one is actually reproducible!

* Nebula station
* Spawn Nebula shuttle
* Call it
* Set event to Various Meteors (safe)
* Launch it

Or at least I just did this twice and both times it happened

**Comment by Sadboysuss** [comment]
the pr is merged now
