### ISSUE TITLE
Firebot ranged attack

### ISSUE THREAD

**Issue by Aniantan** [tgstation/tgstation#85015]
## Issue Summary
Sentient firebots can attack stuff with their extinguisher at any range.

## Round ID:
[232193](https://scrubby.melonmesa.com/round/232193)

## Testmerges:
[#84826: 'Adds new station map Nebulastation' by KikoWen0 at commit 36f1dfa793](https://www.github.com/tgstation/tgstation/pull/84826)

## Reproduction:
1. Become a sentient firebot
2. Click on something that can be hit with a fire extinguisher while not being close enough to actually hit it, might need combat mode.
3. Notice that your firebot did the attack animation and the object took damage

**Comment by necromanceranne** [comment]
I swear I thought this was already up on the tracker.
