### ISSUE TITLE
wawastation's ai core is somewhat inhospitable to human ais

### ISSUE THREAD

**Issue by nianjiilical** [tgstation/tgstation#85013]
## Round ID: [232190](https://scrubby.melonmesa.com/round/232190)

wawa's ai sat/core design puts the telecomms machines and the ai core itself in a single room, which is cool design but has the unfortunate effect of freezing the big brother to death when the human ai station trait rolls

**Comment by mc-oofert** [comment]
im not sure how this would be fixed without just making it not connected to telecomms but for this purpose theres a spacesuit next to the SMES

**Comment by EEASAS** [comment]
> im not sure how this would be fixed without just making it not connected to telecomms but for this purpose theres a spacesuit next to the SMES

this is the only way i can communicate with you but im thinking of sealing the ai area and putting passive vents connected to a digital valve that the ai can only use connected to an air injector or pump or something

**Comment by mc-oofert** [comment]
no thats boring

**Comment by TheVekter** [comment]
I think this is ultimately just a side effect of human AI being kind of a shitty station trait

**Comment by loganuk** [comment]
### Mock up of one suggestion for discussion

- Removed railings
- Added glass flooring to seal off t-comms below
- Replaced transparent catwalk with dark catwalk
- Could chuck in some air controls for it as well

### Before: 
![image](https://github.com/user-attachments/assets/2e2c3ebd-d351-4823-80b1-9e7347f87e0a)

### After:
![image](https://github.com/user-attachments/assets/454c3232-2675-463e-bf2b-7106c9e29861)

**Comment by mc-oofert** [comment]
just no, tcomms AI is just a novel idea itself

**Comment by Sealed101** [comment]
#86953 should have done the trick
