### ISSUE TITLE
Space light overlays don't account for creature features

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#85035]
Reporting client version: 515.1641

## Issue Summary
When in space light, only body parts and clothing pieces count when being drawn around ;
 body features and overlays, like wings, snouts, tails, even clothing, Don't, so they get fullbright'd instead

## Reproduction:
![image](https://github.com/user-attachments/assets/09b6a782-9221-4fe8-ad73-0750ed58bdcb)

**Comment by LemonInTheDark** [comment]
The issue is space lights work by drawing an emissive behind, and then counting on anything solid to block that emissive and thus show the glow of space (that way we don't color parallax).
The problem is a lot of mob parts just like, fail to draw emissive blockers. so this sort of thing happens.

**Comment by MrMelbert** [comment]
theoretically fixable by just making humans `EMISSIVE_BLOCK_UNIQUE`? but that breaks emissive overlays
