### ISSUE TITLE
Borgs cannot use the research queue system

### ISSUE THREAD

**Issue by L0pz** [tgstation/tgstation#85049]
Reporting client version: 515.1641

## Issue Summary

Borgs cannot queue research nodes or cancel queued research nodes.

## Round ID:
[232245](https://scrubby.melonmesa.com/round/232245)

## Testmerges:
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)

## Reproduction:

1. Be a borg
2. Try pressing the queue button on an un-queued node
3. Try cancelling a queued node
4. Hope really hard that this is indeed a bug and not something someone actually intended

**Comment by Sadboysuss** [comment]
@MTandi is this intended?

**Comment by MTandi** [comment]
No really. I needed to check RD so I cast to carbon/human to get `wear_id`. We can expand this to non humans probably.
