### ISSUE TITLE
MODsuit Organ Thrower Deletes Brains Instead of Replacing 

### ISSUE THREAD

**Issue by Neuroplasty** [tgstation/tgstation#85058]
## Issue Summary

When using the medical MODsuit organ thrower to try to replace someone's brain, it simply deletes the brain being shot into the recipient. I was told in deadchat that this is a known issue, but I couldn't find anything in here.

## Round ID:

[232239](https://scrubby.melonmesa.com/round/232239)

## Reproduction:

This should be easily reproducible by trying to use an organ thrower module to replace a brain in an open patient. When the brain hits the body it simply ceases to exist. I assume this is specifically because I tried to use the catatonic body of another player with their brain still inside the head to try to hot swap consciousness on someone.

**Comment by CCC23** [comment]
I wonder if I could use a organ thrower loaded with monkey brains on people with open skulls to hotswap them into a fucking monkey
