### ISSUE TITLE
Monkey hide makes a metal sound when picked up / dropped

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#85056]
Reporting client version: 515.1641

## Round ID:
[232256](https://scrubby.melonmesa.com/round/232256)

## Testmerges:
- [Ghosts once again can see people's true names and roundstart jobs](https://www.github.com/tgstation/tgstation/pull/84951)

## Reproduction:
Butcher a monkey
Pick up its hide
Hear a metal clink???

**Comment by necromanceranne** [comment]
Same for bones, probably any animal hide and sinew.
