### ISSUE TITLE
Jitter Animation Bugs Layers/Planes

### ISSUE THREAD

**Issue by Gottfrei** [tgstation/tgstation#85099]
## Issue Summary

Proc /mob/living/proc/do_jitter_animation() works incorrectly when traversing Z-levels. Something with layers/planes idk.

[dreamseeker_XMofhqVUf1.webm](https://github.com/user-attachments/assets/dfb743c5-d9ab-4354-b7a2-387e3ce57c54)

**Comment by Sadboysuss** [comment]
Dupe of https://github.com/tgstation/tgstation/issues/84327
