### ISSUE TITLE
Surgical tape embedding stats not updated to the new system

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#85095]
## Issue Summary

https://github.com/tgstation/tgstation/blob/035c3ec70b4e0addd5ce3b1cece265a2c0c93f96/code/game/objects/items/stacks/tape.dm#L130

**Comment by MrMelbert** [comment]
Also maybe this
https://github.com/tgstation/tgstation/blob/035c3ec70b4e0addd5ce3b1cece265a2c0c93f96/code/modules/paperwork/pen.dm#L366-L367

**Comment by SmArtKar** [comment]
aeugh
