### ISSUE TITLE
Fire immunity mutation doesn't stop you from getting "I'M ON FIRE!!!" negative moodlet 

### ISSUE THREAD

**Issue by zoomachina** [tgstation/tgstation#85105]
## Issue Summary
If you have "Heat Adaptation", which makes you immune to damage from fire, you will still get a mood debuff ("I'M ON FIRE!!!")

## Reproduction:
1. Get Heat Adaptation mutation.
2. Ignite yourself in any way. You will not take damage from fire, but you will get a negative moodlet.

**Comment by the-orange-cow** [comment]
To be fair, it would probably be pretty unsettling.

**Comment by zoomachina** [comment]
![man-on-fire-498-x-322-gif-35hed18otg256sad](https://github.com/user-attachments/assets/b57efc2c-40ad-4018-a05d-715bf2af6b7f)

**Comment by Axidyuwu** [comment]
Heat adaptation does not saves you from fire, it saves you from overheating, thats it

**Comment by zoomachina** [comment]
> Heat adaptation does not saves you from fire, it saves you from overheating, thats it

```
	desc = "A strange mutation that renders the host immune to damage from high temperature, including being set alight, though the flame itself still burns clothing. It also seems to make the host resist ash storms."
```
