### ISSUE TITLE
Floorbots fucky with catwalk replacing.

### ISSUE THREAD

**Issue by Stiix72** [tgstation/tgstation#85102]
Reporting client version: 515.1641

## Issue Summary

Can't replace catwalk unless I pull up the tile content menu. I then replace catwalk and it creates a pretty flashing error block.
https://imgur.com/a/9j2REWx

## Round ID:
232337

**Comment by Hoolny** [comment]
When you say you "can't replace catwalk" could you be more specific, replication is nice to have when looking over bugs

**Comment by Stiix72** [comment]
> When you say you "can't replace catwalk" could you be more specific, replication is nice to have when looking over bugs

This issue has since been fixed, but if you spam click maints floors you WILL make an impassible tile.

**Comment by Hoolny** [comment]
> > When you say you "can't replace catwalk" could you be more specific, replication is nice to have when looking over bugs
> 
> This issue has since been fixed, but if you spam click maints floors you WILL make an impassible tile.

Well If there isn't an issue made for it now would be a good time for it, this one's done though thanks <3.
