### ISSUE TITLE
Monkeys start with the Monkified gene hidden, unable to be revealed (except on a human by activating it as a hidden gene), and cannot have it deactivated on monkeys themselves (so they can't be made into a human)

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#85100]
## Issue Summary

As it says, in the title

## Reproduction:

Put a monkey into a scanner roundstart. It'll reveal no information and will not reveal what gene is the monkey gene. Even if you did reveal it on an actual human, and it ends up in the database, you cannot deactivate it on monkeys themselves. This works on live consistently.

**Comment by Jacquerel** [comment]
Are you sure they don't have it? My understanding is that it isn't automatically revealed until you have discovered it, which you will not have done at roundstart.  
If it was old behaviour that it _was_ always visible that may have regressed at some point.

**Comment by necromanceranne** [comment]
Actually, it's a lot worse. They have it, it is hidden, and it can't be removed at all. They have to be human from the start.

**Comment by MrMelbert** [comment]
Monkeys can random have no tails which I find weird but it's intentional
