### ISSUE TITLE
Ghost sec/med/diag hud doesn't work

### ISSUE THREAD

**Issue by cnleth** [tgstation/tgstation#85120]
## Issue Summary
Observe, see that healthbars, id trims and other such ui elements are not visible, try toggling "Sec/Med/Diag HUD' and it doesn't do anything. Admin hud is not affected by this apparently

## Round ID:
[232348](https://scrubby.melonmesa.com/round/232348)

**Comment by Holoo-1** [comment]
Reproduction:
update byond to 515.1641
observe
