### ISSUE TITLE
You can move at pre-nerf jetpack speed using a jetpack implant.

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#85148]
## Issue Summary
Using a jetpack implant, you can go at pre-nerf jetpack speed.

## Round ID:
Fulpstation

## Reproduction:
Use a jetpack implant.

**Comment by Jacquerel** [comment]
> ## Round ID:
> 
> Fulpstation

![image](https://github.com/user-attachments/assets/d54cee99-1240-4272-b32d-fe1830f8e5dc)

**Comment by Sadboysuss** [comment]
> > ## Round ID:
> > Fulpstation
> 
> ![image](https://private-user-images.githubusercontent.com/7483112/350722857-d54cee99-1240-4272-b32d-fe1830f8e5dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1MDk5NTEsIm5iZiI6MTcyMTUwOTY1MSwicGF0aCI6Ii83NDgzMTEyLzM1MDcyMjg1Ny1kNTRjZWU5OS0xMjQwLTQyNzItYjMyZC1mZTE4MzBmOGU1ZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjBUMjEwNzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzBmMGY0ZjZiYzVmNGI2YTY0ZGQzYTVlZTE1N2RjZmExNTM3ODk0NWY5ZmQyNzdlZDc1NGFmNGQzZmIzMGU3MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SxNUSZoZg0QJA6DW-tFsEjKKOXQC8J6VHYuC65k8GDY)

I don't remember how it's called so I just said it's jetpack implant, I know it exists on tg, I'll get the proof later if you don't believe me
