### ISSUE TITLE
"Implantable thrusters set" moves at pre jetpack nerf speed

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#85165]
Reporting client version: 515.1641

## Issue Summary
Revival of https://github.com/tgstation/tgstation/issues/85148 @Jacquerel 

![image](https://github.com/user-attachments/assets/9c2a7977-1c2f-49a0-8df1-c4c98d80cf81)

https://github.com/user-attachments/assets/1c55aa4b-6a2c-4a05-8e80-82480e04ff68

## Round ID:
Reproduced locally on latest /TG/station master

## Reproduction:
Equip an "Implantable thrusters set" and use it in space

**Comment by JackEnoff** [comment]
Honestly? Feature, barely anyone uses jetpack implant, it's harder to get than a jetpack, has no stabilization, and on space eats whatever gas in your internals tank by a LOT (100 kpa of gas every 2-3 seconds when moving).

**Comment by SmArtKar** [comment]
Oversight by mc-oofert when nerfing other jetpacks

**Comment by mc-oofert** [comment]
> Oversight by mc-oofert when nerfing other jetpacks

JackEnoffs point stands

**Comment by Sadboysuss** [comment]
> > Oversight by mc-oofert when nerfing other jetpacks
> 
> JackEnoffs point stands

this doesn't make sense because antag gear is balanced about crew gear being weaker, thruster implants are stronger than any jetpacks nuclear operatives for example can get, so you have to either be consistent with nerfing all of it or leave antags with a better option.

**Comment by mc-oofert** [comment]
i meant that jetpack implants are so unused i absolutely forgot they existed

**Comment by JohnFulpWillard** [comment]
antag gear is not balanced around crew gear being weaker

**Comment by Sadboysuss** [comment]
> antag gear is not balanced around crew gear being weaker

- contractor baton
- syndicate revolver
- combat defib
- suspicious toolbox

what?
