### ISSUE TITLE
My mech can hold the armory of weapons

### ISSUE THREAD

**Issue by iansdoor** [tgstation/tgstation#85166]
However I only get the one to use. So you can store infinite amounts of weapon on a side and lose all those weapons on accident.
![Screenshot_731](https://github.com/user-attachments/assets/931e7312-1e94-4cb1-9ba1-10c2c7d07637)
![Screenshot_730](https://github.com/user-attachments/assets/005e537a-ebab-4e5e-b78e-066630e39bf3)
![Screenshot_729](https://github.com/user-attachments/assets/7d5aea2d-d2d5-403a-9ed3-68b149267d3c)

**Comment by Sadboysuss** [comment]
Needs a check to prevent multiple weapons being installed
