### ISSUE TITLE
Tram smashes its rails and pipes

### ISSUE THREAD

**Issue by SmArtKar** [tgstation/tgstation#85171]
## Issue Summary

#84350 changed all floor plane stuff to have 10000+ layer which causes tram to smash through all of it as it only checks for object layer and not plane when breaking things. This includes tram rails, pipes, lattice, disposals, wires, etc. I went through all other usecases of .layer >/< and everything else seems unaffected.

## Round ID:

Not relevant

## Reproduction:

- Boot up tramstation locally
- Try to call the tram
- See it bulldoze through everything you hold dear to your heart
- Cry

**Comment by lessthnthree** [comment]
Related to https://github.com/tgstation/tgstation/issues/84789

**Comment by lessthnthree** [comment]
There's two parts to this bug. Destroying rails due to not checking plane is fixed in #85229 

Pipes and cable will continue to be destroyed because they're currently on the wrong layer, which is related to #84789
