### ISSUE TITLE
Some machines ticking very slow (e.g. IV drip takes minutes to transfer)

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#85170]
Reporting client version: 515.1641

## Round ID:
[232438](https://scrubby.melonmesa.com/round/232438)

## Testmerges:
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)

## Reproduction:

Noticed this while playing yesterday and still seems to be an issue ; the rate at which some actions "update" has become incredibly slow, for example:
Spawn a human, modify their blood volume to like 100 and spawn an iv_drip and a blood pack, set up a blood transfer to the patient, it appears to transfer about 10u in a step, every say 10 seconds.  Overall a complete blood transfusion has gone to taking minutes to complete.  Which when an empty person might need two bags worth of blood is pretty tedious.

A complete 200u transfusion took 4 minutes 30 seconds just now in testing.

Note the server isn't overly laggy, while running at 80 pop, and much less last night when I observed this, time dilation is stable under 10% and atmos, the great sufferer of server overload is "only" at 600%-1000% (this is perfectly normal nowadays, sadly) and doesn't seem to explain the dramatic increase in time some of these actions take:

Also seems to affect weapon chargers and borg chargers, and probably other things given the variety here, maybe a subsystem commonality.

**Comment by Moonlit2000** [comment]
This also might be affecting the timers on TTVs, I noticed them taking far longer than they should recently

**Comment by Sadboysuss** [comment]
I'm not sure if this is something we can fix

**Comment by iprice** [comment]
This didn't feel like a gradual performance degredation, more like something changed in the last week or so that dramatically changed the rate these things progress.

**Comment by MTandi** [comment]
I have recently made adjustments to the `/datum/controller/subsystem/machines/fire` to make APCs process in cascades. May be somehow related to that. Not sure.

**Comment by LemonInTheDark** [comment]
A:
My initial assumption is this smells strongly of something choking out the rest of the server. I'm not sure what, it could just be client input, it's kind of hard to check right now.
B:
The total tick usage per run is not a useful metric here, what would be more interesting is fire count (the number at the end) <https://github.com/tgstation/tgstation/blob/master/.github/guides/MC_tab.md#subsystem-entries>
I believe our issue is relevant subsystem (machines) is having its windpipe crushed. That's the thing to check here. Does this issue only occur at highpop? is it consistent? What is the value of `tick_allocation_avg` on the subsystem in these cases?

> I have recently made adjustments to the `/datum/controller/subsystem/machines/fire` to make APCs process in cascades. May be somehow related to that. Not sure.

Highly likely, though none of your changes stand out as fucked

**Comment by SyncIt21** [comment]
It might be the AI subsystem that is lagging. Even when testing in local it randomly runtimes with "invalid jps route" which happens when beepsky or some other bot attempts to open an airlock door

**Comment by LemonInTheDark** [comment]
Issue appears to be SSmachines improperly adding extra wait due to sleeps propogating up the chain.

https://github.com/user-attachments/assets/90733b47-f517-4db6-a37e-6e3f1960becd

![image](https://github.com/user-attachments/assets/2989992a-8069-4b94-8101-ef94d080b9a3)

![image](https://github.com/user-attachments/assets/ed57e2b0-cbf3-495a-946d-6af2333f4ad3)

**Comment by SyncIt21** [comment]
Does this still happen?

**Comment by Ghommie** [comment]
Closing for now. It can be reopened if it hasn't been fixed.
