### ISSUE TITLE
Icebox has a CMO telescreen in the security medbay post

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#85182]
## Issue Summary
![image](https://github.com/user-attachments/assets/f1c73a2d-bf15-4efe-a49a-25551c7335e0)

Odd bug. The bounty tracker asked for the CMO's telescreen, but in the security medical area. It can't be unwrenched and moved either.

Also storage items still can't be scanned.

**Comment by MrMelbert** [comment]
![image](https://github.com/user-attachments/assets/b8a16f7a-7d6d-4114-9d29-97e625afc802)
