### ISSUE TITLE
Cyborg apparatuses are unable to put things onto tables

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#85181]
Reporting client version: 515.1641

## Issue Summary
The apparatuses for both the medical and service cyborgs are unable to put their held contents onto tables.
Clicking on the table does nothing, and harm intent just bashes the table with the apparatus.

## Round ID:
[232459](https://scrubby.melonmesa.com/round/232459)

## Testmerges:
- [Spacemove refactor - Newtonian physics](https://www.github.com/tgstation/tgstation/pull/84869)
- [Block atmos processing on ReservedTurfs\:tm: ](https://www.github.com/tgstation/tgstation/pull/84873)
- [More food effects](https://www.github.com/tgstation/tgstation/pull/84889)

## Reproduction:
1.  Become a medical or service cyborg.
2. Equip your beaker/glass holding apparatus.
3. Find a table.
4. Attempt to place the contained container onto the table.
5. Nothing happens.

**Comment by Sadboysuss** [comment]
I don't think you were able to put beakers on tables with the apparatus? Only into machines and drop them on the floor

**Comment by Derpguy3** [comment]
> I don't think you were able to put beakers on tables with the apparatus? Only into machines and drop them on the floor Edit: this isn't bug but more of a feature request. UNLESS before all the refactors it was possible to do this.

I hadn't been aware of a refractor but if there had been one, its most likely broken it by accident.
You were always able to place beakers and glasses onto tables prior.

**Comment by Zergspower** [comment]
> I don't think you were able to put beakers on tables with the apparatus? Only into machines and drop them on the floor Edit: this isn't bug but more of a feature request. UNLESS before all the refactors it was possible to do this.

the Apparatus is a grabber, the internal beaker is the one that cant be moved

**Comment by 00-Steven** [comment]
Looking at it, this seems like it might be an order of operations issue.
Normally, the borg apparatuses run the `melee_attack_chain(...)` as the stored object on their `pre_attack(...)`...
However, this is *after* the item interaction type procs on the table, and thus after it attempts to place the item.

Borg items I believe are not abstract, which would return `NONE` and allow it, rather they're just blocked from being placed, which returns `ITEM_INTERACT_BLOCKING`.
As such, it cuts it short before the `pre_attack(...)` is even ran.

**Comment by 00-Steven** [comment]
It might work to just replace the current behaviour with the relatively new `get_proxy_attacker_for(...)` proc, which should essentially do the same but cutting into the melee attack chain before item interactions.
