### ISSUE TITLE
The contents of indestructible items are not protected from being destroyed by emagged recyclers.

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#85189]
Reporting client version: 515.1640

## Issue Summary

As it says in the title. If an indestructible item goes through an emagged recycler, it still destroys its contents. This includes things like the HoS's energy gun and the antique laser gun.

## Round ID:
[232477](https://scrubby.melonmesa.com/round/232477)

## Testmerges:
- [Block atmos processing on ReservedTurfs\:tm: ](https://www.github.com/tgstation/tgstation/pull/84873)
- [More food effects](https://www.github.com/tgstation/tgstation/pull/84889)
- [Spacemove refactor - Newtonian physics](https://www.github.com/tgstation/tgstation/pull/84869)

## Reproduction:

Step 1: Get a recycler.
Step 2: Emag it.
Step 3: Make an energy gun indestructible.
Step 4: Throw it into the recycler.
Step 5: Inspect its cell. See that it is null.

**Comment by Rhials** [comment]
The same applies to the cremator. I'd wager its necessary though because it's the only way to complete "Destroy the blackbox".

**Comment by necromanceranne** [comment]
The cremator I think straight up deletes anything, but the recycler ignores indestructible stuff because it also happens to destroy things it probably shouldn't (like singulos).

(Also, I feel like the only thing that should delete literally anything should be the supermatter crystal, but that's besides the point)
