### ISSUE TITLE
Metal is ashed in hands if you burn.

### ISSUE THREAD

**Issue by DoomAngelBlade** [tgstation/tgstation#85203]
Reporting client version: 515.1640
## Issue Summary
Orange Flame Temperature - 1000-1200°C
Bright yellow Flame Temperature - 1200-1400°C
Being on fire raises body temp to 1350C.
Titatiun melting point is  1725C
## Reproduction:
Set yourself on fire.
Grab titanium sheet.
Watch it disappear from your hands.

**Comment by Sadboysuss** [comment]
@Pickle-Coding thoughts on this?

**Comment by Pickle-Coding** [comment]
Not sure why my thoughts would be relevant to this, as I've never worked on the handling of burning objects. Titanium has some flammable property or combustible component when it shouldn't. I don't actually know how it's handled. Just look for something that determines the flammability of titanium sheets.

**Comment by DoomAngelBlade** [comment]
If it has fire proof flag - it doesn't melt.

**Comment by Sadboysuss** [comment]
> Not sure why my thoughts would be relevant to this, as I've never worked on the handling of burning objects. Titanium has some flammable property or combustible component when it shouldn't. I don't actually know how it's handled. Just look for something that determines the flammability of titanium sheets.

you're knowledgable about atmos which is why I asked.

**Comment by DoomAngelBlade** [comment]
Update:
Adding LAVA PROOF slime extract to anything 
Doesn't prevent it from being ashed from fire.

![image](https://github.com/user-attachments/assets/27f2e898-7ce4-48d5-a33f-b3c92332ceb9)

**Comment by Sadboysuss** [comment]
> Update: Adding LAVA PROOF slime potion to anything Doesn't prevent it from being ashed from fire.
> 
> ![image](https://private-user-images.githubusercontent.com/46872312/352194729-27f2e898-7ce4-48d5-a33f-b3c92332ceb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MjMxMjEsIm5iZiI6MTcyMTkyMjgyMSwicGF0aCI6Ii80Njg3MjMxMi8zNTIxOTQ3MjktMjdmMmU4OTgtN2NlNC00OGQ1LWEzM2YtYjNjOTIzMzJjZWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDE1NTM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxOGZiM2E5M2JjM2FmODUwZDgxMTEyNmFmZWU0NjAwM2VmNDhkOTY1Zjc3MDUyYWRlNmJkMzNkMzU3Mzg5MTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sjx4FvFSptRe6WkWfznrpwDLETFevJm80coDSFrVeAw)
> 
> And adding lava proof slime potion adds this text to items: ITEM is made of an extremely heat-resistant material, it'd probably be able to withstand lava!

you should make this a separate issue

**Comment by Jewelry-x** [comment]
This is not really a bug report, all the numbers for temperatures are just the first result that comes up on google, there are no melting points set for titanium in the code of the game. The game does not even check if something is fire proof or lava proof before applying damage to its integrity.

**Comment by DoomAngelBlade** [comment]
I haven't played for a long time so it might have changed.
But fireproof items were not ashed. Bone armor / axe.
Some ID cards
Katana

**Comment by Jewelry-x** [comment]
Yes you are correct, fire proof items are not ashed, but there is a distinction between lava proof and fire proof. The best example, as you tried, is the lavaproof potion that makes something ONLY lava proof. If an item does not have the fire proof flag it just gets ashed.
