### ISSUE TITLE
projectile dampener field doesnt drop when mod is disabled + mirage greande dispenser mod doesnt owrk + ion jump jet also doesnt wrok

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#85207]
## Issue Summary

When you dsiable proj dampner teh field stays and is unremavble even if you get striped of modsuit

Mirage greande dispsner  adn ion jump jet go on CD but dont actually do anythnig whne activated

## Reproduction:

Get mod use it

**Comment by deathrobotpunch** [comment]
I had a stroke reading this

**Comment by SyncIt21** [comment]
This is  not how you write issues. Isolate each part into its own issue and put the relevant details into the issue body or wait for a maintainer to close this
