### ISSUE TITLE
Krokodil and its intended effects don't work

### ISSUE THREAD

**Issue by L0pz** [tgstation/tgstation#85206]
Reporting client version: 515.1641

## Issue Summary

Krokodil is supposed to give you a unique krokodil addiction, which makes your skin fall off and turns you into a fake zombie. However, instead of a krokodil addiction, it just gives you a regular opioid addiction and so the effects don't take place
## Round ID:
[232529](https://scrubby.melonmesa.com/round/232529)

## Testmerges:
- [Replaces Auxlua with the byondapi-based Dreamluau](https://www.github.com/tgstation/tgstation/pull/84810)

## Reproduction:

1. Ingest a good amount of krokodil
2. Wait for it to give you a krokodil addiction

**Comment by cnleth** [comment]
Not a bug. This effect only happens when krokodil is low purity

**Comment by L0pz** [comment]
oh
