### ISSUE TITLE
lights can draw negative wattage

### ISSUE THREAD

**Issue by triplezeta** [tgstation/tgstation#85213]
Reporting client version: 515.1635

## Issue Summary

![image](https://github.com/user-attachments/assets/11281060-a754-4125-b622-4dcff396c1fd)

lights are drawing negative electricity, which results in zero power consumption and no discharge of the APC battery even with no external power. It's also worth noting that the backup batteries of all lights slowly charge also under these conditions.

## Round ID:
[232556](https://scrubby.melonmesa.com/round/232556)

## Testmerges:
- [Block atmos processing on ReservedTurfs\:tm: ](https://www.github.com/tgstation/tgstation/pull/84873)
- [Spacemove refactor - Newtonian physics](https://www.github.com/tgstation/tgstation/pull/84869)

## Reproduction:

Did not attempt to replicate at time of opening issue

**Comment by Sadboysuss** [comment]
what kind of lights were in the room? If it was circuit floors then this is a dupe of https://github.com/tgstation/tgstation/issues/84923

**Comment by Sadboysuss** [comment]
please provide more information for reproduction, this will be cleanup flagged and auto closed within 7 days, if you provide more info - I will remove the cleanup flag

**Comment by triplezeta** [comment]
Hi yes, there were circuit floors. I'll close this then since this is a dupe
