### ISSUE TITLE
Wawa Engineering has barely any water.

### ISSUE THREAD

**Issue by iansdoor** [tgstation/tgstation#85214]
When you go into the maints or just the department itself. There is exactly two small water tanks to cool off a multi-Z fire, which is pretty impossible to to take care of. Anyways, each tank is worth up to 10 atmos resin shots and that is not enough to deal with multi-Z plasmafires. The locations of the water tanks are out of the way, instead of in view when needed.

So the changes that are needed is more water tanks in maints and better location/more water tanks in engineering.
![Screenshot_733](https://github.com/user-attachments/assets/20c0df5e-0344-467a-a234-c6c0485cfde4)
![Screenshot_732](https://github.com/user-attachments/assets/100646db-5bd5-464d-b89b-7e5bcfcb126a)

The third nearest water tank is maints 70 tiles away from the engineering lobby.

**Comment by Sadboysuss** [comment]
honestly this is more of a feature request
