### ISSUE TITLE
Atmospheric-thermal mode on visors do not work as intended

### ISSUE THREAD

**Issue by Dingus997** [tgstation/tgstation#85224]
Atmospheric-thermal mode does not work.
## Issue Summary
The atmospheric-thermal mode doesnt work in both the optical t-ray scanner and atmospheric thermal imaging goggles. 

Normally they are suposed to highlight tiles with a color depending on the temperature of said tile, however, in the current state of the game, this option does nothing.
## Round ID:
[232580](https://scrubby.melonmesa.com/round/232580)

## Reproduction:
Equip the optical t-ray scanner and toggle them to the third option, named atmospheric-thermal mode. Equip atmospheric thermal imaging goggles and activate them. In both cases they should highlight tiles based on temperature but they dont.

**Comment by Inari-Whitebear** [comment]
I noticed they seem to highlight floors below, like if you use them in engi foyer on icebox, you have that glass floor there and it blinks below that

**Comment by Sadboysuss** [comment]
I suspect this has to do with multi-z maps. Since scrubby hasn't processed the round yet, could you please provide additional information? What map was this on? Where were you? And what Z level?

**Comment by Sadboysuss** [comment]
likely caused by https://github.com/tgstation/tgstation/pull/84350

**Comment by OverwatchVoice** [comment]
STILL a problem after all these months. Bumping in hopes it gets noticed.
