### ISSUE TITLE
Self resp virus now spamming chat with messages once it hits stage 5

### ISSUE THREAD

**Issue by Thlumyn** [tgstation/tgstation#85237]
## Issue Summary

The self resp virus now spams my chat with "You don't need to breath" messages, despite being at stage 5 and having been at stage for a while. Perhaps since this PR was merged. https://github.com/tgstation/tgstation/pull/85091 

![image](https://github.com/user-attachments/assets/5f502ac8-b530-48aa-8336-4c39bfd484da)

## Round ID:

Reporting from downstream, link to downstream mirror & repo here 
https://github.com/NovaSector/NovaSector/pull/3905

## Reproduction:

I went into VV to take a look during the round, and it looked like the virus was hanging out at stage 5 the whole time. I didn't look too close though but there wasn't anything that could've been lowering the virus stage afaik.

**Comment by EuSouAFazer** [comment]
Have you tested it upstream to make sure it's also a problem here?

**Comment by Thlumyn** [comment]
Yeah, I tested locally on commit 9eb1d5a4e95b13ded723bf2c19150add58db74ba

![image](https://github.com/user-attachments/assets/7784ce5c-ae45-4829-8895-e2a58aaf00f9)

**Comment by FlufflesTheDog** [comment]
started in https://github.com/tgstation/tgstation/pull/85091
