### ISSUE TITLE
Purchasing discounts from NT Frontier does not apply any discounts

### ISSUE THREAD

**Issue by whatisthisplace** [tgstation/tgstation#85234]
## Issue Summary
NT Frontier which used to provide discounts upon purchasing nodes from partners no longer provides discounts after the techweb rework

## Round ID:
N/A - Tested locally

## Reproduction:

1. Get enough reputation with Defense Partnership
2. Buy riot suppression discount
3. cry as 80 points is spent instead of seeing any discount

https://github.com/user-attachments/assets/1f1d3dec-b984-47e2-8eae-3e15df03ae58

**Comment by Sadboysuss** [comment]
@MTandi

**Comment by MTandi** [comment]
@SpaceLoveSs13 took this item (#84375) and was going to fix it via https://github.com/tgstation/tgstation/pull/84177 but I don't think he did the points update to match the new values as NT Frontier has some ambiguous calculation logic relating to the points, boost and funds given.

**Comment by SpaceLoveSs13** [comment]
> @SpaceLoveSs13 took this item (#84375) and was going to fix it via #84177 but I don't think he did the points update to match the new values as NT Frontier has some ambiguous calculation logic relating to the points, boost and funds given.
> 
> Though it seems to be broken since before the techweb change.
> 
> I made the discount experiments always give the full discount, and the goal is to have all 3-5 nodes have some discount experiments so that people have an alternative research path when the points are in demand by the queue. I have a branch that updates the partners to discount nodes that don't overlap with the discount experiments, but Ideally their discounts should be reduced with the introduction of new experiments, and removed completely later.
> 
> Also I plan to decouple NT frontier from gas shells and make compressor upload directly to the techweb, to allow atmos techs to participate in the research, then the app won't be needed at all.
> 
> I'll take a look again, but I'm leaning towards removal of NT frontier app (hiding until someone wants to refactor it) as people find it annoying and don't engage with the research papers as intended.

The points were updated with the DEFINES, however, if the actual system is broken in transferring the discount, then yeah...
The documentation for the calculation as well as the discounting is totally very much lacking. A complete removal of frontier to move to a more direct approach in uploading research would be nice. But only if they are done together, removing the former without the latter will make RnD very linear imo.
