### ISSUE TITLE
monkey wizards can't do grand rituals

### ISSUE THREAD

**Issue by Loafin34** [tgstation/tgstation#85267]
## Issue Summary
when you transform into a monkey via magic mirror, you sacrifice the ability to manipulate machines for the ability to ventcrawl. This is fine on paper, but due to how ss13 works, a grand ritual is a machine, and monkeys cannot use them. I was a monkeymancer, and tried being a gorilla and a monkey, but both didn't work.

**Comment by Sadboysuss** [comment]
A good solution to this could be a subtype of monkey without those traits and put that in the magic mirror

**Comment by BlueMemesauce** [comment]
> A good solution to this could be making a subtype of monkey without those traits and putting that in the magic mirror

its meant to have advantages and disadvantages

**Comment by Sadboysuss** [comment]
it's the wizard, balance isn't a problem
