### ISSUE TITLE
New Fish Imports let you print money ordering and shipping back crates of fish

### ISSUE THREAD

**Issue by OrbisAnima** [tgstation/tgstation#85284]
## Issue Summary

As it sounds, you can basically order fish from cargo at 400 credits, and then resell the fish inside with the crate they come in, not even needing to open the crate, and get an amount thats similar from what you initially put to 5x times as much

## Reproduction:

Order the Aquarium Fish case crate from cargo,. or any of the others fish cases.
wrap the crate on paper
put a cargo ticket 
Enjoy!

Scanned the aquarium fish crate - Purchased by The Gaucho - # 8663 and its contents, total value: 875 credits.
Scanned the aquarium fish crate - Purchased by The Gaucho - # 8664 and its contents, total value: 2630 credits.

**Comment by OrbisAnima** [comment]
@Ghommie , you might want to remove the crates being orderable from cargo, although I would leave an easy way to get cases

**Comment by Time-Green** [comment]
Of fucking COURSE AHHHHHHHH FISH ECONOMY IN SHAMBLES

**Comment by OrbisAnima** [comment]
the other way, which might keep everyone happy, is to set fishes generated like it a custom export value of 0

**Comment by Ghommie** [comment]
I know how to fix it.
