### ISSUE TITLE
Birdshot's Holodeck Arcade... isn't area'd?

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#85280]
Reporting client version: 515.1641

## Issue Summary
for some reason, that whole room is just... fullbright? Is it linked to the holodeck itself a little too much, or...?

## Round ID:
[232676](https://scrubby.melonmesa.com/round/232676)

## Testmerges:
- [Block atmos processing on ReservedTurfs\:tm: ](https://www.github.com/tgstation/tgstation/pull/84873)
- [Spacemove refactor - Newtonian physics](https://www.github.com/tgstation/tgstation/pull/84869)
- [fuck](https://www.github.com/tgstation/tgstation/pull/85264)

## Reproduction:
![image](https://github.com/user-attachments/assets/b52b34c2-55ce-4ba9-a9dd-d1385fad4fe6)

**Comment by Sadboysuss** [comment]
wtf?? maybe testmerge bug?

**Comment by AdipemDragon** [comment]
no it's... just one of those that nobody really reported, it's been kind of like this for a while

**Comment by Sadboysuss** [comment]
what map?

**Comment by Sadboysuss** [comment]
also is this only an issue on this map or on all holodeck areas?

**Comment by AdipemDragon** [comment]
the arcade that's specifically east of birdshot's holodeck

**Comment by Sadboysuss** [comment]
yeah I see the problem
