### ISSUE TITLE
Gulagging plasmamen kills them

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#85296]
Reporting client version: 515.1642

## Round ID:
[232698](https://scrubby.melonmesa.com/round/232698)

## Testmerges:
- [Block atmos processing on ReservedTurfs\:tm: ](https://www.github.com/tgstation/tgstation/pull/84873)
- [Spacemove refactor - Newtonian physics](https://www.github.com/tgstation/tgstation/pull/84869)
- [fuck](https://www.github.com/tgstation/tgstation/pull/85264)

## Reproduction:
If you gulag a plasmaman it removes their plasma tank which pretty much guarantees their death

**Comment by SmArtKar** [comment]
Doesn't seem to be happening on live, there is code to prevent that and it is successfully working. Unless there's more details this'll be closed in a week

**Comment by xzero314** [comment]
Ive seen this happen twice in the last couple days. Its happening for sure

**Comment by Sadboysuss** [comment]
> Ive seen this happen twice in the last couple days. Its happening for sure

If you see it ingame , please provide reproduction info here.
