### ISSUE TITLE
entering Beaconed paddy mech removes A.I from core, cannot control mech

### ISSUE THREAD

**Issue by RoderickGrey** [tgstation/tgstation#85295]
## Issue Summary
As A.I, jumping into a beaconed paddy removed A.I from its core, cannot use mech or re-enter core. can however jump to shell

## Reproduction:

Be an A.I, try to enter a beaconed paddy while having a shell connected.

**Comment by Sadboysuss** [comment]
Dupe of https://github.com/tgstation/tgstation/issues/85136
