### ISSUE TITLE
Deep fried energy guns can still fire

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#85315]
## Issue Summary
What it says on the tin

## Round ID:
Fulpstation

## Reproduction:
Deep-fry an energy gun and try to shoot it.

**Comment by GPeckman** [comment]
This is intentional, deep fried items are supposed to be functional as of #71551

**Comment by Sadboysuss** [comment]
> This is intentional, deep fried items are supposed to be functional as of #71551

ok that sucks
