### ISSUE TITLE
Being heretic sacced round removes you

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#85325]
Reporting client version: 515.1642

## Round ID:
[232749](https://scrubby.melonmesa.com/round/232749)

## Testmerges:
- [Block atmos processing on ReservedTurfs\:tm: ](https://www.github.com/tgstation/tgstation/pull/84873)
- [Spacemove refactor - Newtonian physics](https://www.github.com/tgstation/tgstation/pull/84869)
- [fuck](https://www.github.com/tgstation/tgstation/pull/85264)
- [Death of mutant bodyparts AND external organs](https://www.github.com/tgstation/tgstation/pull/85137)

## Reproduction:
![image](https://github.com/user-attachments/assets/dab3b0c4-c2f4-4377-8472-db61cd4c16e6)
Pictured below. Three bodies who died instantly as they were sent to the mansus, only one of them is DNR. I got no clue what the cause is but you're literally stuck there forever

**Comment by Sadboysuss** [comment]
likely test merge bug

**Comment by Sadboysuss** [comment]
https://github.com/tgstation/tgstation/pull/85137

**Comment by Time-Green** [comment]
Caused by https://github.com/tgstation/tgstation/pull/85137
