### ISSUE TITLE
Lungs not being implanted.

### ISSUE THREAD

**Issue by JohnHenryEton** [tgstation/tgstation#85321]
Reporting client version: 515.1641

## Issue Summary
Surgically implanting lungs into ashwalkers and lizards (confirmed and tested by myself, not sure about others) causes nothing. No lungs added and the game still acts like they don't have lungs (oxygen damage,  health analyzer saying no lungs)

## Round ID:
[232746](https://scrubby.melonmesa.com/round/232746)

## Testmerges:
- [Block atmos processing on ReservedTurfs\:tm: ](https://www.github.com/tgstation/tgstation/pull/84873)
- [Spacemove refactor - Newtonian physics](https://www.github.com/tgstation/tgstation/pull/84869)
- [fuck](https://www.github.com/tgstation/tgstation/pull/85264)
- [Death of mutant bodyparts AND external organs](https://www.github.com/tgstation/tgstation/pull/85137)

## Reproduction:
Perform organ manipulation surgery, attempt to implant lungs. No lungs implanted, lungs are consumed.

**Comment by norsvenska** [comment]
happens to every organ you try to insert, including brains. i ahelped, apparently they get sent to nullspace

**Comment by Tuckatk** [comment]
Just made a report on it too whoops, seems about right. Know one patient had four hearts inserted into them with no luck.

**Comment by norsvenska** [comment]
tested on local, works fine. seems to be a testmerge issue

**Comment by norsvenska** [comment]
confirmed to be #85137

**Comment by Sadboysuss** [comment]
To be more specific:
Placing organs in a body sends them to nullspace.

**Comment by Time-Green** [comment]
https://github.com/tgstation/tgstation/pull/85137

**Comment by Time-Green** [comment]
Also I'm really confused why this didn't trigger any of our tests? Will have to look into that
