### ISSUE TITLE
Organs Disappear Upon Insertion

### ISSUE THREAD

**Issue by Weisyl** [tgstation/tgstation#85328]
Reporting client version: 515.1641

## Issue Summary

When inserting organs into people, they seem to immediately disappear upon completion of the insert action, even if successful. Encountered this multiple times when trying to transplant (multiple) tongues into one person, and then later with a different person when trying to insert a liver. Obviously, this is REALLY bad as it makes reviving people without admin intervention FAR more difficult (and maybe impossible?)
Possibly related to the death of mutant bodyparts and external bodyparts testmerge??

## Round ID:
[232753](https://scrubby.melonmesa.com/round/232753)

## Testmerges:
- [Block atmos processing on ReservedTurfs\:tm: ](https://www.github.com/tgstation/tgstation/pull/84873)
- [Death of mutant bodyparts AND external organs](https://www.github.com/tgstation/tgstation/pull/85137)

## Reproduction:

Have somebody with a missing organ, or remove then try to re-insert an organ. The organ-to-be-implanted will immediately disappear upon completion. Multiple times when using a health scanner, they were reported as still missing the organ, whether or not I had used a cautery after inserting the organ. This occurred whether on a stasis bed or operating table. P

**Comment by SyncIt21** [comment]
Duplicate #85323
