### ISSUE TITLE
Ai doesnt have new radio noises

### ISSUE THREAD

**Issue by demir-pl** [tgstation/tgstation#85334]
## Issue Summary

AI cant hear the radio pings/beeps etc.
stuff from the #85115 basically ai cant hear any of that

## Testmerges:

[#84810: 'Replaces Auxlua with the byondapi-based Dreamluau' by Y0SH1M4S73R at commit 48d38d2bd1](https://www.github.com/tgstation/tgstation/pull/84810)

## Reproduction:

become ai and speak on radio - you dont hear no beeps or anything - other people can hear your beeps

**Comment by Sadboysuss** [comment]
@DrDiasyl is this intentional?

**Comment by DrDiasyl** [comment]
> @DrDiasyl is this intentional?

No. I think this is happening cus it is looking for a carbon, and AI not a carbon..?

**Comment by Sadboysuss** [comment]
> No. I think this is happening cus it is looking for a carbon, and AI not a carbon..?

carbons are mobs with hands, AI is silicon
