### ISSUE TITLE
heart eater oversight

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#85364]
## Issue Summary
The heart eater perk for a wizard allows them to get damage resistance when eating hearts.
The issue is it also works for eating cybernetic hearts when they're deep-fried.

## Round ID:
local

## Reproduction:
1. pick heart eater perk as a wizard
2. deep-fry a cybernetic heart
3. eat it
4. profit

**Comment by Sadboysuss** [comment]
@Xackii is this an oversight of your feature or emergent gameplay?

**Comment by carlarctg** [comment]
1000% feature and eemrgent gameplay if you remove this i am no longer friends with you

**Comment by Sadboysuss** [comment]
pretty op since you can get up to 80% innate damage resist (10% per heart), plus they act as wound healers and heal 50 damage of every type

**Comment by Xackii** [comment]
> @Xackii is this an oversight of your feature or emergent gameplay?

XD
