### ISSUE TITLE
Ninja suit is lost when the ninja is monkey'd through SE injectors.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#8537]
Also, ninja can be injected with an SE syringe, but not regular syringes. Also it kicked me out of my body. ALSO you survive as a MODE if you're a monkey like this at the end of the round.

**Comment by RemieRichards** [comment]
Not a bug.

The Suit has NODROP while active, which means when it was forced off the ninja they were deleted.

**Comment by WJohn** [comment]
Being kicked out of your body is probably a bug, though, and it really shouldn't be able to inject you if regular syringes can't. Of course SE injectors aren't actually syringes but come on...

**Comment by Miauw62** [comment]
NODROP does NOT imply del on drop, it's just a feature some NODROP items
have as an extra safety (but del on drop causes runtimes anyway, I recall
shocking yourself on a grille with something that dels on drop causing a
runtime)
Op 25-mrt.-2015 13:57 schreef "WJohn" <notifications@github.com>:

**Comment by WJohn** [comment]
This is technically impossible to really achieve now because space ninja clothing is syringe proof. Closing.
