### ISSUE TITLE
Subtype vendor requires an ID

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#85378]
Reporting client version: 515.1641

## Issue Summary
Debug items shouldn't need normal circumstances

## Round ID:
local

**Comment by SmArtKar** [comment]
free vendors in general shouldn't require IDs, weird

**Comment by Sadboysuss** [comment]
> free vendors in general shouldn't require IDs, weird

maybe because it needs an ID to record it in the HoP's bank management console?
