### ISSUE TITLE
Instrument beacon uses the wrong pod

### ISSUE THREAD

**Issue by dalmationer** [tgstation/tgstation#85385]
## Issue Summary

Instrument beacons call down the cult pod, instead of the NT pod, which looks very strange.

## Reproduction:

Use an instrument beacon.

**Comment by necromanceranne** [comment]
Oh man, thanks for posting this because I keep forgetting.

I think literally any instance where the pod isn't pre-selected, the pod set will always be the cult pod. I had someone double take when I got a synthesizer out of a blood oozing pod.

**Comment by Jacquerel** [comment]
we should use the transparent pod, give it a flame trail, and make some kind of guitar smash/accordion noise upon landing

**Comment by OuroborusReporter** [comment]
Legendary Skill pods have been doing the same thing
