### ISSUE TITLE
Can't build portable scruber and portable pump

### ISSUE THREAD

**Issue by Dingus997** [tgstation/tgstation#85384]
Reporting client version: 515.1641

I was unable to finish building a portable air scrubber and portable air pump
## Issue Summary
I've seen that they added the freature of building portable scrubbers and pumps for a while but only recently I attempted to actually build said machines. Upon trying, I realized that the machine frames refuse to accept the only component necesary to complete it: a pipe. When trying to add the component it shows a message saying "can't add to that!". I assume from the vague description that 1 pipe refers to one pipe fitting, which can be printed with a rapid piping device. When that failed, I tried seeing if could find other components named "pipe" so I tried a disposals pipe which does show up as just "pipe", however it was not effective. Next I tried to use the crafting menu and to my surprise the crafting menu has 2 separate options for a pipe, one which shows as "smart pipe fitting" and another just as "pipe". I tried to use the regular pipe option which also did not work so at this point I considered the problem to be a bug of some sort which is why Im reporting it here now.

## Round ID:
[232846](https://scrubby.melonmesa.com/round/232846)

## Testmerges:
- [Block atmos processing on ReservedTurfs\:tm: ](https://www.github.com/tgstation/tgstation/pull/84873)
- [Makes cyborg damage more... showy](https://www.github.com/tgstation/tgstation/pull/85298)

## Reproduction:
Print either a portable air pump or portable air scrubber from the engineering board printer.
build a machine frame and add cables to it.
Add either board and try to add the listed component.

**Comment by Sadboysuss** [comment]
It's probably the same requirement as improvised explosives: round start atmos pipe or a pipe made from the shitty pipe dispenser machine. Technically, it's not a bug but should be conveyed better as it's not very intuitive

**Comment by Sadboysuss** [comment]
> a filter for the pipe scrubber, a scrubber for the scrubber, etc. 

If that's the case then you're right, I'll check it out

**Comment by MTandi** [comment]
They are buildable and they allow RPD, dispensed and crafted (via crafting menu) versions of pipe fittings - filter fitting for pipe scrubber, scrubber fitting for air scrubber, vent fitting for the air pump.

The only bug here is with all the fittings saying "Pipe"

**Comment by MTandi** [comment]
Yeah, addressed the other issues, thank you
