### ISSUE TITLE
You cannot edit the stat panel font size

### ISSUE THREAD

**Issue by GhostPlayer6942** [tgstation/tgstation#85395]
## Issue Summary
Changing the stat pannel font size does nothing

## Round ID:
[232858](https://scrubby.melonmesa.com/round/232858)

## Testmerges:
The following pull requests are currently test merged:
[#84873: 'Block atmos processing on ReservedTurfs\:tm: ' by ZephyrTFA at commit e3480139fa](https://www.github.com/tgstation/tgstation/pull/84873)
[#85298: 'Makes cyborg damage more... showy' by dragomagol at commit ddfa3dcc9f](https://www.github.com/tgstation/tgstation/pull/85298)
[#85371: '[TM only] Roundstart Traitors will not have side objectives' by Jacquerel at commit 1bd4f93a8a](https://www.github.com/tgstation/tgstation/pull/85371)
[#85257: 'Refactor Stat Panel styles and more TGUI-like appearance' by AyIong at commit 417b3eae36](https://www.github.com/tgstation/tgstation/pull/85257) 

## Reproduction:
open chat settings
click the button next to the font size bar that says "chat" and it'll turn into "stat panel"
try to change the size

**Comment by AyIong** [comment]
You need to first unlink Stat Panel from the chat font size, there's a red button on the right hand side
![image](https://github.com/user-attachments/assets/67c196a8-9908-4f7d-b338-e0f8716eeefb)

**Comment by Sadboysuss** [comment]
https://github.com/tgstation/tgstation/pull/85392

**Comment by lessthnthree** [comment]
Fixed since https://github.com/tgstation/tgstation/pull/85399
