### ISSUE TITLE
Statpanel doesn't respect font selection

### ISSUE THREAD

**Issue by lessthnthree** [tgstation/tgstation#85396]
## Issue Summary

Statpanel always displays in Verdana, no matter what font is selected in options.

## Round ID:

[232859](https://scrubby.melonmesa.com/round/232859)

## Reproduction:

Pick a font other than Verdana

**Comment by MrStonedOne** [comment]
dupe of #85395

**Comment by lessthnthree** [comment]
85395 is for the font size box, this is for the font selection.

**Comment by AyIong** [comment]
It doesn't have to, only the ability to change the font size has been added

**Comment by lessthnthree** [comment]
Yeah, I was corrected it's not actually TGUI.
