### ISSUE TITLE
Spy miners can complete bounties on the lavaland mining station

### ISSUE THREAD

**Issue by GhostPlayer6942** [tgstation/tgstation#85402]
## Issue Summary
Normally when you're a specific job and theres a bounty thats in your department, you arent allowed to complete it because its "too easy". For miners though the mining outpost isnt considered "too easy"

## Reproduction:
Be shaft miner spy
RNG
Get a bounty to steal something from the mining outpost
![image_2024-07-29_234540476](https://github.com/user-attachments/assets/5b0aa666-a845-42ce-913d-dac15ffe0c96)

**Comment by MrMelbert** [comment]
Most (if not all) machine bounties don't exclude due to difficulty (only item bounties and mobs? iirc), so this is WAD 

Though people are free to change it

**Comment by Sadboysuss** [comment]
this will be cleanup flagged and auto-closed in 7 days in case you have any more questions.
