### ISSUE TITLE
Stealth implants can be detected with the contraband scanner

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#85419]
## Issue Summary
So the new contraband scanner feature allows you to detect stealthy implants such as:
- storage implant
- stealth implant
- freedom implant
- idk other stealth implants, probably

## Round ID:
Revealed to me in discord (dream)

## Reproduction:
1. Use the contraband scanner on a person that has a stealthy implant

**Comment by Rhials** [comment]
![image](https://github.com/user-attachments/assets/c3b4b1e6-9682-4f0d-b048-5312c8a6fbcc)

I can't seem to replicate this on local. I could bypass a contraband scanner and scanned myself with no issues. Maybe the reporter had some contraband they didn't realize on them?

I don't believe any of the implants have `SYNDIE_TRIPS_CONTRABAND` either so I don't see why they would be detected either.

**Comment by Sadboysuss** [comment]
> ![image](https://private-user-images.githubusercontent.com/28870487/353518275-c3b4b1e6-9682-4f0d-b048-5312c8a6fbcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNTM2NDIsIm5iZiI6MTcyMjM1MzM0MiwicGF0aCI6Ii8yODg3MDQ4Ny8zNTM1MTgyNzUtYzNiNGIxZTYtOTY4Mi00ZjBkLWIwNDgtNTMxMmM4YTZmYmNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDE1MjkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyZmFkYTdjYTAyODU4NGU4NTEyZWFkMGJlZGM4MTlhOWQ3MDhiOTk1MjcxZGZjNDFmOWE3YzAwZmY5NTc4YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i7W-6HyfcjVyNEvnhA3y1dkRuBbr80dfsW7dRxw2RDs)
> 
> I can't seem to replicate this on local. I could bypass a contraband scanner and scanned myself with no issues. Maybe the reporter had some contraband they didn't realize on them?
> 
> I don't believe any of the implants have `SYNDIE_TRIPS_CONTRABAND` either so I don't see why they would be detected either.

it's the other contraband scanner, not the contraband GATE

**Comment by Sadboysuss** [comment]
I was lied to.
