### ISSUE TITLE
Scanner gate inconsistency with N-spect scanner

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#85423]
Reporting client version: 515.1641

## Issue Summary

https://github.com/user-attachments/assets/e4178bbc-9dd9-405c-9cf4-e1dc6b6a576e

## Round ID:
local

## Reproduction:
Video

**Comment by Sadboysuss** [comment]
> I believe you have to attach the n-spect scanner to the scanner gate for it to detect contraband natively?

oh my god.. really?

**Comment by Rhials** [comment]
> > I believe you have to attach the n-spect scanner to the scanner gate for it to detect contraband natively?
> 
> oh my god.. really?

Noticed this when I was testing the last report, didn't think much of it though.

![image](https://github.com/user-attachments/assets/8fd1a625-a4f6-45a4-94b1-c07efe5bfb28)

Looks to be a thing though.

**Comment by Sadboysuss** [comment]
Okay lemme try it with N-spect scanner on the gate, this is what happens when you don't play the game anymore

**Comment by Inari-Whitebear** [comment]
You also have to tell it what to detect, no? So you click the gate and select what it should detect. One option is Contraband, which is disabled/greyed out when you don't attach an N-spect scanner.

**Comment by Shadow-Quill** [comment]
Can confirm that scanner gates on contraband mode alert on ritual daggers.

**Comment by lessthnthree** [comment]
If there's an issue with an item once it's confirmed on the gate, add it to https://github.com/tgstation/tgstation/issues/85086
