### ISSUE TITLE
Raw durathread bundles make metallic sounds when dropped and picked up

### ISSUE THREAD

**Issue by cnleth** [tgstation/tgstation#85433]
Reporting client version: 515.1641

## Issue Summary
Self-explanatory. They probably inherit the sound from base stack materials

## Round ID:
[232895](https://scrubby.melonmesa.com/round/232895)

**Comment by Sadboysuss** [comment]
If someone wants to fix this: just apply either the cloth sound to it or the skin sounds introduced in https://github.com/tgstation/tgstation/pull/85254
