### ISSUE TITLE
Slimes can jump on you from inside the xenobiology console

### ISSUE THREAD

**Issue by Blockaboo** [tgstation/tgstation#85466]
Reporting client version: 515.1640

## Issue Summary
If a living slime is inside of a xenobiology console it can attack the user of the console when they are standing next to it

## Round ID:
[232953](https://scrubby.melonmesa.com/round/232953)

## Reproduction:
Pick up a slime with the xenobiology console, if the slime is aggroed onto you then it will jump onto you from inside of the xenobiology console

**Comment by deathrobotpunch** [comment]
FUCK moment
