### ISSUE TITLE
Vending machines start off with no items in them

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#85477]
Reporting client version: 515.1642

## Round ID:
[232970](https://scrubby.melonmesa.com/round/232970)

## Testmerges:
- [Block atmos processing on ReservedTurfs\:tm: ](https://www.github.com/tgstation/tgstation/pull/84873)
- [Makes cyborg damage more... showy](https://www.github.com/tgstation/tgstation/pull/85298)
- [[TM only] Roundstart Traitors will not have side objectives](https://www.github.com/tgstation/tgstation/pull/85371)
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)
- [fuck](https://www.github.com/tgstation/tgstation/pull/85264)

## Reproduction:
![image](https://github.com/user-attachments/assets/c697f37f-caaa-45c0-be33-4117b9e7e0b5)

**Comment by Metekillot** [comment]
whoops

**Comment by deathrobotpunch** [comment]
is this the case for every vending machine?

**Comment by SmArtKar** [comment]
no, doesn't seem to be

**Comment by Metekillot** [comment]
> is this the case for every vending machine?



All the ones that have refill canisters

> no, doesn't seem to be

There be dragons in _vending.dm
