### ISSUE TITLE
Dehydrator items cannot be removed once inserted

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#85484]
## Reproduction:
Put some blood sausages in the dehydrator to dry out
Can't seem to take them out
![image](https://github.com/user-attachments/assets/bd4858a6-ffae-41ad-ae35-eb7bc69fdc6b)

**Comment by SmArtKar** [comment]
Seems to be working on live?

**Comment by Sadboysuss** [comment]
Please provide new reproduction steps or provide a video reenacting the issue. Otherwise, it will be auto-closed in 7 days.
