### ISSUE TITLE
Spamming both resist and movement keys while aggressive grabbed doesn't trigger the cooldown of the other

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#85486]
## Issue Summary
Reported on discord. This should trigger a universal cooldown if it isn't already

## Round ID:
Hearsay

## Reproduction:
1. Be aggro grabbed
2. Spam both resist and movement keys
3. Trigger double the resist.

**Comment by necromanceranne** [comment]
Oh boy, this broke again huh?

**Comment by Sadboysuss** [comment]
> Oh boy, this broke again huh?

It's hearsay, could be false idk
