### ISSUE TITLE
Chameleon gun doesn't work for pacifists

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#85496]
## Issue Summary

Paccies cant shoot fake gun

## Reproduction:

be pacifist shoot gun

**Comment by TheVekter** [comment]
Working as intended, pacifists cannot fire guns.

**Comment by GPeckman** [comment]
Pacifists can fire non-harmful guns, including disablers and practice lasers. I don't see why the chameleon gun should be any different.
