### ISSUE TITLE
egg fried rice doesn't use a bowl and doesn't spawn a bowl but is in a bowl

### ISSUE THREAD

**Issue by Loafin34** [tgstation/tgstation#85509]
## Issue Summary
egg fried rice just uses a fried egg, some soy sauce, and boiled rice, but is contained in a bowl. my immersion is RUINED.

## Round ID:
[233128](https://scrubby.melonmesa.com/round/233128)

## Testmerges:
none

## Reproduction:
craft egg fried rice (comes in bowl, without using bowl)
eat egg fried rice (no bowl left behind..)

**Comment by Sadboysuss** [comment]
bruh

**Comment by Sadboysuss** [comment]
Spessmen just eat the bowl, duh.

**Comment by r3dj4ck0424** [comment]
looks like there's a whole bunch of bowl-related recipes missing bowls in the crafting
(though eating them in a private test server got me the bowls left behind for some reason?)

**Comment by Sadboysuss** [comment]
This can be solved in two ways:
Option 1: Give every bowl related recipe a requirement of a bowl to create it and spit out the bowl once it's eaten (sucks)
Option 2: Change every food that uses a bowl's sprite to be without a bowl (a lot of effort)

Whatever you do, don't make it spit out the bowl if it didn't require one in the first place, for obvious reasons.

**Comment by Loafin34** [comment]
option 1 sounds easier
