### ISSUE TITLE
Spies cannot complete donut theft bounty

### ISSUE THREAD

**Issue by dalmationer** [tgstation/tgstation#85516]
## Issue Summary

Spies cannot complete the doughnut theft bounty, as their pda when used on one simply attempts to put itself inside of the container

## Reproduction:
-roll spy, get a doughnut theft bounty
-right click the doughnut box
-you will be unable to complete the bounty

**Comment by Inari-Whitebear** [comment]
I think this is like a generic issue with all containers. Modsuits too, you have to remove the storage module before you can steal it.
