### ISSUE TITLE
punji stick invisible on perspeciteve

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#85527]
## Issue Summary

punji stick cant be seen in  Walening tsetmerge in certain perspectives -such as horizontal doors

## Reproduction:
![image](https://github.com/user-attachments/assets/98e52025-5019-407b-a31d-b22dccb049d0)

Make punji stick in horizontal airlock
It is invisible

**Comment by Jacquerel** [comment]
Please write a more descriptive issue report, for instance illustrating where they're actually supposed to be in the image.

**Comment by carlarctg** [comment]
ok
