### ISSUE TITLE
Character sprite in wheelchair looks like they are standing on top of wheelchair in wallening

### ISSUE THREAD

**Issue by Treachce** [tgstation/tgstation#85522]
## Issue Summary
When in sitting a wheelchair with the wallening testmerged, the player sprite will look as if they were standing on top of the wheelchair instead of sitting in it.

## Round ID:
[233188](https://scrubby.melonmesa.com/round/233188)
[Round ID]: #233188

## Testmerges:
#85491 

## Reproduction:
Just start as a paraplegic during the wallening and see for yourself. I tried to get good screenshots but they didn't save, but this isn't too hard to replicate on your own.

**Comment by Jacquerel** [comment]
This is essentially true of all vehicles.

**Comment by LemonInTheDark** [comment]
Should be resolved
