### ISSUE TITLE
Glass Wall is not transparent, nor looks like glass [Wallening]

### ISSUE THREAD

**Issue by Jacquerel** [tgstation/tgstation#85526]
## Issue Summary

To be more clear, the walls do not block line of sight, but visually do not look like they are made of glass at all.

![image](https://github.com/user-attachments/assets/af5ad931-2c1a-4bf5-8ac9-6f8ed16f38b1)
I am going to assume that given how walls work it also _cannot_ be transparent so this maybe isn't solveable but in that case we should... block making glass walls? Make an entirely new sprite for a glass wall which isn't transparent but at least sort of looks the part? Spawn a window instead? Surely glass walls are the same as fulltile windows anyway right?

## Testmerges:

https://github.com/tgstation/tgstation/pull/85491

## Reproduction:

Spawn Wall Girder
Spawn Glass Sheet
Hit Wall Girder with Glass Sheet

**Comment by GPeckman** [comment]
Glass walls are not currently the same as windows. They block lasers and can't be destroyed through damage like normal windows can.

**Comment by Jacquerel** [comment]
> Glass walls are not currently the same as windows. They block lasers and can't be destroyed through damage like normal windows can.

All of those things sound undesirable for a glass wall so that doesn't matter that much to me. Replacing them with windows would be the lazy way out though, preferably we don't do that.

**Comment by lessthnthree** [comment]
Something that looks like frosted glass would be nice.

**Comment by moocowswag** [comment]
> > Glass walls are not currently the same as windows. They block lasers and can't be destroyed through damage like normal windows can.
> 
> All of those things sound undesirable for a glass wall so that doesn't matter that much to me. Replacing them with windows would be the lazy way out though, preferably we don't do that.

This is because the glass is placed onto a metal girder , not hiding the metal girder but protecting it from direct assault with a layer of glass, allowing you to see through like a normal girder but blocking lasers like a normal girder..
