### ISSUE TITLE
Radio noise can still be heard with prefs off

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#85539]
## Issue Summary
standing on the same tile as another mob that has a radio will play the sound for you if you are near them and have the pref turned off

## Round ID:
local

## Reproduction:
1. stand in 1 tile proximity to a mob with a radio
2. trigger a radio message

**Comment by SmArtKar** [comment]
...unable to reproduce and highly confused at what could even cause that in the code? since it directly sends sounds to clients

**Comment by Sadboysuss** [comment]
> Member

I'll try to get a vid next time I see it then

**Comment by Sadboysuss** [comment]
it's definetly still happening, I could hear radio noise through walls, still no vid tho
