### ISSUE TITLE
Cyborgs attempt to look up or down repeatedly once attempted

### ISSUE THREAD

**Issue by btcbuster** [tgstation/tgstation#85532]
Reporting client version: 515.1641

## Issue Summary
Cyborgs attempt to look up or down repeatedly once attempted

## Round ID:
[233196](https://scrubby.melonmesa.com/round/233196)

## Testmerges:
- [Block atmos processing on ReservedTurfs\:tm: ](https://www.github.com/tgstation/tgstation/pull/84873)
- [Refactor Stat Panel styles and more TGUI-like appearance](https://www.github.com/tgstation/tgstation/pull/85257)
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)

## Reproduction:

As a cyborg, hitting the look down or look upwards button will cause the fail message to proc repeatedly everytime you move (Experienced on Metastation)

**Comment by btcbuster** [comment]
> I tried to reproduce this, unless you mean that you hold down the button constantly while moving around, what you are describing is not something I can reproduce.

It may have been fixed by unrelated things.  To make it clear I was referring to the look across z levels mechanic. At the time I pressed look upwards in the OOC tab and every time I would move it would reactivate the message about the lack of another floor

**Comment by Jewelry-x** [comment]
Oh I used the keybinds (L and ;) and it worked fine but you are right! Pressing the IC buttons does do that constantly.

**Comment by Jewelry-x** [comment]
After further investigation, the behaviour of the "Loop Up" and "Loop Down" buttons is that of a toggle button, so that part is not a bug, but an exception happens in maps with only 1 z level that makes it so you can't stop looking up or down once you attempt it.
