### ISSUE TITLE
[WALLENING] Firelocks render OVER doors, especially windoors

### ISSUE THREAD

**Issue by Metekillot** [tgstation/tgstation#85547]
## Issue Summary

It makes them REALLY hard to click.

## Reproduction:

DOOR STUCK DOOR STUCK

**Comment by lessthnthree** [comment]
Also the firelock on the "north" (upper) side falls down in front of the door when its placement would be on the other side of the door pane.

**Comment by Sadboysuss** [comment]
Firelocks always blocked an airlocks why is this a problem now?

**Comment by Inari-Whitebear** [comment]
> Firelocks always blocked airlocks why is this a problem now?

Cause now they're a big more visible box
