### ISSUE TITLE
[WALLENING] Wheelchair miracles

### ISSUE THREAD

**Issue by Metekillot** [tgstation/tgstation#85548]
Reporting client version: 515.1642

## Issue Summary

![image](https://github.com/user-attachments/assets/cff587d1-5573-4925-9dde-661fa60df69b)

## Round ID:
[233244](https://scrubby.melonmesa.com/round/233244)

## Testmerges:
- [Block atmos processing on ReservedTurfs\:tm: ](https://www.github.com/tgstation/tgstation/pull/84873)
- [Makes cyborg damage more... showy](https://www.github.com/tgstation/tgstation/pull/85298)
- [[TM only] Roundstart Traitors will not have side objectives](https://www.github.com/tgstation/tgstation/pull/85371)
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)
- [fuck](https://www.github.com/tgstation/tgstation/pull/85264)
- [Wallening [IDB IGNORE] [MDB IGNORE]](https://www.github.com/tgstation/tgstation/pull/85491)

**Comment by Twaticus** [comment]
#85522
