### ISSUE TITLE
Infinite Telecrystals

### ISSUE THREAD

**Issue by GoblinBackwards** [tgstation/tgstation#85542]
## Issue Summary
When you try to withdraw TC from the uplink, pressing cancel will add 1 TC to your hand without removing any from the uplink.

## Testmerges:
[#85392: '[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"' by MrStonedOne at commit a388037701](https://www.github.com/tgstation/tgstation/pull/85392)
[#85491: 'Wallening [IDB IGNORE] [MDB IGNORE]' by LemonInTheDark at commit 5637441acf](https://www.github.com/tgstation/tgstation/pull/85491)

## Reproduction:
Click on TC count in the uplink
Cancel when prompted to choose how many TC to withdraw
???
Get infinite TC

**Comment by CCC23** [comment]
LOADSAEMONE
