### ISSUE TITLE
APC construction seems broken (Wallening)

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#85550]
Reporting client version: 515.1642

## Round ID:
[233251](https://scrubby.melonmesa.com/round/233251)

## Testmerges:
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)
- [Wallening [IDB IGNORE] [MDB IGNORE]](https://www.github.com/tgstation/tgstation/pull/85491)

## Reproduction:

Make yourself a nice box in space on z=1 and area it (or just go to the station somewhere i guess if you can)
spawn wallframe/apc, use on wall
spawn electronics/apc, use on APC frame on wall
add cable to APC
screwdriver APC
spawn a battery or cell, try add to APC.  Get told there's no connector
don't seem to be able to get past this point?

There's an alternative bug if you dont follow the build guide properly
spawn wallframe/apc, use on wall
spawn electronics/apc, use on apc on wall
now screwdriver it.  technically this is the wrong step, but it softlocks the APC frame
Attempting to wire it errors with "wires prevent placing a terminal" - unscrewing it wont fix it, in fact you can even pry the board out, reinsert it, and still wont be able to wire it (even if you dont screwdriver it the 2nd time around, the frame its self is in a messy state)

**Comment by Inari-Whitebear** [comment]
Seems to work currently for me:
* Put frame on wall
* Stick in board
* screwdriver (wires exposed)
* screwdiver (board fastened)
* insert cell
* screwdriver (wires uenxposed)
* corwbar (cover locked)
* Unlock cover in interface
* Crowbar (cover opened)
* Add wires
* Crowbar (cover locked)

**Comment by Inari-Whitebear** [comment]
Sure, I'm just saying how it currently works, not that it should be this way.

**Comment by LemonInTheDark** [comment]
It had to change because kryson sprited it fuckin weird. https://github.com/wall-nerds/wallening/pull/7 (people did notice you stupid bastard)

**Comment by actioninja** [comment]
Should this be considered a bug still?
