### ISSUE TITLE
(Wallening) Unsprited items.

### ISSUE THREAD

**Issue by excalisword** [tgstation/tgstation#85558]
## Issue Summary
I've noticed a couple items in general that aren't sprited so rather than bloating the issues section with a ton of them, I'll just make something general for them. Feel free to add on anything else in the comments that is unsprited.

## Round ID:

233240 and 233256

## Testmerges:

[#85491: 'Wallening [IDB IGNORE] [MDB IGNORE]' by LemonInTheDark at commit 5637441acf](https://www.github.com/tgstation/tgstation/pull/85491)

## Unsprited Items.
Firelock Frames
Light switch frames
Keycard Authentication Devices
Extinguisher Cabinet Frames
Material Airlock Assemblies

**Comment by Justice12354** [comment]
Dormitories signs are also unsprited

**Comment by Justice12354** [comment]
Atmos Resin is also unsprited
