### ISSUE TITLE
[WALLENING] Atmos resin is invisible?

### ISSUE THREAD

**Issue by Metekillot** [tgstation/tgstation#85553]
## Issue Summary

It's in the title. Not much more to it.

**Comment by loganuk** [comment]
Was making an issue and found this



## Issue Summary

Atmos Resign acts as an invisible wall, it can still be attacked and examined but it appears to have no sprite. 

![image](https://github.com/user-attachments/assets/62ff96ce-d268-484a-aa70-ecff0b5a1d91)


## Round ID:

TG Terry - 234137 - Delta Station





## Testmerges:

Server revision compiled on: 
Master commit: [e53c4875a6285b8cb1f31fbe5230f84e8c24980a](https://www.github.com/tgstation/tgstation/commit/e53c4875a6285b8cb1f31fbe5230f84e8c24980a)
The following pull requests are currently test merged:
[#85392: '[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"' by MrStonedOne at commit a388037701](https://www.github.com/tgstation/tgstation/pull/85392)
[#85491: 'Wallening [IDB IGNORE] [MDB IGNORE]' by LemonInTheDark at commit f8ebf9b420](https://www.github.com/tgstation/tgstation/pull/85491)

## Reproduction:

Make Atmos resin appear

Be unable to see it.

**Comment by LemonInTheDark** [comment]
added old sprites, we need 3/4ths verisons eventually (really smoothed ones but whatever)
