### ISSUE TITLE
Tram doors are busted

### ISSUE THREAD

**Issue by Twaticus** [tgstation/tgstation#85554]
## Issue Summary

![dreamseeker_8DCOKsbI8u](https://github.com/user-attachments/assets/b10d8e63-5e4f-4a14-aba9-99e570a2f1f3)
![dreamseeker_sASz9RZoBN](https://github.com/user-attachments/assets/1fe3e64d-327e-41a5-815c-40c0e066a487)

## Testmerges:

[#85491: 'Wallening [IDB IGNORE] [MDB IGNORE]' by LemonInTheDark at commit 5637441acf](https://www.github.com/tgstation/tgstation/pull/85491)

**Comment by lessthnthree** [comment]
Fixed by https://github.com/wall-nerds/wallening/pull/277

**Comment by Twaticus** [comment]
yippee!!
