### ISSUE TITLE
(Wallening) Despite the pixel shifts of humanoids upwards, projectiles and thrown objects still hit the humanoid center mass of the tile.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#85569]
Reporting client version: 515.1642

## Issue Summary

The wallening shifts humanoids up by some 12 or something pixels to try and force everyone into the perspective a bit better. However, the game does not care where people are visually. Projectiles will still impact on people as if the person was fully centered.

Aim towards/slightly behind someone's head, the projectiles will pass by and impact with the wall behind as this is technically a different tile (image below):
![dreamseeker_ePrZBxIz1I](https://github.com/user-attachments/assets/0195d68b-4f04-49f2-a165-f58febbdb99a)

Aim below someone's feet and shots will connect with the target despite never actually making visual contact as this is technically the same tile. They begin to sail under then the impact markers appear suddenly (image below):
![dreamseeker_S2939skl1T](https://github.com/user-attachments/assets/f01027b3-8c40-4e31-a5ea-5fed3bd0c4aa)

While melee combat may be mostly normal in the Wallening perspective, projectile combat will always be slightly off if this human adjustment is kept. I assume thrown objects are affected by this discrepancy.

Another note; projectiles appear to shoot from your character's knees if you're the one firing. Looks silly.

## Round ID:
[233280](https://scrubby.melonmesa.com/round/233280)

## Testmerges:
- [Block atmos processing on ReservedTurfs\:tm: ](https://www.github.com/tgstation/tgstation/pull/84873)
- [Makes cyborg damage more... showy](https://www.github.com/tgstation/tgstation/pull/85298)
- [[TM only] Roundstart Traitors will not have side objectives](https://www.github.com/tgstation/tgstation/pull/85371)
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)
- [fuck](https://www.github.com/tgstation/tgstation/pull/85264)
- [Wallening [IDB IGNORE] [MDB IGNORE]](https://www.github.com/tgstation/tgstation/pull/85491)

**Comment by LemonInTheDark** [comment]
Closed by [#proje](https://github.com/wall-nerds/wallening/pull/301)
