### ISSUE TITLE
(Wallening) Tinted Windows don't block vision.

### ISSUE THREAD

**Issue by excalisword** [tgstation/tgstation#85563]
## Issue Summary
I noticed as a roboticist in a later round and during this round that tinted windows don't seem to block vision anymore.

## Round ID:
[233256](https://scrubby.melonmesa.com/round/233256)

## Testmerges:
[#85491: 'Wallening [IDB IGNORE] [MDB IGNORE]' by LemonInTheDark at commit 5637441acf](https://www.github.com/tgstation/tgstation/pull/85491) 

## Reproduction:
Make some tinted windows and you'll see right through them.

**Comment by Sadboysuss** [comment]
Dupe of https://github.com/tgstation/tgstation/issues/85559
