### ISSUE TITLE
(Wallening) Window frames deconstruction

### ISSUE THREAD

**Issue by Inari-Whitebear** [tgstation/tgstation#85579]
Deconstructing window frames doesn't seem possible with any of the engineer tools I've tried.

If I slap it until it breaks, it doesn't drop material.

How to reproduce:
* Build a window frame from iron sheets
* Try all tools on Window frame, no luck
* Slap it till it breaks instead
* no materials

**Comment by LemonInTheDark** [comment]
kyler added this
