### ISSUE TITLE
(Wallening) Glass windows completely intercept the clicks of anything on the tile above them. (This might be a master issue actually shared by directional firelocks)

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#85572]
## Issue Summary

![frames intercept clicks, but just eats them rather than forcing some kind of interaction, this bible cannot be clicked on directly](https://github.com/user-attachments/assets/b3073080-9d23-4b07-9762-1fa50de51f44)

In this picture, I am attempting to pick up this bible. I cannot pick up this bible. I am clicking on all the exposed parts of this bible, and my cursor indicator even shows that I am hovering over the bible and can click it. It does not let me click the bible.

(This is also present with directional firelocks on our master, by the way, and likely a related issue.)

This does NOT block clicks onto mobs. The top part of the sprite also cannot be clicked to then transfer the click onto the window it is attached too. I tested this by trying to use an object like my nullrod on this top part of the window. It did nothing. So it isn't trying to pass the clicks onto the window, it's just completely blocking any clicking on objects on that tile. I don't think it actually blocked me using a wrench on the chair in that space though.

## Reproduction:

Step 1: Place an item on the ground on a tile above the window
Step 2: Try to click that thing whatsoever. 
Step 3: Discover that it literally cannot be clicked at all. Even if the sprite peeks out from above the rendered part

## Reproduction for Firelocks:

Step 1: Drop the firelock.
Step 2: Place an object on the same tile that the firelock is occupying.
Step 3: Try and click the object. Discover that you cannot.

**Comment by LemonInTheDark** [comment]
IDK what's going on with directional firelocks but the issue with windows was a me problem, should be fixed now

**Comment by actioninja** [comment]
I'm COUNTER-CLOSING, I suspect the issue you were encountering was due to melbert's downshift running on tm's for a while, which was based on an older version with the issue present

**Comment by necromanceranne** [comment]
Hopefully that is the case.
