### ISSUE TITLE
(Wallening) trying to break down a glass door, you somehow hit yourself.

### ISSUE THREAD

**Issue by Graybear98** [tgstation/tgstation#85570]
## Issue Summary
I tried to tide into engineering to get the belt, but instead I smashed my body while I was punching a glass door.

## Round ID:
[233183](https://scrubby.melonmesa.com/round/233183) terry

## Testmerges:
https://github.com/tgstation/tgstation/pull/85491

## Reproduction:

https://github.com/user-attachments/assets/1beb9b36-30e0-4b03-a6d0-eddb78b9f30d

**Comment by Sadboysuss** [comment]
wtf

**Comment by LemonInTheDark** [comment]
that is just how thindow/thindoors work, their hitbox is lowered to the floor so you can click past them. may need rethinking but not really a bug
