### ISSUE TITLE
[WALLENING #85491] Nuclear operatives shuttle's blastdoor button is obscured (unclickable) by doors sprite/southern wall.

### ISSUE THREAD

**Issue by Maxipat112** [tgstation/tgstation#85577]
Reporting client version: 515.1640

## Issue Summary
The button on nukies shuttle is unclickable due to other sprites rendering over it.

The button is obscured by the southern wall and doors (red circle is where the button is according to right click menu) 
![Screenshot 2024-08-03 155824](https://github.com/user-attachments/assets/9205c909-f7da-48c7-a1d0-02e94bb97a61)

OR by the doors only (if the shuttle is already launched somewhere, thus rotated)
![Screenshot 2024-08-03 160422](https://github.com/user-attachments/assets/bf3c9415-d5de-4e74-879b-57473aab8d1a)

## Round ID:
[233319](https://scrubby.melonmesa.com/round/233319)

## Testmerges:
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)
- [Wallening [IDB IGNORE] [MDB IGNORE]](https://www.github.com/tgstation/tgstation/pull/85491)

## Reproduction:

Force nukies shuttle to spawn with admintools/ wait for the nukies round to happen. See there button there is unreachable/unclickable.

**Comment by Sadboysuss** [comment]
offsets my beloved
