### ISSUE TITLE
THE WALLENING - Dying on top of some or all airlocks makes your body invisible and noone will ever find you and drag you back to medbay.

### ISSUE THREAD

**Issue by RobertRoberts2020** [tgstation/tgstation#85581]
## Issue Summary

Since the great wallening update Dying on an airlock renders your corpse invisible for everyone.

![image](https://github.com/user-attachments/assets/648f432c-3c8d-4e21-815a-c0a319e43fba)

## Round ID:

233324

## Testmerges: 

The wallening

## Reproduction: 

Die on an airlock.

Die on an airlock

**Comment by LemonInTheDark** [comment]
![image](https://github.com/user-attachments/assets/9cba1fc8-d934-4662-8642-21bb87df93f3)
Does not replicate, potentially this is that issue where humans just go invisible randomly?

**Comment by RobertRoberts2020** [comment]
> ![image](https://private-user-images.githubusercontent.com/58055496/354969886-9cba1fc8-d934-4662-8642-21bb87df93f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NjkzMjIsIm5iZiI6MTcyMjg2OTAyMiwicGF0aCI6Ii81ODA1NTQ5Ni8zNTQ5Njk4ODYtOWNiYTFmYzgtZDkzNC00NjYyLTg2NDItMjFiYjg3ZGY5M2YzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDE0NDM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1MDBlZjE5ZGU5ZDNhMDViYmRmM2UxZDdhMzVmODk0MjY1OTdlYjIzNjM5YjE1ODgyZWE3NTE0MDJkNDQ3MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AiBV48DVSVSyWVO4mfwdU9jbWvNuKymVKfabXVg2--k) Does not replicate, potentially this is that issue where humans just go invisible randomly?

Bizarre. I remember being invisible for a while a few days ago but I thought it was some kind of space lag induced client-side phenomenon... I guess if its not related to the wallening update this whole thing should be deleted.
