### ISSUE TITLE
Holopads always automatically connect to non-secure areas, irregardless of ID permissions.

### ISSUE THREAD

**Issue by OverwatchVoice** [tgstation/tgstation#85589]
Reporting client version: 515.1641

## Issue Summary

Previously, holopads with incoming calls had the functionality to **auto-accept the call if the caller was a head of staff**. Somehow, the **ID permissions are now ignored**, meaning anyone can call (**and see!**) almost anywhere at any time without meeting the required access.

I was unsure if this is a bug or feature, but I could not find anything about it in the recent changelongs, so I concluded this must be a bug. Closest I've found is [this PR](https://github.com/tgstation/tgstation/pull/85139), but I can't ascertain if the bug was introduced here.
## Round ID:
[233348](https://scrubby.melonmesa.com/round/233348)

## Testmerges:
- [Block atmos processing on ReservedTurfs\:tm: ](https://www.github.com/tgstation/tgstation/pull/84873)
- [Makes cyborg damage more... showy](https://www.github.com/tgstation/tgstation/pull/85298)
- [[TM only] Roundstart Traitors will not have side objectives](https://www.github.com/tgstation/tgstation/pull/85371)
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)
- [fuck](https://www.github.com/tgstation/tgstation/pull/85264)
- [Wallening [IDB IGNORE] [MDB IGNORE]](https://www.github.com/tgstation/tgstation/pull/85491)

## Reproduction:

Stand on a holopad, and make a call to any area that isn't considered secure.

**Comment by SmArtKar** [comment]
not related to the linked pr fyi

**Comment by SmArtKar** [comment]
...Unable to reproduce on live build?

**Comment by OverwatchVoice** [comment]
> ...Unable to reproduce on live build?
Managed to test it on tg/manuel and it indeed happens, even for restricted areas. I'll leave a video of it here once the round ends.

**Comment by SmArtKar** [comment]
...possibly TM bug? somehow?

**Comment by Runi-c** [comment]
Looks like there are two bugs here:

1. Wallening accidentally removed the line of code restricting holopad auto-connections to command (I opened a PR fixing this)
2. Wawastation doesn't use _secure_ holopads for those locations, allowing auto-connections from authorized crew. From what I can tell this also applies to stations like TramStation and Birdshot. These stations only use 3-4 secure pads total, whereas Delta and Meta use 12-13. I don't know the history here so if there should be a review of how secure pads are used that probably needs to go in another issue
