### ISSUE TITLE
WALLENING MASTER MAPPING CHANGES MEGA-ISSUE.

### ISSUE THREAD

**Issue by ArcaneMusic** [tgstation/tgstation#85583]
## Issue Summary
Good afternoon gamers:
This issue is to serve as a master issue related to all the maps that need some level of changes/polish/review. 

Let me know on this issue or on discord if you're claiming mapping work on a specific ruin/portion of the station mapping.
I left some off which I know already should have no issues, such as salvation (it's a single sign, it works.)

Important to note: not every map may need changes! It's largely based on giving each map a once-over to confirm that there's no major issues with layering, and that if there's anything specific to wallening that may have been broken such as directions, orientation, or overlapping, that they can be identified and resolved as they come up.

### General guidelines for map updates:

- Wallmounted objects have best visibility on the northern walls of rooms, but are typically designed to be functional from all four directions. Consider placing smaller objects such as light switches and semi-flat objects such as status displays on the northern wall for this purpose. Objects entirely lacking directionals such as posters should only be placed on northern walls.
- Look for item offsets on surfaces like tables. StrongDMM and the code specific to wallening should now be updated (as of 8/4/24) so that anything offset from the surfaces like items should be accurate, and may need to have it's pixel-y offset updated to correctly be placed on surfaces.
    - This may also be tricky to deal with when regarding objects that have their own, additional x-y offsets installed into their initialize() function, so be advised!
- Airlocks now care about their mapped direction! Make sure that any airlocks that are currently on your maps have the correct directions, as not entering an airlock straight into the doorway will block movement!
- Please, for the love of Jesus Mary Lucifer Christ, compile your map to make sure it looks right? We've got a few visual PRs still rolling into wallening as a result of a large wave of feedback and fixes. I don't need screenshots of everything, as nice as that would be, but I would like to know that YOU have seen how your updated map looks, so that I can tick the box.

## Testmerges:
#85491 

## Station Maps
- [ ] Tramstation (Claimed by MMM)
- [ ] Metastation (Claimed by Vekter)
- [x] Icebox Station (Claimed by Melbert (but not shifting any table objects up))
- [x] Delta Station (Claimed by Melbert (but not shifting any table objects up))
- [ ] Birdshot Station
- [x] Wawa Station (Partially? completed by loganuk)
- [ ] North Star
- [ ] Lavaland itself

### Space Ruins
- [ ] Biological Storage Facility (zoo)
- [ ] Deep Storage
- [ ] Derelict Tradepost
- [ ] Derelict Construction (Capsandi)
- [ ] Derelict Sulaco
- [ ] Dinner for Two
- [ ] Derelict 3
- [ ] Derelict 4
- [ ] Derelict 5
- [ ] Derelict 6
- [ ] Derelict 7 (Capsandi)
- [ ] Derelict 8 (Capsandi)
- [ ] Derelict 9
- [ ] Empty Shell (Capsandi)
- [ ] The Lizard's Gas
- [ ] Authorship
- [ ] Syndicate Ambush
- [ ] A Giant Ball of Paper in Space (paper ruin)
- [ ] CF Corsair (mech transport)
- [ ] DK Excavator 453 (Capsandi)
- [ ] The Twin-Nexus Hotel (space hotel)
- [ ] Unnamed Turreted Outpost
- [ ] Strange Ship (old sprites ruin)
- [ ] DJ Station
- [ ] Kosmicheskaya Stantsiya 13
- [ ] Abandoned Teleporter
- [ ] Crashed Clown Ship
- [ ] Crashed Ship (Capsandi)
- [ ] Syndicate Listening Station
- [ ] Abandoned Telecommunications Satellite
- [ ] Detached Teleporter
- [ ] Aesthetic Outpost (vaporwave)
- [ ] Waylaid Buses (bus ruin)
- [ ] Ancient Space Station (oldstation)
- [ ] Gondoland (gondola asteroid)
- [ ] NT Medical Ship (box whiteship)
- [ ] Whiteship Dock
- [ ] Feline-Human Combination Den
- [ ] Hilbert Research Facility
- [ ] Syndicate Forgotten Ship
- [ ] Abandoned Infiltrator
- [x] Cleric's Den (I'm claiming this one, it's mine ~ Arcane)
- [x] Heck Brewery (I'm claiming this one, it's mine ~ Arcane)
- [ ] Space Billboard
- [ ] Spinward Smoothies
- [ ] Cyborg Mothership
- [ ] Alternate Sciences Research Center
- [ ] Anomaly Research
- [ ] Meateor
- [ ] The Faceoff
- [ ] Bioresearch Outpost (meat derelict)
- [ ] Space Ghost Restaurant
- [ ] Atmos Asteroid
- [ ] Mass driver Router
- [ ] Crashed Mimic Escape Pod
- [ ] Traveler's Rest
- [ ] Crashed Prisoner Shuttle
- [ ] Botanical Haven
- [ ] Pod Crash
- [ ] Interdyne Spinward Research Base
- [ ] Waystation
- [ ] The All-American Diner
- [ ] Abandoned Mime Outpost
- [ ] Transit Booth
- [ ] Phonebooth
- [ ] calebs krazy clothing outlet
- [ ] SYN-C Brutus
- [ ] Decommissioned Garbage Truck NX1
- [ ] Decommissioned Garbage Truck NX2
- [ ] Decommissioned Garbage Truck NX3
- [ ] Decommissioned Garbage Truck NX4
- [ ] Donk Co. Interstellar Trading Post 6016

### Lavaland Ruins

- [ ] Biodome Beach
- [ ] Biodome Winter
- [ ] Biodome Clown Planet
- [ ] The Lizard's Gas
- [ ] Seed Vault
- [ ] Ash Walker Nest
- [ ] Syndicate Lava Base (Unit0016) (Plus map variants woah nelly that's a thing too isn't it)
- [ ] Free Golem Ship
- [ ] Patch of Eden
- [ ] Ruin of Envy
- [ ] Ruin of Gluttony
- [x] Ruin of Greed (Arcane)
- [x] Ruin of Pride (Arcane)
- [x] Ruin of Sloth (Arcane)
- [x] Dead God (ratvar)
- [x] Hierophant's Arena
- [ ] Blood-Drunk Miner (all variants)
- [ ] UFO Crash
- [x] Xenomorph Nest (Arcane)
- [x] Fountain Hall (Arcane) (looks fine)
- [ ] Survival Capsule Ruins
- [ ] Ruined Pizza Party
- [ ] Summoning Ritual
- [ ] Makeshift Shelter (Hermit Cave)
- [ ] Ripley Ruin
- [x] Dark Wizard Altar
- [x] Ancient Puzzle (Looks fine ~Arcane)
- [x] Elephant Graveyard (I'm claiming this one, it's mine ~ Arcane)
- [x] Bileworm Nest (Looks fine ~Arcane)
- [ ] Phonebooth
- [x] Battle Site (I'm claiming this one, it's mine ~ Arcane)
- [ ] Watchers' Grave
- [ ] Mook Village
- [ ] Shuttle Wreckage

### Icemoon Ruins

Above ground:
- [ ] Lizard Gas Station ( - Claimed by [EEASAS](https://github.com/EEASAS) )
- [ ] Ruin of Lust
- [ ] Asteroid Site
- [ ] Engineer Outpost
- [ ] Fountain Hall
- [ ] Insect Research Station (bug habitat)
- [ ] Moffuchi's Pizzeria (Capsandi)
- [ ] Frozen Phonebooth
- [ ] Smoking Room

Above and below ground:
- [ ] Mining Site
- [ ] Mining Site Underground

Below ground:

- [ ] Abandoned Village
- [ ] Buried Library
- [ ] Ruin of Wrath
- [ ] Frozen Shack
- [ ] Lavaland Incursion
- [ ] Ancient Puzzle
- [ ] Bath House
- [ ] Wendigo Cave
- [ ] Free Golem Ship
- [x] Frozen-over Post Office (I'm claiming this one, it's mine ~ Arcane)
- [ ] Frozen Communicatons Outpost
- [ ] Listening Post
- [ ] Abandoned Plasma Facility
- [ ] Hot Springs

## Bitrunning Domains (Claimed by unit0016):

- [x] Abductor Ship
- [x] Ashen Inferno
- [x] Beach Bar
- [x] Sanguine Excavation
- [x] Breeze bay
- [x] Blood-Soaked Lair
- [x] Clown Planet
- [x] Celestial Trial
- [x] Pizza Party (The FNAF reference one)
- [x] Gondola Asteroid
- [x] Zealot Arena
- [x] Island Brawl
- [x] Disposal Pipe Factory
- [x] Corsair Cove
- [x] Crate Chaos
- [x] Infected Domain
- [x] Glacier Grind
- [x] Syndicate Assault
- [x] Cosmic Vestige
- [x] Glacial Devourer
- [x] Xeno Infestation

## Shuttles
(This is the point where I gave up on manually grabbing different map template datums)

- [ ] _maps\shuttles\arrival_birdshot.dmm
- [ ] _maps\shuttles\arrival_box.dmm
- [ ] _maps\shuttles\arrival_delta.dmm
- [ ] _maps\shuttles\arrival_donut.dmm
- [ ] _maps\shuttles\arrival_kilo.dmm
- [ ] _maps\shuttles\arrival_northstar.dmm
- [ ] _maps\shuttles\arrival_pubby.dmm
- [ ] _maps\shuttles\assault_pod_default.dmm
- [ ] _maps\shuttles\aux_base_default.dmm
- [ ] _maps\shuttles\aux_base_small.dmm
- [ ] _maps\shuttles\cargo_birdboat.dmm
- [ ] _maps\shuttles\cargo_birdshot.dmm
- [ ] _maps\shuttles\cargo_box.dmm
- [ ] _maps\shuttles\cargo_delta.dmm
- [ ] _maps\shuttles\cargo_kilo.dmm
- [ ] _maps\shuttles\cargo_northstar.dmm
- [ ] _maps\shuttles\cargo_pubby.dmm
- [ ] _maps\shuttles\emergency_arena.dmm
- [ ] _maps\shuttles\emergency_asteroid.dmm
- [ ] _maps\shuttles\emergency_backup.dmm
- [ ] _maps\shuttles\emergency_bar.dmm
- [ ] _maps\shuttles\emergency_bballhooper.dmm
- [ ] _maps\shuttles\emergency_birdboat.dmm
- [ ] _maps\shuttles\emergency_birdshot.dmm
- [ ] _maps\shuttles\emergency_box.dmm
- [ ] _maps\shuttles\emergency_casino.dmm
- [ ] _maps\shuttles\emergency_cere.dmm
- [ ] _maps\shuttles\emergency_clown.dmm
- [ ] _maps\shuttles\emergency_construction.dmm
- [ ] _maps\shuttles\emergency_cramped.dmm
- [ ] _maps\shuttles\emergency_cruise.dmm
- [ ] _maps\shuttles\emergency_delta.dmm
- [ ] _maps\shuttles\emergency_discoinferno.dmm
- [ ] _maps\shuttles\emergency_donut.dmm
- [ ] _maps\shuttles\emergency_fame.dmm
- [ ] _maps\shuttles\emergency_fish.dmm
- [ ] _maps\shuttles\emergency_goon.dmm
- [ ] _maps\shuttles\emergency_hugcage.dmm
- [ ] _maps\shuttles\emergency_humpback.dmm
- [ ] _maps\shuttles\emergency_imfedupwiththisworld.dmm
- [ ] _maps\shuttles\emergency_kilo.dmm
- [ ] _maps\shuttles\emergency_lance.dmm
- [ ] _maps\shuttles\emergency_luxury.dmm
- [ ] _maps\shuttles\emergency_medisim.dmm
- [ ] _maps\shuttles\emergency_meta.dmm
- [ ] _maps\shuttles\emergency_meteor.dmm
- [ ] _maps\shuttles\emergency_mini.dmm
- [ ] _maps\shuttles\emergency_monastery.dmm
- [ ] _maps\shuttles\emergency_narnar.dmm
- [ ] _maps\shuttles\emergency_nature.dmm
- [ ] _maps\shuttles\emergency_northstar.dmm
- [ ] _maps\shuttles\emergency_omega.dmm
- [ ] _maps\shuttles\emergency_pod.dmm
- [ ] _maps\shuttles\emergency_pubby.dmm
- [ ] _maps\shuttles\emergency_raven.dmm
- [ ] _maps\shuttles\emergency_rollerdome.dmm
- [ ] _maps\shuttles\emergency_russiafightpit.dmm
- [ ] _maps\shuttles\emergency_scrapheap.dmm
- [ ] _maps\shuttles\emergency_shadow.dmm
- [ ] _maps\shuttles\emergency_supermatter.dmm
- [ ] _maps\shuttles\emergency_tram.dmm
- [ ] _maps\shuttles\emergency_tranquility.dmm
- [ ] _maps\shuttles\emergency_venture.dmm
- [ ] _maps\shuttles\emergency_wabbajack.dmm
- [ ] _maps\shuttles\emergency_wawa.dmm
- [ ] _maps\shuttles\emergency_zeta.dmm
- [ ] _maps\shuttles\ert_bounty.dmm
- [ ] _maps\shuttles\escape_pod_cramped.dmm
- [ ] _maps\shuttles\escape_pod_default.dmm
- [ ] _maps\shuttles\escape_pod_large.dmm
- [ ] _maps\shuttles\escape_pod_luxury.dmm
- [ ] _maps\shuttles\ferry_base.dmm
- [ ] _maps\shuttles\ferry_fancy.dmm
- [ ] _maps\shuttles\ferry_kilo.dmm
- [ ] _maps\shuttles\ferry_lighthouse.dmm
- [ ] _maps\shuttles\ferry_meat.dmm
- [ ] _maps\shuttles\hunter_bounty.dmm
- [ ] _maps\shuttles\hunter_mi13_foodtruck.dmm
- [ ] _maps\shuttles\hunter_psyker.dmm
- [ ] _maps\shuttles\hunter_russian.dmm
- [ ] _maps\shuttles\hunter_space_cop.dmm
- [ ] _maps\shuttles\infiltrator_advanced.dmm
- [ ] _maps\shuttles\infiltrator_basic.dmm
- [ ] _maps\shuttles\labour_box.dmm
- [ ] _maps\shuttles\labour_delta.dmm
- [ ] _maps\shuttles\labour_generic.dmm
- [ ] _maps\shuttles\labour_kilo.dmm
- [ ] _maps\shuttles\mining_box.dmm
- [ ] _maps\shuttles\mining_common_kilo.dmm
- [ ] _maps\shuttles\mining_common_meta.dmm
- [ ] _maps\shuttles\mining_common_northstar.dmm
- [ ] _maps\shuttles\mining_delta.dmm
- [ ] _maps\shuttles\mining_freight.dmm
- [ ] _maps\shuttles\mining_kilo.dmm
- [ ] _maps\shuttles\mining_large.dmm
- [ ] _maps\shuttles\mining_northstar.dmm
- [ ] _maps\shuttles\pirate_default.dmm
- [ ] _maps\shuttles\pirate_dutchman.dmm
- [ ] _maps\shuttles\pirate_ex_interdyne.dmm
- [ ] _maps\shuttles\pirate_geode.dmm
- [ ] _maps\shuttles\pirate_grey.dmm
- [ ] _maps\shuttles\pirate_irs.dmm
- [ ] _maps\shuttles\pirate_medieval.dmm
- [ ] _maps\shuttles\pirate_silverscale.dmm
- [ ] _maps\shuttles\ruin_caravan_victim.dmm
- [ ] _maps\shuttles\ruin_cyborg_mothership.dmm
- [ ] _maps\shuttles\ruin_pirate_cutter.dmm
- [ ] _maps\shuttles\ruin_syndicate_dropship.dmm
- [ ] _maps\shuttles\ruin_syndicate_fighter_shiv.dmm
- [ ] _maps\shuttles\snowdin_excavation.dmm
- [ ] _maps\shuttles\snowdin_mining.dmm
- [ ] _maps\shuttles\starfury_corvette.dmm
- [ ] _maps\shuttles\starfury_fighter1.dmm
- [ ] _maps\shuttles\starfury_fighter2.dmm
- [ ] _maps\shuttles\starfury_fighter3.dmm
- [ ] _maps\shuttles\whiteship_birdshot.dmm
- [ ] _maps\shuttles\whiteship_box.dmm
- [ ] _maps\shuttles\whiteship_cere.dmm
- [ ] _maps\shuttles\whiteship_delta.dmm
- [ ] _maps\shuttles\whiteship_donut.dmm
- [ ] _maps\shuttles\whiteship_kilo.dmm
- [ ] _maps\shuttles\whiteship_meta.dmm
- [ ] _maps\shuttles\whiteship_obelisk.dmm
- [ ] _maps\shuttles\whiteship_personalshuttle.dmm
- [ ] _maps\shuttles\whiteship_pubby.dmm
- [ ] _maps\shuttles\whiteship_tram.dmm

### Lazy Templates:

- [ ] _maps\templates\lazy_templates\abductor_ships.dmm
- [ ] _maps\templates\lazy_templates\heretic_sacrifice.dmm
- [ ] _maps\templates\lazy_templates\ninja_den.dmm
- [ ] _maps\templates\lazy_templates\nukie_base.dmm
- [ ] _maps\templates\lazy_templates\voidwalker_void.dmm
- [ ] _maps\templates\lazy_templates\wizard_den.dmm

### Holodeck Simulations (Unit0016 (tentative))

- [ ] _maps\templates\admin_thunderdome.dmm
- [x] _maps\templates\battlecruiser_starfury.dmm (claimed by [unit0016](https://github.com/unit0016))
- [ ] _maps\templates\hilbertshotel.dmm
- [ ] _maps\templates\hilbertshotelempty.dmm
- [ ] _maps\templates\hilbertshotellore.dmm
- [ ] _maps\templates\hilbertshotelstorage.dmm
- [x] _maps\templates\holodeck_animeschool.dmm
- [x] _maps\templates\holodeck_anthophillia.dmm
- [x] _maps\templates\holodeck_baseball.dmm
- [x] _maps\templates\holodeck_basketball.dmm
- [x] _maps\templates\holodeck_beach.dmm
- [x] _maps\templates\holodeck_burntest.dmm
- [x] _maps\templates\holodeck_card_battle.dmm
- [x] _maps\templates\holodeck_chapelcourt.dmm
- [x] _maps\templates\holodeck_dodgeball.dmm
- [x] _maps\templates\holodeck_emptycourt.dmm
- [x] _maps\templates\holodeck_firingrange.dmm
- [x] _maps\templates\holodeck_gamer.dmm
- [x] _maps\templates\holodeck_holdoutbunker.dmm
- [x] _maps\templates\holodeck_kobayashi.dmm
- [x] _maps\templates\holodeck_lounge.dmm
- [x] _maps\templates\holodeck_medicalsim.dmm
- [x] _maps\templates\holodeck_microwave.dmm
- [x] _maps\templates\holodeck_offline.dmm
- [x] _maps\templates\holodeck_petpark.dmm
- [x] _maps\templates\holodeck_photobooth.dmm
- [x] _maps\templates\holodeck_refuelingstation.dmm
- [x] _maps\templates\holodeck_skatepark.dmm
- [x] _maps\templates\holodeck_spacecheckers.dmm
- [x] _maps\templates\holodeck_spacechess.dmm
- [x] _maps\templates\holodeck_thunderdome.dmm
- [x] _maps\templates\holodeck_thunderdome1218.dmm
- [x] _maps\templates\holodeck_wildlifesim.dmm
- [x] _maps\templates\holodeck_winterwonderland.dmm
- [ ] _maps\templates\medium_shuttle1.dmm
- [ ] _maps\templates\medium_shuttle2.dmm
- [ ] _maps\templates\medium_shuttle3.dmm
- [ ] _maps\templates\medium_shuttle4.dmm
- [ ] _maps\templates\shelter_1.dmm
- [ ] _maps\templates\shelter_2.dmm
- [ ] _maps\templates\shelter_3.dmm
- [ ] _maps\templates\shelter_t.dmm
- [ ] _maps\templates\small_asteroid_1.dmm
- [ ] _maps\templates\small_shuttle_1.dmm
- [ ] _maps\templates\the_arena.dmm
- [ ] _maps\templates\unit_tests.dmm

**Comment by Potato-Masher** [comment]
Probably falls under this, but a lot of the bitrunner domains needs the same treatment as the ruins. Many VDs have airlocks that aren't facing the right direction (or maybe they spawn in the wrong direction when loaded). I've had to manually help bitrunners while admined up by moving airlocks out of the way.

**Comment by EEASAS** [comment]
im claiming the lizard's gas station on icebox above ground, i made it

**Comment by TheVekter** [comment]
I am working on Metastation right now, please don't fuck with it.

**Comment by MrMelbert** [comment]
Shuttles also need attention

**Comment by ArcaneMusic** [comment]
Note to self: and Holodeck Sims

**Comment by loganuk** [comment]
Working on Wawa Station

**Comment by unit0016** [comment]
claiming  _maps\templates\battlecruiser_starfury.dmm

**Comment by LemonInTheDark** [comment]
Of note: things "on" tables will need shifting up, which is a good bit of extra work.
Thank you guys for committing to this shit s a lot of work

**Comment by unit0016** [comment]
I feel like that should be done on mapload rather than needing to be manually done each time over; especially because SDMM doesn't agree with what height the tables actually are:
![image](https://github.com/user-attachments/assets/df22c3a7-8a07-4860-b59a-af4ada52423b)
![image](https://github.com/user-attachments/assets/aa34a65c-5841-482e-bfd7-4906af41e61b)

...Or at least, the tables should be at the correct height in SDMM.

**Comment by LemonInTheDark** [comment]
jacqu's recent windows pr should have fixed that, try pulling master?

**Comment by unit0016** [comment]
Workable now; yuh

**Comment by GPeckman** [comment]
There are a couple of instances of machines (smartfridges mostly) being placed on top of walls. It looks really janky with wallening and should probably be removed, might be worth adding a note about that.

**Comment by unit0016** [comment]
Those were intended to be removed even without wallening anyways (it's why they need to be welded AND wrenched; now); probably worth adding a lint for it on /tg/ proper

**Comment by unit0016** [comment]
With https://github.com/wall-nerds/wallening/pull/287 in a tentatively complete state; claiming all of the holodeck templates next.

**Comment by LemonInTheDark** [comment]
![image](https://github.com/user-attachments/assets/836efcd7-aaef-4841-ab7a-28df87cb26bf)

**Comment by Capsandi** [comment]
Claiming SPACE RUINS

DK excavator / onehalf.dmm
CrashedShip.dmm
Derelict7.dmm
Derelict8.dmm
Derelict_Construction.dmm
EmptyShell.dmm
Claiming ICEMOON SURFACE RUIN
Moffuchi's Pizza/ icemoon_surface_pizza.dmm

**Comment by loganuk** [comment]
Open issue regarding posters which we knew about - https://github.com/tgstation/tgstation/issues/85642

**Comment by unit0016** [comment]
Claiming the Syndicate Lavaland Base & The Related Random Variants as my next; seeing as https://github.com/wall-nerds/wallening/pull/287 and https://github.com/wall-nerds/wallening/pull/299 are ready *unless* the wall offset experiment goes through.

**Comment by loganuk** [comment]
Invisible turret control panels for everyone's FYI - https://github.com/tgstation/tgstation/issues/85677

**Comment by loganuk** [comment]
![image](https://github.com/user-attachments/assets/c8a8cde2-6b27-4ef2-a620-627fd042ea6e)
Yay it has a tick. - I do note unfinished and still plenty to do.

I'm going to be releasing Wawa and Birdshot to whoever wants to call dibs. Hopefully fixing one station gave a boost. The Wawa PR is yet to be merged or checked so does need a second opinion once it is in.

I've enjoyed this, thanks for letting me take part.

**Comment by EuSouAFazer** [comment]
Northstar is no longer being phased out so it needs to be unticked and claimed  https://discord.com/channels/326822144233439242/326831214667235328/1271141861708529704

**Comment by unit0016** [comment]
Fuck it; Claiming everything left in `_maps/templates` and it's subfolder in `lazy_templates`

**Comment by LemonInTheDark** [comment]
insane

**Comment by unit0016** [comment]
Claiming Lavaland next; with that being done with.

**Comment by unit0016** [comment]
Treating myself a lil; claiming KC13 and Charlie/Old Station.

**Comment by unit0016** [comment]
Claiming all the bitrunner domains. Oorah.
