### ISSUE TITLE
(Wallening) Player teleport effects (like from the ninja blade dash) are not pixel shifted up to match the characters.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#85587]
Reporting client version: 515.1642

## Issue Summary

![dreamseeker_caNMIdLgSh](https://github.com/user-attachments/assets/6b22612e-5750-4ff8-adcf-d53db24c3e10)

## Round ID:
[233336](https://scrubby.melonmesa.com/round/233336)

## Testmerges:
- [Block atmos processing on ReservedTurfs\:tm: ](https://www.github.com/tgstation/tgstation/pull/84873)
- [Makes cyborg damage more... showy](https://www.github.com/tgstation/tgstation/pull/85298)
- [[TM only] Roundstart Traitors will not have side objectives](https://www.github.com/tgstation/tgstation/pull/85371)
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)
- [fuck](https://www.github.com/tgstation/tgstation/pull/85264)
- [Wallening [IDB IGNORE] [MDB IGNORE]](https://www.github.com/tgstation/tgstation/pull/85491)

**Comment by Sadboysuss** [comment]
gonna guess the genetics effects are also affected
