### ISSUE TITLE
(Wallening) Delta's Bridge and Brig Airlocks are sideways

### ISSUE THREAD

**Issue by Justice12354** [tgstation/tgstation#85582]
## Issue Summary
The inner airlocks of Delta's Bridge and Brig are horizontal, instead of vertical, causing them to block the path. This also applies to the firelocks, though these do not obstruct the way. Changing their rotation to west/east instead of north/south fixes this

**Comment by LemonInTheDark** [comment]
I believe melbert has fixed this
