### ISSUE TITLE
Impassable door in Icebox Bar

### ISSUE THREAD

**Issue by Eronymun** [tgstation/tgstation#85591]
Reporting client version: 515.1641

## Issue Summary

![impassable](https://github.com/user-attachments/assets/25c24596-8e69-4405-822c-3d7d3c95955b)

You simply cannot pass through this airlock from bar to kitchen backroom, and I can't see why as there is nothing blocking it.

## Round ID:
233344

## Testmerges:
- [Block atmos processing on ReservedTurfs\:tm: ](https://www.github.com/tgstation/tgstation/pull/84873)
- [Refactor Stat Panel styles and more TGUI-like appearance](https://www.github.com/tgstation/tgstation/pull/85257)
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)
- [Wallening [IDB IGNORE] [MDB IGNORE]](https://www.github.com/tgstation/tgstation/pull/85491)

## Reproduction:

Open up this door and try walking through it, be amazed as thin air blocks your passage.

**Comment by OuroborusReporter** [comment]
Seen this issue recently, mostly with the outer doors into the bridge on Icebox. The issue seems to be that the doors are sideways - You can see similar results if you deconstruct the wall next to a functioning door, and try to walk into it from the side. No clue WHY this happens though
