### ISSUE TITLE
Supermatter Sword has no attack cooldown

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#85601]
## Issue Summary

Supermatter Sword has no attack cooldown much like my last issue report

## Reproduction:

Use SM sword

**Comment by SyncIt21** [comment]
Why should it? It's an admin only weapon so there's no problem with it being OP

**Comment by SmArtKar** [comment]
seems intentional?

**Comment by carlarctg** [comment]
Bro it's not about it being OP. It's attack chain heckness.

**Comment by SmArtKar** [comment]
> Bro it's not about it being OP. It's attack chain heckness.

yeah, it intentionally does that

**Comment by loganuk** [comment]
I'm curious, was there a specific round where this was an issue?
