### ISSUE TITLE
Wellcheers doesn't have any effects besides causing drowsiness

### ISSUE THREAD

**Issue by Metekillot** [tgstation/tgstation#85617]
Reporting client version: 515.1642

## Round ID:
[233567](https://scrubby.melonmesa.com/round/233567)

## Testmerges:
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)

## Reproduction:

Drink wellcheers and observe that nothing happens besides you getting sleepy.

**Comment by YesterdaysPromise** [comment]
Its effects depend on your mood. Or are supposed to anyway. If you had bad mood, that's intended behaviour.

**Comment by Metekillot** [comment]
I looked at the code for it just now. It has no effect if you have 126-150 sanity; I wanted the effects of neutral to great sanitybut I believe the person who coded it had meant to put max sanity instead of making above 'great' sanity have no effect besides drowsiness.
