### ISSUE TITLE
slipping and getting stuck

### ISSUE THREAD

**Issue by Thrugdelmir** [tgstation/tgstation#85623]
Reporting client version: 515.1642

## Issue Summary

I slipped on a puddle of vomit and got stuck

## Round ID:
[233594](https://scrubby.melonmesa.com/round/233594) /tg/Campbell

## Reproduction:

I slipped on a puddle of vomit in maint and got stuck after getting up again. Couldn#t move at all other then looking in a direction.

**Comment by Thrugdelmir** [comment]
I tried emptying cache and reinstalling Byond. Issue remains.

**Comment by loganuk** [comment]
### Recommend closing this and focusing on - https://github.com/tgstation/tgstation/issues/85620

**Comment by Sadboysuss** [comment]
Seems to be fixed now
