### ISSUE TITLE
drop pods

### ISSUE THREAD

**Issue by Thrugdelmir** [tgstation/tgstation#85622]
Reporting client version: 515.1642

## Issue Summary

Going near a drop pod catches pawn on fire

## Round ID:
[233594](https://scrubby.melonmesa.com/round/233594) /tg/Campbell

## Reproduction:

Going withtin one tile to an event spawned drop pods causes my pawn to catch on fire.

**Comment by Thrugdelmir** [comment]
I tried emptying cache and reinstalling Byond. Issue remains.

**Comment by loganuk** [comment]
### Recommend closing this and focusing on - https://github.com/tgstation/tgstation/issues/85620

**Comment by Sadboysuss** [comment]
Seems to be fixed now
