### ISSUE TITLE
possessing cockroach is not a good idea

### ISSUE THREAD

**Issue by MelokGleb** [tgstation/tgstation#85626]
## Issue Summary
if you use a colossus crystal to possess a cockroach and then turn back, your original body squashes the cockroach before you get back to it, round removing you (not always, theres still a chance that cockroach will avoid getting squashed)

## Round ID:
localhost

## Testmerges:
none

## Reproduction:
1 kill colossus
2 posess a cockroach with crystal dropped from it
2 turn back
4 get round removed
IF 4 STEP FAILS REPEAT STEPS 2 AND 3

**Comment by Dawnseer** [comment]
I guess you should avoid getting stepped on by your former body.
