### ISSUE TITLE
Empty spaces in backpack

### ISSUE THREAD

**Issue by Thrugdelmir** [tgstation/tgstation#85621]
Reporting client version: 515.1642

## Issue Summary

There are spaces in backpack that contain nothing

## Round ID:
[233594](https://scrubby.melonmesa.com/round/233594) /tg/Campbell

## Reproduction:

When placing Items into a backpack or duffelbag sometimes it creates empty spaces in said backpack. These spaces contain nothing but are considered filled by the game. As far as I can tell, this happens when stack sizes of stackable Items change.

![(null)scrnshot1](https://github.com/user-attachments/assets/1055bd5f-aaba-4755-acd0-43edc5b8c165)

**Comment by Thrugdelmir** [comment]
Mining Satchels seem to have the same problem.

**Comment by Thrugdelmir** [comment]
I tried emptying cache and reinstalling Byond. Issue remains.

**Comment by loganuk** [comment]
### Recommend closing this and focusing on - https://github.com/tgstation/tgstation/issues/85620

**Comment by Sadboysuss** [comment]
Seems to be fixed now
