### ISSUE TITLE
Impassable Tiles

### ISSUE THREAD

**Issue by Thrugdelmir** [tgstation/tgstation#85620]
Reporting client version: 515.1642

## Issue Summary

Deconstructing, moving or destroying impassable objects on a tile makes the tile impassable still afterwards.

## Round ID:
[233594](https://scrubby.melonmesa.com/round/233594) /tg/Campbell

## Reproduction:

The bug is permanent and can be reproduced at any time.

When I deconstruct walls windows, machines or even tables, the tile where the asset was, is still not passable for me, as if the former asset is still there. Even some crates and lockers seem to be affected when moved. Same goes for destroying these assets, including trees.

**Comment by Thrugdelmir** [comment]
I tried emptying cache and reinstalling Byond. Issue remains.

**Comment by loganuk** [comment]
@Thrugdelmir Just tried on a few objects and unable to re-produce.

Any screenshots of this? Also what map are you on as round is still in progress?

**Comment by Thrugdelmir** [comment]
yes come to campbell i can show you

**Comment by Thrugdelmir** [comment]
Tried on Meta and Icebox

**Comment by loganuk** [comment]
@Thrugdelmir I'm not coming into a live round to bug test :)

Have you been able to re-produce this with another player or just you?

**Comment by Thrugdelmir** [comment]
There is no one else here I am the only one online. Should be fine if you come have a look.

**Comment by loganuk** [comment]
I think this is just Campbell being weird rather than code specific
![image](https://github.com/user-attachments/assets/82fa4941-d111-4c72-93fd-b18cb178451a)

![image](https://github.com/user-attachments/assets/3c9ece4e-88b9-45f5-ac94-61cadba2ba0d)

**Comment by loganuk** [comment]
Issues such as turfs being blocked after removing a window are present but a bunch of stuff is broken - Likely more to do with the server than code.

**Comment by Thrugdelmir** [comment]
Possible, I will go to manuel and try to reproduce, give me a minute.

**Comment by Thrugdelmir** [comment]
Okay on Manuel everything is fine. Can't reproduce.

**Comment by loganuk** [comment]
### Campbell specific issue - Leave this issue open just in case problem with other servers develops.

This and other issues present even past restart - Admins informed which resulted in re-deployment to Campbell and second restart. Issue appears to be Campbell specific and not an issue with code. 

Suggest leaving this as single issue open and closing others.

**Comment by Sadboysuss** [comment]
Seems to be fixed now
