### ISSUE TITLE
Bubblegum Teleportation Issue

### ISSUE THREAD

**Issue by Blasker29** [tgstation/tgstation#85638]
Reporting client version: 515.1640

## Issue Summary

In an attempt to cheese the Bubblegum fight, the Jacob's ladder was employed to retreat whenever things were dire. This was set-up above the Hierophant arena and used to climb down to the station. It was effective several times, where the Bubblegum combatants lost aggro and were able to get healed on station and resume aggro when climbing back up. However, at one point, the Bubblegum was able to continue aggro and teleport onto the station following retreat via the ladder. I believe this isn't working as intended. 

## Round ID:
[233727](https://scrubby.melonmesa.com/round/233727)

## Testmerges:
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)

## Reproduction:

The basic premise of what occurred was the following:

1. Receive Jacob's Ladder from Necropolis Chest
2. Place at Hierophant Arena
3. Initiate Bubblegum fight
4. Retreat down the ladder during Bubblegum fight
5. Upon being healed, proceed up the ladder, where Bubblegum is no longer aggroed, and resume fight when ready

This seems to have broken down at step 4 for some reason as aggro was maintained following retreat at a certain point.

**Comment by necromanceranne** [comment]
It's during his various teleport attacks that he'll end up teleporting somewhere in proximity to you if you change location, even across z-levels. This isn't a bug necessarily. It just depends on whether it should be crossing z-levels or not.
