### ISSUE TITLE
Wallening poster facing wrong direction

### ISSUE THREAD

**Issue by Zargoar** [tgstation/tgstation#85642]
Reporting client version: 515.1642

## Issue Summary

Posters facing to the side are not displayed correctly on wallening walls.

## Round ID:
[233755](https://scrubby.melonmesa.com/round/233755)

## Testmerges:
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)
- [Wallening [IDB IGNORE] [MDB IGNORE]](https://www.github.com/tgstation/tgstation/pull/85491)

## Reproduction:

1. Go to side poster.
2. Observe it is borked.
3. Notice how the poster is not facing the correct direction.

![image](https://github.com/user-attachments/assets/4f6b1eff-e6ff-4acf-9f68-36f439ed786c)

**Comment by Zargoar** [comment]
![image](https://github.com/user-attachments/assets/a6dff033-1bc0-46ee-bf08-bf1c29ac1243)

**Comment by loganuk** [comment]
@Zargoar Thank you for reporting this.

Posters are a known issue that is going to be worked on to fix :) - I've dropped a link in the mapping mega thread about this issue.

The solution is being worked on as part over the map overhaul, a lot of re-moving of posters to south facing walls for example plus a few code changes.
