### ISSUE TITLE
Wallening barsigns completely detached from the wall

### ISSUE THREAD

**Issue by Zargoar** [tgstation/tgstation#85641]
Reporting client version: 515.1642

## Issue Summary

Bar signs on wallening walls are completely detached.

## Round ID:
[233755](https://scrubby.melonmesa.com/round/233755)

## Testmerges:
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)
- [Wallening [IDB IGNORE] [MDB IGNORE]](https://www.github.com/tgstation/tgstation/pull/85491)

## Reproduction:

1. Walk to a barsign.
2. Observe the barsign.
3. Observe the barsign is detached from the wall.

![image](https://github.com/user-attachments/assets/a39a62e3-e549-4e78-9c48-38e2a3babf26)

**Comment by loganuk** [comment]
@Zargoar Thank you - This is a known issue being investigated regarding wallmount offsets.

https://github.com/wall-nerds/wallening/issues/285
