### ISSUE TITLE
no healing in the pizzeria!

### ISSUE THREAD

**Issue by MelokGleb** [tgstation/tgstation#85666]
Reporting client version: 515.1641

## Issue Summary
if you use patches springlock module will kill you

## Round ID:
[233870](https://scrubby.melonmesa.com/round/233870)

## Testmerges:
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)

## Reproduction:
use a springlock modsuit
use a patch
snap

**Comment by Artemchik542** [comment]
![765](https://github.com/user-attachments/assets/3f64b082-2258-4683-b67f-0d250167b400)

But if you enter a room with a lot of steam - it is normal for you and the springlock (safe for sauna?)

**Comment by SmArtKar** [comment]
patches triggering the springlock is a result of their exposure type, but water vapor part is an oversight

**Comment by Artemchik542** [comment]
> patches triggering the springlock is a result of their exposure type, but water vapor part is an oversight

Should I open a new issue about water vapor?
