### ISSUE TITLE
WALLENING (Crappening) - Can't click stuff.

### ISSUE THREAD

**Issue by RobertRoberts2020** [tgstation/tgstation#85672]
## Issue Summary

Can't click anything in the red circle because of the walls.

## Round ID:
[233939](https://scrubby.melonmesa.com/round/233939)

## Testmerges:
The wallening crap

## Reproduction:

literally try to click on anything thats right next to a wall like in the picture.

literally try to click on anything thats right next to a wall like in the picture.

If you test this in localhost first, you don't ruin several rounds for all the players who constantly play and try to enjoy the game

**Comment by Iamgoofball** [comment]
you forgot to upload this picture

**Comment by RobertRoberts2020** [comment]
> you forgot to upload this picture
oops 
![image](https://github.com/user-attachments/assets/2f170891-05b1-48e8-9294-2fc68703eac6)

**Comment by Metekillot** [comment]
Does not being so snide occur to you like, at all? When it comes to reporting bugs for a game maintained for free by volunteers, I mean.

**Comment by loganuk** [comment]
On testing Wallening-Stable  - I could interact with all objects - Even spawned in an extinguisher to match, may be client-side issue or something else merged in is causing this.

![image](https://github.com/user-attachments/assets/02778876-3930-493c-bf6b-4629002193c2)

**Comment by actioninja** [comment]
Low quality issue with unclear description and lack of reproduction

**Comment by RobertRoberts2020** [comment]
@actioninja 
Please re- open this, as this issue is still ongoing, I'm uploading video evidence on round 234007.

@Metekillot 
As for the "rudeness" I think it's rude to test stuff on production while people who have been working all day try to enjoy the game, but their rounds are ruined because bugs, while the maintainer who is working on the wall stuff plays maybe once a week...


1)
https://www.youtube.com/watch?v=-ow3N1ADjLc
2)
https://www.youtube.com/watch?v=WSkcbDwNgFI
3)
https://www.youtube.com/watch?v=HxsPTJ3Lm5Q
4)
https://www.youtube.com/watch?v=JNRd2pEg_uU
