### ISSUE TITLE
(Wallening?) Ash Dragon's fire breath's and meteors' fires are invisible

### ISSUE THREAD

**Issue by Justice12354** [tgstation/tgstation#85675]
Reporting client version: 515.1640
Manuel

For both the Ash Dragon's fire cone and the flaming meteor, the fire is invisible, only causing a lighting change. Mobs in that area will still catch on fire. Meanwhile, causing a plasmaflood will show the fire.
![imagem](https://github.com/user-attachments/assets/b621d676-fa39-4a2e-bd46-dcc8166dab4a)
![imagem](https://github.com/user-attachments/assets/573079dd-0d2b-41dc-be51-63be1b2f8a89)

**Comment by Sadboysuss** [comment]
probably wallening associated

**Comment by GPeckman** [comment]
This also happens when you ignite oil puddles on the floor

**Comment by LemonInTheDark** [comment]
I fucking named it wrong bro wtf

**Comment by zoomachina** [comment]
The same with chlorine trifluoride fireballs and thermite
