### ISSUE TITLE
Protagonist Anti Antagonist  (suggestion)

### ISSUE THREAD

**Issue by kacperpl1234pl** [tgstation/tgstation#85674]
(suggestion We have tons of antagonists, but what about protagonists? I don't mean normal crew roles. I suggest a role system for protagonists, similar to antagonists.

Why? Let's say the station is at Black Orbit. Security breaches happen all the time. Let's say a ling attempts to go on a rampage, but when he breaks into Medbay, he realizes too late that the medical doctor is actually a Central Command field agent and gets stunned and apprehended.

Also, each protagonist would have their own agenda. When the station decides to rebel against Central Command, the field agent would not align themselves with security, for example.

I suggest the following protagonist roles:

1 Central Command secret service agent
2 Superhero (with a random superpower) + very, very rare (a Superman-like character with all their powers)
3 Survivalist (objective to survive) starts with a random sidearm and a pillbox full of healing patches"

**Comment by Jacquerel** [comment]
I am afraid this area is for bug reports, not suggestions. That's why when you tried to post this the template said:
```
Feature requests are not handled in the repository. The best place to discuss these ideas would be on the /tg/station 13 forums here: https://tgstation13.org/phpBB/viewforum.php?f=9&sid=5153c1c704a4fb1006bf7a265e45e03f
```

**Comment by kacperpl1234pl** [comment]
Damn thanks mate but wasent this spot on github to submit sugestions as well?

**Comment by Jacquerel** [comment]
> Damn thanks mate but wasent this spot on github to submit sugestions as well?

`Feature requests are not handled in the repository.`

**Comment by Sadboysuss** [comment]
> Damn thanks mate but wasent this spot on github to submit sugestions as well?

you're thinking of some downstream, /tg/ doesn't do that
