### ISSUE TITLE
Wallening showers

### ISSUE THREAD

**Issue by Ekaterina-von-Russland** [tgstation/tgstation#85679]
## Issue Summary

Shower is offset wrong

## Testmerges:

[#85392: '[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"' by MrStonedOne at commit a388037701](https://www.github.com/tgstation/tgstation/pull/85392)
[#85491: 'Wallening [IDB IGNORE] [MDB IGNORE]' by LemonInTheDark at commit f8ebf9b420](https://www.github.com/tgstation/tgstation/pull/85491)
## Reproduction:

~will post image after round end~

![image](https://github.com/user-attachments/assets/0c33cf22-0d06-41a3-99fe-ce1558794e8b)

**Comment by loganuk** [comment]
Need at least a map name please @Ekaterina-von-Russland - to go with the screenshot once you post it.

**Comment by Ekaterina-von-Russland** [comment]
Map is tram station but it's not the shower head that is offset wrong, it's the water that's supposed to be coming out of it.

**Comment by loganuk** [comment]
![image](https://github.com/user-attachments/assets/d383d449-de64-4f23-83b4-e4466d881496)

Delta Station - on Terry - They appear to come "behind" the shower head instead of in front now.
