### ISSUE TITLE
Metastation AI chamber turret control stealth mode (Wallening)

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#85677]
Reporting client version: 515.1642

## Round ID:
[233958](https://scrubby.melonmesa.com/round/233958)

## Testmerges:
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)
- [Wallening [IDB IGNORE] [MDB IGNORE]](https://www.github.com/tgstation/tgstation/pull/85491)

## Reproduction:

It's there, barely, its a lightbulb that flashes on and off (if there's any way to turn it off permenantly this item will be unselectable, the area of the light registers as floor when it blinks off :P), something more intuitive might be needed here :)

![image](https://github.com/user-attachments/assets/1c2b3c0c-ac8a-420c-b825-57947cd0dcfa)

**Comment by loganuk** [comment]
For the mapper working on Meta and Spriters - Change the VAR from "control_stun" to "control" - The flashing light still works after but stops the panel being invisible.

![image](https://github.com/user-attachments/assets/9afbf62b-a213-4470-9d51-24d1a53ee38a)

![image](https://github.com/user-attachments/assets/940f3987-b115-4869-b94d-eeeb1e2c01be)

**Posted in mapping thread:**
https://github.com/tgstation/tgstation/issues/85583
