### ISSUE TITLE
(Wallening) Tinted Windows no longer block line of sight

### ISSUE THREAD

**Issue by GPeckman** [tgstation/tgstation#85689]
Reporting client version: 515.1637

## Issue Summary

What the title says. They normally block LoS, but not with wallening.

## Round ID:
[234003](https://scrubby.melonmesa.com/round/234003)

## Testmerges:
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)
- [Wallening [IDB IGNORE] [MDB IGNORE]](https://www.github.com/tgstation/tgstation/pull/85491)

## Reproduction:

The easiest way to reproduce is to load up metastation and check the windows near robotics, I'm not aware of any other mapped-in tinted windows.

**Comment by deathrobotpunch** [comment]
can also be tested through meta’s interrogation room

**Comment by LemonInTheDark** [comment]
should be fixed
