### ISSUE TITLE
(Wallening) Reinforced window frames are stupidly strong

### ISSUE THREAD

**Issue by Inari-Whitebear** [tgstation/tgstation#85699]
## Issue Summary

As a Xeno Queen, dealing with these is absolute pain.

Takes 38 hits to destroy (and you keep getting shocked if electrified of course). Acid doesn't do much of anything, if anything at all.
Granted, you can walk over it instead of destroying it, but risk a chance each time of being shocked.

Old walls grille was like 3 slaps to destroy and instant with acid.

I nearly died three times trying to slap one to break it as a queen., and I'm not sure they respond to corrosive acid at all.

## Reproduction

1. Be Xeno
2. Break a window that has an electrified reinforced window frame (with power in the grid)
3. Slap the hell out of the frame trying to break it, get shocked a ton, if you manage to, it'll break after 38 slaps

**Comment by Sadboysuss** [comment]
unless they actually don't respond to corrosive acid this isn't a bug.

**Comment by Inari-Whitebear** [comment]
> unless they actually don't respond to corrosive acid this isn't a bug.

Seems like a big balance change for a visual PR

**Comment by Sadboysuss** [comment]
> Seems like a big balance change for a visual PR

This was always the case even before wallening.
Hitting an electrified grille shocked you, could even kill you outright if there was enough kw in the system.
You just have to use corrosive acid and the question is how effective was it before and after wallening

**Comment by Inari-Whitebear** [comment]
A single hit on a reinforced window frame takes it down 4 integrity, it has 150 integrity, so that's 38 slaps to break it. If you manage to, because you'll be shocked the hell out.

Putting acid on it, it doesn't seem to decrease in integrity.

Old walls, while the grille still shocks you, you need 3 slaps on the grille to break it. And corrosive liquid breaks it basically instantly.
