### ISSUE TITLE
(Wallening) New walls hide pipes

### ISSUE THREAD

**Issue by Inari-Whitebear** [tgstation/tgstation#85701]
## Issue Summary

Maybe this is intended? Old walls you could see pipes placed on them, new walls hide them.

In the Round ID we had this:
![image](https://github.com/user-attachments/assets/49240f69-64f7-4278-a37d-6b89033d9003)

The pipes were mismatched and didn't connect, but visually it's hard to see that because the walls hide a lot of it.

Doesn't help that the standard piping goes through them.

**Comment by Jacquerel** [comment]
For clarity for future developers, looks like this was on Manuel during the "shift walls down instead of players" test.

**Comment by Inari-Whitebear** [comment]
Oh yeah, maybe that contributes

**Comment by loganuk** [comment]
It's the same for all pipes on all views currently if the pipes are "In" the wall.

Not sure what the right fix for this one is as previously anything from the RPD just sat on top of the wall when placed.
