### ISSUE TITLE
Spare ID safe turns into a happy table when you open it

### ISSUE THREAD

**Issue by rageguy505** [tgstation/tgstation#85707]
Reporting client version: 515.1637

## Issue Summary
Spare ID safe turns into a happy table when you open it. It shouldnt do this.

## Round ID:
[234147](https://scrubby.melonmesa.com/round/234147)

## Testmerges:
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)
- [Wallening [IDB IGNORE] [MDB IGNORE]](https://www.github.com/tgstation/tgstation/pull/85491)

## Reproduction:
Open the spare ID safe

![image](https://github.com/user-attachments/assets/12ee2160-695c-487a-a800-3bfbf3104099)

**Comment by deathrobotpunch** [comment]
but he’s so happy!

**Comment by norsvenska** [comment]
_____________________
 |                              |
 |                              |
 |          o      o          |
 |              n              |
 |                              |
 |____________________|
 
 look how sad he is because you said he shouldnt exist :(

**Comment by Dawnseer** [comment]
Now this is what I call a feature

**Comment by CCC23** [comment]
HUH?

**Comment by actioninja** [comment]
featore
