### ISSUE TITLE
(wallening) AIs cannot open some of the windoors.

### ISSUE THREAD

**Issue by Constellado** [tgstation/tgstation#85715]
## Issue Summary
As much as I tried as an AI, I was not able to open some of the windoors. These ones on meta.
(took this from a round recording)
Medical storage windoor:

https://github.com/user-attachments/assets/37855c2d-954f-4d57-9c85-49ca13cf2d72

Science windoor:
![image](https://github.com/user-attachments/assets/7a95442b-a9ae-4b39-8c0a-6737f9cc0f56)

There is probably more windoors that I cannot open as an AI but I didnt check every one.

I know its not precise as I am unsure what actually causes this. Lots of other windoors work. Maybe its the ones with tables behind them? There is also a chance that maybe some pixels on those windoors do work but I didnt happen to click on those spots if it exists.

## Round ID:

[234219](https://statbus.space/rounds/234219) 

## Testmerges:
#85491 (Wallening.)
#85392

## Reproduction:
Try to open specific windoors as an AI. Won't happen!

**Comment by Dawnseer** [comment]
AIs? I can't do it as a carbon unless I walk into them
