### ISSUE TITLE
Wires are rendering below disposal pipes.

### ISSUE THREAD

**Issue by Constellado** [tgstation/tgstation#85714]
## Issue Summary
The wires are now rendering below the disposal pipes, making it impossible for an engineer fixing wires to actually see if the wires are cut without shift right clicking everything.

## Round ID:
I noticed it on [234211](https://statbus.space/rounds/234211)

## Testmerges:
#85491 (wallening. I think this caused this issue but I am unsure on that.)
#85392

## Reproduction:
![image](https://github.com/user-attachments/assets/7cbda49a-6205-4f72-83cb-69822cc7c8b6)

**Comment by Sadboysuss** [comment]
here's a screenshot of latest master:
![image](https://github.com/user-attachments/assets/47d203fc-0c31-45c6-bc4a-f2300b6456b9)

So yes this is caused by wallening

**Comment by Ghommie** [comment]
![immagine](https://github.com/user-attachments/assets/db50173d-cb38-4136-97bd-40f937bbbcd1)

This has been fixed from what I see.
