### ISSUE TITLE
(WALLENING) Problems clicking on items laying next to (on top of) walls.

### ISSUE THREAD

**Issue by RobertRoberts2020** [tgstation/tgstation#85711]
## Issue Summary

Items, specially small items are impossible or very hard to pick up when they're laying (on top, next to) certain walls and airlocks.

## Round ID:
 [234007](https://scrubby.melonmesa.com/round/234007)
 

## Testmerges:
Wallening

## Reproduction:

Drop small items on top of, next to walls and airlocks and people have a really hard time picking them up, unless they right click.

1)
https://www.youtube.com/watch?v=-ow3N1ADjLc
2)
https://www.youtube.com/watch?v=WSkcbDwNgFI
3)
https://www.youtube.com/watch?v=HxsPTJ3Lm5Q
4)
https://www.youtube.com/watch?v=JNRd2pEg_uU

**Comment by actioninja** [comment]
This was an issue in an earlier version that was was fixed a while ago, melbert's downshift branch was based on the earlier version. I'm now unable to replicate while I was able to replicate on melbert's branch.
