### ISSUE TITLE
Getting hit by a sleeping carp'd bolt of change while polymorphed just makes you cease to exist

### ISSUE THREAD

**Issue by Hotmud9** [tgstation/tgstation#85722]
## Issue Summary
Basically, as a wizard who had wild shaped into a chaos magicarp, I was fighting CE in space, and I was attacking him point blank. Next thing I know, I'm a ghost, and for some reason my ghost teleported to the arrivals shuttle.
I didn't even have the chaos bolt readied (which has no indicator of when it's "selected" and will just auto-fire, which is probably its own separate issue as other spells like that don't function like that)
What had happened was, I somehow fired a bolt of change at him, despite trying to bite him, and he just so happened to have Sleeping Carp, as he was a traitor, and had access to it.
Still doesn't explain why I was deleted from existence

## Round ID:
[234273](https://scrubby.melonmesa.com/round/234273)

## Testmerges:
https://github.com/tgstation/tgstation/pull/85491
https://github.com/tgstation/tgstation/pull/85392

## Reproduction:
Be a wizard polymorphed into a chaos magicarp
Fight someone with scarp
fire at them with a chaos blast
???
cease to fucking exist

**Comment by necromanceranne** [comment]
Hidden feature of sleeping carp is to ki blast someone from existence, didn't you know?

**Comment by Sadboysuss** [comment]
please reproduce the issue by either making a video or adding new reproduction steps, this will be auto-closed in 7 days otherwise.
