### ISSUE TITLE
Wizards can Deja Vu back to their ship.

### ISSUE THREAD

**Issue by leaKsi** [tgstation/tgstation#85737]
## Issue Summary

Wizards can return back to their ship using the Deja Vu park.

## Round ID:
Tested locally only
## Reproduction:

1. Buy the Deja Vu perk.
2. Buy something to break engines with. (Only fireballs/lesser summon guns work, none of the melee weapons do enough damage to actually damage them)
3. Break an engine and step 1 tile into hyperspace.
4. You're now in a different area (not `/area/centcom/wizard_station`), so Deja Vu activates and records that location.
5. From now on, every 60 seconds you will be teleported back to your ship and fully healed.

**Comment by Jacquerel** [comment]
lmao
this probably needs to wait the full duration of the effect after you teleport before activating 😅
