### ISSUE TITLE
Cannot pull objects through certain doors 

### ISSUE THREAD

**Issue by Eronymun** [tgstation/tgstation#85743]
Reporting client version: 515.1641

## Issue Summary

![morebugs](https://github.com/user-attachments/assets/177ec2b5-adc7-4994-9823-3ef88012272e)

Pull a burst engine out of a pod and instead of it being pulled it just gets stuck behind the pod door, even when the pod door is completely open.

## Round ID:
[234405](https://scrubby.melonmesa.com/round/234405)

## Testmerges:
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)
- [Wallening [IDB IGNORE] [MDB IGNORE]](https://www.github.com/tgstation/tgstation/pull/85491)

## Reproduction:

Try to pull a burst engine out from a wall through a pod door and notice that it won't budge (but it will change direction)

**Comment by LemonInTheDark** [comment]
Feature, the door is blocking movement NORTH/SOUTH.
