### ISSUE TITLE
Firelocks of Pure Darkness in Icebox Toxins (Wallening)

### ISSUE THREAD

**Issue by Eronymun** [tgstation/tgstation#85745]
Reporting client version: 515.1641

## Issue Summary

![darknessfirelocks](https://github.com/user-attachments/assets/92cac657-a704-4e05-a516-578b0e5a12a3)

When these firelocks close they block all vision between them and the other side, no idea why, it may be related to multiz?

## Round ID:
[234413](https://scrubby.melonmesa.com/round/234413)

## Testmerges:
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)
- [Wallening [IDB IGNORE] [MDB IGNORE]](https://www.github.com/tgstation/tgstation/pull/85491)

## Reproduction:

Trigger the firelocks in lower toxins on icebox, watch as your vision of lower icebox is cut in half.

**Comment by the-orange-cow** [comment]
I noticed this happening in tram toxins as well.

**Comment by LemonInTheDark** [comment]
if you saw this with directional firelocks then it makes sense. it's also possible directional opacity is yorked? idk
