### ISSUE TITLE
Cannot interact with Opened Blast Doors (Wallening)

### ISSUE THREAD

**Issue by Eronymun** [tgstation/tgstation#85750]
Reporting client version: 515.1641

## Issue Summary

![image](https://github.com/user-attachments/assets/e0a0fffb-425b-41e5-a382-fcbe526f854f)

Screenshot shows closed doors because I forgot to take one when I noticed it. If you open a blast door and then try to screw driver it to put a signaler inside it, the door simply cannot be interacted with, all your clicks will go to the floor instead.

## Round ID:
[234431](https://scrubby.melonmesa.com/round/234431)

## Testmerges:
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)
- [Wallening [IDB IGNORE] [MDB IGNORE]](https://www.github.com/tgstation/tgstation/pull/85491)

## Reproduction:

Open a blast door and try to screwdriver the opened blast door.

**Comment by Thunder12345** [comment]
Same issue applies to opened firelocks

**Comment by Metekillot** [comment]
Same issue also applies to open double wide doors, such as the foyer to Ice Box Botany
