### ISSUE TITLE
(wallening) the fence doesn't look right

### ISSUE THREAD

**Issue by Graybear98** [tgstation/tgstation#85753]
![Новый точечный рисунок (2)](https://github.com/user-attachments/assets/d2269916-f95b-4bf1-8fa4-26da98f6b665)

**Comment by OuroborusReporter** [comment]
Similar issue occurs with the metal fence around the mining dock entrance in Icebox

**Comment by LemonInTheDark** [comment]
fences have their dirs wrong but also were given sprites that only really make sense WITH said wrong dirs so I think this ends up being a mapping issue
