### ISSUE TITLE
(Wallening?) The CE's Office APC cannot be interacted with on Icebox

### ISSUE THREAD

**Issue by Justice12354** [tgstation/tgstation#85757]
Reporting client version: 515.1640

## Issue Summary
I tried rotating it a bunch and it can only be interacted with when it's dir variable equals to 1

## Round ID:
[234514](https://scrubby.melonmesa.com/round/234514)

## Testmerges:
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)
- [Wallening [IDB IGNORE] [MDB IGNORE]](https://www.github.com/tgstation/tgstation/pull/85491)

**Comment by LemonInTheDark** [comment]
fixed, my bad

**Comment by LemonInTheDark** [comment]
or well sorta I changed a < 16 to <= 16 but the core may be flawed, we'll see
