### ISSUE TITLE
Detective 357. chance capped at 25%

### ISSUE THREAD

**Issue by Shoddd** [tgstation/tgstation#85766]
## Issue Summary
Chance for misfire while using 357. in detectives revolver doesn't go past 25%.

## Round ID:
No round ID, found on local host.

## Reproduction:
1.) Wrench .38 detective revolver into 357.

2.) Fire as any number of shots

Instead of increasing 25% per shot capped at 25%.

**Comment by SmArtKar** [comment]
```misfire_probability = clamp(misfire_probability, 0, misfire_probability_cap)```

misfire_probability_cap is set to 25 on all ballistics by default, and detective's revolver doesn't increase it despite what the comment says

**Comment by necromanceranne** [comment]
No, the comments are just outdated, this was a deliberate decision because I was going to get around to a recursive loop in misfire code and just...never did! At this point I'm mostly waiting for someone to make misfiring a component instead.
