### ISSUE TITLE
Wallening - Shadows are applied to things that shouldn't have them

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#85765]
Reporting client version: 515.1642

## Round ID:
[234544](https://scrubby.melonmesa.com/round/234544)

## Testmerges:
- [Wallening [IDB IGNORE] [MDB IGNORE]](https://www.github.com/tgstation/tgstation/pull/85491)
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)

## Reproduction:
![image](https://github.com/user-attachments/assets/9422e856-a669-4183-8bad-8a4e36896b74)
![image](https://github.com/user-attachments/assets/8d890ca6-bb82-4ddf-ac05-6e6761219533)
Unknown if living players can see the ghost shadows but the AI eye one is just silly

**Comment by DATA-xPUNGED** [comment]
@Jacquerel

**Comment by Jacquerel** [comment]
Ghosts are supposed to have shadows so you can see where you are, they aren't visible to living players.
I thought I had removed the one from AI eye but I guess it didn't work.
