### ISSUE TITLE
(WALLENING) Being thrown onto a closed crate or table or the like negates wallening offset

### ISSUE THREAD

**Issue by Inari-Whitebear** [tgstation/tgstation#85774]
## Issue Summary

Edit: Okay, this is just from being thrown in general

Being spit out of a disposals outlet onto something that makes you "lifted up", such as a closed crate or a table make you be then offset lower down after you climb down from the chest or table.
Basically, it negates the upwards tile offset:

![image](https://github.com/user-attachments/assets/c0a81bab-fec3-4813-beae-e4f6c4e2c8cb)

## Testmerges:

[#85491: 'Wallening [IDB IGNORE] [MDB IGNORE]' by LemonInTheDark at commit 7e768a6868](https://www.github.com/tgstation/tgstation/pull/85491)
[#85392: '[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"' by MrStonedOne at commit a388037701](https://www.github.com/tgstation/tgstation/pull/85392)

## Reproduction:

1. Get into disposals chute (easy on Metastation, take the one in Delivery Office)
2. Get spit out onto a closed crate, or table.
3. Move off of it

Alternatively build my LowMaker and AntiLowMaker contraptions (good naming):
![dreamseeker_zztplETrC5](https://github.com/user-attachments/assets/be2e5a04-a5d4-4fcf-aec5-b389fd9ffbbb)

**Comment by MrMelbert** [comment]
It's not disposals, it's being thrown 

You throw anything (mob or item), it loses offset

**Comment by Inari-Whitebear** [comment]
> It's not disposals, it's being thrown
> 
> You throw anything (mob or item), it loses offset

Hmm but onto a tablet or crate specifically then?

Because without it, it offsets me again for the disposals

**Comment by LemonInTheDark** [comment]
> It's not disposals, it's being thrown
> 
> You throw anything (mob or item), it loses offset

I thought I fixed this. fuck
