### ISSUE TITLE
Manifold pipes don't seem to work in mapping

### ISSUE THREAD

**Issue by Shadow-Quill** [tgstation/tgstation#85776]
## Issue Summary
While mapping with the smart manifold pipes, they acted as 4ways, instead of the expected T junction.

## Round ID:

N/A

## Reproduction:

Place manifold smartpipe in Strong DMM (I used a standard layer 3, green variety).
Save, compile map, load in. See that the manifold acts as 4way.

**Comment by MrMelbert** [comment]
The subtypes of pipes in the mapping tools are purely visual, all pipes are ultimately 4-way pipes / "smart pipes".

**Comment by Shadow-Quill** [comment]
> The subtypes of pipes in the mapping tools are purely visual, all pipes are ultimately 4-way pipes / "smart pipes".

Why do the manifold/straight pipes exist in the first place then? It seems like the intent is to allow to have mapped pipes that won't connect to pipes outside of their directions.

**Comment by MrMelbert** [comment]
fmpov they exist so you can visualize what more complex atmos setups (like atmos proper) looks like in-editor, where using 4w manifolds everywhere would look hideous

**Comment by Shadow-Quill** [comment]
Fair enough, albeit moderately confusing at first glance.

**Comment by actioninja** [comment]
Closing as not planned, not a bug
