### ISSUE TITLE
power sinks taking too much power ?

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#85779]
## Issue Summary

how it used to work was that when you placed a power sink, it would eat all the electricity and eventually detonate, now it detonates much faster than it use to, likely because of the semi recent energy changes

## Round ID:
[234626](https://scrubby.melonmesa.com/round/234626)

## Testmerges:
The following pull requests are currently test merged:
[#85491: 'Wallening [IDB IGNORE] [MDB IGNORE]' by LemonInTheDark at commit 7e768a6868](https://www.github.com/tgstation/tgstation/pull/85491)
[#85392: '[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"' by MrStonedOne at commit a388037701](https://www.github.com/tgstation/tgstation/pull/85392)

## Reproduction:

place a power sink on a live wire connected to the stations grid,  with an average SM setup without any zany upgrades it will detonate within 1 minute

**Comment by optimumtact** [comment]
At first I thought this was about them draining the networks and i was gonna be like uh yeah taht's what they do, but them exploding earlier does make sense if the wattage amoutns were changed and nobody rebalanced them.
