### ISSUE TITLE
using the medical borgs omni tool during surgery doesn’t activate the ‘this step requires a different tool’ and instead attacks the patient

### ISSUE THREAD

**Issue by deathrobotpunch** [tgstation/tgstation#85780]
## Issue Summary

using the medical borgs omni tool during surgery doesn’t activate the ‘this step requires a different tool’ and instead attacks the patient

## Reproduction:
1. start a surgery as a medical borg.
2. use the wrong tool in a step
3. experience the horror of accidentally sawing a patient

**Comment by Sadboysuss** [comment]
were you perhaps in combat mode?

**Comment by deathrobotpunch** [comment]
> were you perhaps in combat mode?

no as using tools that weren’t included in the omni tool like the blood filter gave the message
