### ISSUE TITLE
Tears in the Fabric of Reality are missing textures

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#85781]
Reporting client version: 515.1637

## Issue Summary
The Tears in the Fabric of Reality that ring in bitrunning sims are currently showing as pink and black squares. Possibly a lack of wallening sprites?

## Round ID:
[234665](https://scrubby.melonmesa.com/round/234665)

## Testmerges:
- [Wallening [IDB IGNORE] [MDB IGNORE]](https://www.github.com/tgstation/tgstation/pull/85491)
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)

## Reproduction:
1. Join a bitrunning sim
2. 
![Screenshot 2024-08-12 234002](https://github.com/user-attachments/assets/b25e4e24-65e1-41de-8220-9eaba91728cd)

**Comment by optimumtact** [comment]
I'm actually nto sure if this is intended or not lol

**Comment by OuroborusReporter** [comment]
It's still labelled as 'Tear in the Fabric of Reality'. Though I saw the normal 0s and 1s in a different sim - It might specifically be an issue with the Disposals Factory sim?
