### ISSUE TITLE
Labor shuttle stacking machine / points claim console award zero points

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#85789]
Reporting client version: 515.1642

## Round ID:
[234745](https://scrubby.melonmesa.com/round/234745)

## Testmerges:
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)
- [Wallening [IDB IGNORE] [MDB IGNORE]](https://www.github.com/tgstation/tgstation/pull/85491)

## Reproduction:

Spawn in on the labor camp shuttle, feed iron or something to the stacking machine, points claim console still says zero points

**Comment by SmArtKar** [comment]
Seems functional on master?

**Comment by Sadboysuss** [comment]
Please provide new reproduction steps or provide a video reenacting the issue. Otherwise, it will be auto-closed in 7 days.
