### ISSUE TITLE
Beepsky infinitely stacking pathfinding arrows to lag the client

### ISSUE THREAD

**Issue by Isratosh** [tgstation/tgstation#85783]
Reporting client version: 515.1641

## Issue Summary
[lagbots.webm](https://github.com/user-attachments/assets/11a6609a-df11-4ec1-a445-3beb22a34463)

Client lag quickly increased to near-frozen, but would resolve immediately if I moved out of view range.
The cleanbot left the room through the south airlock eventually and the lag remained with just Beepsky continuing to loop there for the rest of the round.

## Round ID:
[234691](https://scrubby.melonmesa.com/round/234691)

## Testmerges:
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)
- [Wallening [IDB IGNORE] [MDB IGNORE]](https://www.github.com/tgstation/tgstation/pull/85491)

## Reproduction:
I don't know what triggered this or how to reproduce it.

**Comment by LemonInTheDark** [comment]
![image](https://github.com/user-attachments/assets/baea2430-52d5-4689-93bb-468bf0a6743a)

**Comment by projectkepler-ru** [comment]
beepsky activating domain expansion to lagswitch all of the spy player and stop them from stealing him

**Comment by optimumtact** [comment]
Fixed by #86499

**Comment by optimumtact** [comment]
The lag was actually from the cleanbot, beepsky was innocent.
