### ISSUE TITLE
Trash cannons are non-functional

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#85793]
Reporting client version: 515.1642

## Round ID:
[234768](https://scrubby.melonmesa.com/round/234768)

## Testmerges:
- [Wallening [IDB IGNORE] [MDB IGNORE]](https://www.github.com/tgstation/tgstation/pull/85491)
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)

## Reproduction:
- Build a trash cannon
- Try to put welding fuel in it
- "The trash cannon is full"
- try to fire said trash cannon
- "Requires 15u to fire"
- Explode from sheer annoyance

**Comment by SyncIt21** [comment]
Duplicate #81226

**Comment by necromanceranne** [comment]
Well, that particular issue is related to food. I think this hasn't applied to objects until recently.

**Comment by SmArtKar** [comment]
Closing as duplicate
