### ISSUE TITLE
Animation glitch with chapel curtain

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#85806]
Reporting client version: 515.1641

## Issue Summary
![image](https://github.com/user-attachments/assets/e95b9c62-2932-4f23-b516-d770d6e42ee7)
`/obj/machinery/door/morgue`

https://github.com/user-attachments/assets/d3fd38c6-7094-437a-87ee-43d8d305d810

**Comment by Jacquerel** [comment]
Write better issue titles
