### ISSUE TITLE
Security bots look odd with dropshadows

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#85802]
Reporting client version: 515.1641

## Issue Summary
![image](https://github.com/user-attachments/assets/466dcb39-f039-4ab0-8e45-9e29ea1971cd)
![image](https://github.com/user-attachments/assets/20f318ea-61dd-4601-9eaa-283ca6c0ef29)

## Round ID:
local

**Comment by Jacquerel** [comment]
could probably do with shifting beepsky down a couple pixels yeah

**Comment by Sadboysuss** [comment]
> could probably do with shifting beepsky down a couple pixels yeah are you planning on updating this post or is this just a badly named issue about secbots?

I'm just going around and rapid-firing issue reports from stuff I'm seeing, there isn't much more info to be put here anyways.
