### ISSUE TITLE
Airlock shutters retract into bluespace

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#85805]
Reporting client version: 515.1641

## Issue Summary
In this video you can see that the airlock shutters, when retracting to open - retract into another dimension, it breaks immersion.

https://github.com/user-attachments/assets/d12bfeb3-eaa5-429c-823e-06c1a5c3c39c

**Comment by Jacquerel** [comment]
Yes.

**Comment by Ghommie** [comment]
Just don't think too hard about it. A lot of things work like that.

**Comment by Sadboysuss** [comment]
![Uploading image_2024-08-14_163519564.png…]()

**Comment by Sadboysuss** [comment]
![image_2024-08-14_163536512](https://github.com/user-attachments/assets/676c3910-c1f1-4aa2-b5b5-f60a5f849a90)
