### ISSUE TITLE
RCD animation has graphical errors

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#85809]
Reporting client version: 515.1641

## Issue Summary
The very last part of the animation has holographic imagery when the construction has been complete already

https://github.com/user-attachments/assets/f0363a90-253e-4b30-b2e2-1921ef6f25dd

**Comment by Justice12354** [comment]
I have a rough feeling that it has always been like that. Did you test it with a prior version of our codebase to compare?

**Comment by Sadboysuss** [comment]
idk it's a new animation

**Comment by Justice12354** [comment]
Mh, I would bet a penny that the old animation's duration and the time it takes to build with the RCD do not match and whoever made the new animation kept the same time for the animation's duration... Or that's just a tick rate problem, bc I feel very confident that that issue has been around before the Wallening
