### ISSUE TITLE
Colorblind people will not be able to distinguish reinforced and normal windows

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#85811]
Reporting client version: 515.1641

## Issue Summary
The only difference in these sprites is a minor tint in color, colorblind people will not be able to distinguish these at a glance

![image](https://github.com/user-attachments/assets/b1204139-e23b-46ae-863e-b489ea5a1f04)

**Comment by Jacquerel** [comment]
I mean I am and I can

**Comment by Momo8289** [comment]
Side by side I can differentiate them, but I didn't know there was a difference visually until I saw this issue so yeah, not great.
