### ISSUE TITLE
Building directional structures with RCD no longer takes in account your dir

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#85810]
Reporting client version: 515.1641

## Issue Summary
Before, placing directional structure like a window would place it in the dir you were facing when the construction was done, now it places it in the direction you were facing when you started constructing, this is a big problem for engineers.

https://github.com/user-attachments/assets/7866f8d9-ae86-48ad-b97e-534ec5eed9e8

## Reproduction:
1. Begin constructing a directional window with RCD
2. Face the direction you want the window to be constructed
3. Window is always constructed in the direction you were facing when you started construction.

**Comment by Ben10Omintrix** [comment]
i plan to fix this soon. but for now, i should mention u can set the direction u want thigns to be built using the arrows top right corner 
![image](https://github.com/user-attachments/assets/8ef962c2-9ece-4f23-bbaa-dbd945772e37)

**Comment by Sadboysuss** [comment]
> i plan to fix this soon. but for now, i should mention u can set the direction u want thigns to be built using the arrows top right corner ![image](https://private-user-images.githubusercontent.com/138636438/357836660-8ef962c2-9ece-4f23-bbaa-dbd945772e37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NDM1MjAsIm5iZiI6MTcyMzY0MzIyMCwicGF0aCI6Ii8xMzg2MzY0MzgvMzU3ODM2NjYwLThlZjk2MmMyLTllY2UtNGYyMy1iYmFhLWRiZDk0NTc3MmUzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQxMzQ3MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDVjNTI1ZjhkZmIwMWJhNDI0NzZlZGMyZjdiYjE1MGQ1ZDQzN2QzOTVjZjk2YmNjMzYyMjdjOWVmMmE4NGI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.t8m1yzVgtzJQfuMQr1kyGPCaWs4qCLFplYg09qBq7Zo)

that's nice but still lost functionality
