### ISSUE TITLE
Delta station issues

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#85816]
Reporting client version: 515.1641

## Issue Summary
- nanotrasen logos are misplaced:
![image](https://github.com/user-attachments/assets/d8eaa517-2fb8-45e9-8ac2-b367fa8e9d3d)
![image](https://github.com/user-attachments/assets/15c1b563-69ee-4634-98d4-a7d8f21dc02e)

- aux base
![image](https://github.com/user-attachments/assets/b52ed3dc-3e6e-44cf-ad98-47a60c47a4b5)

- arrivals north east
![image](https://github.com/user-attachments/assets/12328ea7-c48d-405c-8c20-866130c426c6)

- arrivals north east
![image](https://github.com/user-attachments/assets/21dcc6bb-3f4f-4803-81d2-f1725c629dd4)

- arrivals north west
![image](https://github.com/user-attachments/assets/7e0bc0f3-8300-42e8-9c43-bc6ac4fac470)

- botany 
![image](https://github.com/user-attachments/assets/b0d04607-ae72-4702-ba2b-f0600b58e498)

- north west bridge
![image](https://github.com/user-attachments/assets/6857de06-0162-4db1-a3e2-1fe0641775b1)

**Comment by Sadboysuss** [comment]
![image](https://github.com/user-attachments/assets/ab0ba1ee-dcac-4fa9-9d96-147e7d645ef9)

also here's me standing with a moth character near a fabricator and it looks like he's absolutely massive, even though this character has no quirks

**Comment by MrMelbert** [comment]
The "space" signs in arrivals were intentionally left there, they're hung correctly they just need real wallening sprites 

For the NT signs is it just those or all of them? If it's all of them I would be pretty sad because I literally moved them all once pre-merge which means someone came through and broke them again

**Comment by Sadboysuss** [comment]
> For the NT signs is it just those or all of them? If it's all of them I would be pretty sad because I literally moved them all once pre-merge which means someone came through and broke them again

it's inconsistent, some of them look fine, some of them are displaced
