### ISSUE TITLE
You're known as "potted plant" indefinitely after picking up one.

### ISSUE THREAD

**Issue by Inari-Whitebear** [tgstation/tgstation#85827]
## Issue Summary

I'd assume from #85567

Basically if you pick up a potted plant your name (screentip and examine name) changes to "a potted plant", this persists after dropping the plant.

## Reproduction:

1. Pick up potted plant
2. Drop it again

**Comment by MrMelbert** [comment]
@Metekillot 

Also the `identity[VISIBLE_NAME_FORCED]` stuff is all borked and probably needs to be ripped out (because whether it functions or is broken depends entirely on the order the signals are registered which is out of the control of the recipient)

**Comment by Metekillot** [comment]
I must have missed a testing case. I'm working late tonight but I should be able to at least push a revert from work.
