### ISSUE TITLE
South facing Tall Stairs have a hole in them

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#85847]
## Issue Summary

![image](https://github.com/user-attachments/assets/6779a43a-e321-449c-b8a1-363be8ffa594)

![image](https://github.com/user-attachments/assets/ed8f3278-26c3-49b2-97aa-1dbbad955f75)

**Comment by SmArtKar** [comment]
right, I intended them to be placed right next to a wall but here we got a random offset?

**Comment by MrMelbert** [comment]
oh now that you mention it it does look fine when you offset it down
