### ISSUE TITLE
Camera dir helpers might be a bit bugged

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#85849]
## Issue Summary

![image](https://github.com/user-attachments/assets/55342a73-9ae4-4683-abd2-e8b691b594ed)

**Comment by LemonInTheDark** [comment]
![image](https://github.com/user-attachments/assets/d3a9df66-d2a3-4130-822b-52913c29108d)
![image](https://github.com/user-attachments/assets/0c809eb0-1596-4026-8631-13b804dcbf14)
![image](https://github.com/user-attachments/assets/08418c46-1a2d-47b5-bca3-5c35b8b014e5)
The mapping macro does not match the code logic. I think the mapping macro is right but I'm not sure, would need to check
