### ISSUE TITLE
Identity Bans are broken

### ISSUE THREAD

**Issue by SconesC** [tgstation/tgstation#8584]
Apply them all you want but they don't force randomname/body 

Happening on live Sybil

**Comment by RemieRichards** [comment]
Broken for ages, fairly certain this is a Dupe aswell.

**Comment by Menshin** [comment]
Can't reproduce on local server, either legacy mode or using an SQL database.

Any more info on triggering that bug ?

**Comment by Fayrik** [comment]
I just had a look into this and I couldn't reproduce it locally either.

**Comment by optimumtact** [comment]
>Critical

Aint nobody use that shit

**Comment by MrStonedOne** [comment]
They are broken, but in an odd way, I once had the issue where they worked, but couldn't be removed unless you disabled database bans, and removed the legacy ban.

**Comment by tkdrg** [comment]
The DB ban stuff for these is badly entangled with the NewBan/Legacy Ban stuff that's barely maintained and rarely used. Perhaps we should just deprecate those altogether.

**Comment by MrStonedOne** [comment]
Convert them to job bans. Rename job bans to role bans. Anything not a server ban should be a role ban

**Comment by tkdrg** [comment]
That makes sense too. Right now we have:
- Server permabans
- Server tempbans
- Job permabans
- Job tempbans
- Identity permabans
- Admin permabans
- Admin tempbans
- Sticky permabans

That's too much if you ask me. I'll try merging identity bans onto jobbans. One thing to consider as well is culling admin tempbans, as they are meant to be a stopgap measure against a rogue admin until somebody with remote access can strip their powers.

**Comment by MrStonedOne** [comment]
Remove temp vs perma, make expires allow null, and if expires is null, perma, else, temp. No need to merge that with type. Remove admin ban, make that a field. 'Applies to admins', now we can have admin job bans. Remove type, if role is null, its a server ban, else role/job ban. Remove duration, its not used, expires is.

**Comment by Shadowlight213** [comment]
Fixed. Please close
