### ISSUE TITLE
plasmamen are inexplicably slower

### ISSUE THREAD

**Issue by gorillion** [tgstation/tgstation#85850]
Reporting client version: 515.1640

## Issue Summary

every round ive played today has had my static, palladium xiv, a plasmaman, noticeably slower than all other players. no mood debuffs, not on walk, nothing else of the sort, just like 25-50% slower. ive had an admin fix it manually a few times, they said something about my slowdown being set weird for no reason (the admin was... justice, i think)

## Round ID:
[234851](https://scrubby.melonmesa.com/round/234851) but it also happened on every other round i played today 8/14/24

## Testmerges:
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)

## Reproduction:

roundstart as a plasmaman & go slow

**Comment by iwishforducks** [comment]
Probably due to this PR that adds a slowdown to the armor datum for space helmets https://github.com/tgstation/tgstation/pull/85704

**Comment by TheVekter** [comment]
> Probably due to this PR that adds a slowdown to the armor datum for space helmets #85704

@Watermelon914 I think you forgot to exempt plasmaman helmets

**Comment by Sadboysuss** [comment]
pretty sure it's fixed now

**Comment by Sadboysuss** [comment]
https://github.com/tgstation/tgstation/pull/86783
