### ISSUE TITLE
Campbell is down/bugged!?

### ISSUE THREAD

**Issue by Thrugdelmir** [tgstation/tgstation#85854]
## Issue Summary

I can either not reach Campbell (Connection failed after handshake. (code 0)) or get "A SQL error occurred during this operation, check the server logs." error message

**Comment by LemonInTheDark** [comment]
This isn't a good place to report this because we do not control the /tg/station servers. If it's somehow an issue with linux maybe but the thing to do is to ping @Keyholders (or really just MSO) in the discord.

That said I've seen this so I'll yell at them for you

**Comment by Thrugdelmir** [comment]
Thank you!
