### ISSUE TITLE
A fair amount of wall mounts have no south facing sprites, so they shouldn't have south facing mapping helpers

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#85868]
## Issue Summary

Posters, buttons, many signs (even signs which were already resprited), and more have no south facing sprite, and I would expect they never get a south facing sprite

![image](https://github.com/user-attachments/assets/212646a6-5946-48ba-94f4-20878259d39f)

![image](https://github.com/user-attachments/assets/36bef68d-97a8-4e2b-906d-84ed58d029d1)

So I don't think they should have south facing mapping helpers, or at the very least their south facing helpers should be `ERROR`s. It's a little misleading to mappers (oh i can place a south sign here, oh why is it invisible despite having a preview image) and would also make it easier to find / delete existing south facing signs (obv won't be a problem going forward but sure is one now)

**Comment by MrMelbert** [comment]
In a similar vein, if we don't plan on adding west/east facing sprites to certain signs or to posters ever, we should just delete it and only have north facing sign/poster helpers

**Comment by ninjanomnom** [comment]
The helper should stick around since a mapper could want it on a shuttle which then rotates to make the object visible, but they do need an icon you can see at least in mapping.
