### ISSUE TITLE
heretic's rust walker ritual producing infinite rust walkers without consuming materials

### ISSUE THREAD

**Issue by nianjiilical** [tgstation/tgstation#85925]
## Issue Summary

rust heretic did the ritual to summon a rust walker, the materials weren't consumed, millions must rust

## Reproduction:

1) be rust heretic
2) make rust walker
3) it seemingly does not consume the materials
4) make 25 additional rust walkers

the only seemingly unusual part about this is that the rune was in space but otherwise im not quite sure what caused it (all the bodies were dragged there by the 25 rust walkers)

![image](https://github.com/user-attachments/assets/c6e48acc-8126-4e2d-8cc5-f86f3244abb9)

notably theres a dupe issue ([#51717](https://github.com/tgstation/tgstation/issues/51717)) but its like four years old so

**Comment by MrMelbert** [comment]
#83448

**Comment by Metekillot** [comment]
working on this now
