### ISSUE TITLE
Syndicate Battlecruiser shuttles cannot fly to the station (possibly just Birdshot)

### ISSUE THREAD

**Issue by Isratosh** [tgstation/tgstation#85938]
## Issue Summary
Navigational camera consoles on the various small shuttles in the hangar of the battlecruiser cannot be directed to the station Z level. There is an action button to view camera locations but it only lists the Starfury Battlecruiser where you are currently located, out in a space Z level.

## Round ID:
[235033](https://scrubby.melonmesa.com/round/235033)

## Reproduction:
1. complete battlecruiser final objective / spawn as a battlecruiser team member
2. click navigation computer in the fighters or the corvette
3. cannot move camera to the station to select an appropriate destination

**Comment by Sadboysuss** [comment]
Which station

**Comment by Isratosh** [comment]
Birdshot

**Comment by Sadboysuss** [comment]
Battlecruisers need a syndicate docker so I'm gonna go on whim and say it just doesn't have one of those
