### ISSUE TITLE
Captain's spare ID safe has no sprite for `opened`

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#85930]
## Issue Summary

Open the spare ID safe, it goes invisible

**Comment by MrMelbert** [comment]
Weirdly #85707 also exists but it's not turning into a happy table it's just invisible

**Comment by san7890** [comment]
#81762 changed it so that safes were open by default, and that the special case we changed the sprite to would be the closed state, so maybe something got tweaked in wallening i think
