### ISSUE TITLE
Displays on the south wall facing north bleeds into tile above it

### ISSUE THREAD

**Issue by PaznerIV** [tgstation/tgstation#85968]
### Client Version:

515.1642

### Issue Summary:

so when theirs a display or newscaster placed on the wall south for some reason I can interact with it not only on the tile that it is on but the tile north of it as well

link below is showing what talking about yellow square being the newscaster and Im able to interact with it red square is also where I can also interact with it as well
https://imgur.com/a/cum5rh8

### Round ID:

[235127](https://scrubby.melonmesa.com/round/235127)

### Reproduction Steps:

go to any newscaster or display on the south wall
mouse over the tile north of it

**Comment by LemonInTheDark** [comment]
This is down to issues with how we do the click bubbles, @SmArtKar is workin on a fix rn
