### ISSUE TITLE
Pikachu I choose you!

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#85985]
### Issue Summary:

https://github.com/user-attachments/assets/799a35e4-7495-49f9-b674-c39f8fb977db

https://github.com/user-attachments/assets/58d38a6a-47c4-48fd-85cf-353fc8cfb9ce

Because closets get turned into a normal item - you can fishing rod them.

### Round ID:

noticed on wallstation: https://github.com/wallstation13/wallstation13/issues/129

### Reproduction Steps:

1. Wrap a Closet in wrapping paper
2. Rest
3. Use fishing rod to reel in the large parcel

**Comment by TheVekter** [comment]
I don't want this fixed until I see a rev clown roll up on the Captain and throw a locker full of assistants at him.

**Comment by FoxUkraine1** [comment]
That me keith alex who did it do that hiliarous

**Comment by EuSouAFazer** [comment]
"Where did the armory go"
The suspiciously locker-shaped package in my pockets:

**Comment by Dawnseer** [comment]
Observe proper lifting ergonomics, get to lift larger objects. Seems like a feature to me!

**Comment by SmArtKar** [comment]
smh shouldn't be fixed at least it gets abused at least once on live

**Comment by SyncIt21** [comment]
Duplicate #85893.

**Comment by Oxotnak** [comment]
It's also possible to somehow unwrap it by person in closet when you put it in bag and you'll be able to open/close it while IT'S STILL WORK AS CLOSET ON YOUR TILE AND YOU CAN DEVOUR ITEMS AND PEOPLE. AND PEOPLE WILL BE UNABLE TO LEAVE IT BY ANY MEANS. AND YOU CAN TRAP YOURSELF IF YOU DROP BAG ON FLOOR AND CLOSE CLOSET. It's hilarious actually untill someone will use it not for fun
![image](https://github.com/user-attachments/assets/f852db60-d248-4c5d-9d6a-96765d48481f)

**Comment by SmArtKar** [comment]
> It's also possible to somehow unwrap it by person in closet when you put it in bag and you'll be able to open/close it while IT'S STILL WORK AS CLOSET ON YOUR TILE AND YOU CAN DEVOUR ITEMS AND PEOPLE. AND PEOPLE WILL BE UNABLE TO LEAVE IT BY ANY MEANS. AND YOU CAN TRAP YOURSELF IF YOU DROP BAG ON FLOOR AND CLOSE CLOSET. It's hilarious actually untill someone will use it not for fun ![image](https://private-user-images.githubusercontent.com/107066254/360843609-f852db60-d248-4c5d-9d6a-96765d48481f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MDI4MzQsIm5iZiI6MTcyNDQwMjUzNCwicGF0aCI6Ii8xMDcwNjYyNTQvMzYwODQzNjA5LWY4NTJkYjYwLWQyNDgtNGM1ZC05ZDZhLTk2NzY1ZDQ4NDgxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QwODQyMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOWQ0ODQwMjA3NzMwNDc4MmVmZTNhOTI4YzIyNTQ5MDdjMDdiOTRkOGZlYWE0NjVkNmUyOWUzYWY0MmIxNDRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cUeId0qB3eVdTlPxUJh6gL6y7qaYDo1tjEvi_vsSaTs)

vore

**Comment by Sadboysuss** [comment]
You can also pick up the packaged lockers with an evidence bag

**Comment by TheVekter** [comment]
If this bug wasn't something that's existed in the game for ages, it'd be an easy fuck-up candidate.
