### ISSUE TITLE
Can't repair clothing with storage

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#85993]
### Issue Summary:

Damaged clothing that has a storage component cannot be repaired with cloth. Attempting to use cloth on such items just tries to put the cloth in its storage, regardless of if the storage is filled (just errors with 'storage full') or if the cloth is too big for the storage. Combat mode does not affect this. Likely an attack chain bug.

### Round ID:

Downstream issue from https://github.com/Bubberstation/Bubberstation

### Reproduction Steps:

Find a piece of clothing with storage (such as a fedora) and wear it
Set yourself on fire to damage the clothing
Get some cloth, attempt to repair item
Character will attempt to store cloth, will not repair.

**Comment by projectkepler-ru** [comment]
@SmArtKar  I should note similarly it also mean you can't attach stuff to uniform due to chainattack shenanigan

**Comment by SmArtKar** [comment]
> @SmArtKar  I should note similarly it also mean you can't attach stuff to uniform due to chainattack shenanigan

Do we have any jumpsuits with storage? Likely why it hasn't been caught it yet if we don't

**Comment by projectkepler-ru** [comment]
> > @SmArtKar  I should note similarly it also mean you can't attach stuff to uniform due to chainattack shenanigan
> 
> Do we have any jumpsuits with storage? Likely why it hasn't been caught it yet if we don't

on TG natively? No- or- rather. not one that need to be repaired
downstream we had one of the jumpsuit that can store a small candy corn as a homestuck reference but it ended up causing it to be both unadjustable (suit sensors cant be adjusted on it unless you open the context menu) and cant be repaired, cant attach stuff to it etc

**Comment by Dawnseer** [comment]
> Do we have any jumpsuits with storage? Likely why it hasn't been caught it yet if we don't

Technically yes if you attach a pocket protector to it
