### ISSUE TITLE
Heretics in the Ragnarok Deathmatch map can shatter blades

### ISSUE THREAD

**Issue by Rex9001** [tgstation/tgstation#85997]
### Client Version:

515.1642

### Issue Summary:

Heretics in the Ragnarok Deathmatch map can shatter blades, allowing them to get to the station in any safe area with no consequence.

### Round ID:

[235269](https://scrubby.melonmesa.com/round/235269)

### Reproduction Steps:

1. Deathmatch 
2. Select Ragnarok map
3. Use heretic warrior or invoker
4. Press z with the blade in hand
5. Free respawn

**Comment by TheVekter** [comment]
It's gonna be a spicy vote for 2024's fuckup of the year

**Comment by DATA-xPUNGED** [comment]
I imagine that the fix here would be to make a subtype which you can't shatter?

**Comment by SmArtKar** [comment]
> I imagine that the fix here would be to make a subtype which you can't shatter?

no, the fix is to either make areas noteleport or figure out why cordons aren't preventing Z level teleportation
