### ISSUE TITLE
Can't load anything in the "lazy_templates" folder using the "Map Template - Place" admin verb

### ISSUE THREAD

**Issue by GPeckman** [tgstation/tgstation#86005]
### Client Version:

515.1637

### Issue Summary:

What the title says. The code responsible for generating the list treats the folder as its own thing instead of displaying things inside the folder: 

![Screenshot 2024-08-20 183504](https://github.com/user-attachments/assets/7837c285-5835-48d9-a9a5-d90783344b4d)

So anything inside that folder is functionally inaccessible.

### Round ID:

N/A tested locally

### Reproduction Steps:

Use the "Map Template - Place" admin verb and either scroll down or search for "lazy"

**Comment by unit0016** [comment]
There's a separate, dedicated verb for doing this properly. In in Admin -> Events -> Load/Jump Lazy Template.

Granted; this prevents you from putting lazy templates off of the lazy template z-level.. but admittedly; that's probably best.

**Comment by GPeckman** [comment]
Oh shit, good catch. Unfortunately, it seems I've discovered another bug in the process.
