### ISSUE TITLE
Hierophant forgot how to obliterate

### ISSUE THREAD

**Issue by MelokGleb** [tgstation/tgstation#86017]
### Client Version:

515.1642

### Issue Summary:

if you die to hiero, theres a line in chat
The hierophant obliterates yourname!
but megafauna cant gib or dust anymore

### Round ID:

[235341](https://scrubby.melonmesa.com/round/235341)

### Test Merge Information:

- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)

### Reproduction Steps:

1. find hiero
2. skill issue
3. "The hierophant obliterates yourname"
4. it didnt

**Comment by SmArtKar** [comment]
should probably change the line to something else
