### ISSUE TITLE
Cannot dump donk pockets straight from box into microwaves

### ISSUE THREAD

**Issue by Richie9999** [tgstation/tgstation#86021]
### Client Version:

515.1639

### Issue Summary:

Cannot dump donk pockets straight from box into microwaves

### Round ID:

[235365](https://scrubby.melonmesa.com/round/235365)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Death of mutant bodyparts AND external organs](https://www.github.com/tgstation/tgstation/pull/85137)

### Reproduction Steps:

Can no longer dump the donkpockets within a box of donkpocket brand donkpockets straight into a microwave by clicking on the microwave with the donkpocket box full of donkpockets in hand, instead have to individually remove each donk and put it in the microwave.

Acquire box of donkpocket brand donkpockets. Go to any microwave, click on the microwave with the box full of delicious and nutritious donkpockets. Nothing happens. Cry over the loss of efficiency in how you must now individually place the donks.

**Comment by SmArtKar** [comment]
Not a bug, #85530 changed behavior to RMB
