### ISSUE TITLE
Chasms can be used to smuggle things and people interdimensionally

### ISSUE THREAD

**Issue by Eronymun** [tgstation/tgstation#86033]
### Issue Summary:

Chasms teleport their contents to a collective bottomless pit that can be fished out of via any chasm.

There are chasms in deathmatch, and there are chasms in various virtual domains.

This lets you smuggle things out of the virtual world or death match by fishing in lavaland chasms.

### Reproduction Steps:

1. Load up the zombie domain or something
2. Cover yourself in whatever you want to cross the virtual border with
3. Fall into a bottomless pit
4. Wake up and go to lavaland with your fishing poll
5. Become a gorillnaire on your instagib rifle trade empire.

**Comment by GPeckman** [comment]
I nominate this for fuckup of the year 2024

**Comment by TheVekter** [comment]
busy week for the list!
