### ISSUE TITLE
Roulette machines do not appear to currently pay out.

### ISSUE THREAD

**Issue by Jeffman139** [tgstation/tgstation#86038]
### Client Version:

515.1641

### Issue Summary:

When you attempt to gamble at roulette machines, they do not properly pay out.

NOTE - this was on a downstream that directs all their bug reports to this github.

### Reproduction Steps:

1. Go to an active, bolted lotto machine.
2. Select a bet and roll via ID card.
3. Win, and receive no payout.

**Comment by Jeffman139** [comment]
Entirely Skill-Based Game exclaims, "You have won 300 credits! Congratulations!"
 Payday processed, account now holds 890 cr.
Entirely Skill-Based Game beeps, "The result is: 2 black"
Entirely Skill-Based Game exclaims, "You have won 200 credits! Congratulations!"
[Science] Xulia hisses, "I do however have the grav core."
You feel like you're going to throw up!
[Science] Xulia hisses, "Wait nevermind I dont."
Entirely Skill-Based Game beeps, "The result is: 22 black"
Entirely Skill-Based Game beeps, "You lost! Better luck next time"
Entirely Skill-Based Game beeps, "The result is: 27 red"
Entirely Skill-Based Game exclaims, "You have won 200 credits! Congratulations!"
Entirely Skill-Based Game beeps, "The result is: 4 black"
Entirely Skill-Based Game exclaims, "You have won 200 credits! Congratulations!"
Entirely Skill-Based Game beeps, "The result is: 32 red"
Entirely Skill-Based Game exclaims, "You have won 300 credits! Congratulations!"
Entirely Skill-Based Game beeps, "The result is: 4 black"
Entirely Skill-Based Game beeps, "You lost! Better luck next time"
Entirely Skill-Based Game beeps, "The result is: 14 red"
Entirely Skill-Based Game exclaims, "You have won 300 credits! Congratulations!"
Entirely Skill-Based Game beeps, "The result is: 6 black"
Entirely Skill-Based Game beeps, "You lost! Better luck next time"
Entirely Skill-Based Game beeps, "You do not have the funds to play! Lower your bet or get more money."

Bet was 100 credits throughout

**Comment by Sadboysuss** [comment]
What downstream was it

**Comment by timothymtorres** [comment]
The money is spit out automatically on the floor. (underneath the slot machine so you need to alt+click) For some reason, it only does this for jackpots.

**Comment by SuperNovaa41** [comment]
Doesn't really seem to be an issue? It would be really helpful if you actually included the downstream.
The code for jackpot versus regular payout is not different, and when testing it on local it drops south of the roulette table

**Comment by Sadboysuss** [comment]
Please provide new reproduction steps or provide a video reenacting the issue. Otherwise, it will be auto-closed in 7 days.
