### ISSUE TITLE
Voidwalker can get bioscrambled

### ISSUE THREAD

**Issue by Time-Green** [tgstation/tgstation#86045]
### Issue Summary:

Voidwalkers are affected by bioscrambler anomaly, causing horrible abominations

### Round ID:

Irrelevant (and I forgot)

### Reproduction Steps:

1. Be a voidwalker
2. Get bioscrambled
3. God's coming

![image](https://github.com/user-attachments/assets/c13b474d-232d-4847-a4d4-28438e330c43)

**Comment by Sadboysuss** [comment]
Is this really a bug though? Nightmares can get affected by bioscramblers too and I don't see any reason they shouldn't, adds to the sandbox and makes for some funny moments.

**Comment by Time-Green** [comment]
> Is this really a bug though? Nightmares can get affected by bioscramblers too and I don't see any reason they shouldn't, adds to the sandbox and makes for some funny moments.

I feel like bioscrambler should at least respect mutation immunity/no-dna. Nightmare would be similairly bugged

**Comment by Kiromaka** [comment]
Oh hey thats me, I dont think its should be fixed, it brakes nothing and looks hillarous, at least I dont think it affected me in any way except looks.
