### ISSUE TITLE
Genetic Mutations occasionally do not unlock when solved

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#86050]
Reporting client version: 515.1637

## Issue Summary
Filling in all matching XX pairs for a mutation occasionally results in the cells losing their highlight, like they do when you solve a mutation, but no mutation unlocking and the entry remaining as an unknown mutation. Changing cells around at this point does nothing to fix the issue - The only solution seems to be finding someone else with the mutation and solving it in them.

## Round ID:
[235503](https://scrubby.melonmesa.com/round/235503)

## Testmerges:
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)

## Reproduction:
It's not consistent enough to have an exact plan to recreate it, but I generally see it around once every 2 or 3 genetics shifts. The below image shows the mutation, and the matching gene readout from a different monkey that had it, showing the cells. I promise that all XXs in the readout were either solved or were only missing one cell to be solved before I reached this point.
![Screenshot 2024-08-24 002605](https://github.com/user-attachments/assets/8303ef5f-0c5f-4026-bdea-9a9343494d75)

**Comment by Time-Green** [comment]
Did your subject have other mutations active? Some mutations, like gigantism, refuse to activate if you have something like dwarfism active

**Comment by necromanceranne** [comment]
I think that'd be a UX issue if so. I hadn't drawn the conclusion this was caused by conflicting mutations before now, but if that is the case that is really annoying since the game adamantly refuses to tell you that this is why.

**Comment by Time-Green** [comment]
> I think that'd be a UX issue if so. I hadn't drawn the conclusion this was caused by conflicting mutations before now, but if that is the case that is really annoying since the game adamantly refuses to tell you that this is why.

Yeah uhhh this issue pops up every once in a while and that's always the cause

**Comment by OuroborusReporter** [comment]
> Did your subject have other mutations active? Some mutations, like gigantism, refuse to activate if you have something like dwarfism active

Think he might have had Heat Adaptation on, yeah. If having that blocks Cold Adaptation, or the two of them still block Pressreu Adaptation, there's a solid chance this is the cause

**Comment by Time-Green** [comment]
Yeah then that’s it

**Comment by Time-Green** [comment]
We could throw up an issue for it not being clear
