### ISSUE TITLE
Projectile with reflectable = false can still be deflected with scarp

### ISSUE THREAD

**Issue by projectkepler-ru** [tgstation/tgstation#86051]
### Client Version:

515.1643

### Issue Summary:

During testing for one of my pull request, I wanted to try and make a projectile that can't be deflected by scarp
setting
`var/reflectable = FALSE` 
does not appear to actually do anything

### Round ID:

N/A

### Test Merge Information:

N/A

### Reproduction Steps:

Create a custom projectile with reflectable = FALSE
test in game against a sleeping carp user
still deflected

**Comment by necromanceranne** [comment]
This isn't specifically for Sleeping Carp deflection, but objects causing deflection, such as energy shields and double-bladed energy swords.

Sleeping Carp is working as intended; it is total immunity to projectiles, no exceptions. The variable is the one that isn't accurate and that's just a naming issue.

**Comment by projectkepler-ru** [comment]
> This isn't specifically for Sleeping Carp deflection, but objects deflection, such as energy shields and double-bladed energy swords against energy/laser projectiles. I think also this is checked for reflector boxes, which are used to direct emitter fire into the supermatter.
> 
> Sleeping Carp is working as intended; it is total immunity to projectiles, no exceptions. The variable is the one that isn't accurate and that's just a naming issue.
> 
> This doesn't mean it isn't worth cleaning up for the sake of resolving future confusion. But this isn't a bug.

so there is 100% no way to make a projectile code-wise to bypass that?

**Comment by necromanceranne** [comment]
Not at the moment, no. For clarity, if this var was set to ``TRUE``, the only projectiles that Sleeping Carp could deflect is is lasers.

**Comment by projectkepler-ru** [comment]
> Not at the moment, no. For clarity, if this var was checked by Sleeping Carp, the only projectiles that Sleeping Carp could deflect is is lasers.

Ah, well. thank you.
I hope something comes up for this because it's kind of annoying as sometime not everything is documented (and being a maintainer myself) I get baffled by things like these
<3
