### ISSUE TITLE
The Curse of Thanos Or Why Am I Able To Eat Anomaly Cores

### ISSUE THREAD

**Issue by RandomDudeFromTheRim** [tgstation/tgstation#86062]
### Client Version:

515.1643

### Issue Summary:

![image](https://github.com/user-attachments/assets/c467fedc-3d7f-4e55-8d7f-2bcf0e6b4c00)

When I, in my infinite wisdom, gain the hunger of the mortal ones, I decide to eat.
![image](https://github.com/user-attachments/assets/37bdc215-4214-4ebd-8b06-8e57debaec13)
![image](https://github.com/user-attachments/assets/878eedfe-45a5-4b45-9427-ed4c21262267)
 By using the suicide prompt while a refined anomaly core is in my hand, I do the unthinkable:
![image](https://github.com/user-attachments/assets/6e03c3c8-9fe7-4ad8-ac3e-87f0168ae0af)
...and yeah, after that signaling the defusal radio frequency does absolutely nothing. So you just have an anomaly core (or many, if you decided to go Thanos mode) lodged in your tummy
![image](https://github.com/user-attachments/assets/d3bad392-51b6-42fd-9b56-a644eea3c31b)

### Round ID:

[235605](https://scrubby.melonmesa.com/round/235605)

### Reproduction Steps:

1. Get a refined anomaly core (whether it be via ordnance or anomaly defusing)
2. Hold in hand
3. Suicide
4. Consume the core (as if it was a signaler suicide)
5. Fin

**Comment by thgvr** [comment]
feature. yummy

**Comment by TheVekter** [comment]
This isn't really a "bug" as much as it is a circumstance of anomaly cores being a subtype of signalers for the purposes of making them, y'know. Signal-able.

I remember talking about this to folks when I introduced the anomaly core variants, but I don't think we ever decided it was worth fixing because, let's be honest, it's funny. I might introduce another suicide variant that makes you explode if you swallow five of them, idk.

**Comment by RandomDudeFromTheRim** [comment]
> This isn't really a "bug" as much as it is a circumstance of anomaly cores being a subtype of signalers for the purposes of making them, y'know. Signal-able.
> 
> I remember talking about this to folks when I introduced the anomaly core variants, but I don't think we ever decided it was worth fixing because, let's be honest, it's funny. I might introduce another suicide variant that makes you explode if you swallow five of them, idk.

That will be so funny lmao, besides it would finally fix the issue of cores not killing you when their appropriate frequency is pinged
