### ISSUE TITLE
Hellfire Laser shots (or at least the one from the Pirate Bay sim) are comically large

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#86072]
Reporting client version: 515.1637

## Issue Summary
I mean look at this thing, I'm shooting that shit the Death Star was charging up
![Screenshot 2024-08-25 162650](https://github.com/user-attachments/assets/a9bd4ba6-ba77-455b-af24-b4ac72dc5383)

## Round ID:
[235649](https://scrubby.melonmesa.com/round/235649)

## Testmerges:
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)

## Reproduction:
1. Join the pirate bitrunning sim
2. Blind the ghostrole pirates with your human-sized lasers

**Comment by Metekillot** [comment]
Not a bug; Hellfire lasers do a shitload of damage so them being stupid fucking big is deliberate

**Comment by Metekillot** [comment]
![image](https://github.com/user-attachments/assets/302cf320-31a0-41dd-9df1-79384c10d06d)

vs

![image](https://github.com/user-attachments/assets/8bff5359-15be-4d72-9085-5eff9148abea)

No wound penalty, higher damage, and almost 50% faster moving

**Comment by SmArtKar** [comment]
Not related to damage, this is 4 years old code which likely was broken until recently? Since I don't remember them being as big either, or possibly noone ever made a report

```
/obj/projectile/beam/laser/hellfire/Initialize(mapload)
	. = ..()
	transform *= 2
```
