### ISSUE TITLE
Reticence can break down reinforced walls with its RCD

### ISSUE THREAD

**Issue by xzero314** [tgstation/tgstation#86101]
### Issue Summary:

The reticence mech can just delete r walls with its rcd.  I am not sure if this was intentional, but this is rather ridiculous.

### Reproduction Steps:

Get a reticence.

 Delete r walls at rapid speed

 Laugh as the ai watches you delete your way into the SAT or the armory.

Win

**Comment by SmArtKar** [comment]
Intended behavior
