### ISSUE TITLE
Walking a mech into the supermatter as an AI with mech dominance will permakill you

### ISSUE THREAD

**Issue by trexter5555** [tgstation/tgstation#86107]
### Issue Summary:

be ai, dominate mech, walk it into the sm to troll the crew, oops you're permadead, not shunted back to core

### Round ID:

[235875](https://scrubby.melonmesa.com/round/235875)

### Reproduction Steps:

see above

**Comment by deathrobotpunch** [comment]
this is not a bug. shunting to a mech is unreversable and permadeaths you if you die

**Comment by deathrobotpunch** [comment]
![Uploading IMG_2302.jpeg…]()

**Comment by xzero314** [comment]
> this is not a bug. shunting to a mech is unreversable and permadeaths you if you die

Not correct. The ai has been sent back to its core after the mech dies/it leaves the mech for quite some time

**Comment by deathrobotpunch** [comment]
> Not correct. The ai has been sent back to its core after the mech dies/it leaves the mech for quite some time

the ability description on the malf guide literally says that if you die it’s permanent

**Comment by projectkepler-ru** [comment]
description for mech domination need cleanup then

**Comment by Metekillot** [comment]
> > Not correct. The ai has been sent back to its core after the mech dies/it leaves the mech for quite some time
> 
> the ability description on the malf guide literally says that if you die it’s permanent
> 

Yeah I rewrote mech shunting if you die in it. It's only meant to be permadeath if:

You bought an ability that disables APC shunting (currently only Borg factory)
AND
your inactive core is destroyed

**Comment by xzero314** [comment]
> > > Not correct. The ai has been sent back to its core after the mech dies/it leaves the mech for quite some time
> > 
> > the ability description on the malf guide literally says that if you die it’s permanent
> > 
> 
> Yeah I rewrote mech shunting if you die in it. It's only meant to be permadeath if:
> 
> You bought an ability that disables APC shunting (currently only Borg factory)
> AND
> your inactive core is destroyed 

This change you did actually really nerfed malf ais. This made using mech dominate cancel delta and its a huge pain

**Comment by Metekillot** [comment]
I dont recall touching the delta revoke? It was always supposed to cancel if you shunt out of your core

**Comment by xzero314** [comment]
> I dont recall touching the delta revoke? It was always supposed to cancel if you shunt out of your core 

It never used to cancel Delta when you went into mech domination. Ever since your change, it does. due to the fact that shunting into an APC does cancel Delta
