### ISSUE TITLE
Attempting to put the extracted sliver into a box while it's inside a container that's inside you just dusts you

### ISSUE THREAD

**Issue by projectkepler-ru** [tgstation/tgstation#86120]
### Client Version:

515.1643

### Issue Summary:

Attempting to put the extracted sliver into a box while it's inside a container that's inside you just dusts you
![image](https://github.com/user-attachments/assets/4d57f4d5-b1e1-4b7f-a845-1b0cce8135ea)
Replicated

### Round ID:

N/A

### Test Merge Information:

N/A

### Reproduction Steps:

Use the given super matter sliver extraction kit
extract it
attempt to put it inside your box while it's in a nested storage inside you
dies

**Comment by SmArtKar** [comment]
we really need a regression unit test for this it seems. Does it ***only*** happen if its inside a storage but works fine if you hold it?

**Comment by SmArtKar** [comment]
...unable to reproduce? Are you sure you're running an up to date build that includes my previous fix, in case its a localhost/downstream server? I will mark this as cleanup flagged unless there's more details/steps to it

**Comment by Sadboysuss** [comment]
You need to include the codebase you experienced the issue on in the round ID section next time
