### ISSUE TITLE
space ninja seems to have some modsuit issues (cloak, recall sword)

### ISSUE THREAD

**Issue by nianjiilical** [tgstation/tgstation#86123]
### Client Version:

515.1641

### Issue Summary:

became space ninja, toggling the cloak module failed to make me invisible

later in the round i lost my sword but pressing recall said it was already on my person and my backpack storage inventory stopped appearing, maybe it was in my pack but it broke somehow??

### Round ID:

[236042](https://scrubby.melonmesa.com/round/236042)

### Test Merge Information:

#85392

### Reproduction Steps:

1. spawn as ninja
2. fail to become invisible
3. realize you are the worst as ninjaing

**Comment by Sadboysuss** [comment]
live servers were running an earlier commit, should be fixed now
