### ISSUE TITLE
Ninja cloak is still completely brokenb

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#86289]
Reporting client version: 515.1643

## Round ID:
[236319](https://scrubby.melonmesa.com/round/236319)

## Testmerges:
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)

## Reproduction:
![image](https://github.com/user-attachments/assets/461f4038-6449-4fd6-9140-ad929a08d120)
This is with it turned on, something broke again looks like

**Comment by Sadboysuss** [comment]
Fixed in https://github.com/tgstation/tgstation/pull/85673

Live servers are running an older version of the game until the wallening revert is complete.

**Comment by Sadboysuss** [comment]
wallening revert is now on live servers, should work now
