### ISSUE TITLE
stechkarov

### ISSUE THREAD

**Issue by MelokGleb** [tgstation/tgstation#86287]
Reporting client version: 515.1642

## Issue Summary
virtual domain captain has makarov but mags for stechkin

## Round ID:
[236317](https://scrubby.melonmesa.com/round/236317)

## Testmerges:
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)

## Reproduction:
bitrunners launch syndicate assault
someone joins as captain
no ammo

**Comment by Sealed101** [comment]
can you please name your issues something more easily discernible in the future
