### ISSUE TITLE
Issues with reporter radio

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#86459]
### Client Version:

515.1643

### Issue Summary:

So #86046 introduced the reporter streaming thing which came with its own radio noise whenever someone talks through it, the problem is that the noise it makes is super grating, can be heard from miles away (at least when you're a ghost) and cannot be toggled off by disabling radio noises. I noticed there was a downstream fix here that said it might have something to do with the pref only working on deaf people?
https://github.com/NovaSector/NovaSector/commit/7f69c7859bed6dbd5a28f4978ead3376dd9123cb

### Round ID:

[236600](https://scrubby.melonmesa.com/round/236600)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)

### Reproduction Steps:

Turn off radio sounds
Hear someone make weird muffled talking that sounds the same no matter how close or far you are

**Comment by Sadboysuss** [comment]
https://github.com/tgstation/tgstation/pull/86132

Radio sounds were fixed recently but I'm not sure if it affects the camera

**Comment by DrDiasyl** [comment]
The muffled TV sounds are not connected with radio sounds or radio prefs in any way, mostly because it would be harder as it is a `playsound` and not `SEND_SOUND` so we must manually check every listener and their prefs.

I think it would be better as a separate preference setting.

**Comment by DrDiasyl** [comment]
Also no, this has nothing to do with deafness.

**Comment by Sadboysuss** [comment]
it's not a bug then, I'll let you respond if you think otherwise
