### ISSUE TITLE
Closets eat people (again!)

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#86456]
### Client Version:

515.1643

### Issue Summary:

Person remains trapped inside contents of an open closet when shoved into one

### Round ID:

[236590](https://scrubby.melonmesa.com/round/236590)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)

### Reproduction Steps:

Spawn a /obj/structure/closet
Open it
Shove someone into it
The door snaps open after closing, trapping the person inside the contents until the closet is next closed and opened.
Resisting does not provide escape, apparently.

**Comment by Sadboysuss** [comment]
As far as I know it only stops you from automatically opening the locker when moving while inside, you can still click on the locker while inside to open it
