### ISSUE TITLE
Radio sound blips cant be turned off (possibly just as the AI)

### ISSUE THREAD

**Issue by xzero314** [tgstation/tgstation#86450]
### Client Version:

515.1641

### Issue Summary:

As the ai. Even with the radio sounds off I still hear them. Checking settings shows them as off. turning them on and back off again does not fix the issue

### Round ID:

[236579](https://scrubby.melonmesa.com/round/236579)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)

### Reproduction Steps:

Join as the ai with radio sounds off. expect not to hear them. be constantly spammed by the sound anyway.

**Comment by Sadboysuss** [comment]
fix for this was just merged: https://github.com/tgstation/tgstation/pull/86132
tell us if you still encounter it after the server updates
