### ISSUE TITLE
Roundstart Big Bess mech's Cargo Compartment cannot be accessed

### ISSUE THREAD

**Issue by TheSmallBlue** [tgstation/tgstation#86493]
### Client Version:

515.1642

### Issue Summary:

On the round-start Big Bess mech, on every single station, if you load a crate into it with a hydraulic arm, you cannot access the cargo compartment to take it out.
This has been an issue for a while, but I can't find any mention of it.

### Round ID:

[236774](https://scrubby.melonmesa.com/round/236774)

### Test Merge Information:

#83227 
#85947 

### Reproduction Steps:

1. Get a crate, get the Big Bess.
2. Get on the Big Bess, use the hydraulic arm to load a crate into it
3. Access the mech control panel
4. Try to click on the Cargo compartment to eject the crate
5. Notice how it doesn't let you, forcing you to keep the hydraulic arm selected.

You can then eject the hydraulic arm to finally be able to access the cargo compartment

**Comment by TwistedCicrularConvexLens** [comment]
Oh hey! Timing on this is uncanny I noticed this too and just made a PR to fix it. Not been merged or reviewed yet so eh.

#86490

This broke 2 months ago with when Justice was introduced.

**Comment by TheSmallBlue** [comment]
> Oh hey! Timing on this is uncanny 

I mean, clearly we both came to the same conclusion of "How the hell has this not been fixed yet" and just took two differing ways as to how to approach it lol
