### ISSUE TITLE
Minor magic problems with monkeys.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#8650]
You can read through spellbooks and learn the powers, even though you can't understand writing.

These spells can then be used as always.

You aren't dextrous enough to use wands on others, but you CAN use wands on yourself, so wand of healing is a completely viable option for surviving the mage apocalypse, even after you're turned into a monkey. If you want to take a gamble you could even try polymorphing yourself back to a human or human-like creature.

**Comment by Incoming5643** [comment]
I dunno if I should fix this. Being able to risk polying out of monkey was something I kind of intended. As for the books, well I don't want to throw the "IT'S MAGIC" card buuuuuuut...

**Comment by WJohn** [comment]
You should at least be able to use the wands on other people, if you can use it on yourself.

**Comment by Incoming5643** [comment]
[impending monkey firing pin]
