### ISSUE TITLE
Lavaland mobs are nonhostile

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#86515]
### Client Version:

515.1637

### Issue Summary:

As of a day or so ago, lavaland enemies don't attack you, either passively or when you attack them. The only things that fight at this point are bile/vileworms and megafauna
[Screen-Recording-2024-09-06T15_27_48.174Z.webm](https://github.com/user-attachments/assets/ab1d9a06-c224-4f85-9afb-80423d5b6ab1)

### Round ID:

[236898](https://scrubby.melonmesa.com/round/236898)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [[TM] Assorted changes to job assignment code and logging. Runtime free, guaranteed or your money back. Price: $Â£0.](https://www.github.com/tgstation/tgstation/pull/85947)

### Reproduction Steps:

1. Be a miner
2. Get free shit because nothing cares that you're on lavaland

**Comment by Sadboysuss** [comment]
likely https://github.com/tgstation/tgstation/pull/86031

@ZephyrTFA @Ben10Omintrix ?

**Comment by Ben10Omintrix** [comment]
im checking this out now, seems to be related to #86020 . changes to can_see() proc keeps returning FALSE

**Comment by CCC23** [comment]
damn :( well atleast while your at it can you reduce the fucking speed of goliath tendral spam PLEASE

**Comment by Metekillot** [comment]
Also happening with slimes.
