### ISSUE TITLE
wizard deathmatch is noteleport so you cant use any teleport spells

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#86512]
### Client Version:

515.1630

### Issue Summary:

try to use blink in wizard deathmatch, cant

### Round ID:

[236889](https://scrubby.melonmesa.com/round/236889)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)

### Reproduction Steps:

try to use blink in wizard deathmatch, cant

**Comment by ZephyrTFA** [comment]
This will not be fixed as lazy loaded templates will remain noteleport.

**Comment by Sadboysuss** [comment]
> This will not be fixed as lazy loaded templates will remain noteleport.

we can fix this by removing the teleport loadout, it's false advertising

**Comment by ZephyrTFA** [comment]
This issue is about the death match area being non teleport flagged which will not be changed.
