### ISSUE TITLE
TGUI Certain Input Types Require Extra Clicks to Set Their Values

### ISSUE THREAD

**Issue by Garash2k** [tgstation/tgstation#86536]
### Client Version:

515.1637

### Issue Summary:

Left clicking any of the following inputs: `<Slider>`, `<Knob>` or `<DraggableControl>`, should select the number's value, allowing for easily typing in a new value. That's how they used to work some time ago (pre react?) Instead, they enter a weird half clicked mode. After a 2nd click, the value is editable, but it's still not selected.

Tested on the current master:

https://github.com/user-attachments/assets/63ba91f9-9e6e-4713-a3a2-909404d622d4

### Reproduction Steps:

1. Left click a Slider, a Knob or a DraggableControl
2. At that point, it should be possible to type in a new number and then press enter, but instead, the input is in a bizzare state.

**Comment by SyncIt21** [comment]
Its not a issue with number input but with sliders & knobs. The regular number input works fine

**Comment by Garash2k** [comment]
You're right, description adjusted.
