### ISSUE TITLE
Heat capacity maplint doesn't run

### ISSUE THREAD

**Issue by PowerfulBacon** [tgstation/tgstation#86551]
The heat capacity maplint at `tools/maplint/lints/heat_capacity.yaml` has an incorrect extension `yaml`, when it should be `yml`. The maplint script only runs lints that end with .yml meaning that it has never been run.

https://github.com/tgstation/tgstation/blob/e0ff5c9326be53286261d21bc6c442c6faf55460/tools/maplint/source/__main__.py#L63

**Comment by PowerfulBacon** [comment]
@ZephyrTFA See issue above

**Comment by ZephyrTFA** [comment]
You should fix bacon :)

**Comment by PowerfulBacon** [comment]
I would but I'm scared that it'll catch things 😆

**Comment by ZephyrTFA** [comment]
>:(
