### ISSUE TITLE
Lavaland mobs are STILL nonhostile

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#86562]
### Client Version:

515.1637

### Issue Summary:

#86517 was meant to fix an issue that made lavaland creatures nonhostile. However, they still are not hostile. It seems like they'll attack you if you are directly next to them right as they spawn (say, from a vent), but do nothing after that point

### Round ID:

[237242](https://scrubby.melonmesa.com/round/237242)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [[TM] Assorted changes to job assignment code and logging. Runtime free, guaranteed or your money back. Price: $Â£0.](https://www.github.com/tgstation/tgstation/pull/85947)

### Reproduction Steps:

1. Go to lavaland
2. Slap the wildlife

**Comment by MrMelbert** [comment]
Are you certain that the fix rolled out to the server yet

**Comment by OuroborusReporter** [comment]
Heck, you are correct, I saw a different PR in the changelog and thought that it was that one
