### ISSUE TITLE
Missing attributions for new sounds

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#86635]
### Issue Summary:

- VoidDeflect1.ogg
- VoidDeflect2.ogg
- VoidDeflect3.ogg
in `sound/magic`
from https://github.com/tgstation/tgstation/pull/85728

### Reproduction Steps:

look in the files

**Comment by Sadboysuss** [comment]
the filenames are also capitalized but that's a different issue

**Comment by Sealed101** [comment]
@EnterTheJake pls

**Comment by LemonInTheDark** [comment]
![image](https://github.com/user-attachments/assets/a5e29542-c3be-4f6a-8baf-ad62d05a2d1d)
