### ISSUE TITLE
Bitrunners have a backdoor into sec records

### ISSUE THREAD

**Issue by TwistedCicrularConvexLens** [tgstation/tgstation#86645]
### Client Version:

515.1642

### Issue Summary:

Ok, this is gonna be a complicated one. But I encountered this a while back, essentially on meta central bitrunning there's an unfortunate mix of items that allows you to set people to arrest, add notes or crimes. In terms of fixing this maybe replace the night vision sechuds with normal night vision goggles? Takes away the cleanup crew vibe a bit but alas, bugs need fixin'.

While creative and most certainly inline with Bitrunnings hacking theme. This is annoying to sec-offs who rely on sechuds to identify threats and likely not intended.

https://github.com/user-attachments/assets/ea96d38a-674e-4964-9b4a-3167a937a401

### Reproduction Steps:

Step 1: Go to Meta Central bitrunning domain.
Step 2: Aquire night vision secHuds
Step 3: Aquire Emag
Step 4: Emag Sechuds, removing the need for a sec-id to view and add to records, arrest status, whatever.
Step 5: Use security camera console also in Meta Central to pick unsuspecting victims in the real world and steal their social security id or whatever.

**Comment by Moonnest** [comment]
To be honest if they need emag to interact with those items in such fashion i don't see any issues at all. Also it's not that fast or simple to get to that point as well so.

**Comment by Bibarra** [comment]
> To be honest if they need emag to interact with those items in such fashion i don't see any issues at all. Also it's not that fast or simple to get to that point as well so.

There's an emag that spawns in the domain. You can accomplish this within 10 minutes of the round.
