### ISSUE TITLE
You can still tackle with left-click

### ISSUE THREAD

**Issue by DrDiasyl** [tgstation/tgstation#86668]
### Client Version:

515.1642

### Issue Summary:

#84909 has removed tackling with a left-click mouse button.

But when you're in the game you can still tackle with a left-click and its infuriating as you accidentally do that and break your neck or look stupid.

### Round ID:

[237939](https://scrubby.melonmesa.com/round/237939)

### Test Merge Information:

[#85947: 'Assorted changes to job assignment code and logging. Runtime free, guaranteed or your money back. Price: $Â£0.' by Timberpoes at commit bee2faf070](https://www.github.com/tgstation/tgstation/pull/85947)
[#83227: '[TM ONLY] Hijacked Revision Date for v3 TGS Api' by ZephyrTFA at commit bfecdb9b39](https://www.github.com/tgstation/tgstation/pull/83227)
[#84826: 'Adds new station map Nebulastation' by KikoWen0 at commit 193bd4f5b3](https://www.github.com/tgstation/tgstation/pull/84826)

### Reproduction Steps:

1. Put on any tackling gloves
2. Turn on THROW
3. Left-click any tile
4. You tackle that tile even though you used left-click instead of right-click

**Comment by DrDiasyl** [comment]
Found out, #86031 accidentally deleted it as there is nothing in changelog or PR body stating about deleting the right-click check.

**Comment by MrMelbert** [comment]
Scanning through and I see some instances of code which looks maybe not updated correctly
![image](https://github.com/user-attachments/assets/97e2630c-f2d9-4d65-8443-4b7ebc81c615)

**Comment by DrDiasyl** [comment]
That's a lot for "some"
