### ISSUE TITLE
Broadcast camera camera on/off does not work

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#86660]
### Client Version:

515.1643

### Issue Summary:

The broadcast camera claims in examine text that you can alt+click it to turn the microphone on or off.  This in fact doesn't work and falls through to the default alt+click on turf loot popup handler, which, if you're holding the camera at the time will emit the confusing error "You can't search for this item, it's already in your inventory! Take it off first."

### Round ID:

[237919](https://scrubby.melonmesa.com/round/237919)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [GetFlatIcon improvements.](https://www.github.com/tgstation/tgstation/pull/86077)

### Reproduction Steps:

Spawn camera
Alt click it.
Mandatory field good.

**Comment by DrDiasyl** [comment]
This is my bad.

I created the Broadcast Camera and wanted to give it a toggleable microphone, but at some point I dropped that feature but didn't remove the examine message
