### ISSUE TITLE
When i use the hemostat from the surgical omni-toolset to take out organs while playing as a medical cyborg it instantly closes the menu instead of doing anything.

### ISSUE THREAD

**Issue by Ninjatucker26** [tgstation/tgstation#86696]
### Client Version:

515.1643

### Issue Summary:

When i use the hemostat from the surgical omni-toolset to take out organs while playing as a medical cyborg it instantly closes the menu instead of doing anything.

### Round ID:

Unsure

### Reproduction Steps:

Try the organ manipulation surgery while being a medical cyborg.
Get to the point in the surgery where you take out organs and try to take out organs with hemostat.

**Comment by SyncIt21** [comment]
Duplicate #86676
