### ISSUE TITLE
Xenomorph can hold ID or pens in hand by removing them from a PDA.

### ISSUE THREAD

**Issue by Jewelry-x** [tgstation/tgstation#86703]
### Client Version:

515.1462

### Issue Summary:

Xenomorphs can alt click or ctrl click to remove the ID and pen from the PDA and forcing it in their hand, but if these items are on the floor the warning "Your claws aren't capable of such fine manipulation!" is shown.

### Reproduction Steps:

1. Drop a PDA with an ID and/or pen in it.
2. As a xenomorph, alt-click or ctrl-click the PDA and the item will be in your hands.
![image](https://github.com/user-attachments/assets/d4369d00-d0e1-424e-b7c4-bc1348d99601)

**Comment by Livrah** [comment]
feature
