### ISSUE TITLE
Snow bears are god moded, where previously ancient ones only were

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#86709]
### Client Version:

515.1643

### Issue Summary:

Spawn a basic/bear/snow.  Observe it has god mode trait.

Issue sourced here https://github.com/tgstation/tgstation/pull/86596/files#r1761801220 in PR #86596

### Round ID:

[238153](https://scrubby.melonmesa.com/round/238153)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [GetFlatIcon improvements.](https://www.github.com/tgstation/tgstation/pull/86077)

### Reproduction Steps:

See above

**Comment by MrMelbert** [comment]
Anyone tackling this should also go through and fix the few mobs which are now stunnable/knockdownable which shouldn't be able <https://github.com/tgstation/tgstation/pull/86596#discussion_r1761807199>
