### ISSUE TITLE
Digitigrade jumpsuit can be seen through EVA suits

### ISSUE THREAD

**Issue by Treachce** [tgstation/tgstation#86756]
### Client Version:

515.1643

### Issue Summary:

When playing as a lizard with digitigrade legs and wearing an EVA suit, parts of the jumpsuit can be seen when they should logically be concealed by the EVA suit. This might affect other suit items (like firesuits maybe) as it's probably an issue with sprite overlays but I haven't tested it with them.

![image](https://github.com/user-attachments/assets/0042421b-44aa-4850-9707-074d42fd3f31)
In this picture I am wearing a green jumpsuit and the knees/ankle parts can be seen sticking out.

### Round ID:

[23802](https://scrubby.melonmesa.com/round/23802)

### Test Merge Information:

probably n/a

### Reproduction Steps:

1. Be lizard with digitigrade legs
2. Put on jumpsuit with digitigrade sprite
3. Put on EVA suit
4. See the bulky legs of the digitigrade jumpsuit that should be concealed by the EVA suit

**Comment by MrMelbert** [comment]
In testing, this is very odd

The first time you equip something that squishes your legs, it will function correctly and hide the jumpsuit

However, unequipping that same item will permanently break your jumpsuit sprite, getting it stuck
