### ISSUE TITLE
Midround/Latejoin traitors cannot forge objectives

### ISSUE THREAD

**Issue by Y0SH1M4S73R** [tgstation/tgstation#86763]
### Client Version:

514.1642

### Issue Summary:

Midround/Latejoin traitors cannot forge objectives

### Round ID:

[238335](https://scrubby.melonmesa.com/round/238335)

### Test Merge Information:

#85947
#83227
#84826
#84869

### Reproduction Steps:

1. Roll midround traitor
2. Open your uplink
3. The "Primary Objectives" tab, which contains the button used to forge objectives, is absent

**Comment by AdipemDragon** [comment]
iirc, that was an intentional change, don't remember when but it's something about insentivising roundstart antagonism more?

**Comment by Sadboysuss** [comment]
it may be intentional still idk
