### ISSUE TITLE
Ghost polls seem to return "no taker" (null key?) as a valid result, with side effects and runtimes!

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#86760]
### Client Version:

515.1641

### Issue Summary:

Create a mob
Offer it to ghosts
Have no ghost take it
Get this weird error instead of "no-one took it"
```
ADMIN LOG: [*invalid*] has taken control of (*no key*/(DO NOT ACCEPT)([?]) ([FLW])
```
Probably associated runtime:
```
[2024-09-18 23:22:16.355] RUNTIME: runtime error: undefined variable list/var/key
 - proc name: offer control (/proc/offer_control)
 -   source file: code/modules/mob/mob_helpers.dm,383
 -   usr: Bob Stange (/mob/dead/observer)
 -   src: null
 -   usr.loc: the floor (165,49,1) (/turf/open/floor/iron)
 -   call stack:
 - offer control(DO NOT ACCEPT (/mob/living/carbon/human))
 - DO NOT ACCEPT (/mob/living/carbon/human): vv do topic(/list (/list))
 - DO NOT ACCEPT (/mob/living/carbon/human): vv do topic(/list (/list))
 - DO NOT ACCEPT (/mob/living/carbon/human): vv do topic(/list (/list))
 - DO NOT ACCEPT (/mob/living/carbon/human): vv do topic(/list (/list))
 - Iain0 (/client): view var Topic("_src_=vars;admin_token=2108081...", /list (/list), null)
 - Iain0 (/client): Topic("_src_=vars;admin_token=2108081...", /list (/list), null, null)
```

What makes this more interesting is
Spawn a cat/space
spawn a sentience slime potion
use potion on cat
Get no takers
Slime potion becomes unusable, var being_used = 1 and stuck this way. also associated runtime:

```
[2024-09-18 23:25:16.924] RUNTIME: runtime error: undefined variable list/var/key
 - proc name: on poll concluded (/obj/item/slimepotion/slime/sentience/proc/on_poll_concluded)
 -   source file: code/modules/research/xenobiology/xenobiology.dm,739
 -   usr: Bob Stange (/mob/living/carbon/human)
 -   src: the intelligence potion (/obj/item/slimepotion/slime/sentience)
 -   usr.loc: the floor (166,49,1) (/turf/open/floor/iron)
 -   src.loc: Bob Stange (/mob/living/carbon/human)
 -   call stack:
 - the intelligence potion (/obj/item/slimepotion/slime/sentience): on poll concluded(Bob Stange (/mob/living/carbon/human), PLEASE DO NOT TAKE (/mob/living/basic/pet/cat/space), /list (/list))
 - the intelligence potion (/obj/item/slimepotion/slime/sentience): attack(PLEASE DO NOT TAKE (/mob/living/basic/pet/cat/space), Bob Stange (/mob/living/carbon/human), "icon-x=16;icon-y=11;left=1;but...")
 - PLEASE DO NOT TAKE (/mob/living/basic/pet/cat/space): attackby(the intelligence potion (/obj/item/slimepotion/slime/sentience), Bob Stange (/mob/living/carbon/human), "icon-x=16;icon-y=11;left=1;but...")
 - the intelligence potion (/obj/item/slimepotion/slime/sentience): melee attack chain(Bob Stange (/mob/living/carbon/human), PLEASE DO NOT TAKE (/mob/living/basic/pet/cat/space), "icon-x=16;icon-y=11;left=1;but...")
 - Bob Stange (/mob/living/carbon/human): ClickOn(PLEASE DO NOT TAKE (/mob/living/basic/pet/cat/space), "icon-x=16;icon-y=11;left=1;but...")
 - PLEASE DO NOT TAKE (/mob/living/basic/pet/cat/space): Click(the floor (167,49,1) (/turf/open/floor/iron), "mapwindow.map", "icon-x=16;icon-y=11;left=1;but...")
```

I'ma guess some null gets returned by polling, that the callers then take to be a key, assume things worked and then die down the road trying to set that key up.

Possibly also explains a miner this round who noted their power miner instantly "went SSD", but (haven't exactly checked) it seems very inline with this kinda thing where no-applicants is treated as a valid result then fails to put any ckey in control because its a null ckey.

Of note if a "offer to ghosts" mob had a ckey in charge, that ckey is ejected as ghost even if "invalid key" wins, and the ckey controller becomes null.

Possibly has been fixed before but wallening and reverts might have broken something here?

### Round ID:

[238321](https://scrubby.melonmesa.com/round/238321)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [GetFlatIcon improvements.](https://www.github.com/tgstation/tgstation/pull/86077)

### Reproduction Steps:

HI SECOND BOX!

Like really which bit goes where, if the other box is just for summary can i just write "see below" and essay post here instead?  Also whats the title.  A summary of the summary?  Anyway, ignore this bit :)

**Comment by iprice** [comment]
Maybe here where length(newpoll signedup) will be 0 and amount to pick will be 1 and we return the empty list?

https://github.com/tgstation/tgstation/blob/941677e2a4e774dcbb67025168da0fd601a9563e/code/controllers/subsystem/polling.dm#L178

**Comment by iprice** [comment]
Gonna assume this fun piece is related too (lone op rolled, i guess no takers)

ADMIN LOG: An attempt to spawn lone operative returned , this is a bug.

**Comment by Sealed101** [comment]
we love `list = (0)` returns
