### ISSUE TITLE
Mining modsuit is broken - again.

### ISSUE THREAD

**Issue by Kiromaka** [tgstation/tgstation#86772]
### Client Version:

515.1640

### Issue Summary:

After-attack refractor previously broke the mining modsuit making it unable to recharge, which later was fixed. Seems like wallening revert brought it back.

### Round ID:

[238396](https://scrubby.melonmesa.com/round/238396)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [GetFlatIcon improvements.](https://www.github.com/tgstation/tgstation/pull/86077)

### Reproduction Steps:

1.Buy mining modsuit
2.Lower its charge
3.Try to recharge with plasma
4.Nothing heappens

**Comment by the-orange-cow** [comment]
Possibly fixed by https://github.com/tgstation/tgstation/pull/86754
