### ISSUE TITLE
Announcement have a 10 nonillion character limit

### ISSUE THREAD

**Issue by Chowder-McArthor** [tgstation/tgstation#86784]
### Client Version:

515.1637

### Issue Summary:

![Screenshot 2024-09-19 182733](https://github.com/user-attachments/assets/40f171a9-bd11-4393-aaaa-bbf1f82f4fb4)

https://github.com/user-attachments/assets/d98b624d-aaf5-4bdd-8ed0-493ce859ac34

### Round ID:

[238410](https://scrubby.melonmesa.com/round/238410)

### Test Merge Information:

- [Assorted changes to job assignment code and logging. Runtime free, guaranteed or your money back. Price: $Â£0.](https://www.github.com/tgstation/tgstation/pull/85947)
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [Spacemove refactor - Newtonian physics](https://www.github.com/tgstation/tgstation/pull/84869)
- [Adds a warning and single retry to byond membership lookup](https://www.github.com/tgstation/tgstation/pull/86765)

### Reproduction Steps:

I honestly have no idea what caused this. I looked at the bridge console and this was like this. It's not a fake character limit, it did seem to work.

**Comment by excalisword** [comment]
I think I noticed the succumb option letting you put that many as well.

**Comment by Y0SH1M4S73R** [comment]
I think this has something to do with `tgui_input_text` having a default character limit of the macro `INFINITY`, which isn't actually the 32-bit floating-point infinity.

**Comment by LemonInTheDark** [comment]
@MrStonedOne this is why you don't just wrecking ball sanity checks I am KILLING YOU WITH A ROCK

**Comment by MrStonedOne** [comment]
>when the stoned one gets stoned
![image](https://github.com/user-attachments/assets/abb4280f-5270-46e3-9395-0752caba7877)
