### ISSUE TITLE
Admin drop pods really should not create sparks

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#86799]
### Client Version:

515.1643

### Issue Summary:

Spawn a mineral/plasma/thirty in a drop pod bay
Deliver it using default settings
Yay fire

Also of course happens if there's even a hint of plasma in the air where you drop the pod.

This probably shouldn't be a thing because
1) Admin intervention by pod isn't intended to set a place on fire and make the recipients life worse
2) Burning rooms down because there's trace plasma in the air thats not even visible sucks.
3) Rather not have to turn on gas scan and read the tile every time i want to do this.

Normal drop pods, sure, whatever, but admin spawned ones shouldn't do this IMO.

(I think you can work around this by using "pod stays" for some reason)

### Round ID:

[238489](https://scrubby.melonmesa.com/round/238489)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [GetFlatIcon improvements.](https://www.github.com/tgstation/tgstation/pull/86077)

### Reproduction Steps:

I'm eating pizza right now.

**Comment by memecraft22** [comment]
Yeah this happened to me one round there was plasma in the air and I ask an admin via prayer to send mats they sent it via drop pod and then the plasma caught on fire the admin put it out thankfully and when they sent something again they instead just spawned it in
