### ISSUE TITLE
Mining MODsuits cannot be charged using plasma. The Plasma core needs to be charged directly (by pulling it out)

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#86810]
### Client Version:

515.1640

### Issue Summary:

Rather than the intended method for charging the MODsuit, which is using plasma/plasma ore on the control core, the mining MODsuit must be charged by wrenching out the core from the suit and applying plasma to that.

### Round ID:

[238344](https://scrubby.melonmesa.com/round/238344) 

### Reproduction Steps:

1. Get a mining MODsuit
2. Drain the power slightly.
3. Attempt to use a sheet of plasma on the suit.
4. Fail.

1-1. Deactivate suit.
2-1. Wrench the control core to remove the core
3-1. Use some plasma on the core.
4-1. Hey presto, core was recharged. Slap that shit back into the control core.

**Comment by MrMelbert** [comment]
#86754 ?

**Comment by necromanceranne** [comment]
I think you're right, it could be that manuels just not been updated for a few days
