### ISSUE TITLE
ethereal crystalization doesnt trigger properly on death 

### ISSUE THREAD

**Issue by wonderinghost** [tgstation/tgstation#86823]
### Client Version:

515.1642

### Issue Summary:

ethereal crystalization doesnt trigger even though they died. suffered a hairline fracture to the chest and died from a esword. normally would remain in body as you are crystalizing but for some reason didnt. no spilt organs, no quirks, late join ethereal 

### Round ID:

[238569](https://scrubby.melonmesa.com/round/238569)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [GetFlatIcon improvements.](https://www.github.com/tgstation/tgstation/pull/86077)
- [ai controllers that fail to make a plan no longer process until theyre able to plan again](https://www.github.com/tgstation/tgstation/pull/86600)

### Reproduction Steps:

late join as a ethereal
die
move, if you move out of your body then something is wrong

**Comment by Vineettiwari02** [comment]
❤️

**Comment by Vineettiwari02** [comment]
❤️

**Comment by Time-Green** [comment]
I really can't reproduce this. You sure you didn't have significant heart damage? Sharp weaponry can damage internal organs

**Comment by wonderinghost** [comment]
If that is the reason then can a e sword do enough damage to it?

**Comment by Time-Green** [comment]
> If that is the reason then can a e sword do enough damage to it?

I’ll have to test it, I’ll try it tonight (remind me if I forget)

**Comment by wonderinghost** [comment]
> > If that is the reason then can a e sword do enough damage to it?
> 
> I’ll have to test it, I’ll try it tonight (remind me if I forget)

**Comment by Sadboysuss** [comment]
@Time-Green

**Comment by Time-Green** [comment]
Uh yeah I can't reproduce this. If this happens again, could you healthscan your corpse? I want to rule out the most likely cause, which is something killing your heart

**Comment by wonderinghost** [comment]
Yeah I came across something similar. Sharp objects definitely prevented crystalization as it damaged the organ 

Forgot to close this
