### ISSUE TITLE
Debug chemical synthesizer makes ice that instantly melts back into water

### ISSUE THREAD

**Issue by zoomachina** [tgstation/tgstation#86858]
### Client Version:

Irrelevant

### Issue Summary:

If you try to get some ice using the debug chemical synthesizer machine, it instantly melts back into water.

### Round ID:

Irrelevant

### Test Merge Information:

N/A

### Reproduction Steps:

1. Spawn a debug chemical synthesizer (chem_synthesizer)
2. Try to add 1u ice into an empty beaker
3. See it instantly melt into 0.92u water

**Comment by ExcessiveUseOfCobblestone** [comment]
debug part aside, anything that makes ice should be cooling the cup down right?
