### ISSUE TITLE
officers assigned to a department cannot buy stuff from vendors

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#86887]
### Client Version:

515.1630

### Issue Summary:

When you try to buy stuff from vendor it says "Departmental accounts have been blacklisted from personal expenses due to embezzlement"

### Round ID:

[238945](https://scrubby.melonmesa.com/round/238945)

### Reproduction Steps:

Try to buy stuff in vendor as officer assigned to any department, cant

**Comment by 00-Steven** [comment]
agh, taking a look

**Comment by 00-Steven** [comment]
think I get why
this gets the job by comparing trim assignment to all possible jobs:
https://github.com/tgstation/tgstation/blob/8c3c9a6ea29bf32385c148c5294e3f6a18f57bf3/code/datums/id_trim/_id_trim.dm#L32-L36
this works for stock security officers:
https://github.com/tgstation/tgstation/blob/8c3c9a6ea29bf32385c148c5294e3f6a18f57bf3/code/modules/jobs/job_types/security_officer.dm#L1-L2
https://github.com/tgstation/tgstation/blob/8c3c9a6ea29bf32385c148c5294e3f6a18f57bf3/code/datums/id_trim/jobs.dm#L1040-L1041
however, the departmental security officers have different assignment names:
https://github.com/tgstation/tgstation/blob/8c3c9a6ea29bf32385c148c5294e3f6a18f57bf3/code/datums/id_trim/jobs.dm#L1103-L1104

...really iunno why it's trying to do it this way, when the `/datum/id_trim/job` subtype we probably actually care about already has a job var
