### ISSUE TITLE
Multiple people can be assigned to a singular head of staff role at round start

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#86899]
### Client Version:

515.1643

### Issue Summary:

Have seen this a couple of times now, not sure what the root cause is, mostly seems to affect Captain and CE, but opening an issue and if nothing else can track round numbers here, so for openers round 238957

![image](https://github.com/user-attachments/assets/8c3184f9-c242-47fc-ba17-b8e391deea4b)

### Round ID:

[238957](https://scrubby.melonmesa.com/round/238957)

### Reproduction Steps:

A

**Comment by Kiromaka** [comment]
It can affect any roll, does it matter tho, its funny)

**Comment by Sealed101** [comment]
wonder if there's any relation to #62337

> It can affect any role, does it matter tho, its funny)

we're killing fun here, sir
