### ISSUE TITLE
Ninja invisibility is unstoppable.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#8691]
Their weapons are invisible, you can't force them out of it, you don't even get a hint as to where they might be.

I suggest we make anything they hold visible, and having them be stunned should disable their invisibility so that they're not completely unbeatable.

**Comment by PKPenguin321** [comment]
It being strong is kind of the point, but I agree with making them lose invisibility when stunned

**Comment by Marflowerose** [comment]
Alternatively they could just have the genetic cloak of darkness and chameleon and/or hunter camo. Seeing as Ninja is not a roundtype in itself, Ninja doesn't need the "Single antag versus entire crew" superpowers like with wizard.

**Comment by Lumipharon** [comment]
Ninja is supposed to be OP.

It's rare as shit and (usually) can't murderbone anymore, as per policy changes.

If you make their weapons visible then you might as well not bother.
And you can still find them with mouse over, or just use AOE attacks (setting them on fire afaik lets you see where they are nicely), and emp's are AOE and drain their power - invisibility burns power fast.

**Comment by Anonus** [comment]
They used to have a shimmery visible outline and you could see items they were holding, except someone went "this is snowflakey, it needs to go!" and made them completely invisible and unfindable.

**Comment by Shadowlight213** [comment]
They also used to be visible if you had thermals. Not anymore sadly.
Also, EMPS dont do anything to ninjas currently

**Comment by Anonus** [comment]
EMPS never did anything to the ninja, they even used to have an AoE EMP ability.

**Comment by Iamgoofball** [comment]
Try medhuds

**Comment by Anonus** [comment]
It doesn't work, they're an overlay on the mob. The only thing that works is, uh, nothing at all.

**Comment by Iamgoofball** [comment]
Rip, we fixed medhuds showing invisible ninjas?

**Comment by Anonus** [comment]
Alpha=0 means all the things that let you notice the ninja don't work. You can't see progress bars, stuff they're holding, huds of any king, or them at all.
