### ISSUE TITLE
Security vendors are a bit messed up

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#86926]
### Client Version:

515.1643

### Issue Summary:

![image](https://github.com/user-attachments/assets/5a7c0d28-1003-4bd4-8c6c-34a2e08caa9b)
Keep getting this message when trying to purchase anything, taking credits out into my hand works though

### Round ID:

[239070](https://scrubby.melonmesa.com/round/239070)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [Adds a warning and single retry to byond membership lookup](https://www.github.com/tgstation/tgstation/pull/86765)
- [Adds the NT BR-38 Battle Rifle. A sci-fi hybrid gun (that can critically fail on existence). Throws combat shotguns (the big ones from cargo) into the bin. Other changes. (SPRITES WIP)](https://www.github.com/tgstation/tgstation/pull/86853)

### Reproduction Steps:

Try to buy anything from the sectech or drobe as a secoff

**Comment by Sealed101** [comment]
Duplicate of #86887
