### ISSUE TITLE
Traitor Panels of antagonists are broken

### ISSUE THREAD

**Issue by xzero314** [tgstation/tgstation#86921]
### Client Version:

515.1641

### Issue Summary:

The Traitor Panel of anybody who is an antagonist is broken. Most options are redded out and unusable. You can add MORE antags but removing antag status and some other features is broke. Everything is fine for players that are NOT antagonists but as soon as any antag is given the panel breaks.

### Round ID:

[239052](https://scrubby.melonmesa.com/round/239052)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [Adds a warning and single retry to byond membership lookup](https://www.github.com/tgstation/tgstation/pull/86765)
- [Adds the NT BR-38 Battle Rifle. A sci-fi hybrid gun (that can critically fail on existence). Throws combat shotguns (the big ones from cargo) into the bin. Other changes. (SPRITES WIP)](https://www.github.com/tgstation/tgstation/pull/86853)

### Reproduction Steps:

Give yourself an antag. Traitor Panel breaks. Also applies to players assigned antag at round start

**Comment by 00-Steven** [comment]
hrmn
![image](https://github.com/user-attachments/assets/5f73f4f9-a48d-4109-8f0f-2d546d8fb1db)
I can reproduce the red text bit, but the buttons still seem usable? may be a span issue

**Comment by 00-Steven** [comment]
oh- remove is, I see.

**Comment by 00-Steven** [comment]
https://github.com/tgstation/tgstation/blob/a8af27fa0af69cd6859c8e03faf8b7c20932a1a3/code/__DEFINES/span.dm#L18

**Comment by 00-Steven** [comment]
seems there's a bit more to this, but that's the starting bit
