### ISSUE TITLE
Modsuit tether doesn't work, gets you stuck

### ISSUE THREAD

**Issue by Qoldoon** [tgstation/tgstation#86933]
### Client Version:

515.1640

### Issue Summary:

When using the modsuit tether, instead of getting pulled to a tile, the tether gets stuck and doesnt pull me, getting me stuck in place completely.

Got rescued by a miners fulton recovery system.
Could use the tether multiple times, creating as many lines as i wished, making me even more stuck.
Taking the suit off didn't remove the tethers

### Round ID:

[239124](https://scrubby.melonmesa.com/round/239124)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [Adds a warning and single retry to byond membership lookup](https://www.github.com/tgstation/tgstation/pull/86765)
- [Adds the NT BR-38 Battle Rifle. A sci-fi hybrid gun (that can critically fail on existence). Throws combat shotguns (the big ones from cargo) into the bin. Other changes. (SPRITES WIP)](https://www.github.com/tgstation/tgstation/pull/86853)

### Reproduction Steps:

1. Go to space with engineering modsuit
2. Use tether module on any wall or similar tile
3. Stuck

**Comment by SmArtKar** [comment]
Tether behavior has been changed with spacemove changes, they now prevent you from drifting off into space. Ctrl click the tether to cut it after a short delay.
