### ISSUE TITLE
Carp DNA spacewalk does not work

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#86930]
### Issue Summary:

DNA infuse with space carps should give you spacewalk, now you just float with no grav

### Round ID:

[239113](https://scrubby.melonmesa.com/round/239113)

### Reproduction Steps:

Infuse self with 4 carps in genetics
Go to space

**Comment by SmArtKar** [comment]
surprisingly not a spacemove issue - trait itself works just fine

**Comment by SmArtKar** [comment]
unable to reproduce?

**Comment by Livrah** [comment]
It might be Cybernetic Revolution station trait, DNA infuser does not replace mechanic organs and does not give a message.
