### ISSUE TITLE
ethereals cant charge from apc 

### ISSUE THREAD

**Issue by wonderinghost** [tgstation/tgstation#86942]
### Client Version:

515.1642

### Issue Summary:

ethereals cant charge from apc after putting on haul gauntlets 

### Round ID:

[239178](https://scrubby.melonmesa.com/round/239178)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [Adds a warning and single retry to byond membership lookup](https://www.github.com/tgstation/tgstation/pull/86765)
- [Adds the NT BR-38 Battle Rifle. A sci-fi hybrid gun (that can critically fail on existence). Throws combat shotguns (the big ones from cargo) into the bin. Other changes. (SPRITES WIP)](https://www.github.com/tgstation/tgstation/pull/86853)

### Reproduction Steps:

join as a ethereal
pickup and wear haul gloves
try to charge from apc

**Comment by wonderinghost** [comment]
ethereal charging and food should probably be checked on as eating and discharging is draconic

**Comment by Sadboysuss** [comment]
closing in favor of https://github.com/tgstation/tgstation/issues/86985 on the basis of more information
