### ISSUE TITLE
Fishing-related items either DECREASE fishing skill or have misleading tool tips

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#86965]
### Client Version:

515.1637

### Issue Summary:

#86646 added several modifiers to different items, to make fishing easier or harder. However, as seen in the attached, these seem to indicate that items which should make it easier as per the PR actually make it harder. There are two possibilities:

1. They actually make it harder, and a value somewhere got set to negative instead of positive
2. They correctly make it easier, and the tooltip is just wrong
![Screenshot 2024-09-29 140014](https://github.com/user-attachments/assets/2c92a37e-66d6-41e6-9f86-53a9f86e51c4)
![Screenshot 2024-09-29 140024](https://github.com/user-attachments/assets/e23c5d3a-4505-43e5-8217-95442b87237b)
![Screenshot 2024-09-29 140032](https://github.com/user-attachments/assets/b4546a87-3371-466d-94a2-745159338a61)

### Round ID:

[239331](https://scrubby.melonmesa.com/round/239331)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [Adds a warning and single retry to byond membership lookup](https://www.github.com/tgstation/tgstation/pull/86765)
- [Adds the NT BR-38 Battle Rifle. A sci-fi hybrid gun (that can critically fail on existence). Throws combat shotguns (the big ones from cargo) into the bin. Other changes. (SPRITES WIP)](https://www.github.com/tgstation/tgstation/pull/86853)

### Reproduction Steps:

1. Try to be a master baitsman
2. Grab your handy dandy fishing toolbox
3. Weep as the fish run in fear from it

**Comment by 00-Steven** [comment]
thiiiink the tooltip's flipped

**Comment by Ghommie** [comment]
The tooltip's flipped whoops
