### ISSUE TITLE
Map vote always fails

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#86963]
### Client Version:

515.1642

### Issue Summary:

Map vote always fails, presumably due to the associated test merge.

### Round ID:

[239323](https://scrubby.melonmesa.com/round/239323)

### Test Merge Information:

- [Adds the NT BR-38 Battle Rifle. A sci-fi hybrid gun (that can critically fail on existence). Throws combat shotguns (the big ones from cargo) into the bin. Other changes. (SPRITES WIP)](https://www.github.com/tgstation/tgstation/pull/86853)
- [Persistent Map Vote Tallies](https://www.github.com/tgstation/tgstation/pull/86788)

### Reproduction Steps:

Start a map vote
Vote for a map
Result is "None" 
No map is selected for the next round
24/7 Meta as god intended

**Comment by ElGitificador** [comment]
should change name to map vote always lands properly

**Comment by SyncIt21** [comment]
The test merges are not open. Please close if it's no longer a issue

**Comment by Sadboysuss** [comment]
the pr has been merged and the issue seems to be solved
