### ISSUE TITLE
Void Path cold detection doesn't work properly in space

### ISSUE THREAD

**Issue by KazooBard** [tgstation/tgstation#86962]
### Issue Summary:

If you create new tiles in space, a 3x3 rune area and on those freshly placed tiles with no atmos create a rune and attempt to craft anything that requires low temperature you will be told that "The temperature is not cold enough!"

I think this is not planned as space naturally is extremely cold and the space heretic cannot craft items in space like it did before. 

### Round ID:

[239322](https://scrubby.melonmesa.com/round/239322)

### Reproduction Steps:

1. Go into space, use iron rods and floor tiles to create a 3x3 platform
2. Draw a transmutation rune as the void path heretic and attempt to complete "Glimmer of Winter"
3. You will be told that it is not cold enough, despite requiring sub zero (celsius) temperatures, in space.

**Comment by the-orange-cow** [comment]
For what it's worth, I was able to make the void blade on the wawastation solars.  Half of the tiles were naturally part of the solars and half were ones that I placed.  Not sure if that matters.

**Comment by Sadboysuss** [comment]
https://github.com/user-attachments/assets/6b8970ca-fb63-41b9-a5b1-55c9a191ae28

unable to reproduce, please provide new reproduction steps or a video of the issue
