### ISSUE TITLE
Syndicate AI cards usually (??) deposits a new-ass mob/living/ai on the tile they're at when polling ends

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#86976]
### Client Version:

n/a

### Issue Summary:

![image](https://github.com/user-attachments/assets/c2f6dc2f-c8b2-4381-89e5-b2e885ef57f4)
I dont fucking know honestly

### Round ID:

I dont remember sorry it was a nukie manuel round. But i verified this on local

### Reproduction Steps:

1. call on poolling finished with appropiate arguments, or just use syndicard normally
2. nwe ai magically deposited

**Comment by OuroborusReporter** [comment]
Can confirm I was there too at the end - The card deposited a total of 3-4 AIs on their ship, which didn't seem to have souls
