### ISSUE TITLE
Drones can delete their own gas analyser via camreas

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#86989]
### Client Version:

515.1643

### Issue Summary:

Since the drone gas analyser is integrated you can't drop it, however if you just use it to upgrade a camera its gone forever
This might affect engi borgs too I haven't tested that yet

### Round ID:

[239454](https://scrubby.melonmesa.com/round/239454)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [Adds a warning and single retry to byond membership lookup](https://www.github.com/tgstation/tgstation/pull/86765)
- [Adds the NT BR-38 Battle Rifle. A sci-fi hybrid gun (that can critically fail on existence). Throws combat shotguns (the big ones from cargo) into the bin. Other changes. (SPRITES WIP)](https://www.github.com/tgstation/tgstation/pull/86853)

### Reproduction Steps:

Screw open camera as a drone
Apply gas analyser

**Comment by mcbalaam** [comment]
The easiest fix it seems is to make a new gas analyser subtype for drones to cancel out the upgrading

**Comment by Sadboysuss** [comment]
https://github.com/user-attachments/assets/632b870c-90a0-49b5-b6b5-4485e01de7e3
