### ISSUE TITLE
Some items are missing from Autolathe/Protolathe Construction

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#86992]
### Client Version:

515.1641

### Issue Summary:

Certain items are missing from the construction lists of protolathes/autolathes.

Items in particular that I have noticed;
- Camera Assemblies (Produced at an autolathe)
- Circuit Tiles (Red, Green, Blue)

### Round ID:

[239466](https://scrubby.melonmesa.com/round/239466)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [Adds a warning and single retry to byond membership lookup](https://www.github.com/tgstation/tgstation/pull/86765)
- [Adds the NT BR-38 Battle Rifle. A sci-fi hybrid gun (that can critically fail on existence). Throws combat shotguns (the big ones from cargo) into the bin. Other changes. (SPRITES WIP)](https://www.github.com/tgstation/tgstation/pull/86853)

### Reproduction Steps:

1. Go to an autolathe/protolathe
2. Search up the item
3. Item not found

**Comment by SyncIt21** [comment]
Not a bug, this is an feature request

**Comment by Derpguy3** [comment]
> Not a bug, this is a feature request because there are multiple ways you could make these items available in game and not just through lathes for e.g. through crafting, cargo etc.
> 
> Which method is suitable is purely subjective

The items must have been recently removed from the lathes without my knowing and turned into craft-able items, they were previously available and made from the lathes.

At the round of the issue report I had been playing as a cyborg, which has no way of accessing the crafting menu.
