### ISSUE TITLE
Wand of healing removes your cyberimplants

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#87007]
### Issue Summary:

I dont think a magic wand of healing shoudl remove your positive cybernetics

This happens cause it resets organs

### Reproduction Steps:

1. install cybers
2. wand of healing
3. no cybers :/(

**Comment by necromanceranne** [comment]
Is it only the primary organs, like hearts and livers, or is it also extra organs like toolset arm implants?

**Comment by carlarctg** [comment]
> Is it only the primary organs, like hearts and livers, or is it also extra organs like toolset arm implants?

all
