### ISSUE TITLE
Wizard re-memorize deletes artificier spell.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#8703]
Since points that you spend on items aren't supposed to be replenished, but you lose ALL your spells anyway, this makes the soulstone belt near worthless as you can only get shades out of it at that point instead of a self-sustaining army.

It probably shouldn't delete these spells in particular, or MAYBE it should just delete all of these physical items alongside it and replenish the point.

**Comment by Incoming5643** [comment]
Another good reason I/Someone needs to datum base the spellbook

**Comment by optimumtact** [comment]
------------
09:44 < Firecage> oranges: I believe this issue was fixed. You can't even 
                  refund said spell anymore, so you keep the soulstones and the 
                  artificer spell after summoning the soulstone belt.
09:44 < Firecage> https://github.com/tgstation/tgstation/issues/8703
