### ISSUE TITLE
Remember how borgs used to be able to screwdriver air alarms n shit to put them on walls?

### ISSUE THREAD

**Issue by NexusLeader** [tgstation/tgstation#87098]
### Client Version:

515.1639

### Issue Summary:

When i attempt to screwdriver theair alarm or APC, facing a wall while pulling, it just doesn't work.
Probably a result of the omnitool update, it also broke multitools with oresilo but that was fixed.

### Round ID:

[239951](https://scrubby.melonmesa.com/round/239951)

### Test Merge Information:

- [[TESTMERGE READY] The Torment Nexus: The future of Security brigging and prisoner rehabilitation!](https://www.github.com/tgstation/tgstation/pull/86106)
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [Adds a warning and single retry to byond membership lookup](https://www.github.com/tgstation/tgstation/pull/86765)
- [Adds the NT BR-38 Battle Rifle. A sci-fi hybrid gun (that can critically fail on existence). Throws combat shotguns (the big ones from cargo) into the bin. Other changes. (SPRITES WIP)](https://www.github.com/tgstation/tgstation/pull/86853)
- [Fixes multiple players being picked for the same single-slot command job roundstart.](https://www.github.com/tgstation/tgstation/pull/87005)
- Not sure these aresupposed to be here or not, but they aren't the problem causers

### Reproduction Steps:

1. Attempt to pull the frame with screwdriver omnitool, make sure you facinga wall
2. Attempt toscrewdriver the frame.
3. Doesn't work...

**Comment by SyncIt21** [comment]
What exactly were you trying to do? Neither borgs nor humans can screwdriver air/fire alarm nor APC frames until they have added electronics & wires after which the screwdriver just closes/opens their panels(tested locally & it works)

> Attempt to pull the frame

Did you mean detach the frame from the wall? If so you need to use a wrench(for borgs omni wrench) not screwdriver cause neither borgs nor humans can use a screwdriver for this task

**Comment by Sadboysuss** [comment]
https://github.com/user-attachments/assets/aff56b56-d524-4e75-98a0-8e5783930d16


https://github.com/user-attachments/assets/6dd00280-82af-46a7-8933-d659ae98fe52

**Comment by NexusLeader** [comment]
oh. it just has to be under you. Idiot gaming!

**Comment by NexusLeader** [comment]
never fucking mind i didn't watch the whole video when i said that

**Comment by moocowswag** [comment]
I'm scared apc cover repair is also broken for borgs too (if a cover is broken off of an apc you can screwdriver another apc frame onto the same tile to replace the cover)
