### ISSUE TITLE
Offstation roles can grief with boulder teleporters

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#87118]
### Issue Summary:

Offstation roles have access to build boulder teleporters, through means such as the golem order vendor. Boulder teleporters can be used (especially when upgraded) to steal the station's boulders. Enough of these can effectively prevent the station from gaining mats from vents they tap, in an untraceable way.

### Reproduction Steps:

Be golem
Buy 4 boulder beacons from mining vendor
Set up several conveyors linked to their own ore silo
Laugh as the station has no iron

**Comment by SyncIt21** [comment]
Duplicate #82934

**Comment by Sealed101** [comment]
^
