### ISSUE TITLE
The Emergency tether module has no way to remove teathers, and they persist without a suit.

### ISSUE THREAD

**Issue by restedwaves** [tgstation/tgstation#87117]
### Client Version:

515.1643

### Issue Summary:

![Screenshot 2024-10-08 202149](https://github.com/user-attachments/assets/0c6a8f8c-e1cd-49b2-9587-69038cd55aad)
![
![Screenshot 2024-10-08 202034](https://github.com/user-attachments/assets/4b20645c-ee83-418b-8a47-fc36601843ad)
Screenshot 2024-10-08 202632](https://github.com/user-attachments/assets/52ef3d36-2b40-4137-8dbc-93a9b62c331b)
It also has very scuffed interactions with zero G flinging you all over the place
update: the only way I have found to remove them is picking them up
![image](https://github.com/user-attachments/assets/791b6de0-8164-4454-8870-80378531e865)

### Round ID:

[239997](https://scrubby.melonmesa.com/round/239997)

### Test Merge Information:

- [[TESTMERGE READY] The Torment Nexus: The future of Security brigging and prisoner rehabilitation!](https://www.github.com/tgstation/tgstation/pull/86106)
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [Adds a warning and single retry to byond membership lookup](https://www.github.com/tgstation/tgstation/pull/86765)
- [Adds the NT BR-38 Battle Rifle. A sci-fi hybrid gun (that can critically fail on existence). Throws combat shotguns (the big ones from cargo) into the bin. Other changes. (SPRITES WIP)](https://www.github.com/tgstation/tgstation/pull/86853)
- [Fixes multiple players being picked for the same single-slot command job roundstart.](https://www.github.com/tgstation/tgstation/pull/87005)

### Reproduction Steps:

Use the emergency tether module
make your emergency about 40% worse

**Comment by SmArtKar** [comment]
Ctrl click cuts the tether, this is displayed when you examine the anchor

**Comment by restedwaves** [comment]
> Ctrl click cuts the tether, this is displayed when you examine the anchor. Persisting without a suit is intended.

![image](https://github.com/user-attachments/assets/9f25a67d-2840-4fe3-aa64-ed953185434b)
No it isnt.
