### ISSUE TITLE
Slicing silver extract food makes it edible again

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#87123]
### Client Version:

515.1637

### Issue Summary:

Food generated by silver slime extracts is disgusting to non-slime carbons, to avoid it being an easy replacement for the chef and because fun is bad. If it makes a large, slicable item like a cake, slicing it makes pieces that are edible again
![Screenshot 2024-10-08 220053](https://github.com/user-attachments/assets/40746b66-fd50-448a-8d76-9c2a960b66cd)
![Screenshot 2024-10-08 215442](https://github.com/user-attachments/assets/8938e2b6-c358-42c6-bdd2-3231e2da84a3)

### Round ID:

[240001](https://scrubby.melonmesa.com/round/240001)

### Test Merge Information:

- [[TESTMERGE READY] The Torment Nexus: The future of Security brigging and prisoner rehabilitation!](https://www.github.com/tgstation/tgstation/pull/86106)
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [Adds a warning and single retry to byond membership lookup](https://www.github.com/tgstation/tgstation/pull/86765)
- [Adds the NT BR-38 Battle Rifle. A sci-fi hybrid gun (that can critically fail on existence). Throws combat shotguns (the big ones from cargo) into the bin. Other changes. (SPRITES WIP)](https://www.github.com/tgstation/tgstation/pull/86853)
- [Fixes multiple players being picked for the same single-slot command job roundstart.](https://www.github.com/tgstation/tgstation/pull/87005)

### Reproduction Steps:

1. Get a silver extract
2. Generate food until you get a cake
3. Slice it
4. Eat as much as you want. There's no law against silver food anymore. I have 37 cakes at home

**Comment by OuroborusReporter** [comment]
(two screenshots because my only sliceable left had been sitting on the floor long enough to get dirty - I wanted to show that yes, it DOES show as disgusting while still fresh, as with the e-cake slice, which generated as a slice and not a whole cake)

**Comment by deathrobotpunch** [comment]
maybe we should just remove inedible silver slime food

**Comment by SmArtKar** [comment]
> maybe we should just make inedible silver slime food edible again, I feel a decreased food quality would suit silver slime food much better.

They already are low quality, that's what's making them toxic
