### ISSUE TITLE
Items in slots wont drop after unequipping clothing

### ISSUE THREAD

**Issue by K4rlox** [tgstation/tgstation#87129]
### Client Version:

515.1643

### Issue Summary:

Roundstart, and for the rest of the round, after i unequipped a jumpsuit, i didnt drop items on my id and belt along with pockets

### Round ID:

[240028](https://scrubby.melonmesa.com/round/240028)

### Reproduction Steps:

1. spawn
2. take off jumpsuit
3. items equipped dont drop

**Comment by MrMelbert** [comment]
Caused by #87073

**Comment by K4rlox** [comment]
> Caused by #87073

wha- how?

**Comment by MrMelbert** [comment]
> wha- how?

TL;DR they added a check to core un/equip code which bypasses stuff
