### ISSUE TITLE
you cant turn off entertainment mumbling

### ISSUE THREAD

**Issue by MelokGleb** [tgstation/tgstation#87136]
### Issue Summary:

if someone talks on entertainment  channel you hear mumbling and theres no button to turn that off

### Round ID:

[240042](https://scrubby.melonmesa.com/round/240042)

### Reproduction Steps:

1. someone talks on entertainment 
2. you hear mumbling
3. you want to turn it off
4. you cant

**Comment by Sadboysuss** [comment]
Maybe some kind of mute button on the monitor would be wise
