### ISSUE TITLE
Typo in gills description from fish DNA infusion

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#87173]
### Client Version:

515.1637

### Issue Summary:

The new fish (not carp) DNA infusion gives you gills. Apparently you heve gills
![Screenshot 2024-10-11 143712](https://github.com/user-attachments/assets/4cd03f84-2001-4add-96aa-6dee33c11386)

### Round ID:

[240145](https://scrubby.melonmesa.com/round/240145)

### Test Merge Information:

- [[TESTMERGE READY] The Torment Nexus: The future of Security brigging and prisoner rehabilitation!](https://www.github.com/tgstation/tgstation/pull/86106)
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [Adds a warning and single retry to byond membership lookup](https://www.github.com/tgstation/tgstation/pull/86765)

### Reproduction Steps:

1. Return to fishe
2. Heve gills

**Comment by Rhials** [comment]
Strange. The typo isn't the result of an explicit misinput, but seems to be the pronoun macros not working properly.

![image](https://github.com/user-attachments/assets/1971f56a-039c-4f25-9d7e-8b5a075a7968)

This is evident with the "multiple lives" component as well.

![image](https://github.com/user-attachments/assets/68388a19-0bbd-4f36-b11f-26dc52d9dfa4)

**Comment by SmArtKar** [comment]
> Strange. The typo isn't the result of an explicit misinput, but seems to be the pronoun macros not working properly.
> 
> ![image](https://private-user-images.githubusercontent.com/28870487/375886613-1971f56a-039c-4f25-9d7e-8b5a075a7968.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MzM3OTIsIm5iZiI6MTcyODczMzQ5MiwicGF0aCI6Ii8yODg3MDQ4Ny8zNzU4ODY2MTMtMTk3MWY1NmEtMDM5Yy00ZjI1LTlkN2UtOGI1YTA3NWE3OTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDExNDQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNTgwNzE2NzhhNTRhMzJkNGM2NTYyZWIzZWJmOGJlNzBlOTc5NzlkODRiNzgyNDY4ZTUwNDYyZTdhYzhjYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8Sah66uNL8UpKkDgGWIRDnxFexAYIW8Adb2vVN9wmYY)
> 
> This is evident with the "multiple lives" component as well.
> 
> ![image](https://private-user-images.githubusercontent.com/28870487/375888257-68388a19-0bbd-4f36-b11f-26dc52d9dfa4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MzM3OTIsIm5iZiI6MTcyODczMzQ5MiwicGF0aCI6Ii8yODg3MDQ4Ny8zNzU4ODgyNTctNjgzODhhMTktMGJiZC00ZjM2LWIxMWYtMjZkYzUyZDlkZmE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDExNDQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMDBkNTJmMWQ3NDE1ZWM5OWNkMDE0Y2MxNTZkYzMzMzM3OGU1NzNkNjY4M2ZhNGMyMDliZDVlNzljMWMxMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LBcnYfG3i79qmCWRX3zgCL5vKxIbafv__JcYAxr2P0g)

in your case macros are working as intended, they're just being used where they shouldn't be. ``He's, She's, They've`` are proper returns from them. Using it in an element, on the other hand, produces funky results.
