### ISSUE TITLE
MODsuit's Tether doesn't sanitize COMSIG_CLICK user

### ISSUE THREAD

**Issue by larentoun** [tgstation/tgstation#87192]
### Issue Summary:

It seems that `/datum/component/tether` doesn't check if user is capable of acting, or even if it's living - ghosts can CTRL-CLICK and remove tethers at the very least.

### Reproduction Steps:

1. Get eng MODSuit
2. Fire a tether
3. Ghost, de-admin
4. CTRL-CLICK the tether
5. Tether gets removed by a ghost

**Comment by Sadboysuss** [comment]
cc @SmArtKar
