### ISSUE TITLE
Odd hair bug

### ISSUE THREAD

**Issue by Chocobro** [tgstation/tgstation#8719]
i don't know how to describe it better than that. top left is the alt-click tab to show a tile. hair is white in that, doesn't occur on other humans though.
could be a client-side only bug, or a problem with the colour.
picture for posterity.
![hairbug](https://cloud.githubusercontent.com/assets/5677255/6983365/cfb60c7a-da14-11e4-9539-2d1c09e2ae90.png)

**Comment by PKPenguin321** [comment]
i think this happens with examining too and it's been around for a while

**Comment by RemieRichards** [comment]
Requires a new feature from byond (```icon(appearance)```) to be fixed nicely, should be coming soonTM, closing for now.

**Comment by Militaires** [comment]
this isnt just hair.

any greyscale icons that use hues are grey/white on default on examine or object tab

**Comment by Thunder12345** [comment]
See above

**Comment by RemieRichards** [comment]
doesn't change anything.

**Comment by Chocobro** [comment]
haha fuck this was when kylie had short hair
also rippers this issue is two years old
