### ISSUE TITLE
issue maybe with cryopods

### ISSUE THREAD

**Issue by Syilumi** [tgstation/tgstation#87205]
### Client Version:

515.1642

### Issue Summary:

you can no longer close cryopods on yourself and have them automatically turn on, now they just refuse to close

### Reproduction Steps:

attempt to fix your wounds via cryopod because you play solo
be unable to
die alone

**Comment by Syilumi** [comment]
the reason i made this is because i cannot find any merge or anything saying that it was intentional if it was please correct me

**Comment by SyncIt21** [comment]
> you can no longer close cryopods on yourself

This was a intentional change see https://github.com/tgstation/tgstation/pull/80873#issuecomment-1896315295

**Comment by Syilumi** [comment]
ah damn.. i needa get into multiplayer ss13

**Comment by Vect0r2** [comment]
> > you can no longer close cryopods on yourself
> 
> This was a intentional change see [#80873 (comment)](https://github.com/tgstation/tgstation/pull/80873#issuecomment-1896315295)
> 
> More justification provided here [#77919 (comment)](https://github.com/tgstation/tgstation/pull/77919#issuecomment-1692706211)

Is Pickle-coding a maintainer?

**Comment by Syilumi** [comment]
no idea.. sorry
