### ISSUE TITLE
Using tethers on the gravity generator deletes it from existence

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#87203]
### Issue Summary:

Using the tether item on the gravity gen blocks will result in it being deleted. This probably also works on other anchored tiles but I haven't tested it extensively.

### Round ID:

[240231](https://scrubby.melonmesa.com/round/240231)

### Reproduction Steps:

1. Go to gravgen
2. Tether it
3. It goes away

**Comment by deathrobotpunch** [comment]
this doesn’t need reproducing because I saw it happen lol
