### ISSUE TITLE
Bronze (brass) chairs lost their special spin gimmick + you show up on top of the armrests when buckled

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#87222]
### Issue Summary:

This no longer works.
![obraz](https://github.com/user-attachments/assets/a4972d83-398b-4f1c-91f4-b54f74d73718)
This looks bad.
![obraz](https://github.com/user-attachments/assets/f971cc04-ddf7-4312-9ffd-6817c6e6fa01)

### Reproduction Steps:

1. Bronze = copper splashed on iron
2. Make bronze (brass) chair.
3. Alt click.
4. Weep.

**Comment by Sealed101** [comment]
unplayable
