### ISSUE TITLE
Service borg can't pick up rolling tables or their beakers

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#87233]
### Client Version:

515.1643

### Issue Summary:

The rolling table that you can deploy doesnt' seem to be able to be picked up after being put down, and neither do beakers from the secondary apparatus

### Round ID:

[240329](https://scrubby.melonmesa.com/round/240329)

### Test Merge Information:

- [[TESTMERGE READY] The Torment Nexus: The future of Security brigging and prisoner rehabilitation!](https://www.github.com/tgstation/tgstation/pull/86106)
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [Adds a warning and single retry to byond membership lookup](https://www.github.com/tgstation/tgstation/pull/86765)
- [Recovered Crew | Medical Cargo Respawns ](https://www.github.com/tgstation/tgstation/pull/87072)

### Reproduction Steps:

Go service borg
Put down rolling table or your beaker
you can't pick them back up

**Comment by SyncIt21** [comment]
Duplicate #85596

**Comment by Sealed101** [comment]
^
