### ISSUE TITLE
 When rotating new manufacturing machines, the indicator lights do not rotate with them

### ISSUE THREAD

**Issue by MX0739** [tgstation/tgstation#87255]
### Client Version:

515.1644

### Issue Summary:

When you rotate the machines, the colored indicator light does not rotate with them (blue input light always faces north, orange output light always faces south), when the actual inputs and outputs do. Because of this, you won’t be able to figure out where the actual input and output are just by looking (these machines don't have directional sprites), you’ll have to try to insert the components on each side until you succeed. I don't think it was intended that way

### Reproduction Steps:

1. Build one of new manufactoring machines (crafter for example)
2. Unscrew it and try to rotate it
3. See that there is no difference between different directions
4. Try to guess where the actual output/input is

**Comment by mc-oofert** [comment]
fixed by #87244

**Comment by Sadboysuss** [comment]
fix was merged, if you still experience the issue - comment here and we'll reopen it
