### ISSUE TITLE
Converted cultists lose commune verb after being cloned

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#8726]
You can still hear the other cultists, you just can't say anything back.

**Comment by francinum** [comment]
Use a tome
Seriously, does everyone forget these have a communicate option.

**Comment by palpatine213** [comment]
@francium It's still a bug. 
I know that the tome can function this way, but why have the verb in the first place if you should just use a tome? Also, you would have to HAVE a tome to use it. you can't just magically create one by yourself anytime you please.

**Comment by MrStonedOne** [comment]
This is caused by the mob being in something when spawned (the cloning tube).

reconnecting should fix it, but it's still a bug, a byond bug.

**Comment by tedward1337** [comment]
Is this fixed?

**Comment by ChangelingRain** [comment]
yes
