### ISSUE TITLE
Lionhunter Rifle, if used to point blank someone in deathmatch, can send you to the rupee room/you shouldn't be here room.

### ISSUE THREAD

**Issue by excalisword** [tgstation/tgstation#87265]
### Client Version:

515.1641

### Issue Summary:

The Lionhunter Rifle's new change has resulted in some inadvertent effects in the Ragnarok deathmatch map. In particular, when you point blank someone with the rifle, it results in you being sent to the admin error/ rupee room. From here, you can, as the heretic scribe loadout, head to station to proceed to grace them with your presence/kill them all.

### Round ID:

[240399](https://scrubby.melonmesa.com/round/240399)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [Recovered Crew | Medical Cargo Respawns ](https://www.github.com/tgstation/tgstation/pull/87072)

### Reproduction Steps:

1. Get someone with you to do a deathmatch on the heretic scribe map.
2. You or them or both of you go heretic scribe.
3. Point blank shoot a monkey with the lionhunter rifle.
4. Get sent to the rupee room/fuckup room.
5. Proceed to head to station with or without your buddy via the ladder and give good loot, kill people, or get revenge on the one who killed you.

**Comment by mc-oofert** [comment]
adding magic antags to deathmatch wasn't a good idea the first time nor this time apparently

**Comment by excalisword** [comment]
> adding magic antags to deathmatch wasn't a good idea the first time nor this time apparently

Honestly, I think the real problem is adding magical antagonists with teleport moves.
