### ISSUE TITLE
Odd pitch shifting on vocal emotes

### ISSUE THREAD

**Issue by sylvia-from-fulp-station** [tgstation/tgstation#87274]
### Issue Summary:

This has existed since i started playing as far as i can tell. i was told to make this an issue report.

When you use the *laugh emote or others like it the pitch is randomly adjusted to add some variance to the sound, noticeably the sound can come across as quite unnerving at a lower pitch; it could be reined in or players could be given a voice pitch slider.

### Reproduction Steps:

use the *laugh emote

**Comment by carlarctg** [comment]
fnaf freddy laugh

**Comment by Sadboysuss** [comment]
this isn't actually fixed, the issue was just mitigated in that pr
