### ISSUE TITLE
Killing the NODE drone results in the ore vent successfully being tapped

### ISSUE THREAD

**Issue by NoHaxJustPi** [tgstation/tgstation#87284]
### Issue Summary:

Attempting to tap an ore vent (apply mining scanner twice) and then shooting the NODE drone to death results in the vent successfully being tapped.

### Reproduction Steps:

1. Get your mining scanner and weapon of choice
2. Find an ore vent, apply scanner twice to start it
3. Attack the NODE drone with your weapon
4. Watch as it somehow causes the vent to be tapped

**Comment by OuroborusReporter** [comment]
Can confirm, it normally works as advertised. Second attempt at testing this got weird though - It said attempt failed, I didn't get mining points, and the bucket sprite didn't spawn on it, but the wire moving up and down DID spawn and it was pulling up boulders
![Screenshot 2024-10-18 114450](https://github.com/user-attachments/assets/ca110311-5aec-4ebe-a869-93cfa99d2913)
