### ISSUE TITLE
lums and the dark blue extract inconsistency

### ISSUE THREAD

**Issue by Syilumi** [tgstation/tgstation#87292]
### Client Version:

515.1642

### Issue Summary:

using the dark blue extract as a luminescent,
wiki: Infuses the user with frost oil and Cryoxadone
in game it infuses the user with regenerative jelly and frost oil

![Screenshot 2024-10-18 153510](https://github.com/user-attachments/assets/34b58edd-544f-4585-89ab-e08848e0d66c)

### Reproduction Steps:

be a luminescent
consume dark blue extract
click the minor activation button

**Comment by Sealed101** [comment]
wiki was not updated way back when https://github.com/tgstation/tgstation/pull/66157 rolled out, fixed it [now](https://tgstation13.org/wiki/index.php?title=Guide_to_xenobiology&oldid=58022)

**Comment by Syilumi** [comment]
ah nice
