### ISSUE TITLE
Infinite MOD Emergency Tether Module Tethers

### ISSUE THREAD

**Issue by Roastglue** [tgstation/tgstation#87307]
### Client Version:

515.1639

### Issue Summary:

When I use the MOD Emergency Tether Module, I can spam it seemingly infinitely and create infinite tethers. This also locks me in place forever.

<img width="942" alt="tethers" src="https://github.com/user-attachments/assets/ccde6b5b-0453-4cf7-aad2-b3f8b4d3ed62">

It seems like tethers disappeared after the places I was moored to were destroyed:

<img width="941" alt="tethers 2" src="https://github.com/user-attachments/assets/7f2b79c8-4411-4e28-9f59-92b681a85f35">

Joe Madwell was nice enough to try and save me, but I wasn't freed even when my suit was removed:

<img width="941" alt="tethers 3" src="https://github.com/user-attachments/assets/285ee88b-f687-48c3-ae8f-6fea3c4e77b0">

Even after dying, I was still stuck:

<img width="939" alt="tethers 4" src="https://github.com/user-attachments/assets/c8cef9b1-5da5-4ff1-9b2e-0b130af86243">

### Round ID:

240458

### Test Merge Information:

The following pull requests are currently test merged:
[#87191: 'Optivorbis lossless compression for the sound folder' by Sadboysuss at commit ed4744e53c](https://www.github.com/tgstation/tgstation/pull/87191)

### Reproduction Steps:

This took place on Delta Station. It was also in space.

1. Use the tether module on objects and floors
2. Get stuck on things
3. Stay stuck on things
4. Profit

**Comment by SmArtKar** [comment]
Not a bug. You can remove tethers either by ctrl clicking them (explained in the examine text) or using your tether MOD's ability from the MODsuit GUI.

**Comment by Roastglue** [comment]
> Not a bug. You can remove tethers either by ctrl clicking them (explained in the examine text) or using your tether MOD's ability from the MODsuit GUI.

Are you supposed to stay stuck even after you die? I can rename the issue for that if you want.

**Comment by SmArtKar** [comment]
> > Not a bug. You can remove tethers either by ctrl clicking them (explained in the examine text) or using your tether MOD's ability from the MODsuit GUI.
> 
> Are you supposed to stay stuck even after you die and the suit is removed? I can edit and rename the issue to focus on that if you want.
> 
> Also, I tried using the MODSuit GUI to disable it. I remember trying control clicking too, but admittedly I probably didn't select the cables specifically.

anyone can ctrl click the cables adjacent to them, that would quickly cut the tethers.

**Comment by Roastglue** [comment]
> > > Not a bug. You can remove tethers either by ctrl clicking them (explained in the examine text) or using your tether MOD's ability from the MODsuit GUI.
> > 
> > 
> > Are you supposed to stay stuck even after you die and the suit is removed? I can edit and rename the issue to focus on that if you want.
> > Also, I tried using the MODSuit GUI to disable it. I remember trying control clicking too, but admittedly I probably didn't select the cables specifically.
> 
> anyone can ctrl click the cables adjacent to them, that would quickly cut the tethers.

To clarify, it sounds like the cables staying after someone dies and the suit is removed IS a bug, while the cables being infinite isn't?
