### ISSUE TITLE
silver food randomly had nanites in it?

### ISSUE THREAD

**Issue by trexter5555** [tgstation/tgstation#87301]
### Issue Summary:

silver food that isnt roburger have nanite?

### Round ID:

[240451](https://scrubby.melonmesa.com/round/240451)

### Reproduction Steps:

i made some pizza from silver slimes, cut it since that makes it not gross anymore, and somehow it gave the ce and the cmo the nanite disease and they turned into borgs. i dont know how or why

**Comment by Sealed101** [comment]
what kind of pizza

**Comment by JackEnoff** [comment]
>i made some pizza from silver slimes, cut it since that makes it not gross anymore, and somehow it gave the ce and the cmo the nanite disease and they turned into borgs. i dont know how or why

```
/obj/item/food/pizza/margherita/robo
	food_reagents = list(
		/datum/reagent/cyborg_mutation_nanomachines = 70,
		/datum/reagent/consumable/nutriment = 25,
		/datum/reagent/consumable/nutriment/protein = 8,
		/datum/reagent/consumable/tomatojuice = 6,
		/datum/reagent/consumable/nutriment/vitamin = 5,
	)
```

**Comment by Sealed101** [comment]
classic
