### ISSUE TITLE
metastation cargo issues

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#87312]
### Client Version:

515.1641

### Issue Summary:

![image](https://github.com/user-attachments/assets/fe2f4709-a983-4bd1-926b-be7d04b70daf)

any sec off can go into the cargo send off office, the tile is missing

### Round ID:

[240468](https://scrubby.melonmesa.com/round/240468)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [Recovered Crew | Medical Cargo Respawns ](https://www.github.com/tgstation/tgstation/pull/87072)
- [Optivorbis lossless compression for the sound folder](https://www.github.com/tgstation/tgstation/pull/87191)

### Reproduction Steps:

load up metastation

**Comment by JackEnoff** [comment]
https://github.com/tgstation/tgstation/pull/87259
