### ISSUE TITLE
You still drop items in your hand when consuming 100% pure Ephedrine

### ISSUE THREAD

**Issue by o-d-a-z** [tgstation/tgstation#87337]
### Client Version:

515.1644

### Issue Summary:

I made 100% pure Ephedrine and was sipping on it and constantly dropping what I was holding in my hand.

"causes up to 20% chance to drop held items, based on purity following: 20% * (1 - purity). Pure ephedrine has 0% chance to drop held items"

### Round ID:

[240497](https://scrubby.melonmesa.com/round/240497)

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [Recovered Crew | Medical Cargo Respawns ](https://www.github.com/tgstation/tgstation/pull/87072)
- [Optivorbis lossless compression for the sound folder](https://www.github.com/tgstation/tgstation/pull/87191)

### Reproduction Steps:

Make (Or spawn in) 100% pure Ephedrine
Drink a few sips
It seems either at random or when you try to use a handheld object on things you drop it getting the message
"Your hands spaz out and you drop what you were holding!"

This happens even when you use spawn reagent container to spawn in 100% pure Ephedrine

**Comment by Helg2** [comment]
It was nerfed to be this way. https://github.com/tgstation/tgstation/pull/78158

**Comment by Sadboysuss** [comment]
wiki problem :(

**Comment by Sealed101** [comment]
something something wiki is free to edit
https://tgstation13.org/wiki/index.php?title=Chemistry/Medicines&oldid=58027
