### ISSUE TITLE
male sigh sound is too quiet

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#87335]
### Client Version:

515.1641

### Issue Summary:

I could barely hear it, maybe female is too quiet too

### Round ID:

[240497](https://scrubby.melonmesa.com/round/240497)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [Recovered Crew | Medical Cargo Respawns ](https://www.github.com/tgstation/tgstation/pull/87072)
- [Optivorbis lossless compression for the sound folder](https://www.github.com/tgstation/tgstation/pull/87191)

### Reproduction Steps:

use *sigh emote

**Comment by SmArtKar** [comment]
female *sigh is fine, issue is that male is much more toned down and doesn't have an inhale part, only an exhale

**Comment by Sadboysuss** [comment]
Might just voice it myself
