### ISSUE TITLE
Blade Heretic still has no post-ascend blades & no cooldown on blade shield ability

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#87344]
### Client Version:

n/a

### Issue Summary:

1. Blade Heretic STILL does not gain blades after ascending.
2. Malestrom of Silver or whatever has no cooldown - it can be cast continously after expending all blades.

Also for the latter if you get hit while the silver blades are appearing, the rest of them don't appear, I dunno if thats intended or not

Placing together because they are related to the recent blade rework PR.

### Round ID:

[24053](https://scrubby.melonmesa.com/round/24053)

### Test Merge Information:

n/a

### Reproduction Steps:

1. get maelstrom of silver
2. notice it has no cd
3. get ascension
4. notice no blades spawn

**Comment by carlarctg** [comment]
![image](https://github.com/user-attachments/assets/0549927f-e81f-42f9-a8bb-374e8b262a41)
![image](https://github.com/user-attachments/assets/e1649e76-02b5-4355-843c-70728ddc08e3)

**Comment by EnterTheJake** [comment]
The furious steel issue seems to be tied to server lag, i couldn't replicate it on live servers.

Blade not appearing during ascension is my fuckup; I'll try to cook something in the near future.
