### ISSUE TITLE
One of the dock rolls has a broken name

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#87342]
### Client Version:

515.1644

### Issue Summary:

![image](https://github.com/user-attachments/assets/c1f95085-ccd4-4133-b667-32320954f6be)

### Round ID:

[240502](https://scrubby.melonmesa.com/round/240502)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [Recovered Crew | Medical Cargo Respawns ](https://www.github.com/tgstation/tgstation/pull/87072)
- [Optivorbis lossless compression for the sound folder](https://www.github.com/tgstation/tgstation/pull/87191)

### Reproduction Steps:

Not sure how this was achieved but the desc should point to which donk roll in particular caused this

**Comment by Rhials** [comment]
One of the issue reports has a broken name
