### ISSUE TITLE
Big manipulators create copious amounts of clientless humans that appear in the orbit menu

### ISSUE THREAD

**Issue by Y0SH1M4S73R** [tgstation/tgstation#87360]
### Client Version:

515.1642

### Issue Summary:

Big manipulators create a human with a mind every time they attempt to use an item on an atom.
If the attempted interaction runtimes at any point, the code that deletes this human never runs.
This leaves a clientless human **that shows up in the orbit menu** every time a big manipulator runtimes while trying to use an item on an atom.
And if the big manipulator gets caught in a devastating explosion...
# OH LORD THE GIBS

### Round ID:

[240529](https://scrubby.melonmesa.com/round/240529)

### Test Merge Information:

#83227
#84826
#87072
#87191
#87357

### Reproduction Steps:

1. Make a big manipulator.
2. Have it use an item on something in such a way that the interaction runtimes.
3. Check the orbit menu.

**Comment by LemonInTheDark** [comment]
why the fuck was this code merged

**Comment by 00-Steven** [comment]
i wanna see how this goes

**Comment by necromanceranne** [comment]
big manipulator

**Comment by zxaber** [comment]
Why is it creating and then deleting humans. If it needs a mob for the item use procs, why does it not just keep a generic mob on hand?

**Comment by Blacklist897** [comment]
MY ARMS ARE FULL OF LITTLE MEN

**Comment by mcbalaam** [comment]
![image](https://github.com/user-attachments/assets/958a6d1d-7b36-4f5a-9f4b-15477e4b6de0)

**Comment by SyncIt21** [comment]
> Have it use an item on something in such a way that the interaction runtimes.

Could you give us an example where the interaction runtimes?

**Comment by DrAmazing343** [comment]
So you're telling me The Machine is run with living flesh that will spatter gore along the halls when it is inevitably smashed open?

That's some Edgar Allen Poe shit, dude, put this one in the running for the Fuckups Of The Year 2024 compilation.

**Comment by Sealed101** [comment]
sir yes sir

**Comment by dendyd00m** [comment]
> scorn reference

corn

**Comment by TheVekter** [comment]
Definitely a contender, if a late one.

**Comment by MrMelbert** [comment]
I feel like the manipulator itself can just be a dexterous basic mob, basically just a drone with less sentience
