### ISSUE TITLE
Potted plants don't have icons and make players invisible

### ISSUE THREAD

**Issue by General-Gaston** [tgstation/tgstation#87366]
### Client Version:

515.1643

### Issue Summary:

All potted plants are invisible and when you pick them up, it makes the user completely invisible

### Round ID:

[240540](https://scrubby.melonmesa.com/round/240540)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [Recovered Crew | Medical Cargo Respawns ](https://www.github.com/tgstation/tgstation/pull/87072)
- [Optivorbis lossless compression for the sound folder](https://www.github.com/tgstation/tgstation/pull/87191)
- [Revert "Master-overlayed screen alerts (i.e aura healing) now use appearance cloning instead of directly overlaying the master"](https://www.github.com/tgstation/tgstation/pull/87357)

### Reproduction Steps:

Pick up plant (if you can find one using the tile examine)
Become completely invisible
![Screenshot 2024-10-22 013516](https://github.com/user-attachments/assets/32b4b287-26fb-4fba-8c4e-b63288d99327)
![Screenshot 2024-10-22 013603](https://github.com/user-attachments/assets/dd4e0dd1-8ad5-41d9-8689-2f4b5cdab2f7)

**Comment by Katomou** [comment]
the evil fucked up plant that makes you invisible

**Comment by carlarctg** [comment]
never seen this bug on live, close it

**Comment by Profakos** [comment]
Could not replicate on latest. Was this one specific potted plant or all of them?

**Comment by General-Gaston** [comment]
@carlarctg it was reported and seen live on manny via an ahelp, it wasn’t just a false report 

@Profakos it was all potted plants, least what I saw during the round on Tram. The worse part is that you would look completely invisible to players while you were in game but if you ghosted, or are a ghost orbiting the person holding a plant, they would look normal

**Comment by Profakos** [comment]
Often multiZ causes issues like this, like when dead borgs became invisible in the bottom floor of icebox. I will try this out on Tram then.

**Comment by Sealed101** [comment]
that or admemery. sure would love public logs right about now

**Comment by General-Gaston** [comment]
@Sealed101 As the only admin that was on during this, i can safely say there was no admemey done on this he potted plants

**Comment by Profakos** [comment]
Can confirm after local testing, potted plants are completely invisible on Tramstation, but not on Metastation.

**Comment by Sealed101** [comment]
??????????

**Comment by General-Gaston** [comment]
An admin posting a bug report??? Unheard of!!!!
