### ISSUE TITLE
The new github issue template doesn't allow preview of pictures in the body

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#87387]
### Issue Summary:

![image](https://github.com/user-attachments/assets/1fe0556f-5101-4c34-b54d-832f9aac890c)

### Reproduction Steps:

try reporting an issue

**Comment by Sealed101** [comment]
? are you not getting the usual write/preview?
![изображение](https://github.com/user-attachments/assets/d09d6327-49cd-474e-acf3-87791f55c208)

**Comment by Sadboysuss** [comment]
seems like manually making an issue report works fine but pressing report issue ingame doesn't allow it?

**Comment by Sealed101** [comment]
works on my machine ™️ 
![изображение](https://github.com/user-attachments/assets/1e032c2a-8dc6-4ecb-b9f7-5dc133309f92)

**Comment by Sadboysuss** [comment]
weird
