### ISSUE TITLE
Toy aliens can get "shredded"

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#87386]
### Client Version:

515.1642

### Issue Summary:

![image](https://github.com/user-attachments/assets/8ca0a144-889f-415b-bfda-00ae0e0d64de)

### Round ID:

[240553](https://scrubby.melonmesa.com/round/240553)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [Recovered Crew | Medical Cargo Respawns ](https://www.github.com/tgstation/tgstation/pull/87072)
- [Optivorbis lossless compression for the sound folder](https://www.github.com/tgstation/tgstation/pull/87191)
- [Revert "Master-overlayed screen alerts (i.e aura healing) now use appearance cloning instead of directly overlaying the master"](https://www.github.com/tgstation/tgstation/pull/87357)

### Reproduction Steps:

shoot a toy alien? reduce its integrity?

**Comment by Sealed101** [comment]
it's a mask item so clothing damage still applies

**Comment by Sadboysuss** [comment]
Is why I didn't label it myself, idk if it's fine ir nah

**Comment by Sealed101** [comment]
i mean ideally it wouldn't use generic clothing damage text
