### ISSUE TITLE
emoting while asleep with a surgery mask will "make a strong noise"

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#87385]
### Client Version:

515.1642

### Issue Summary:

See reproduction steps

### Round ID:

[240553](https://scrubby.melonmesa.com/round/240553)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [Recovered Crew | Medical Cargo Respawns ](https://www.github.com/tgstation/tgstation/pull/87072)
- [Optivorbis lossless compression for the sound folder](https://www.github.com/tgstation/tgstation/pull/87191)
- [Revert "Master-overlayed screen alerts (i.e aura healing) now use appearance cloning instead of directly overlaying the master"](https://www.github.com/tgstation/tgstation/pull/87357)

### Reproduction Steps:

1. put anesthetic tank on back 
2. put on surgery mask
3. lie down on surgery bed
4. activate internals and fall asleep
5. *snore in chat box (maybe other emotes too?)
6. "x makes a strong noise"

**Comment by MrMelbert** [comment]
What's the bug here, surgical masks are supposed to muffle your emotes

**Comment by Sadboysuss** [comment]
> What's the bug here, surgical masks are supposed to muffle your emotes

Well you can't emote *scream while asleep (I think?) , but if there is a mask you make a noise, maybe I should make that a separate issue idk. Other than that I thought you can't emote *snore while sedated (I thought it's only for willing sleep), but maybe I'm wrong
