### ISSUE TITLE
Drones can use pirate speak if they put on a pirate hat

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#87405]
### Client Version:

515.1642

### Issue Summary:

title

### Round ID:

[240575](https://scrubby.melonmesa.com/round/240575)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [Recovered Crew | Medical Cargo Respawns ](https://www.github.com/tgstation/tgstation/pull/87072)
- [Optivorbis lossless compression for the sound folder](https://www.github.com/tgstation/tgstation/pull/87191)

### Reproduction Steps:

1. be drone
2. put on pirate hat
3. "yarrr matey!"

**Comment by Ghommie** [comment]
I need an explaination to why this should be an issue.

**Comment by Sadboysuss** [comment]
My thought was drones shouldn't have such an easy way to bypass their language restrictions
