### ISSUE TITLE
Re-secured plastic flaps loose their airtight quality.

### ISSUE THREAD

**Issue by OverwatchVoice** [tgstation/tgstation#87417]
### Client Version:

515.1644

### Issue Summary:

When a plastic flap is unsecured and secured elsewhere, the new tile will not inherit the plastic flap's airtightness.

### Round ID:

XXXXXX

### Test Merge Information:

N/A
Tested on local.

### Reproduction Steps:

Self-explanatory.

**Comment by Sealed101** [comment]
likely extension of #71957
