### ISSUE TITLE
Slimes can move through railing

### ISSUE THREAD

**Issue by Weisyl** [tgstation/tgstation#87446]
### Client Version:

515.1643

### Issue Summary:

See title: Was working in xenobiology and while standing diagonally-adjacent to a slime that was "sealed" within railings on all 4 sides, the slime immediately stunned and latched on to me.

### Round ID:

[240639](https://scrubby.melonmesa.com/round/240639)

### Test Merge Information:

- [Optivorbis lossless compression for the sound folder](https://www.github.com/tgstation/tgstation/pull/87191)
- [Magazines now lazyload their contents in order to save on gun init times](https://www.github.com/tgstation/tgstation/pull/87224)

### Reproduction Steps:

Have a (hostile) slime trapped or surrounded on all sides by railings.

**Comment by dragomagol** [comment]
I mean, why should a slime be contained by railings? It can just squeeze through

**Comment by moocowswag** [comment]
they can go through grilles as well for the same reason.

**Comment by Weisyl** [comment]
They should be able to move through railings at any moment then, at least that way you would know right away. The fact that this behavior ONLY occurs when they latch on to somebody (and ignore the railing) gives the impression that this particular behavior is an oversight. That is to say, if they just ignored railings with normal movement, it would make a lot more sense.

**Comment by Sealed101** [comment]
railings do not block melee interactions for any mob, not just the slimes. i guess movement is blocked by the pathfinding AI, so what can you do
