### ISSUE TITLE
antigrav module and ion jetpack maeks you smash into fucking ervervything

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#87468]
### Issue Summary:

![image](https://github.com/user-attachments/assets/0a9e4688-db24-4497-9786-b7df05d74e83)
![image](https://github.com/user-attachments/assets/5d296ea5-c24e-4b8c-bf96-48925ee38a49)

![image](https://github.com/user-attachments/assets/9f2364ab-1469-4b1d-bda6-3e4be65ffacb)

holy shit

### Round ID:

[240723](https://scrubby.melonmesa.com/round/240723)

### Reproduction Steps:

1. activate antigrav and ion
2. run into every wall
3. die

pls just remove newton from stabilized jetpacks

**Comment by Pickle-Coding** [comment]
What's the issue though?

**Comment by DATA-xPUNGED** [comment]
Seems to be working as intended, doing that in-house is prone to lead to damage to one self

**Comment by carlarctg** [comment]
okay man lol
