### ISSUE TITLE
Bug when trying to sell Space Cash on a cargo shuttle

### ISSUE THREAD

**Issue by EEASAS** [tgstation/tgstation#87476]
### Client Version:

515.1642

### Issue Summary:

Even though i put 50000 credits on the cargo shuttle, it only sells for 39 credits.
There is also a spelling error where it says "billss" instead of "bills"
Tested locally
![image](https://github.com/user-attachments/assets/6464a18f-62f6-48d7-b3cf-0c2ab43221f7)

### Round ID:

N/A

### Reproduction Steps:

1. Try to sell 50000 space cash on the cargo shuttle
2. Look at the cargo computer in horror that you've only gained 39 credits
3. Look at the spelling mistake too: "billss"

**Comment by Sealed101** [comment]
was that the debug stack of cash that you sold? did you try it with other space cash stacks?

**Comment by EEASAS** [comment]
> was that the debug stack of cash that you sold? did you try it with other space cash stacks?

it was, i didn't try any other
