### ISSUE TITLE
Proto-kinetic Crusher alternative skins lack worn sprites entirely.

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#87473]
### Issue Summary:

Wearing a proto-kinetic crusher while it has a skin applied in either the suit storage or back slots produces the dreaded pink sprite of missing textures. They simply don't have a sprite available at all.

### Reproduction Steps:

1. Take a proto-kinetic crusher.
2. Apply a skin.
3. Store it in your suit storage or your back
4. No sproite!

**Comment by r3dj4ck0424** [comment]
oops
