### ISSUE TITLE
"Pirate cove" simplemobs attack ghost role pirate

### ISSUE THREAD

**Issue by WarerBrow** [tgstation/tgstation#87481]
### Client Version:

515.1642

### Issue Summary:

When you join in a "pirate cove" bitrunning domain as a ghost role pirate (i think this role is called "something remains"), simplemob pirates instantly attack and kill you. So this role becomes pointless in a sense that you can't play it

### Round ID:

[240770](https://scrubby.melonmesa.com/round/240770)

### Test Merge Information:

- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)

### Reproduction Steps:

1. Try to posess remains of a pirate in a "pirate cove" bitrunning domain
2. Get killed by agressive simplemobs
3. Watch dem bitrunners clean the area easily...

**Comment by DATA-xPUNGED** [comment]
Mutiny? In MY pirate ship? This can't be

**Comment by DATA-xPUNGED** [comment]
Failed to reproduce this, the pirates seem to ignore the ghost role as they should
