### ISSUE TITLE
Glass walls are completely opaque

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#87495]
### Client Version:

515.1645

### Issue Summary:

![obraz](https://github.com/user-attachments/assets/a915a358-0e7e-4e05-bd2c-cd583a395a53)

### Reproduction Steps:

1. Acquire wall girder (2 iron).
2. Put 2 glass on wall girder.
3. Behold.
4. Weep.

**Comment by Sealed101** [comment]
i dont remember if they ever were seethrough

**Comment by Likteer** [comment]
> i dont remember if they ever were seethrough

@Sealed101 They were both see-through and semi-translucent, showing a girder inside them.
Fake walls differed back then as well, having no girder inside (or clearly displaced girder even further back).
![obraz](https://github.com/user-attachments/assets/d7e1c023-ad4b-43b3-9e6a-d5253f371aac)
