### ISSUE TITLE
The SM sliver can be held using a fishing rod

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#87514]
### Issue Summary:

The SM sliver ~~for crafting the SM sword~~ can be held in hands by using a fishing rod to pick it up.
![dreamseeker_0aRRt1uGpq](https://github.com/user-attachments/assets/7f2321df-76c1-4a5c-87f5-7af3e233cd63)

### Reproduction Steps:

1. Get SM sliver ~~(the one for crafting sword)~~
2. Reel it in using a fishing rod
3. Profit

**Comment by JackEnoff** [comment]
![dreamseeker_yDkkDJ5toq](https://github.com/user-attachments/assets/0c5ac5a3-d1e0-47c6-b9aa-0a4a9f5eccc1)

**Comment by JackEnoff** [comment]
Additionally, it does not have dusting properties unless you drop it and try to pick it up with your hands.

**Comment by 0ri-0ri** [comment]
Hyper-Nob fishing hook when?

**Comment by Livrah** [comment]
> Additionally, it does not have dusting properties unless you drop it and try to pick it up with your hands.

but works fine on throw
