### ISSUE TITLE
Plasmamen with damaged envirosuit seem to catch fire regardless of what's over it (?)

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#87515]
### Client Version:

515.1645

### Issue Summary:

> The refactor accidentally made it, that anybody with a plasma limb in any spot on their body, needs a plasmaman envirosuit to survive. The one that spawns on plasmamen/is ordered from cargo. No substitutes.

![obraz](https://github.com/user-attachments/assets/bfb58f1c-83f1-41e1-960d-d4fe4ec0f42c)
![obraz](https://github.com/user-attachments/assets/875d67cf-b246-4f65-954d-0b72351d7e1f)
![obraz](https://github.com/user-attachments/assets/7e46faef-9602-43e3-91e5-20e2c6150d9f)

### Round ID:

[240856](https://scrubby.melonmesa.com/round/240856)

### Test Merge Information:

The following pull requests are currently test merged:
[#84826: 'Adds new station map Nebulastation' by KikoWen0 at commit becfb2aece](https://www.github.com/tgstation/tgstation/pull/84826)
[#87434: 'The death or internal/external organ pathing (ft. fixed fox ears and recoloring bodypart overlays with dye sprays)' by Ghommie at commit 619d09501e](https://www.github.com/tgstation/tgstation/pull/87434)
[#87499: 'Add time dilation to hub status.' by MrStonedOne at commit f761b04ef9](https://www.github.com/tgstation/tgstation/pull/87499)

### Reproduction Steps:

1. Be plasmaman (or anyone with plasmaman limbs)
2. Equip envirosuit, fire stops
3. Damage envirosuit, fire starts
4. Equip fire suit, fire does not stop

**Comment by MrMelbert** [comment]
IIRC a damaged piece of clothing doesn't cover the limb anymore.

**Comment by Likteer** [comment]
@MrMelbert Yup, but an undamaged firesuit does.

**Comment by MrMelbert** [comment]
so I supposed this is WAD, and this is just a consequence of the sandbox, in which case it's probably wontfix (though damaged clothes should probably be more obvious in how they don't cover the limb, maybe via alpha filters to cut out sections of it?)

**Comment by Likteer** [comment]
@MrMelbert WDYM "consequence of sandbox", wontfix? 
A firesuit is a thick, atmos, pressure-proof suit that covers everything but the head.
It is reasonable to expect it to work as an emergency replacement (especially when put over the old suit)
and it did work that way before the refactor (https://github.com/tgstation/tgstation/pull/87086).

Also, here's a case from 240872, caught as ghost.
A single plasmaman limb from bio anomaly on some guy. Full spacesuit. Still got taken out of the round.
(sprayed with fire-extinguisher at the split moment i took the pic)
![obraz](https://github.com/user-attachments/assets/012c75e1-a566-4eee-95b1-28a8f6225f67)
Spent the rest of it AFK under a shower, then dead because he couldn't get someone to do surgery on him.

**Comment by MrMelbert** [comment]
> WDYM "consequence of sandbox", wontfix? A firesuit is a thick, atmos, pressure-proof suit that covers everything but the head. It is reasonable to expect it to work as an emergency replacement (especially when put over the old suit) and it did work that way before the refactor (#87086).

Because if the thick, pressure proof suit is broken - and has a big hole in it - you can also reasonably expect that it won't protect you 

>  A single plasmaman limb from bio anomaly on some guy. Full spacesuit. Still got taken out of the round.

This is off (I think we should model fire per-bodypart rather than whole-body. Can't really model this correctly otherwise)

**Comment by Likteer** [comment]
@MrMelbert The emergency firesuit is pristine, no hole inside of it. Only the envirosuit underneath is damaged.

In the spacesuit scenario, there isn't even a damaged envirosuit underneath.

The refactor accidentally made it, that anybody with a plasma limb in any spot on their body, needs a plasmaman envirosuit to survive. The one that spawns on plasmamen/is ordered from cargo. No substitutes.

**Comment by MrMelbert** [comment]
Ok I misunderstood, I'm going to update it to clarify

**Comment by Sadboysuss** [comment]
https://github.com/user-attachments/assets/ec6e2d49-b2e9-43e8-8213-7ee2a2b9c242

**Comment by SmArtKar** [comment]
Damaged envirosuits not working is intentional, but firesuits not working at all is not - willfix:tm:
