### ISSUE TITLE
Proto-Kinetic Crusher does not give any Mining Experience when used for mining

### ISSUE THREAD

**Issue by 0ri-0ri** [tgstation/tgstation#87527]
### Client Version:

515.1642

### Issue Summary:

When you mine using the crusher you won't get any experience at all. I assume it is a consistency issue as the Proto-Kinetic Accelerator does give experience when used for mining so it doesn't make any sense to me why would the crusher be excluded as it is worse for mining than an accelerator specially if the accelerator is upgraded and dual wielded.

### Round ID:

[240898](https://scrubby.melonmesa.com/round/240898)

### Test Merge Information:

- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [The death or internal/external organ pathing (ft. fixed fox ears and recoloring bodypart overlays with dye sprays)](https://www.github.com/tgstation/tgstation/pull/87434)
- [Add time dilation to hub status.](https://www.github.com/tgstation/tgstation/pull/87499)

### Reproduction Steps:

1: Take a crusher
2: Mine some rocks
3: Check your skills and notice you have no remarkable skills no matter how many rocks you mine with the crusher

**Comment by Sealed101** [comment]
it never did afaik, plus it doesn't benefit from the skill level

**Comment by 0ri-0ri** [comment]
> it never did afaik, plus it doesn't benefit from the skill level
Does KPA benefit from the skill level?

**Comment by Sealed101** [comment]
pka recharges faster when you mine rocks with it (it's a little bit wonky, see https://github.com/tgstation/tgstation/issues/52807)

i mean honestly i am never too bothered by the lack of mining experience when mining with the crusher, because prolonged mining with the crusher fucking sucks ass and i wouldn't subject myself to this torture willingly

iirc plasma cutter mining and possibly resonator mining don't grant XP either, so there's also that. the feature is inconsistent indeed, and i'm not sure there's interest in bringing it up to par for all the mining methods, especially seeing as the skill is only used for the cape, the PKA cooldown and the Very Hard Rock/excavation ruin walls

**Comment by 0ri-0ri** [comment]
> pka recharges faster when you mine rocks with it (it's a little bit wonky, see #52807)
> 
> i mean honestly i am never too bothered by the lack of mining experience when mining with the crusher, because prolonged mining with the crusher fucking sucks ass and i wouldn't subject myself to this torture willingly
> 
> iirc plasma cutter mining and possibly resonator mining don't grant XP either, so there's also that. the feature is inconsistent indeed, and i'm not sure there's interest in bringing it up to par for all the mining methods, especially seeing as the skill is only used for the cape, the PKA cooldown and the Very Hard Rock/excavation ruin walls

I mean it is somewhat of a minor thing but it bothers me because it feels like the crusher is one of the mining tools that would appreciate being affected by the mining skill (including the janky cooldown reduction on breaking rocks but that's out of scope of this issue)

**Comment by Sealed101** [comment]
> #66826
> 
> intended behaviour. though changing it would be pretty nice

oh, we have a precedent of this, cool

in that case i suggest the OP makes a forum thread for this so at the very least the want for this change is not lost to the gigantic heap of issues that we have here. plus it's basically a feature request, and we don't handle these here anyway.
