### ISSUE TITLE
HPLC cannot purify and individualize some inverses

### ISSUE THREAD

**Issue by sneksnek** [tgstation/tgstation#87521]
### Client Version:

515.1644

### Issue Summary:

The HPLC cannot purify and turn inverses into their own inverse reagents. This seems to affect only inverses that do not fully transform into their inverse when they shift. This may be related to #81613 since the HPLC could perform this function before. A comment under that PR attests to this as well.

Inverses spawned in with the debug chemical synthesizer work, but not ones normally created. Here's a video to help show it in effect:

https://github.com/user-attachments/assets/cf6aa66d-52f1-4d54-8e7d-ca049dc471a8

### Reproduction Steps:

1. Create an inverse chemical that doesn't shift upon completion (example provided in video)
2. Put the beaker into the HPLC
3. Observe that it cannot purify and turn inverses into proper reagents

**Comment by Livrah** [comment]
I got a same result with Nooartrium (Penthrite). Also despite Penthrite being inverted, it still reacted with Atropine.

**Comment by SyncIt21** [comment]
Not a bug.

In your video check the status of each reagent. It clearly states the reason why they cannot be purified.

HPLC cannot purify all chems to 100% nor can it purify chems which are too impure, these limitations are intentional else it would make it too OP.

**Comment by sneksnek** [comment]
![prtemp1](https://github.com/user-attachments/assets/b9fcf45b-cca4-4441-a3e7-fa0e89a6c5c0)
![prtemp2](https://github.com/user-attachments/assets/d356d0a3-34f0-4e91-9902-5042a0e5a0a1)

The HPLC cleans reagents to their unreacted purity. For example, salicylic has an unreacted purity of 100%, libital has an unreacted purity of 75%. You can see that from this, cryogelidia's unreacted purity is 100%. Whether if it were 5% pure or 95% pure, it would clean the reagent to 100% and output the amount equal to how percent pure it was (30u 95% pure would turn into 28.5, 30u 5% pure would turn into 1.5u).

However, the HPLC refuses to purify it whatsoever.

![prtemp4](https://github.com/user-attachments/assets/c6d1bb04-895a-4dcd-bd84-d6c02119ee87)
![prtemp5](https://github.com/user-attachments/assets/8757b533-04d5-4557-8ae1-23807f35d53b)

There is not a case of "too impure" because even if you put a 5% pure chemical in there, it will still purify it to the base purity. (I chose synthflesh specifically because you can get it this low in-game if you want to).

![prtemp3](https://github.com/user-attachments/assets/847b6895-1261-4b52-9e54-59d977cd4d35)

I figured there may have been a concern for cryostylane's unreacted purity preventing purification, so I reacted some cryogelidia to 74% and it still refused to purify it.

**Comment by SyncIt21** [comment]
> There is not a case of "too impure" because even if you put a 5% pure chemical in there, it will still purify it to the base purity

This is only true "if the reagent does not have an inverse form" or "If the reagent is not already inverse". Cryogelidia is an inverse chem and from debugging its purity was 0.05 from the normal reaction so the output is correct here. The only thing wrong is that its displaying the inverse purity & not the actual purity

> Whether if it were 5% pure or 95% pure, it would clean the reagent to 100%

This is false. It only cleans the reagent to its "initial purity"(which is not always 100% for all reagents). For example you cannot purify ephedrine above 75%
![Screenshot (441)](https://github.com/user-attachments/assets/73305b7c-8a7d-46c2-bbc0-f5aba92a82a8)


> There is not a case of "too impure" because even if you put a 5% pure chemical in there, it will still purify it to the base purity. (I chose synthflesh specifically because you can get it this low in-game if you want to).

Back to point 1. You are able to purify synthflesh(`/datum/reagent/medicine/c2/synthflesh`) even at 5% purity because it does not have an inverse chem

![Screenshot (440)](https://github.com/user-attachments/assets/3f6c807b-3ac6-4319-9a72-d689389e1b31)

The HPLC works, it's only problem is it's feedback message for inverse chems which i will fix in my next PR

**Comment by sneksnek** [comment]
> > There is not a case of "too impure" because even if you put a 5% pure chemical in there, it will still purify it to the base purity
> 
> This is only true "if the reagent does not have an inverse form" or "If the reagent is not already inverse". Cryogelidia is an inverse chem and from debugging its purity was 0.05 from the normal reaction so the output is correct here. The only thing wrong is that its displaying the inverse purity & not the actual purity

This doesn't parallel how the HPLC worked former to the PR. You were able to purify inverses and convert them into their own proper reagents. You cannot do that now.

> > Whether if it were 5% pure or 95% pure, it would clean the reagent to 100%
> 
> This is false. It only cleans the reagent to its "initial purity"(which is not always 100% for all reagents). For example you cannot purify ephedrine above 75% ![Screenshot (441)](https://private-user-images.githubusercontent.com/110812394/380597654-73305b7c-8a7d-46c2-bbc0-f5aba92a82a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwOTYzNjksIm5iZiI6MTczMDA5NjA2OSwicGF0aCI6Ii8xMTA4MTIzOTQvMzgwNTk3NjU0LTczMzA1YjdjLThhN2QtNDZjMi1iYmMwLWY1YWJhOTJhODJhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQwNjE0MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzNjY2VmMGQ5MjE1YjYxYzI5NDE1YWY5MDlkNTlkNTc3NDZkNjU2MmUzZGVlNDkyOTA5ZDZjNzFhZWFhNjEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.e_gnqjKFZmxXk3YGKfx2GQI_MiWvY_bpjqNnZPjmYsg)
> 

I said cryogelidia's 'initial purity' is 100%. The wiki refers to this as unreacted purity so I called it that. Ephedrine has an initial purity of 75%, so it purifies up to that point.

![prtemp6](https://github.com/user-attachments/assets/6597bdbc-aeb8-484b-86df-72079b6ab8ef)
![prtemp7](https://github.com/user-attachments/assets/65ff6254-e01c-46e9-88cd-c5107c520dab)
![prtemp8](https://github.com/user-attachments/assets/22b25f5a-b54e-4c06-9e32-792b5547742d)

Cyrogelidia doesn't have a purity set, so it's 100%.

![prtemp9](https://github.com/user-attachments/assets/8a1d300f-1010-4ffa-b49f-939e59415575)

So it should purify it up to 100% and multiple the amount by the purity if it worked as it did before. However, it refuses to purify any inverse. This is a loss in functionality.

> > There is not a case of "too impure" because even if you put a 5% pure chemical in there, it will still purify it to the base purity. (I chose synthflesh specifically because you can get it this low in-game if you want to).
> 
> Back to point 1. You are able to purify synthflesh(`/datum/reagent/medicine/c2/synthflesh`) even at 5% purity because it does not have an inverse chem
> 
> ![Screenshot (440)](https://private-user-images.githubusercontent.com/110812394/380597245-3f6c807b-3ac6-4319-9a72-d689389e1b31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwOTYzNjksIm5iZiI6MTczMDA5NjA2OSwicGF0aCI6Ii8xMTA4MTIzOTQvMzgwNTk3MjQ1LTNmNmM4MDdiLTNhYzYtNDMxOS05YTcyLWQ2ODkzODllMWIzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQwNjE0MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZWEwYWY5NjU0YTJmMzRmZjJjMjRkODE2YjgzYjhjMzM3ZWE2MDFhNmE5MDVkYTM4Yzc2ODVkYzk3Mjk5NjVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KDnO4lR5SKZUndGiQMsXSZOWz0p5LL0KBrRaxI25WSo)
> 
> The HPLC works, it's only problem is it's feedback message for inverse chems which i will fix in my next PR

I believe there's a flaw with this system because it won't purify these reacted inverses due to that condition. I don't see why a reacted inverse shouldn't be able to be purified to the same degree as other chemicals, especially if it did so before the PR.

**Comment by sneksnek** [comment]
Alright I downloaded a random build from February 15th of this year, 6 days before the PR was made, to show it. The same recipe as in the video was used.

![prtemp14](https://github.com/user-attachments/assets/7bfdd397-cbce-46bd-b428-039e6a7b6584)
![prtemp10](https://github.com/user-attachments/assets/83b45877-bfb6-4de5-bae5-06e53658a321)
![prtemp11](https://github.com/user-attachments/assets/6ecaee6a-83b2-4ca8-9b9e-1b07e9b81b54)
![prtemp12](https://github.com/user-attachments/assets/39354ce9-d9c0-4b3f-8acb-0633fba074fc)

It didn't function perfectly (I had to process it a second time to purify to 100%) but you can see that it formerly would turn inverses into their proper, individual reagent.

![prtemp13](https://github.com/user-attachments/assets/b607fb3b-68f8-4321-986e-33c044600c2e)

**Comment by SyncIt21** [comment]
Thank you for the comparison from Feb 15th. I did assume all inverted chems cannot be purified which was a mistake on my part. Fix coming up
