### ISSUE TITLE
[Admin issue] Using execute midround ruleset and selecting "Syndicate Sleeper agent" does not work

### ISSUE THREAD

**Issue by xzero314** [tgstation/tgstation#87535]
### Client Version:

515.1644

### Issue Summary:

Using the game panel to execute a midround ruleset and specifically selecting syndicate sleeper agent does nothing.  Spawning other rulesets seems to be working as intended like paradox clone or revenant.  You will see a log in chat about spawning the ruleset but no player is made into a traitor.

### Round ID:

[240913](https://scrubby.melonmesa.com/round/240913)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)

### Reproduction Steps:

Try to produce a sleeper agent via game mode panel. execute the ruleset. A player should be made into a traitor but none is.

**Comment by DrAmazing343** [comment]
I genuinely just thought there were no candidates with the option turned on. I was annoyed and confused.
