### ISSUE TITLE
scanner gate malfunctioning on a sec off access

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#87542]
### Client Version:

515.1642

### Issue Summary:

scanner gate malfunctioning on a sec off access will play both "weapons detected!" and "weapons detection bypassed"

### Round ID:

[240921](https://scrubby.melonmesa.com/round/240921)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)

### Reproduction Steps:

1. increase malf probability to 100%
2. walk through with sec off access and a weapon

**Comment by lessthnthree** [comment]
It sure does.
