### ISSUE TITLE
Nearsighted quirk conflict with Scarred Eye quirk.

### ISSUE THREAD

**Issue by EmptyLullaby** [tgstation/tgstation#87546]
### Client Version:

515.1644

### Issue Summary:

If you have both the scarred eye and nearsighted quirks at the same time, if you at any point remove your prescription glasses you will be nearsighted for the rest of the round, regardless of what pair of glasses you are wearing.

### Round ID:

[240925](https://scrubby.melonmesa.com/round/240925)

### Reproduction Steps:

Pick Nearsighted and Scarred Eye quirks
Take off glasses
The nearsighted filter will appear
Put on glasses again
The filter does not go away

**Comment by 00-Steven** [comment]
wait aren't these like. supposed to be impossible to pick together.
https://github.com/tgstation/tgstation/blob/dbd1919c99f5f828417a47bbf1d5fae3970ecea8/code/controllers/subsystem/processing/quirks.dm#L6-L7

**Comment by EmptyLullaby** [comment]
ah I must have had my quirks snapshotted before this fix. (i play with around 20 negative quirks, dont ask) i will close this report then, thanks.
