### ISSUE TITLE
You can drag your inventory slots into your backpack? (fuck?)

### ISSUE THREAD

**Issue by K4rlox** [tgstation/tgstation#87551]
### Client Version:

515.1645

### Issue Summary:

halloween round
trying to drag my belt into my backpack box
somehow dragged my belt slot into my inventory

![image](https://github.com/user-attachments/assets/d5cbec97-5cff-440d-844b-9bead65bb58c)

Below is a video of me peforming this 

https://github.com/user-attachments/assets/2c2e2b3a-785c-4392-ab48-0470bcbfb94c

i have asked others and they have confirmed that they can infact see my pockets in my backpack

after reconnecting they got moved to my screen where the backpack slots are supposed to be while also still being in said backpack, far away from me
![image](https://github.com/user-attachments/assets/d81034d1-dbc4-49e7-b541-f47f9856a22c)

### Round ID:

[240935](https://scrubby.melonmesa.com/round/240935)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [fixes issues with the separate modsuit part activation](https://www.github.com/tgstation/tgstation/pull/87482)

### Reproduction Steps:

1. vampire on halloween round (may be related?)
2. drag inventory slot into backpack
3. ?????
4. profit?

**Comment by K4rlox** [comment]
to add onto this

apperently walls work too
![image](https://github.com/user-attachments/assets/9fa5fa67-f115-4448-ae68-4a266685aa68)

**Comment by necromanceranne** [comment]
No sir, I did not steal that entire refrigerator in my bag. I'm keeping it for a friend.

**Comment by DaydreamIQ** [comment]
![image](https://github.com/user-attachments/assets/00282795-e004-4c0f-9518-5a3c6654546a)
So I may have stuffed a Paddy into my bag AND made a permament singlo on my screen when i tried to do it to one

**Comment by Fikou** [comment]
caused by #87551

**Comment by Isratosh** [comment]
![](https://i.imgur.com/XLjNHC9.png)
![](https://i.imgur.com/B7Kn2SZ.png)

**Comment by Deadgebert** [comment]
If you need help with replication.
drag any object on screen (except walls or floors) onto an item in storage
funny bug

**Comment by Fikou** [comment]
FIXED ✅

**Comment by deathrobotpunch** [comment]
> FIXED ✅

NOOOOOO I HAVEN’T GOT TO TRY IT :((((((

**Comment by Blacklist897** [comment]
THEY ARE DRAGGING THE WALLS

**Comment by Hotmud9** [comment]
> So I may have stuffed a Paddy into my bag AND made a permament singlo on my screen when i tried to do it to one

taking bagulo'ing to a whole new level there

**Comment by TheVekter** [comment]
![image](https://github.com/user-attachments/assets/268d584b-0678-4c97-b687-b6fb18a9236a)
Congratulations, I guess!
