### ISSUE TITLE
Nukie .357 revolver bundle can't be reloaded

### ISSUE THREAD

**Issue by WarerBrow** [tgstation/tgstation#87559]
### Client Version:

515.1642

### Issue Summary:

When you buy a nukie revolver bundle (a box with .357 revolver with 3 speedloaders in it) after you shoot 7 rounds it cannot be reloaded by using speedloader on it. 

I don't know if a regular revolver (not from bundle) suffers from this, nor I don't know if it can't be reloaded manually, bullet by bullet into the chamber. That would require an additional check. 

### Round ID:

[240980](https://scrubby.melonmesa.com/round/240980)

### Test Merge Information:

- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [The death or internal/external organ pathing (ft. fixed fox ears and recoloring bodypart overlays with dye sprays)](https://www.github.com/tgstation/tgstation/pull/87434)

### Reproduction Steps:

1. Buy revolver bundle as a nukie
2. Shoot the entire chamber
3. Try using speedloader on revolver
4. See as nothing happenes

**Comment by Maxipat112** [comment]
Also seemingly doesn't work on det's revolver, round 240982
