### ISSUE TITLE
Detectives .38 cannot be reloaded

### ISSUE THREAD

**Issue by kuricityy** [tgstation/tgstation#87567]
### Client Version:

515.1636

### Issue Summary:

The detectives revolver cant be reloaded, and when you try to unload it it only deposits one bullet. I saw an issue report earlier, talking about the nukie 357 bundle, is it possible this is broken for all revolvers?

### Round ID:

[241001](https://scrubby.melonmesa.com/round/241001)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)

### Reproduction Steps:

Spawn in as detective
Grab your colt.
Try to empty it.
 Fail.
 Try to reload
 Also fail

**Comment by necromanceranne** [comment]
@SmArtKar you have entered the REVOLVER CODE PROBLEMS ZONE
