### ISSUE TITLE
DNA Infused Goliath Tendril Hammer Can Burn to Ash

### ISSUE THREAD

**Issue by ZealousZeke** [tgstation/tgstation#87566]
### Client Version:

515.1645

### Issue Summary:

The DNA Infused goliath tendril hammer, which is attached to the goliath brain organ, can burn to ash if you are on fire long enough.
![golaithhammerrr](https://github.com/user-attachments/assets/4372c410-876a-4ad4-83fc-676c84380fc5)

### Round ID:

[240997](https://scrubby.melonmesa.com/round/240997)

### Reproduction Steps:

1. Get goliath tendril Hammer from DNA infusing goliaths.
2. Set yourself on fire for a minute or two.
3. Watch your beloved goliath tendril hammer turn to ash, never to return.

**Comment by Loafin34** [comment]
accurate to flesh
