### ISSUE TITLE
glass tiles prevent access to sublayer of tiles

### ISSUE THREAD

**Issue by wonderinghost** [tgstation/tgstation#87569]
### Client Version:

515.1642

### Issue Summary:

items under a glass tile cant be accessed or be replaced 

### Round ID:

[241001](https://scrubby.melonmesa.com/round/241001)

### Reproduction Steps:

place a glass tile
try to place wire or something on that tile or cut it 
notice the fruitless attempt as its inaccessible and cant be replaced without tile destruction

**Comment by timothymtorres** [comment]
Relevant PR:

- #66301
