### ISSUE TITLE
Observing a ghost and clicking on a ghost notification forces them to orbit an object

### ISSUE THREAD

**Issue by deathrobotpunch** [tgstation/tgstation#87572]
### Issue Summary:

observing a ghost (in this case @DrAmazing343 ‘s ghost (:< ) and clicking on a notification that appears in the hud forces the person you are observing to orbit an object.

this might also be able to sign people up for some roles too idk

### Round ID:

https://statbus.space/rounds/240735

### Test Merge Information:

https://github.com/tgstation/tgstation/pull/83227

https://github.com/tgstation/tgstation/pull/84826

https://github.com/tgstation/tgstation/pull/87072

### Reproduction Steps:

1. Ghost Observe Jane Sierpenski‘s ghost (any other ghost works fine, Use the observe command not orbit)
2. wait for or create a ghost notification.
3. spam press on the notification and watch as they are helplessly stuck until the notification disappears.

**Comment by DrAmazing343** [comment]
just checked my email to see a ping from github and Yeah. it threw me for a loop when I realized what was happening. For additional context, I was able to fix this via spawning myself in then re-ghosting; whatever was happening was a temporary thing, and I haven't experienced it since.

**Comment by deathrobotpunch** [comment]
> whatever was happening was a temporary thing, and I haven't experienced it since.

For it to happen someone someone has to do it to you intentionally
