### ISSUE TITLE
Glass Duplication Glitch with Status Display Frame

### ISSUE THREAD

**Issue by NebulaSkull** [tgstation/tgstation#87574]
### Issue Summary:

You can make infinite Glass with 7 sheets of Iron

### Reproduction Steps:

1. Get 7 Sheets of Iron.

2. Make a Status Display Frame.

3. Wrench the frame in hand.

4. You gain 1 Glass Sheet and 7 Iron Sheets back.

5. Repeat for infinite Glass.

**Comment by chel8ed** [comment]
Exact same problem with newscasters as well, they give 4 glass sheets each time they are deconstructed and return same amount of iron as they cost to create
