### ISSUE TITLE
Peacekeeper cyborg's shield breaks on shuttle

### ISSUE THREAD

**Issue by K4rlox** [tgstation/tgstation#87609]
### Client Version:

515.1645

### Issue Summary:

![image](https://github.com/user-attachments/assets/418c74d1-e1ab-4691-9d63-f6b65a764b2e)
![image](https://github.com/user-attachments/assets/9cac93bc-f393-4e8e-ae74-ca3382d475bc)
no idea how it happened
shuttle left and parts of it began floating away

### Round ID:

[241114](https://scrubby.melonmesa.com/round/241114)

### Test Merge Information:

- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)

### Reproduction Steps:

1. be peacekeeper borg
2. get on shuttle and enable your shield
3. wait for shuttle to depart
4. watch as your shield floats away

**Comment by Sealed101** [comment]
fairly certain this is #77093 again
