### ISSUE TITLE
All flatpacked manufacture machines stack in alt click menu

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#87614]
### Issue Summary:

![Screenshot_416](https://github.com/user-attachments/assets/f69ae528-b7b0-4d1a-b6c5-936b6d006797)

### Reproduction Steps:

flatpack different manufacture machinery
unwrap the boxes on a same tile

**Comment by SyncIt21** [comment]
@Sealed101 not a bug.

By default the lootpanel has "grouping enabled" which stacks together objects with the same typepath. This option is indicated by the green stack box on the top left of the loot panel.

![Screenshot (446)](https://github.com/user-attachments/assets/e9b50d20-a8e5-4c89-9a05-1720f4b8cd86)

Disabling this option displays each individual flat box

**Comment by Sealed101** [comment]
oh no, streamer skill issue
