### ISSUE TITLE
ice cream vats are seriously broken

### ISSUE THREAD

**Issue by gorillion** [tgstation/tgstation#87632]
### Client Version:

515.1640

### Issue Summary:

ice cream vats do not accept more reagents. there is a slot to put a beaker in, but regardless of what is in the beaker, it does not transfer to the actual tank that the vat draws from, limiting you to making ~6 ice creams per vat. i was testing this with Jane Sierpinski and she said that the vat somehow 'ate' her container of milk cream (it was not inside the vat, removing the beaker revealed a seperate beaker filled with something else that I had inserted before). something is seriously broken.

### Round ID:

[241197](https://scrubby.melonmesa.com/round/241197)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [[TM ONLY] The roundstart report will only ever show either Pulsar Star or White Dwarf](https://www.github.com/tgstation/tgstation/pull/87584)

### Reproduction Steps:

1. get an ice cream vat from kitchen backroom (seems to be the only place it spawns)
2. try to put a beaker of ingredients into it
3. realize nothing is actually transferred to the tank
4. cry

**Comment by SyncIt21** [comment]
Duplicate #85190 
Duplicate #86181

**Comment by Sealed101** [comment]
^
