### ISSUE TITLE
Borgs wirecutters do not work on airlock wires ; borg cautery does not close surgery

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#87641]
### Client Version:

515.1645

### Issue Summary:

Spawn in as a medical borg.
Slam a human on your borg bed, open a tend wounds (brute) on em, run a step, try end the surgery with the cautery, get told "This step required a different tool!"

Similarlyish
Engi borg up to an airlock, screwdriver the panel open, try wirecuttering things, get told "You need wirecutters!"

### Round ID:

[241210](https://scrubby.melonmesa.com/round/241210)

### Test Merge Information:

- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [[TM ONLY] The roundstart report will only ever show either Pulsar Star or White Dwarf](https://www.github.com/tgstation/tgstation/pull/87584)

### Reproduction Steps:

.

**Comment by MrMelbert** [comment]
https://github.com/tgstation/tgstation/pull/87464/files#diff-0334f363d76b6d70d175ecf493a99ef2d04cf8eeedbba89e65c60b9240c08152 Deleted a bunch of omnitool stuff so I'd start by looking there

**Comment by SyncIt21** [comment]
After all my hardwork in fixing borg omnitool bro just deleted everything :(. 

Assign me this task I'm on it

**Comment by Aliceee2ch** [comment]
> After all my hardwork in fixing borg omnitool bro just deleted everything :(
> 
> Assign me this task I'm on it

i tried to bound it for all items and when i tested it worked good :sob:

**Comment by combustor** [comment]
You also can't cut APC wires or pulse them
