### ISSUE TITLE
The entirety of TG Station appears to be down

### ISSUE THREAD

**Issue by btcbuster** [tgstation/tgstation#87675]
### Issue Summary:

The Main website has had most of its functionality stripped and a link to an unrelated youtube video is inserted. Related websites such as the forum and wiki also appear to be nonfunctional.

### Reproduction Steps:

1. Go the tgstation13.org
2. Cry

**Comment by Sealed101** [comment]
not the place for this kind of issue (see discord)

**Comment by Sadboysuss** [comment]
unfortunately not a codebase issue, wait till the host(s) figure it out

**Comment by btcbuster** [comment]
> not the place for this kind of issue (see discord)

There is no way into the Discord when everything has stopped functioning, unfortunately
