### ISSUE TITLE
The shuttle can occasionally leave in blob rounds for some reason

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#8767]
In certain hard to replicate situations that I can't pin down blob rounds can somehow get around the var that prevents the shuttle from leaving while the blob is still alive.

Ways this could be happening:

blob_cores.len might be misreported as 0 at some point, which would set off a mulligan and allow the shuttle to leave. The round I saw this happen in had no other antagonists though.

emergencyNoEscape might be accidentally getting set to 0 at some point

or some other thing I haven't considered

**Comment by optimumtact** [comment]
old higgs bugson
