### ISSUE TITLE
Cannot make American Sausage 

### ISSUE THREAD

**Issue by Thlumyn** [tgstation/tgstation#87694]
### Client Version:

515.1636

### Issue Summary:

Cannot make American Sausage. Both salami and that are made with knife on sausage so it always seems to make salami. This was reproduced on a slightly modified version on my local computer, but that specific code shouldn't have been changed. I'll test it with a fresh rebuild with no modifications and provide most recent commit # when I get home but I don't create issue now I will forget. 

<details>
<Summary>Screenshot of where it is adding components mostly for my own reference if I decide to try and fix this later pls don't judge my cropping skills</summary>

![Screenshot_20241104-134511](https://github.com/user-attachments/assets/d7ab291e-99d6-493b-b72b-38a6f456cffe)

</details>

### Reproduction Steps:

Get sausage, place on table. Cut with knife.

**Comment by Dawnseer** [comment]
Either this has already been fixed, or you've done something wrong. I just tested this out and it works just fine. It should give you a menu like so
![image](https://github.com/user-attachments/assets/49cf023b-1c16-4993-a1c9-1eb6f2f1aaab)
