### ISSUE TITLE
Pressure-proof clothing still/once again DOES NOT prevent plasmamen self-combustion

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#87718]
### Client Version:

515.1646

### Issue Summary:

Previously, on /tg/ plasmamen issues:
https://github.com/tgstation/tgstation/issues/87515
https://github.com/tgstation/tgstation/pull/87598

Breaking News:
![obraz](https://github.com/user-attachments/assets/6df4abcd-ac8e-4c49-962a-86d28ea9bbe0)

### Round ID:

[241451](https://scrubby.melonmesa.com/round/241451)

### Test Merge Information:

The following pull requests are currently test merged:
[#84826: 'Adds new station map Nebulastation' by KikoWen0 at commit aac758d4e5](https://www.github.com/tgstation/tgstation/pull/84826)
[#87584: '[TM ONLY] The roundstart report will only ever show either Pulsar Star or White Dwarf' by TheVekter at commit 59299a5029](https://www.github.com/tgstation/tgstation/pull/87584)

### Reproduction Steps:

Same as it ever was

**Comment by SmArtKar** [comment]
#87598 fixed the issue, servers dood
