### ISSUE TITLE
Missing essentials in Birdshot Medbay (and kitchen)

### ISSUE THREAD

**Issue by MatrixOne500** [tgstation/tgstation#87729]
### Client Version:

515.1646

### Issue Summary:

Here's what's missing roundstart in Birdshot medbay, from most critically important to least:
1. A crate of surplus robotic limbs.
2. Surgery tray.
3. Chem storage (most needed for Formaldehyde, but also used for spare Multiver and doing chem during power outages).
4. Medbay break room, preferably with a microwave for charging PDAs, cigarette machine, and food.

The kitchen is also missing a machine for drying food (dehydrator) which necessitates deconstructing the bar chairs for wood to make a drying rack. Having only one oven is also a large nuisance and makes the chef unable to bake multiple components simultaneously, so I consider that a missing feature.

### Test Merge Information:

- [[TM ONLY] The roundstart report will only ever show either Pulsar Star or White Dwarf](https://www.github.com/tgstation/tgstation/pull/87584)

### Reproduction Steps:

A surgery tray is missing from the surgery theater room.
A crate of robotic limbs is missing from the cold room (the one with the blood crates), or possibly from surgery theater room.
A dehydrator is missing in the kitchen.

**Comment by Sealed101** [comment]
not sure about the drying rack since i haven't really seen it in any kitchen round-start (exluding northstart and nebula cuz i never played them) but the other conserns are fair

**Comment by Mrfilms** [comment]
> not sure about the drying rack since i haven't really seen it in any kitchen round-start (exluding northstart and nebula cuz i never played them) but the other conserns are fair

The 'dehydrator', a machine that effectively does the same function as a drying rack, is a roundstart spawn in practically every kitchen.

**Comment by Sealed101** [comment]
oh it's [this PR](https://github.com/tgstation/tgstation/pull/85141) i see
goes to show how blind i am lmao
