### ISSUE TITLE
"conveyor sort-router" doesn't validate filters it deletes

### ISSUE THREAD

**Issue by DrPepperIsSpicy** [tgstation/tgstation#87722]
### Issue Summary:

title, either make the locate in context(IE: LOCATE(THING) IN (LISTOFTHINGS)) or check to see if its the proper type
end result = player can delete any object ref

### Reproduction Steps:

EDIT: REMOVED FOR SECURITY REASONS
use multitool on sorter, change ref to thing you want to delete, paste and enter in chat while the menu is open

**Comment by LemonInTheDark** [comment]
@mc-oofert I hate you I hate you I hate you
also consider just opening a fix for this sort of thing directly instead of making an issue report this iss omething I'd prefer to fix as fast as possible

**Comment by DrPepperIsSpicy** [comment]
Yeah MB I don't have GitHub setup

**Comment by LemonInTheDark** [comment]
sall good

**Comment by mc-oofert** [comment]
oh yeah you can fuck with byond cache to modify tgui clientside
hold on let me check if i apparently did not put validation

**Comment by mc-oofert** [comment]
also that edit is far too late github has an edit history feature
