### ISSUE TITLE
The God Hand null rod can melt into ash if the wielder is on fire for long enough, despite the god hand literally being made of fire.

### ISSUE THREAD

**Issue by Xkallubar** [tgstation/tgstation#87746]
### Issue Summary:

The god hand should probably be fire proof (as with the other null rods, I see no reason for them to not be fire proof)

### Reproduction Steps:

1. Select the god hand null rod
2. Acquire 100% fire immune clothing
3. Set yourself on fire
4. Wait a couple of minutes

**Comment by the-orange-cow** [comment]
For what its worth, the same can happen to miners KPA's, and isn't even that uncommon when wearing for proof clothing.

**Comment by necromanceranne** [comment]
I mean, this is really two issues in one. One more obvious than the other. The God Hand is burnable as an abstract arm replacement. And that total fire immunity does not protect your held items (still).
