### ISSUE TITLE
Genetic Sequencing Bug- missing orange box

### ISSUE THREAD

**Issue by pingytalker** [tgstation/tgstation#87770]
### Client Version:

515.1643

### Issue Summary:

https://imgur.com/a/bug-tgstation-QT7769T

![Screenshot 2024-11-08 165957](https://github.com/user-attachments/assets/7db1ff2e-9554-4e18-a006-11a9364d0219)

An orange box is supposed to be around the genes sequences that start out wrong (like, AX, or XX)- this allows you to go back and forth between different genes and work on different ones, or just attempt brute forcing. Without the orange box, you have to screenshot or write down the genes as they start each time, and that is horrendously more difficult. I don't see anything in the changelog about this, so I'm really really hoping its a bug and not some kind of massive intentional genetics nerf. Not fun to do genetics at all right now. :(

EDIT: Important info, this seems to be only happening on Terry for reasons unknown to the minds of men. Manuel is working fine and has the orange box.

### Round ID:

[241637](https://scrubby.melonmesa.com/round/241637)

### Test Merge Information: This is only happening on Terry, not Manuel. I do not know why. 
The following pull requests are currently test merged:
[#87742: '[TM ONLY] Buffs jetpack/wing forces and stabilization greatly to see how major the subsystem chugging issue is' by SmArtKar at commit a6186c2da9](https://www.github.com/tgstation/tgstation/pull/87742)
[#87754: '(TM ONLY) (THIS IS A TEST PR) Batons have their stamina damage reduced by armor, but get stun armor penetration based on some factors (THIS IS A TEST PR)' by necromanceranne at commit 05ce384386](https://www.github.com/tgstation/tgstation/pull/87754)

### Reproduction Steps:

1. Go to genetics
2. put a person in the dna scanner
3. look at console
4. under "Genome Sequencer TM" there will be sequences that contain X's, those will not be marked with an orange box indicating they are wrong, and they should be marked with the box.

**Comment by jlsnow301** [comment]
very likely resolved after #87776. feel free to reopen if it isn't
