### ISSUE TITLE
Nuke Spaced = No proper end screen

### ISSUE THREAD

**Issue by SconesC** [tgstation/tgstation#8778]
If the nuke gets spaced after ops make it go delta, there is no end roll where we see what the flukes bought, and what their ckeys are so we can ridicule them

**Comment by PKPenguin321** [comment]
to clarify, the *end-round report* doesn't show up properly, but the cutscene of the nuke going off (and the station remaining intact, as the bomb was offstation) will still play properly

**Comment by tedward1337** [comment]
Fixed
