### ISSUE TITLE
Detective UI style lacks the action bar options bar

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#87809]
### Issue Summary:

![image](https://github.com/user-attachments/assets/794d848e-a7d8-485b-b45f-b8344741a594)
This bar doesn't seem to exist on the detective UI style

### Round ID:

Downstream issue from https://github.com/Bubberstation/Bubberstation

### Reproduction Steps:

Use Detective UI

**Comment by Sealed101** [comment]
find the difference and win a prize (taxes may apply)
![изображение](https://github.com/user-attachments/assets/441073d0-4516-4b18-bd08-13a28478e463)

![изображение](https://github.com/user-attachments/assets/53c4523c-0481-4f5c-bfe5-587b2719048e)
