### ISSUE TITLE
tracker playtime menu seems broken

### ISSUE THREAD

**Issue by Graybear98** [tgstation/tgstation#87826]
### Client Version:

515.1642

### Issue Summary:

![Новый точечный рисунок (2)](https://github.com/user-attachments/assets/fdac8d2d-032f-4c31-a5d1-448e0db55772)

### Reproduction Steps:

1. open the game
2. open menu tracker playtime

**Comment by jlsnow301** [comment]
Tested this on sybil&manuel live, MIGHT just be a cache issue for now. Either way, keeping an eye on this and it might circle back to #87776. Do you have a round id?

**Comment by Graybear98** [comment]
> Tested this on sybil&manuel live, MIGHT just be a cache issue for now. Either way, keeping an eye on this and it might circle back to #87776. Do you have a round id?

I was playing on downstream and saw this, then I decided to check it on terry and found the same bug here. Haven't cleared explorer cache, so might be it

**Comment by jlsnow301** [comment]
very likely resolved after #87776. feel free to reopen if it isn't
