### ISSUE TITLE
Every radio message has a "1" before it

### ISSUE THREAD

**Issue by Time-Green** [tgstation/tgstation#87822]
### Client Version:

515.1637

### Issue Summary:

![image](https://github.com/user-attachments/assets/11848347-3cc9-4626-9094-6c3e8d8d3b2e)

### Round ID:

[241814](https://scrubby.melonmesa.com/round/241814)

### Reproduction Steps:

1. Play the game
2. Listen or talk in radio
3. "1"

**Comment by Time-Green** [comment]
![image](https://github.com/user-attachments/assets/e1a05b36-2eb7-456a-a180-dd90f8daea16)

**Comment by SmArtKar** [comment]
what in the everloving

**Comment by Time-Green** [comment]
uhhh it stopped when I updated idk man
