### ISSUE TITLE
Lizards do not like the taste of nuts

### ISSUE THREAD

**Issue by ItzRiumz** [tgstation/tgstation#87844]
### Client Version:

515.1640

### Issue Summary:

Lizards apparently do not like the taste of nuts even though they're supposed to.

### Round ID:

[241867](https://scrubby.melonmesa.com/round/241867)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)

### Reproduction Steps:

![image](https://github.com/user-attachments/assets/0b4e6514-123b-42b6-a535-99196bedd4a4)
![image](https://github.com/user-attachments/assets/d6d6d2b4-7d56-4b56-ba20-aa79634049ae)

**Comment by SmArtKar** [comment]
```js
/obj/item/organ/tongue/lizard
	name = "forked tongue"
	liked_foodtypes = GORE | MEAT | SEAFOOD | NUTS | BUGS
	```
```js
/obj/item/food/pizza/flatbread/rawmeat
	name = "meatlovers flatbread"
	foodtypes = MEAT | NUTS | RAW | GORE
	```
that's an issue specifically due to RAW tag on meatlovers' flatbread
