### ISSUE TITLE
manufacturing assembling machine makes "junk shell spawner" instead of actual junk shells

### ISSUE THREAD

**Issue by vertolodka** [tgstation/tgstation#87876]
### Client Version:

515.1642

### Issue Summary:

manufacturing assembling machine makes "junk shell spawner" instead of actual junk shells

### Test Merge Information:

[#87742: '[TM ONLY] Buffs jetpack/wing forces and stabilization greatly to see how major the subsystem chugging issue is' by SmArtKar at commit a6186c2da9](https://www.github.com/tgstation/tgstation/pull/87742)
[#87754: 'Batons have their stamina damage reduced by armor, get stun armor penetration' by necromanceranne at commit 697e66008b](https://www.github.com/tgstation/tgstation/pull/87754)
[#84280: 'Add ignition sound and roaring fire to atmos fire' by TheBoondock at commit 2f7cbfbdbc](https://www.github.com/tgstation/tgstation/pull/84280)

### Reproduction Steps:

set manufacturing assembling machine to make "junk shell". supply it with all required materials. see junk shell spawner at output

**Comment by Loafin34** [comment]
im guessing that junk shell spawner is what's originally crafted, but it automatically chooses which of the junk shells to be qdeld by and replaced

**Comment by vertolodka** [comment]
same thing with lizard boots craft (lizard skin + leather)
