### ISSUE TITLE
hp+ gum don't work unless you take a bite first

### ISSUE THREAD

**Issue by vertolodka** [tgstation/tgstation#87873]
### Client Version:

515.1642

### Issue Summary:

hp+ gum in mask slot doesn't trigger the "happieness" effect unless you take a bit first and then put it into the mask slot.

### Test Merge Information:

[#87742: '[TM ONLY] Buffs jetpack/wing forces and stabilization greatly to see how major the subsystem chugging issue is' by SmArtKar at commit a6186c2da9](https://www.github.com/tgstation/tgstation/pull/87742)
[#87754: 'Batons have their stamina damage reduced by armor, get stun armor penetration' by necromanceranne at commit 697e66008b](https://www.github.com/tgstation/tgstation/pull/87754)
[#84280: 'Add ignition sound and roaring fire to atmos fire' by TheBoondock at commit 2f7cbfbdbc](https://www.github.com/tgstation/tgstation/pull/84280)

### Reproduction Steps:

find hp+ gum box in maints. put gum into mask slot. no effect on your mood.
take a bite and put it into mask slot. see "cant feel a thing" in mood.

**Comment by SmArtKar** [comment]
The problem isn't with reagents setup but rather with microdosing not working. Taking a bite just gives you a large enough dose in this case - chewing it and giving it to someone else to suckle on will not make them happy.

**Comment by SmArtKar** [comment]
![image](https://github.com/user-attachments/assets/be1629d7-87af-44a3-82b2-6fc4f4af343f)
```js
/datum/reagent/drug/happiness/on_mob_metabolize(mob/living/affected_mob)
	. = ..()
	to_chat(world, "1")
	affected_mob.add_mood_event("happiness_drug", /datum/mood_event/happiness_drug)

/datum/reagent/drug/happiness/on_mob_delete(mob/living/affected_mob)
	. = ..()
	to_chat(world, "2")
	affected_mob.clear_mood_event("happiness_drug")
```
yeah, its being metabolized out of the user's system right after being introduced
