### ISSUE TITLE
manufactoring lathe consumes materials but won't output anything if theres manufacturing assembling machine at the output

### ISSUE THREAD

**Issue by vertolodka** [tgstation/tgstation#87874]
### Client Version:

515.1642

### Issue Summary:

manufactoring lathe will consume material but won't output anything if theres manufacturing assembling machine at the output (tried with crafting cable on lathe)
example:
![a](https://github.com/user-attachments/assets/9ab34f8c-29d1-4e0b-b137-97b995d97e15)

### Test Merge Information:

[#87742: '[TM ONLY] Buffs jetpack/wing forces and stabilization greatly to see how major the subsystem chugging issue is' by SmArtKar at commit a6186c2da9](https://www.github.com/tgstation/tgstation/pull/87742)
[#87754: 'Batons have their stamina damage reduced by armor, get stun armor penetration' by necromanceranne at commit 697e66008b](https://www.github.com/tgstation/tgstation/pull/87754)
[#84280: 'Add ignition sound and roaring fire to atmos fire' by TheBoondock at commit 2f7cbfbdbc](https://www.github.com/tgstation/tgstation/pull/84280)

### Reproduction Steps:

place manufactoring lathe, set it to make cables. place manufacturing assembling machine at the lathe's output. set it to make anything. put some glass+iron into lathe via conveyors. manufacturing lathe consumes materials, but won't make any cables, until you unwrench and move assembling machine away.

**Comment by Sadboysuss** [comment]
@mc-oofert
