### ISSUE TITLE
"Input: Enable TGUI" preference does not function with any verb hotkeys

### ISSUE THREAD

**Issue by subject217** [tgstation/tgstation#87884]
### Issue Summary:

The intended behavior is that when the preference is not enabled, ALL input boxes will use the normal BYOND input. For some reason, the hotkey specifically bypasses this and forces TGUI say regardless of preferences.

### Reproduction Steps:

1. Boot up your local master of tgstation
2. Disable TGUI input in preferences
3. Use the say verb from the input bar or the IC tab, it works as intended
4. Press your say hotkey, by default "t"
5. You get TGUI input instead
6. 
This also happens with Me, OOC, and Asay. Works in the IC/OOC tab, pressing the hotkey always gives TGUI.

**Comment by Sadboysuss** [comment]
![image](https://github.com/user-attachments/assets/d96591d2-739b-4952-927f-83b9dbce70e0)

**Comment by subject217** [comment]
Mothblocks disagreed on the forums a year ago in this thread which is why I made the issue in the first place.

https://tgstation13.org/phpBB/viewtopic.php?p=670157#p670157 

https://tgstation13.org/phpBB/viewtopic.php?p=672068#p672068

Specifically, the phrase "I think it should revert it to old chat as well". I wasn't able to find anyone at all who talked about the issue being specific to hotkeys in my research on the issue, which I'm pretty sure is just because nobody uses verbs the old BYOND way.

@Sadboysuss
