### ISSUE TITLE
The second coming of Space Jesus: Fish multiplication bug via the holodeck and fishing portal capsules

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#87930]
### Client Version:

515.1637

### Issue Summary:

Powering on the holodeck while a fishing portal capsule is deployed on it makes it overload and turn off. For some reason, if you have fished up fishes from the capsule's water already, each time you do this it duplicates the fish. It duplicates a new fish for each one already there - It didn't seem to be doubling each time, so **hopefully** this isn't a grey goo scenario, but it's still BAD

![Screenshot 2024-11-14 231031](https://github.com/user-attachments/assets/364d7d94-9d88-4281-9682-2dc3c463a6e4)
When I first noticed it, after trying to start it around 4 times
![Screenshot 2024-11-14 231340](https://github.com/user-attachments/assets/9944e109-6ae7-4113-aca5-2bf3880cfc64)
After 1 or 2 more tries

### Round ID:

[242215](https://scrubby.melonmesa.com/round/242215)

### Test Merge Information:

- [[tgui] Tgui core components D-M](https://www.github.com/tgstation/tgstation/pull/87763)

### Reproduction Steps:

1. Get fishing portal capsule
2. Deploy in holodeck
3. Fish up some fish
4. Toggle the holodeck on a few times and watch as the manna flows

**Comment by OuroborusReporter** [comment]
Heck, ick ock, closing and will reopen post-round

**Comment by OuroborusReporter** [comment]
![Screenshot 2024-11-14 232012](https://github.com/user-attachments/assets/aff88787-2658-45f1-a6f5-35295567e19f)
Mime Christ, by the way

**Comment by CCC23** [comment]
what the fuck
