### ISSUE TITLE
Manufactory sort-routers can crawl

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#87945]
### Issue Summary:

https://www.twitch.tv/livrah/clip/DelightfulCrepuscularSparrowPogChamp-KtqJyZ1vYZUpNu2c

### Reproduction Steps:

Build Sort-router
Unwrench it
It's free now (in whatever direction chosen with multitool)
(emag content)

**Comment by mc-oofert** [comment]
oops
