### ISSUE TITLE
Emitter beams are a bit WONKY and invisible too

### ISSUE THREAD

**Issue by Formerxboxgamer** [tgstation/tgstation#87965]
### Issue Summary:

Emitters beams are invisible and seem to randomly show their beams firing in whatever direction they feel like

### Round ID:

[242350](https://scrubby.melonmesa.com/round/242350)

### Test Merge Information:

[#87763: '[tgui] Tgui core components D-M' by jlsnow301 at commit 3f2834c9ba](https://www.github.com/tgstation/tgstation/pull/87763)
[#87740: 'Guncode Agony 4: The Great Projectile Purge' by SmArtKar at commit 4f1050b7a3](https://www.github.com/tgstation/tgstation/pull/87740)
[#87742: '[TM ONLY] Buffs jetpack/wing forces and stabilization greatly to see how major the subsystem chugging issue is' by SmArtKar at commit a6186c2da9](https://www.github.com/tgstation/tgstation/pull/87742)
[#87754: 'Batons have their stamina damage reduced by armor, get stun armor penetration' by necromanceranne at commit 697e66008b](https://www.github.com/tgstation/tgstation/pull/87754)
[#84280: 'Add ignition sound and roaring fire to atmos fire' by TheBoondock at commit 5eeee26473](https://www.github.com/tgstation/tgstation/pull/84280)

### Reproduction Steps:

Setup an emitter, probably the SM ones, Observe the BEAMS

**Comment by SmArtKar** [comment]
#87740, should be fixed? But leaving up because its a bit fucky
