### ISSUE TITLE
Floortile camo no longer works

### ISSUE THREAD

**Issue by K4rlox** [tgstation/tgstation#87961]
### Client Version:

515.1645

### Issue Summary:

floortile came no longer seem to work due to the fact players now have a faint shadow around them
![image](https://github.com/user-attachments/assets/aae9427a-69e0-4821-901d-02cfe2631461)

### Round ID:

[0](https://scrubby.melonmesa.com/round/0)

### Test Merge Information:

- [[TM ONLY] Buffs jetpack/wing forces and stabilization greatly to see how major the subsystem chugging issue is](https://www.github.com/tgstation/tgstation/pull/87742)
- [Batons have their stamina damage reduced by armor, get stun armor penetration](https://www.github.com/tgstation/tgstation/pull/87754)
- [Add ignition sound and roaring fire to atmos fire](https://www.github.com/tgstation/tgstation/pull/84280)
- [Guncode Agony 4: The Great Projectile Purge](https://www.github.com/tgstation/tgstation/pull/87740)

### Reproduction Steps:

1. get floortile camo from blackmarket
2. wear it
3. stand ontop of floortile
4. you are visible because of the faint shadow around you

**Comment by SmArtKar** [comment]
This is intentional, floortile camo always was a joke and never was meant to be functional

**Comment by LemonInTheDark** [comment]
(more then that it isn't really solvable, we don't have a good way of locally turning off AO outside of rendering a mob on the floor (which makes no sense)
