### ISSUE TITLE
Circuit camera bugs out on z level maps

### ISSUE THREAD

**Issue by moocowswag** [tgstation/tgstation#87989]
### Client Version:

515.1631

### Issue Summary:

I made a drone circuit to bomb people on wawa and the camera bugged out when the drone was not on the same z level as me and i could barely see anything (it shifted my view no longer centering the drone which was now halfway off screen)

### Round ID:

[242453](https://scrubby.melonmesa.com/round/242453)

### Test Merge Information:

- [[TM ONLY] Buffs jetpack/wing forces and stabilization greatly to see how major the subsystem chugging issue is](https://www.github.com/tgstation/tgstation/pull/87742)
- [Batons have their stamina damage reduced by armor, get stun armor penetration](https://www.github.com/tgstation/tgstation/pull/87754)
- [Add ignition sound and roaring fire to atmos fire](https://www.github.com/tgstation/tgstation/pull/84280)
- [Guncode Agony 4: The Great Projectile Purge](https://www.github.com/tgstation/tgstation/pull/87740)

### Reproduction Steps:

Make drone with camera on wawa.

use sec camera console to watch it

it goes down some stairs

can no longer see very well

go back up stairs

see fine again.

go back down stairs

bad shifted view again

**Comment by norsvenska** [comment]
Duplicate of #83943 I think

**Comment by moocowswag** [comment]
same visuals it is the same bug apparently.
