### ISSUE TITLE
each time i press succumb i want to succumb in real life

### ISSUE THREAD

**Issue by vertolodka** [tgstation/tgstation#87986]
### Client Version:

515.1642

### Issue Summary:

when i press succumb and green button i expect my character to die, like it worked before, but its not happening because instead of fixing the menu someone made another fucking menu (https://github.com/tgstation/tgstation/pull/87683)

### Reproduction Steps:

1 get crit. 
2 try to succumb the normal way.
3 nothing happens at all.

**Comment by mc-oofert** [comment]
thats bullcrap this literally worked previously fixing the bug would not break every other text input

**Comment by mc-oofert** [comment]
i have no clue what the original behavior was but the text input modals params["entry"] will return empty text that is: not null, istext returns 1, and is a falsey value
set_entry apparently just makes it null

**Comment by mc-oofert** [comment]
trimtext turns "" into null

**Comment by vertolodka** [comment]
tried to succumb without typing anything in round 242839 and it didn't work

**Comment by Ghommie** [comment]
Maybe the server hasn't updated, but that's unlikely and I'm not feeling like checking right away.

**Comment by vertolodka** [comment]
yea, server wasn't updated, tried it on local and it worked
