### ISSUE TITLE
wearing a beret (or one of a selection of other hats) gives you extreme hair loss

### ISSUE THREAD

**Issue by norsvenska** [tgstation/tgstation#87991]
### Client Version:

515.1642

### Issue Summary:

Following #87940, berets (among certain other hats) now add a mask to hide hair, to make the hair fit normally. However, for whatever reason, it cuts out too much hair, giving characters severe baldness.

I'm guessing people are aware of the issue (since Manuel did not have the PR active, I don't think. Sybil did, however.) but no issue report for it exists yet.

Some examples:
<details>
  <summary>Research director w/ wisp hairstyle</summary>
  
![image](https://github.com/user-attachments/assets/98b4f091-45fa-401d-a569-82a198282c1c)

![image](https://github.com/user-attachments/assets/fb09dbb8-2806-41ec-ac5c-405e732a59b4)

![image](https://github.com/user-attachments/assets/aa8b7182-e599-43e2-bf42-65492a19ccfa)

![image](https://github.com/user-attachments/assets/b444c5b3-4f92-48af-b091-82820faaf471)

</details>

<details>
  <summary>Head of personnel w/ high braid hairstyle</summary>
 
![image](https://github.com/user-attachments/assets/2056922c-5dcc-45bb-ba97-fcf2d8c9dbb2)

![image](https://github.com/user-attachments/assets/32396466-cdad-4c15-8911-af4698283562)

![image](https://github.com/user-attachments/assets/b2eeb207-cf66-4034-bda7-dabaab2e1263)

![image](https://github.com/user-attachments/assets/444d4862-1d42-4376-a5ea-8952ead6893d)

 </details>

### Test Merge Information:

N/A

### Reproduction Steps:

1. have hair
2. wear hat
3. instantly age 30 years

**Comment by Sadboysuss** [comment]
I'll try to fix it
