### ISSUE TITLE
Atmos fire is mostly invisible

### ISSUE THREAD

**Issue by Zeerum** [tgstation/tgstation#88009]
### Client Version:

515.1640

### Issue Summary:

Atmos and plasma fires do not render properly and are mostly invisible. 

### Round ID:

[242605](https://scrubby.melonmesa.com/round/242605)

### Reproduction Steps:

1. Fill a room with plasma
2. Ignite plasma

**Comment by LemonInTheDark** [comment]
![image](https://github.com/user-attachments/assets/b43449c2-bcd3-4782-a669-a3aae947b865)
![image](https://github.com/user-attachments/assets/f33ad51d-1d8f-4ca9-bd4f-72f81f09605d)

the icon state var was updated to match wallening work but the dmi was not similarly updated
