### ISSUE TITLE
rebar crossbows have 3 calibers and only 1 is actually relevant

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#88046]
### Client Version:

idk

### Issue Summary:

![image](https://github.com/user-attachments/assets/a524bdb9-e61e-4548-9699-25bd9a114c11)
wtf?
this should only use the rebar caliber

### Reproduction Steps:

open code/_DEFINES/projectiles.dm
weep

**Comment by SmArtKar** [comment]
projectile code be projectiling, man
