### ISSUE TITLE
Sentient Repairbot issues

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#88067]
### Client Version:

515.1646

### Issue Summary:

A couple things of note I've picked up on from my brief time playing repairbots:
There is nothing telling you that you have a limited amount of floor tiles, I ended up wasting so much time trying to replace floors with no popup saying I was out of tiles. Which is also annoying because you need to go ask someone for more. A counter or a slow internal synthesiser would go the extra mile.
You can build girders....and then do nothing with them, why? 
You don't have welding protection so you'll get flashbanged any time you try to weld something, I found this out by accident when I clicked on a vent by mistake
You can't really eject floor tiles you have so you're stuck with whatevers in the lineup

Obviously you can't expect every bot to work as flawlessly as its non sentient counterpart but they feel incredibly clunky to play rn

### Round ID:

[242885](https://scrubby.melonmesa.com/round/242885)

### Reproduction Steps:

Just...play repairbot, you'll get the jist after fiddling around a bit yourself

**Comment by DaydreamIQ** [comment]
Adding on if I find more things but one of note is that there's no flavour text other than a placeholder
![image](https://github.com/user-attachments/assets/3560c8de-65dd-4589-9e51-6a25c736529b)

**Comment by Ergovisavi** [comment]
I believe if you click on a disposal unit your welder gets flushed and there's no way of getting it back.

**Comment by Ben10Omintrix** [comment]
very funny but also cursed. anyways im working on a patch PR which will hopefully be done by tomorrow or the day after. if u catch anymore bugs be sure to report them here or through a seperate issue
