### ISSUE TITLE
Lightmode issue chat box is now eye cancer grey (UI problem)

### ISSUE THREAD

**Issue by JusticeGoat** [tgstation/tgstation#88064]
### Client Version:

515.1645

### Issue Summary:

When the game loads now it has this ugly grey overlay on my chat window. I have played with lightmode since 2014 i don't want to change to dark mode, now i have this horrible grey tint to my chat and i cant turn it off and have it white.....
![fsdsfdled](https://github.com/user-attachments/assets/eee0cfd1-8676-4ce2-bd4c-90607b37d4df)

Yes i cleared cache and all it did was delete my chat tabs.

### Reproduction Steps:

join the server with light mode on.

**Comment by optimumtact** [comment]
@tgstation/commit-access

**Comment by LemonInTheDark** [comment]
> I can't find any PR that corresponds to this, it is making me want to fight someone.
> 
> ![image](https://private-user-images.githubusercontent.com/7897664/388338219-c77e196b-6c60-4b6b-9553-20228c3e03d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNjUyMzUsIm5iZiI6MTczMjE2NDkzNSwicGF0aCI6Ii83ODk3NjY0LzM4ODMzODIxOS1jNzdlMTk2Yi02YzYwLTRiNmItOTU1My0yMDIyOGMzZTAzZDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjFUMDQ1NTM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWZiY2FmNWVjN2M0MTQwMTM0YmM4ZmU3NWRkZjIzN2YwYTA4OWMxOWIzMmEwNzBiNGE3NmUwZWY5MjdjZTQ0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.tBDEM8sVsXoDX4kpwMjWUYUqHq5q7JPO4HoKtu3hKSI) there's also a new yellow highlight around the buckled "pop-up" that I can't find a PR for -- I'm wondering if it's related? I don't know what PR I'd blame, the only style related one recently was #87964

#87902

**Comment by Sadboysuss** [comment]
Closed by https://github.com/tgstation/tgstation/pull/88069
