### ISSUE TITLE
Ablative trenchcoat doesn't reflect emitter blasts

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#88073]
### Issue Summary:

Title

### Reproduction Steps:

1. Equip ablative trenchcoat
2. Be shot with emitter
3. Ow

**Comment by Jackal-boop** [comment]
what the fuck the projectile is fine but somehow the emitter itself is eating the ability for a projectile to be reflected

**Comment by SmArtKar** [comment]
Because emitters are schizocode and don't handle projectiles properly.
