### ISSUE TITLE
Light mode fancy chat box is grey and ugly on Manuel only

### ISSUE THREAD

**Issue by Isratosh** [tgstation/tgstation#88093]
### Client Version:

515.1641

### Issue Summary:

Manuel
![](https://i.imgur.com/isguQtq.png)

Terry
![](https://i.imgur.com/84pa57M.png)

Sybil is the same as Terry

Terry TMs at the time were 87742 87754 87740
No TMs on Sybil

neither fix-chat, clearing BYOND and internet explorer cache, nor swapping to dark mode and back resolves it
but using fix-chat and selecting "no, switch to old ui" does resolve it, until you reload fancy chat
![](https://i.imgur.com/wgpPRp3.png)

### Round ID:

[243001](https://scrubby.melonmesa.com/round/243001)

### Test Merge Information:

- [Guncode Agony 4: The Great Projectile Purge](https://www.github.com/tgstation/tgstation/pull/87740)
- [Adds meowing and purring back for felinids](https://www.github.com/tgstation/tgstation/pull/87156)

### Reproduction Steps:

1. Connect to Manuel

**Comment by Sadboysuss** [comment]
Wait for it to update

**Comment by basarbyz** [comment]
how did you fix this?

**Comment by Sadboysuss** [comment]
> how did you fix this?

https://github.com/tgstation/tgstation/issues/88064
