### ISSUE TITLE
Chainsaw troubles

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#88105]
### Issue Summary:

- Turned off chainsaw in your hand doesn't show on your character sprite
- turning on a chainsaw plays an extra unrelated sound

### Reproduction Steps:

See issue summary

**Comment by necromanceranne** [comment]
Consequence of it using transforming now I think

**Comment by Sk1Wass3r** [comment]
also chainsaw arms that are turned on don't show their sprite, only when they're off
