### ISSUE TITLE
emitters have no trail or projectile tracer

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#88106]
### Client Version:

515.1646

### Issue Summary:

title

### Round ID:

[243041](https://scrubby.melonmesa.com/round/243041)

### Test Merge Information:

- [Guncode Agony 4: The Great Projectile Purge](https://www.github.com/tgstation/tgstation/pull/87740)
- [Adds meowing and purring back for felinids](https://www.github.com/tgstation/tgstation/pull/87156)

### Reproduction Steps:

look at an emitter firing

**Comment by SmArtKar** [comment]
Interestingly enough this only happens on roundstart mapped-in emitters ***on live***. Locally they work just fine and so do they when build with a circuitboard/flatpacker

**Comment by SmArtKar** [comment]
They do have one, its just ***hidden beneath the floor*** due to planecube shenanigans. Fuck?
