### ISSUE TITLE
Unable to start surgery 

### ISSUE THREAD

**Issue by JohnHenryEton** [tgstation/tgstation#88134]
### Client Version:

515.1641

### Issue Summary:

Some people seem to get into a state where surgery cannot be started on them by anyone.

### Round ID:

[243121](https://scrubby.melonmesa.com/round/243121)

### Test Merge Information:

- [Guncode Agony 4: The Great Projectile Purge](https://www.github.com/tgstation/tgstation/pull/87740)
- [Adds meowing and purring back for felinids](https://www.github.com/tgstation/tgstation/pull/87156)

### Reproduction Steps:

I'm not sure how to reproduce it, but it can start midway through round.
In this round I was able to perform surgery on the clown, then later when the clown came back nobody in medical could start surgery on them.

**Comment by mozi-h** [comment]
Should get fixed by #88099?
