### ISSUE TITLE
Wawastation's Solar arrays have missing wires under the solar panel tiles.

### ISSUE THREAD

**Issue by ClingFoil** [tgstation/tgstation#88138]
### Client Version:

515.1646

### Issue Summary:

Wawastation's Solar arrays has missing wires under solar panel tiles which are under the already placed solar panels. This seems like a oversight as this is one of the only stations that have some missing wires under tiles. This is found in both north side arrays. Also on the south west side there is a missing wire under the SMES.

### Test Merge Information:

[bb697ae67fb1f41bd342ea4eef27c2a1ffdd3a9a](https://www.github.com/tgstation/tgstation/commit/bb697ae67fb1f41bd342ea4eef27c2a1ffdd3a9a)

### Reproduction Steps:

Both north solar arrays have missing wires under some of the solar panel tiles which are under the solar panels themselves.

**Comment by mc-oofert** [comment]
im pretty sure youre supposed to fix the cables because the arrays are supposed to be busted up
