### ISSUE TITLE
Maint fridge didnt save mea from nuke

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#88158]
### Issue Summary:

Fridges are suposed to save you from nukes because of indana jones. But it didn't do ti. It was maitnenance fridfge, though.

![image](https://github.com/user-attachments/assets/5e3d192f-682a-4c1c-92ae-92e62882f1cc)

### Reproduction Steps:

1. Nuke
2. Maint fridge
3. Go in
4. Die

**Comment by SmArtKar** [comment]
If the freezer had been blown up before, even a lil bit, it is no longer counts for nuke protection
