### ISSUE TITLE
Turning into a Gondola in the Bitrunning Domain breaks the connection to your original body

### ISSUE THREAD

**Issue by Justice12354** [tgstation/tgstation#88156]
### Client Version:

515.1646

### Issue Summary:

Turning into a Gondola in the Gondola Asteroid Bitrunning Domain breaks the connection to your original body. You can no longer return to your body through the ladder, and the disconnect alert pop-up does not show up

### Round ID:

[243239](https://scrubby.melonmesa.com/round/243239)

### Test Merge Information:

#87742
#87754
#87740

### Reproduction Steps:

Go into the Bitrunning Domain
Eat Gondola Meat
Become a Gondola
Figure out you can't return to your body
Ahelp

**Comment by OuroborusReporter** [comment]
Dup of #88116 . And also possibly #88126 . Stupid complicated game
