### ISSUE TITLE
Slimes can still attack and latch on to you while frozen into a block of ice

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#88185]
### Client Version:

515.1637

### Issue Summary:

#82176 made it so that slimes freeze into a solid block when cold enough. Despite being frozen in there and we're out here, they can still attack you, and can latch onto you to feed, dragging their ice block with them

![Screenshot 2024-11-24 151503](https://github.com/user-attachments/assets/ed9bce2c-bede-4658-b290-259476d2e94d)
Hard to see, but my corpse is underneath the lower ice block

Unsure if this is intended behavior or not, the block of ice interaction always feels a little bit buggy, but ided during the setup for a gimmick tot round, so you're getting a bug report about it. If this is intended I guess I'll just take my lumps   ̶(̶a̶n̶d̶ ̶b̶l̶a̶m̶e̶ ̶t̶h̶e̶ ̶d̶u̶m̶b̶a̶s̶s̶ ̶a̶s̶s̶i̶s̶t̶a̶n̶t̶ ̶w̶h̶o̶ ̶w̶e̶n̶t̶ ̶i̶n̶t̶o̶ ̶t̶h̶e̶ ̶x̶e̶n̶o̶b̶i̶o̶ ̶s̶e̶c̶t̶i̶o̶n̶ ̶i̶n̶ ̶h̶i̶l̶b̶e̶r̶t̶ ̶d̶e̶l̶t̶a̶r̶u̶n̶e̶'̶s̶ ̶l̶a̶b̶,̶ ̶j̶e̶s̶u̶s̶ ̶C̶H̶R̶I̶S̶T̶ ̶m̶a̶n̶ ̶t̶h̶e̶r̶e̶'̶s̶ ̶n̶o̶t̶h̶i̶n̶g̶ ̶i̶n̶ ̶t̶h̶e̶r̶e̶ ̶f̶o̶r̶ ̶y̶o̶u̶ ̶b̶u̶t̶ ̶d̶e̶a̶t̶h̶)̶

### Round ID:

243357

### Test Merge Information:

- [Adds meowing and purring back for felinids](https://www.github.com/tgstation/tgstation/pull/87156)

### Reproduction Steps:

1. Kite a slime attacking you out into space, assuming you'd be safe or that it'd die fast enough to not kill you
2. See it freeze into a solid block of ice
3. Still get your ass beat to death by it

**Comment by MrMelbert** [comment]
I was looking at this but as it turns out being frozen doesn't stop humans from attacking, let alone slimes, so I guess this is technically not a bug
