### ISSUE TITLE
Transferring a brain to a new body doesn't work

### ISSUE THREAD

**Issue by pbj567** [tgstation/tgstation#88189]
### Client Version:

515.1636

### Issue Summary:

If your brain is put into a new body you are not put in the body.

### Round ID:

[243385](https://scrubby.melonmesa.com/round/243385)

### Reproduction Steps:

1. Take your brain out of your body
2. Put it in a new body
3. Have the body revived
4. You are not in the body

**Comment by pbj567** [comment]
Maybe this is related to [this issue](https://github.com/tgstation/tgstation/issues/88187)? I think it's an issue with putting someone back into a body once they've been taken out

**Comment by ifZoey** [comment]
It seems like it also probably has something to do with that sometimes people can still be alive even without a brain. Was doing tests with Pun Pun and he was still walking, laughing, and dancing, while his brain was on the table.
