### ISSUE TITLE
it is possible to break a grinder by removing the beaker during operation

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#88180]
### Client Version:

idk forgor

### Issue Summary:

if you remove the beaker while the grinder is grinding it breaks and never stops operating

### Round ID:

downstream

### Reproduction Steps:

1. put stuff in grinder
2. have another dude open the radial
3. start grinding
4. dude presses eject
5. it becomes unresponsive

**Comment by mc-oofert** [comment]
> Tested on local and It's not possible to remove the beaker by hand while It's operating.
> 
> This is a downstream specific issue 

It absolutely is possible

**Comment by mc-oofert** [comment]
I'm not sure right now but it's probably via the radial menu

**Comment by SyncIt21** [comment]
> I'm not sure right now but it's probably via the radial menu

In the video i left clicked as well to try to access he radial menu & it did not show up

**Comment by mc-oofert** [comment]
with two people

**Comment by Sadboysuss** [comment]
Please give more concise reproduction steps

**Comment by mc-oofert** [comment]
literally just add the same checks to the end of the proc with the radials

**Comment by mc-oofert** [comment]
desc fixed

**Comment by SyncIt21** [comment]
It's still not possible to reproduce the issue on local even with your reproduction steps.

The radial menu has a callback which get's invoked after the user has made their choice 
https://github.com/tgstation/tgstation/blob/f290bd0f2df82d2ff2dd3730648f5839952504c6/code/modules/reagents/chemistry/machinery/reagentgrinder.dm#L387

And this callback invalidates the choice if the machine is operating, so the 2nd dude cannot eject the beaker
https://github.com/tgstation/tgstation/blob/f290bd0f2df82d2ff2dd3730648f5839952504c6/code/modules/reagents/chemistry/machinery/reagentgrinder.dm#L415

Until you get video demonstration of the issue upstream I suggest you report the issue downstream
