### ISSUE TITLE
fish tank shows your body parts as props

### ISSUE THREAD

**Issue by memecraft22** [tgstation/tgstation#88197]
### Client Version:

515.1642

### Issue Summary:

when you hold the fish tank in your hand it shows everything you have on you in the props menu 

### Round ID:

[243435](https://scrubby.melonmesa.com/round/243435)

### Test Merge Information:

- [[TM ONLY] Buffs jetpack/wing forces and stabilization greatly to see how major the subsystem chugging issue is](https://www.github.com/tgstation/tgstation/pull/87742)

### Reproduction Steps:

get a fish tank and open the control and feed menu while its in your hands

**Comment by Ghommie** [comment]
fixed by #88160
