### ISSUE TITLE
Exploding someone during organ manipulation summons new organs.

### ISSUE THREAD

**Issue by lizardqueenlexi** [tgstation/tgstation#88227]
### Client Version:

515.1641

### Issue Summary:

When an explosion goes off by someone who is currently opened for organ manipulation, randomized organs will spawn from nowhere. This appears to grant easy access to implants, mutant organs, and more with nothing more than a morgue corpse and some water-potassium grenades.

![image](https://github.com/user-attachments/assets/c04d07b1-d112-4d78-8b36-41958a4fe866)

Caused by the interaction between #87774 and the effect explosions have on fishing spots.

### Reproduction Steps:

1. Open a human up for organ manipulation, up to the step where you can actually manipulate organs.
2. Set off your favorite explosive next to or on them.
3. Behold as several random organs spontaneously congeal into being, while your victim's organs stay put.

**Comment by Time-Green** [comment]
@Ghommie ?!!!?!!

**Comment by timothymtorres** [comment]
Bizzaro organ bug.
