### ISSUE TITLE
Atmos Turbine PSU receives less than half of Turbine's generated power

### ISSUE THREAD

**Issue by MatrixOne500** [tgstation/tgstation#88231]
### Client Version:

515.1646

### Issue Summary:

The Atmos Turbine outputs less than half of its stated power.
Screenshot from Manuel round 243523 on Tramstation.
**Power generated by turbine:** 220 kW
**Power available in PSU and sent to station:** only 100 kW.
That was very relevant because the SM blew up, and we needed power. Screenshot:
![rip turbine](https://github.com/user-attachments/assets/b485e1ba-fa1b-4ca4-8bd4-be3c3b41f671)

I've also reproduced this same issue on localhost on Birdshot.

A potential source of this problem could be the energy unit conversion PR that turned all energy units into joules:
https://github.com/tgstation/tgstation/pull/81579

### Round ID:

[243523](https://scrubby.melonmesa.com/round/243523)

### Test Merge Information:

- [Adds meowing and purring back for felinids](https://www.github.com/tgstation/tgstation/pull/87156)

### Reproduction Steps:

1. Set up the turbine.
2. Note the turbine's generated power in the "Gas Turbine Control Computer."
3. Compare it to the PSU "Input: Available" power.

**Comment by distributivgesetz** [comment]
@Pickle-Coding

**Comment by SyncIt21** [comment]
This isn't a bug with the power generated by the turbine but how it's displayed on the UI
 https://github.com/tgstation/tgstation/blob/4a6e11d3612a68a0bc75e4a44e2d686699d79e6f/tgui/packages/tgui/interfaces/TurbineComputer.tsx#L117

Rather than this constant conversion we should convert energy to power in the backend before sending it to the UI using the correct formula

**Comment by MatrixOne500** [comment]
Thanks for clarifying the issue! It's a bit sad because it implies a base turbine can only do 100kW so it's equivalent to about one solar, I wish it'd get a slight buff. I was hoping resolving the issue would get it to generate 220kW as the UI stated but oh well
