### ISSUE TITLE
Clarke drill doesn't seem to work

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#88277]
### Client Version:

515.1646

### Issue Summary:

![image](https://github.com/user-attachments/assets/b5f1cca9-b763-4d30-95ba-4382fdf72ff6)
This is me hugging a wall trying to drill through with no luck. It was a diamond drill not the standard one

### Round ID:

[243724](https://scrubby.melonmesa.com/round/243724)

### Reproduction Steps:

Build a Clarke
Equip a diamond drill
Push into wall
No digging

**Comment by moocowswag** [comment]
likely https://github.com/tgstation/tgstation/pull/87936 related

**Comment by SmArtKar** [comment]
Drill needs to be activated first, which is a weird decision on itself, plus checks for drilling are only ran after you try to drill which is even weirder.
