### ISSUE TITLE
the red lines around your screen disappear when injured sometimes

### ISSUE THREAD

**Issue by kuricityy** [tgstation/tgstation#88278]
### Client Version:

515.1636

### Issue Summary:

When you get a wound, (etc second, third, catastrophic burns, weeping avulsions, arm breaks) sometimes the red lines on your screen disappear, as if you had the numb quirk. 
![image](https://github.com/user-attachments/assets/f5c64aac-d7ac-4550-9998-9d782493fc32)
image has me with second degree burns, no numb quirk, and near critical with no red lines.

### Round ID:

[243730](https://scrubby.melonmesa.com/round/243730)

### Reproduction Steps:

Get a wound
Red lines go bye bye

**Comment by NoHaxJustPi** [comment]
caused by #88029, which made TRAIT_ANALGESIA (which the Determination from a wound gives) disable the damage overlay
