### ISSUE TITLE
Lionhunter's rifle's homing shot doesn't actually home at target's position

### ISSUE THREAD

**Issue by MX0739** [tgstation/tgstation#88293]
### Client Version:

515.1646

### Issue Summary:

Lionhunter rifle's homing shot doesn't home at target's position, instead it targets 1 tile north and 1 tile east of the target

![homing](https://github.com/user-attachments/assets/15b73b5a-7768-4e34-b7f6-413841bb4aac)

I also tested this with the smartgun, seems like it has the same issue but i don't really sure

### Reproduction Steps:

1. Aquire a Lionhunter rifle
2. Shoot at someone with homing shot
3. The bullet homes not where it should

**Comment by Sadboysuss** [comment]
cc @SmArtKar
