### ISSUE TITLE
Lunar Parade causes a frankly heinous amount of noise when it's used

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#88292]
### Issue Summary:

It sounds like Lunar Parade is playing the music every time it moves, so it ends up being less a cool little thematic song and more hell noise.

https://streamable.com/1n2yg8

### Reproduction Steps:

1) Use Lunar Parade
2) Expect it to not annihilate my ears
3) It does it anyway

**Comment by TheVekter** [comment]
I don't know how to fucking embed streamable videos on here I'm an old man also this goes in the bin

**Comment by Rex9001** [comment]
I've bashed my head trying to fix this but I never managed it, best of luck trying to fix this one, its related to soundloops and how they work but I couldnt figure those out proper enough to fix it
