### ISSUE TITLE
NPC slimes without players in them can talk in chat just after they die.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#8829]
![](http://i.imgur.com/Mkc6EiO.png)

This was NOT a player, and the corpse was destroyed right after.

**Comment by phil235** [comment]
Weird, handle_speech is called only when the slime is alive.

**Comment by Incoming5643** [comment]
only happens when the slime attempts to speak in the same moment as it dies

**Comment by Miauw62** [comment]
Probably related to the bug where people can talk when they're just cloned,
which SHOULD be fixed but is such an edge case there's no way to be sure.
Op 8-apr.-2015 17:41 schreef "Incoming5643" <notifications@github.com>:

**Comment by Kelenius** [comment]
Just call it a feature.

**Comment by tedward1337** [comment]
Fixed?

**Comment by phil235** [comment]
Likely fixed, my guess is the slime was dying mid-Life() and since we used to not check the mob's stat after each action inside Life() the slime could die from exposition to high temperature and then talk immediately which would be sent to dead chat.
