### ISSUE TITLE
armless humans can point

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#88327]
### Issue Summary:

we have this but aren't using it with the point button https://github.com/tgstation/tgstation/blob/bc2a55a666b3a0b047222f552761cf6e09c4ef6a/code/modules/mob/living/emote.dm#L289

### Reproduction Steps:

try pointing without arms

**Comment by Jacquerel** [comment]
I think carbons should be able to point with any number of limbs but if they have no arms it says they use a leg and if they have no arms or legs it says they give a meaningful glance and if they have no eyes it says they gesture with their nose.

**Comment by Sadboysuss** [comment]
> I think carbons should be able to point with any number of limbs but if they have no arms it says they use a leg and if they have no arms or legs it says they give a meaningful glance and if they have no eyes it says they gesture with their nose.

yeah I like that
