### ISSUE TITLE
Lings Regenerate replaces your organs if you used infusion in genetics

### ISSUE THREAD

**Issue by Graybear98** [tgstation/tgstation#88342]
### Client Version:

515.1642

### Issue Summary:

I had an infusion with carp. I fought in space and got injured, then I pressed regenerate ability and found that I could no longer move in space without a jetpack, and I also started taking pressure damage

### Round ID:

-

### Reproduction Steps:

1. Got carp infusion
2. Press regenerate
3. Realize that you have lost all your new organs

**Comment by necromanceranne** [comment]
yeah, sorry, this is working as intended.

https://github.com/tgstation/tgstation/blob/a5471b31ce6360d1c6003ced4ce5c204469fb736/code/modules/antagonists/changeling/powers/regenerate.dm#L19

https://github.com/tgstation/tgstation/blob/a5471b31ce6360d1c6003ced4ce5c204469fb736/code/__DEFINES/mobs.dm#L947

It doesn't just heal organs, it completely refreshes those organs. This is closer to a feature request than actually a bug.
