### ISSUE TITLE
Several Drink Containers have their drink-type coded into the container itself

### ISSUE THREAD

**Issue by OrionTheFox** [tgstation/tgstation#88351]
### Client Version:

515.1646

### Issue Summary:

Some drink containers have their drink 'type' coded into the container itself, making it so drinks consumed through it are also given that type.

![image](https://github.com/user-attachments/assets/5799fe98-a305-4ec5-a83e-f20965877680)

`It is alcohol.` says the empty bottle...
Were this filled with something non-alcoholic and drank, it would still be treated like alcohol was consumed, i.e. for species taste mood events

### Reproduction Steps:

1. Spawn a bunch of drink containers (emptying soda cans _(which are tagged as sugar)_ or using the aforementioned alcoholic empty glass bottles)
2. Fill them with drinks that aren't the given types (water is a good catch-all since it's none of the types that would be relevant)
3. The drink is considered that drink type when consumed, even when the reagent is not the given type

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/3790cff6a0dfa229fb28673018a2ab74b083c04a/code/modules/reagents/reagent_containers/cups/_cup.dm#L27-L31

**Comment by timothymtorres** [comment]
A couple other notes I observed from code diving:

- `drink_type` is cosmetic and only used for the examine message. It doesn't affect mood/status effects
- The large empty bottle is the parent class for all alcohol bottles. Meaning you would have to change like 50 different drinks to inherit the `ALCOHOL` drink type flag.

**Comment by OrionTheFox** [comment]
> A couple other notes I observed from code diving:
> 
>     * `drink_type` is cosmetic and only used for the examine message. It doesn't affect mood/status effects
> 
>     * The large empty bottle is the parent class for all alcohol bottles. Meaning you would have to change like 50 different drinks to inherit the `ALCOHOL` drink type flag.

Oh lord I think downstream has set up a mechanical thing (food prefs) with this cosmetic variable 🤮
