### ISSUE TITLE
wendigo is unplayably laggy

### ISSUE THREAD

**Issue by LePiromano** [tgstation/tgstation#88395]
### Client Version:

515.1643

### Issue Summary:

in any of the main servers fighting against the wendigo becomes impossible when it uses some of its spiral projectile attacks

https://github.com/user-attachments/assets/c135d0a3-9554-4bd3-8925-39de76d8d603

### Round ID:

[244705](https://scrubby.melonmesa.com/round/244705)

### Reproduction Steps:

fight the wendigo

**Comment by SmArtKar** [comment]
Possibly an issue with amount of animate()s called, as wendigo's projectiles use homing for their spiral logic and thus call it every 32 pixels/every tick? The ping seems to absolutely skyrocket

**Comment by LePiromano** [comment]
the lag instantly dissipates when the projectiles dissappear

**Comment by Namwty** [comment]
Feature + Skill issue

But jokes aside Wendigo's spiral attack is especially absurdly laggy.
