### ISSUE TITLE
Can lizards hiss? Or can't they anymore these days?

### ISSUE THREAD

**Issue by Artemchik542** [tgstation/tgstation#88423]
### Issue Summary:

https://github.com/tgstation/tgstation/blob/3ae424ccdb0f202b72e07b2ed877d03830afec57/code/modules/mob/living/carbon/human/species_types/lizardpeople.dm#L117C1-L119C1
```byond
/datum/species/lizard/get_hiss_sound(mob/living/carbon/human/lizard)
	return 'sound/mobs/humanoids/lizard/lizard_hiss.ogg'
```
**File Not Found** `sound/mobs/humanoids/lizard/lizard_hiss.ogg`

### Reproduction Steps:

look in Issue Summary and then in actual code

**Comment by SmArtKar** [comment]
Is this a downstream issue? The sound exists and hissing works just fine

**Comment by Sadboysuss** [comment]
https://github.com/tgstation/tgstation/blob/master/sound/mobs/humanoids/lizard/lizard_hiss.ogg

???

**Comment by Artemchik542** [comment]
I didn't see that git was looking in a specific commit again, not the latest code. Sorry for misinformation.
