### ISSUE TITLE
Newtonian physics: approaching a corner will slow you down

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#88460]
### Client Version:

515.1642

### Issue Summary:

https://github.com/user-attachments/assets/47a0df5f-4bc4-46bf-956a-d401c00f78aa

### Reproduction Steps:

- be in 0 gravity
- speed up to max speed
- approach a corner
- be slowed

**Comment by SmArtKar** [comment]
Closed by #88450 actually
