### ISSUE TITLE
one cannot simply place a toolbox on a table

### ISSUE THREAD

**Issue by norsvenska** [tgstation/tgstation#88484]
### Client Version:

515.1647

### Issue Summary:

When I try to place a toolbox on a table, it just spits random tools out. I can only place the toolbox down after emptying it of all tools. I tried left clicking, right clicking, combat mode on and off, nothing worked until it was emptied. Throwing it worked fine.

### Round ID:

[245241](https://scrubby.melonmesa.com/round/245241)

### Test Merge Information:

None

### Reproduction Steps:

1. have the desire to set your toolbox on a table
2. click on table
3. cry

**Comment by SyncIt21** [comment]
Duplicate #88446
