### ISSUE TITLE
Wrapping wounds with gauze doesnt work.

### ISSUE THREAD

**Issue by Sonnzer** [tgstation/tgstation#88504]
### Client Version:

515.1647

### Issue Summary:

Title.

### Round ID:

[245501](https://scrubby.melonmesa.com/round/245501)

### Reproduction Steps:

1. Get wound. (I had a burn)
2. Try to wrap with medical gauze
3. No wrap
4. mfw infection

**Comment by MrMelbert** [comment]
I blame skews or something

![image](https://github.com/user-attachments/assets/1e304138-e853-4ca5-ac63-a7fc5eb971cb)
