### ISSUE TITLE
N-SPECT scanners cannot actually scan people

### ISSUE THREAD

**Issue by restedwaves** [tgstation/tgstation#88515]
### Client Version:

515.1645

### Issue Summary:

despite stating it can scan people for contraband in the description it cannot do so

### Round ID:

[245545](https://scrubby.melonmesa.com/round/245545)

### Reproduction Steps:

attempt to scan someone with it.
bap them with it instead

tests have been using right and left click on someone aswell as alt clicking on living and corpses and one living person who was cuffed

**Comment by Sadboysuss** [comment]
https://github.com/tgstation/tgstation/pull/87882

Description needs correction

**Comment by OrionTheFox** [comment]
Easy peasy
