### ISSUE TITLE
Spraypaint appears to only alter hue, not apply a multiply filter.

### ISSUE THREAD

**Issue by dalmationer** [tgstation/tgstation#88533]
### Client Version:

515.1647

### Issue Summary:

In the round above, I attempted to spraypaint a table to decorate the bar. Instead of multiplying the table to make it appear wooden, it hue shifted but did not affect the value of the table.

### Round ID:

[245641](https://scrubby.melonmesa.com/round/245641)

### Reproduction Steps:

use a spraycan on an object.

**Comment by dalmationer** [comment]
ah, I just saw that #88201 altered the behaviour of the spray can... It still does not appear to work well for low-saturation low brightness colours, like the brown I like to use for tables

**Comment by mc-oofert** [comment]
couldnt you just make an actual wooden table though

**Comment by Likteer** [comment]
@dalmationer use rmb to get the old behaviour

**Comment by SmArtKar** [comment]
> ah, I just saw that #88201 altered the behaviour of the spray can... It still does not appear to work well for low-saturation low brightness colours, like the brown I like to use for tables

RMB has a similar (slightly better) effect to how spraycans functioned prior to this change - use tham

**Comment by LSommers** [comment]
> > ah, I just saw that #88201 altered the behaviour of the spray can... It still does not appear to work well for low-saturation low brightness colours, like the brown I like to use for tables
> 
> RMB has a similar (slightly better) effect to how spraycans functioned prior to this change - use that

The RMB function _over_-saturates from what I've seen- A white item using the new behaviour won't be colored at all on LMB, but RMB oversaturates it. (IE if you try to paint a chef hat light tan LMB stays white and RMB makes it very yellow)

**Comment by IgiariValkyr** [comment]
> > > ah, I just saw that #88201 altered the behaviour of the spray can... It still does not appear to work well for low-saturation low brightness colours, like the brown I like to use for tables
> > 
> > 
> > RMB has a similar (slightly better) effect to how spraycans functioned prior to this change - use that
> 
> The RMB function _over_-saturates from what I've seen- A white item using the new behaviour won't be colored at all on LMB, but RMB oversaturates it. (IE if you try to paint a chef hat light tan LMB stays white and RMB makes it very yellow)

Then make it a lighter color. Instead of having something a solid yellow, make the color you’re spraying on more pale towards white to get a more subtle fade. This is a technique from the olden color days to make something appear “slightly less vibrant”
