### ISSUE TITLE
Wirecutters don't cut cables or zipties off of people

### ISSUE THREAD

**Issue by pbj567** [tgstation/tgstation#88558]
### Client Version:

515.1646

### Issue Summary:

If you try to cut someone's zipties/cablecuffs off you just snip them.

### Round ID:

[245863](https://scrubby.melonmesa.com/round/245863)

### Reproduction Steps:

1. find a guy cuffed by cables or zipties
2. try to cut them off
3. you snip him with your wirecutters :(

**Comment by OuroborusReporter** [comment]
Just to check, you were RIGHT clicking them, correct? Left clicking just gives them a little lovesnip, right click cuts ties. I know it worked 2 days ago, at least

**Comment by pbj567** [comment]
oh my god i swear left click used to cut cuffs
