### ISSUE TITLE
Lead-acid batteries have the charge of a battery despite functioning as a cell

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#88573]
### Client Version:

515.1647

### Issue Summary:

Lead-acid batteries are actually cells, not batteries (megacells). Despite this they have the max charge of a battery. As a result they have a max_charge of 1000000, making them one of the most powerful cells you can get (And surpassing bluespace cells significantly).

Could probably be fixed either by changing maxcharge to the cell equivalent, or by changing it from a cell into a battery

### Reproduction Steps:

Acquire lead-acid battery. Note that you can use it as a cell, despite it having the capacity of a battery

**Comment by Livrah** [comment]
It's also a rare random spawn
