### ISSUE TITLE
Large mob's toggle seethrough ability moves their sprite up, makes space dragons invisible

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#88579]
### Client Version:

515.1647

### Issue Summary:

Toggle seethrough should make it so you're able to see stuff under your large sprite by making your sprite transparent only to yourself. For some reason, it now moves your sprite up a tile from where you really are. Furthermore, space dragons (Once they have chosen a color, so probably some issue with whatever the greyscale color system is) turn entirely invisible (as opposed to slightly transparent). Both of these effects are observable even by others, not just yourself.

### Round ID:

[245932](https://scrubby.melonmesa.com/round/245932)

### Reproduction Steps:

Toggle Seethrough as a xeno queen or space dragon and your sprite will move upwards.

Toggle Seethrough as a space dragon after having chosen a color and you will be invisible.

Bystanders can observe both of these effects.

**Comment by Isratosh** [comment]
#88266 perhaps?
