### ISSUE TITLE
Follow produces duplicate names with cyborgs.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#8858]
If a new cyborg is made and it is renamed, you will find both what it used to be named and its new name listed. Two happened simultaneously where "lucky 7" was also "default cyborg-208" and "u.s.e.l.e.s.s." was also "default cyborg-472". Both were engineering cyborgs.

**Comment by tedward1337** [comment]
This been fixed?

**Comment by phil235** [comment]
looks like it
