### ISSUE TITLE
Character Preferences: Necktie Bug

### ISSUE THREAD

**Issue by Cassavanova** [tgstation/tgstation#88641]
### Client Version:

515.1647

### Character Preferences: Necktie Bug

Changing your necktie to untied in character preferences wont let it change back to tied/bowtie

I can still tie it when i spawn in-game, but it's a tiny bit annoying and i need to go to an AutoDrobe Dispenser to get a bowtie.

![Bug](https://github.com/user-attachments/assets/b7c18f15-f1f4-4db5-a0ec-0d36cdd2ee2b)

### Round ID:

[246281](https://scrubby.melonmesa.com/round/246281)

### Reproduction Steps:

On any map, round type, etc:

1. Open Character Preferences under Loadout under Neckwear
2. Wear a Necktie (colorable)
3. Click modify Color Configuration
4. Under Icon States change it to tie_greyscale_untied
5. Change it back to either tie_greyscaled_tied or bowtie_greyscale
6. Realize you can't change it back to either tie_greyscaled_tied or bowtie_greyscale

**Comment by MrMelbert** [comment]
Not a bug, those "icon states" are just meant for previewing, they're not actually implemented to do anything
