### ISSUE TITLE
Can't respawn after round-end

### ISSUE THREAD

**Issue by freerealestate** [tgstation/tgstation#8865]
Admins are currently investigating some grief on singulo at round-end. They enabled respawn so players have something to keep them occupied while they investigate, but it's impossible to enter the game after round-end.

**Comment by Jalleo** [comment]
Old code

**Comment by Cheridan** [comment]
Not a bug, the code is working how it was meant to. It's just that old functionality isn't desired anymore.

**Comment by Amnestik** [comment]
Well, it's an issue.

**Comment by optimumtact** [comment]
Not a bug, should be requested in ideas or feedback forum
