### ISSUE TITLE
Manipulators will ignore backpack item/size limit

### ISSUE THREAD

**Issue by combustor** [tgstation/tgstation#88671]
### Issue Summary:

You can place any item into a backpack by using a manipulator.

### Reproduction Steps:

1. Get a manipulator
2. Make it drop its' items to storage, put a backpack at the output side
3. Put an item in front of it and it'll insert it into the backpack, no matter how big the item is.
![image](https://github.com/user-attachments/assets/c3148ddd-156c-49a7-bd40-82fd8ba8ef66)

**Comment by necromanceranne** [comment]
The big manipulator fiasco continues

**Comment by DustanHache** [comment]
a true bag of holding

**Comment by GreytideSkye** [comment]
Big Backpack is in the pocket of Big Manipulator.
