### ISSUE TITLE
Smartfridge tile UI number click dumps all items

### ISSUE THREAD

**Issue by MTandi** [tgstation/tgstation#88672]
### Issue Summary:

#85970 removed the pop-up for putting the desired amount to vend, overlooking the tile version of this UI.

Now people just dump all fruits by accident when they click on the numbers in the tile UI and items are left laying around, causing lag for players in proximity.

@JohnFulpWillard FYI

### Reproduction Steps:

1. Put loads of fruits into botany smartfridge
2. Click on the number next to the fruit

Actual result: Smart Fridge dumps all fruits of this type out (if there are 150, all 150 will be dropped to the tile)

Expected result: Player is prompted with the desired amount as it was before the most recent UI change

**Comment by SyncIt21** [comment]
> Expected result: Player is prompted with the desired amount as it was before the most recent UI change

Is this actually expected? The PR's whole point was to remove the tgui popup and adding it back again seems to defeat its purpose. Also having a way to dump all contents by a single click is actually a convenience rather than typing the number in the number input box & then clicking vend

**Comment by JohnFulpWillard** [comment]
What? What are you talking about an alternative? This is meant to do the exact same thing as the previous system did just without the need for a second popup, it should be doing the exact same thing as before

**Comment by MTandi** [comment]
> What? What are you talking about an alternative? This is meant to do the exact same thing as the previous system did just without the need for a second popup, it should be doing the exact same thing as before

On tile view, which is default for fruit fridges, if you click on the number, it dumps everything out, without any limit. 
Before the change, it was asking to specify the amount. Also limiting to 50 items max.

**Comment by JohnFulpWillard** [comment]
Why do different smartfridges use different UIs I made it based on what chemistry's smart fridge uses

**Comment by MTandi** [comment]
> Why do different smartfridges use different UIs I made it based on what chemistry's smart fridge uses

Because tile view is more compact, and the names are important for chemistry because you need to know the pill name to pick it up. 

Fruits and foods can be selected by the look, you don't need to read their names, so tile view is better - it is more compact and icons are bigger - easier to navigate and click.
