### ISSUE TITLE
Gas Holoparasites can make produce gas while not manifested

### ISSUE THREAD

**Issue by TagGamerGang22** [tgstation/tgstation#88686]
### Client Version:

515.1637

### Issue Summary:

What the title says. This is a bit of an issue because a gas holoparasite can just plasma/co2/n2o/etc flood the entire station while not manifested with basically no one being able to tell the source.

Probably related to this: https://github.com/tgstation/tgstation/issues/81826

### Test Merge Information:

- [Make the xmas period longer](https://www.github.com/tgstation/tgstation/pull/88581)
- [Fully converts tgui to use tgui-core](https://www.github.com/tgstation/tgstation/pull/88648)

### Reproduction Steps:

1. Get yourself a gas holoparasite
2. Have them make gas while not manifested

**Comment by the-orange-cow** [comment]
Inspired by Junji Ito.
