### ISSUE TITLE
Really bizzare mutantrace bug

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#8868]
Got hit with a polymorph bolt twice in succession, ended up as a normal human with the speech pattern of a flyperson.

Later when I used green slime toxin to see if I could turn into a slimeperson, it turned me into a plant person instead, at least visually.

**Comment by optimumtact** [comment]
@Miauw62 any thoughts from the say code side?

**Comment by Miauw62** [comment]
lol this is just fucked up dna datums

**Comment by RemieRichards** [comment]
Shouldn't be occurring now speech effects happen on tongues
