### ISSUE TITLE
Santa's Suit has missing textures when anything is in its suit storage

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#88693]
### Client Version:

515.1637

### Issue Summary:

One of the santa suits (The one that's a space suit, you can find it in the cult murder ruin on icebox) has suit storage for a lot of things, but if you put anything in it it gets the funny pink square on its sprite

![Screenshot 2024-12-23 222022](https://github.com/user-attachments/assets/56b84fcf-a308-48e3-aa04-26173c0ea555)

How am I supposed to jollymaxx like this?

### Round ID:

[246466](https://scrubby.melonmesa.com/round/246466)

### Test Merge Information:

- [Make the xmas period longer](https://www.github.com/tgstation/tgstation/pull/88581)
- [Fully converts tgui to use tgui-core](https://www.github.com/tgstation/tgstation/pull/88648)

### Reproduction Steps:

1. Shit, let's be santa
2. Put something in suit storage
3. Missing texture moment

**Comment by OrionTheFox** [comment]
Consequence of it allowing **ANYTHING** to be suit-stored is that most of the anythings don't have icons. 
One of the major points of the suit is that it can suit-store anything though, so...

**Comment by OuroborusReporter** [comment]
No real worrying about this then, the only true fix would be spriting literally every item  ̶o̶r̶ ̶r̶e̶m̶o̶v̶i̶n̶g̶ ̶i̶t̶ ̶f̶r̶o̶m̶ ̶m̶a̶p̶s̶ ̶a̶n̶d̶ ̶m̶a̶k̶i̶n̶g̶ ̶i̶t̶ ̶a̶d̶m̶i̶n̶ ̶o̶n̶l̶y̶ ̶b̶u̶t̶ ̶w̶h̶e̶r̶e̶'̶s̶ ̶t̶h̶e̶ ̶f̶u̶n̶ ̶i̶n̶ ̶t̶h̶a̶t̶

**Comment by OrionTheFox** [comment]
> No real worrying about this then, the only true fix would be spriting literally every item ̶o̶r̶ ̶r̶e̶m̶o̶v̶i̶n̶g̶ ̶i̶t̶ ̶f̶r̶o̶m̶ ̶m̶a̶p̶s̶ ̶a̶n̶d̶ ̶m̶a̶k̶i̶n̶g̶ ̶i̶t̶ ̶a̶d̶m̶i̶n̶ ̶o̶n̶l̶y̶ ̶b̶u̶t̶ ̶w̶h̶e̶r̶e̶'̶s̶ ̶t̶h̶e̶ ̶f̶u̶n̶ ̶i̶n̶ ̶t̶h̶a̶t̶

wait hold on i thought it was admin/event only where in the world is it spawning

**Comment by OuroborusReporter** [comment]
It spawns in one of the Icebox ruins, the one that spawns on the station layer that's full of viscerators and dead cultists, it's on the ground at the north end of the ruin outside, by the raptor pen
