### ISSUE TITLE
laser shotgun gets deleted when it gets dropped

### ISSUE THREAD

**Issue by terracat474** [tgstation/tgstation#88707]
### Client Version:

515.1646

### Issue Summary:

laser shotgun exists when it is in your hands, and doesn't when you drop it or try to put it in a locker

### Round ID:

[246509](https://scrubby.melonmesa.com/round/246509)

### Test Merge Information:

- [Make the xmas period longer](https://www.github.com/tgstation/tgstation/pull/88581)
- [Pet Commands QOL . makes pet commands easier to use](https://www.github.com/tgstation/tgstation/pull/88495)

### Reproduction Steps:

1. Obtain laser shotgun (from present)
2. Drop it/put it in a locker
3. Marvel at the magic of dissapearing laser shotgun

**Comment by Sadboysuss** [comment]
```php
/obj/item/gun/ballistic/shotgun/ctf/Initialize(mapload)
	. = ..()
	AddElement(/datum/element/delete_on_drop)
```
this item isn't supposed to ever drop and if it ever does - deletes itself (on purpose)

**Comment by Sadboysuss** [comment]
although the issue that presents can spawn these types of items is valid

**Comment by terracat474** [comment]
yeah i got it from a present
