### ISSUE TITLE
You can pass through admin walls/windows using a plate (the dinnerware kind)

### ISSUE THREAD

**Issue by RandomDudeFromTheRim** [tgstation/tgstation#88727]
### Client Version:

515.1646

### Issue Summary:

If you have a pal, a deepfrier, and a way to become an item, you can get thrown into a wall while stored into the plate. The plate transfers its contents into the wall, allowing you to slip through 1 tile thick admin walls
EVIL plate

### Round ID:

[246584](https://scrubby.melonmesa.com/round/246584)

### Test Merge Information:

- [Make the xmas period longer](https://www.github.com/tgstation/tgstation/pull/88581)

### Reproduction Steps:

1. Get a deepfrier, friend, and a way to turn self into an item (poly belt for example)
2.  Get deepfried
3.  Get put onto a plate
4.  Make your pal throw you at the wall
5.  The plate shatters and you get spewed out into the wall
6. Escape onto the other side
![image](https://github.com/user-attachments/assets/0e809020-1731-4105-82f4-fac8f408502e)

**Comment by RandomDudeFromTheRim** [comment]
IN FACT, I think this works on just about any obstacle

**Comment by necromanceranne** [comment]
This is some troll logic holy fuck, a fantastic bug coming in hot at the last second?

**Comment by RandomDudeFromTheRim** [comment]
I only bothered to post my autistic finds here at the last days of this year, huh

**Comment by Majkl-J** [comment]
This is amazing

**Comment by the-orange-cow** [comment]
Using plates to clip through walls, what is this, Skyrim?

**Comment by Lorwp** [comment]
> and a way to become an item
morty i'm

**Comment by TheVekter** [comment]
How the ACTUAL FUCK did you find this one

**Comment by RandomDudeFromTheRim** [comment]
> How the ACTUAL FUCK did you find this one

Was fooling around as sec one day on another server when I noticed that "wait... did that item thst was inside the plate teleport?" Shortly after that, I came up with this

**Comment by Jamarkus127** [comment]
THIS IS MY VOTE FOR FUCKUP OF THE YEAR. THIS IS AMAZING.
