### ISSUE TITLE
Abductors console (or probably any advanced cameras) can see every single z-level (centcom, space, station, gateway)

### ISSUE THREAD

**Issue by Singul0** [tgstation/tgstation#88737]
### Client Version:

515.1641

### Issue Summary:

You can access every single z-level with the abductor camera I'm not really sure if there's any method to it, but I just flicked through z-levels really fast and realized I stumbled upon the CC z-level when I saw thunderdome's cameras lit up. we were able to TP to it before an admeme caught us.

### Round ID:

[246604](https://scrubby.melonmesa.com/round/246604)

### Test Merge Information:

- [Make the xmas period longer](https://www.github.com/tgstation/tgstation/pull/88581)
- [Fully converts tgui to use tgui-core](https://www.github.com/tgstation/tgstation/pull/88648)

### Reproduction Steps:

1. Be abductor
2. Flick through the z-levels really fast
3. ???
4. profit as now you can see any z-levels

**Comment by Y0SH1M4S73R** [comment]
Already fixed by #88689
