### ISSUE TITLE
Cannot set keybinds for emotes

### ISSUE THREAD

**Issue by Bibarra** [tgstation/tgstation#88736]
### Client Version:

515.1647

### Issue Summary:

In the keybindings menu, you cannot set or unset keybinds for emotes. Keyboard inputs do not seem to be accepted. Notably when the binding is highlighted and you are in the lobby, if that key is already bound to another emote you will try to perform that emote.

### Reproduction Steps:

Open up game preferences either in the lobby or in the OOC tab.
Try to set a keybind, or unset a keybind with ESC.
Fail miserably.

**Comment by distributivgesetz** [comment]
Could this be related to #88648 ? Did this happen in a live round or on local?

**Comment by distributivgesetz** [comment]
Confirmed to be related to #88648, please include a Round ID/just the server it happened on next time

**Comment by SmArtKar** [comment]
@jlsnow301

**Comment by jlsnow301** [comment]
Confirmed tgui core issue. I looked into it a bit, it seems I can't get the `KeyListener` component to use its callbacks. I've made an issue there and should have a solution in the next day or so.

**Comment by jlsnow301** [comment]
This should be resolved on the latest commit! Reopen if not
