### ISSUE TITLE
YOU CAN ORDER RAPTORS TO FUCK PEOPLE

### ISSUE THREAD

**Issue by L0pz** [tgstation/tgstation#88743]
### Client Version:

515.1647

### Issue Summary:

![image](https://github.com/user-attachments/assets/69292e72-9ca3-4a31-9fca-80c6f441137c)

### Round ID:

[246662](https://scrubby.melonmesa.com/round/246662)

### Reproduction Steps:

I DONT KNOW I WASNT THE ONE DOING IT

**Comment by TheVekter** [comment]
I already had to edit the poll once today, I'm not doing it again. This goes in 2025 as soon as smartkar makes it.

**Comment by nikothedude** [comment]
RULE EIGHT

**Comment by ReturnToZender** [comment]
Don't let the furry servers know about this one *gulp

**Comment by norsvenska** [comment]
![raptors](https://github.com/user-attachments/assets/c1cddc8e-527b-4f97-9cd7-fdac0e3fcfa4)

**Comment by MatrixOne500** [comment]
Kek

**Comment by the-orange-cow** [comment]
So, has this issue been.........  reproduced?

**Comment by Livrah** [comment]
Peak

**Comment by ZephyrTFA** [comment]
Every day we stray further from God. 
I helped bring this abominable thing into existence; yet, I will not help remove it because I'm fixing

**Comment by Sadboysuss** [comment]
> So, has this issue been......... reproduced?

yeah.

**Comment by Moltovz** [comment]
Nah mate keep it

**Comment by Ben10Omintrix** [comment]
ok so while u CAN technically try to give them the command, theyll refuse to act upon it unless its with a suitable raptor partner. still... 
![image](https://github.com/user-attachments/assets/a0e8e4d3-753b-47e0-9e10-5405f488f92c)

**Comment by Keekenox** [comment]
Working as intended

**Comment by SyncIt21** [comment]
The nephalem are here

**Comment by projectkepler-ru** [comment]
How do you even come across this

**Comment by NargaInDisguise** [comment]
Holy fucking shit this one is a CONTENDER

**Comment by DrAmazing343** [comment]
HAHAHAHAHAHAHAAHHAHAHAHAHAHHAHAHAHA

**Comment by RandomDudeFromTheRim** [comment]
> ok so while u CAN technically try to give them the command, theyll refuse to act upon it unless its with a suitable raptor partner. still... ![image](https://private-user-images.githubusercontent.com/138636438/398813765-a0e8e4d3-753b-47e0-9e10-5405f488f92c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyODY3NDMsIm5iZiI6MTczNTI4NjQ0MywicGF0aCI6Ii8xMzg2MzY0MzgvMzk4ODEzNzY1LWEwZThlNGQzLTc1M2ItNDdlMC05ZTEwLTU0MDVmNDg4ZjkyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QwODAwNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZmExN2YwYmJlY2NjMzVjZmZjMTAzN2NlZDIxZGI4MjljY2VlZTllMzY2Mjg1ZGQxZGIwMGJiYjFkMWE5NGYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZBnZwgvfSG8vfSGZ3jxj0FIM_JCg1jvs29c1UnJbI3Y)

Now I'm wondering: what if you polybelt into a raptor? Will the raptor breed with you? And if yes, what will happen if you'll revert back to your human self mid-breeding?

**Comment by Medziaga** [comment]
what are the mechanical benifits of this.

**Comment by distributivgesetz** [comment]
> Now I'm wondering: what if you polybelt into a raptor? Will the raptor breed with you? And if yes, what will happen if you'll revert back to your human self mid-breeding?

QUIT FANTASIZING

**Comment by RandomDudeFromTheRim** [comment]
It's not fantasizing, it's called mad science

**Comment by NargaInDisguise** [comment]
> 
> Now I'm wondering: what if you polybelt into a raptor? Will the raptor breed with you? And if yes, what will happen if you'll revert back to your human self mid-breeding?

The DnD 5e "What happens if you get pregnant as a polymorph druid" discussion:

**Comment by projectkepler-ru** [comment]
> what are the mechanical benifits of this.

Lets you make more raptor with no inherited personality from second pair or colour changes

**Comment by ZephyrTFA** [comment]
Nope. Let's stop right here.

**Comment by LemonInTheDark** [comment]
coward

**Comment by ZephyrTFA** [comment]
> coward

Correct.
