### ISSUE TITLE
Crusher destabilizing blast doesn't always activate on hit

### ISSUE THREAD

**Issue by pbj567** [tgstation/tgstation#88782]
### Client Version:

515.1647

### Issue Summary:

If you hit an enemy after using the destabilizing blast on them, it seems to not always activate

### Round ID:

[246817](https://scrubby.melonmesa.com/round/246817)

### Reproduction Steps:

1. shoot fauna with destabilizing blast
2. hit fauna with crusher
3. hope the destabilizing blast actually works

**Comment by SmArtKar** [comment]
#88171 changed how marks work
