### ISSUE TITLE
Spray Can Bug: Spray can secondary 'multiply' functionality now maximises hue.

### ISSUE THREAD

**Issue by dalmationer** [tgstation/tgstation#88838]
### Client Version:

515.1647

### Issue Summary:

I covered this in #88533 however while this was closed, I believe the following represents a bug.
Previously, when recolouring some objects, you were able to select the value and saturation of the object to recolour, allowing a greater range of colours. This could be used to achieve a variety of more subtle colours, especially when colouring lights. For example, note the following screenshot where the lighting has been changed to a low-saturation, high value pink colour, and the tables have been changed to a low saturation, low value orange-brown hue.

![image](https://github.com/user-attachments/assets/95b6aa3d-bcdb-445f-a35a-5c97c5d08122)

compare to the current reworked version as of #88201 (I am attempting to approximate the same colours in this image.

![image](https://github.com/user-attachments/assets/b9885164-54ea-4b26-a8c6-99e8a9c00e8e)

Note that tables cannot be darkened much further than this: it appears applying the multiply mode to objects has very limited effect on low-saturation colours, presumably to avoid black spray paint camophlaging things.

Overall, I believe the new changes are better in some regards, but they suffer when it comes to lower saturation or lower brightness colours to greyscale objects or lights: They are most useful when recolouring high-detail or coloured objects and worn items.

### Round ID:

[247120](https://scrubby.melonmesa.com/round/247120)

### Test Merge Information:

- [Adds an off-by-default config option to optionally disable TTS audio on whispered speech.](https://www.github.com/tgstation/tgstation/pull/88826)

### Reproduction Steps:

1. apply spray paint to a light of varying levels of saturation, hue and value.
2. apply spray paint to an object of varying levels of saturation, hue and value.

**Comment by SmArtKar** [comment]
![image](https://github.com/user-attachments/assets/13b832b8-155a-42f7-967a-858a895c4b60)

Instead of using HSV you should stick to HSL, high sat values make your colors darker. Here you can see a working version of your color, although the closest would be achieved by 300-25-70 HSL.

```js
    if (saturation_behavior == SATURATION_OVERRIDE)
        added_saturation = saturation * 0.75
        deducted_light = saturation * 0.5
        saturation = min(saturation, 1 - added_saturation)
```
