### ISSUE TITLE
Spray paint still has tons of issues.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#8940]
1. It doesn't stun you at all if you have no protection, and doesn't blind you if you have glasses.
2. It's also only removable with paper or space cleaner (an effect of all lipstick, but it really should be expanded to showers, rags, and sinks).
3. When you wipe it off with a paper sheet it is called lipstick "Sherlock Bones wipes Shannon Marriman's lipstick off with the paper."
4. Several things appear to make it not work, but it seems to break after using it on a person who has already been sprayed, preventing you from coloring anyone else's face.
5. You can't tell how much paint is left.
6. When all used by huffing, the can is deleted.
7. Spraying aliens with it does not make any sound for ONLY the first two attempts.
8. These first two spray attempts are capable of giving the aliens a foggy screen, but ONLY on the first two attempts! Aliens already have covered faces and possibly no eyes. What exactly are you blinding?
9. Monkeys are the only things that get stunned, they get both the stun and a bit of eye blur. This however ONLY happens for the first two attempts, it stops working after that.
10. Attempting to huff the paint for the first time will spray your face and stun you (while saying you took a huff), even though you're targeting your mouth. It will huff normally after that.
11. You can spray simple animals, and while it doesn't stun them it still makes the sound and says you gently tapped them with the spray. It should either at least say it sprayed them or shouldn't work on them at all.

Also further minor gripes:

The spray can has far too many unnecessary buttons. There's no reason for an entire extra prompt that lets you select if you want to toggle the cap (just have it be usable at all times), or choose a color or drawing as separate buttons. Just make it use the rainbow crayon UI as it already has those two things together.

@sawu-tg

**Comment by Jordie0608** [comment]
Spraycans aren't depleting their uses when spraying faces.

Also noticed that sometimes the spraycans fail the color the target's face, usually after the color has been changed.

**Comment by WJohn** [comment]
These things are unbelievably buggy like holy shit, on top of previously having been able to do this at any range, through walls and with no protection in the past.

**Comment by BillWilsonCIA** [comment]
Yes, I can confirm you can spray through walls as long as you see your target.

**Comment by Ikarrus** [comment]
Well fuck. Can we coordinate this a bit so it doesn't cause a merge conflict with the gang update?

**Comment by Ikarrus** [comment]
I can try and plug up some of these bugs right now actually

**Comment by Boredone** [comment]
So, minor thing.
When ye use up a spray can by spraying people in the face, it still exists.
BUT, when you use it up by spraying graffiti, runes, letters, etc, it disappears.
On a side note, no feedback for the user if the can is empty when ye are trying to color people's faces.

**Comment by Amnestik** [comment]
(why was this pulled in this state?)

**Comment by tedward1337** [comment]
Has this been fixed?

**Comment by phil235** [comment]
All fixed except for number 4. Also the spray sound is very faint when spraying someone's face, its volume ought to be increased.
