### ISSUE TITLE
Remains/Gibs contain no 'evidence'

### ISSUE THREAD

**Issue by SconesC** [tgstation/tgstation#8951]
DNA/Blood type/fingerprints

'Remains' meaning cult skeleton

Not sure if this is a bug or a feature or just something nobody bothered to implement, but I see no reason why I shouldn't be able to take a blood sample from that chunk of gore and run it through out magic machines. Similarly, remains might have fibers or something on them.

**Comment by phil235** [comment]
Gibs should already have blood_dna on them since the fix for it was merged a few days ago.

**Comment by Lumipharon** [comment]
if you could actually extract blood from gibs (syringe or whatever) you could pod people gibbed guys.
