### ISSUE TITLE
Objective #2: Prevent Megatron, the AI, from escaping alive.

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#8984]
Enough said

**Comment by optimumtact** [comment]
Did they succeed?

**Comment by MrStonedOne** [comment]
This was on my test server, when i was playing with minds to see how they work for testing of ghost drag

**Comment by SconesC** [comment]
Are you referring to how it uses the roundstart random name for the AI instead of it's chosen one?

**Comment by Dorsisdwarf** [comment]
He's referring to the fact that the AI is being chosen as 'Prevent from escaping'

**Comment by xxalpha** [comment]
Well the AI has a mech now, so it's valid.

**Comment by Firecage** [comment]
But AI's can escape....intelicard and core on shuttle.

**Comment by Dorsisdwarf** [comment]
Seems like a "FEATURE" to me.

**Comment by tedward1337** [comment]
Fixed ?
