### ISSUE TITLE
Player Pannel Rudimentary Transforms Using Wrong Player

### ISSUE THREAD

**Issue by Fayrik** [tgstation/tgstation#8988]
Should be easy enough to reproduce. Make a character, give it a new ckey then use the player panel to transform your ghost/observer self.
Expected results: You transform.
Actual results: They transform.

Looks like line 277 of topic.dm might be the issue.
`var/mob/M = locate(href_list["mob"])`
I don't quite understand where that's drawing information from enough to attempt a fix however, so I'm hoping someone here does.

**Comment by Miauw62** [comment]
the strange part is, without looking at the code, that that should locate a mob by its ref.

**Comment by Fayrik** [comment]
Basically, there can be more than one of that specific mob, it needs to select by client, I think?

**Comment by ShizCalev** [comment]
Doesn't seem to be an issue anymore.

**Comment by ShizCalev** [comment]
No further reports in years.
