### ISSUE TITLE
Using Say Hotkey lets you Talk without being interupted

### ISSUE THREAD

**Issue by Boredone** [tgstation/tgstation#8999]
Basically, ye know how you can get interrupted if you get hit hard while typing somethi-oof!
If you use the say HotKey, it makes a window pop up, which can't be interrupted.
So you could use it to utterly ignore the interruption getting attacked can cause to yell out whatever you want.

**Comment by Miauw62** [comment]
wasnt this supposed to be fixed

**Comment by TheVekter** [comment]
@Miauw62 I have no idea how we'd fix it other than making it close the say window when you get stunned.

**Comment by Razharas** [comment]
After testing on thunderdone forcesay appears to be not working at all

**Comment by tedward1337** [comment]
This still seems to be an issue?

**Comment by phil235** [comment]
still a thing.

**Comment by Cyberboss** [comment]
Would have to redo how say input is done in hotkey mode because it's impossible to stop the input proc/read it's contents
