### ISSUE TITLE
Runtime /mob/living/simple_animal/proc/handle_automated_movement

### ISSUE THREAD

**Issue by xxalpha** [tgstation/tgstation#9015]
runtime error: list index out of bounds
proc name: handle automated movement (/mob/living/simple_animal/proc/handle_automated_movement)
  source file: simple_animal.dm,122
  usr: null
  src: the goldgrub (/mob/living/simple_animal/hostile/asteroid/goldgrub)
  call stack:
the goldgrub (/mob/living/simple_animal/hostile/asteroid/goldgrub): handle automated movement()
the goldgrub (/mob/living/simple_animal/hostile/asteroid/goldgrub): Life(2)
the goldgrub (/mob/living/simple_animal/hostile/asteroid/goldgrub): Life(2)
Mobs (/datum/subsystem/mobs): fire()
/datum/controller/game_control... (/datum/controller/game_controller): process()

**Comment by phil235** [comment]
line 122 is `var/anydir = pick(cardinal)`

**Comment by xxalpha** [comment]
Yeah, there is no such thing as "cardinal" defined anywhere, as far as I am aware.

**Comment by xxalpha** [comment]
I think this can be closed, pick() being a BYOND proc we can't fix the runtime. I have been trying to reproduce it without success.

**Comment by phil235** [comment]
Alright then, closing.

**Comment by xxalpha** [comment]
This was fixed.

http://www.byond.com/forum/?post=2081799

**Comment by phil235** [comment]
Still happening.

**Comment by optimumtact** [comment]
I've not seen this in a long time
