### ISSUE TITLE
Recovery ship's navigation console loses ability to travel.

### ISSUE THREAD

**Issue by Turgent** [tgstation/tgstation#9039]
The recovery ship's navigation console loses the ability to travel if it is tampered with.
I disconnected the monitor from the console and displaced the glass to prevent people jacking it whilst I did things on the station. I assembled it back together and it displayed this; 
![aaa](http://puu.sh/higFQ/c48162baf3.jpg)

Server revision compiled on: 
c3505f7df02bb3e4628f7794c1cea1c11476aa86 
This happened on the 18th of April, at 17:44 GMT +1. It happened on Basil.

**Comment by PKPenguin321** [comment]
You mean the white ship?

**Comment by Dorsisdwarf** [comment]
He means the recovery ship. It's like the whiteship but actually comes with a lot of stuff. Meatstation only.

**Comment by Robustin** [comment]
aka Metastation inferiority complex whiteship

**Comment by PKPenguin321** [comment]
Necro

**Comment by ExcessiveUseOfCobblestone** [comment]
Is this still a bug though

**Comment by Jalleo** [comment]
@Coiax or @Cyberboss any idea if this has been fixed or not?

**Comment by octareenroon91** [comment]
Yeah this is fixed: white ship consoles drop the a white ship console board. White ship boards build white ship consoles.

**Comment by Cyberboss** [comment]
@lzimann
