### ISSUE TITLE
Malf AI sometimes unable to bring up the right click menu.

### ISSUE THREAD

**Issue by Boggart** [tgstation/tgstation#9062]
As a malf AI it's possible to have the right click menu not show, leaving you unable to use abilities that depend on it. To fix it you have to either rejoin or (unconfirmed but mentioned in ooc) cancel your camera view.

At the time right clicking seemed to cause 1-5 seconds of lag, which went away on a rejoin. I am unsure if the menu was gone originally or only after the purchase of the first power using it.

**Comment by GunHog** [comment]
Return to your core using the first button on your AI HUD, it is the same function as cancelling camera view in the OOC tab. There is a bug when adding new verbs to the AI when buying Malfunction modules. I have yet to pin this problem down, but that is all you need to do. Do not disconnect, there is no need for that.
