### ISSUE TITLE
Drinking Glass in secret inventory slot

### ISSUE THREAD

**Issue by Sven-Grey** [tgstation/tgstation#9068]
Problem Description: 
About half way though a round as bartender, I realized I had a drinking glass stuck to my hand that couldn't be removed. Sometimes it would teleport into my inventory (where the third slot of the backpack would be) regardless if I was wearing a backpack or if the slot was filled.

What did you expect to happen: 
I expected to be able to drop the Drinking Glass

What happened instead: 
Not only could I not drop it, but other people could not take it off me. They pushed me; tried to pickpocket it out; even the drink was even overlapping handcuffs when I was cuffed.

Why is this bad/What are the consequences: 
On the plus side, I would still use the drinking glass. So it could have been used to smuggle chemicals. On the down side, it took away one of my hands.

Steps to reproduce the problem: 
I'm not sure how exactly it happened. Oddly enough, all the drinking glasses were accounted for. This drinking glass came from nowhere. I tried a combination of mixing drinks and throwing glasses around, but I couldn't reproduce it.

Server:
Sybil (4/19/2015) (Around 1:00PM - 2:00PM EST)

Revision: 
Server revision compiled on: 
c8a1275cfcbf214904069cf0fc79cba051b6df8b 
Current Infomational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 1
Allow Latejoin Antagonists: 1
Protect Assistant From Antagonist: 0

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?):
It seemed to be a normal traitor/changeling round. There were abductors as well. I'm sorry I couldn't reproduce it on my own.

**Comment by phil235** [comment]
Something similar happened to a virologist with a beaker around a month ago.

**Comment by AnonymousNow** [comment]
Sovereign Glue.

**Comment by callanrocks** [comment]
Glue is buggy as hell.

**Comment by stapler2025** [comment]
I had this happen a week ago with a pair of cuffs.

**Comment by Marflowerose** [comment]
Also had this with an ebow indefinite time ago.

**Comment by TheVekter** [comment]
This seems like a fringe case. It's apparently been around for a while, but I have no idea what's actually going on to cause it.

If this is happening with more than just the glass, it needs to be looked at ASAP.

**Comment by Miauw62** [comment]
I had this happen with handcuffs, they appeared where the leftmost slot of my backpack would be and I couldnt interact with them at all. Searching for them in my contents did not show anything.

**Comment by optimumtact** [comment]
old higgs bugson
