### ISSUE TITLE
Exosuit Fabricator can bypass powercell reliability.

### ISSUE THREAD

**Issue by Firecage** [tgstation/tgstation#9084]
As the title says. In short, the Exosuit Fabricator isn't bound to the reliability system. So while the Protolathe might make powercells with low reliability, the Exosuit Fabricator can be used to bypass it to give reliable powercells.

**Comment by GunHog** [comment]
Reliability is pretty terrible system in of itself. Only a few things use it really. The AE Gun is the one and only item that adds interesting gameplay in that it will break or irradiate you if you do not improve on it. 

Power cells will break and fail to recharge, <b>giving no warning to the user</b>. Giving a poor little Borgie a protolathe cell will only confuse it when it gains no charge from a borg station. This was also a proper nightmare to figure out on mech chargers. For the longest time, I thought charger code was simply broken. You cannot tell when you have a broken cell except that it may fail to charge.

The BoH has code for realiability, but I have never seen it proc. As for the rest, it is a simple annoyance that prevents deconstructing certain items.

**Comment by Lumipharon** [comment]
reliability is pretty shit, although it does make R&D require a small amount of extra effort.

**Comment by Kelenius** [comment]
Proposed solution: axe reliability.

**Comment by Jalleo** [comment]
This is actually intented.

Plz tag not a bug

**Comment by chimersable** [comment]
Reliability doesn't even work correctly with AE guns. Every AE gun I ever made regardless of protolathe upgrade or research always breaks after a dozen shots or so.

**Comment by GunHog** [comment]
Reliability works correctly with AE guns. Release levels or protolathe upgrade status has no effect, and is not coded to do so. There are two ways to perfect the AE guns. The quick and wasteful way is to deconstruct several of them in an <b>upgraded</b> destructive analyzer, or you could save a massive amount of uranium by inserting a test range pin (this is why that pin exists!), wearing a radiation suit, and intentionally breaking the gun. DAing it at this point, no matter the upgrades on the DA, will give you perfect AE guns.

**Comment by Dorsisdwarf** [comment]
I do giggle at people who think that breakable kit can only be upgraded in the DA though.
