### ISSUE TITLE
Slime follow/stay commands not working.

### ISSUE THREAD

**Issue by SeikoTheSeal** [tgstation/tgstation#9128]
No matter how many plasma bars you feed them, after giving them a command, instead of responding with a simple "No" if they dont consider you their friend, or acknowledging the command and following you/sitting on their ass, they instead respond with "Hi", "Hello", which are responses to "Hi slimes" "Hello slimes" et cetera, and nothing happens.

Happened on Yogs yesterday at night, code was updated round before i noticed this.

**Comment by chimersable** [comment]
Maybe #9125 (NPC pool is lagging the server to shit.) is related. They are theorizing their problem is a pathing issue. I am going to pop over there and suggest this be considered for possible inclusion in 9125

**Comment by sawu-tg** [comment]
@chimersable  Slimes do not use NPCPool, but they do use A*.

This is probably an issue with someone breaking a switch somewhere.

**Comment by phil235** [comment]
This problem lies in one of the slime life subprocs.

**Comment by Mervill** [comment]
@optimumtact closeable, #18151 indicates that this was fixed

**Comment by jughu** [comment]
I said last time attack slimes and there was no response from them normally they say no if they dont want and there was targets nearby
