### ISSUE TITLE
Moveable machinery that relies on APC power retains their powered/unpowered setting even after being moved to an area with a different setting than the room it was taken from.

### ISSUE THREAD

**Issue by TheSadFox** [tgstation/tgstation#9146]
This may be a dupe, as i THINK i saw a report about something simmilar somewhere, but couldnt find it. Or i am just delusional, thats also possible.
1. Turn off equipment power in botany (or any other place that has such machines).
2. Screwdriver > wrench > drag the vending machine to a different area that still has equipment power on.
3. Machine still unpowered.

Works with every machine that can be moved without fully deconstructing it.
This leads to odd cases like people moving chargers into an area in space near blob, that have no power at all, building plating and wrenching them in place, and then firing at blob with zero danger.
Or botanists whose APC got destroyed/sabotaged in some way being unable to move their vending machines to the hallway/other area so that they can keep working.

**Comment by feemjmeem** [comment]
I fixed this for rechargers in #11917. I'll look at the other machines.

**Comment by Rinoka** [comment]
is this still a problem? know we've had a bit of reworking on all parts here
