### ISSUE TITLE
Infrared Emitter Beam is Wonky

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#9170]
Namely it's really buggy in its behavior as it doesn't refresh much...this results in the infrared beam hanging in the area where the assembly was originally activated/turned on. This goes beyond a mere graphical abnormality; if someone crosses that beam, it will still trigger the infrared assembly...no matter where on the map it's located.

**Comment by WJohn** [comment]
Infrared has been broken for years.

**Comment by Jalleo** [comment]
Ill look into this bug this freeze @WJohn please send a memo to me later so I remember to do so tomorrow

**Comment by Jalleo** [comment]
@phil235 have you fixed this quite a while ago in https://github.com/tgstation/-tg-station/commit/27302aa6ae7b233ae6b4d08492efb109a2f778b2 or later via the https://github.com/tgstation/-tg-station/commit/135293bedfc4226b08d840433397b35073e4cc3b ?

**Comment by phil235** [comment]
Dunno, it's probably best to try to reproduce the issue.

**Comment by Jalleo** [comment]
I am currently working on overhauling assemblies so I will make this work better at the same time.

**Comment by PKPenguin321** [comment]
Does this use an actual Beam()? It should

**Comment by Jalleo** [comment]
no it doesnt
