### ISSUE TITLE
Cyborg deconstruction possibly bugged?

### ISSUE THREAD

**Issue by Ausops** [tgstation/tgstation#9234]
anon- There's a borg in robotics, I've done the steps. Unlock, open, remove battery, cut all wires, and wrench.
anon- But rather than falling into pieces, it just leaves an endoskeleton
anon- I see the falls to pieces part

admin- Alright, so it shows you the 'falling to pieces' message but doesn't fall apart at all?
anon- Nope. And the endoskeleton just... warps back to where Nelson Muntz is.

Nelson Muntz was a second, braindead borg.

The borg unable to be deconstructed apparently used to have a mmi.

**Comment by kingofkosmos** [comment]
https://github.com/tgstation/-tg-station/blob/548e0eb17e1e46e4a686006c80096fd3c3237d97/code/modules/mob/living/silicon/robot/robot.dm#L479
this must be the part of code in question?

**Comment by Jordie0608** [comment]
This seems to be working for me

**Comment by optimumtact** [comment]
old with no repro
