### ISSUE TITLE
Point blank is a really bad mechanic

### ISSUE THREAD

**Issue by SconesC** [tgstation/tgstation#9266]
It's basically required to make shotguns work well but it's still sort of confusing and unintuative, mainly considering it requires you to click on your target, which _sometimes_ makes you hit them with your gun, sometimes you hit them and shoot them, sometimes you just shoot them.

Also, this happened. 1st pellet hit me, somehow, stationary and firing point blank at a stationary naked target in the Thunderdome.

You pull the magazine out of the syndicate shotgun.
You load a new magazine into the syndicate shotgun.
Adeline Lacon is hit by a pellet in the chest!
You fire the syndicate shotgun point blank at Nelle Garland!
Nelle Garland is hit by a pellet in the chest!
Nelle Garland is hit by a pellet in the chest!
Nelle Garland is hit by a pellet in the chest!
Nelle Garland is hit by a pellet in the chest!

**Comment by WJohn** [comment]
It depends on your intent. If you're on harm intent, you will instead bash them with your gun. How help, disarm, or grab intent is more suited to bashing someone I have no idea. Intent system is a massive consistency mess in and of itself.

**Comment by WJohn** [comment]
So now the only remaining part here is the broken cone mechanic and the inconsistencies with firing at point blank range. If you click on someone, all pellets are GUARANTEED to end up inside them. If you click on the floor or an object instead, though, there's a good chance some pellets will *immediately* appear off to the side, meaning you're guaranteed to miss. This is probably largely in part due to the broken cone mechanic, but come on.

**Comment by optimumtact** [comment]
This isn't really a bug, it's just due to how cones don't work in a 2d tile game properly.

**Comment by jughu** [comment]
@korphaeron can be closed?
Im also pretty sure 40% of the bugs reported in 2015 are either byond sided or old snowflake cose or inconsity issues

**Comment by Robustin** [comment]
Its a shitty mechanic but not a bug.

You'd think going to the most harmful intent with a goddamn gun would ensure you always use the most harmful option. Instead disarm is more lethal than harm because you actually shoot point-blank.

**Comment by duncathan** [comment]
fuck it
