### ISSUE TITLE
Mechs are inconsistent in space

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/tgstation#9282]
In space, mechs drift, like everything else. However, they are totally unable to propel themselves, even by firing machineguns or pulse rifles.

Obviosuly this is retarded, especially since it means mechs can get stuck in a space turf and be unable to move.

**Comment by xxalpha** [comment]
Mechs are inconsistent, period.

**Comment by Lumipharon** [comment]
No grav can be pretty awful.

**Comment by Cheridan** [comment]
I don't mechas not being moved by their weapons is an issue. Mechas are big and stompy, so the recoil of the weapons would have much less of an effect. 

Though some kind of thrust ability to unstick in nograv situations would be nice.

**Comment by Dorsisdwarf** [comment]
Firing machineguns and scatterguns in a zero-G environs is definitely going to move you, even if you're in a big metal box. Maybe not like with people where an SMG is a jetpack with more collateral damage, but sitting still spewing deadly projectiles into the void is dumb.

**Comment by Marflowerose** [comment]
I can't fathom why mechs don't come preinstalled with manouvering thrusters(fire extinguisher) let alone magboots.

**Comment by Lumipharon** [comment]
Didn't they previously not get effected by no grav?

**Comment by Marflowerose** [comment]
Lumi, you are correct, the floating mechs has been a thing for quite a while now though, I can't remember what update broke them.

**Comment by Miauw62** [comment]
is this a bug? i dont know ;-; other maintainers please help

**Comment by Lumipharon** [comment]
It's worth mentioning, that a mech can't move even if it's next to a solid turf - ie: mech is on space, tile next to it is asteroid sand, they can't move.

This is particularly awful when you remember a ripley's drill mines both tiles adjacent to the one you target.

**Comment by phil235** [comment]
>t's worth mentioning, that a mech can't move even if it's next to a solid turf - ie: mech is on space, tile next to it is asteroid sand, they can't move.

This isn't the mech's fault, the same thing happens with mob. The issue seems to be that the asteroir floor doesn't let you grab onto it like other floor turfs.

**Comment by MrStonedOne** [comment]
needs reproduce tag please.
