### ISSUE TITLE
Genetic nano UI is awkward.

### ISSUE THREAD

**Issue by Durkel** [tgstation/tgstation#9316]
The UE and SE buffers are right on top of eachother, which leads to a confusing situation of what's what.They should be separated by a space to clarify the difference. Additionally, the radiation output is hanging outside the box for the UI and looks bad.

Ignore my issue about monkeys, I'm retarded. Honk.

**Comment by AlexCrimson** [comment]
Agreed. UE should be in a separate tab if possible.

**Comment by chimersable** [comment]
Any way to update font sizes and type while fixing this? It's a bad font that has too many characters that look alike. Honestly the old interface was better.

**Comment by Mervill** [comment]
@optimumtact I think this is referring to NanoUI? At any rate these issues don't seem to be present on in the genetics ui. closeable.
