### ISSUE TITLE
Gang mode slowdown issues

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/tgstation#9392]
Not sure if this has been fixed, quick glance showed no signs, issue was few days ago.
Non-gangmembers should not be able to clean gangtags. Neither gang can win if there's two or more janitors/janiborgs who clean the tags faster than any gang is able to spray them. Gang mode by default is very slow-paced it doesn't need army of janiborgs grinding it to halt.

**Comment by hanshansenhansson** [comment]
Maybe make it require pure aceton? That way dedicated anti-gangers like the Janitor can still get it from chemistry, and borgs are out of luck. And if chemistry keeps making it, they get stitches.

**Comment by Alek2ander** [comment]
But then the gang that takes over chemistry will have a huge advantage

**Comment by SeikoTheSeal** [comment]
If chemistry and RnD became such crucial areas to achieve victory, maybe we would see some gang versus gang combat, trying gain control over the aceton supply and denying it from the other gang.

**Comment by Dorsisdwarf** [comment]
How about gang signs need ammonia to clear off. That way non-chemists can order it from chemistry (it's a fertiliser and ingredient in space cleaner) without raising too many eyebrows, but you can also just sieze control of chem and mass-produce it if you've snowballed enough.

**Comment by Alek2ander** [comment]
Gangs often become nations quickly because it's easy to recruit people in your department. So any gang boss who started as a chemist/MD will have a huge advantage.

**Comment by nullbear** [comment]
uh then kill the janitors if they're wiping you're tags???
