### ISSUE TITLE
Perfluorodecalin mutes custom me emotes but not say* emotes.

### ISSUE THREAD

**Issue by Ausops** [tgstation/tgstation#9438]
Reported by a player in game and tested again by myself. 

The chem's description says it mutes you but it also mutes any custom emotes. Normal ones aren't affected and you can still do them.

**Comment by Dorsisdwarf** [comment]
I'm pretty sure this is to stop ' me " says "Help john's a traitor gave me a deathmix." '

**Comment by Miauw62** [comment]
its called admins

**Comment by Thunder12345** [comment]
Yeah, I thought there were admins to stop people abusing me like that

**Comment by Cheridan** [comment]
They won't, though. 'Me " indicates that he was stabbed with a pen-like object' is completely fine as far as /tg/station rules go.

**Comment by Dorsisdwarf** [comment]
Also I'm not sure if it's even possible for an admin to casually notice someone using "me" to say things.

**Comment by Iamgoofball** [comment]
I think this is a bug though, it's only supposed to prevent talking

Its a problem with the mute var I bet

**Comment by AlexanderUlanH** [comment]
The silent var mutes works as intended, muting speech and custom emotes.  It's mostly used in things like sleepypens and mutesting, which are meant to prevent a target from communicating entirely.  You'll probably need a new var if you want to make a chem mute speech only and not custom emotes for fluff reasons.
