### ISSUE TITLE
Bug - Camera view in Engineering

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#9443]
Server: Basil

Revision: Unknown

Problem Description: Encountered a bug as a sec-borg in Engineering. I was looking through a camera, I was near the airlocks at the time and not next to the monitor, and was switching to another but I got a Human order so I cancelled mid-switch. It locked my view to the initial camera that I couldn't get out of. After that, anytime I entered the Engine Room, my view automatically switched to the camera's.

What did you expect to happen: I expected that cancelling the camera view would... Cancel the camera view.

What happened instead: I got stuck in the camera's viewpoint and couldn't go to engineering without my view jumping to it. I could still move around and if I left the Engine Room my view would go back to normal.

Why is this bad/What are the consequences: Because I can't do anything in Engineering, such as there being a double E-Sword wielding rogue crewmember harming a Human.

Steps to reproduce the problem:  I was near the airlocks at the time and not next to the monitor, and was switching to another but I got a Human order so I cancelled mid-switch. There was also a lag-spike caused by the Singularity which was in stage 4 at the time.

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): I can't really think of anything else that happened. I didn't stick around long enough to learn the game mode.

**Comment by palpatine213** [comment]
Did you try using the cancel camera view verb in he ooc tab?

**Comment by MrStonedOne** [comment]
This is a dupe of #3324 but I'll close #3324 since this explains more

**Comment by loqoman** [comment]
Not enough info, probabbly close
@Dorsisdwarf

**Comment by Anonmare** [comment]
I've got it
