### ISSUE TITLE
Glass shards are the only things that do not shock you if hitting an electrified grille.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#9459]
This makes no sense at all. We have tons of non-metallic items like cloth, cardboard, wood, and other objects that simply should not shock you if you struck a grille with it.

I think perhaps the way this should be fixed is by checking if:
1. The item can be deconstructed in the autolathe or protolathe or exosuit fab or whatever else
2. The item has a metal content in it (screwdrivers, multitools, RCDs and others would all apply)

If it had both of these and you weren't wearing any insulated gloves, THEN it should shock you.

**Comment by GunHog** [comment]
The CONDUCT flag is what you want, WJohn.

**Comment by WJohn** [comment]
There's that option too, but what I'm suggesting is probably the lazy way out. There's an absolute assload of items in the game already and the sheer amount of work and conflicts you'd run into throwing that flag into everything wouldn't be something people would want.

Up to you, though.

**Comment by hanshansenhansson** [comment]
Why go with realism here? I think it is this way for gameplay reasons. No need to make it even easier to break through them.

**Comment by buttsmcgee** [comment]
>I think it is this way for gameplay reasons

It really doesn't make sense for gameplay reasons either. Pretty much everything seriously capable of grille smashery has metal in it.

I'm struggling to think of a widely available, nonmetal object that can smash through grilles easily.

**Comment by WJohn** [comment]
A light tube? Has metal on the tips but it uses only glass when creating them.

**Comment by Wolfie13** [comment]
Wood stack would probably be a good candidate. Toy Esword? Considering players can bash through grilles pretty easily with hands, a large assortment of clothes would probably be good enough. Backpacks certainly could be used to beat on the grille.

I take issue with the idea of people without gloves being able to hold a shard of broken glass firmly enough to beat through a grill, more than I do that they're the only nonconductive item.

Side note: Could you use a glass shard to cut a power wire?

**Comment by WJohn** [comment]
Almost all clothing has no force, wolfie. Same goes with the toy sword, wood stacks *might* work but that's not very common.

**Comment by 9600bauds** [comment]
Glass shards are conductive on themselves, so if you try to cut a power wire you end up station bacon.
