### ISSUE TITLE
Zoey Webb(Firecage) as an Animal (survived)

### ISSUE THREAD

**Issue by Firecage** [tgstation/tgstation#9490]
Basically I was a ling, used Last Resort and became a headslug, infected a corpse, became a human(ling) again eventually. Though the round end report said I was an animal.

Zoey Webb(Firecage) as an Animal (survived)

**Comment by peoplearestrange** [comment]
Y-you ANIMAL!

**Comment by Incoming5643** [comment]
Sounds like the round end report was still tracking the oldest body you had that wasn't gibbed (the headslug)

**Comment by Dorsisdwarf** [comment]
Tested, could not reproduce.
