### ISSUE TITLE
Spraycan colour can be wiped off your face, but only if you aim for the mouth

### ISSUE THREAD

**Issue by hanshansenhansson** [tgstation/tgstation#9524]
It colours your entire face, but you have to use a paper and aim for the mouth (similar to lipstick) to wipe it off. Should require aiming for the entire head, as the entire head is coloured after all

**Comment by Incoming5643** [comment]
It's because it's a child of lipstick, the whole system is older than dirt and needs to be reworked.

**Comment by WJohn** [comment]
Probably related or duped from #8940
