### ISSUE TITLE
Lights work from inside lockers.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#9545]
Originally if you had lights on, but went inside a locker, it would all stop emitting light. Now it still makes light.

Additionally if I try to turn off my light while inside a locker it tells me I can't turn it on while in it, instead of off.

**Comment by phil235** [comment]
The issue is that the object's light isn't updated when you get in the closet. This also happens when you have a light source (PDA for example) that you put inside you backpack, the PDA's light stays at the location even after you move away.

**Comment by Mervill** [comment]
@optimumtact closeable, no longer an issue.
