### ISSUE TITLE
space vines with mutations have incorrect colors and missing description upon spawning

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/tgstation#9585]
Usually, mutated spacevines have a special color and a unique examing description that tells you what type of vine you're looking at.

Seedpacks of mutated vines will correctly store the mutations of the vines but spawning vines with them will result in regular, non mutated looking vines that do not have any special description text, atleast until they mutate naturally again.

Do note that despite being hidden, the mutations still do work correctly.

**Comment by WJohn** [comment]
I'm kind of impressed this situation even came about to have this kind of bug discovered, honestly. This means you'd have to fight off a sufficiently mutated vine species, grab the seed pack, and start the process over again to even notice it, all before the shuttle left and people abandon fighting the vines.

**Comment by Tokiko1** [comment]
You can get kudzu from weed mutations and planting it in dorms, hacking away at the tiles until you get a good mutation is entirely possible.
