### ISSUE TITLE
Explosions no longer produce gibs when destroying someone's body.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#9592]
What it says on the tin. It can gib somebody, but not leave any goopy bits of their remains. Tested with a 3, 5, 9 on 9 people in the thunderdome.

EDIT: You _have_ to be dead for any gibs to be produced, blowing up a living person will not leave behind any remains.

**Comment by Incoming5643** [comment]
it probably is making gibs they just aren't being spared from the explosion anymore

**Comment by WJohn** [comment]
This is definitely still the case. Being gibbed by a microbomb implant will gib you, but being blown up by surrounding explosions will not.

**Comment by phil235** [comment]
I don't think gibs are not produced, they're likely destroyed by the explosion itself.

**Comment by Cyberboss** [comment]
@lzimann What @phil235 said, the second the gibs are dropped they are blown up. Closable

**Comment by Robustin** [comment]
This is one of the hundreds of issues that need to be closed so we can have a manageable list of actual issues.

**Comment by Cyberboss** [comment]
@lzimann @lzimann @lzimann @lzimann @lzimann @lzimann @lzimann

**Comment by lzimann** [comment]
@Cyberboss @Cyberboss @Cyberboss @Cyberboss @Cyberboss @Cyberboss
