### ISSUE TITLE
Pneumatic Cannons fail to fire after firing armed prox. sensor grenades

### ISSUE THREAD

**Issue by Fr4gn0st1c** [tgstation/tgstation#9604]
So I wanted to test to see if a armed prox. sensor grenade would detonate upon being fired and not while moving with it inside the pneumatic cannon, to function as a ghetto RPG

I did the following things:
-made the improvised pneumatic cannon by placing a stack of 25 package wrap, exactly 4 metal, and two pipes from the heaters and coolers in maint. while holding a wrench and an welder(unlit)
-made a water grenade from a single beaker(small) with 50u water , a standard grenade casing made from 1 sheet of metal, an igniter and prox. sensor from Primary Tool Storage vending machine
-filled an oxygen tank(not emergency) to 1013.25 kpa with a white canister full of "Air" mix
-attached the said tank to the pneumatic cannon, and used a wrench on the cannon to change the output to "2"
-armed the earlier mentioned water grenade to 10 seconds, placed it inside the pneumatic cannon, waited well over 10 seconds and took several steps back and forth
-the grenade, as expected, did not 'detonate'. I turned and ran to the Kitchen and fired the cannon into it
-it flew several tiles very quickly and hit the a tile below the table where I aimed and exploded almost so rapidly that I hardly saw a grenade casing, and exploded exactly at the intended target with no grenade casing present where it "landed", as if it exploded instantly on contact.
-i refilled the tank again to 1013.25 and filled it with 3 metal rods(most that would fit), and aimed at windows, did not fire, then at a person, still nothing

**Comment by Incoming5643** [comment]
As I said at the time, there's probably an associated runtime for this.
