### ISSUE TITLE
Cancelled clones do not take oxygen damage if in crit due to clone damage.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#9605]
![](http://i.imgur.com/P1AzeDq.png)

This guy was in crit for over 5 mins, but was not taking oxygen damage at any point. He was a cancelled clone, though I'm not sure why he had taken 10 toxin damage.

**Comment by coiax** [comment]
@WJohn this is due to the large amounts of salbutamol that clones are currently injected with in the pod. When I finish my epic cloning PR, this will be fixed.

**Comment by coiax** [comment]
@WJohn this is no longer the case, because I finished my cloning changes. This can be closed.

**Comment by Cyberboss** [comment]
@lzimann
