### ISSUE TITLE
Bluespace vines are completely unstoppable once they go into space.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#9609]
Vines basically end up filling up the entire z-level and fuck the station completely over.

For something that has the default start time of 20 minutes as a silent event, and is able to be made by players, it shouldn't be able to fuck the station up so easily.

Vines have basically reached the point of a xeno infestiation. Either you manage to cut it off right as they start, or the station is completely and utterly fucked.

Edit: Did some extensive testing on vines. (note. this was with the bluespace vine mutation disabled. keep that in mind. This is without them being able to go through walls.)
-Vines have no maximum amount they can grow. They just slow down after a certain number of tiles.
-The smoke from weedkiller smoke grenades seems to have very limited effect on the vines. Only the explosion does significant damage.
-Not sure if it was the hardened vines, or due to the previous point, but I used multiple weedkiller cluster grenades, with limited effect. Well, they were the only thing that seemed to be able to destroy the fireproof hardened vines.
-Vines are not slowed down at all when spreading on space. Also, one of the mutation colors is black. This makes them an absolute nightmare to get rid of.
-Explosive vines detonate on removal, REGARDLESS of the method used to delete them. Yes, even if admins delete them they still explode.
-Aggressive spreading vines will knock you out for a while if they spread onto the tile you are standing in. They also destroy things similar to how a blob does, breaking consoles and ripping up wires beneath the floor.
-Hardened vines are immune to goats and scythes.

**Comment by Iamgoofball** [comment]
obviously the solution is I get around to making all my fire burny death chems work as vine repellant

**Comment by palpatine213** [comment]
Hardened vines become fireproof and dense, so welders and scythe become useless, and chem smoke weed killer grenades are of limited usefulness. If you can make some sort of chem to counter that, that would be great.

I honsely think Space spreading should be removed. Vines can regrow from a single tile, so missing anything makes all your work in vain. I'm not sure, but it seems Razharas thought that vines were adminspawn only when he made #7688 which would explain how OP it made vines.

**Comment by Iamgoofball** [comment]
>fireproof
>clf3

ha, ha, ha, funny joke right there

i'll do a weedbusters update to the chems sometime

**Comment by Tokiko1** [comment]
Don't vines from a single spawn source stop growing after they reach a certain amount of tiles? Which is what the random event spawns?

**Comment by Lumipharon** [comment]
He did think they were admin only, I told him otherwise, but it got merged anyway.

Spreading high potency kudzu around is honestly the worst grief you can do other then just releasing the singulo - We've had times were admins have spawned dozens of goats and scythes and shit, and it still just fucks the entire station and kills everyone.

**Comment by palpatine213** [comment]
Description updated with observations from testing.

**Comment by Lumipharon** [comment]
Goof nerfed smoke into the ground, so anything that relies on smoke is now effectively useless.
On the flip side, foam grenades are now rediculously OP, and can cover a far, far larger area then a smoke nade.

**Comment by Iamgoofball** [comment]
@Lumipharon smoke nerf getting reverted when freeze ends

**Comment by Dorsisdwarf** [comment]
I think there's an issue for it, so unless its part of one of those bumper bundles you do, you could do it right away.

**Comment by Iamgoofball** [comment]
i've got a PR up that will just need reopened when the freeze ends that has it in it, the biowarfare ~~DLC~~PR

**Comment by Firecage** [comment]
Mmm. Personally the only things I should go is the whole space spreading, and the hardened vines. Especially hardened vines. Normally space vines can be dealt with even if they spread to litterally half the station. But once they mutate into hardened vines and the hardened vines spreads far enough....well, it kinda fucks you over.

**Comment by kyrahabattoir** [comment]
Could make it so it cannot progress more than X tiles away from a solid structure when in space?
