### ISSUE TITLE
Backpack inhand sprites

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#9631]
A few backpack inhand sprites are pretty poorly done, some are outright terrible.

Mime/chemistry/genetics/virology/botany and satchel variations don't have sprites. They could AT LEAST use the default grey backpack inhands.
Industrial backpack right hand back sprite is missing a line of pixels next to the leg, appearing cut off.
Clown backpack inhands are terrible. At most they just shift a few pixels and often not even to the right hand or direction.

**Comment by phil235** [comment]
chem/genetic/science/virology satchels should use the same sprite as the regular chem/science/viro backpack, the color would match.

**Comment by PKPenguin321** [comment]
Valid issue report. Sprite issues are still issues.

**Comment by optimumtact** [comment]
It's not a bug, file it on the feedback forum.

I only want actionable issue reports here

**Comment by PKPenguin321** [comment]
An entire feedback forum for one unintended sprite issue...
Hmmmmmmmm....
