### ISSUE TITLE
You can move the white shuttle despite the console being deleted

### ISSUE THREAD

**Issue by SconesC** [tgstation/tgstation#9646]
The name is a bit unclear, but:
If you have the white shuttle console and you are a silicon, open it, delete the console - You will still be able to fly the ship via that window without the console in existence 

Just kind of a funny bug, RIP the NSS Sunfucker, jerked back and forth by one jerk of a borg for about ten minutes

**Comment by HoaxIT** [comment]
i'm assuming topic isn't doing any extra checks.

**Comment by Miauw62** [comment]
yeah, probably.
this is a qdel issue

**Comment by Firecage** [comment]
Does the same thing happen with the mining shuttle and labor shuttle?

**Comment by Miauw62** [comment]
might happen with a lot of computers. do qdelled computers become unpowered?

**Comment by Firecage** [comment]
Probably not Miauw, since he was still able to pilot the ship, and ship consoles are computers.

**Comment by Jalleo** [comment]
I wonder how many runtimes could occur from doing it on the wrong machines.

**Comment by Fox-McCloud** [comment]
Guessing this has been fixed because of: https://github.com/tgstation/-tg-station/pull/11505

**Comment by Jalleo** [comment]
@duncathan this fixed?

**Comment by Robustin** [comment]
Just tested under the OP's conditions and the white ship would not fly. Were done here boys.

**Comment by Cyberboss** [comment]
@lzimann
