### ISSUE TITLE
Power sinks placed under doors do not give off any light

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#9663]
Pretty much the title. If you put a power sink under a door, it is absolutely undetectable until that door is opened.
This pretty much nullifies the balance that sinks had where they gave off a lot of light and were supposed to be really noticeable.

**Comment by xxalpha** [comment]
I think it's because they're not dense. The only way I can guess to fix this is to make them dense and then you couldn't walk over them but I don't think that's a big problem.

**Comment by Jalleo** [comment]
Could make it so activating it makes it dense.

**Comment by Anonus** [comment]
That, uh, wouldn't actually fix this; you could still get one under a door with sufficient shenanigans, though I wouldn't expect most players to know how.

**Comment by xxalpha** [comment]
How?

**Comment by AlexanderUlanH** [comment]
Put a powersink between two doors and it's undetectable until one of those doors is opened.  I don't see the issue here.
Also, you can interact with a power sink hidden under a door if you know it's there by alt-clicking the door.

**Comment by Dorsisdwarf** [comment]
They still give off light though, even if they're under a door, right? The walls around it light up

**Comment by palpatine213** [comment]
@Dorsisdwarf Nope, they don't give off any light whatsoever, which is the issue.

@AlexanderUlanH There are far less areas that have two doors side by side like that. By putting it under a door, you can place it literally anywhere and it won't be seen unless the door opens. Additionally, players and admins ghosting or anyone with xray vision would be able to see it. If you place it under a door the admin log is the only indicator.

**Comment by Anonus** [comment]
The first way to get it under a door is simple: Make a door on it, or partially deconstruct a door and reconstruct the door on it. The second way is less simple, but can be summed up as wire fuckery.
(the above may not be accurate, I haven't tested how doors interact with suddenly having a dense object under them)

**Comment by AlexanderUlanH** [comment]
There aren't many areas closed off by opaque walls and opaque airlocks, sure.  But there're also not that many opaque airlocks with wires underneath that aren't likely to be tried when everyone's looking for the sink.
If it's not giving off light because there's an airlock on top, though, that's definitely an issue.

**Comment by palpatine213** [comment]
Yeah, not giving off light is the real issue. if they did, the other things would balance out

**Comment by Mysak0CZ** [comment]
I thing, that this is a door bug: why doors close, if there is powersing in middle of them?

**Comment by bgobandit** [comment]
how does this work with glowing

**Comment by Jalleo** [comment]
@MrPerson I believe this bug is still present is that correct?

**Comment by MrPerson** [comment]
How the shit would I know?

**Comment by Shadowlight213** [comment]
Issue seems to be resolved

**Comment by Cyberboss** [comment]
Yeah newlighting fixed it
