### ISSUE TITLE
Pet Collars: No Overlay

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#9673]
When you put a pet collar on a pet, there's no overlay on the mob itself; it doesn't show up, at all.

**Comment by Amnestik** [comment]
You can't remove it either, seeing as it doesn't show up in the mob's strip menu. And putting a hat on Ian renames him, but once you remove the hat he goes back to being called Ian again.

**Comment by Fox-McCloud** [comment]
well, the item isn't mean to show up in the strip menu, AFAIK.

**Comment by Amnestik** [comment]
I know, but it'd be better if it was reusable and only gave the pet the name while equipped.

**Comment by Jordie0608** [comment]
The overlay icons for collars aren't handled all that well and about half of them don't have sprites; Collars are intended to be single use but it wouldn't be that difficult to change that I guess.

**Comment by Fox-McCloud** [comment]
I've not been able to find a single one that works, AFAIK (mob collar sprites).
