### ISSUE TITLE
Blast Shutter Weirdness

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/tgstation#9682]
Interesting fact: Blast shutters don't block whatever's below it, so you can be shocked by doors you physically cannot see or hack.

**Comment by astralenigma** [comment]
Chocking blastshutters. I call it feature specially if used for a brig lockdown.

**Comment by Jalleo** [comment]
I think we could use the same fix from normal shutters on people getting on tables for this.
Also do you mean the blast doors?

**Comment by SconesC** [comment]
blast doors or shutters

**Comment by Dorsisdwarf** [comment]
Shutters

**Comment by bgobandit** [comment]
Fixed by https://github.com/tgstation/tgstation/pull/23697?

@Dorsisdwarf @KorPhaeron
