### ISSUE TITLE
SMES cells sometimes break upon construction.

### ISSUE THREAD

**Issue by Boggart** [tgstation/tgstation#9739]
I've noticed this happening several times with drones fixing the derelict grav gen, but also when players construct a SMES on-station. After construction it will be un-interactable and it's stat var will be 1.

If the var is edited to 0, the SMES functions as expected. (It may have something to do with the step where you add the coils to it for a terminal.)

**Comment by PKPenguin321** [comment]
iirc, this once happened to me with the left SMES in the backup power room (that room cults hide in all the time in chapel maint), on box

**Comment by Core0verload** [comment]
Fixed in #22657.
