### ISSUE TITLE
Socks stick through some shoes

### ISSUE THREAD

**Issue by SconesC** [tgstation/tgstation#9749]
I guess I'll have to make a SOCKBLOCK flag

Happens with socks on jackboots, will test further with other footgear

**Comment by Tokiko1** [comment]
Just fix the sprite instead. Blocking socks from appearing in some shoes will cause issues with the longer ones.

**Comment by CosmicScientist** [comment]
Is this due to a specific sock or shoe? Because sock sprites should probably not be bigger than the foot/leg.
