### ISSUE TITLE
Custom maps: The server freaks out in the absense of a shuttle

### ISSUE THREAD

**Issue by kyrahabattoir** [tgstation/tgstation#9750]
While this is not critical it would be nice if it was handled gracefully. (the server doesn't crash but the console gets spammed)

proc name: Stat (/mob/Stat)
  source file: mob.dm,698
runtime error: Cannot read null.mode
proc name: Stat (/mob/Stat)
  source file: mob.dm,698
runtime error: Cannot read null.mode
proc name: Stat (/mob/Stat)
  source file: mob.dm,698
runtime error: Cannot read null.mode
proc name: check finished (/datum/game_mode/proc/check_finished)
  source file: game_mode.dm,174
runtime error: Cannot read null.mode
proc name: Stat (/mob/Stat)
  source file: mob.dm,698
runtime error: Cannot read null.mode
proc name: Stat (/mob/Stat)
  source file: mob.dm,698
runtime error: Cannot read null.mode
proc name: Stat (/mob/Stat)
  source file: mob.dm,698
runtime error: Cannot read null.mode
proc name: Stat (/mob/Stat)
  source file: mob.dm,698
runtime error: Cannot read null.mode
proc name: check finished (/datum/game_mode/proc/check_finished)
  source file: game_mode.dm,174
runtime error: Cannot read null.mode
proc name: Stat (/mob/Stat)
  source file: mob.dm,698
runtime error: Cannot read null.mode
proc name: Stat (/mob/Stat)
  source file: mob.dm,698
runtime error: Cannot read null.mode
proc name: check finished (/datum/game_mode/proc/check_finished)
  source file: game_mode.dm,174
runtime error: Cannot read null.mode
proc name: Stat (/mob/Stat)
  source file: mob.dm,698
runtime error: Cannot read null.mode
proc name: Stat (/mob/Stat)
  source file: mob.dm,698
runtime error: Cannot read null.mode
proc name: Stat (/mob/Stat)
  source file: mob.dm,698
runtime error: Cannot read null.mode
proc name: check finished (/datum/game_mode/proc/check_finished)
  source file: game_mode.dm,174
runtime error: Cannot read null.mode
proc name: Stat (/mob/Stat)
  source file: mob.dm,698

**Comment by xxalpha** [comment]
What?

**Comment by kyrahabattoir** [comment]
If you don't have a shuttle on your map the server spam those errors.

**Comment by WJohn** [comment]
It's things like this that make me scared of making NOT full stations, perhaps missing a little piece here or there, and then getting a map freakout because it's expected that every single piece is put to use.

**Comment by AlexanderUlanH** [comment]
I'd say it's not really a bug because the round requires a shuttle to work as-is, but it would be a cool feature to make the crew's manual round ender modular, or to have a list of mandatory map bits on the wiki.

**Comment by kyrahabattoir** [comment]
I'm just saying a few checks to gracefully recover (the game doesn't crash, but the server console get spammed) if no shuttle exist would be nice, i basically have to load a centcomm map with my test station to suppress those errors.

**Comment by AlexanderUlanH** [comment]
Go for it :+1:

**Comment by Dorsisdwarf** [comment]
Shuttles now start on the station. @kyrahabattoir does this still happen?
