### ISSUE TITLE
Radios don't pick up megaphone speech

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#9850]
HELP: Tempchar1/(Lord Maximilian) (?) (PP) (VV) (SM) (JMP) (TP) : i discovered a game-dehancing bug, if you use a megaphone to scream into an intercom, it wont broadcast

**Comment by francinum** [comment]
The very important bugs right here.

**Comment by Xhuis** [comment]
This is because megaphones don't use say() but they just produce an audible message.

**Comment by Miauw62** [comment]
REMOVE MEGAPHONES REMOVE
Op 9-jun.-2015 06:27 schreef "Xhuis" <notifications@github.com>:
