### ISSUE TITLE
Defib if emagged and used on a person will permanently make them unable to breathe

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#9873]
What the fuck

**Comment by bgobandit** [comment]
feature

**Comment by phil235** [comment]
Pretty sure this is intended, the defib gives the victim a heart attack.

**Comment by SconesC** [comment]
heart attack

**Comment by PKPenguin321** [comment]
pretty sure it's not permanent, but makes you unable to breathe long enough so that you go into crit
that's what heart attacks do

**Comment by Kromgar** [comment]
I was in  cryo for 10 minutes

**Comment by francinum** [comment]
give them a non-harm defib to fix that I think

**Comment by Iamgoofball** [comment]
@Kromgar You are given a heart attack when an emag defib is used on you.

Stop it with a default defib OR there's a 25% chance a normal electrical shock from a grille or shocked door can stop it

**Comment by Dorsisdwarf** [comment]
@miauw62 This is not a bug. This is an issue report for the "heart attack" feature.
