### ISSUE TITLE
AI Click to Jump error

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/tgstation#9886]
"Target is not on or near any active cameras on the station." is all I get from vast majority of people in the radio, it seems to work one some people at random. Rebooting client may have alleviated the problem but it still existed. I was unable to Click to Jump to a person I was 100% certain I was able to track on camera. By Click to Jump I mean the blue link on AI radio chat which is supposed to jump the camera to the location. Apparently worked fine when Admin took control.

**Comment by GunHog** [comment]
Were there any scripts on the radio? Could your target have had an agent card/digital camo?

**Comment by Marflowerose** [comment]
The targets were most of the crew, only the minority worked. It seemed to favor sec but before booting, I couldn't even jump to my own borg.

**Comment by Marflowerose** [comment]
I was unable to jump to target with the link while I was able to use the more complex method of tracking via camera to jump to person.

**Comment by optimumtact** [comment]
old with no repro
