### ISSUE TITLE
Ascended shadowlings showing up in round-end report as Animal

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#9908]
Like so:

Mime(Bgobandit) as an Animal (body destroyed)

Possibly relevant: The body was destroyed by stepping into a vortex because I am unrobust as fuck

**Comment by RemieRichards** [comment]
this technically isn't a bug, it's a missing feature, they're simple_animals.

**Comment by Miauw62** [comment]
The bug is that gamemode code is shite
Op 11-jun.-2015 23:30 schreef "Remie Richards" <notifications@github.com>:
