### ISSUE TITLE
Too Point-Blank for Point-Blank

### ISSUE THREAD

**Issue by AlexanderUlanH** [tgstation/tgstation#9914]
Shooting someone point-blank on the same tile as you shoots you instead.  Happened on Sibyl with a silenced SABR, and tested on a test server with a taser.

**Comment by SconesC** [comment]
i've reported this before, sometimes 4 pellets hit the target and one hits you (?????)

**Comment by Jordie0608** [comment]
#9266

**Comment by phil235** [comment]
Fixed by me in some PR. Firing point blank no longer puts the projectile on the firer's loc to move them onto the target (like regular projectile movement). Instead we go directly to bullet_act() and deletes the projectile right after.
