### ISSUE TITLE
Anomalies can spawn in maint on the APC

### ISSUE THREAD

**Issue by theOperand** [tgstation/tgstation#9919]
What it says on the tin.
![2015-06-12 15_11_41-sybil_ spess space-hulk iii](https://cloud.githubusercontent.com/assets/3975713/8130744/69daa306-1115-11e5-8cf2-e20f56b143e4.png)

expected location here was Law Office, but its in maint.

**Comment by Ikarrus** [comment]
Do we really need APCs in maint they cause so many problems

**Comment by callanrocks** [comment]
They make maint useful for sabotage and make the wiring neater.

**Comment by xxalpha** [comment]
What's the problem if it spawns in maint? It's part of the station.

**Comment by Dorsisdwarf** [comment]
Most anomalies move through walls anyway

**Comment by Marflowerose** [comment]
I'd call it Works as Intended, the buggy part is the announcement. It should state that it's NEAR the location stated rather than in the room.

**Comment by Strathcona** [comment]
I think "expected location" is vague enough. It's expected but not confirmed.

**Comment by PKPenguin321** [comment]
>I think "expected location" is vague enough. It's expected but not confirmed.

This
This is a non-issue

**Comment by ChangelingRain** [comment]
Difficult to fix and not really that much of an issue
