### ISSUE TITLE
Instant Summons can multiply embedded items

### ISSUE THREAD

**Issue by Madjura** [tgstation/tgstation#9937]
Server revision compiled on: 2015-06-13
cf46c8a8a5089d94acbba928e094aff06cff73cc 

Mark an object that can be embedded for recall (GAR glasses work I think, spears work for sure)
Throw the object at someone and hope it gets stuck in a limb
Recall it
You now have the object in your hand and you can throw it again to get it stuck again, while at the same time it's still stuck in the person
Eventually the object falls out of the limb and you have the one in your hand and the one that fell out + any other that you might have embedded from throwing
Only tested with spears but I am pretty sure it works with all objects that can get stuck in limbs

**Comment by Incoming5643** [comment]
The objects weren't intending to ever move/be deleted while in the limb (though there's a few non wizard related versions of this like the ever hilarious throwing star/C4 combo)

Surprised it actually makes a new version of the item though.

**Comment by phil235** [comment]
Does it really make a new item or does it simply change the item's location w/o updating the embedding system?

**Comment by phil235** [comment]
Do you really end up with two items or is it just a visual illusion?

**Comment by Madjura** [comment]
I could definitely recall the spear, throw it again and get it stuck, the guy I did this to had the same spear stuck in himself 3 times

///
I tried it on a local server (old revision but shouldn't matter)
This is   Tristan Ackerley!
He has a spear   embedded in his chest!
He has a spear   embedded in his head!
He is bleeding!
He is totally catatonic. The stresses of life in deep-space must have been too much for him. Any recovery is unlikely.

![ss13 spear](https://cloud.githubusercontent.com/assets/4841238/8148248/d445a0d6-1293-11e5-81f6-6aed162cbcd8.png)

The second spear disappeared from my hands when I picked it up (the icon) but I could still throw it.
To reproduce: Throw spear at someone until it gets stuck, recall it
Wait until it falls out, pick it up
Throw spear in left hand, switch hand, throw spear in other hand (no icon but sprite holds two spears and you can throw and it can get embedded)
It's not a perfect duplication but you can use the same throwing item twice in quick succession using this
