### ISSUE TITLE
Reanimated Monkey

### ISSUE THREAD

**Issue by Xarvox** [tgstation/tgstation#9941]
I performed an appendectomy on a humanized monkey. It immediately reverted to a monkey, and was very much alive.

**Comment by phil235** [comment]
Cannot reproduce, dead humanized monkey doesn't change when I perform an appendectomy on them. Can we have more details about this?

**Comment by WJohn** [comment]
I can't replicate this. How were they killed? Brute, toxins, suffocation? Did they actually have a bloated appendix? How were they turned into a human?

**Comment by optimumtact** [comment]
old with no repro
