### ISSUE TITLE
Spiderlings don't use the new ventcrawling

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#9985]
So instead of actually moving around the pipes, they just teleport around.
They would have to be changed to not grow in pipes, or simple animals would need to naturally exit pipes so that they wouldn't get stuck, though.
(le feature request)

**Comment by Lumipharon** [comment]
>hundreds of spiders multiplying in the vents
>crawl out of random vents when they're full grown

nope.jpg

On a more practical note, it would make killing them harder, since they'd be crawling around in pipes all day.

**Comment by Anonus** [comment]
Well, the actual spider mobs wouldn't be able to do much in pipes; they can't attack other stuff in pipes so they can't cocoon people and breed in the vents.

**Comment by Jordie0608** [comment]
I'd imagine this is because spiderlings aren't /mobs but /effects so they can't use the code for new ventcrawling.
