### ISSUE TITLE
Reducing View Range: Blind Overlay

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#9988]
If you increase view range, most overlays (flash, etc) scale properly...that said, if you _reduce_ the view range (say from 7 to 6) instead of actually reducing the actual view range (and scaling your image) it just overlays black onto your image.

**Comment by ShizCalev** [comment]
![image](https://user-images.githubusercontent.com/6209658/40852608-f6e4d61a-6598-11e8-9a8d-93c5cbcef72a.png)
update

**Comment by JJRcop** [comment]
Too old

**Comment by FlamingLily** [comment]
Tested, unable to reproduce

**Comment by KittyNoodle** [comment]
@optimumtact this has been fixed for ages can you close thos
